apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edu-app.secretName" . }}
  namespace: {{ include "edu-app.namespace" . }}
  labels:
    {{- include "edu-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
