export type CountryNameSeedItem = {
  nameJa: string;
  kana: string;
  romaji: string;
  meaningVi: string;
  countryCode: string;
};

export type CountryRegionSeed = {
  slug: string;
  label: string;
  items: CountryNameSeedItem[];
};

/** Tên quốc gia phổ biến trong tiếng Nhật — nhóm theo khu vực. */
export const COUNTRY_NAME_REGIONS: CountryRegionSeed[] = [
  {
    slug: 'asia',
    label: 'Châu Á',
    items: [
      { nameJa: '日本', kana: 'にほん', romaji: 'nihon / nippon', meaningVi: 'Nhật Bản', countryCode: 'JP' },
      { nameJa: 'ベトナム', kana: 'ベトナム', romaji: 'betonamu', meaningVi: 'Việt Nam', countryCode: 'VN' },
      { nameJa: '中国', kana: 'ちゅうごく', romaji: 'chuugoku', meaningVi: 'Trung Quốc', countryCode: 'CN' },
      { nameJa: '韓国', kana: 'かんこく', romaji: 'kankoku', meaningVi: 'Hàn Quốc', countryCode: 'KR' },
      { nameJa: '北朝鮮', kana: 'きたちょうせん', romaji: 'kita chousen', meaningVi: 'Triều Tiên', countryCode: 'KP' },
      { nameJa: 'タイ', kana: 'タイ', romaji: 'tai', meaningVi: 'Thái Lan', countryCode: 'TH' },
      { nameJa: 'ラオス', kana: 'ラオス', romaji: 'raosu', meaningVi: 'Lào', countryCode: 'LA' },
      { nameJa: 'カンボジア', kana: 'カンボジア', romaji: 'kanbojia', meaningVi: 'Campuchia', countryCode: 'KH' },
      { nameJa: 'ミャンマー', kana: 'ミャンマー', romaji: 'myanmaa', meaningVi: 'Myanmar', countryCode: 'MM' },
      { nameJa: 'マレーシア', kana: 'マレーシア', romaji: 'mareeshia', meaningVi: 'Malaysia', countryCode: 'MY' },
      { nameJa: 'シンガポール', kana: 'シンガポール', romaji: 'shingapooru', meaningVi: 'Singapore', countryCode: 'SG' },
      { nameJa: 'インドネシア', kana: 'インドネシア', romaji: 'indoneshia', meaningVi: 'Indonesia', countryCode: 'ID' },
      { nameJa: 'フィリピン', kana: 'フィリピン', romaji: 'firipin', meaningVi: 'Philippines', countryCode: 'PH' },
      { nameJa: 'ブルネイ', kana: 'ブルネイ', romaji: 'burunei', meaningVi: 'Brunei', countryCode: 'BN' },
      { nameJa: '東ティモール', kana: 'ひがしティモール', romaji: 'higashi timooru', meaningVi: 'Đông Timor', countryCode: 'TL' },
      { nameJa: 'インド', kana: 'インド', romaji: 'indo', meaningVi: 'Ấn Độ', countryCode: 'IN' },
      { nameJa: 'パキスタン', kana: 'パキスタン', romaji: 'pakisutan', meaningVi: 'Pakistan', countryCode: 'PK' },
      { nameJa: 'バングラデシュ', kana: 'バングラデシュ', romaji: 'banguradeshu', meaningVi: 'Bangladesh', countryCode: 'BD' },
      { nameJa: 'スリランカ', kana: 'スリランカ', romaji: 'suriranka', meaningVi: 'Sri Lanka', countryCode: 'LK' },
      { nameJa: 'ネパール', kana: 'ネパール', romaji: 'nepaaru', meaningVi: 'Nepal', countryCode: 'NP' },
      { nameJa: 'ブータン', kana: 'ブータン', romaji: 'buutan', meaningVi: 'Bhutan', countryCode: 'BT' },
      { nameJa: 'アフガニスタン', kana: 'アフガニスタン', romaji: 'afuganisutan', meaningVi: 'Afghanistan', countryCode: 'AF' },
      { nameJa: 'モンゴル', kana: 'モンゴル', romaji: 'mongoru', meaningVi: 'Mông Cổ', countryCode: 'MN' },
      { nameJa: '台湾', kana: 'たいわん', romaji: 'taiwan', meaningVi: 'Đài Loan', countryCode: 'TW' },
      { nameJa: '香港', kana: 'ほんこん', romaji: 'honkon', meaningVi: 'Hồng Kông', countryCode: 'HK' },
      { nameJa: 'マカオ', kana: 'マカオ', romaji: 'makao', meaningVi: 'Ma Cao', countryCode: 'MO' },
    ],
  },
  {
    slug: 'europe',
    label: 'Châu Âu',
    items: [
      { nameJa: 'イギリス', kana: 'イギリス', romaji: 'igirisu', meaningVi: 'Anh (UK)', countryCode: 'GB' },
      { nameJa: 'アイルランド', kana: 'アイルランド', romaji: 'airurando', meaningVi: 'Ireland', countryCode: 'IE' },
      { nameJa: 'フランス', kana: 'フランス', romaji: 'furansu', meaningVi: 'Pháp', countryCode: 'FR' },
      { nameJa: 'ドイツ', kana: 'ドイツ', romaji: 'doitsu', meaningVi: 'Đức', countryCode: 'DE' },
      { nameJa: 'イタリア', kana: 'イタリア', romaji: 'itaria', meaningVi: 'Ý', countryCode: 'IT' },
      { nameJa: 'スペイン', kana: 'スペイン', romaji: 'supein', meaningVi: 'Tây Ban Nha', countryCode: 'ES' },
      { nameJa: 'ポルトガル', kana: 'ポルトガル', romaji: 'porutogaru', meaningVi: 'Bồ Đào Nha', countryCode: 'PT' },
      { nameJa: 'オランダ', kana: 'オランダ', romaji: 'oranda', meaningVi: 'Hà Lan', countryCode: 'NL' },
      { nameJa: 'ベルギー', kana: 'ベルギー', romaji: 'berugii', meaningVi: 'Bỉ', countryCode: 'BE' },
      { nameJa: 'ルクセンブルク', kana: 'ルクセンブルク', romaji: 'rukusenburuku', meaningVi: 'Luxembourg', countryCode: 'LU' },
      { nameJa: 'スイス', kana: 'スイス', romaji: 'suisu', meaningVi: 'Thụy Sĩ', countryCode: 'CH' },
      { nameJa: 'オーストリア', kana: 'オーストリア', romaji: 'oosutoria', meaningVi: 'Áo', countryCode: 'AT' },
      { nameJa: 'スウェーデン', kana: 'スウェーデン', romaji: 'suweedden', meaningVi: 'Thụy Điển', countryCode: 'SE' },
      { nameJa: 'ノルウェー', kana: 'ノルウェー', romaji: 'noruwee', meaningVi: 'Na Uy', countryCode: 'NO' },
      { nameJa: 'デンマーク', kana: 'デンマーク', romaji: 'denmaaku', meaningVi: 'Đan Mạch', countryCode: 'DK' },
      { nameJa: 'フィンランド', kana: 'フィンランド', romaji: 'finrando', meaningVi: 'Phần Lan', countryCode: 'FI' },
      { nameJa: 'アイスランド', kana: 'アイスランド', romaji: 'aisurando', meaningVi: 'Iceland', countryCode: 'IS' },
      { nameJa: 'ポーランド', kana: 'ポーランド', romaji: 'poorando', meaningVi: 'Ba Lan', countryCode: 'PL' },
      { nameJa: 'チェコ', kana: 'チェコ', romaji: 'cheko', meaningVi: 'Séc', countryCode: 'CZ' },
      { nameJa: 'スロバキア', kana: 'スロバキア', romaji: 'surobakia', meaningVi: 'Slovakia', countryCode: 'SK' },
      { nameJa: 'ハンガリー', kana: 'ハンガリー', romaji: 'hangarii', meaningVi: 'Hungary', countryCode: 'HU' },
      { nameJa: 'ルーマニア', kana: 'ルーマニア', romaji: 'ruumania', meaningVi: 'Romania', countryCode: 'RO' },
      { nameJa: 'ブルガリア', kana: 'ブルガリア', romaji: 'burugaria', meaningVi: 'Bulgaria', countryCode: 'BG' },
      { nameJa: 'ギリシャ', kana: 'ギリシャ', romaji: 'girisha', meaningVi: 'Hy Lạp', countryCode: 'GR' },
      { nameJa: 'クロアチア', kana: 'クロアチア', romaji: 'kuroachia', meaningVi: 'Croatia', countryCode: 'HR' },
      { nameJa: 'セルビア', kana: 'セルビア', romaji: 'serubia', meaningVi: 'Serbia', countryCode: 'RS' },
      { nameJa: 'ウクライナ', kana: 'ウクライナ', romaji: 'ukraina', meaningVi: 'Ukraine', countryCode: 'UA' },
      { nameJa: 'ロシア', kana: 'ロシア', romaji: 'roshia', meaningVi: 'Nga', countryCode: 'RU' },
      { nameJa: 'トルコ', kana: 'トルコ', romaji: 'toruko', meaningVi: 'Thổ Nhĩ Kỳ', countryCode: 'TR' },
    ],
  },
  {
    slug: 'americas',
    label: 'Châu Mỹ',
    items: [
      { nameJa: 'アメリカ', kana: 'アメリカ', romaji: 'amerika', meaningVi: 'Mỹ (Hoa Kỳ)', countryCode: 'US' },
      { nameJa: 'カナダ', kana: 'カナダ', romaji: 'kanada', meaningVi: 'Canada', countryCode: 'CA' },
      { nameJa: 'メキシコ', kana: 'メキシコ', romaji: 'mekishiko', meaningVi: 'Mexico', countryCode: 'MX' },
      { nameJa: 'キューバ', kana: 'キューバ', romaji: 'kyuuba', meaningVi: 'Cuba', countryCode: 'CU' },
      { nameJa: 'ジャマイカ', kana: 'ジャマイカ', romaji: 'jamaika', meaningVi: 'Jamaica', countryCode: 'JM' },
      { nameJa: 'ドミニカ共和国', kana: 'ドミニカきょうわこく', romaji: 'dominika kyouwakoku', meaningVi: 'Cộng hòa Dominica', countryCode: 'DO' },
      { nameJa: 'パナマ', kana: 'パナマ', romaji: 'panama', meaningVi: 'Panama', countryCode: 'PA' },
      { nameJa: 'コスタリカ', kana: 'コスタリカ', romaji: 'kosutarika', meaningVi: 'Costa Rica', countryCode: 'CR' },
      { nameJa: 'ブラジル', kana: 'ブラジル', romaji: 'burajiru', meaningVi: 'Brazil', countryCode: 'BR' },
      { nameJa: 'アルゼンチン', kana: 'アルゼンチン', romaji: 'aruzenchin', meaningVi: 'Argentina', countryCode: 'AR' },
      { nameJa: 'チリ', kana: 'チリ', romaji: 'chiri', meaningVi: 'Chile', countryCode: 'CL' },
      { nameJa: 'ペルー', kana: 'ペルー', romaji: 'peruu', meaningVi: 'Peru', countryCode: 'PE' },
      { nameJa: 'コロンビア', kana: 'コロンビア', romaji: 'koronbia', meaningVi: 'Colombia', countryCode: 'CO' },
      { nameJa: 'ベネズエラ', kana: 'ベネズエラ', romaji: 'benezuera', meaningVi: 'Venezuela', countryCode: 'VE' },
      { nameJa: 'エクアドル', kana: 'エクアドル', romaji: 'ekuadoru', meaningVi: 'Ecuador', countryCode: 'EC' },
      { nameJa: 'ボリビア', kana: 'ボリビア', romaji: 'boribia', meaningVi: 'Bolivia', countryCode: 'BO' },
      { nameJa: 'ウルグアイ', kana: 'ウルグアイ', romaji: 'uruguai', meaningVi: 'Uruguay', countryCode: 'UY' },
      { nameJa: 'パラグアイ', kana: 'パラグアイ', romaji: 'paraguai', meaningVi: 'Paraguay', countryCode: 'PY' },
    ],
  },
  {
    slug: 'oceania',
    label: 'Châu Đại Dương',
    items: [
      { nameJa: 'オーストラリア', kana: 'オーストラリア', romaji: 'oosutoraria', meaningVi: 'Úc', countryCode: 'AU' },
      { nameJa: 'ニュージーランド', kana: 'ニュージーランド', romaji: 'nyuujiirando', meaningVi: 'New Zealand', countryCode: 'NZ' },
      { nameJa: 'フィジー', kana: 'フィジー', romaji: 'fijii', meaningVi: 'Fiji', countryCode: 'FJ' },
      { nameJa: 'パプアニューギニア', kana: 'パプアニューギニア', romaji: 'papua nyuuginia', meaningVi: 'Papua New Guinea', countryCode: 'PG' },
      { nameJa: 'サモア', kana: 'サモア', romaji: 'samoa', meaningVi: 'Samoa', countryCode: 'WS' },
    ],
  },
  {
    slug: 'africa-me',
    label: 'Châu Phi & Trung Đông',
    items: [
      { nameJa: 'エジプト', kana: 'エジプト', romaji: 'ejiputo', meaningVi: 'Ai Cập', countryCode: 'EG' },
      { nameJa: '南アフリカ', kana: 'みなみアフリカ', romaji: 'minami afurika', meaningVi: 'Nam Phi', countryCode: 'ZA' },
      { nameJa: 'ナイジェリア', kana: 'ナイジェリア', romaji: 'naijeria', meaningVi: 'Nigeria', countryCode: 'NG' },
      { nameJa: 'ケニア', kana: 'ケニア', romaji: 'kenia', meaningVi: 'Kenya', countryCode: 'KE' },
      { nameJa: 'タンザニア', kana: 'タンザニア', romaji: 'tanzania', meaningVi: 'Tanzania', countryCode: 'TZ' },
      { nameJa: 'エチオピア', kana: 'エチオピア', romaji: 'echiopia', meaningVi: 'Ethiopia', countryCode: 'ET' },
      { nameJa: 'ガーナ', kana: 'ガーナ', romaji: 'gaana', meaningVi: 'Ghana', countryCode: 'GH' },
      { nameJa: 'モロッコ', kana: 'モロッコ', romaji: 'morokko', meaningVi: 'Ma-rốc', countryCode: 'MA' },
      { nameJa: 'チュニジア', kana: 'チュニジア', romaji: 'chunijia', meaningVi: 'Tunisia', countryCode: 'TN' },
      { nameJa: 'アルジェリア', kana: 'アルジェリア', romaji: 'arujeria', meaningVi: 'Algeria', countryCode: 'DZ' },
      { nameJa: 'サウジアラビア', kana: 'サウジアラビア', romaji: 'sauji arabia', meaningVi: 'Ả Rập Saudi', countryCode: 'SA' },
      { nameJa: 'アラブ首長国連邦', kana: 'アラブしゅちょうこくれんぽう', romaji: 'arabu shuchou-koku renpou', meaningVi: 'UAE', countryCode: 'AE' },
      { nameJa: 'カタール', kana: 'カタール', romaji: 'kataaru', meaningVi: 'Qatar', countryCode: 'QA' },
      { nameJa: 'クウェート', kana: 'クウェート', romaji: 'kuweeto', meaningVi: 'Kuwait', countryCode: 'KW' },
      { nameJa: 'オマーン', kana: 'オマーン', romaji: 'omaan', meaningVi: 'Oman', countryCode: 'OM' },
      { nameJa: 'イスラエル', kana: 'イスラエル', romaji: 'isuraeru', meaningVi: 'Israel', countryCode: 'IL' },
      { nameJa: 'イラン', kana: 'イラン', romaji: 'iran', meaningVi: 'Iran', countryCode: 'IR' },
      { nameJa: 'イラク', kana: 'イラク', romaji: 'iraku', meaningVi: 'Iraq', countryCode: 'IQ' },
      { nameJa: 'ヨルダン', kana: 'ヨルダン', romaji: 'yorudan', meaningVi: 'Jordan', countryCode: 'JO' },
    ],
  },
  {
    slug: 'regions',
    label: 'Châu lục / vùng',
    items: [
      { nameJa: 'アジア', kana: 'アジア', romaji: 'ajia', meaningVi: 'Châu Á', countryCode: 'UN' },
      { nameJa: 'ヨーロッパ', kana: 'ヨーロッパ', romaji: 'yooroppa', meaningVi: 'Châu Âu', countryCode: 'EU' },
      { nameJa: 'アフリカ', kana: 'アフリカ', romaji: 'afurika', meaningVi: 'Châu Phi', countryCode: 'UN' },
      { nameJa: '北アメリカ', kana: 'きたアメリカ', romaji: 'kita amerika', meaningVi: 'Bắc Mỹ', countryCode: 'UN' },
      { nameJa: '南アメリカ', kana: 'みなみアメリカ', romaji: 'minami amerika', meaningVi: 'Nam Mỹ', countryCode: 'UN' },
      { nameJa: 'オセアニア', kana: 'オセアニア', romaji: 'oseania', meaningVi: 'Châu Đại Dương', countryCode: 'UN' },
      { nameJa: '中東', kana: 'ちゅうとう', romaji: 'chuutou', meaningVi: 'Trung Đông', countryCode: 'UN' },
      { nameJa: '東南アジア', kana: 'とうなんアジア', romaji: 'tounan ajia', meaningVi: 'Đông Nam Á', countryCode: 'UN' },
      { nameJa: '東アジア', kana: 'ひがしアジア', romaji: 'higashi ajia', meaningVi: 'Đông Á', countryCode: 'UN' },
      { nameJa: 'ヨーロッパ連合', kana: 'ヨーロッパれんごう', romaji: 'yooroppa rengou', meaningVi: 'Liên minh châu Âu (EU)', countryCode: 'EU' },
    ],
  },
];
