// Từ vựng N2/N1 bổ sung — lesson 406–410 (N2), 505–509 (N1).
// Chạy: npm run seed:jlpt-expand -w @edu/prisma-nihongo

import type { JlptVocabUnit } from './jlpt-vocab.data';
import { JLPT_VOCAB_EXPAND_EXTRA } from './jlpt-vocab-expand-extra.data';
import { JLPT_VOCAB_EXPAND_EXTRA_TAIL } from './jlpt-vocab-expand-extra-tail.data';

const JLPT_VOCAB_EXPAND_BATCH1: JlptVocabUnit[] = [
  {
    lessonNumber: 406,
    jlptLevel: 'N2',
    words: [
      { kanji: '雇用', kana: 'こよう', romaji: 'koyō', meaning: 'tuyển dụng, thuê lao động', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '就職', kana: 'しゅうしょく', romaji: 'shūshoku', meaning: 'nhậm việc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '退職', kana: 'たいしょく', romaji: 'taishoku', meaning: 'nghỉ việc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '転職', kana: 'てんしょく', romaji: 'tenshoku', meaning: 'chuyển việc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '給料', kana: 'きゅうりょう', romaji: 'kyūryō', meaning: 'lương', partOfSpeech: 'danh từ' },
      { kanji: '福利', kana: 'ふくり', romaji: 'fukuri', meaning: 'phúc lợi', partOfSpeech: 'danh từ' },
      { kanji: '待遇', kana: 'たいぐう', romaji: 'taigū', meaning: 'đãi ngộ', partOfSpeech: 'danh từ' },
      { kanji: '昇進', kana: 'しょうしん', romaji: 'shōshin', meaning: 'thăng tiến', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '降格', kana: 'こうかく', romaji: 'kōkaku', meaning: 'hạ cấp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '配属', kana: 'はいぞく', romaji: 'haizoku', meaning: 'phân công, bố trí', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '担当', kana: 'たんとう', romaji: 'tantō', meaning: 'phụ trách', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '責任', kana: 'せきにん', romaji: 'sekinin', meaning: 'trách nhiệm', partOfSpeech: 'danh từ' },
      { kanji: '権限', kana: 'けんげん', romaji: 'kengen', meaning: 'quyền hạn', partOfSpeech: 'danh từ' },
      { kanji: '委任', kana: 'いにん', romaji: 'inin', meaning: 'ủy nhiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '依頼', kana: 'いらい', romaji: 'irai', meaning: 'nhờ vả, yêu cầu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '届ける', kana: 'とどける', romaji: 'todokeru', meaning: 'gửi đến, nộp', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '割合', kana: 'わりあい', romaji: 'wariai', meaning: 'tỷ lệ', partOfSpeech: 'danh từ' },
      { kanji: '倍率', kana: 'ばいりつ', romaji: 'bairitsu', meaning: 'tỷ lệ (gấp bội)', partOfSpeech: 'danh từ' },
      { kanji: '公務員', kana: 'こうむいん', romaji: 'kōmuin', meaning: 'công chức', partOfSpeech: 'danh từ' },
      { kanji: '民間', kana: 'みんかん', romaji: 'minkan', meaning: 'tư nhân, dân sự', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 407,
    jlptLevel: 'N2',
    words: [
      { kanji: '環境', kana: 'かんきょう', romaji: 'kankyō', meaning: 'môi trường', partOfSpeech: 'danh từ' },
      { kanji: '資源', kana: 'しげん', romaji: 'shigen', meaning: 'tài nguyên', partOfSpeech: 'danh từ' },
      { kanji: 'エネルギー', kana: 'エネルギー', romaji: 'enerugī', meaning: 'năng lượng', partOfSpeech: 'danh từ' },
      { kanji: '汚染', kana: 'おせん', romaji: 'osen', meaning: 'ô nhiễm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '公害', kana: 'こうがい', romaji: 'kōgai', meaning: 'ô nhiễm môi trường', partOfSpeech: 'danh từ' },
      { kanji: '危険', kana: 'きけん', romaji: 'kiken', meaning: 'nguy hiểm', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '安全', kana: 'あんぜん', romaji: 'anzen', meaning: 'an toàn', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '保全', kana: 'ほぜん', romaji: 'hozen', meaning: 'bảo toàn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '削減', kana: 'さくげん', romaji: 'sakugen', meaning: 'cắt giảm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '増加', kana: 'ぞうか', romaji: 'zōka', meaning: 'tăng thêm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '温暖化', kana: 'おんだんか', romaji: 'ondanka', meaning: 'nóng lên toàn cầu', partOfSpeech: 'danh từ' },
      { kanji: '再生', kana: 'さいせい', romaji: 'saisei', meaning: 'tái sinh, tái chế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '循環', kana: 'じゅんかん', romaji: 'junkan', meaning: 'tuần hoàn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '統計', kana: 'とうけい', romaji: 'tōkei', meaning: 'thống kê', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '調査', kana: 'ちょうさ', romaji: 'chōsa', meaning: 'điều tra', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '率', kana: 'りつ', romaji: 'ritsu', meaning: 'tỷ lệ', partOfSpeech: 'danh từ' },
      { kanji: '割合', kana: 'わりあい', romaji: 'wariai', meaning: 'tỷ lệ phần trăm', partOfSpeech: 'danh từ' },
      { kanji: '平均', kana: 'へいきん', romaji: 'heikin', meaning: 'trung bình', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '最大', kana: 'さいだい', romaji: 'saidai', meaning: 'lớn nhất', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '最小', kana: 'さいしょう', romaji: 'saishō', meaning: 'nhỏ nhất', partOfSpeech: 'danh từ, tính từ na' },
    ],
  },
  {
    lessonNumber: 408,
    jlptLevel: 'N2',
    words: [
      { kanji: '広告', kana: 'こうこく', romaji: 'kōkoku', meaning: 'quảng cáo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '宣伝', kana: 'せんでん', romaji: 'senden', meaning: 'tuyên truyền', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '掲載', kana: 'けいさい', romaji: 'keisai', meaning: 'đăng tải', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発表', kana: 'はっぴょう', romaji: 'happyō', meaning: 'công bố', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '公開', kana: 'こうかい', romaji: 'kōkai', meaning: 'công khai', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '秘密', kana: 'ひみつ', romaji: 'himitsu', meaning: 'bí mật', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '匿名', kana: 'とくめい', romaji: 'tokumei', meaning: 'ẩn danh', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '漏洩', kana: 'ろうえい', romaji: 'rōei', meaning: 'rò rỉ thông tin', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '暴露', kana: 'ばくろ', romaji: 'bakuro', meaning: 'phơi bày', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '批判', kana: 'ひはん', romaji: 'hihan', meaning: 'phê phán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '評価', kana: 'ひょうか', romaji: 'hyōka', meaning: 'đánh giá', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '論争', kana: 'ろんそう', romaji: 'ronsō', meaning: 'tranh luận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '議論', kana: 'ぎろん', romaji: 'giron', meaning: 'bàn luận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '称賛', kana: 'しょうさん', romaji: 'shōsan', meaning: 'ca ngợi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '非難', kana: 'ひなん', romaji: 'hinan', meaning: 'chỉ trích', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '報道', kana: 'ほうどう', romaji: 'hōdō', meaning: 'đưa tin', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '取材', kana: 'しゅざい', romaji: 'shuzai', meaning: 'phỏng vấn thu thập tin', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '記者', kana: 'きしゃ', romaji: 'kisha', meaning: 'phóng viên', partOfSpeech: 'danh từ' },
      { kanji: '編集', kana: 'へんしゅう', romaji: 'henshū', meaning: 'biên tập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '出版', kana: 'しゅっぱん', romaji: 'shuppan', meaning: 'xuất bản', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 409,
    jlptLevel: 'N2',
    words: [
      { kanji: '法律', kana: 'ほうりつ', romaji: 'hōritsu', meaning: 'pháp luật', partOfSpeech: 'danh từ' },
      { kanji: '条例', kana: 'じょうれい', romaji: 'jōrei', meaning: 'điều lệ', partOfSpeech: 'danh từ' },
      { kanji: '契約', kana: 'けいやく', romaji: 'keiyaku', meaning: 'hợp đồng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '締結', kana: 'ていけつ', romaji: 'teiketsu', meaning: 'ký kết', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '違反', kana: 'いはん', romaji: 'ihan', meaning: 'vi phạm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '罰金', kana: 'ばっきん', romaji: 'bakkin', meaning: 'tiền phạt', partOfSpeech: 'danh từ' },
      { kanji: '刑事', kana: 'けいじ', romaji: 'keiji', meaning: 'hình sự', partOfSpeech: 'danh từ' },
      { kanji: '民事', kana: 'みんじ', romaji: 'minji', meaning: 'dân sự', partOfSpeech: 'danh từ' },
      { kanji: '訴訟', kana: 'そしょう', romaji: 'soshō', meaning: 'kiện tụng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '裁判', kana: 'さいばん', romaji: 'saiban', meaning: 'xét xử', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '判決', kana: 'はんけつ', romaji: 'hanketsu', meaning: 'phán quyết', partOfSpeech: 'danh từ' },
      { kanji: '有罪', kana: 'ゆうざい', romaji: 'yūzai', meaning: 'có tội', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '無罪', kana: 'むざい', romaji: 'muzai', meaning: 'vô tội', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '容疑', kana: 'ようぎ', romaji: 'yōgi', meaning: 'nghi vấn tội phạm', partOfSpeech: 'danh từ' },
      { kanji: '証拠', kana: 'しょうこ', romaji: 'shōko', meaning: 'bằng chứng', partOfSpeech: 'danh từ' },
      { kanji: '弁護', kana: 'べんご', romaji: 'bengo', meaning: 'biện hộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '補償', kana: 'ほしょう', romaji: 'hoshō', meaning: 'bồi thường', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '賠償', kana: 'ばいしょう', romaji: 'baishō', meaning: 'đền bù', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '権利', kana: 'けんり', romaji: 'kenri', meaning: 'quyền lợi', partOfSpeech: 'danh từ' },
      { kanji: '義務', kana: 'ぎむ', romaji: 'gimu', meaning: 'nghĩa vụ', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 410,
    jlptLevel: 'N2',
    words: [
      { kanji: '領域', kana: 'りょういき', romaji: 'ryōiki', meaning: 'lĩnh vực', partOfSpeech: 'danh từ' },
      { kanji: '範囲', kana: 'はんい', romaji: 'han\'i', meaning: 'phạm vi', partOfSpeech: 'danh từ' },
      { kanji: '区分', kana: 'くぶん', romaji: 'kubun', meaning: 'phân loại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '分類', kana: 'ぶんるい', romaji: 'bunrui', meaning: 'phân loại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '特徴', kana: 'とくちょう', romaji: 'tokuchō', meaning: 'đặc trưng', partOfSpeech: 'danh từ' },
      { kanji: '特色', kana: 'とくしょく', romaji: 'tokushoku', meaning: 'đặc sắc', partOfSpeech: 'danh từ' },
      { kanji: '性質', kana: 'せいしつ', romaji: 'seishitsu', meaning: 'tính chất', partOfSpeech: 'danh từ' },
      { kanji: '量', kana: 'りょう', romaji: 'ryō', meaning: 'số lượng', partOfSpeech: 'danh từ' },
      { kanji: '程度', kana: 'ていど', romaji: 'teido', meaning: 'mức độ', partOfSpeech: 'danh từ' },
      { kanji: '段階', kana: 'だんかい', romaji: 'dankai', meaning: 'giai đoạn', partOfSpeech: 'danh từ' },
      { kanji: '構造', kana: 'こうぞう', romaji: 'kōzō', meaning: 'cấu trúc', partOfSpeech: 'danh từ' },
      { kanji: '組織', kana: 'そしき', romaji: 'soshiki', meaning: 'tổ chức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '編成', kana: 'へんせい', romaji: 'hensei', meaning: 'biên chế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '整理', kana: 'せいり', romaji: 'seiri', meaning: 'sắp xếp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '改善', kana: 'かいぜん', romaji: 'kaizen', meaning: 'cải thiện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '改革', kana: 'かいかく', romaji: 'kaikaku', meaning: 'cải cách', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '善', kana: 'ぜん', romaji: 'zen', meaning: 'thiện, tốt', partOfSpeech: 'danh từ' },
      { kanji: '悪', kana: 'あく', romaji: 'aku', meaning: 'ác, xấu', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '区別', kana: 'くべつ', romaji: 'kubetsu', meaning: 'phân biệt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '共通', kana: 'きょうつう', romaji: 'kyōtsū', meaning: 'chung', partOfSpeech: 'danh từ, tính từ na' },
    ],
  },

  // ─── N1 ───
  {
    lessonNumber: 505,
    jlptLevel: 'N1',
    words: [
      { kanji: '損失', kana: 'そんしつ', romaji: 'sonshitsu', meaning: 'tổn thất', partOfSpeech: 'danh từ' },
      { kanji: '利益', kana: 'りえき', romaji: 'rieki', meaning: 'lợi nhuận', partOfSpeech: 'danh từ' },
      { kanji: '収支', kana: 'しゅうし', romaji: 'shūshi', meaning: 'thu chi', partOfSpeech: 'danh từ' },
      { kanji: '赤字', kana: 'あかじ', romaji: 'akaji', meaning: 'lỗ, thâm hụt', partOfSpeech: 'danh từ' },
      { kanji: '黒字', kana: 'くろじ', romaji: 'kuroji', meaning: 'lãi, thặng dư', partOfSpeech: 'danh từ' },
      { kanji: '余剰', kana: 'よじょう', romaji: 'yojō', meaning: 'dư thừa', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '欠乏', kana: 'けつぼう', romaji: 'ketsubō', meaning: 'thiếu hụt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '富裕', kana: 'ふゆう', romaji: 'fuyū', meaning: 'giàu có', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '貧困', kana: 'ひんこん', romaji: 'hinkon', meaning: 'nghèo đói', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '圧迫', kana: 'あっぱく', romaji: 'appaku', meaning: 'áp bức, ép buộc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '逼迫', kana: 'はっぱく', romaji: 'happaku', meaning: 'bức bách', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '急務', kana: 'きゅうむ', romaji: 'kyūmu', meaning: 'việc cấp bách', partOfSpeech: 'danh từ' },
      { kanji: '励ます', kana: 'はげます', romaji: 'hagemasu', meaning: 'khích lệ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '促す', kana: 'うながす', romaji: 'unagasu', meaning: 'thúc giục', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '控える', kana: 'ひかえる', romaji: 'hikaeru', meaning: 'kiềm chế, tạm hoãn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '充実', kana: 'じゅうじつ', romaji: 'jūjitsu', meaning: 'phong phú, đầy đủ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '満足', kana: 'まんぞく', romaji: 'manzoku', meaning: 'hài lòng', partOfSpeech: 'danh từ, động từ する, tính từ na' },
      { kanji: '不足', kana: 'ふそく', romaji: 'fusoku', meaning: 'thiếu sót', partOfSpeech: 'danh từ, động từ する, tính từ na' },
      { kanji: '剰余', kana: 'じょうよ', romaji: 'jōyo', meaning: 'dư thừa (toán học)', partOfSpeech: 'danh từ' },
      { kanji: '経済的', kana: 'けいざいてき', romaji: 'keizaiteki', meaning: 'mang tính kinh tế', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 506,
    jlptLevel: 'N1',
    words: [
      { kanji: '分析', kana: 'ぶんせき', romaji: 'bunseki', meaning: 'phân tích', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '総合', kana: 'そうごう', romaji: 'sōgō', meaning: 'tổng hợp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '推測', kana: 'すいそく', romaji: 'suisoku', meaning: 'suy đoán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '測定', kana: 'そくてい', romaji: 'sokutei', meaning: 'đo lường', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '算出', kana: 'さんしゅつ', romaji: 'sanshutsu', meaning: 'tính toán ra', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '観察', kana: 'かんさつ', romaji: 'kansatsu', meaning: 'quan sát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '監視', kana: 'かんし', romaji: 'kanshi', meaning: 'giám sát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '診断', kana: 'しんだん', romaji: 'shindan', meaning: 'chẩn đoán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '探究', kana: 'たんきゅう', romaji: 'tankyū', meaning: 'thám hiểm, nghiên cứu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '精査', kana: 'せいさ', romaji: 'seisa', meaning: 'điều tra kỹ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '精緻', kana: 'せいち', romaji: 'seichi', meaning: 'tinh vi, tỉ mỉ', partOfSpeech: 'tính từ na' },
      { kanji: '記憶', kana: 'きおく', romaji: 'kioku', meaning: 'ký ức', partOfSpeech: 'danh từ' },
      { kanji: '悟る', kana: 'さとる', romaji: 'satoru', meaning: 'giác ngộ, nhận ra', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '領会', kana: 'りょうかい', romaji: 'ryōkai', meaning: 'lĩnh hội', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '洞察', kana: 'どうさつ', romaji: 'dōsatsu', meaning: 'động sát, thấu hiểu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '見解', kana: 'けんかい', romaji: 'kenkai', meaning: 'quan điểm', partOfSpeech: 'danh từ' },
      { kanji: '視点', kana: 'してん', romaji: 'shiten', meaning: 'góc nhìn', partOfSpeech: 'danh từ' },
      { kanji: '着眼', kana: 'ちゃくがん', romaji: 'chakugan', meaning: 'để mắt tới', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '焦点', kana: 'しょうてん', romaji: 'shōten', meaning: 'tiêu điểm', partOfSpeech: 'danh từ' },
      { kanji: '核心', kana: 'かくしん', romaji: 'kakushin', meaning: 'cốt lõi', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 507,
    jlptLevel: 'N1',
    words: [
      { kanji: '風習', kana: 'ふうしゅう', romaji: 'fūshū', meaning: 'phong tục tập quán', partOfSpeech: 'danh từ' },
      { kanji: '慣習', kana: 'かんしゅう', romaji: 'kanshū', meaning: 'tập quán', partOfSpeech: 'danh từ' },
      { kanji: '儀式', kana: 'ぎしき', romaji: 'gishiki', meaning: 'nghi lễ', partOfSpeech: 'danh từ' },
      { kanji: '礼儀', kana: 'れいぎ', romaji: 'reigi', meaning: 'lễ nghi', partOfSpeech: 'danh từ' },
      { kanji: '敬意', kana: 'けいい', romaji: 'keii', meaning: 'sự kính trọng', partOfSpeech: 'danh từ' },
      { kanji: '謙虚', kana: 'けんきょ', romaji: 'kenkyo', meaning: 'khiêm tốn', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '誠実', kana: 'せいじつ', romaji: 'seijitsu', meaning: 'chân thành', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '偽善', kana: 'ぎぜん', romaji: 'gizen', meaning: 'đạo đức giả', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '詐欺', kana: 'さぎ', romaji: 'sagi', meaning: 'lừa đảo', partOfSpeech: 'danh từ' },
      { kanji: '裏切り', kana: 'うらぎり', romaji: 'uragiri', meaning: 'sự phản bội', partOfSpeech: 'danh từ' },
      { kanji: '血筋', kana: 'ちすじ', romaji: 'chisuji', meaning: 'dòng máu, gia đình', partOfSpeech: 'danh từ' },
      { kanji: '一族', kana: 'いちぞく', romaji: 'ichizoku', meaning: 'cả họ', partOfSpeech: 'danh từ' },
      { kanji: '戸籍', kana: 'こせき', romaji: 'koseki', meaning: 'hộ tịch', partOfSpeech: 'danh từ' },
      { kanji: '大衆', kana: 'たいしゅう', romaji: 'taishū', meaning: 'đại chúng', partOfSpeech: 'danh từ' },
      { kanji: '群衆', kana: 'ぐんしゅう', romaji: 'gunshū', meaning: 'đám đông', partOfSpeech: 'danh từ' },
      { kanji: '集団', kana: 'しゅうだん', romaji: 'shūdan', meaning: 'tập thể', partOfSpeech: 'danh từ' },
      { kanji: '協調', kana: 'きょうちょう', romaji: 'kyōchō', meaning: 'hợp tác, phối hợp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '同調', kana: 'どうちょう', romaji: 'dōchō', meaning: 'đồng điệu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '異質', kana: 'いしつ', romaji: 'ishitsu', meaning: 'khác biệt về bản chất', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '独自', kana: 'どくじ', romaji: 'dokuji', meaning: 'độc lập, riêng', partOfSpeech: 'tính từ na, danh từ' },
    ],
  },
  {
    lessonNumber: 508,
    jlptLevel: 'N1',
    words: [
      { kanji: '哲学', kana: 'てつがく', romaji: 'tetsugaku', meaning: 'triết học', partOfSpeech: 'danh từ' },
      { kanji: '深奥', kana: 'しんおう', romaji: 'shin\'ō', meaning: 'huyền sâu', partOfSpeech: 'tính từ na' },
      { kanji: '深遠', kana: 'しんえん', romaji: 'shin\'en', meaning: 'sâu xa', partOfSpeech: 'tính từ na' },
      { kanji: '浅はか', kana: 'あさはか', romaji: 'asahaka', meaning: 'nông cạn, hời hợt', partOfSpeech: 'tính từ na' },
      { kanji: '狭量', kana: 'きょうりょう', romaji: 'kyōryō', meaning: 'hẹp hòi (lòng dạ)', partOfSpeech: 'tính từ na' },
      { kanji: '遠隔', kana: 'えんかく', romaji: 'enkaku', meaning: 'từ xa', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '近隣', kana: 'きんりん', romaji: 'kinrin', meaning: 'hàng xóm, lân cận', partOfSpeech: 'danh từ' },
      { kanji: '恒久', kana: 'こうきゅう', romaji: 'kōkyū', meaning: 'vĩnh cửu', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '永続', kana: 'えいぞく', romaji: 'eizoku', meaning: 'bền vững', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '暫定', kana: 'ざんてい', romaji: 'zantei', meaning: 'tạm thời', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '瞬間', kana: 'しゅんかん', romaji: 'shunkan', meaning: 'khoảnh khắc', partOfSpeech: 'danh từ' },
      { kanji: '即座', kana: 'そくざ', romaji: 'sokuza', meaning: 'ngay lập tức', partOfSpeech: 'phó từ' },
      { kanji: '既成', kana: 'きせい', romaji: 'kisei', meaning: 'đã hình thành sẵn', partOfSpeech: 'tính từ na' },
      { kanji: '未熟', kana: 'みじゅく', romaji: 'mijuku', meaning: 'non nớt, chưa thành thục', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '曾て', kana: 'かつて', romaji: 'katsute', meaning: 'từng, ngày xưa', partOfSpeech: 'phó từ' },
      { kanji: '根源', kana: 'こんげん', romaji: 'kongen', meaning: 'cội nguồn', partOfSpeech: 'danh từ' },
      { kanji: '根本', kana: 'こんぽん', romaji: 'konpon', meaning: 'căn bản', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '末端', kana: 'まったん', romaji: 'mattan', meaning: 'đầu cuối, tận cùng', partOfSpeech: 'danh từ' },
      { kanji: '端緒', kana: 'たんしょ', romaji: 'tansho', meaning: 'manh mối, khởi đầu', partOfSpeech: 'danh từ' },
      { kanji: '始末', kana: 'しまつ', romaji: 'shimatsu', meaning: 'kết cục; xử lý', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 509,
    jlptLevel: 'N1',
    words: [
      { kanji: '覆す', kana: 'くつがえす', romaji: 'kutsugaesu', meaning: 'lật đổ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '貯蓄', kana: 'ちょちく', romaji: 'chochiku', meaning: 'tiết kiệm, tích lũy', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '浸す', kana: 'ひたす', romaji: 'hitasu', meaning: 'ngâm', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '溶解', kana: 'ようかい', romaji: 'yōkai', meaning: 'hòa tan', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '融合', kana: 'ゆうごう', romaji: 'yūgō', meaning: 'hòa nhập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '混合', kana: 'こんごう', romaji: 'kongō', meaning: 'trộn lẫn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '純粋', kana: 'じゅんすい', romaji: 'junsui', meaning: 'thuần khiết', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '希少', kana: 'きしょう', romaji: 'kishō', meaning: 'hiếm', partOfSpeech: 'tính từ na' },
      { kanji: '膨張', kana: 'ぼうちょう', romaji: 'bōchō', meaning: 'phồng lên', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '収縮', kana: 'しゅうしゅく', romaji: 'shūshuku', meaning: 'co lại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '緻密', kana: 'ちみつ', romaji: 'chimitsu', meaning: 'tỉ mỉ, chặt chẽ', partOfSpeech: 'tính từ na' },
      { kanji: '粗雑', kana: 'そざつ', romaji: 'sozatsu', meaning: 'thô sơ, cẩu thả', partOfSpeech: 'tính từ na' },
      { kanji: '複合', kana: 'ふくごう', romaji: 'fukugō', meaning: 'phức hợp', partOfSpeech: 'danh từ, động từ する, tính từ na' },
      { kanji: '簡素', kana: 'かんそ', romaji: 'kanso', meaning: 'giản dị', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '詳細', kana: 'しょうさい', romaji: 'shōsai', meaning: 'chi tiết', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '細部', kana: 'さいぶ', romaji: 'saibu', meaning: 'chi tiết nhỏ', partOfSpeech: 'danh từ' },
      { kanji: '緩慢', kana: 'かんまん', romaji: 'kanman', meaning: 'chậm chạp', partOfSpeech: 'tính từ na' },
      { kanji: '濁る', kana: 'にごる', romaji: 'nigoru', meaning: 'đục, trở nên trần tục', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '雑然', kana: 'ざつぜん', romaji: 'zatsuzen', meaning: 'lộn xộn', partOfSpeech: 'tính từ na' },
      { kanji: '物質', kana: 'ぶっしつ', romaji: 'busshitsu', meaning: 'vật chất', partOfSpeech: 'danh từ' },
    ],
  },
];

/** Batch 1 (406–410, 505–509) + batch 2 (N5–N1 bổ sung). */
export const JLPT_VOCAB_EXPAND: JlptVocabUnit[] = [
  ...JLPT_VOCAB_EXPAND_BATCH1,
  ...JLPT_VOCAB_EXPAND_EXTRA,
  ...JLPT_VOCAB_EXPAND_EXTRA_TAIL,
];
