// Kanji N2/N1 bổ sung — lesson 405–409 (N2), 504–508 (N1).
// Chạy: npm run seed:jlpt-expand -w @edu/prisma-nihongo

import type { JlptKanjiLesson } from './jlpt-kanji.data';

export const JLPT_KANJI_EXPAND: JlptKanjiLesson[] = [
  {
    lessonNumber: 405,
    jlptLevel: 'N2',
    title: 'Bài 40 · Kanji N2 (5) — Giáo dục, công việc',
    sortOrder: 4050,
    entries: [
      { character: '育', hanViet: 'DỤC', onyomi: 'いく', kunyomi: 'そだ-つ, そだ-てる', meaningVi: 'nuôi dưỡng, giáo dục', strokeCount: 8 },
      { character: '教', hanViet: 'GIÁO', onyomi: 'きょう', kunyomi: 'おし-える, おそ-わる', meaningVi: 'dạy, học', strokeCount: 11 },
      { character: '養', hanViet: 'DƯỠNG', onyomi: 'よう', kunyomi: 'やしな-う', meaningVi: 'nuôi dưỡng, bồi dưỡng', strokeCount: 15 },
      { character: '就', hanViet: 'TỰU', onyomi: 'しゅう, じゅ', kunyomi: 'つ-く', meaningVi: 'nhậm chức, bắt đầu làm việc', strokeCount: 12 },
      { character: '配', hanViet: 'PHỐI', onyomi: 'はい', kunyomi: 'くば-る', meaningVi: 'phân phối, sắp xếp', strokeCount: 10 },
      { character: '属', hanViet: 'THUỘC', onyomi: 'ぞく', meaningVi: 'thuộc về, thuộc hạ', strokeCount: 12 },
      { character: '署', hanViet: 'THỰ', onyomi: 'しょ', meaningVi: 'cơ quan, sở', strokeCount: 13 },
      { character: '官', hanViet: 'QUAN', onyomi: 'かん', meaningVi: 'quan chức, cơ quan', strokeCount: 8 },
      { character: '公', hanViet: 'CÔNG', onyomi: 'こう', kunyomi: 'おおやけ', meaningVi: 'công cộng', strokeCount: 4 },
      { character: '私', hanViet: 'TƯ', onyomi: 'し', kunyomi: 'わたし', meaningVi: 'cá nhân, riêng tư', strokeCount: 7 },
      { character: '委', hanViet: 'ỦY', onyomi: 'い', kunyomi: 'ゆだ-ねる', meaningVi: 'ủy thác, ủy ban', strokeCount: 8 },
      { character: '託', hanViet: 'THÁC', onyomi: 'たく', meaningVi: 'giao phó', strokeCount: 10 },
      { character: '依', hanViet: 'Y', onyomi: 'い, え', kunyomi: 'よ-る', meaningVi: 'dựa vào, nhờ cậy', strokeCount: 8 },
      { character: '頼', hanViet: 'LẠI', onyomi: 'らい', kunyomi: 'たの-む, たよ-る', meaningVi: 'nhờ vả, tin cậy', strokeCount: 16 },
      { character: '求', hanViet: 'CẦU', onyomi: 'きゅう', kunyomi: 'もと-める', meaningVi: 'yêu cầu, tìm kiếm', strokeCount: 7 },
      { character: '供', hanViet: 'CÚNG', onyomi: 'きょう, く', kunyomi: 'そな-える', meaningVi: 'cung cấp', strokeCount: 8 },
      { character: '給', hanViet: 'CẤP', onyomi: 'きゅう', kunyomi: 'たま-う', meaningVi: 'cấp, trả lương', strokeCount: 12 },
      { character: '届', hanViet: 'GIỚI', onyomi: 'かい', kunyomi: 'とど-ける, とど-く', meaningVi: 'gửi đến; đến nơi', strokeCount: 8 },
      { character: '倍', hanViet: 'BỘI', onyomi: 'ばい', meaningVi: 'gấp đôi, lần', strokeCount: 10 },
      { character: '割', hanViet: 'CÁT', onyomi: 'かつ', kunyomi: 'わ-る, わ-り', meaningVi: 'chia, tỷ lệ', strokeCount: 12 },
    ],
  },
  {
    lessonNumber: 406,
    jlptLevel: 'N2',
    title: 'Bài 41 · Kanji N2 (6) — Thống kê, môi trường',
    sortOrder: 4060,
    entries: [
      { character: '率', hanViet: 'SUẤT', onyomi: 'りつ', kunyomi: 'ひき-いる', meaningVi: 'tỷ lệ; dẫn dắt', strokeCount: 11 },
      { character: '統', hanViet: 'THỐNG', onyomi: 'とう', meaningVi: 'thống nhất, thống kê', strokeCount: 12 },
      { character: '計', hanViet: 'KẾ', onyomi: 'けい', kunyomi: 'はか-る', meaningVi: 'kế hoạch, tính toán', strokeCount: 9 },
      { character: '環', hanViet: 'HOÀN', onyomi: 'かん', meaningVi: 'vòng tròn; môi trường', strokeCount: 17 },
      { character: '境', hanViet: 'CẢNH', onyomi: 'きょう', kunyomi: 'さかい', meaningVi: 'biên giới; hoàn cảnh', strokeCount: 14 },
      { character: '資', hanViet: 'TƯ', onyomi: 'し', meaningVi: 'tài nguyên, vốn', strokeCount: 13 },
      { character: '源', hanViet: 'NGUYÊN', onyomi: 'げん', kunyomi: 'みなもと', meaningVi: 'nguồn, gốc', strokeCount: 13 },
      { character: '汚', hanViet: 'Ô', onyomi: 'お', kunyomi: 'よご-す, よご-れる', meaningVi: 'bẩn, ô nhiễm', strokeCount: 6 },
      { character: '染', hanViet: 'NHIỄM', onyomi: 'せん', kunyomi: 'そ-める, し-みる', meaningVi: 'nhuộm; nhiễm', strokeCount: 9 },
      { character: '害', hanViet: 'HẠI', onyomi: 'がい', meaningVi: 'tổn hại', strokeCount: 10 },
      { character: '危', hanViet: 'NGUY', onyomi: 'き', kunyomi: 'あぶ-ない', meaningVi: 'nguy hiểm', strokeCount: 6 },
      { character: '険', hanViet: 'HIỂM', onyomi: 'けん', kunyomi: 'けわ-しい', meaningVi: 'hiểm trở', strokeCount: 11 },
      { character: '安', hanViet: 'AN', onyomi: 'あん', kunyomi: 'やす-い', meaningVi: 'an toàn; rẻ', strokeCount: 6 },
      { character: '全', hanViet: 'TOÀN', onyomi: 'ぜん', kunyomi: 'まった-く', meaningVi: 'toàn bộ', strokeCount: 6 },
      { character: '保', hanViet: 'BẢO', onyomi: 'ほ', kunyomi: 'たも-つ', meaningVi: 'bảo vệ, duy trì', strokeCount: 9 },
      { character: '減', hanViet: 'GIẢM', onyomi: 'げん', kunyomi: 'へ-る, へ-らす', meaningVi: 'giảm bớt', strokeCount: 12 },
      { character: '少', hanViet: 'THIỂU', onyomi: 'しょう', kunyomi: 'すく-ない, すこ-し', meaningVi: 'ít', strokeCount: 4 },
      { character: '加', hanViet: 'GIA', onyomi: 'か', kunyomi: 'くわ-える', meaningVi: 'cộng thêm', strokeCount: 5 },
      { character: '温', hanViet: 'ÔN', onyomi: 'おん', kunyomi: 'あたた-か, あたた-める', meaningVi: 'ấm', strokeCount: 12 },
      { character: '暖', hanViet: 'NOÃN', onyomi: 'だん', kunyomi: 'あたた-か, あたた-める', meaningVi: 'ấm áp', strokeCount: 13 },
    ],
  },
  {
    lessonNumber: 407,
    jlptLevel: 'N2',
    title: 'Bài 42 · Kanji N2 (7) — Truyền thông, công bố',
    sortOrder: 4070,
    entries: [
      { character: '宣', hanViet: 'TUYÊN', onyomi: 'せん', meaningVi: 'tuyên bố', strokeCount: 9 },
      { character: '伝', hanViet: 'TRUYỀN', onyomi: 'でん', kunyomi: 'つた-える, つた-わる', meaningVi: 'truyền đạt', strokeCount: 6 },
      { character: '広', hanViet: 'QUẢNG', onyomi: 'こう', kunyomi: 'ひろ-い, ひろ-める', meaningVi: 'rộng, quảng cáo', strokeCount: 5 },
      { character: '掲', hanViet: 'KHẢI', onyomi: 'けい', kunyomi: 'かか-げる', meaningVi: 'treo, đăng tải', strokeCount: 11 },
      { character: '載', hanViet: 'TÁI', onyomi: 'さい', kunyomi: 'の-せる, の-る', meaningVi: 'chở, đăng tải', strokeCount: 10 },
      { character: '発', hanViet: 'PHÁT', onyomi: 'はつ', kunyomi: 'た-つ', meaningVi: 'phát sinh, công bố', strokeCount: 9 },
      { character: '表', hanViet: 'BIỂU', onyomi: 'ひょう', kunyomi: 'あらわ-す', meaningVi: 'biểu hiện', strokeCount: 8 },
      { character: '開', hanViet: 'KHAI', onyomi: 'かい', kunyomi: 'ひら-く, あ-く', meaningVi: 'mở', strokeCount: 12 },
      { character: '秘', hanViet: 'BÍ', onyomi: 'ひ', kunyomi: 'ひ-める', meaningVi: 'bí mật', strokeCount: 10 },
      { character: '密', hanViet: 'MẬT', onyomi: 'みつ', meaningVi: 'mật mị', strokeCount: 11 },
      { character: '匿', hanViet: 'NẤP', onyomi: 'とく', meaningVi: 'ẩn náu', strokeCount: 10 },
      { character: '称', hanViet: 'XƯNG', onyomi: 'しょう', kunyomi: 'とな-える', meaningVi: 'xưng hô; ca ngợi', strokeCount: 10 },
      { character: '呼', hanViet: 'HỐ', onyomi: 'こ', kunyomi: 'よ-ぶ', meaningVi: 'gọi', strokeCount: 8 },
      { character: '漏', hanViet: 'LẬU', onyomi: 'ろう', kunyomi: 'も-れる, も-らす', meaningVi: 'rò rỉ, lộ', strokeCount: 14 },
      { character: '洩', hanViet: 'TIẾT', onyomi: 'せつ', kunyomi: 'も-れる', meaningVi: 'tiết lộ', strokeCount: 9 },
      { character: '暴', hanViet: 'BẠO', onyomi: 'ぼう', kunyomi: 'あば-く, あば-れる', meaningVi: 'bạo lực; phơi bày', strokeCount: 15 },
      { character: '露', hanViet: 'LỘ', onyomi: 'ろ', kunyomi: 'つゆ', meaningVi: 'lộ ra; sương', strokeCount: 21 },
      { character: '批', hanViet: 'PHÊ', onyomi: 'ひ', meaningVi: 'phê phán', strokeCount: 7 },
      { character: '評', hanViet: 'BÌNH', onyomi: 'ひょう', meaningVi: 'bình luận', strokeCount: 12 },
      { character: '論', hanViet: 'LUẬN', onyomi: 'ろん', meaningVi: 'luận, bàn luận', strokeCount: 15 },
    ],
  },
  {
    lessonNumber: 408,
    jlptLevel: 'N2',
    title: 'Bài 43 · Kanji N2 (8) — Pháp luật, hợp đồng',
    sortOrder: 4080,
    entries: [
      { character: '法', hanViet: 'PHÁP', onyomi: 'ほう', kunyomi: 'のり', meaningVi: 'pháp luật', strokeCount: 8 },
      { character: '条', hanViet: 'ĐIỀU', onyomi: 'じょう', meaningVi: 'điều khoản', strokeCount: 7 },
      { character: '約', hanViet: 'ƯỚC', onyomi: 'やく', meaningVi: 'hẹn ước', strokeCount: 9 },
      { character: '契', hanViet: 'KHẾ', onyomi: 'けい', meaningVi: 'hợp đồng', strokeCount: 9 },
      { character: '締', hanViet: 'ĐẾ', onyomi: 'てい', kunyomi: 'し-める', meaningVi: 'ký kết', strokeCount: 15 },
      { character: '違', hanViet: 'VI', onyomi: 'い', kunyomi: 'ちが-う', meaningVi: 'vi phạm, khác', strokeCount: 13 },
      { character: '反', hanViet: 'PHẢN', onyomi: 'はん', kunyomi: 'そ-る', meaningVi: 'phản đối', strokeCount: 4 },
      { character: '罰', hanViet: 'PHẠT', onyomi: 'ばつ', meaningVi: 'hình phạt', strokeCount: 14 },
      { character: '刑', hanViet: 'HÌNH', onyomi: 'けい', meaningVi: 'hình phạt', strokeCount: 6 },
      { character: '訴', hanViet: 'TỐ', onyomi: 'そ', kunyomi: 'うった-える', meaningVi: 'khởi kiện', strokeCount: 12 },
      { character: '訟', hanViet: 'TỤNG', onyomi: 'しょう', meaningVi: 'kiện tụng', strokeCount: 11 },
      { character: '裁', hanViet: 'TÀI', onyomi: 'さい', kunyomi: 'さば-く', meaningVi: 'xét xử', strokeCount: 12 },
      { character: '件', hanViet: 'KIỆN', onyomi: 'けん', meaningVi: 'sự việc, vụ án', strokeCount: 6 },
      { character: '罪', hanViet: 'TỘI', onyomi: 'ざい', meaningVi: 'tội lỗi', strokeCount: 13 },
      { character: '犯', hanViet: 'PHẠM', onyomi: 'はん', kunyomi: 'おか-す', meaningVi: 'phạm tội', strokeCount: 5 },
      { character: '疑', hanViet: 'NGHI', onyomi: 'ぎ', kunyomi: 'うたが-う', meaningVi: 'nghi ngờ', strokeCount: 14 },
      { character: '証', hanViet: 'CHỨNG', onyomi: 'しょう', meaningVi: 'chứng cứ', strokeCount: 12 },
      { character: '弁', hanViet: 'BIỆN', onyomi: 'べん', meaningVi: 'biện hộ', strokeCount: 5 },
      { character: '補', hanViet: 'BỔ', onyomi: 'ほ', kunyomi: 'おぎな-う', meaningVi: 'bổ sung', strokeCount: 12 },
      { character: '賠', hanViet: 'BỒI', onyomi: 'ばい', meaningVi: 'bồi thường', strokeCount: 15 },
    ],
  },
  {
    lessonNumber: 409,
    jlptLevel: 'N2',
    title: 'Bài 44 · Kanji N2 (9) — Phân loại, đặc trưng',
    sortOrder: 4090,
    entries: [
      { character: '領', hanViet: 'LĨNH', onyomi: 'りょう', kunyomi: 'えり', meaningVi: 'lãnh thổ, lĩnh vực', strokeCount: 14 },
      { character: '域', hanViet: 'VỰC', onyomi: 'いき', meaningVi: 'khu vực', strokeCount: 11 },
      { character: '範', hanViet: 'PHẠM', onyomi: 'はん', meaningVi: 'phạm vi', strokeCount: 15 },
      { character: '囲', hanViet: 'VI', onyomi: 'い', kunyomi: 'かこ-む', meaningVi: 'bao quanh', strokeCount: 7 },
      { character: '区', hanViet: 'KHU', onyomi: 'く', meaningVi: 'khu vực', strokeCount: 4 },
      { character: '別', hanViet: 'BIỆT', onyomi: 'べつ', kunyomi: 'わか-れる', meaningVi: 'riêng biệt', strokeCount: 7 },
      { character: '特', hanViet: 'ĐẶC', onyomi: 'とく', meaningVi: 'đặc biệt', strokeCount: 10 },
      { character: '色', hanViet: 'SẮC', onyomi: 'しょく', kunyomi: 'いろ', meaningVi: 'màu sắc', strokeCount: 6 },
      { character: '質', hanViet: 'CHẤT', onyomi: 'しつ', kunyomi: 'たち', meaningVi: 'chất lượng', strokeCount: 15 },
      { character: '量', hanViet: 'LƯỢNG', onyomi: 'りょう', meaningVi: 'số lượng', strokeCount: 12 },
      { character: '度', hanViet: 'ĐỘ', onyomi: 'ど', kunyomi: 'たび', meaningVi: 'mức độ', strokeCount: 9 },
      { character: '段', hanViet: 'ĐOẠN', onyomi: 'だん', meaningVi: 'giai đoạn', strokeCount: 9 },
      { character: '階', hanViet: 'GIAI', onyomi: 'かい', meaningVi: 'tầng, cấp bậc', strokeCount: 12 },
      { character: '層', hanViet: 'TẰNG', onyomi: 'そう', meaningVi: 'tầng lớp', strokeCount: 14 },
      { character: '構', hanViet: 'CẤU', onyomi: 'こう', kunyomi: 'かま-える', meaningVi: 'cấu trúc', strokeCount: 14 },
      { character: '組', hanViet: 'TỔ', onyomi: 'そ', kunyomi: 'く-む', meaningVi: 'tổ chức', strokeCount: 11 },
      { character: '編', hanViet: 'BIÊN', onyomi: 'へん', kunyomi: 'あ-む', meaningVi: 'biên soạn', strokeCount: 15 },
      { character: '整', hanViet: 'CHỈNH', onyomi: 'せい', kunyomi: 'ととの-える', meaningVi: 'chỉnh sửa', strokeCount: 16 },
      { character: '改', hanViet: 'CẢI', onyomi: 'かい', kunyomi: 'あらた-める', meaningVi: 'cải cách', strokeCount: 7 },
      { character: '善', hanViet: 'THIỆN', onyomi: 'ぜん', kunyomi: 'よ-い', meaningVi: 'tốt, thiện', strokeCount: 12 },
    ],
  },
  {
    lessonNumber: 504,
    jlptLevel: 'N1',
    title: 'Bài 45 · Kanji N1 (4) — Vật chất, tính chất',
    sortOrder: 5040,
    entries: [
      { character: '覆', hanViet: 'PHỤC', onyomi: 'ふく', kunyomi: 'おお-う, くつがえ-す', meaningVi: 'che phủ; lật đổ', strokeCount: 18 },
      { character: '貯', hanViet: 'TRỮ', onyomi: 'ちょ', kunyomi: 'た-める', meaningVi: 'tích trữ', strokeCount: 12 },
      { character: '蓄', hanViet: 'SÚC', onyomi: 'ちく', kunyomi: 'たくわ-える', meaningVi: 'tích lũy', strokeCount: 13 },
      { character: '浸', hanViet: 'CẬM', onyomi: 'しん', kunyomi: 'ひ-たす, ひ-たる', meaningVi: 'ngâm, thấm', strokeCount: 10 },
      { character: '溶', hanViet: 'DUNG', onyomi: 'よう', kunyomi: 'と-ける, と-かす', meaningVi: 'tan, hòa tan', strokeCount: 13 },
      { character: '融', hanViet: 'DUNG', onyomi: 'ゆう', kunyomi: 'と-ける', meaningVi: 'hòa tan, hòa nhập', strokeCount: 16 },
      { character: '混', hanViet: 'HỖN', onyomi: 'こん', kunyomi: 'ま-じる, ま-ぜる', meaningVi: 'trộn lẫn', strokeCount: 11 },
      { character: '濁', hanViet: 'ĐỐC', onyomi: 'だく', kunyomi: 'にご-る', meaningVi: 'đục, trần tục', strokeCount: 16 },
      { character: '純', hanViet: 'THUẦN', onyomi: 'じゅん', meaningVi: 'thuần khiết', strokeCount: 10 },
      { character: '希', hanViet: 'HI', onyomi: 'き', meaningVi: 'hiếm', strokeCount: 7 },
      { character: '膨', hanViet: 'BÀNH', onyomi: 'ぼう', kunyomi: 'ふく-らむ', meaningVi: 'phồng lên', strokeCount: 16 },
      { character: '縮', hanViet: 'SÚC', onyomi: 'しゅく', kunyomi: 'ちぢ-む, ちぢ-める', meaningVi: 'co lại', strokeCount: 17 },
      { character: '緻', hanViet: 'CHÍ', onyomi: 'ち', meaningVi: 'tỉ mỉ (緻密)', strokeCount: 16 },
      { character: '粗', hanViet: 'THÔ', onyomi: 'そ', kunyomi: 'あら-い', meaningVi: 'thô sơ', strokeCount: 11 },
      { character: '雑', hanViet: 'TẠP', onyomi: 'ざつ', kunyomi: 'ま-じる', meaningVi: 'tạp, lộn xộn', strokeCount: 14 },
      { character: '複', hanViet: 'PHỨC', onyomi: 'ふく', meaningVi: 'phức tạp', strokeCount: 14 },
      { character: '簡', hanViet: 'GIẢN', onyomi: 'かん', meaningVi: 'đơn giản', strokeCount: 18 },
      { character: '詳', hanViet: 'TƯƠNG', onyomi: 'しょう', kunyomi: 'くわ-しい', meaningVi: 'chi tiết', strokeCount: 13 },
      { character: '細', hanViet: 'TẾ', onyomi: 'さい', kunyomi: 'ほそ-い, こま-かい', meaningVi: 'nhỏ, tế nhị', strokeCount: 11 },
      { character: '緩', hanViet: 'HOÃN', onyomi: 'かん', kunyomi: 'ゆる-い, ゆる-める', meaningVi: 'lỏng lẻo, nới lỏng', strokeCount: 15 },
    ],
  },
  {
    lessonNumber: 505,
    jlptLevel: 'N1',
    title: 'Bài 46 · Kanji N1 (5) — Kinh tế, bồi thường',
    sortOrder: 5050,
    entries: [
      { character: '損', hanViet: 'TỔN', onyomi: 'そん', kunyomi: 'そこ-なる', meaningVi: 'tổn thất', strokeCount: 13 },
      { character: '益', hanViet: 'ÍCH', onyomi: 'えき', meaningVi: 'lợi ích', strokeCount: 10 },
      { character: '償', hanViet: 'THƯỜNG', onyomi: 'しょう', kunyomi: 'つぐな-う', meaningVi: 'bồi thường', strokeCount: 17 },
      { character: '充', hanViet: 'SUNG', onyomi: 'じゅう', kunyomi: 'あ-てる', meaningVi: 'lấp đầy', strokeCount: 6 },
      { character: '満', hanViet: 'MÃN', onyomi: 'まん', kunyomi: 'み-ちる', meaningVi: 'đầy đủ', strokeCount: 12 },
      { character: '欠', hanViet: 'KHIẾM', onyomi: 'けつ', kunyomi: 'か-ける', meaningVi: 'thiếu', strokeCount: 4 },
      { character: '乏', hanViet: 'PHẠP', onyomi: 'ぼう', kunyomi: 'とぼ-しい', meaningVi: 'nghèo thiếu', strokeCount: 4 },
      { character: '富', hanViet: 'PHÚ', onyomi: 'ふ', kunyomi: 'と-む', meaningVi: 'giàu có', strokeCount: 12 },
      { character: '貧', hanViet: 'BẦN', onyomi: 'ひん', meaningVi: 'nghèo khó', strokeCount: 11 },
      { character: '裕', hanViet: 'DỤ', onyomi: 'ゆう', meaningVi: 'dư dả', strokeCount: 12 },
      { character: '剰', hanViet: 'THỪA', onyomi: 'じょう', meaningVi: 'dư thừa', strokeCount: 11 },
      { character: '余', hanViet: 'DƯ', onyomi: 'よ', kunyomi: 'あま-る', meaningVi: 'dư, thừa', strokeCount: 7 },
      { character: '控', hanViet: 'KHỐNG', onyomi: 'こう', kunyomi: 'ひか-える', meaningVi: 'kiềm chế', strokeCount: 11 },
      { character: '急', hanViet: 'CẤP', onyomi: 'きゅう', kunyomi: 'いそ-ぐ', meaningVi: 'gấp, khẩn cấp', strokeCount: 9 },
      { character: '迫', hanViet: 'BÁCH', onyomi: 'はく', kunyomi: 'せま-る', meaningVi: 'ép buộc', strokeCount: 8 },
      { character: '逼', hanViet: 'BỨC', onyomi: 'ふく', meaningVi: 'bức bách', strokeCount: 12 },
      { character: '圧', hanViet: 'ÁP', onyomi: 'あつ', meaningVi: 'áp lực', strokeCount: 5 },
      { character: '抑', hanViet: 'ỨC', onyomi: 'よく', kunyomi: 'おさ-える', meaningVi: 'kìm nén', strokeCount: 7 },
      { character: '促', hanViet: 'XÚC', onyomi: 'そく', kunyomi: 'うなが-す', meaningVi: 'thúc giục', strokeCount: 9 },
      { character: '励', hanViet: 'LỆ', onyomi: 'れい', kunyomi: 'はげ-ます, はげ-む', meaningVi: 'khích lệ', strokeCount: 17 },
    ],
  },
  {
    lessonNumber: 506,
    jlptLevel: 'N1',
    title: 'Bài 47 · Kanji N1 (6) — Tư duy, phân tích',
    sortOrder: 5060,
    entries: [
      { character: '析', hanViet: 'TÍCH', onyomi: 'せき', meaningVi: 'phân tích', strokeCount: 8 },
      { character: '綜', hanViet: 'TỔNG', onyomi: 'そう', meaningVi: 'tổng hợp', strokeCount: 16 },
      { character: '括', hanViet: 'QUÁT', onyomi: 'かつ', kunyomi: 'くく-る', meaningVi: 'tóm lại', strokeCount: 9 },
      { character: '推', hanViet: 'THÔI', onyomi: 'すい', kunyomi: 'お-す', meaningVi: 'suy đoán', strokeCount: 11 },
      { character: '測', hanViet: 'TRẮC', onyomi: 'そく', kunyomi: 'はか-る', meaningVi: 'đo lường', strokeCount: 12 },
      { character: '算', hanViet: 'TOÁN', onyomi: 'さん', meaningVi: 'tính toán', strokeCount: 14 },
      { character: '察', hanViet: 'SÁT', onyomi: 'さつ', meaningVi: 'quan sát, suy xét', strokeCount: 14 },
      { character: '観', hanViet: 'QUÁN', onyomi: 'かん', kunyomi: 'み-る', meaningVi: 'quan sát', strokeCount: 18 },
      { character: '視', hanViet: 'THỊ', onyomi: 'し', meaningVi: 'nhìn', strokeCount: 11 },
      { character: '監', hanViet: 'GIÁM', onyomi: 'かん', meaningVi: 'giám sát', strokeCount: 15 },
      { character: '督', hanViet: 'ĐỐC', onyomi: 'とく', meaningVi: 'đốc thúc', strokeCount: 13 },
      { character: '診', hanViet: 'CHẨN', onyomi: 'しん', meaningVi: 'chẩn đoán', strokeCount: 12 },
      { character: '究', hanViet: 'CỨU', onyomi: 'きゅう', kunyomi: 'きわ-める', meaningVi: 'nghiên cứu sâu', strokeCount: 7 },
      { character: '探', hanViet: 'THÁM', onyomi: 'たん', kunyomi: 'さぐ-る, さが-す', meaningVi: 'dò tìm', strokeCount: 11 },
      { character: '索', hanViet: 'SÁCH', onyomi: 'さく', meaningVi: 'tìm kiếm', strokeCount: 10 },
      { character: '精', hanViet: 'TINH', onyomi: 'せい', kunyomi: 'しら-げる', meaningVi: 'tinh tế', strokeCount: 14 },
      { character: '准', hanViet: 'CHUẨN', onyomi: 'じゅん', meaningVi: 'chuẩn, cho phép', strokeCount: 10 },
      { character: '憶', hanViet: 'ỨC', onyomi: 'おく', meaningVi: 'ký ức', strokeCount: 16 },
      { character: '悟', hanViet: 'NGỘ', onyomi: 'ご', kunyomi: 'さと-る', meaningVi: 'giác ngộ', strokeCount: 10 },
      { character: '領', hanViet: 'LĨNH', onyomi: 'りょう', meaningVi: 'lĩnh hội', strokeCount: 14 },
    ],
  },
  {
    lessonNumber: 507,
    jlptLevel: 'N1',
    title: 'Bài 48 · Kanji N1 (7) — Xã hội, văn hóa',
    sortOrder: 5070,
    entries: [
      { character: '俗', hanViet: 'TỤC', onyomi: 'ぞく', meaningVi: 'tục lệ', strokeCount: 9 },
      { character: '慣', hanViet: 'QUÁN', onyomi: 'かん', kunyomi: 'な-れる', meaningVi: 'quen', strokeCount: 14 },
      { character: '風', hanViet: 'PHONG', onyomi: 'ふう', kunyomi: 'かぜ', meaningVi: 'phong cách', strokeCount: 9 },
      { character: '儀', hanViet: 'NGHI', onyomi: 'ぎ', meaningVi: 'nghi lễ', strokeCount: 15 },
      { character: '礼', hanViet: 'LỄ', onyomi: 'れい', meaningVi: 'lễ nghi', strokeCount: 5 },
      { character: '拝', hanViet: 'BÁI', onyomi: 'はい', kunyomi: 'おが-む', meaningVi: 'bái lạy', strokeCount: 8 },
      { character: '敬', hanViet: 'KÍNH', onyomi: 'けい', kunyomi: 'うや-まう', meaningVi: 'kính trọng', strokeCount: 12 },
      { character: '謙', hanViet: 'KHIÊM', onyomi: 'けん', meaningVi: 'khiêm tốn', strokeCount: 17 },
      { character: '虚', hanViet: 'HƯ', onyomi: 'きょ', meaningVi: 'hư ảo', strokeCount: 11 },
      { character: '誠', hanViet: 'THÀNH', onyomi: 'せい', kunyomi: 'まこと', meaningVi: 'chân thành', strokeCount: 13 },
      { character: '偽', hanViet: 'NGỤY', onyomi: 'ぎ', kunyomi: 'いつわ-る', meaningVi: 'giả mạo', strokeCount: 11 },
      { character: '欺', hanViet: 'KHI', onyomi: 'ぎ', kunyomi: 'あざむ-く', meaningVi: 'lừa dối', strokeCount: 12 },
      { character: '詐', hanViet: 'TRÁ', onyomi: 'さ', meaningVi: 'lừa gạt', strokeCount: 12 },
      { character: '裏', hanViet: 'LÝ', onyomi: 'り', kunyomi: 'うら', meaningVi: 'mặt sau', strokeCount: 13 },
      { character: '筋', hanViet: 'CÂN', onyomi: 'きん', kunyomi: 'すじ', meaningVi: 'gân, logic', strokeCount: 12 },
      { character: '脈', hanViet: 'MẠCH', onyomi: 'みゃく', meaningVi: 'mạch, dòng chảy', strokeCount: 10 },
      { character: '血', hanViet: 'HUYẾT', onyomi: 'けつ', kunyomi: 'ち', meaningVi: 'máu', strokeCount: 6 },
      { character: '族', hanViet: 'TỘC', onyomi: 'ぞく', meaningVi: 'dòng họ, tộc', strokeCount: 11 },
      { character: '籍', hanViet: 'TỊCH', onyomi: 'せき', meaningVi: 'hộ tịch, sổ', strokeCount: 20 },
      { character: '民', hanViet: 'DÂN', onyomi: 'みん', kunyomi: 'たみ', meaningVi: 'dân chúng', strokeCount: 5 },
      { character: '衆', hanViet: 'CHÚNG', onyomi: 'しゅう', meaningVi: 'đám đông', strokeCount: 12 },
      { character: '群', hanViet: 'QUẦN', onyomi: 'ぐん', kunyomi: 'む-れる, む-れ', meaningVi: 'bầy, nhóm', strokeCount: 13 },
      { character: '集', hanViet: 'TẬP', onyomi: 'しゅう', kunyomi: 'あつ-まる, あつ-める', meaningVi: 'tập hợp', strokeCount: 12 },
      { character: '団', hanViet: 'ĐOÀN', onyomi: 'だん, とん', meaningVi: 'đoàn thể', strokeCount: 6 },
      { character: '協', hanViet: 'HIỆP', onyomi: 'きょう', meaningVi: 'hợp tác', strokeCount: 8 },
      { character: '同', hanViet: 'ĐỒNG', onyomi: 'どう', kunyomi: 'おな-じ', meaningVi: 'cùng, giống', strokeCount: 6 },
      { character: '異', hanViet: 'DỊ', onyomi: 'い', kunyomi: 'こと', meaningVi: 'khác biệt', strokeCount: 11 },
      { character: '共', hanViet: 'CỘNG', onyomi: 'きょう', kunyomi: 'とも', meaningVi: 'cùng, chung', strokeCount: 6 },
      { character: '独', hanViet: 'ĐỘC', onyomi: 'どく, とく', kunyomi: 'ひと-り', meaningVi: 'độc lập', strokeCount: 9 },
    ],
  },
  {
    lessonNumber: 508,
    jlptLevel: 'N1',
    title: 'Bài 49 · Kanji N1 (8) — Trừu tượng, triết lý',
    sortOrder: 5080,
    entries: [
      { character: '哲', hanViet: 'TRIẾT', onyomi: 'てつ', meaningVi: 'triết học', strokeCount: 10 },
      { character: '玄', hanViet: 'HUYỀN', onyomi: 'げん', meaningVi: 'huyền bí', strokeCount: 5 },
      { character: '奥', hanViet: 'ÁO', onyomi: 'おう', kunyomi: 'おく', meaningVi: 'sâu bên trong', strokeCount: 12 },
      { character: '深', hanViet: 'THÂM', onyomi: 'しん', kunyomi: 'ふか-い', meaningVi: 'sâu sắc', strokeCount: 11 },
      { character: '浅', hanViet: 'THIỂN', onyomi: 'せん', kunyomi: 'あさ-い', meaningVi: 'nông cạn', strokeCount: 9 },
      { character: '狭', hanViet: 'HIỆP', onyomi: 'きょう', kunyomi: 'せま-い', meaningVi: 'hẹp', strokeCount: 9 },
      { character: '遠', hanViet: 'VIỄN', onyomi: 'えん', kunyomi: 'とお-い', meaningVi: 'xa xôi', strokeCount: 13 },
      { character: '近', hanViet: 'CẬN', onyomi: 'きん', kunyomi: 'ちか-い', meaningVi: 'gần', strokeCount: 7 },
      { character: '恒', hanViet: 'HẰNG', onyomi: 'こう', meaningVi: 'vĩnh cửu', strokeCount: 9 },
      { character: '永', hanViet: 'VĨNH', onyomi: 'えい', kunyomi: 'なが-い', meaningVi: 'vĩnh viễn', strokeCount: 5 },
      { character: '暫', hanViet: 'TẠM', onyomi: 'ざん', kunyomi: 'しばら-く', meaningVi: 'tạm thời', strokeCount: 15 },
      { character: '瞬', hanViet: 'NHÚN', onyomi: 'しゅん', meaningVi: 'khoảnh khắc', strokeCount: 18 },
      { character: '即', hanViet: 'TỨC', onyomi: 'そく', kunyomi: 'すなわ-ち', meaningVi: 'tức thì', strokeCount: 7 },
      { character: '既', hanViet: 'KÝ', onyomi: 'き', meaningVi: 'đã', strokeCount: 9 },
      { character: '未', hanViet: 'VỊ', onyomi: 'み', meaningVi: 'chưa', strokeCount: 5 },
      { character: '曾', hanViet: 'TĂNG', onyomi: 'そ', kunyomi: 'かつ-て', meaningVi: 'từng, xưa kia', strokeCount: 11 },
      { character: '根', hanViet: 'CĂN', onyomi: 'こん', kunyomi: 'ね', meaningVi: 'gốc rễ', strokeCount: 10 },
      { character: '本', hanViet: 'BẢN', onyomi: 'ほん', kunyomi: 'もと', meaningVi: 'gốc, sách', strokeCount: 5 },
      { character: '末', hanViet: 'MẠT', onyomi: 'まつ', kunyomi: 'すえ', meaningVi: 'cuối, tận cùng', strokeCount: 5 },
      { character: '端', hanViet: 'ĐOAN', onyomi: 'たん', kunyomi: 'はし, は', meaningVi: 'đầu mút, đoan', strokeCount: 14 },
    ],
  },
];
