// Bổ sung từ vựng N2 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 706-711.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N2_PART2: JlptVocabUnit[] = [
  {
    lessonNumber: 706,
    jlptLevel: 'N2',
    words: [
      { kana: 'しいんと', romaji: 'shiinto', meaning: 'im lặng như tờ', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'しつこい', romaji: 'shitsukoi', meaning: 'dai dẳng, ngoan cố', partOfSpeech: 'tính từ i' },
      { kana: 'しっぽ', romaji: 'shippo', meaning: 'cái đuôi', partOfSpeech: 'danh từ' },
      { kanji: '痺れます', kana: 'しびれます', romaji: 'shibiremasu', meaning: 'bị tê, tê liệt', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '萎みます', kana: 'しぼみます', romaji: 'shibomimasu', meaning: 'héo úa, xẹp xuống', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'しみじみ', romaji: 'shimijimi', meaning: 'thấm thía, sâu sắc', partOfSpeech: 'phó từ' },
      { kana: 'ジャーナリスト', romaji: 'jānarisuto', meaning: 'nhà báo', partOfSpeech: 'danh từ' },
      { kanji: '蹲みます', kana: 'しゃがみます', romaji: 'shagamimasu', meaning: 'ngồi xổm', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'しゃっくり', romaji: 'shakkuri', meaning: 'cái nấc cụt', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'シャッター', romaji: 'shattā', meaning: 'cửa cuốn, màn trập', partOfSpeech: 'danh từ' },
      { kanji: 'しゃぶります', kana: 'しゃぶります', romaji: 'shaburimasu', meaning: 'mút, ngậm', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'じゃんけん', romaji: 'janken', meaning: 'trò oẳn tù tì', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'じゅうたん', romaji: 'jūtan', meaning: 'thảm trải sàn', partOfSpeech: 'danh từ' },
      { kana: 'ショップ', romaji: 'shoppu', meaning: 'cửa hàng', partOfSpeech: 'danh từ' },
      { kana: 'シリーズ', romaji: 'shirīzu', meaning: 'loạt, chuỗi (phim, sách)', partOfSpeech: 'danh từ' },
      { kana: 'ずうずうしい', romaji: 'zūzūshii', meaning: 'trơ trẽn, mặt dày', partOfSpeech: 'tính từ i' },
      { kana: 'スカーフ', romaji: 'sukāfu', meaning: 'khăn quàng cổ', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 707,
    jlptLevel: 'N2',
    words: [
      { kana: 'スクール', romaji: 'sukūru', meaning: 'trường học', partOfSpeech: 'danh từ' },
      { kana: 'すくなくとも', romaji: 'sukunakutomo', meaning: 'ít nhất là', partOfSpeech: 'phó từ' },
      { kana: 'スチュワーデス', romaji: 'suchuwādesu', meaning: 'tiếp viên hàng không (nữ)', partOfSpeech: 'danh từ' },
      { kana: 'すっきり', romaji: 'sukkiri', meaning: 'gọn gàng, sảng khoái', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'すっぱい', romaji: 'suppai', meaning: 'chua', partOfSpeech: 'tính từ i' },
      { kana: 'ステージ', romaji: 'sutēji', meaning: 'sân khấu', partOfSpeech: 'danh từ' },
      { kana: 'ストッキング', romaji: 'sutokkingu', meaning: 'tất dài (nữ)', partOfSpeech: 'danh từ' },
      { kana: 'ストップ', romaji: 'sutoppu', meaning: 'dừng lại', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'スピーカー', romaji: 'supīkā', meaning: 'loa', partOfSpeech: 'danh từ' },
      { kana: 'スマート', romaji: 'sumāto', meaning: 'mảnh mai, sành điệu', partOfSpeech: 'tính từ na' },
      { kana: 'すまない', romaji: 'sumanai', meaning: 'xin lỗi (cách nói suồng sã)', partOfSpeech: 'cụm từ' },
      { kana: 'スライド', romaji: 'suraido', meaning: 'slide, phim đèn chiếu', partOfSpeech: 'danh từ' },
      { kanji: 'ずらします', kana: 'ずらします', romaji: 'zurashimasu', meaning: 'dịch chuyển, dời (thời gian, vị trí)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '擦れ違います', kana: 'すれちがいます', romaji: 'surechigaimasu', meaning: 'lướt qua nhau; hiểu lầm nhau', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'ぜひとも', romaji: 'zehitomo', meaning: 'nhất định phải, bằng mọi giá', partOfSpeech: 'phó từ' },
      { kana: 'ゼミ', romaji: 'zemi', meaning: 'buổi seminar, hội thảo nhỏ', partOfSpeech: 'danh từ' },
      { kana: 'セメント', romaji: 'semento', meaning: 'xi măng', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 708,
    jlptLevel: 'N2',
    words: [
      { kana: 'センチ', romaji: 'senchi', meaning: 'xăng-ti-mét', partOfSpeech: 'danh từ' },
      { kana: 'そういえば', romaji: 'sōieba', meaning: 'nói mới nhớ, nhân tiện nói tới', partOfSpeech: 'phó từ' },
      { kana: 'そうして', romaji: 'sōshite', meaning: 'rồi thì, như vậy đó', partOfSpeech: 'liên từ' },
      { kana: 'そそっかしい', romaji: 'sosokkashii', meaning: 'hậu đậu, đãng trí', partOfSpeech: 'tính từ i' },
      { kana: 'そのため', romaji: 'sonotame', meaning: 'vì thế, do đó', partOfSpeech: 'liên từ' },
      { kana: 'そのほか', romaji: 'sonohoka', meaning: 'ngoài ra, còn lại', partOfSpeech: 'liên từ' },
      { kana: 'だいいち', romaji: 'daiichi', meaning: 'trước hết, quan trọng nhất', partOfSpeech: 'danh từ, phó từ' },
      { kana: 'ダイヤグラム', romaji: 'daiyaguramu', meaning: 'biểu đồ, sơ đồ', partOfSpeech: 'danh từ' },
      { kana: 'ダイヤモンド', romaji: 'daiyamondo', meaning: 'kim cương', partOfSpeech: 'danh từ' },
      { kana: 'ダイヤル', romaji: 'daiyaru', meaning: 'mặt số quay (điện thoại)', partOfSpeech: 'danh từ' },
      { kana: 'たちまち', romaji: 'tachimachi', meaning: 'ngay lập tức, chỉ trong chốc lát', partOfSpeech: 'phó từ' },
      { kana: 'ダブル', romaji: 'daburu', meaning: 'đôi, gấp đôi', partOfSpeech: 'danh từ' },
      { kanji: '騙します', kana: 'だまします', romaji: 'damashimasu', meaning: 'lừa dối, lừa gạt', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'ダム', romaji: 'damu', meaning: 'đập nước', partOfSpeech: 'danh từ' },
      { kanji: '躊躇います', kana: 'ためらいます', romaji: 'tameraimasu', meaning: 'do dự, chần chừ', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'だらしない', romaji: 'darashinai', meaning: 'luộm thuộm, thiếu ngăn nắp', partOfSpeech: 'tính từ i' },
      { kanji: '千切ります', kana: 'ちぎります', romaji: 'chigirimasu', meaning: 'xé nhỏ, ngắt ra', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 709,
    jlptLevel: 'N2',
    words: [
      { kana: 'チップ', romaji: 'chippu', meaning: 'tiền boa; con chip', partOfSpeech: 'danh từ' },
      { kana: 'チョーク', romaji: 'chōku', meaning: 'phấn viết bảng', partOfSpeech: 'danh từ' },
      { kana: 'ついで', romaji: 'tsuide', meaning: 'tiện thể, nhân dịp', partOfSpeech: 'danh từ' },
      { kanji: '躓きます', kana: 'つまずきます', romaji: 'tsumazukimasu', meaning: 'vấp ngã, gặp trở ngại', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'テーマ', romaji: 'tēma', meaning: 'chủ đề', partOfSpeech: 'danh từ' },
      { kana: 'でたらめ', romaji: 'detarame', meaning: 'vô căn cứ, bậy bạ', partOfSpeech: 'danh từ, tính từ na' },
      { kana: 'テニスコート', romaji: 'tenisukōto', meaning: 'sân tennis', partOfSpeech: 'danh từ' },
      { kana: 'テンポ', romaji: 'tenpo', meaning: 'nhịp độ, tốc độ', partOfSpeech: 'danh từ' },
      { kana: 'どうぞよろしく', romaji: 'dōzoyoroshiku', meaning: 'rất hân hạnh được biết bạn', partOfSpeech: 'cụm từ' },
      { kana: 'どきどき', romaji: 'dokidoki', meaning: 'hồi hộp, đập thình thịch', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'とっくに', romaji: 'tokkuni', meaning: 'đã từ lâu rồi', partOfSpeech: 'phó từ' },
      { kana: 'どっと', romaji: 'dotto', meaning: 'ồ ạt, đột ngột (số đông)', partOfSpeech: 'phó từ' },
      { kanji: '怒鳴ります', kana: 'どなります', romaji: 'donarimasu', meaning: 'quát mắng, la hét', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'ともかく', romaji: 'tomokaku', meaning: 'dù sao đi nữa, dù thế nào', partOfSpeech: 'phó từ' },
      { kana: 'トレーニング', romaji: 'torēningu', meaning: 'sự luyện tập', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'ナイロン', romaji: 'nairon', meaning: 'ni lông', partOfSpeech: 'danh từ' },
      { kanji: '殴ります', kana: 'なぐります', romaji: 'nagurimasu', meaning: 'đánh, đấm', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 710,
    jlptLevel: 'N2',
    words: [
      { kana: 'なにしろ', romaji: 'nanishiro', meaning: 'dù sao thì, bởi vì', partOfSpeech: 'phó từ' },
      { kana: 'なんとも', romaji: 'nantomo', meaning: 'chẳng có gì, không thể nói được (đi với phủ định)', partOfSpeech: 'phó từ' },
      { kana: 'ナンバー', romaji: 'nanbā', meaning: 'số, con số', partOfSpeech: 'danh từ' },
      { kana: 'ねじ', romaji: 'neji', meaning: 'con ốc vít', partOfSpeech: 'danh từ' },
      { kana: 'ネックレス', romaji: 'nekkuresu', meaning: 'dây chuyền (trang sức)', partOfSpeech: 'danh từ' },
      { kana: 'のこぎり', romaji: 'nokogiri', meaning: 'cái cưa', partOfSpeech: 'danh từ' },
      { kana: 'のろのろ', romaji: 'noronoro', meaning: 'chậm chạp, ì ạch', partOfSpeech: 'phó từ' },
      { kana: 'ばからしい', romaji: 'bakarashii', meaning: 'ngớ ngẩn, vô lý', partOfSpeech: 'tính từ i' },
      { kana: 'はきはき', romaji: 'hakihaki', meaning: 'rành mạch, dứt khoát', partOfSpeech: 'phó từ' },
      { kana: 'バケツ', romaji: 'baketsu', meaning: 'cái xô', partOfSpeech: 'danh từ' },
      { kana: 'はじめまして', romaji: 'hajimemashite', meaning: 'rất vui được gặp bạn (lần đầu)', partOfSpeech: 'cụm từ' },
      { kana: 'パターン', romaji: 'patān', meaning: 'khuôn mẫu, kiểu', partOfSpeech: 'danh từ' },
      { kana: 'バック', romaji: 'bakku', meaning: 'phía sau, lùi lại', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'ばね', romaji: 'bane', meaning: 'lò xo', partOfSpeech: 'danh từ' },
      { kanji: '嵌めます', kana: 'はめます', romaji: 'hamemasu', meaning: 'lắp vào, đeo vào', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'バランス', romaji: 'baransu', meaning: 'sự cân bằng', partOfSpeech: 'danh từ' },
      { kana: 'パンツ', romaji: 'pantsu', meaning: 'quần lót, quần đùi', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 711,
    jlptLevel: 'N2',
    words: [
      { kana: 'バンド', romaji: 'bando', meaning: 'ban nhạc; dây đai', partOfSpeech: 'danh từ' },
      { kana: 'ハンドル', romaji: 'handoru', meaning: 'vô lăng, tay cầm', partOfSpeech: 'danh từ' },
      { kana: 'ぴかぴか', romaji: 'pikapika', meaning: 'sáng lấp lánh, bóng loáng', partOfSpeech: 'phó từ, tính từ na' },
      { kana: 'ピストル', romaji: 'pisutoru', meaning: 'súng lục', partOfSpeech: 'danh từ' },
      { kana: 'ビタミン', romaji: 'bitamin', meaning: 'vitamin', partOfSpeech: 'danh từ' },
      { kana: 'ひとまず', romaji: 'hitomazu', meaning: 'tạm thời, trước mắt', partOfSpeech: 'phó từ' },
      { kana: 'ひとりでに', romaji: 'hitorideni', meaning: 'tự nó, tự động', partOfSpeech: 'phó từ' },
      { kana: 'ビニール', romaji: 'binīru', meaning: 'nhựa vinyl, ni lông', partOfSpeech: 'danh từ' },
      { kanji: '百科事典', kana: 'ひゃっかじてん', romaji: 'hyakkajiten', meaning: 'từ điển bách khoa', partOfSpeech: 'danh từ' },
      { kana: 'ビルディング', romaji: 'birudeぃngu', meaning: 'tòa nhà cao tầng', partOfSpeech: 'danh từ' },
      { kana: 'ピンク', romaji: 'pinku', meaning: 'màu hồng', partOfSpeech: 'danh từ' },
      { kana: 'ファスナー', romaji: 'fuぁsunā', meaning: 'khóa kéo', partOfSpeech: 'danh từ' },
      { kana: 'ふざけます', romaji: 'fuzakemasu', meaning: 'đùa giỡn, nghịch ngợm', partOfSpeech: 'động từ nhóm 2' },
      { kanji: 'ぶつけます', kana: 'ぶつけます', romaji: 'butsukemasu', meaning: 'va đập, ném trúng', partOfSpeech: 'động từ nhóm 2' },
    ],
  },
];
