// Bổ sung từ vựng N3 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 326-331.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N3_PART4: JlptVocabUnit[] = [
  {
    lessonNumber: 326,
    jlptLevel: 'N3',
    words: [
      { kanji: '手間', kana: 'てま', romaji: 'tema', meaning: 'công sức, thời gian bỏ ra', partOfSpeech: 'danh từ' },
      { kanji: '手伝い', kana: 'てつだい', romaji: 'tetsudai', meaning: 'sự giúp đỡ, người phụ giúp', partOfSpeech: 'danh từ' },
      { kanji: '手品', kana: 'てじな', romaji: 'tejina', meaning: 'trò ảo thuật', partOfSpeech: 'danh từ' },
      { kanji: '種', kana: 'たね', romaji: 'tane', meaning: 'hạt giống; nguyên nhân, chất liệu', partOfSpeech: 'danh từ' },
      { kanji: '首都', kana: 'しゅと', romaji: 'shuto', meaning: 'thủ đô', partOfSpeech: 'danh từ' },
      { kanji: '受け取ります', kana: 'うけとります', romaji: 'uketorimasu', meaning: 'nhận, tiếp nhận', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '収めます', kana: 'おさめます', romaji: 'osamemasu', meaning: 'thu được, đạt được; nộp (tiền)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '収穫', kana: 'しゅうかく', romaji: 'shūkaku', meaning: 'sự thu hoạch', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '周囲', kana: 'しゅうい', romaji: 'shūi', meaning: 'xung quanh, chu vi', partOfSpeech: 'danh từ' },
      { kanji: '州', kana: 'しゅう', romaji: 'shū', meaning: 'bang, châu (đơn vị hành chính)', partOfSpeech: 'danh từ' },
      { kanji: '修正', kana: 'しゅうせい', romaji: 'shūsei', meaning: 'sự sửa đổi, hiệu chỉnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '終えます', kana: 'おえます', romaji: 'oemasu', meaning: 'kết thúc, hoàn thành', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '臭い', kana: 'くさい', romaji: 'kusai', meaning: 'hôi, thối', partOfSpeech: 'tính từ i' },
      { kanji: '集まり', kana: 'あつまり', romaji: 'atsumari', meaning: 'buổi tụ họp', partOfSpeech: 'danh từ' },
      { kanji: '集中', kana: 'しゅうちゅう', romaji: 'shūchū', meaning: 'sự tập trung', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '住宅', kana: 'じゅうたく', romaji: 'jūtaku', meaning: 'nhà ở, khu dân cư', partOfSpeech: 'danh từ' },
      { kanji: '従います', kana: 'したがいます', romaji: 'shitagaimasu', meaning: 'tuân theo, đi theo', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 327,
    jlptLevel: 'N3',
    words: [
      { kanji: '従兄弟', kana: 'いとこ', romaji: 'itoko', meaning: 'anh chị em họ', partOfSpeech: 'danh từ' },
      { kanji: '重視', kana: 'じゅうし', romaji: 'jūshi', meaning: 'sự coi trọng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '重大', kana: 'じゅうだい', romaji: 'jūdai', meaning: 'trọng đại, nghiêm trọng', partOfSpeech: 'tính từ na' },
      { kanji: '重要', kana: 'じゅうよう', romaji: 'jūyō', meaning: 'quan trọng', partOfSpeech: 'tính từ na' },
      { kanji: '宿', kana: 'やど', romaji: 'yado', meaning: 'nhà trọ, quán trọ', partOfSpeech: 'danh từ' },
      { kanji: '宿泊', kana: 'しゅくはく', romaji: 'shukuhaku', meaning: 'sự lưu trú, nghỉ trọ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '祝い', kana: 'いわい', romaji: 'iwai', meaning: 'lễ mừng, sự chúc mừng', partOfSpeech: 'danh từ' },
      { kanji: '祝います', kana: 'いわいます', romaji: 'iwaimasu', meaning: 'chúc mừng, ăn mừng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '出会います', kana: 'であいます', romaji: 'deaimasu', meaning: 'tình cờ gặp gỡ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '出身', kana: 'しゅっしん', romaji: 'shusshin', meaning: 'xuất thân, quê quán', partOfSpeech: 'danh từ' },
      { kanji: '述べます', kana: 'のべます', romaji: 'nobemasu', meaning: 'trình bày, phát biểu', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '順', kana: 'じゅん', romaji: 'jun', meaning: 'thứ tự, lượt', partOfSpeech: 'danh từ' },
      { kanji: '順調', kana: 'じゅんちょう', romaji: 'junchō', meaning: 'thuận lợi, suôn sẻ', partOfSpeech: 'tính từ na' },
      { kanji: '順番', kana: 'じゅんばん', romaji: 'junban', meaning: 'thứ tự, lượt (xếp hàng)', partOfSpeech: 'danh từ' },
      { kanji: '処理', kana: 'しょり', romaji: 'shori', meaning: 'sự xử lý', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '所為', kana: 'せい', romaji: 'sei', meaning: 'nguyên nhân, lỗi tại', partOfSpeech: 'danh từ' },
      { kanji: '署名', kana: 'しょめい', romaji: 'shomei', meaning: 'chữ ký', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 328,
    jlptLevel: 'N3',
    words: [
      { kanji: '書斎', kana: 'しょさい', romaji: 'shosai', meaning: 'phòng đọc sách, thư phòng', partOfSpeech: 'danh từ' },
      { kanji: '書物', kana: 'しょもつ', romaji: 'shomotsu', meaning: 'sách vở', partOfSpeech: 'danh từ' },
      { kanji: '助手', kana: 'じょしゅ', romaji: 'joshu', meaning: 'trợ lý, trợ giảng', partOfSpeech: 'danh từ' },
      { kanji: '女王', kana: 'じょおう', romaji: 'joō', meaning: 'nữ hoàng', partOfSpeech: 'danh từ' },
      { kanji: '女子', kana: 'じょし', romaji: 'joshi', meaning: 'nữ giới, con gái', partOfSpeech: 'danh từ' },
      { kanji: '女優', kana: 'じょゆう', romaji: 'joyū', meaning: 'nữ diễn viên', partOfSpeech: 'danh từ' },
      { kanji: '除きます', kana: 'のぞきます', romaji: 'nozokimasu', meaning: 'loại trừ, loại bỏ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '商売', kana: 'しょうばい', romaji: 'shōbai', meaning: 'buôn bán, kinh doanh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '小屋', kana: 'こや', romaji: 'koya', meaning: 'túp lều, nhà kho nhỏ', partOfSpeech: 'danh từ' },
      { kanji: '小麦', kana: 'こむぎ', romaji: 'komugi', meaning: 'lúa mì', partOfSpeech: 'danh từ' },
      { kanji: '少々', kana: 'しょうしょう', romaji: 'shōshō', meaning: 'một chút, một lát', partOfSpeech: 'phó từ' },
      { kanji: '少しも', kana: 'すこしも', romaji: 'sukoshimo', meaning: 'không một chút nào (đi với phủ định)', partOfSpeech: 'phó từ' },
      { kanji: '少女', kana: 'しょうじょ', romaji: 'shōjo', meaning: 'thiếu nữ, bé gái', partOfSpeech: 'danh từ' },
      { kanji: '少年', kana: 'しょうねん', romaji: 'shōnen', meaning: 'thiếu niên', partOfSpeech: 'danh từ' },
      { kanji: '招きます', kana: 'まねきます', romaji: 'manekimasu', meaning: 'mời, chiêu đãi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '消防', kana: 'しょうぼう', romaji: 'shōbō', meaning: 'công tác cứu hỏa', partOfSpeech: 'danh từ' },
      { kanji: '省きます', kana: 'はぶきます', romaji: 'habukimasu', meaning: 'lược bỏ, tiết kiệm', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 329,
    jlptLevel: 'N3',
    words: [
      { kanji: '章', kana: 'しょう', romaji: 'shō', meaning: 'chương (sách)', partOfSpeech: 'danh từ' },
      { kanji: '笑い', kana: 'わらい', romaji: 'warai', meaning: 'tiếng cười, nụ cười', partOfSpeech: 'danh từ' },
      { kanji: '笑顔', kana: 'えがお', romaji: 'egao', meaning: 'gương mặt tươi cười', partOfSpeech: 'danh từ' },
      { kanji: '衝突', kana: 'しょうとつ', romaji: 'shōtotsu', meaning: 'sự va chạm, xung đột', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '上達', kana: 'じょうたつ', romaji: 'jōtatsu', meaning: 'sự tiến bộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '上等', kana: 'じょうとう', romaji: 'jōtō', meaning: 'hạng nhất, cao cấp', partOfSpeech: 'tính từ na' },
      { kanji: '乗客', kana: 'じょうきゃく', romaji: 'jōkyaku', meaning: 'hành khách', partOfSpeech: 'danh từ' },
      { kanji: '常に', kana: 'つねに', romaji: 'tsuneni', meaning: 'luôn luôn, thường xuyên', partOfSpeech: 'phó từ' },
      { kanji: '植物', kana: 'しょくぶつ', romaji: 'shokubutsu', meaning: 'thực vật', partOfSpeech: 'danh từ' },
      { kanji: '職', kana: 'しょく', romaji: 'shoku', meaning: 'nghề nghiệp, chức vụ', partOfSpeech: 'danh từ' },
      { kanji: '職業', kana: 'しょくぎょう', romaji: 'shokugyō', meaning: 'nghề nghiệp', partOfSpeech: 'danh từ' },
      { kanji: '触れます', kana: 'ふれます', romaji: 'furemasu', meaning: 'chạm vào, đề cập đến', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '食います', kana: 'くいます', romaji: 'kuimasu', meaning: 'ăn (cách nói suồng sã, thường nam giới dùng)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '食卓', kana: 'しょくたく', romaji: 'shokutaku', meaning: 'bàn ăn', partOfSpeech: 'danh từ' },
      { kanji: '食物', kana: 'しょくもつ', romaji: 'shokumotsu', meaning: 'thức ăn, thực phẩm', partOfSpeech: 'danh từ' },
      { kanji: '食料', kana: 'しょくりょう', romaji: 'shokuryō', meaning: 'lương thực, thực phẩm', partOfSpeech: 'danh từ' },
      { kanji: '尻', kana: 'しり', romaji: 'shiri', meaning: 'mông, phần đáy', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 330,
    jlptLevel: 'N3',
    words: [
      { kanji: '伸ばします', kana: 'のばします', romaji: 'nobashimasu', meaning: 'kéo dài, duỗi ra; để (tóc, râu) dài ra', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '伸びます', kana: 'のびます', romaji: 'nobimasu', meaning: 'dài ra, phát triển, tiến bộ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '審判', kana: 'しんぱん', romaji: 'shinpan', meaning: 'trọng tài; sự xét xử', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '心臓', kana: 'しんぞう', romaji: 'shinzō', meaning: 'trái tim, tim', partOfSpeech: 'danh từ' },
      { kanji: '心理', kana: 'しんり', romaji: 'shinri', meaning: 'tâm lý', partOfSpeech: 'danh từ' },
      { kanji: '新た', kana: 'あらた', romaji: 'arata', meaning: 'mới, mới mẻ', partOfSpeech: 'tính từ na' },
      { kanji: '新鮮', kana: 'しんせん', romaji: 'shinsen', meaning: 'tươi mới, tươi ngon', partOfSpeech: 'tính từ na' },
      { kanji: '申し訳', kana: 'もうしわけ', romaji: 'mōshiwake', meaning: 'lời xin lỗi, lý do biện hộ', partOfSpeech: 'danh từ' },
      { kanji: '真っ赤', kana: 'まっか', romaji: 'makka', meaning: 'đỏ chót, đỏ rực', partOfSpeech: 'tính từ na' },
      { kanji: '真剣', kana: 'しんけん', romaji: 'shinken', meaning: 'nghiêm túc, chân thành', partOfSpeech: 'tính từ na' },
      { kanji: '神経', kana: 'しんけい', romaji: 'shinkei', meaning: 'thần kinh, sự nhạy cảm', partOfSpeech: 'danh từ' },
      { kanji: '親しい', kana: 'したしい', romaji: 'shitashii', meaning: 'thân thiết, gần gũi', partOfSpeech: 'tính từ i' },
      { kanji: '親戚', kana: 'しんせき', romaji: 'shinseki', meaning: 'họ hàng, thân thích', partOfSpeech: 'danh từ' },
      { kanji: '親友', kana: 'しんゆう', romaji: 'shinyū', meaning: 'bạn thân', partOfSpeech: 'danh từ' },
      { kanji: '診察', kana: 'しんさつ', romaji: 'shinsatsu', meaning: 'sự khám bệnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '身体', kana: 'しんたい', romaji: 'shintai', meaning: 'cơ thể, thân thể', partOfSpeech: 'danh từ' },
      { kanji: '辛い', kana: 'つらい', romaji: 'tsurai', meaning: 'khổ sở, đau lòng', partOfSpeech: 'tính từ i' },
    ],
  },
  {
    lessonNumber: 331,
    jlptLevel: 'N3',
    words: [
      { kanji: '進学', kana: 'しんがく', romaji: 'shingaku', meaning: 'sự học lên (bậc cao hơn)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '震えます', kana: 'ふるえます', romaji: 'furuemasu', meaning: 'run rẩy, rung động', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '人間', kana: 'にんげん', romaji: 'ningen', meaning: 'con người', partOfSpeech: 'danh từ' },
      { kanji: '人込み', kana: 'ひとごみ', romaji: 'hitogomi', meaning: 'đám đông người', partOfSpeech: 'danh từ' },
      { kanji: '人種', kana: 'じんしゅ', romaji: 'jinshu', meaning: 'chủng tộc', partOfSpeech: 'danh từ' },
      { kanji: '人物', kana: 'じんぶつ', romaji: 'jinbutsu', meaning: 'nhân vật, con người (tính cách)', partOfSpeech: 'danh từ' },
      { kanji: '人類', kana: 'じんるい', romaji: 'jinrui', meaning: 'nhân loại', partOfSpeech: 'danh từ' },
      { kanji: '図書', kana: 'としょ', romaji: 'tosho', meaning: 'sách, tài liệu', partOfSpeech: 'danh từ' },
      { kanji: '数', kana: 'かず', romaji: 'kazu', meaning: 'số lượng, con số', partOfSpeech: 'danh từ' },
      { kanji: '数字', kana: 'すうじ', romaji: 'sūji', meaning: 'chữ số', partOfSpeech: 'danh từ' },
    ],
  },
];
