// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 947-952.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART9: JlptVocabUnit[] = [
  {
    lessonNumber: 947,
    jlptLevel: 'N1',
    words: [
      { kanji: '跨がります', kana: 'またがります', romaji: 'matagarimasu', meaning: 'cưỡi, dạng chân qua; trải dài qua', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '顧みます', kana: 'かえりみます', romaji: 'kaerimimasu', meaning: 'nhìn lại, hồi tưởng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '御負け', kana: 'おまけ', romaji: 'omake', meaning: 'quà tặng kèm, khuyến mãi', partOfSpeech: 'danh từ' },
      { kanji: '御覧なさい', kana: 'ごらんなさい', romaji: 'gorannasai', meaning: 'hãy xem đi, hãy thử xem', partOfSpeech: 'cụm từ' },
      { kanji: '碁盤', kana: 'ごばん', romaji: 'goban', meaning: 'bàn cờ vây', partOfSpeech: 'danh từ' },
      { kanji: '語源', kana: 'ごげん', romaji: 'gogen', meaning: 'từ nguyên, gốc từ', partOfSpeech: 'danh từ' },
      { kanji: '語彙', kana: 'ごい', romaji: 'goi', meaning: 'vốn từ vựng', partOfSpeech: 'danh từ' },
      { kanji: '誤差', kana: 'ごさ', romaji: 'gosa', meaning: 'sai số', partOfSpeech: 'danh từ' },
      { kanji: '誤魔化します', kana: 'ごまかします', romaji: 'gomakashimasu', meaning: 'lừa gạt, che giấu', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '護衛', kana: 'ごえい', romaji: 'goei', meaning: 'sự hộ tống, bảo vệ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '交えます', kana: 'まじえます', romaji: 'majiemasu', meaning: 'pha trộn, giao thoa', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '交わします', kana: 'かわします', romaji: 'kawashimasu', meaning: 'trao đổi (lời nói), né tránh', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '交易', kana: 'こうえき', romaji: 'kōeki', meaning: 'sự giao thương', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '交互', kana: 'こうご', romaji: 'kōgo', meaning: 'luân phiên, xen kẽ', partOfSpeech: 'danh từ' },
      { kanji: '交付', kana: 'こうふ', romaji: 'kōfu', meaning: 'sự cấp phát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '光沢', kana: 'こうたく', romaji: 'kōtaku', meaning: 'độ bóng, độ sáng', partOfSpeech: 'danh từ' },
      { kanji: '光熱費', kana: 'こうねつひ', romaji: 'kōnetsuhi', meaning: 'chi phí điện nước, ga', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 948,
    jlptLevel: 'N1',
    words: [
      { kanji: '公', kana: 'おおやけ', romaji: 'ōyake', meaning: 'công khai, chính thức', partOfSpeech: 'danh từ' },
      { kanji: '公然', kana: 'こうぜん', romaji: 'kōzen', meaning: 'công khai, ai cũng biết', partOfSpeech: 'tính từ na, phó từ' },
      { kanji: '公団', kana: 'こうだん', romaji: 'kōdan', meaning: 'công đoàn, tổ chức công', partOfSpeech: 'danh từ' },
      { kanji: '公認', kana: 'こうにん', romaji: 'kōnin', meaning: 'sự công nhận chính thức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '公募', kana: 'こうぼ', romaji: 'kōbo', meaning: 'sự tuyển mộ công khai', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '効き目', kana: 'ききめ', romaji: 'kikime', meaning: 'hiệu quả, tác dụng', partOfSpeech: 'danh từ' },
      { kanji: '口ずさみます', kana: 'くちずさみます', romaji: 'kuchizusamimasu', meaning: 'ngâm nga, khe khẽ hát', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '口述', kana: 'こうじゅつ', romaji: 'kōjutsu', meaning: 'lời khai miệng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '向き', kana: 'むき', romaji: 'muki', meaning: 'hướng, xu hướng phù hợp', partOfSpeech: 'danh từ' },
      { kanji: '向け', kana: 'むけ', romaji: 'muke', meaning: 'dành cho, hướng đến', partOfSpeech: 'hậu tố' },
      { kanji: '好ましい', kana: 'このましい', romaji: 'konomashii', meaning: 'đáng ưa thích, dễ chịu', partOfSpeech: 'tính từ i' },
      { kanji: '好意', kana: 'こうい', romaji: 'kōi', meaning: 'thiện ý, cảm tình', partOfSpeech: 'danh từ' },
      { kanji: '工学', kana: 'こうがく', romaji: 'kōgaku', meaning: 'ngành kỹ thuật', partOfSpeech: 'danh từ' },
      { kanji: '工作', kana: 'こうさく', romaji: 'kōsaku', meaning: 'công việc thủ công; sự vận động ngầm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '巧み', kana: 'たくみ', romaji: 'takumi', meaning: 'khéo léo, tinh xảo', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '巧妙', kana: 'こうみょう', romaji: 'kōmyō', meaning: 'tinh vi, khéo léo', partOfSpeech: 'tính từ na' },
      { kanji: '広まります', kana: 'ひろまります', romaji: 'hiromarimasu', meaning: 'lan rộng, được phổ biến', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 949,
    jlptLevel: 'N1',
    words: [
      { kanji: '控室', kana: 'ひかえしつ', romaji: 'hikaeshitsu', meaning: 'phòng chờ', partOfSpeech: 'danh từ' },
      { kanji: '控除', kana: 'こうじょ', romaji: 'kōjo', meaning: 'sự khấu trừ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '攻め', kana: 'せめ', romaji: 'seme', meaning: 'sự tấn công', partOfSpeech: 'danh từ' },
      { kanji: '構え', kana: 'かまえ', romaji: 'kamae', meaning: 'tư thế, dáng vẻ', partOfSpeech: 'danh từ' },
      { kanji: '構えます', kana: 'かまえます', romaji: 'kamaemasu', meaning: 'chuẩn bị tư thế, xây dựng (nhà cửa)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '皇居', kana: 'こうきょ', romaji: 'kōkyo', meaning: 'hoàng cung', partOfSpeech: 'danh từ' },
      { kanji: '考古学', kana: 'こうこがく', romaji: 'kōkogaku', meaning: 'khảo cổ học', partOfSpeech: 'danh từ' },
      { kanji: '荒っぽい', kana: 'あらっぽい', romaji: 'arappoi', meaning: 'thô lỗ, cục cằn', partOfSpeech: 'tính từ i' },
      { kanji: '荒します', kana: 'あらします', romaji: 'arashimasu', meaning: 'tàn phá, phá hoại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '行', kana: 'ぎょう', romaji: 'gyō', meaning: 'hàng, dòng (chữ)', partOfSpeech: 'danh từ' },
      { kanji: '行い', kana: 'おこない', romaji: 'okonai', meaning: 'hành vi, hành động', partOfSpeech: 'danh từ' },
      { kanji: '行き違い', kana: 'いきちがい', romaji: 'ikichigai', meaning: 'sự hiểu lầm, đi lệch nhau', partOfSpeech: 'danh từ' },
      { kanji: '行政', kana: 'ぎょうせい', romaji: 'gyōsei', meaning: 'hành chính', partOfSpeech: 'danh từ' },
      { kanji: '講読', kana: 'こうどく', romaji: 'kōdoku', meaning: 'sự đọc và giải nghĩa văn bản', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '購入', kana: 'こうにゅう', romaji: 'kōnyū', meaning: 'sự mua vào', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '購買', kana: 'こうばい', romaji: 'kōbai', meaning: 'sự mua sắm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '鉱山', kana: 'こうざん', romaji: 'kōzan', meaning: 'mỏ khoáng sản', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 950,
    jlptLevel: 'N1',
    words: [
      { kanji: '香辛料', kana: 'こうしんりょう', romaji: 'kōshinryō', meaning: 'gia vị', partOfSpeech: 'danh từ' },
      { kanji: '高', kana: 'たか', romaji: 'taka', meaning: 'số lượng, tổng số tiền', partOfSpeech: 'danh từ' },
      { kanji: '高まります', kana: 'たかまります', romaji: 'takamarimasu', meaning: 'tăng cao, dâng lên', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '高原', kana: 'こうげん', romaji: 'kōgen', meaning: 'cao nguyên', partOfSpeech: 'danh từ' },
      { kanji: '合わします', kana: 'あわします', romaji: 'awashimasu', meaning: 'ghép lại, làm cho khớp nhau', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '合間', kana: 'あいま', romaji: 'aima', meaning: 'khoảng nghỉ giữa các việc', partOfSpeech: 'danh từ' },
      { kanji: '合唱', kana: 'がっしょう', romaji: 'gasshō', meaning: 'hợp xướng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '合成', kana: 'ごうせい', romaji: 'gōsei', meaning: 'sự tổng hợp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '合致', kana: 'がっち', romaji: 'gacchi', meaning: 'sự phù hợp, trùng khớp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '告げます', kana: 'つげます', romaji: 'tsugemasu', meaning: 'báo cho biết, thông báo', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '告白', kana: 'こくはく', romaji: 'kokuhaku', meaning: 'lời thú nhận, tỏ tình', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '国境', kana: 'くにざかい', romaji: 'kunizakai', meaning: 'biên giới quốc gia', partOfSpeech: 'danh từ' },
      { kanji: '国交', kana: 'こっこう', romaji: 'kokkō', meaning: 'quan hệ ngoại giao', partOfSpeech: 'danh từ' },
      { kanji: '国産', kana: 'こくさん', romaji: 'kokusan', meaning: 'sản xuất trong nước', partOfSpeech: 'danh từ' },
      { kanji: '国定', kana: 'こくてい', romaji: 'kokutei', meaning: 'do nhà nước quy định', partOfSpeech: 'danh từ' },
      { kanji: '国土', kana: 'こくど', romaji: 'kokudo', meaning: 'lãnh thổ quốc gia', partOfSpeech: 'danh từ' },
      { kanji: '国防', kana: 'こくぼう', romaji: 'kokubō', meaning: 'quốc phòng', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 951,
    jlptLevel: 'N1',
    words: [
      { kanji: '国有', kana: 'こくゆう', romaji: 'kokuyū', meaning: 'quốc hữu, thuộc sở hữu nhà nước', partOfSpeech: 'danh từ' },
      { kanji: '骨', kana: 'こつ', romaji: 'kotsu', meaning: 'bí quyết, mẹo', partOfSpeech: 'danh từ' },
      { kanji: '骨董品', kana: 'こっとうひん', romaji: 'kottōhin', meaning: 'đồ cổ', partOfSpeech: 'danh từ' },
      { kanji: '込めます', kana: 'こめます', romaji: 'komemasu', meaning: 'gửi gắm, nạp vào', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '今更', kana: 'いまさら', romaji: 'imasara', meaning: 'giờ mới, bây giờ mới (đã muộn)', partOfSpeech: 'phó từ' },
      { kanji: '昆虫', kana: 'こんちゅう', romaji: 'konchū', meaning: 'côn trùng', partOfSpeech: 'danh từ' },
      { kanji: '根回し', kana: 'ねまわし', romaji: 'nemawashi', meaning: 'sự vận động hậu trường, dàn xếp trước', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '根底', kana: 'こんてい', romaji: 'kontei', meaning: 'nền tảng, gốc rễ', partOfSpeech: 'danh từ' },
      { kanji: '混血', kana: 'こんけつ', romaji: 'konketsu', meaning: 'con lai, hỗn huyết', partOfSpeech: 'danh từ' },
      { kanji: '混同', kana: 'こんどう', romaji: 'kondō', meaning: 'sự lẫn lộn, nhầm lẫn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '左程', kana: 'さほど', romaji: 'sahodo', meaning: 'không mấy, không lắm (đi với phủ định)', partOfSpeech: 'phó từ' },
      { kanji: '左利き', kana: 'ひだりきき', romaji: 'hidarikiki', meaning: 'thuận tay trái', partOfSpeech: 'danh từ' },
      { kanji: '差し引きます', kana: 'さしひきます', romaji: 'sashihikimasu', meaning: 'khấu trừ, trừ đi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '差し掛かります', kana: 'さしかかります', romaji: 'sashikakarimasu', meaning: 'sắp đến gần, sắp tới', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '差し支えます', kana: 'さしつかえます', romaji: 'sashitsukaemasu', meaning: 'gây trở ngại, bất tiện', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '差し出します', kana: 'さしだします', romaji: 'sashidashimasu', meaning: 'đưa ra, trình nộp', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '差額', kana: 'さがく', romaji: 'sagaku', meaning: 'khoản chênh lệch', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 952,
    jlptLevel: 'N1',
    words: [
      { kanji: '砂利', kana: 'じゃり', romaji: 'jari', meaning: 'sỏi đá', partOfSpeech: 'danh từ' },
      { kanji: '座談会', kana: 'ざだんかい', romaji: 'zadankai', meaning: 'buổi tọa đàm', partOfSpeech: 'danh từ' },
      { kanji: '座標', kana: 'ざひょう', romaji: 'zahyō', meaning: 'tọa độ', partOfSpeech: 'danh từ' },
      { kanji: '催します', kana: 'もよおします', romaji: 'moyōshimasu', meaning: 'tổ chức (sự kiện); cảm thấy (buồn ngủ...)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '再現', kana: 'さいげん', romaji: 'saigen', meaning: 'sự tái hiện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '再発', kana: 'さいはつ', romaji: 'saihatsu', meaning: 'sự tái phát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '最善', kana: 'さいぜん', romaji: 'saizen', meaning: 'tốt nhất có thể', partOfSpeech: 'danh từ' },
      { kanji: '採掘', kana: 'さいくつ', romaji: 'saikutsu', meaning: 'sự khai thác (mỏ)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '採決', kana: 'さいけつ', romaji: 'saiketsu', meaning: 'sự biểu quyết', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '採択', kana: 'さいたく', romaji: 'saitaku', meaning: 'sự lựa chọn, thông qua', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '栽培', kana: 'さいばい', romaji: 'saibai', meaning: 'sự trồng trọt, canh tác', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
];
