// Bổ sung kanji N1 — dịch tay (Hán Việt + nghĩa Việt) dựa trên dữ liệu đọc âm
// (onyomi/kunyomi) và stroke count lấy từ kanjiapi.dev (nguồn mở), không auto-scrape nghĩa tiếng Việt.
// KanjiLesson lessonNumber 831-835.

import type { JlptKanjiLesson } from './jlpt-kanji.data';

export const JLPT_KANJI_BOOST4_N1_G: JlptKanjiLesson[] = [
  {
    lessonNumber: 831,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (1)',
    sortOrder: 8310,
    entries: [
      { character: '耗', hanViet: 'HAO', onyomi: 'もう, こう', meaningVi: 'hao mòn, giảm bớt', strokeCount: 10 },
      { character: '聖', hanViet: 'THÁNH', onyomi: 'せい, しょう', kunyomi: 'ひじり', meaningVi: 'thánh nhân', strokeCount: 13 },
      { character: '聡', hanViet: 'THÔNG', onyomi: 'そう', kunyomi: 'さと-い, みみざと-い', meaningVi: 'thông minh', strokeCount: 14 },
      { character: '聴', hanViet: 'THÍNH', onyomi: 'ちょう, てい', kunyomi: 'き-く, ゆる-す', meaningVi: 'lắng nghe', strokeCount: 17 },
      { character: '肖', hanViet: 'TIẾU', onyomi: 'しょう', kunyomi: 'あやか-る', meaningVi: 'giống nhau, chân dung', strokeCount: 7 },
      { character: '肝', hanViet: 'CAN', onyomi: 'かん', kunyomi: 'きも', meaningVi: 'gan', strokeCount: 7 },
      { character: '肢', hanViet: 'CHI', onyomi: 'し', meaningVi: 'chi (tay chân)', strokeCount: 8 },
      { character: '肪', hanViet: 'PHƯƠNG', onyomi: 'ぼう', meaningVi: 'mỡ béo', strokeCount: 8 },
      { character: '胆', hanViet: 'ĐẢM', onyomi: 'たん', kunyomi: 'きも', meaningVi: 'mật; can đảm', strokeCount: 9 },
      { character: '胎', hanViet: 'THAI', onyomi: 'たい', meaningVi: 'bào thai', strokeCount: 9 },
      { character: '胞', hanViet: 'BÀO', onyomi: 'ほう', meaningVi: 'nhau thai; đồng bào', strokeCount: 9 },
      { character: '胡', hanViet: 'HỒ', onyomi: 'う, こ, ご', kunyomi: 'なんぞ', meaningVi: 'người Hồ (ngoại tộc); sao lại', strokeCount: 9 },
      { character: '胴', hanViet: 'ĐỘNG', onyomi: 'どう', meaningVi: 'thân mình (ngực-bụng)', strokeCount: 10 },
      { character: '脚', hanViet: 'CƯỚC', onyomi: 'きゃく, きゃ, かく', kunyomi: 'あし', meaningVi: 'chân, cẳng', strokeCount: 11 },
      { character: '脱', hanViet: 'THOÁT', onyomi: 'だつ', kunyomi: 'ぬ-ぐ, ぬ-げる', meaningVi: 'cởi ra, thoát khỏi', strokeCount: 11 },
      { character: '脹', hanViet: 'TRƯỚNG', onyomi: 'ちょう', kunyomi: 'は-れる, ふく-らむ, ふく-れる', meaningVi: 'phình to, sưng', strokeCount: 12 },
      { character: '膜', hanViet: 'MẠC', onyomi: 'まく', meaningVi: 'màng', strokeCount: 14 },
      { character: '臨', hanViet: 'LÂM', onyomi: 'りん', kunyomi: 'のぞ-む', meaningVi: 'đến gần, đối diện', strokeCount: 18 },
      { character: '至', hanViet: 'CHÍ', onyomi: 'し', kunyomi: 'いた-る', meaningVi: 'đến, tột cùng', strokeCount: 6 },
      { character: '致', hanViet: 'TRÍ', onyomi: 'ち', kunyomi: 'いた-す', meaningVi: 'đưa đến, gây ra', strokeCount: 10 },
    ],
  },
  {
    lessonNumber: 832,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (2)',
    sortOrder: 8320,
    entries: [
      { character: '興', hanViet: 'HƯNG', onyomi: 'こう, きょう', kunyomi: 'おこ-る, おこ-す', meaningVi: 'hưng thịnh, hứng thú', strokeCount: 16 },
      { character: '舌', hanViet: 'THIỆT', onyomi: 'ぜつ', kunyomi: 'した', meaningVi: 'cái lưỡi', strokeCount: 6 },
      { character: '舎', hanViet: 'XÁ', onyomi: 'しゃ, せき', kunyomi: 'やど-る', meaningVi: 'nhà, quán trọ', strokeCount: 8 },
      { character: '舗', hanViet: 'PHỐ', onyomi: 'ほ', meaningVi: 'cửa hàng', strokeCount: 15 },
      { character: '舜', hanViet: 'THUẤN', onyomi: 'しゅん', meaningVi: 'vua Thuấn (Trung Quốc cổ)', strokeCount: 13 },
      { character: '舶', hanViet: 'BẠC', onyomi: 'はく', meaningVi: 'tàu thuyền lớn', strokeCount: 11 },
      { character: '艇', hanViet: 'ĐĨNH', onyomi: 'てい', meaningVi: 'thuyền nhỏ', strokeCount: 13 },
      { character: '艦', hanViet: 'HẠM', onyomi: 'かん', meaningVi: 'chiến hạm', strokeCount: 21 },
      { character: '芋', hanViet: 'VU', onyomi: 'う', kunyomi: 'いも', meaningVi: 'khoai môn, khoai sọ', strokeCount: 6 },
      { character: '芙', hanViet: 'PHÙ', onyomi: 'ふ', meaningVi: 'hoa phù dung', strokeCount: 7 },
      { character: '芝', hanViet: 'CHI', onyomi: 'し', kunyomi: 'しば', meaningVi: 'cỏ linh chi; bãi cỏ', strokeCount: 6 },
      { character: '芳', hanViet: 'PHƯƠNG', onyomi: 'ほう', kunyomi: 'かんば-しい', meaningVi: 'thơm, tốt đẹp', strokeCount: 7 },
      { character: '芹', hanViet: 'CẦN', onyomi: 'きん', kunyomi: 'せり', meaningVi: 'rau cần', strokeCount: 7 },
      { character: '苑', hanViet: 'UYỂN', onyomi: 'えん, おん', kunyomi: 'その, う-つ', meaningVi: 'vườn hoa, công viên', strokeCount: 8 },
      { character: '苗', hanViet: 'MIÊU', onyomi: 'びょう, みょう', kunyomi: 'なえ, なわ-', meaningVi: 'mầm cây, mạ non', strokeCount: 8 },
      { character: '茂', hanViet: 'MẬU', onyomi: 'も', kunyomi: 'しげ-る', meaningVi: 'rậm rạp, tươi tốt', strokeCount: 8 },
      { character: '茄', hanViet: 'GIÀ', onyomi: 'か', meaningVi: 'cà tím', strokeCount: 8 },
      { character: '茅', hanViet: 'MAO', onyomi: 'ぼう, みょう', kunyomi: 'かや, ちがや', meaningVi: 'cỏ tranh', strokeCount: 8 },
      { character: '茉', hanViet: 'MẠT', onyomi: 'まつ, ばつ, ま', meaningVi: 'hoa nhài', strokeCount: 8 },
      { character: '茎', hanViet: 'KINH', onyomi: 'けい, きょう', kunyomi: 'くき', meaningVi: 'thân cây, cuống', strokeCount: 8 },
    ],
  },
  {
    lessonNumber: 833,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (3)',
    sortOrder: 8330,
    entries: [
      { character: '茜', hanViet: 'THIÊN', onyomi: 'せん', kunyomi: 'あかね', meaningVi: 'cây thiến thảo, màu đỏ thẫm', strokeCount: 9 },
      { character: '莉', hanViet: 'LỴ', onyomi: 'り, らい, れい', meaningVi: 'hoa nhài', strokeCount: 10 },
      { character: '菌', hanViet: 'KHUẨN', onyomi: 'きん', meaningVi: 'vi khuẩn, nấm', strokeCount: 11 },
      { character: '菖', hanViet: 'XƯƠNG', onyomi: 'しょう', meaningVi: 'cây xương bồ', strokeCount: 11 },
      { character: '菫', hanViet: 'CẨN', onyomi: 'きん', kunyomi: 'すみれ', meaningVi: 'hoa violet', strokeCount: 11 },
      { character: '華', hanViet: 'HOA', onyomi: 'か, け', kunyomi: 'はな', meaningVi: 'hoa lệ; Trung Hoa', strokeCount: 10 },
      { character: '萌', hanViet: 'MANH', onyomi: 'ほう', kunyomi: 'も-える, きざ-す, めばえ, きざ-し', meaningVi: 'nảy mầm, manh nha', strokeCount: 11 },
      { character: '葵', hanViet: 'QUỲ', onyomi: 'き', kunyomi: 'あおい', meaningVi: 'hoa quỳ, hoa dâm bụt', strokeCount: 12 },
      { character: '蒼', hanViet: 'THƯƠNG', onyomi: 'そう', kunyomi: 'あお-い', meaningVi: 'xanh biếc; già cỗi', strokeCount: 13 },
      { character: '蓉', hanViet: 'DUNG', onyomi: 'よう', meaningVi: 'hoa phù dung', strokeCount: 13 },
      { character: '蓮', hanViet: 'LIÊN', onyomi: 'れん', kunyomi: 'はす, はちす', meaningVi: 'hoa sen', strokeCount: 13 },
      { character: '蕉', hanViet: 'TIÊU', onyomi: 'しょう', meaningVi: 'cây chuối (ba tiêu)', strokeCount: 15 },
      { character: '薦', hanViet: 'TIẾN', onyomi: 'せん', kunyomi: 'すす-める', meaningVi: 'tiến cử, đề cử', strokeCount: 16 },
      { character: '薪', hanViet: 'TÂN', onyomi: 'しん', kunyomi: 'たきぎ, まき', meaningVi: 'củi đốt', strokeCount: 16 },
      { character: '薫', hanViet: 'HUÂN', onyomi: 'くん', kunyomi: 'かお-る', meaningVi: 'tỏa hương thơm', strokeCount: 16 },
      { character: '藍', hanViet: 'LAM', onyomi: 'らん', kunyomi: 'あい', meaningVi: 'màu chàm', strokeCount: 18 },
      { character: '藩', hanViet: 'PHIÊN', onyomi: 'はん', meaningVi: 'phiên trấn, lãnh địa', strokeCount: 18 },
      { character: '藻', hanViet: 'TẢO', onyomi: 'そう', kunyomi: 'も', meaningVi: 'rong tảo', strokeCount: 19 },
      { character: '蘭', hanViet: 'LAN', onyomi: 'らん, ら', meaningVi: 'hoa lan', strokeCount: 19 },
      { character: '虜', hanViet: 'LỖ', onyomi: 'りょ, ろ', kunyomi: 'とりこ, とりく', meaningVi: 'tù binh', strokeCount: 13 },
    ],
  },
  {
    lessonNumber: 834,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (4)',
    sortOrder: 8340,
    entries: [
      { character: '虞', hanViet: 'NGU', onyomi: 'ぐ', kunyomi: 'おそれ, おもんぱか-る, はか-る, うれ-える, あざむ-く, あやま-る, のぞ-む, たの-しむ', meaningVi: 'lo ngại, e sợ', strokeCount: 13 },
      { character: '蚊', hanViet: 'VĂN', onyomi: 'ぶん', kunyomi: 'か', meaningVi: 'con muỗi', strokeCount: 10 },
      { character: '蚕', hanViet: 'TÀM', onyomi: 'さん, てん', kunyomi: 'かいこ, こ', meaningVi: 'con tằm', strokeCount: 10 },
      { character: '蛇', hanViet: 'XÀ', onyomi: 'じゃ, だ, い, や', kunyomi: 'へび', meaningVi: 'con rắn', strokeCount: 11 },
      { character: '蛍', hanViet: 'HUỲNH', onyomi: 'けい', kunyomi: 'ほたる', meaningVi: 'đom đóm', strokeCount: 11 },
      { character: '蛮', hanViet: 'MAN', onyomi: 'ばん', kunyomi: 'えびす', meaningVi: 'man rợ', strokeCount: 12 },
      { character: '蝶', hanViet: 'ĐIỆP', onyomi: 'ちょう', meaningVi: 'con bướm', strokeCount: 15 },
      { character: '街', hanViet: 'NHAI', onyomi: 'がい, かい', kunyomi: 'まち', meaningVi: 'đường phố', strokeCount: 12 },
      { character: '衛', hanViet: 'VỆ', onyomi: 'えい, え', meaningVi: 'bảo vệ, phòng vệ', strokeCount: 16 },
      { character: '衡', hanViet: 'HÀNH', onyomi: 'こう', meaningVi: 'cân bằng, cán cân', strokeCount: 16 },
      { character: '衷', hanViet: 'TRUNG', onyomi: 'ちゅう', meaningVi: 'chân thành, trong lòng', strokeCount: 9 },
      { character: '衿', hanViet: 'KHÂM', onyomi: 'きん, こん', kunyomi: 'えり', meaningVi: 'cổ áo', strokeCount: 9 },
      { character: '袈', hanViet: 'CA', onyomi: 'け, か', meaningVi: 'áo cà sa (phần 1)', strokeCount: 11 },
      { character: '裟', hanViet: 'SA', onyomi: 'さ, しゃ', meaningVi: 'áo cà sa (phần 2)', strokeCount: 13 },
      { character: '裸', hanViet: 'LÕA', onyomi: 'ら', kunyomi: 'はだか', meaningVi: 'trần truồng', strokeCount: 13 },
      { character: '製', hanViet: 'CHẾ', onyomi: 'せい', meaningVi: 'chế tạo', strokeCount: 14 },
      { character: '褐', hanViet: 'CÁT', onyomi: 'かつ', meaningVi: 'màu nâu', strokeCount: 13 },
      { character: '褒', hanViet: 'BAO', onyomi: 'ほう', kunyomi: 'ほ-める', meaningVi: 'khen ngợi', strokeCount: 15 },
      { character: '襟', hanViet: 'KHÂM', onyomi: 'きん', kunyomi: 'えり', meaningVi: 'cổ áo; tấm lòng', strokeCount: 18 },
      { character: '覇', hanViet: 'BÁ', onyomi: 'は, はく', kunyomi: 'はたがしら', meaningVi: 'bá chủ', strokeCount: 19 },
    ],
  },
  {
    lessonNumber: 835,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (5)',
    sortOrder: 8350,
    entries: [
      { character: '覧', hanViet: 'LÃM', onyomi: 'らん', kunyomi: 'み-る', meaningVi: 'xem, duyệt', strokeCount: 17 },
      { character: '訂', hanViet: 'ĐÍNH', onyomi: 'てい', kunyomi: 'ただ-す', meaningVi: 'đính chính, sửa', strokeCount: 9 },
      { character: '詔', hanViet: 'CHIẾU', onyomi: 'しょう', kunyomi: 'みことのり', meaningVi: 'chiếu chỉ vua', strokeCount: 12 },
      { character: '詠', hanViet: 'VỊNH', onyomi: 'えい', kunyomi: 'よ-む, うた-う', meaningVi: 'ngâm vịnh (thơ)', strokeCount: 12 },
      { character: '誓', hanViet: 'THỆ', onyomi: 'せい', kunyomi: 'ちか-う', meaningVi: 'thề nguyền', strokeCount: 14 },
      { character: '誕', hanViet: 'ĐẢN', onyomi: 'たん', meaningVi: 'sinh ra, sinh nhật', strokeCount: 15 },
      { character: '誘', hanViet: 'DỤ', onyomi: 'ゆう', kunyomi: 'さそ-う, いざな-う', meaningVi: 'dụ dỗ, mời gọi', strokeCount: 14 },
      { character: '誼', hanViet: 'NGHỊ', onyomi: 'ぎ', kunyomi: 'よしみ, よい', meaningVi: 'tình nghĩa, tình bạn', strokeCount: 15 },
      { character: '請', hanViet: 'THỈNH', onyomi: 'せい, しん, しょう', kunyomi: 'こ-う, う-ける', meaningVi: 'mời, xin', strokeCount: 15 },
    ],
  },
];
