// Bổ sung kanji N1 — dịch tay (Hán Việt + nghĩa Việt) dựa trên dữ liệu đọc âm
// (onyomi/kunyomi) và stroke count lấy từ kanjiapi.dev (nguồn mở), không auto-scrape nghĩa tiếng Việt.
// KanjiLesson lessonNumber 806-810.

import type { JlptKanjiLesson } from './jlpt-kanji.data';

export const JLPT_KANJI_BOOST4_N1_B: JlptKanjiLesson[] = [
  {
    lessonNumber: 806,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (1)',
    sortOrder: 8060,
    entries: [
      { character: '唯', hanViet: 'DUY', onyomi: 'ゆい, い', kunyomi: 'ただ', meaningVi: 'chỉ, duy nhất', strokeCount: 11 },
      { character: '唱', hanViet: 'XƯỚNG', onyomi: 'しょう', kunyomi: 'とな-える', meaningVi: 'xướng, hát, hô to', strokeCount: 11 },
      { character: '啄', hanViet: 'TRÁC', onyomi: 'たく, つく, とく', kunyomi: 'ついば-む, つつ-く', meaningVi: 'mổ, mổ ăn', strokeCount: 10 },
      { character: '啓', hanViet: 'KHẢI', onyomi: 'けい', kunyomi: 'ひら-く, さと-す', meaningVi: 'khai mở, thông báo', strokeCount: 11 },
      { character: '喚', hanViet: 'HOÁN', onyomi: 'かん', kunyomi: 'わめ-く', meaningVi: 'kêu gào, gọi lớn', strokeCount: 12 },
      { character: '喝', hanViet: 'HÁT', onyomi: 'かつ', meaningVi: 'quát mắng; khàn giọng', strokeCount: 11 },
      { character: '喬', hanViet: 'KIỀU', onyomi: 'きょう', kunyomi: 'たか-い', meaningVi: 'cao, tự phụ', strokeCount: 12 },
      { character: '嗣', hanViet: 'TỰ', onyomi: 'し', meaningVi: 'người thừa kế', strokeCount: 13 },
      { character: '嘉', hanViet: 'GIA', onyomi: 'か', kunyomi: 'よみ-する, よい', meaningVi: 'khen ngợi, tốt lành', strokeCount: 14 },
      { character: '嘱', hanViet: 'CHÚC', onyomi: 'しょく', kunyomi: 'しょく-する, たの-む', meaningVi: 'ủy thác, nhờ cậy', strokeCount: 15 },
      { character: '器', hanViet: 'KHÍ', onyomi: 'き', kunyomi: 'うつわ', meaningVi: 'đồ dùng, dụng cụ', strokeCount: 15 },
      { character: '嚇', hanViet: 'HÁCH', onyomi: 'かく', kunyomi: 'おど-す', meaningVi: 'đe dọa, uy hiếp', strokeCount: 17 },
      { character: '囚', hanViet: 'TÙ', onyomi: 'しゅう', kunyomi: 'とら-われる', meaningVi: 'tù nhân, giam giữ', strokeCount: 5 },
      { character: '圏', hanViet: 'KHUYÊN', onyomi: 'けん', kunyomi: 'かこ-い', meaningVi: 'phạm vi, vòng tròn', strokeCount: 12 },
      { character: '圭', hanViet: 'KHUÊ', onyomi: 'けい, け', meaningVi: 'ngọc khuê; góc cạnh', strokeCount: 6 },
      { character: '坑', hanViet: 'KHANH', onyomi: 'こう', meaningVi: 'hầm, hố', strokeCount: 7 },
      { character: '坪', hanViet: 'BÌNH', onyomi: 'へい', kunyomi: 'つぼ', meaningVi: 'đơn vị diện tích (tsubo)', strokeCount: 8 },
      { character: '垂', hanViet: 'THÙY', onyomi: 'すい', kunyomi: 'た-れる, た-らす, た-れ, -た-れ, なんなんと-す', meaningVi: 'rủ xuống, treo', strokeCount: 8 },
      { character: '垣', hanViet: 'VIÊN', onyomi: 'えん', kunyomi: 'かき', meaningVi: 'hàng rào', strokeCount: 9 },
      { character: '基', hanViet: 'CƠ', onyomi: 'き', kunyomi: 'もと, もとい', meaningVi: 'nền tảng, cơ bản', strokeCount: 11 },
    ],
  },
  {
    lessonNumber: 807,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (2)',
    sortOrder: 8070,
    entries: [
      { character: '堀', hanViet: 'QUẬT', onyomi: 'くつ', kunyomi: 'ほり', meaningVi: 'hào, mương', strokeCount: 11 },
      { character: '堅', hanViet: 'KIÊN', onyomi: 'けん', kunyomi: 'かた-い, -がた-い', meaningVi: 'kiên cố, cứng chắc', strokeCount: 12 },
      { character: '堕', hanViet: 'ĐỌA', onyomi: 'だ', kunyomi: 'お-ちる, くず-す, くず-れる', meaningVi: 'sa đọa, rơi xuống', strokeCount: 12 },
      { character: '堤', hanViet: 'ĐỀ', onyomi: 'てい', kunyomi: 'つつみ', meaningVi: 'con đê', strokeCount: 12 },
      { character: '堪', hanViet: 'KHẢM', onyomi: 'かん, たん', kunyomi: 'た-える, たま-る, こら-える, こた-える', meaningVi: 'chịu đựng, kham nổi', strokeCount: 12 },
      { character: '塀', hanViet: 'BÌNH', onyomi: 'へい, べい', meaningVi: 'tường rào (quốc tự)', strokeCount: 12 },
      { character: '塁', hanViet: 'LŨY', onyomi: 'るい, らい, すい', kunyomi: 'とりで', meaningVi: 'lũy, thành lũy; gôn (bóng chày)', strokeCount: 12 },
      { character: '塊', hanViet: 'KHỐI', onyomi: 'かい, け', kunyomi: 'かたまり, つちくれ', meaningVi: 'khối, cục', strokeCount: 13 },
      { character: '塑', hanViet: 'TỐ', onyomi: 'そ', kunyomi: 'でく', meaningVi: 'tạo hình, nặn tượng', strokeCount: 13 },
      { character: '塚', hanViet: 'TRỦNG', onyomi: 'ちょう', kunyomi: 'つか, -づか', meaningVi: 'gò mộ', strokeCount: 12 },
      { character: '塾', hanViet: 'THỤC', onyomi: 'じゅく', meaningVi: 'trường tư, lớp học thêm', strokeCount: 14 },
      { character: '墜', hanViet: 'TRỤY', onyomi: 'つい', kunyomi: 'お-ちる, お-つ', meaningVi: 'rơi, sụp đổ', strokeCount: 15 },
      { character: '墳', hanViet: 'PHẦN', onyomi: 'ふん', meaningVi: 'mộ, mồ', strokeCount: 15 },
      { character: '墾', hanViet: 'KHẨN', onyomi: 'こん', kunyomi: 'は-る, ひら-く', meaningVi: 'khai khẩn đất', strokeCount: 16 },
      { character: '壁', hanViet: 'BÍCH', onyomi: 'へき', kunyomi: 'かべ', meaningVi: 'tường vách', strokeCount: 16 },
      { character: '壇', hanViet: 'ĐÀN', onyomi: 'だん, たん', meaningVi: 'bục, đàn tế', strokeCount: 16 },
      { character: '壌', hanViet: 'NHƯỠNG', onyomi: 'じょう', kunyomi: 'つち', meaningVi: 'đất đai', strokeCount: 16 },
      { character: '壮', hanViet: 'TRÁNG', onyomi: 'そう', kunyomi: 'さかん', meaningVi: 'tráng kiện, hùng tráng', strokeCount: 6 },
      { character: '壱', hanViet: 'NHẤT', onyomi: 'いち, いつ', kunyomi: 'ひとつ', meaningVi: 'số một (dùng trong văn kiện)', strokeCount: 7 },
      { character: '奈', hanViet: 'NẠI', onyomi: 'な, ない, だい', kunyomi: 'いかん, からなし', meaningVi: 'sao, thế nào (như trong 奈良 Nara)', strokeCount: 8 },
    ],
  },
  {
    lessonNumber: 808,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (3)',
    sortOrder: 8080,
    entries: [
      { character: '奉', hanViet: 'PHỤNG', onyomi: 'ほう, ぶ', kunyomi: 'たてまつ-る, まつ-る, ほう-ずる', meaningVi: 'phụng sự, dâng tặng', strokeCount: 8 },
      { character: '奎', hanViet: 'KHUÊ', onyomi: 'けい, き', meaningVi: 'sao Khuê', strokeCount: 9 },
      { character: '奔', hanViet: 'BÔN', onyomi: 'ほん', kunyomi: 'はし-る', meaningVi: 'chạy, bôn ba', strokeCount: 8 },
      { character: '奨', hanViet: 'TƯỞNG', onyomi: 'しょう, そう', kunyomi: 'すす-める', meaningVi: 'khuyến khích', strokeCount: 13 },
      { character: '奴', hanViet: 'NÔ', onyomi: 'ど', kunyomi: 'やつ, やっこ', meaningVi: 'nô lệ; gã (khinh miệt)', strokeCount: 5 },
      { character: '妃', hanViet: 'PHI', onyomi: 'ひ', kunyomi: 'きさき', meaningVi: 'vương phi', strokeCount: 6 },
      { character: '妄', hanViet: 'VỌNG', onyomi: 'もう, ぼう', kunyomi: 'みだ-りに', meaningVi: 'vọng tưởng, càn bậy', strokeCount: 6 },
      { character: '妊', hanViet: 'NHÂM', onyomi: 'にん, じん', kunyomi: 'はら-む, みごも-る', meaningVi: 'mang thai', strokeCount: 7 },
      { character: '姫', hanViet: 'CƠ', onyomi: 'き', kunyomi: 'ひめ, ひめ-', meaningVi: 'công chúa', strokeCount: 10 },
      { character: '姻', hanViet: 'NHÂN', onyomi: 'いん', meaningVi: 'hôn nhân', strokeCount: 9 },
      { character: '姿', hanViet: 'TƯ', onyomi: 'し', kunyomi: 'すがた', meaningVi: 'dáng vẻ, tư thế', strokeCount: 9 },
      { character: '娠', hanViet: 'THẦN', onyomi: 'しん', meaningVi: 'mang thai', strokeCount: 10 },
      { character: '娯', hanViet: 'NGU', onyomi: 'ご', meaningVi: 'vui chơi, giải trí', strokeCount: 10 },
      { character: '婆', hanViet: 'BÀ', onyomi: 'ば', kunyomi: 'ばば, ばあ', meaningVi: 'bà già', strokeCount: 11 },
      { character: '媒', hanViet: 'MÔI', onyomi: 'ばい', kunyomi: 'なこうど', meaningVi: 'mai mối, môi giới', strokeCount: 12 },
      { character: '媛', hanViet: 'VIÊN', onyomi: 'えん', kunyomi: 'ひめ', meaningVi: 'người đẹp, công chúa', strokeCount: 12 },
      { character: '嫌', hanViet: 'HIỀM', onyomi: 'けん, げん', kunyomi: 'きら-う, きら-い, いや', meaningVi: 'ghét, hiềm nghi', strokeCount: 13 },
      { character: '嫡', hanViet: 'ĐÍCH', onyomi: 'ちゃく, てき', meaningVi: 'con vợ cả, chính thất', strokeCount: 14 },
      { character: '嬉', hanViet: 'HI', onyomi: 'き', kunyomi: 'うれ-しい, たの-しむ', meaningVi: 'vui mừng', strokeCount: 15 },
      { character: '嬢', hanViet: 'NƯƠNG', onyomi: 'じょう', kunyomi: 'むすめ', meaningVi: 'cô gái, tiểu thư', strokeCount: 16 },
    ],
  },
  {
    lessonNumber: 809,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (4)',
    sortOrder: 8090,
    entries: [
      { character: '孔', hanViet: 'KHỔNG', onyomi: 'こう, く', kunyomi: 'あな', meaningVi: 'lỗ hổng; họ Khổng', strokeCount: 4 },
      { character: '孟', hanViet: 'MẠNH', onyomi: 'もう, ぼう, みょう', kunyomi: 'かしら', meaningVi: 'đầu tiên; họ Mạnh', strokeCount: 8 },
      { character: '宏', hanViet: 'HOẰNG', onyomi: 'こう', kunyomi: 'ひろ-い', meaningVi: 'rộng lớn', strokeCount: 7 },
      { character: '宗', hanViet: 'TÔNG', onyomi: 'しゅう, そう', kunyomi: 'むね', meaningVi: 'tông giáo, dòng họ', strokeCount: 8 },
      { character: '宙', hanViet: 'TRỤ', onyomi: 'ちゅう', meaningVi: 'không trung, vũ trụ', strokeCount: 8 },
      { character: '宜', hanViet: 'NGHI', onyomi: 'ぎ', kunyomi: 'よろ-しい, よろ-しく', meaningVi: 'thích hợp, nên', strokeCount: 8 },
      { character: '宥', hanViet: 'HỰU', onyomi: 'ゆう', kunyomi: 'なだ-める, ゆる-す', meaningVi: 'tha thứ, xoa dịu', strokeCount: 9 },
      { character: '宮', hanViet: 'CUNG', onyomi: 'きゅう, ぐう, く, くう', kunyomi: 'みや', meaningVi: 'cung điện, đền thờ', strokeCount: 10 },
      { character: '宰', hanViet: 'TỂ', onyomi: 'さい', meaningVi: 'tể tướng, cai quản', strokeCount: 10 },
      { character: '寂', hanViet: 'TỊCH', onyomi: 'じゃく, せき', kunyomi: 'さび, さび-しい, さび-れる, さみ-しい', meaningVi: 'tịch mịch, cô đơn', strokeCount: 11 },
      { character: '寅', hanViet: 'DẦN', onyomi: 'いん', kunyomi: 'とら', meaningVi: 'năm/giờ Dần (con hổ)', strokeCount: 11 },
      { character: '寛', hanViet: 'KHOAN', onyomi: 'かん', kunyomi: 'くつろ-ぐ, ひろ-い, ゆる-やか', meaningVi: 'khoan dung, rộng lượng', strokeCount: 13 },
      { character: '寡', hanViet: 'QUẢ', onyomi: 'か', meaningVi: 'góa bụa; ít', strokeCount: 14 },
      { character: '寧', hanViet: 'NINH', onyomi: 'ねい', kunyomi: 'むし-ろ', meaningVi: 'thà rằng; yên ổn', strokeCount: 14 },
      { character: '寮', hanViet: 'LIÊU', onyomi: 'りょう', meaningVi: 'ký túc xá', strokeCount: 15 },
      { character: '寸', hanViet: 'THỐN', onyomi: 'すん', meaningVi: 'đơn vị đo lường (tấc)', strokeCount: 3 },
      { character: '射', hanViet: 'XẠ', onyomi: 'しゃ', kunyomi: 'い-る, さ-す, う-つ', meaningVi: 'bắn, chiếu', strokeCount: 10 },
      { character: '尉', hanViet: 'ÚY', onyomi: 'い, じょう', meaningVi: 'chức quan úy', strokeCount: 11 },
      { character: '尋', hanViet: 'TẦM', onyomi: 'じん', kunyomi: 'たず-ねる, ひろ', meaningVi: 'tìm kiếm; đơn vị đo (tầm)', strokeCount: 12 },
      { character: '尚', hanViet: 'THƯỢNG', onyomi: 'しょう', kunyomi: 'なお', meaningVi: 'hơn nữa, còn', strokeCount: 8 },
    ],
  },
  {
    lessonNumber: 810,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (5)',
    sortOrder: 8100,
    entries: [
      { character: '尭', hanViet: 'NGHIÊU', onyomi: 'ぎょう', kunyomi: 'たか-い', meaningVi: 'vua Nghiêu; cao', strokeCount: 8 },
      { character: '尺', hanViet: 'XÍCH', onyomi: 'しゃく, せき', kunyomi: 'さし', meaningVi: 'đơn vị đo lường (thước)', strokeCount: 4 },
      { character: '尼', hanViet: 'NI', onyomi: 'に', kunyomi: 'あま', meaningVi: 'ni cô', strokeCount: 5 },
      { character: '尽', hanViet: 'TẬN', onyomi: 'じん, さん', kunyomi: 'つ-きる, つ-くす, つ-かす, -づ-く, -ず-く, ことごと-く', meaningVi: 'hết, cạn kiệt', strokeCount: 6 },
      { character: '尾', hanViet: 'VĨ', onyomi: 'び', kunyomi: 'お', meaningVi: 'cái đuôi', strokeCount: 7 },
      { character: '尿', hanViet: 'NIỆU', onyomi: 'にょう', kunyomi: 'ゆばり, いばり, しと', meaningVi: 'nước tiểu', strokeCount: 7 },
      { character: '屈', hanViet: 'KHUẤT', onyomi: 'くつ', kunyomi: 'かが-む, かが-める', meaningVi: 'khuất phục, cong', strokeCount: 8 },
      { character: '展', hanViet: 'TRIỂN', onyomi: 'てん', meaningVi: 'triển khai, mở rộng', strokeCount: 10 },
      { character: '履', hanViet: 'LÝ', onyomi: 'り', kunyomi: 'は-く', meaningVi: 'thực hiện; giày dép', strokeCount: 15 },
      { character: '屯', hanViet: 'ĐỒN', onyomi: 'とん', kunyomi: 'たむろ', meaningVi: 'đồn trú, doanh trại', strokeCount: 4 },
      { character: '岐', hanViet: 'KỲ', onyomi: 'き, ぎ', meaningVi: 'rẽ nhánh, ngã rẽ', strokeCount: 7 },
      { character: '岬', hanViet: 'GIÁP', onyomi: 'こう', kunyomi: 'みさき', meaningVi: 'mũi đất (địa lý)', strokeCount: 8 },
      { character: '岳', hanViet: 'NHẠC', onyomi: 'がく', kunyomi: 'たけ', meaningVi: 'núi lớn', strokeCount: 8 },
      { character: '峡', hanViet: 'HIỆP', onyomi: 'きょう, こう', kunyomi: 'はざま', meaningVi: 'eo núi, hẻm núi', strokeCount: 9 },
      { character: '峰', hanViet: 'PHONG', onyomi: 'ほう', kunyomi: 'みね, ね', meaningVi: 'đỉnh núi', strokeCount: 10 },
      { character: '峻', hanViet: 'TUẤN', onyomi: 'しゅん', kunyomi: 'けわ-しい, たか-い', meaningVi: 'cao, dốc đứng', strokeCount: 10 },
      { character: '崚', hanViet: 'LĂNG', onyomi: 'りょう', meaningVi: 'núi trùng điệp', strokeCount: 11 },
      { character: '嵩', hanViet: 'TUNG', onyomi: 'すう, しゅう', kunyomi: 'かさ, かさ-む, たか-い', meaningVi: 'cao, chồng chất', strokeCount: 13 },
      { character: '嵯', hanViet: 'TA', onyomi: 'さ, し', meaningVi: 'gồ ghề, dốc đứng', strokeCount: 13 },
      { character: '嶺', hanViet: 'LĨNH', onyomi: 'れい, りょう', kunyomi: 'みね', meaningVi: 'đỉnh núi, dãy núi', strokeCount: 17 },
    ],
  },
];
