// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 929-934.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART6: JlptVocabUnit[] = [
  {
    lessonNumber: 929,
    jlptLevel: 'N1',
    words: [
      { kanji: '感度', kana: 'かんど', romaji: 'kando', meaning: 'độ nhạy', partOfSpeech: 'danh từ' },
      { kanji: '慣らします', kana: 'ならします', romaji: 'narashimasu', meaning: 'làm quen dần, huấn luyện', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '慣れ', kana: 'なれ', romaji: 'nare', meaning: 'sự quen thuộc, kinh nghiệm', partOfSpeech: 'danh từ' },
      { kanji: '換算', kana: 'かんさん', romaji: 'kansan', meaning: 'sự quy đổi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '漢語', kana: 'かんご', romaji: 'kango', meaning: 'từ Hán (từ gốc Hán trong tiếng Nhật)', partOfSpeech: 'danh từ' },
      { kanji: '甘えます', kana: 'あまえます', romaji: 'amaemasu', meaning: 'nũng nịu, làm nũng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '甘口', kana: 'あまくち', romaji: 'amakuchi', meaning: 'vị ngọt; lời nịnh', partOfSpeech: 'danh từ' },
      { kanji: '竿', kana: 'さお', romaji: 'sao', meaning: 'cây sào', partOfSpeech: 'danh từ' },
      { kanji: '簡易', kana: 'かんい', romaji: 'kani', meaning: 'đơn giản, dễ dàng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '緩みます', kana: 'ゆるみます', romaji: 'yurumimasu', meaning: 'trở nên lỏng, chùng xuống', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '緩めます', kana: 'ゆるめます', romaji: 'yurumemasu', meaning: 'nới lỏng, giảm tốc', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '肝心', kana: 'かんじん', romaji: 'kanjin', meaning: 'cốt yếu, quan trọng nhất', partOfSpeech: 'tính từ na' },
      { kanji: '観覧', kana: 'かんらん', romaji: 'kanran', meaning: 'sự xem, tham quan', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '貫きます', kana: 'つらぬきます', romaji: 'tsuranukimasu', meaning: 'xuyên qua, giữ vững (lập trường)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '貫禄', kana: 'かんろく', romaji: 'kanroku', meaning: 'phong thái uy nghi, khí chất', partOfSpeech: 'danh từ' },
      { kanji: '還元', kana: 'かんげん', romaji: 'kangen', meaning: 'sự trả lại, hoàn nguyên', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '還暦', kana: 'かんれき', romaji: 'kanreki', meaning: 'lễ mừng thọ 60 tuổi', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 930,
    jlptLevel: 'N1',
    words: [
      { kanji: '間々', kana: 'まま', romaji: 'mama', meaning: 'thỉnh thoảng, đôi khi', partOfSpeech: 'phó từ' },
      { kanji: '間違います', kana: 'まちがいます', romaji: 'machigaimasu', meaning: 'nhầm lẫn, sai sót', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '間柄', kana: 'あいだがら', romaji: 'aidagara', meaning: 'mối quan hệ (giữa người với người)', partOfSpeech: 'danh từ' },
      { kanji: '関税', kana: 'かんぜい', romaji: 'kanzei', meaning: 'thuế quan', partOfSpeech: 'danh từ' },
      { kanji: '関与', kana: 'かんよ', romaji: 'kanyo', meaning: 'sự tham gia, dính líu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '丸々', kana: 'まるまる', romaji: 'marumaru', meaning: 'hoàn toàn, tròn trịa', partOfSpeech: 'phó từ' },
      { kanji: '丸ごと', kana: 'まるごと', romaji: 'marugoto', meaning: 'nguyên vẹn, cả khối', partOfSpeech: 'phó từ' },
      { kanji: '丸っきり', kana: 'まるっきり', romaji: 'marukkiri', meaning: 'hoàn toàn (không)', partOfSpeech: 'phó từ' },
      { kanji: '丸めます', kana: 'まるめます', romaji: 'marumemasu', meaning: 'vo tròn, cuộn lại', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '癌', kana: 'がん', romaji: 'gan', meaning: 'bệnh ung thư', partOfSpeech: 'danh từ' },
      { kanji: '眼科', kana: 'がんか', romaji: 'ganka', meaning: 'khoa mắt (nhãn khoa)', partOfSpeech: 'danh từ' },
      { kanji: '眼球', kana: 'がんきゅう', romaji: 'gankyū', meaning: 'nhãn cầu', partOfSpeech: 'danh từ' },
      { kanji: '岩石', kana: 'がんせき', romaji: 'ganseki', meaning: 'đá, nham thạch', partOfSpeech: 'danh từ' },
      { kanji: '贋物', kana: 'がんぶつ', romaji: 'ganbutsu', meaning: 'hàng giả, đồ nhái', partOfSpeech: 'danh từ' },
      { kanji: '頑丈', kana: 'がんじょう', romaji: 'ganjō', meaning: 'chắc chắn, vững chãi', partOfSpeech: 'tính từ na' },
      { kanji: '顔付き', kana: 'かおつき', romaji: 'kaotsuki', meaning: 'nét mặt, biểu cảm', partOfSpeech: 'danh từ' },
      { kanji: '願書', kana: 'がんしょ', romaji: 'gansho', meaning: 'đơn xin, hồ sơ đăng ký', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 931,
    jlptLevel: 'N1',
    words: [
      { kanji: '企画', kana: 'きかく', romaji: 'kikaku', meaning: 'kế hoạch, dự án', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '危ぶみます', kana: 'あやぶみます', romaji: 'ayabumimasu', meaning: 'lo ngại, nghi ngờ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '危害', kana: 'きがい', romaji: 'kigai', meaning: 'sự gây hại, nguy hiểm', partOfSpeech: 'danh từ' },
      { kanji: '喜劇', kana: 'きげき', romaji: 'kigeki', meaning: 'hài kịch', partOfSpeech: 'danh từ' },
      { kanji: '器', kana: 'うつわ', romaji: 'utsuwa', meaning: 'cái bát, vật đựng', partOfSpeech: 'danh từ' },
      { kanji: '奇数', kana: 'きすう', romaji: 'kisū', meaning: 'số lẻ', partOfSpeech: 'danh từ' },
      { kanji: '寄り掛かります', kana: 'よりかかります', romaji: 'yorikakarimasu', meaning: 'dựa vào, tựa vào', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '寄贈', kana: 'きそう', romaji: 'kisō', meaning: 'sự tặng, quyên góp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '寄与', kana: 'きよ', romaji: 'kiyo', meaning: 'sự đóng góp, cống hiến', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '幾多', kana: 'いくた', romaji: 'ikuta', meaning: 'vô số, nhiều', partOfSpeech: 'phó từ' },
      { kanji: '既婚', kana: 'きこん', romaji: 'kikon', meaning: 'đã kết hôn', partOfSpeech: 'danh từ' },
      { kanji: '期日', kana: 'きじつ', romaji: 'kijitsu', meaning: 'kỳ hạn, ngày quy định', partOfSpeech: 'danh từ' },
      { kanji: '期末', kana: 'きまつ', romaji: 'kimatsu', meaning: 'cuối kỳ, cuối học kỳ', partOfSpeech: 'danh từ' },
      { kanji: '帰京', kana: 'ききょう', romaji: 'kikyō', meaning: 'sự trở về Tokyo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '気まぐれ', kana: 'きまぐれ', romaji: 'kimagure', meaning: 'tính khí thất thường', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '気楽', kana: 'きらく', romaji: 'kiraku', meaning: 'thoải mái, nhẹ nhàng', partOfSpeech: 'tính từ na' },
      { kanji: '気軽', kana: 'きがる', romaji: 'kigaru', meaning: 'vô tư, thoải mái (không câu nệ)', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 932,
    jlptLevel: 'N1',
    words: [
      { kanji: '気兼ね', kana: 'きがね', romaji: 'kigane', meaning: 'sự e ngại, ngại làm phiền', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '気質', kana: 'かたぎ', romaji: 'katagi', meaning: 'tính khí, khí chất (đặc trưng nghề nghiệp)', partOfSpeech: 'danh từ' },
      { kanji: '気障', kana: 'きざ', romaji: 'kiza', meaning: 'làm bộ, làm điệu', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '気触れます', kana: 'かぶれます', romaji: 'kaburemasu', meaning: 'bị dị ứng da; bị ảnh hưởng (tư tưởng)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '気品', kana: 'きひん', romaji: 'kihin', meaning: 'sự thanh cao, phong thái sang trọng', partOfSpeech: 'danh từ' },
      { kanji: '気風', kana: 'きふう', romaji: 'kifū', meaning: 'khí chất, tinh thần chung', partOfSpeech: 'danh từ' },
      { kanji: '気立て', kana: 'きだて', romaji: 'kidate', meaning: 'tính tình, tính nết', partOfSpeech: 'danh từ' },
      { kanji: '気流', kana: 'きりゅう', romaji: 'kiryū', meaning: 'luồng khí, khí lưu', partOfSpeech: 'danh từ' },
      { kanji: '祈り', kana: 'いのり', romaji: 'inori', meaning: 'lời cầu nguyện', partOfSpeech: 'danh từ' },
      { kanji: '規定', kana: 'きてい', romaji: 'kitei', meaning: 'quy định', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '規模', kana: 'きぼ', romaji: 'kibo', meaning: 'quy mô', partOfSpeech: 'danh từ' },
      { kanji: '規約', kana: 'きやく', romaji: 'kiyaku', meaning: 'quy ước, điều lệ', partOfSpeech: 'danh từ' },
      { kanji: '記します', kana: 'しるします', romaji: 'shirushimasu', meaning: 'ghi chép lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '記載', kana: 'きさい', romaji: 'kisai', meaning: 'sự ghi chép, ghi vào', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '記述', kana: 'きじゅつ', romaji: 'kijutsu', meaning: 'sự mô tả, miêu thuật', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '記名', kana: 'きめい', romaji: 'kimei', meaning: 'sự ký tên', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '貴い', kana: 'たっとい', romaji: 'tattoi', meaning: 'quý báu, cao quý', partOfSpeech: 'tính từ i' },
    ],
  },
  {
    lessonNumber: 933,
    jlptLevel: 'N1',
    words: [
      { kanji: '貴族', kana: 'きぞく', romaji: 'kizoku', meaning: 'quý tộc', partOfSpeech: 'danh từ' },
      { kanji: '起点', kana: 'きてん', romaji: 'kiten', meaning: 'điểm xuất phát', partOfSpeech: 'danh từ' },
      { kanji: '起伏', kana: 'きふく', romaji: 'kifuku', meaning: 'sự thăng trầm, gập ghềnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '軌道', kana: 'きどう', romaji: 'kidō', meaning: 'quỹ đạo, đường ray', partOfSpeech: 'danh từ' },
      { kanji: '戯曲', kana: 'ぎきょく', romaji: 'gikyoku', meaning: 'kịch bản sân khấu', partOfSpeech: 'danh từ' },
      { kanji: '技', kana: 'わざ', romaji: 'waza', meaning: 'kỹ thuật, thủ thuật', partOfSpeech: 'danh từ' },
      { kanji: '技能', kana: 'ぎのう', romaji: 'ginō', meaning: 'kỹ năng, tay nghề', partOfSpeech: 'danh từ' },
      { kanji: '欺きます', kana: 'あざむきます', romaji: 'azamukimasu', meaning: 'lừa dối, đánh lừa', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '犠牲', kana: 'ぎせい', romaji: 'gisei', meaning: 'sự hy sinh', partOfSpeech: 'danh từ' },
      { kanji: '疑惑', kana: 'ぎわく', romaji: 'giwaku', meaning: 'sự nghi ngờ, hoài nghi', partOfSpeech: 'danh từ' },
      { kanji: '義理', kana: 'ぎり', romaji: 'giri', meaning: 'nghĩa vụ, đạo nghĩa', partOfSpeech: 'danh từ' },
      { kanji: '議案', kana: 'ぎあん', romaji: 'gian', meaning: 'dự luật, đề án', partOfSpeech: 'danh từ' },
      { kanji: '議決', kana: 'ぎけつ', romaji: 'giketsu', meaning: 'sự biểu quyết, nghị quyết', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '議事堂', kana: 'ぎじどう', romaji: 'gijidō', meaning: 'tòa nhà quốc hội', partOfSpeech: 'danh từ' },
      { kanji: '議題', kana: 'ぎだい', romaji: 'gidai', meaning: 'chủ đề nghị sự', partOfSpeech: 'danh từ' },
      { kanji: '鞠', kana: 'まり', romaji: 'mari', meaning: 'quả bóng (đồ chơi truyền thống)', partOfSpeech: 'danh từ' },
      { kanji: '喫茶', kana: 'きっさ', romaji: 'kissa', meaning: 'việc uống trà, quán trà', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 934,
    jlptLevel: 'N1',
    words: [
      { kanji: '詰ります', kana: 'なじります', romaji: 'najirimasu', meaning: 'trách móc, quở trách', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '客観', kana: 'きゃっかん', romaji: 'kyakkan', meaning: 'tính khách quan', partOfSpeech: 'danh từ' },
      { kanji: '脚色', kana: 'きゃくしょく', romaji: 'kyakushoku', meaning: 'sự chuyển thể kịch bản', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '逆転', kana: 'ぎゃくてん', romaji: 'gyakuten', meaning: 'sự đảo ngược tình thế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '逆立ち', kana: 'さかだち', romaji: 'sakadachi', meaning: 'trồng cây chuối (thể dục)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '久しい', kana: 'ひさしい', romaji: 'hisashii', meaning: 'đã lâu, lâu dài', partOfSpeech: 'tính từ i' },
      { kanji: '休めます', kana: 'やすめます', romaji: 'yasumemasu', meaning: 'cho nghỉ ngơi, tạm dừng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '休学', kana: 'きゅうがく', romaji: 'kyūgaku', meaning: 'sự nghỉ học tạm thời', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '休戦', kana: 'きゅうせん', romaji: 'kyūsen', meaning: 'sự đình chiến', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '及び', kana: 'および', romaji: 'oyobi', meaning: 'và, cùng với', partOfSpeech: 'liên từ' },
      { kanji: '及びます', kana: 'およびます', romaji: 'oyobimasu', meaning: 'đạt đến, lan tới', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '宮殿', kana: 'きゅうでん', romaji: 'kyūden', meaning: 'cung điện', partOfSpeech: 'danh từ' },
    ],
  },
];
