// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 917-922.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART4: JlptVocabUnit[] = [
  {
    lessonNumber: 917,
    jlptLevel: 'N1',
    words: [
      { kanji: '一括', kana: 'いっかつ', romaji: 'ikkatsu', meaning: 'gộp lại, tổng hợp một lần', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '一気', kana: 'いっき', romaji: 'ikki', meaning: 'một hơi, một mạch', partOfSpeech: 'danh từ' },
      { kanji: '一挙に', kana: 'いっきょに', romaji: 'ikkyoni', meaning: 'cùng một lúc, ngay lập tức', partOfSpeech: 'phó từ' },
      { kanji: '一筋', kana: 'ひとすじ', romaji: 'hitosuji', meaning: 'một sợi, một lòng một dạ', partOfSpeech: 'danh từ' },
      { kanji: '一見', kana: 'いっけん', romaji: 'ikken', meaning: 'thoáng nhìn, mới nhìn qua', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '一頃', kana: 'ひところ', romaji: 'hitokoro', meaning: 'có một dạo, có thời', partOfSpeech: 'danh từ' },
      { kanji: '一人', kana: 'いちにん', romaji: 'ichinin', meaning: 'một người', partOfSpeech: 'danh từ' },
      { kanji: '一切', kana: 'いっさい', romaji: 'issai', meaning: 'tất cả, hoàn toàn', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '一息', kana: 'ひといき', romaji: 'hitoiki', meaning: 'một hơi thở, một chút nghỉ ngơi', partOfSpeech: 'danh từ' },
      { kanji: '一同', kana: 'いちどう', romaji: 'ichidō', meaning: 'tất cả mọi người có mặt', partOfSpeech: 'danh từ' },
      { kanji: '一部', kana: 'いちぶ', romaji: 'ichibu', meaning: 'một phần; một bản (tài liệu)', partOfSpeech: 'danh từ' },
      { kanji: '一変', kana: 'いっぺん', romaji: 'ippen', meaning: 'sự thay đổi hoàn toàn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '一面', kana: 'いちめん', romaji: 'ichimen', meaning: 'một mặt, trang nhất (báo)', partOfSpeech: 'danh từ' },
      { kanji: '一目', kana: 'いちもく', romaji: 'ichimoku', meaning: 'một cái liếc nhìn', partOfSpeech: 'danh từ' },
      { kanji: '一様', kana: 'いちよう', romaji: 'ichiyō', meaning: 'đồng nhất, giống nhau', partOfSpeech: 'tính từ na' },
      { kanji: '一連', kana: 'いちれん', romaji: 'ichiren', meaning: 'một loạt, một chuỗi', partOfSpeech: 'danh từ' },
      { kanji: '逸らします', kana: 'そらします', romaji: 'sorashimasu', meaning: 'hướng đi chỗ khác, lảng tránh', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 918,
    jlptLevel: 'N1',
    words: [
      { kanji: '稲光', kana: 'いなびかり', romaji: 'inabikari', meaning: 'ánh chớp', partOfSpeech: 'danh từ' },
      { kanji: '印', kana: 'いん', romaji: 'in', meaning: 'con dấu, dấu ấn', partOfSpeech: 'danh từ' },
      { kanji: '引きずります', kana: 'ひきずります', romaji: 'hikizurimasu', meaning: 'kéo lê', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '引き下げます', kana: 'ひきさげます', romaji: 'hikisagemasu', meaning: 'hạ xuống, giảm bớt', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '引き起こします', kana: 'ひきおこします', romaji: 'hikiokoshimasu', meaning: 'gây ra, dẫn đến', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '引き取ります', kana: 'ひきとります', romaji: 'hikitorimasu', meaning: 'nhận về, đảm nhận', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '引き上げます', kana: 'ひきあげます', romaji: 'hikiagemasu', meaning: 'rút lui, kéo lên, nâng lên', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '引っ掛けます', kana: 'ひっかけます', romaji: 'hikkakemasu', meaning: 'móc vào, khoác lên; lừa gạt', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '引っ掻きます', kana: 'ひっかきます', romaji: 'hikkakimasu', meaning: 'cào, gãi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '飲み込みます', kana: 'のみこみます', romaji: 'nomikomimasu', meaning: 'nuốt xuống; hiểu rõ, nắm bắt', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '陰気', kana: 'いんき', romaji: 'inki', meaning: 'u ám, ảm đạm', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '隠居', kana: 'いんきょ', romaji: 'inkyo', meaning: 'sự nghỉ hưu, ẩn dật', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '雨具', kana: 'あまぐ', romaji: 'amagu', meaning: 'đồ dùng đi mưa', partOfSpeech: 'danh từ' },
      { kanji: '雨天', kana: 'うてん', romaji: 'uten', meaning: 'trời mưa', partOfSpeech: 'danh từ' },
      { kanji: '渦', kana: 'うず', romaji: 'uzu', meaning: 'xoáy nước', partOfSpeech: 'danh từ' },
      { kanji: '嘘つき', kana: 'うそつき', romaji: 'usotsuki', meaning: 'kẻ nói dối', partOfSpeech: 'danh từ' },
      { kanji: '云々', kana: 'うんぬん', romaji: 'unnun', meaning: 'vân vân, và những điều tương tự', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 919,
    jlptLevel: 'N1',
    words: [
      { kanji: '運賃', kana: 'うんちん', romaji: 'unchin', meaning: 'cước phí vận chuyển', partOfSpeech: 'danh từ' },
      { kanji: '運搬', kana: 'うんぱん', romaji: 'unpan', meaning: 'sự vận chuyển', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '運輸', kana: 'うんゆ', romaji: 'unyu', meaning: 'ngành vận tải', partOfSpeech: 'danh từ' },
      { kanji: '営みます', kana: 'いとなみます', romaji: 'itonamimasu', meaning: 'kinh doanh, tiến hành (công việc)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '映写', kana: 'えいしゃ', romaji: 'eisha', meaning: 'sự chiếu phim', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '映像', kana: 'えいぞう', romaji: 'eizō', meaning: 'hình ảnh, thước phim', partOfSpeech: 'danh từ' },
      { kanji: '栄えます', kana: 'さかえます', romaji: 'sakaemasu', meaning: 'thịnh vượng, phát đạt', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '英字', kana: 'えいじ', romaji: 'eiji', meaning: 'chữ cái tiếng Anh', partOfSpeech: 'danh từ' },
      { kanji: '英雄', kana: 'えいゆう', romaji: 'eiyū', meaning: 'anh hùng', partOfSpeech: 'danh từ' },
      { kanji: '閲覧', kana: 'えつらん', romaji: 'etsuran', meaning: 'sự đọc, tra cứu (tài liệu)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '厭々', kana: 'いやいや', romaji: 'iyaiya', meaning: 'miễn cưỡng, bất đắc dĩ', partOfSpeech: 'phó từ' },
      { kanji: '厭やらしい', kana: 'いやらしい', romaji: 'iyarashii', meaning: 'khó chịu, đáng ghét', partOfSpeech: 'tính từ i' },
      { kanji: '円滑', kana: 'えんかつ', romaji: 'enkatsu', meaning: 'trôi chảy, suôn sẻ', partOfSpeech: 'tính từ na' },
      { kanji: '円満', kana: 'えんまん', romaji: 'enman', meaning: 'hòa thuận, viên mãn', partOfSpeech: 'tính từ na' },
      { kanji: '延いては', kana: 'ひいては', romaji: 'hiiteha', meaning: 'và do đó, hơn nữa là', partOfSpeech: 'phó từ' },
      { kanji: '延べ', kana: 'のべ', romaji: 'nobe', meaning: 'tổng cộng, tính gộp', partOfSpeech: 'danh từ' },
      { kanji: '沿い', kana: 'ぞい', romaji: 'zoi', meaning: 'dọc theo', partOfSpeech: 'hậu tố' },
    ],
  },
  {
    lessonNumber: 920,
    jlptLevel: 'N1',
    words: [
      { kanji: '沿岸', kana: 'えんがん', romaji: 'engan', meaning: 'duyên hải, ven bờ', partOfSpeech: 'danh từ' },
      { kanji: '沿線', kana: 'えんせん', romaji: 'ensen', meaning: 'dọc theo tuyến đường sắt', partOfSpeech: 'danh từ' },
      { kanji: '演じます', kana: 'えんじます', romaji: 'enjimasu', meaning: 'diễn (vai), thể hiện', partOfSpeech: 'động từ する' },
      { kanji: '煙たい', kana: 'けむたい', romaji: 'kemutai', meaning: 'cay khói; khó xử, ngại ngùng', partOfSpeech: 'tính từ i' },
      { kanji: '煙ります', kana: 'けむります', romaji: 'kemurimasu', meaning: 'bốc khói', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '縁側', kana: 'えんがわ', romaji: 'engawa', meaning: 'hiên nhà kiểu Nhật', partOfSpeech: 'danh từ' },
      { kanji: '縁談', kana: 'えんだん', romaji: 'endan', meaning: 'chuyện mai mối, hôn sự', partOfSpeech: 'danh từ' },
      { kanji: '遠ざかります', kana: 'とおざかります', romaji: 'tōzakarimasu', meaning: 'xa dần, lùi xa', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '遠方', kana: 'えんぽう', romaji: 'enpō', meaning: 'nơi xa xôi', partOfSpeech: 'danh từ' },
      { kanji: '鉛', kana: 'なまり', romaji: 'namari', meaning: 'chì (kim loại)', partOfSpeech: 'danh từ' },
      { kanji: '於いて', kana: 'おいて', romaji: 'oite', meaning: 'tại, ở, về (văn viết trang trọng)', partOfSpeech: 'phó từ' },
      { kanji: '汚らわしい', kana: 'けがらわしい', romaji: 'kegarawashii', meaning: 'dơ bẩn, ô uế', partOfSpeech: 'tính từ i' },
      { kanji: '汚れ', kana: 'けがれ', romaji: 'kegare', meaning: 'sự ô uế, vết nhơ', partOfSpeech: 'danh từ' },
      { kanji: '汚れます', kana: 'けがれます', romaji: 'kegaremasu', meaning: 'bị vấy bẩn, ô uế', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '応急', kana: 'おうきゅう', romaji: 'ōkyū', meaning: 'cấp cứu, khẩn cấp', partOfSpeech: 'danh từ' },
      { kanji: '押し寄せます', kana: 'おしよせます', romaji: 'oshiyosemasu', meaning: 'ùa tới, tràn tới', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '押し込みます', kana: 'おしこみます', romaji: 'oshikomimasu', meaning: 'nhét vào, ấn vào', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 921,
    jlptLevel: 'N1',
    words: [
      { kanji: '横綱', kana: 'よこづな', romaji: 'yokozuna', meaning: 'võ sĩ sumo hạng nhất (yokozuna)', partOfSpeech: 'danh từ' },
      { kanji: '黄金', kana: 'おうごん', romaji: 'ōgon', meaning: 'vàng ròng', partOfSpeech: 'danh từ' },
      { kanji: '黄色', kana: 'おうしょく', romaji: 'ōshoku', meaning: 'màu vàng', partOfSpeech: 'danh từ' },
      { kanji: '屋敷', kana: 'やしき', romaji: 'yashiki', meaning: 'dinh thự, biệt thự', partOfSpeech: 'danh từ' },
      { kanji: '臆病', kana: 'おくびょう', romaji: 'okubyō', meaning: 'sự nhút nhát, hèn nhát', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '俺', kana: 'おれ', romaji: 'ore', meaning: 'tao (đại từ nam giới, suồng sã)', partOfSpeech: 'đại từ' },
      { kanji: '温和', kana: 'おんわ', romaji: 'onwa', meaning: 'ôn hòa, dịu dàng', partOfSpeech: 'tính từ na' },
      { kanji: '音', kana: 'ね', romaji: 'ne', meaning: 'âm thanh, tiếng đàn', partOfSpeech: 'danh từ' },
      { kanji: '音色', kana: 'おんいろ', romaji: 'oniro', meaning: 'âm sắc, âm điệu', partOfSpeech: 'danh từ' },
      { kanji: '下火', kana: 'したび', romaji: 'shitabi', meaning: 'lụi tàn, hạ nhiệt', partOfSpeech: 'danh từ' },
      { kanji: '下取り', kana: 'したどり', romaji: 'shitadori', meaning: 'sự đổi hàng cũ lấy hàng mới', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '下心', kana: 'したごころ', romaji: 'shitagokoro', meaning: 'ý đồ thầm kín', partOfSpeech: 'danh từ' },
      { kanji: '下地', kana: 'したじ', romaji: 'shitaji', meaning: 'nền tảng, cơ sở ban đầu', partOfSpeech: 'danh từ' },
      { kanji: '下調べ', kana: 'したしらべ', romaji: 'shitashirabe', meaning: 'sự điều tra sơ bộ, chuẩn bị trước', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '下痢', kana: 'げり', romaji: 'geri', meaning: 'tiêu chảy', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '化けます', kana: 'ばけます', romaji: 'bakemasu', meaning: 'biến hình, giả dạng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '化合', kana: 'かごう', romaji: 'kagō', meaning: 'sự hóa hợp (hóa học)', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 922,
    jlptLevel: 'N1',
    words: [
      { kanji: '化石', kana: 'かせき', romaji: 'kaseki', meaning: 'hóa thạch', partOfSpeech: 'danh từ' },
      { kana: 'どれどれ', romaji: 'doredore', meaning: 'để xem nào (thán từ)', partOfSpeech: 'thán từ' },
      { kanji: '何だか', kana: 'なんだか', romaji: 'nandaka', meaning: 'không hiểu sao, phần nào đó', partOfSpeech: 'phó từ' },
      { kanji: '何て', kana: 'なんて', romaji: 'nante', meaning: 'sao mà, thật là (cảm thán)', partOfSpeech: 'phó từ' },
      { kanji: '何と', kana: 'なんと', romaji: 'nanto', meaning: 'ôi chao, thật là', partOfSpeech: 'thán từ' },
      { kanji: '何なり', kana: 'なんなり', romaji: 'nannari', meaning: 'bất cứ cái gì', partOfSpeech: 'đại từ' },
      { kanji: '何より', kana: 'なにより', romaji: 'naniyori', meaning: 'hơn hết, tốt nhất', partOfSpeech: 'phó từ' },
      { kanji: '何気ない', kana: 'なにげない', romaji: 'nanigenai', meaning: 'vô tình, tự nhiên (không cố ý)', partOfSpeech: 'tính từ i' },
    ],
  },
];
