// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 935-940.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART7: JlptVocabUnit[] = [
  {
    lessonNumber: 935,
    jlptLevel: 'N1',
    words: [
      { kanji: '弓', kana: 'ゆみ', romaji: 'yumi', meaning: 'cây cung', partOfSpeech: 'danh từ' },
      { kanji: '急かします', kana: 'せかします', romaji: 'sekashimasu', meaning: 'thúc giục, giục giã', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '救い', kana: 'すくい', romaji: 'sukui', meaning: 'sự cứu giúp', partOfSpeech: 'danh từ' },
      { kanji: '救援', kana: 'きゅうえん', romaji: 'kyūen', meaning: 'sự cứu viện, cứu trợ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '朽ちます', kana: 'くちます', romaji: 'kuchimasu', meaning: 'mục nát, thối rữa', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '球根', kana: 'きゅうこん', romaji: 'kyūkon', meaning: 'củ (cây trồng)', partOfSpeech: 'danh từ' },
      { kanji: '窮屈', kana: 'きゅうくつ', romaji: 'kyūkutsu', meaning: 'chật chội, gò bó', partOfSpeech: 'tính từ na' },
      { kanji: '窮乏', kana: 'きゅうぼう', romaji: 'kyūbō', meaning: 'sự nghèo túng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '給仕', kana: 'きゅうじ', romaji: 'kyūji', meaning: 'người phục vụ, bồi bàn', partOfSpeech: 'danh từ' },
      { kanji: '給食', kana: 'きゅうしょく', romaji: 'kyūshoku', meaning: 'bữa ăn học đường', partOfSpeech: 'danh từ' },
      { kanji: '旧知', kana: 'きゅうち', romaji: 'kyūchi', meaning: 'bạn cũ, quen biết từ lâu', partOfSpeech: 'danh từ' },
      { kanji: '居住', kana: 'きょじゅう', romaji: 'kyojū', meaning: 'sự cư trú', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '拒絶', kana: 'きょぜつ', romaji: 'kyozetsu', meaning: 'sự từ chối, cự tuyệt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '許容', kana: 'きょよう', romaji: 'kyoyō', meaning: 'sự cho phép, dung thứ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '距離', kana: 'きょり', romaji: 'kyori', meaning: 'khoảng cách', partOfSpeech: 'danh từ' },
      { kanji: '漁船', kana: 'ぎょせん', romaji: 'gyosen', meaning: 'tàu đánh cá', partOfSpeech: 'danh từ' },
      { kanji: '漁村', kana: 'ぎょそん', romaji: 'gyoson', meaning: 'làng chài', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 936,
    jlptLevel: 'N1',
    words: [
      { kanji: '共稼ぎ', kana: 'ともかせぎ', romaji: 'tomokasegi', meaning: 'vợ chồng cùng đi làm', partOfSpeech: 'danh từ' },
      { kanji: '共学', kana: 'きょうがく', romaji: 'kyōgaku', meaning: 'học chung nam nữ', partOfSpeech: 'danh từ' },
      { kanji: '共感', kana: 'きょうかん', romaji: 'kyōkan', meaning: 'sự đồng cảm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '共存', kana: 'きょうそん', romaji: 'kyōson', meaning: 'sự cùng tồn tại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '共働き', kana: 'ともばたらき', romaji: 'tomobataraki', meaning: 'cả hai vợ chồng cùng đi làm', partOfSpeech: 'danh từ' },
      { kanji: '共鳴', kana: 'きょうめい', romaji: 'kyōmei', meaning: 'sự cộng hưởng, đồng tình', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '凶作', kana: 'きょうさく', romaji: 'kyōsaku', meaning: 'mùa màng thất bát', partOfSpeech: 'danh từ' },
      { kanji: '叫び', kana: 'さけび', romaji: 'sakebi', meaning: 'tiếng hét', partOfSpeech: 'danh từ' },
      { kanji: '境遇', kana: 'きょうぐう', romaji: 'kyōgū', meaning: 'hoàn cảnh, cảnh ngộ', partOfSpeech: 'danh từ' },
      { kanji: '強いて', kana: 'しいて', romaji: 'shiite', meaning: 'gượng ép, cố tình', partOfSpeech: 'phó từ' },
      { kanji: '強います', kana: 'しいます', romaji: 'shiimasu', meaning: 'ép buộc, cưỡng ép', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '強まります', kana: 'つよまります', romaji: 'tsuyomarimasu', meaning: 'trở nên mạnh hơn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '強めます', kana: 'つよめます', romaji: 'tsuyomemasu', meaning: 'làm mạnh thêm, nhấn mạnh', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '強硬', kana: 'きょうこう', romaji: 'kyōkō', meaning: 'cứng rắn, kiên quyết', partOfSpeech: 'tính từ na' },
      { kanji: '強制', kana: 'きょうせい', romaji: 'kyōsei', meaning: 'sự cưỡng chế, bắt buộc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '強請ります', kana: 'ねだります', romaji: 'nedarimasu', meaning: 'vòi vĩnh, đòi hỏi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '強烈', kana: 'きょうれつ', romaji: 'kyōretsu', meaning: 'mạnh mẽ, dữ dội', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 937,
    jlptLevel: 'N1',
    words: [
      { kanji: '怯えます', kana: 'おびえます', romaji: 'obiemasu', meaning: 'sợ hãi, kinh hoàng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '恐れ', kana: 'おそれ', romaji: 'osore', meaning: 'nỗi sợ hãi', partOfSpeech: 'danh từ' },
      { kanji: '恐れ入ります', kana: 'おそれいります', romaji: 'osoreirimasu', meaning: 'cảm kích, ngại quá (khiêm nhường)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '教え', kana: 'おしえ', romaji: 'oshie', meaning: 'lời dạy, giáo lý', partOfSpeech: 'danh từ' },
      { kanji: '教員', kana: 'きょういん', romaji: 'kyōin', meaning: 'giáo viên', partOfSpeech: 'danh từ' },
      { kanji: '教訓', kana: 'きょうくん', romaji: 'kyōkun', meaning: 'bài học, lời răn dạy', partOfSpeech: 'danh từ' },
      { kanji: '教材', kana: 'きょうざい', romaji: 'kyōzai', meaning: 'tài liệu giảng dạy', partOfSpeech: 'danh từ' },
      { kanji: '教習', kana: 'きょうしゅう', romaji: 'kyōshū', meaning: 'sự huấn luyện, đào tạo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '教職', kana: 'きょうしょく', romaji: 'kyōshoku', meaning: 'nghề giáo', partOfSpeech: 'danh từ' },
      { kanji: '橋渡し', kana: 'はしわたし', romaji: 'hashiwatashi', meaning: 'sự làm cầu nối, trung gian', partOfSpeech: 'danh từ' },
      { kanji: '況して', kana: 'まして', romaji: 'mashite', meaning: 'huống chi, huống hồ', partOfSpeech: 'phó từ' },
      { kanji: '脅します', kana: 'おどします', romaji: 'odoshimasu', meaning: 'đe dọa, uy hiếp', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '脅迫', kana: 'きょうはく', romaji: 'kyōhaku', meaning: 'sự đe dọa, uy hiếp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '興じます', kana: 'きょうじます', romaji: 'kyōjimasu', meaning: 'vui đùa, giải trí', partOfSpeech: 'động từ する' },
      { kanji: '興奮', kana: 'こうふん', romaji: 'kōfun', meaning: 'sự phấn khích, kích động', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '郷里', kana: 'きょうり', romaji: 'kyōri', meaning: 'quê hương', partOfSpeech: 'danh từ' },
      { kanji: '驚異', kana: 'きょうい', romaji: 'kyōi', meaning: 'điều kỳ diệu, kinh ngạc', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 938,
    jlptLevel: 'N1',
    words: [
      { kanji: '凝ります', kana: 'こります', romaji: 'korimasu', meaning: 'say mê, chăm chút; cứng (vai)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '凝らします', kana: 'こらします', romaji: 'korashimasu', meaning: 'tập trung (chú ý), dồn hết tâm trí', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '業', kana: 'ごう', romaji: 'gō', meaning: 'nghiệp (theo Phật giáo)', partOfSpeech: 'danh từ' },
      { kanji: '業者', kana: 'ぎょうしゃ', romaji: 'gyōsha', meaning: 'nhà buôn, doanh nghiệp', partOfSpeech: 'danh từ' },
      { kanji: '業績', kana: 'ぎょうせき', romaji: 'gyōseki', meaning: 'thành tích, kết quả kinh doanh', partOfSpeech: 'danh từ' },
      { kanji: '業務', kana: 'ぎょうむ', romaji: 'gyōmu', meaning: 'nghiệp vụ, công việc', partOfSpeech: 'danh từ' },
      { kanji: '局限', kana: 'きょくげん', romaji: 'kyokugen', meaning: 'giới hạn cục bộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '極めて', kana: 'きわめて', romaji: 'kiwamete', meaning: 'vô cùng, cực kỳ', partOfSpeech: 'phó từ' },
      { kanji: '極楽', kana: 'ごくらく', romaji: 'gokuraku', meaning: 'thiên đường, cực lạc', partOfSpeech: 'danh từ' },
      { kanji: '玉', kana: 'ぎょく', romaji: 'gyoku', meaning: 'quân vua (cờ tướng Nhật)', partOfSpeech: 'danh từ' },
      { kanji: '勤まります', kana: 'つとまります', romaji: 'tsutomarimasu', meaning: 'đảm đương được, phù hợp với', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '勤め先', kana: 'つとめさき', romaji: 'tsutomesaki', meaning: 'nơi làm việc', partOfSpeech: 'danh từ' },
      { kanji: '勤勉', kana: 'きんべん', romaji: 'kinben', meaning: 'sự siêng năng, cần cù', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '勤務', kana: 'きんむ', romaji: 'kinmu', meaning: 'sự làm việc, công tác', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '勤労', kana: 'きんろう', romaji: 'kinrō', meaning: 'lao động', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '禁じます', kana: 'きんじます', romaji: 'kinjimasu', meaning: 'cấm đoán', partOfSpeech: 'động từ する' },
      { kanji: '禁物', kana: 'きんもつ', romaji: 'kinmotsu', meaning: 'điều cấm kỵ', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 939,
    jlptLevel: 'N1',
    words: [
      { kanji: '襟', kana: 'えり', romaji: 'eri', meaning: 'cổ áo', partOfSpeech: 'danh từ' },
      { kanji: '近眼', kana: 'きんがん', romaji: 'kingan', meaning: 'cận thị', partOfSpeech: 'danh từ' },
      { kanji: '近付きます', kana: 'ちかづきます', romaji: 'chikazukimasu', meaning: 'đến gần, làm quen với', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '金槌', kana: 'かなづち', romaji: 'kanazuchi', meaning: 'cái búa; người không biết bơi', partOfSpeech: 'danh từ' },
      { kanji: '吟味', kana: 'ぎんみ', romaji: 'ginmi', meaning: 'sự xem xét kỹ lưỡng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '区々', kana: 'まちまち', romaji: 'machimachi', meaning: 'khác nhau, đa dạng, không đồng nhất', partOfSpeech: 'tính từ na' },
      { kanji: '区画', kana: 'くかく', romaji: 'kukaku', meaning: 'khu vực, lô đất', partOfSpeech: 'danh từ' },
      { kanji: '区間', kana: 'くかん', romaji: 'kukan', meaning: 'đoạn đường, chặng', partOfSpeech: 'danh từ' },
      { kanji: '区切り', kana: 'くぎり', romaji: 'kugiri', meaning: 'sự phân đoạn, dấu chấm câu', partOfSpeech: 'danh từ' },
      { kanji: '苦しめます', kana: 'くるしめます', romaji: 'kurushimemasu', meaning: 'hành hạ, làm khổ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '駆けっこ', kana: 'かけっこ', romaji: 'kakekko', meaning: 'cuộc thi chạy', partOfSpeech: 'danh từ' },
      { kanji: '駆け足', kana: 'かけあし', romaji: 'kakeashi', meaning: 'chạy nhanh, nước kiệu', partOfSpeech: 'danh từ' },
      { kanji: '愚か', kana: 'おろか', romaji: 'oroka', meaning: 'ngu ngốc, dại dột', partOfSpeech: 'tính từ na' },
      { kanji: '愚痴', kana: 'ぐち', romaji: 'guchi', meaning: 'lời than vãn', partOfSpeech: 'danh từ' },
      { kanji: '空しい', kana: 'むなしい', romaji: 'munashii', meaning: 'trống rỗng, vô ích', partOfSpeech: 'tính từ i' },
      { kanji: '空ろ', kana: 'うつろ', romaji: 'utsuro', meaning: 'trống rỗng, hõm sâu', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '空き間', kana: 'あきま', romaji: 'akima', meaning: 'khoảng trống, phòng cho thuê', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 940,
    jlptLevel: 'N1',
    words: [
      { kanji: '空腹', kana: 'くうふく', romaji: 'kūfuku', meaning: 'cơn đói', partOfSpeech: 'danh từ' },
      { kanji: '君主', kana: 'くんしゅ', romaji: 'kunshu', meaning: 'quân chủ, vua', partOfSpeech: 'danh từ' },
      { kanji: '群がります', kana: 'むらがります', romaji: 'muragarimasu', meaning: 'tụ tập thành đàn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '軍艦', kana: 'ぐんかん', romaji: 'gunkan', meaning: 'chiến hạm', partOfSpeech: 'danh từ' },
      { kanji: '軍事', kana: 'ぐんじ', romaji: 'gunji', meaning: 'quân sự', partOfSpeech: 'danh từ' },
      { kanji: '軍備', kana: 'ぐんび', romaji: 'gunbi', meaning: 'quân bị, vũ trang', partOfSpeech: 'danh từ' },
      { kanji: '軍服', kana: 'ぐんぷく', romaji: 'gunpuku', meaning: 'quân phục', partOfSpeech: 'danh từ' },
    ],
  },
];
