// Bổ sung từ vựng N3 đợt 3 — tự soạn tay. lessonNumber 322–331.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST3_N3: JlptVocabUnit[] = [
  {
    lessonNumber: 322,
    jlptLevel: 'N3',
    words: [
      { kanji: '生産', kana: 'せいさん', romaji: 'seisan', meaning: 'sản xuất', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '製造', kana: 'せいぞう', romaji: 'seizō', meaning: 'chế tạo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '加工', kana: 'かこう', romaji: 'kakō', meaning: 'gia công', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '販売', kana: 'はんばい', romaji: 'hanbai', meaning: 'bán hàng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '輸出', kana: 'ゆしゅつ', romaji: 'yushutsu', meaning: 'xuất khẩu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '輸入', kana: 'ゆにゅう', romaji: 'yunyū', meaning: 'nhập khẩu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '貿易', kana: 'ぼうえき', romaji: 'bōeki', meaning: 'mậu dịch, thương mại', partOfSpeech: 'danh từ' },
      { kanji: '需要', kana: 'じゅよう', romaji: 'juyō', meaning: 'nhu cầu', partOfSpeech: 'danh từ' },
      { kanji: '供給', kana: 'きょうきゅう', romaji: 'kyōkyū', meaning: 'cung cấp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '需給', kana: 'じゅきゅう', romaji: 'jukyū', meaning: 'cung và cầu', partOfSpeech: 'danh từ' },
      { kanji: '景気', kana: 'けいき', romaji: 'keiki', meaning: 'tình hình kinh tế', partOfSpeech: 'danh từ' },
      { kanji: '不況', kana: 'ふきょう', romaji: 'fukyō', meaning: 'suy thoái kinh tế', partOfSpeech: 'danh từ' },
      { kanji: '好況', kana: 'こうきょう', romaji: 'kōkyō', meaning: 'kinh tế thịnh vượng', partOfSpeech: 'danh từ' },
      { kanji: '物価', kana: 'ぶっか', romaji: 'bukka', meaning: 'vật giá', partOfSpeech: 'danh từ' },
      { kanji: 'インフレ', kana: 'インフレ', romaji: 'infure', meaning: 'lạm phát', partOfSpeech: 'danh từ' },
      { kanji: '賃金', kana: 'ちんぎん', romaji: 'chingin', meaning: 'tiền công', partOfSpeech: 'danh từ' },
      { kanji: '雇用', kana: 'こよう', romaji: 'koyō', meaning: 'thuê lao động', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '失業', kana: 'しつぎょう', romaji: 'shitsugyō', meaning: 'thất nghiệp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '転職', kana: 'てんしょく', romaji: 'tenshoku', meaning: 'chuyển việc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '退職', kana: 'たいしょく', romaji: 'taishoku', meaning: 'nghỉ việc, về hưu', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 323,
    jlptLevel: 'N3',
    words: [
      { kanji: '態度', kana: 'たいど', romaji: 'taido', meaning: 'thái độ', partOfSpeech: 'danh từ' },
      { kanji: '姿勢', kana: 'しせい', romaji: 'shisei', meaning: 'tư thế, lập trường', partOfSpeech: 'danh từ' },
      { kanji: '行動', kana: 'こうどう', romaji: 'kōdō', meaning: 'hành động', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '反応', kana: 'はんのう', romaji: 'hannō', meaning: 'phản ứng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '対応', kana: 'たいおう', romaji: 'taiō', meaning: 'ứng phó', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '協力', kana: 'きょうりょく', romaji: 'kyōryoku', meaning: 'hợp tác', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '協定', kana: 'きょうてい', romaji: 'kyōtei', meaning: 'hiệp định', partOfSpeech: 'danh từ' },
      { kanji: '同意', kana: 'どうい', romaji: 'dōi', meaning: 'đồng ý', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '賛成', kana: 'さんせい', romaji: 'sansei', meaning: 'tán thành', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '反対', kana: 'はんたい', romaji: 'hantai', meaning: 'phản đối, ngược lại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '協議', kana: 'きょうぎ', romaji: 'kyōgi', meaning: 'hiệp thương, thảo luận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '議論', kana: 'ぎろん', romaji: 'giron', meaning: 'tranh luận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '討論', kana: 'とうろん', romaji: 'tōron', meaning: 'thảo luận, biện luận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発表', kana: 'はっぴょう', romaji: 'happyō', meaning: 'công bố, thuyết trình', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '報告', kana: 'ほうこく', romaji: 'hōkoku', meaning: 'báo cáo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '連絡', kana: 'れんらく', romaji: 'renraku', meaning: 'liên lạc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '通知', kana: 'つうち', romaji: 'tsūchi', meaning: 'thông báo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '連続', kana: 'れんぞく', romaji: 'renzoku', meaning: 'liên tục', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '連合', kana: 'れんごう', romaji: 'rengō', meaning: 'liên hợp, liên minh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '団体', kana: 'だんたい', romaji: 'dantai', meaning: 'đoàn thể', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 324,
    jlptLevel: 'N3',
    words: [
      { kanji: '原則', kana: 'げんそく', romaji: 'gensoku', meaning: 'nguyên tắc', partOfSpeech: 'danh từ' },
      { kanji: '基準', kana: 'きじゅん', romaji: 'kijun', meaning: 'tiêu chuẩn', partOfSpeech: 'danh từ' },
      { kanji: '標準', kana: 'ひょうじゅん', romaji: 'hyōjun', meaning: 'tiêu chuẩn, chuẩn mực', partOfSpeech: 'danh từ' },
      { kanji: '水準', kana: 'すいじゅん', romaji: 'suijun', meaning: 'mức độ, trình độ', partOfSpeech: 'danh từ' },
      { kanji: '基本', kana: 'きほん', romaji: 'kihon', meaning: 'cơ bản', partOfSpeech: 'danh từ' },
      { kanji: '基礎', kana: 'きそ', romaji: 'kiso', meaning: 'nền móng, cơ sở', partOfSpeech: 'danh từ' },
      { kanji: '応用', kana: 'おうよう', romaji: 'ōyō', meaning: 'ứng dụng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '実用', kana: 'じつよう', romaji: 'jitsuyō', meaning: 'thực dụng, dùng thực tế', partOfSpeech: 'danh từ' },
      { kanji: '実際', kana: 'じっさい', romaji: 'jissai', meaning: 'thực tế', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '現実', kana: 'げんじつ', romaji: 'genjitsu', meaning: 'hiện thực', partOfSpeech: 'danh từ' },
      { kanji: '理想', kana: 'りそう', romaji: 'risō', meaning: 'lý tưởng', partOfSpeech: 'danh từ' },
      { kanji: '想像', kana: 'そうぞう', romaji: 'sōzō', meaning: 'tưởng tượng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '創造', kana: 'そうぞう', romaji: 'sōzō', meaning: 'sáng tạo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '独創', kana: 'どくそう', romaji: 'dokusō', meaning: 'sự độc đáo sáng tạo', partOfSpeech: 'danh từ' },
      { kanji: '模倣', kana: 'もほう', romaji: 'mohō', meaning: 'bắt chước', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '真似', kana: 'まね', romaji: 'mane', meaning: 'bắt chước, giả vờ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '参考', kana: 'さんこう', romaji: 'sankō', meaning: 'tham khảo', partOfSpeech: 'danh từ' },
      { kanji: '資料', kana: 'しりょう', romaji: 'shiryō', meaning: 'tài liệu', partOfSpeech: 'danh từ' },
      { kanji: '情報', kana: 'じょうほう', romaji: 'jōhō', meaning: 'thông tin', partOfSpeech: 'danh từ' },
      { kanji: 'データ', kana: 'データ', romaji: 'dēta', meaning: 'dữ liệu', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 325,
    jlptLevel: 'N3',
    words: [
      { kanji: '姿', kana: 'すがた', romaji: 'sugata', meaning: 'dáng vẻ, hình dáng', partOfSpeech: 'danh từ' },
      { kanji: '容姿', kana: 'ようし', romaji: 'yōshi', meaning: 'dung mạo', partOfSpeech: 'danh từ' },
      { kanji: '外見', kana: 'がいけん', romaji: 'gaiken', meaning: 'vẻ bề ngoài', partOfSpeech: 'danh từ' },
      { kanji: '印象', kana: 'いんしょう', romaji: 'inshō', meaning: 'ấn tượng', partOfSpeech: 'danh từ' },
      { kanji: '雰囲気', kana: 'ふんいき', romaji: 'fun\'iki', meaning: 'bầu không khí', partOfSpeech: 'danh từ' },
      { kanji: '魅力', kana: 'みりょく', romaji: 'miryoku', meaning: 'sức hấp dẫn', partOfSpeech: 'danh từ' },
      { kanji: '個性', kana: 'こせい', romaji: 'kosei', meaning: 'cá tính', partOfSpeech: 'danh từ' },
      { kanji: '特徴', kana: 'とくちょう', romaji: 'tokuchō', meaning: 'đặc trưng', partOfSpeech: 'danh từ' },
      { kanji: '長所', kana: 'ちょうしょ', romaji: 'chōsho', meaning: 'ưu điểm', partOfSpeech: 'danh từ' },
      { kanji: '短所', kana: 'たんしょ', romaji: 'tansho', meaning: 'khuyết điểm', partOfSpeech: 'danh từ' },
      { kanji: '欠点', kana: 'けってん', romaji: 'ketten', meaning: 'nhược điểm', partOfSpeech: 'danh từ' },
      { kanji: '長点', kana: 'ちょうてん', romaji: 'chōten', meaning: 'điểm mạnh (ít dùng, đối lập 欠点)', partOfSpeech: 'danh từ' },
      { kanji: '長生き', kana: 'ながいき', romaji: 'nagaiki', meaning: 'sống lâu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '健康的', kana: 'けんこうてき', romaji: 'kenkōteki', meaning: 'mang tính khỏe mạnh', partOfSpeech: 'tính từ na' },
      { kanji: '体力', kana: 'たいりょく', romaji: 'tairyoku', meaning: 'thể lực', partOfSpeech: 'danh từ' },
      { kanji: '筋肉', kana: 'きんにく', romaji: 'kinniku', meaning: 'cơ bắp', partOfSpeech: 'danh từ' },
      { kanji: '体重', kana: 'たいじゅう', romaji: 'taijū', meaning: 'cân nặng', partOfSpeech: 'danh từ' },
      { kanji: '身長', kana: 'しんちょう', romaji: 'shinchō', meaning: 'chiều cao', partOfSpeech: 'danh từ' },
      { kanji: 'ダイエット', kana: 'ダイエット', romaji: 'daietto', meaning: 'ăn kiêng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '姿勢を正す', kana: 'しせいをただす', romaji: 'shisei o tadasu', meaning: 'chỉnh lại tư thế', partOfSpeech: 'cụm động từ' },
    ],
  },
  {
    lessonNumber: 326,
    jlptLevel: 'N3',
    words: [
      { kanji: '教育', kana: 'きょういく', romaji: 'kyōiku', meaning: 'giáo dục', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '教養', kana: 'きょうよう', romaji: 'kyōyō', meaning: 'học vấn, tu dưỡng', partOfSpeech: 'danh từ' },
      { kanji: '学問', kana: 'がくもん', romaji: 'gakumon', meaning: 'học vấn, học thuật', partOfSpeech: 'danh từ' },
      { kanji: '知能', kana: 'ちのう', romaji: 'chinō', meaning: 'trí tuệ', partOfSpeech: 'danh từ' },
      { kanji: '記憶力', kana: 'きおくりょく', romaji: 'kiokuryoku', meaning: 'trí nhớ', partOfSpeech: 'danh từ' },
      { kanji: '集中力', kana: 'しゅうちゅうりょく', romaji: 'shūchūryoku', meaning: 'khả năng tập trung', partOfSpeech: 'danh từ' },
      { kanji: '想像力', kana: 'そうぞうりょく', romaji: 'sōzōryoku', meaning: 'khả năng tưởng tượng', partOfSpeech: 'danh từ' },
      { kanji: '判断力', kana: 'はんだんりょく', romaji: 'handanryoku', meaning: 'khả năng phán đoán', partOfSpeech: 'danh từ' },
      { kanji: '理解力', kana: 'りかいりょく', romaji: 'rikairyoku', meaning: 'khả năng hiểu', partOfSpeech: 'danh từ' },
      { kanji: '表現力', kana: 'ひょうげんりょく', romaji: 'hyōgenryoku', meaning: 'khả năng diễn đạt', partOfSpeech: 'danh từ' },
      { kanji: '語学力', kana: 'ごがくりょく', romaji: 'gogakuryoku', meaning: 'năng lực ngoại ngữ', partOfSpeech: 'danh từ' },
      { kanji: '専門', kana: 'せんもん', romaji: 'senmon', meaning: 'chuyên môn', partOfSpeech: 'danh từ' },
      { kanji: '専攻', kana: 'せんこう', romaji: 'senkō', meaning: 'chuyên ngành', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '資格', kana: 'しかく', romaji: 'shikaku', meaning: 'chứng chỉ, tư cách', partOfSpeech: 'danh từ' },
      { kanji: '免許', kana: 'めんきょ', romaji: 'menkyo', meaning: 'giấy phép, bằng lái', partOfSpeech: 'danh từ' },
      { kanji: '学歴', kana: 'がくれき', romaji: 'gakureki', meaning: 'trình độ học vấn', partOfSpeech: 'danh từ' },
      { kanji: '職歴', kana: 'しょくれき', romaji: 'shokureki', meaning: 'quá trình làm việc', partOfSpeech: 'danh từ' },
      { kanji: '履歴書', kana: 'りれきしょ', romaji: 'rirekisho', meaning: 'sơ yếu lý lịch', partOfSpeech: 'danh từ' },
      { kanji: '面接', kana: 'めんせつ', romaji: 'mensetsu', meaning: 'phỏng vấn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '採用', kana: 'さいよう', romaji: 'saiyō', meaning: 'tuyển dụng', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 327,
    jlptLevel: 'N3',
    words: [
      { kanji: '寿命', kana: 'じゅみょう', romaji: 'jumyō', meaning: 'tuổi thọ', partOfSpeech: 'danh từ' },
      { kanji: '一生', kana: 'いっしょう', romaji: 'isshō', meaning: 'cả cuộc đời', partOfSpeech: 'danh từ' },
      { kanji: '人生', kana: 'じんせい', romaji: 'jinsei', meaning: 'đời người', partOfSpeech: 'danh từ' },
      { kanji: '生涯', kana: 'しょうがい', romaji: 'shōgai', meaning: 'suốt đời', partOfSpeech: 'danh từ' },
      { kanji: '運命', kana: 'うんめい', romaji: 'unmei', meaning: 'vận mệnh', partOfSpeech: 'danh từ' },
      { kanji: '偶然', kana: 'ぐうぜん', romaji: 'gūzen', meaning: 'ngẫu nhiên, tình cờ', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '必然', kana: 'ひつぜん', romaji: 'hitsuzen', meaning: 'tất nhiên, tất yếu', partOfSpeech: 'danh từ' },
      { kanji: '奇跡', kana: 'きせき', romaji: 'kiseki', meaning: 'kỳ tích', partOfSpeech: 'danh từ' },
      { kanji: '縁', kana: 'えん', romaji: 'en', meaning: 'duyên phận', partOfSpeech: 'danh từ' },
      { kanji: '出会い', kana: 'であい', romaji: 'deai', meaning: 'sự gặp gỡ', partOfSpeech: 'danh từ' },
      { kanji: '別れ', kana: 'わかれ', romaji: 'wakare', meaning: 'sự chia ly', partOfSpeech: 'danh từ' },
      { kanji: '再会', kana: 'さいかい', romaji: 'saikai', meaning: 'tái ngộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '思い出', kana: 'おもいで', romaji: 'omoide', meaning: 'kỷ niệm', partOfSpeech: 'danh từ' },
      { kanji: '記念', kana: 'きねん', romaji: 'kinen', meaning: 'kỷ niệm (sự kiện)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '過去', kana: 'かこ', romaji: 'kako', meaning: 'quá khứ', partOfSpeech: 'danh từ' },
      { kanji: '未来', kana: 'みらい', romaji: 'mirai', meaning: 'tương lai', partOfSpeech: 'danh từ' },
      { kanji: '現在', kana: 'げんざい', romaji: 'genzai', meaning: 'hiện tại', partOfSpeech: 'danh từ' },
      { kanji: '将来性', kana: 'しょうらいせい', romaji: 'shōraisei', meaning: 'tiềm năng tương lai', partOfSpeech: 'danh từ' },
      { kanji: '可能性', kana: 'かのうせい', romaji: 'kanōsei', meaning: 'khả năng, tính khả thi', partOfSpeech: 'danh từ' },
      { kanji: '選択肢', kana: 'せんたくし', romaji: 'sentakushi', meaning: 'lựa chọn (phương án)', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 328,
    jlptLevel: 'N3',
    words: [
      { kanji: '交通機関', kana: 'こうつうきかん', romaji: 'kōtsū kikan', meaning: 'phương tiện giao thông công cộng', partOfSpeech: 'danh từ' },
      { kanji: '渋滞', kana: 'じゅうたい', romaji: 'jūtai', meaning: 'tắc đường', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '事故', kana: 'じこ', romaji: 'jiko', meaning: 'tai nạn', partOfSpeech: 'danh từ' },
      { kanji: '信号無視', kana: 'しんごうむし', romaji: 'shingō mushi', meaning: 'vượt đèn đỏ', partOfSpeech: 'danh từ' },
      { kanji: '速度', kana: 'そくど', romaji: 'sokudo', meaning: 'tốc độ', partOfSpeech: 'danh từ' },
      { kanji: '制限', kana: 'せいげん', romaji: 'seigen', meaning: 'sự hạn chế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '免許証', kana: 'めんきょしょう', romaji: 'menkyoshō', meaning: 'bằng lái xe', partOfSpeech: 'danh từ' },
      { kanji: '運転手', kana: 'うんてんしゅ', romaji: 'untenshu', meaning: 'tài xế', partOfSpeech: 'danh từ' },
      { kanji: '歩行者', kana: 'ほこうしゃ', romaji: 'hokōsha', meaning: 'người đi bộ', partOfSpeech: 'danh từ' },
      { kanji: '横断歩道', kana: 'おうだんほどう', romaji: 'ōdan hodō', meaning: 'vạch qua đường', partOfSpeech: 'danh từ' },
      { kanji: '駐車', kana: 'ちゅうしゃ', romaji: 'chūsha', meaning: 'đỗ xe', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '停車', kana: 'ていしゃ', romaji: 'teisha', meaning: 'dừng xe', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '通行止め', kana: 'つうこうどめ', romaji: 'tsūkōdome', meaning: 'cấm đi lại', partOfSpeech: 'danh từ' },
      { kanji: '工事中', kana: 'こうじちゅう', romaji: 'kōjichū', meaning: 'đang thi công', partOfSpeech: 'danh từ' },
      { kanji: '迂回', kana: 'うかい', romaji: 'ukai', meaning: 'đi đường vòng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '近道', kana: 'ちかみち', romaji: 'chikamichi', meaning: 'đường tắt', partOfSpeech: 'danh từ' },
      { kanji: '遠回り', kana: 'とおまわり', romaji: 'tōmawari', meaning: 'đường vòng xa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '渋々', kana: 'しぶしぶ', romaji: 'shibushibu', meaning: 'miễn cưỡng', partOfSpeech: 'phó từ' },
      { kanji: '徐行', kana: 'じょこう', romaji: 'jokō', meaning: 'đi chậm lại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '一方通行', kana: 'いっぽうつうこう', romaji: 'ippō tsūkō', meaning: 'đường một chiều', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 329,
    jlptLevel: 'N3',
    words: [
      { kanji: '文学', kana: 'ぶんがく', romaji: 'bungaku', meaning: 'văn học', partOfSpeech: 'danh từ' },
      { kanji: '小説', kana: 'しょうせつ', romaji: 'shōsetsu', meaning: 'tiểu thuyết', partOfSpeech: 'danh từ' },
      { kanji: '作家', kana: 'さっか', romaji: 'sakka', meaning: 'nhà văn', partOfSpeech: 'danh từ' },
      { kanji: '作者', kana: 'さくしゃ', romaji: 'sakusha', meaning: 'tác giả', partOfSpeech: 'danh từ' },
      { kanji: '作品', kana: 'さくひん', romaji: 'sakuhin', meaning: 'tác phẩm', partOfSpeech: 'danh từ' },
      { kanji: '物語', kana: 'ものがたり', romaji: 'monogatari', meaning: 'câu chuyện', partOfSpeech: 'danh từ' },
      { kanji: '主人公', kana: 'しゅじんこう', romaji: 'shujinkō', meaning: 'nhân vật chính', partOfSpeech: 'danh từ' },
      { kanji: '登場人物', kana: 'とうじょうじんぶつ', romaji: 'tōjō jinbutsu', meaning: 'nhân vật xuất hiện (trong truyện)', partOfSpeech: 'danh từ' },
      { kanji: '内容', kana: 'ないよう', romaji: 'naiyō', meaning: 'nội dung', partOfSpeech: 'danh từ' },
      { kanji: '場面', kana: 'ばめん', romaji: 'bamen', meaning: 'cảnh, tình huống', partOfSpeech: 'danh từ' },
      { kanji: '表現', kana: 'ひょうげん', romaji: 'hyōgen', meaning: 'sự diễn đạt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '描写', kana: 'びょうしゃ', romaji: 'byōsha', meaning: 'miêu tả', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '感想', kana: 'かんそう', romaji: 'kansō', meaning: 'cảm tưởng', partOfSpeech: 'danh từ' },
      { kanji: '批評', kana: 'ひひょう', romaji: 'hihyō', meaning: 'phê bình', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '評判', kana: 'ひょうばん', romaji: 'hyōban', meaning: 'danh tiếng, dư luận', partOfSpeech: 'danh từ' },
      { kanji: '出版', kana: 'しゅっぱん', romaji: 'shuppan', meaning: 'xuất bản', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '編集', kana: 'へんしゅう', romaji: 'henshū', meaning: 'biên tập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '翻訳', kana: 'ほんやく', romaji: 'hon\'yaku', meaning: 'dịch thuật', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '原作', kana: 'げんさく', romaji: 'gensaku', meaning: 'nguyên tác', partOfSpeech: 'danh từ' },
      { kanji: '映画化', kana: 'えいがか', romaji: 'eigaka', meaning: 'chuyển thể thành phim', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 330,
    jlptLevel: 'N3',
    words: [
      { kanji: '祭り', kana: 'まつり', romaji: 'matsuri', meaning: 'lễ hội', partOfSpeech: 'danh từ' },
      { kanji: '行事', kana: 'ぎょうじ', romaji: 'gyōji', meaning: 'sự kiện thường niên', partOfSpeech: 'danh từ' },
      { kanji: '儀式', kana: 'ぎしき', romaji: 'gishiki', meaning: 'nghi lễ', partOfSpeech: 'danh từ' },
      { kanji: '習わし', kana: 'ならわし', romaji: 'narawashi', meaning: 'tập tục', partOfSpeech: 'danh từ' },
      { kanji: '伝統', kana: 'でんとう', romaji: 'dentō', meaning: 'truyền thống', partOfSpeech: 'danh từ' },
      { kanji: '風習', kana: 'ふうしゅう', romaji: 'fūshū', meaning: 'phong tục', partOfSpeech: 'danh từ' },
      { kanji: '祝日', kana: 'しゅくじつ', romaji: 'shukujitsu', meaning: 'ngày lễ', partOfSpeech: 'danh từ' },
      { kanji: '休日', kana: 'きゅうじつ', romaji: 'kyūjitsu', meaning: 'ngày nghỉ', partOfSpeech: 'danh từ' },
      { kanji: '正月', kana: 'しょうがつ', romaji: 'shōgatsu', meaning: 'Tết năm mới', partOfSpeech: 'danh từ' },
      { kanji: '花火', kana: 'はなび', romaji: 'hanabi', meaning: 'pháo hoa', partOfSpeech: 'danh từ' },
      { kanji: '神社', kana: 'じんじゃ', romaji: 'jinja', meaning: 'đền thờ Thần đạo', partOfSpeech: 'danh từ' },
      { kanji: '寺', kana: 'てら', romaji: 'tera', meaning: 'ngôi chùa', partOfSpeech: 'danh từ' },
      { kanji: '参拝', kana: 'さんぱい', romaji: 'sanpai', meaning: 'viếng bái', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '祈る', kana: 'いのる', romaji: 'inoru', meaning: 'cầu nguyện', partOfSpeech: 'động từ nhóm 1' },
      { kanji: 'お守り', kana: 'おまもり', romaji: 'omamori', meaning: 'bùa hộ mệnh', partOfSpeech: 'danh từ' },
      { kanji: '占い', kana: 'うらない', romaji: 'uranai', meaning: 'bói toán', partOfSpeech: 'danh từ' },
      { kanji: '風習的', kana: 'ふうしゅうてき', romaji: 'fūshūteki', meaning: 'mang tính phong tục', partOfSpeech: 'tính từ na' },
      { kanji: '独特', kana: 'どくとく', romaji: 'dokutoku', meaning: 'độc đáo, riêng biệt', partOfSpeech: 'tính từ na' },
      { kanji: '珍しい', kana: 'めずらしい', romaji: 'mezurashii', meaning: 'hiếm, hiếm gặp', partOfSpeech: 'tính từ i' },
      { kanji: '興味深い', kana: 'きょうみぶかい', romaji: 'kyōmibukai', meaning: 'rất thú vị', partOfSpeech: 'tính từ i' },
    ],
  },
  {
    lessonNumber: 331,
    jlptLevel: 'N3',
    words: [
      { kanji: '体調', kana: 'たいちょう', romaji: 'taichō', meaning: 'tình trạng sức khỏe', partOfSpeech: 'danh từ' },
      { kanji: '睡眠', kana: 'すいみん', romaji: 'suimin', meaning: 'giấc ngủ', partOfSpeech: 'danh từ' },
      { kanji: '栄養', kana: 'えいよう', romaji: 'eiyō', meaning: 'dinh dưỡng', partOfSpeech: 'danh từ' },
      { kanji: '食欲', kana: 'しょくよく', romaji: 'shokuyoku', meaning: 'sự thèm ăn', partOfSpeech: 'danh từ' },
      { kanji: '偏食', kana: 'へんしょく', romaji: 'henshoku', meaning: 'kén ăn, ăn lệch', partOfSpeech: 'danh từ, động từ する' },
      { kanji: 'ストレス', kana: 'ストレス', romaji: 'sutoresu', meaning: 'căng thẳng (stress)', partOfSpeech: 'danh từ' },
      { kanji: '疲労', kana: 'ひろう', romaji: 'hirō', meaning: 'mệt mỏi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '過労', kana: 'かろう', romaji: 'karō', meaning: 'làm việc quá sức', partOfSpeech: 'danh từ' },
      { kanji: '休養', kana: 'きゅうよう', romaji: 'kyūyō', meaning: 'nghỉ dưỡng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '療養', kana: 'りょうよう', romaji: 'ryōyō', meaning: 'điều dưỡng, chữa bệnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '診断', kana: 'しんだん', romaji: 'shindan', meaning: 'chẩn đoán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '治療', kana: 'ちりょう', romaji: 'chiryō', meaning: 'điều trị', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '手術', kana: 'しゅじゅつ', romaji: 'shujutsu', meaning: 'phẫu thuật', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '入院', kana: 'にゅういん', romaji: 'nyūin', meaning: 'nhập viện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '通院', kana: 'つういん', romaji: 'tsūin', meaning: 'đi khám định kỳ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '予防', kana: 'よぼう', romaji: 'yobō', meaning: 'phòng ngừa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '検診', kana: 'けんしん', romaji: 'kenshin', meaning: 'khám sức khỏe', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '副作用', kana: 'ふくさよう', romaji: 'fukusayō', meaning: 'tác dụng phụ', partOfSpeech: 'danh từ' },
      { kanji: 'アレルギー', kana: 'アレルギー', romaji: 'arerugī', meaning: 'dị ứng', partOfSpeech: 'danh từ' },
      { kanji: '症状', kana: 'しょうじょう', romaji: 'shōjō', meaning: 'triệu chứng', partOfSpeech: 'danh từ' },
    ],
  },
];
