// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 923-928.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART5: JlptVocabUnit[] = [
  {
    lessonNumber: 923,
    jlptLevel: 'N1',
    words: [
      { kanji: '加入', kana: 'かにゅう', romaji: 'kanyū', meaning: 'sự gia nhập, tham gia', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '家計', kana: 'かけい', romaji: 'kakei', meaning: 'kinh tế gia đình, chi tiêu hộ gia đình', partOfSpeech: 'danh từ' },
      { kanji: '家主', kana: 'いえぬし', romaji: 'ienushi', meaning: 'chủ nhà', partOfSpeech: 'danh từ' },
      { kanji: '家出', kana: 'いえで', romaji: 'iede', meaning: 'sự bỏ nhà ra đi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '家畜', kana: 'かちく', romaji: 'kachiku', meaning: 'gia súc', partOfSpeech: 'danh từ' },
      { kanji: '家来', kana: 'けらい', romaji: 'kerai', meaning: 'gia thần, kẻ hầu', partOfSpeech: 'danh từ' },
      { kanji: '暇', kana: 'いとま', romaji: 'itoma', meaning: 'thời gian rảnh, sự cáo từ', partOfSpeech: 'danh từ' },
      { kanji: '果たします', kana: 'はたします', romaji: 'hatashimasu', meaning: 'hoàn thành, thực hiện', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '果て', kana: 'はて', romaji: 'hate', meaning: 'tận cùng, giới hạn', partOfSpeech: 'danh từ' },
      { kanji: '果てます', kana: 'はてます', romaji: 'hatemasu', meaning: 'kết thúc, chấm dứt', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '儚い', kana: 'はかない', romaji: 'hakanai', meaning: 'phù du, ngắn ngủi', partOfSpeech: 'tính từ i' },
      { kanji: '火花', kana: 'ひばな', romaji: 'hibana', meaning: 'tia lửa', partOfSpeech: 'danh từ' },
      { kanji: '火星', kana: 'かせい', romaji: 'kasei', meaning: 'sao Hỏa', partOfSpeech: 'danh từ' },
      { kanji: '火燵', kana: 'こたつ', romaji: 'kotatsu', meaning: 'bàn sưởi kiểu Nhật (kotatsu)', partOfSpeech: 'danh từ' },
      { kanji: '箇条書き', kana: 'かじょうがき', romaji: 'kajōgaki', meaning: 'cách viết liệt kê theo mục', partOfSpeech: 'danh từ' },
      { kanji: '花びら', kana: 'はなびら', romaji: 'hanabira', meaning: 'cánh hoa', partOfSpeech: 'danh từ' },
      { kanji: '花壇', kana: 'かだん', romaji: 'kadan', meaning: 'bồn hoa', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 924,
    jlptLevel: 'N1',
    words: [
      { kanji: '花粉', kana: 'かふん', romaji: 'kafun', meaning: 'phấn hoa', partOfSpeech: 'danh từ' },
      { kanji: '荷造り', kana: 'にづくり', romaji: 'nizukuri', meaning: 'sự đóng gói hành lý', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '華々しい', kana: 'はなばなしい', romaji: 'hanabanashii', meaning: 'rực rỡ, huy hoàng', partOfSpeech: 'tính từ i' },
      { kanji: '華やか', kana: 'はなやか', romaji: 'hanayaka', meaning: 'rực rỡ, hào nhoáng', partOfSpeech: 'tính từ na' },
      { kanji: '華美', kana: 'かび', romaji: 'kabi', meaning: 'sự xa hoa, lộng lẫy', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '華奢', kana: 'きゃしゃ', romaji: 'kyasha', meaning: 'mảnh mai, thanh tú', partOfSpeech: 'tính từ na' },
      { kanji: '課外', kana: 'かがい', romaji: 'kagai', meaning: 'ngoại khóa', partOfSpeech: 'danh từ' },
      { kanji: '貨幣', kana: 'かへい', romaji: 'kahei', meaning: 'tiền tệ', partOfSpeech: 'danh từ' },
      { kanji: '過ち', kana: 'あやまち', romaji: 'ayamachi', meaning: 'sai lầm, lỗi lầm', partOfSpeech: 'danh từ' },
      { kanji: '過疎', kana: 'かそ', romaji: 'kaso', meaning: 'sự thưa dân, giảm dân số', partOfSpeech: 'danh từ' },
      { kanji: '過密', kana: 'かみつ', romaji: 'kamitsu', meaning: 'quá đông đúc', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '霞みます', kana: 'かすみます', romaji: 'kasumimasu', meaning: 'mờ đi, có sương mù', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '雅致', kana: 'がち', romaji: 'gachi', meaning: 'sự tao nhã, thanh lịch', partOfSpeech: 'danh từ' },
      { kanji: '会見', kana: 'かいけん', romaji: 'kaiken', meaning: 'cuộc gặp gỡ, họp báo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '解除', kana: 'かいじょ', romaji: 'kaijo', meaning: 'sự hủy bỏ, giải trừ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '解剖', kana: 'かいぼう', romaji: 'kaibō', meaning: 'sự giải phẫu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '回収', kana: 'かいしゅう', romaji: 'kaishū', meaning: 'sự thu hồi', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 925,
    jlptLevel: 'N1',
    words: [
      { kanji: '回送', kana: 'かいそう', romaji: 'kaisō', meaning: 'sự chuyển tiếp, chuyển phát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '回路', kana: 'かいろ', romaji: 'kairo', meaning: 'mạch điện', partOfSpeech: 'danh từ' },
      { kanji: '快い', kana: 'こころよい', romaji: 'kokoroyoi', meaning: 'dễ chịu, thoải mái', partOfSpeech: 'tính từ i' },
      { kanji: '怪獣', kana: 'かいじゅう', romaji: 'kaijū', meaning: 'quái vật', partOfSpeech: 'danh từ' },
      { kanji: '懐きます', kana: 'なつきます', romaji: 'natsukimasu', meaning: 'quấn quýt, gắn bó (với ai)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '拐います', kana: 'さらいます', romaji: 'saraimasu', meaning: 'bắt cóc, cuỗm đi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '改まります', kana: 'あらたまります', romaji: 'aratamarimasu', meaning: 'được đổi mới, trở nên trang trọng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '改悪', kana: 'かいあく', romaji: 'kaiaku', meaning: 'sự sửa đổi theo hướng xấu đi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '改定', kana: 'かいてい', romaji: 'kaitei', meaning: 'sự sửa đổi, cải cách', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '改良', kana: 'かいりょう', romaji: 'kairyō', meaning: 'sự cải tiến', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '海運', kana: 'かいうん', romaji: 'kaiun', meaning: 'vận tải đường biển', partOfSpeech: 'danh từ' },
      { kanji: '海峡', kana: 'かいきょう', romaji: 'kaikyō', meaning: 'eo biển', partOfSpeech: 'danh từ' },
      { kanji: '海抜', kana: 'かいばつ', romaji: 'kaibatsu', meaning: 'độ cao so với mực nước biển', partOfSpeech: 'danh từ' },
      { kanji: '海流', kana: 'かいりゅう', romaji: 'kairyū', meaning: 'hải lưu, dòng biển', partOfSpeech: 'danh từ' },
      { kanji: '灰皿', kana: 'はいさら', romaji: 'haisara', meaning: 'gạt tàn thuốc', partOfSpeech: 'danh từ' },
      { kanji: '開拓', kana: 'かいたく', romaji: 'kaitaku', meaning: 'sự khai hoang, khai phá', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '開発', kana: 'かいはつ', romaji: 'kaihatsu', meaning: 'sự phát triển, khai phá', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 926,
    jlptLevel: 'N1',
    words: [
      { kanji: '階級', kana: 'かいきゅう', romaji: 'kaikyū', meaning: 'giai cấp, đẳng cấp', partOfSpeech: 'danh từ' },
      { kanji: '貝殻', kana: 'かいがら', romaji: 'kaigara', meaning: 'vỏ sò', partOfSpeech: 'danh từ' },
      { kanji: '外貨', kana: 'がいか', romaji: 'gaika', meaning: 'ngoại tệ, hàng nhập khẩu', partOfSpeech: 'danh từ' },
      { kanji: '外観', kana: 'がいかん', romaji: 'gaikan', meaning: 'bề ngoài, ngoại quan', partOfSpeech: 'danh từ' },
      { kanji: '外相', kana: 'がいしょう', romaji: 'gaishō', meaning: 'bộ trưởng ngoại giao', partOfSpeech: 'danh từ' },
      { kanji: '外方', kana: 'そっぽ', romaji: 'soppo', meaning: 'hướng khác, quay mặt đi', partOfSpeech: 'danh từ' },
      { kanji: '外来', kana: 'がいらい', romaji: 'gairai', meaning: 'ngoại lai, nhập ngoại', partOfSpeech: 'danh từ' },
      { kanji: '害します', kana: 'がいします', romaji: 'gaishimasu', meaning: 'gây hại, làm tổn thương', partOfSpeech: 'động từ する' },
      { kanji: '崖', kana: 'がけ', romaji: 'gake', meaning: 'vách đá', partOfSpeech: 'danh từ' },
      { kanji: '概説', kana: 'がいせつ', romaji: 'gaisetsu', meaning: 'bài khái quát, đại cương', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '概略', kana: 'がいりゃく', romaji: 'gairyaku', meaning: 'đại khái, tóm lược', partOfSpeech: 'danh từ' },
      { kanji: '街道', kana: 'かいどう', romaji: 'kaidō', meaning: 'quốc lộ, đại lộ', partOfSpeech: 'danh từ' },
      { kanji: '各種', kana: 'かくしゅ', romaji: 'kakushu', meaning: 'các loại, mọi loại', partOfSpeech: 'danh từ' },
      { kanji: '拡散', kana: 'かくさん', romaji: 'kakusan', meaning: 'sự khuếch tán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '獲得', kana: 'かくとく', romaji: 'kakutoku', meaning: 'sự giành được', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '獲物', kana: 'えもの', romaji: 'emono', meaning: 'con mồi, chiến lợi phẩm', partOfSpeech: 'danh từ' },
      { kanji: '確定', kana: 'かくてい', romaji: 'kakutei', meaning: 'sự xác định, quyết định chắc chắn', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 927,
    jlptLevel: 'N1',
    words: [
      { kanji: '確保', kana: 'かくほ', romaji: 'kakuho', meaning: 'sự đảm bảo, giữ chắc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '覚え', kana: 'おぼえ', romaji: 'oboe', meaning: 'trí nhớ, kinh nghiệm', partOfSpeech: 'danh từ' },
      { kanji: '隔たります', kana: 'へだたります', romaji: 'hedatarimasu', meaning: 'cách xa, xa cách', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '隔週', kana: 'かくしゅう', romaji: 'kakushū', meaning: 'hai tuần một lần', partOfSpeech: 'danh từ' },
      { kanji: '学芸', kana: 'がくげい', romaji: 'gakugei', meaning: 'học thuật và nghệ thuật', partOfSpeech: 'danh từ' },
      { kanji: '学士', kana: 'がくし', romaji: 'gakushi', meaning: 'cử nhân (bằng đại học)', partOfSpeech: 'danh từ' },
      { kanji: '楽観', kana: 'らっかん', romaji: 'rakkan', meaning: 'sự lạc quan', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '楽譜', kana: 'がくふ', romaji: 'gakufu', meaning: 'bản nhạc', partOfSpeech: 'danh từ' },
      { kanji: '顎', kana: 'あご', romaji: 'ago', meaning: 'cằm, hàm', partOfSpeech: 'danh từ' },
      { kanji: '掛け', kana: 'かけ', romaji: 'kake', meaning: 'sự mua chịu, ghi nợ', partOfSpeech: 'danh từ' },
      { kanji: '割り込みます', kana: 'わりこみます', romaji: 'warikomimasu', meaning: 'chen vào, ngắt lời', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '割り当て', kana: 'わりあて', romaji: 'wariate', meaning: 'sự phân bổ, chỉ tiêu', partOfSpeech: 'danh từ' },
      { kanji: '活けます', kana: 'いけます', romaji: 'ikemasu', meaning: 'cắm hoa', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '活発', kana: 'かっぱつ', romaji: 'kappatsu', meaning: 'hoạt bát, năng động', partOfSpeech: 'tính từ na' },
      { kanji: '滑らか', kana: 'なめらか', romaji: 'nameraka', meaning: 'trơn tru, mượt mà', partOfSpeech: 'tính từ na' },
      { kanji: '滑稽', kana: 'こっけい', romaji: 'kokkei', meaning: 'buồn cười, hài hước', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '叶います', kana: 'かないます', romaji: 'kanaimasu', meaning: 'trở thành sự thật (ước nguyện)', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 928,
    jlptLevel: 'N1',
    words: [
      { kanji: '叶えます', kana: 'かなえます', romaji: 'kanaemasu', meaning: 'làm cho thành hiện thực', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '噛み切ります', kana: 'かみきります', romaji: 'kamikirimasu', meaning: 'cắn đứt', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '粥', kana: 'かゆ', romaji: 'kayu', meaning: 'cháo', partOfSpeech: 'danh từ' },
      { kanji: '勘弁', kana: 'かんべん', romaji: 'kanben', meaning: 'sự tha thứ, khoan dung', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '勧め', kana: 'すすめ', romaji: 'susume', meaning: 'lời khuyên, sự khuyến khích', partOfSpeech: 'danh từ' },
      { kanji: '勧誘', kana: 'かんゆう', romaji: 'kanyū', meaning: 'sự mời gọi, rủ rê', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '巻', kana: 'まき', romaji: 'maki', meaning: 'tập, cuộn (sách)', partOfSpeech: 'danh từ' },
      { kanji: '堪らない', kana: 'たまらない', romaji: 'tamaranai', meaning: 'không chịu nổi, cực kỳ', partOfSpeech: 'tính từ i' },
      { kanji: '完璧', kana: 'かんぺき', romaji: 'kanpeki', meaning: 'hoàn hảo', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '干し物', kana: 'ほしもの', romaji: 'hoshimono', meaning: 'đồ phơi (quần áo)', partOfSpeech: 'danh từ' },
      { kanji: '幹線', kana: 'かんせん', romaji: 'kansen', meaning: 'tuyến đường chính', partOfSpeech: 'danh từ' },
      { kanji: '幹部', kana: 'かんぶ', romaji: 'kanbu', meaning: 'cán bộ lãnh đạo, ban giám đốc', partOfSpeech: 'danh từ' },
      { kanji: '感触', kana: 'かんしょく', romaji: 'kanshoku', meaning: 'cảm giác, xúc cảm', partOfSpeech: 'danh từ' },
    ],
  },
];
