// Bổ sung từ vựng N2 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 724-729.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N2_PART5: JlptVocabUnit[] = [
  {
    lessonNumber: 724,
    jlptLevel: 'N2',
    words: [
      { kanji: '括弧', kana: 'かっこ', romaji: 'kakko', meaning: 'dấu ngoặc', partOfSpeech: 'danh từ' },
      { kanji: '活字', kana: 'かつじ', romaji: 'katsuji', meaning: 'chữ in', partOfSpeech: 'danh từ' },
      { kanji: '活躍', kana: 'かつやく', romaji: 'katsuyaku', meaning: 'sự hoạt động tích cực, tỏa sáng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '活力', kana: 'かつりょく', romaji: 'katsuryoku', meaning: 'sức sống, năng lượng', partOfSpeech: 'danh từ' },
      { kanji: '釜', kana: 'かま', romaji: 'kama', meaning: 'nồi gang, ấm đun', partOfSpeech: 'danh từ' },
      { kanji: '瓦', kana: 'かわら', romaji: 'kawara', meaning: 'ngói lợp mái', partOfSpeech: 'danh từ' },
      { kanji: '乾かします', kana: 'かわかします', romaji: 'kawakashimasu', meaning: 'làm khô, phơi khô', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '乾電池', kana: 'かんでんち', romaji: 'kandenchi', meaning: 'pin khô', partOfSpeech: 'danh từ' },
      { kanji: '冠', kana: 'かんむり', romaji: 'kanmuri', meaning: 'vương miện', partOfSpeech: 'danh từ' },
      { kanji: '寒帯', kana: 'かんたい', romaji: 'kantai', meaning: 'vùng hàn đới', partOfSpeech: 'danh từ' },
      { kanji: '官庁', kana: 'かんちょう', romaji: 'kanchō', meaning: 'cơ quan chính phủ', partOfSpeech: 'danh từ' },
      { kanji: '干します', kana: 'ほします', romaji: 'hoshimasu', meaning: 'phơi khô', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '換気', kana: 'かんき', romaji: 'kanki', meaning: 'sự thông gió', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '甘やかします', kana: 'あまやかします', romaji: 'amayakashimasu', meaning: 'nuông chiều, làm hư', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '看板', kana: 'かんばん', romaji: 'kanban', meaning: 'biển hiệu', partOfSpeech: 'danh từ' },
      { kanji: '看病', kana: 'かんびょう', romaji: 'kanbyō', meaning: 'sự chăm sóc người bệnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '緩い', kana: 'ゆるい', romaji: 'yurui', meaning: 'lỏng lẻo, chậm, khoan dung', partOfSpeech: 'tính từ i' },
    ],
  },
  {
    lessonNumber: 725,
    jlptLevel: 'N2',
    words: [
      { kanji: '観測', kana: 'かんそく', romaji: 'kansoku', meaning: 'sự quan trắc, quan sát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '間も無く', kana: 'まもなく', romaji: 'mamonaku', meaning: 'chẳng bao lâu nữa', partOfSpeech: 'phó từ' },
      { kanji: '間接', kana: 'かんせつ', romaji: 'kansetsu', meaning: 'gián tiếp', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '関東', kana: 'かんとう', romaji: 'kantō', meaning: 'vùng Kanto (miền đông Nhật Bản)', partOfSpeech: 'danh từ' },
      { kanji: '含めます', kana: 'ふくめます', romaji: 'fukumemasu', meaning: 'bao gồm cả, tính cả', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '危うい', kana: 'あやうい', romaji: 'ayaui', meaning: 'nguy hiểm, nguy cấp', partOfSpeech: 'tính từ i' },
      { kanji: '基地', kana: 'きち', romaji: 'kichi', meaning: 'căn cứ', partOfSpeech: 'danh từ' },
      { kanji: '寄せます', kana: 'よせます', romaji: 'yosemasu', meaning: 'dồn lại, đưa tới gần', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '幾分', kana: 'いくぶん', romaji: 'ikubun', meaning: 'phần nào, ít nhiều', partOfSpeech: 'phó từ' },
      { kanji: '機関車', kana: 'きかんしゃ', romaji: 'kikansha', meaning: 'đầu máy xe lửa', partOfSpeech: 'danh từ' },
      { kanji: '気圧', kana: 'きあつ', romaji: 'kiatsu', meaning: 'áp suất khí quyển', partOfSpeech: 'danh từ' },
      { kanji: '気配', kana: 'けはい', romaji: 'kehai', meaning: 'dấu hiệu, linh cảm', partOfSpeech: 'danh từ' },
      { kanji: '稀', kana: 'まれ', romaji: 'mare', meaning: 'hiếm, hiếm khi', partOfSpeech: 'tính từ na' },
      { kanji: '規律', kana: 'きりつ', romaji: 'kiritsu', meaning: 'kỷ luật, quy tắc', partOfSpeech: 'danh từ' },
      { kanji: '記号', kana: 'きごう', romaji: 'kigō', meaning: 'ký hiệu', partOfSpeech: 'danh từ' },
      { kanji: '飢饉', kana: 'ききん', romaji: 'kikin', meaning: 'nạn đói', partOfSpeech: 'danh từ' },
      { kanji: '詰まります', kana: 'つまります', romaji: 'tsumarimasu', meaning: 'bị nghẹt, bị tắc', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 726,
    jlptLevel: 'N2',
    words: [
      { kanji: '客間', kana: 'きゃくま', romaji: 'kyakuma', meaning: 'phòng khách', partOfSpeech: 'danh từ' },
      { kanji: '逆さ', kana: 'さかさ', romaji: 'sakasa', meaning: 'ngược, lộn ngược', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '逆様', kana: 'さかさま', romaji: 'sakasama', meaning: 'ngược, lộn ngược (nhấn mạnh)', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '休業', kana: 'きゅうぎょう', romaji: 'kyūgyō', meaning: 'sự tạm nghỉ kinh doanh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '給与', kana: 'きゅうよ', romaji: 'kyūyo', meaning: 'tiền lương, trợ cấp', partOfSpeech: 'danh từ' },
      { kanji: '漁業', kana: 'ぎょぎょう', romaji: 'gyogyō', meaning: 'ngành ngư nghiệp', partOfSpeech: 'danh từ' },
      { kanji: '漁師', kana: 'りょうし', romaji: 'ryōshi', meaning: 'ngư dân', partOfSpeech: 'danh từ' },
      { kanji: '競馬', kana: 'けいば', romaji: 'keiba', meaning: 'đua ngựa', partOfSpeech: 'danh từ' },
      { kanji: '強引', kana: 'ごういん', romaji: 'gōin', meaning: 'cưỡng ép, áp đặt', partOfSpeech: 'tính từ na' },
      { kanji: '強気', kana: 'つよき', romaji: 'tsuyoki', meaning: 'cứng rắn, kiên quyết', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '恐縮', kana: 'きょうしゅく', romaji: 'kyōshuku', meaning: 'cảm thấy áy náy, ngại ngùng (vì phiền ai)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '挟まります', kana: 'はさまります', romaji: 'hasamarimasu', meaning: 'bị kẹp giữa, bị kẹt', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '挟みます', kana: 'はさみます', romaji: 'hasamimasu', meaning: 'kẹp, cài giữa', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '教わります', kana: 'おそわります', romaji: 'osowarimasu', meaning: 'được dạy, được chỉ bảo', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '響き', kana: 'ひびき', romaji: 'hibiki', meaning: 'tiếng vang, âm vang', partOfSpeech: 'danh từ' },
      { kanji: '響きます', kana: 'ひびきます', romaji: 'hibikimasu', meaning: 'vang lên, vang dội', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '驚かします', kana: 'おどろかします', romaji: 'odorokashimasu', meaning: 'làm ngạc nhiên, làm giật mình', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 727,
    jlptLevel: 'N2',
    words: [
      { kanji: '曲げます', kana: 'まげます', romaji: 'magemasu', meaning: 'uốn cong, bẻ cong', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '曲線', kana: 'きょくせん', romaji: 'kyokusen', meaning: 'đường cong', partOfSpeech: 'danh từ' },
      { kanji: '近々', kana: 'ちかぢか', romaji: 'chikajika', meaning: 'sắp tới, trong nay mai', partOfSpeech: 'phó từ' },
      { kanji: '近寄ります', kana: 'ちかよります', romaji: 'chikayorimasu', meaning: 'đến gần, tiếp cận', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '近付けます', kana: 'ちかづけます', romaji: 'chikazukemasu', meaning: 'đưa lại gần, cho tiếp cận', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '金魚', kana: 'きんぎょ', romaji: 'kingyo', meaning: 'cá vàng', partOfSpeech: 'danh từ' },
      { kanji: '句読点', kana: 'くとうてん', romaji: 'kutōten', meaning: 'dấu câu', partOfSpeech: 'danh từ' },
      { kanji: '区域', kana: 'くいき', romaji: 'kuiki', meaning: 'khu vực, phạm vi', partOfSpeech: 'danh từ' },
      { kanji: '区切ります', kana: 'くぎります', romaji: 'kugirimasu', meaning: 'phân đoạn, ngắt câu', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '苦情', kana: 'くじょう', romaji: 'kujō', meaning: 'lời than phiền, khiếu nại', partOfSpeech: 'danh từ' },
      { kanji: '空っぽ', kana: 'からっぽ', romaji: 'karappo', meaning: 'trống rỗng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '空想', kana: 'くうそう', romaji: 'kūsō', meaning: 'sự tưởng tượng, mộng tưởng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '空中', kana: 'くうちゅう', romaji: 'kūchū', meaning: 'trên không trung', partOfSpeech: 'danh từ' },
      { kanji: '偶数', kana: 'ぐうすう', romaji: 'gūsū', meaning: 'số chẵn', partOfSpeech: 'danh từ' },
      { kanji: '櫛', kana: 'くし', romaji: 'kushi', meaning: 'cái lược', partOfSpeech: 'danh từ' },
      { kanji: '屑', kana: 'くず', romaji: 'kuzu', meaning: 'rác, vụn, phế liệu', partOfSpeech: 'danh từ' },
      { kanji: '群れ', kana: 'むれ', romaji: 'mure', meaning: 'đàn, bầy, nhóm', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 728,
    jlptLevel: 'N2',
    words: [
      { kanji: '係わります', kana: 'かかわります', romaji: 'kakawarimasu', meaning: 'liên quan đến, dính líu tới', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '傾きます', kana: 'かたむきます', romaji: 'katamukimasu', meaning: 'nghiêng, ngả về', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '形式', kana: 'けいしき', romaji: 'keishiki', meaning: 'hình thức', partOfSpeech: 'danh từ' },
      { kanji: '形容詞', kana: 'けいようし', romaji: 'keiyōshi', meaning: 'tính từ (loại i)', partOfSpeech: 'danh từ' },
      { kanji: '形容動詞', kana: 'けいようどうし', romaji: 'keiyōdōshi', meaning: 'tính từ (loại na)', partOfSpeech: 'danh từ' },
      { kanji: '恵まれます', kana: 'めぐまれます', romaji: 'megumaremasu', meaning: 'được ban phước, được ưu đãi', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '敬います', kana: 'うやまいます', romaji: 'uyamaimasu', meaning: 'kính trọng, tôn kính', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '敬語', kana: 'けいご', romaji: 'keigo', meaning: 'kính ngữ', partOfSpeech: 'danh từ' },
      { kanji: '稽古', kana: 'けいこ', romaji: 'keiko', meaning: 'sự luyện tập, rèn luyện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '経度', kana: 'けいど', romaji: 'keido', meaning: 'kinh độ', partOfSpeech: 'danh từ' },
      { kanji: '繋がり', kana: 'つながり', romaji: 'tsunagari', meaning: 'mối liên kết, quan hệ', partOfSpeech: 'danh từ' },
      { kanji: '繋がります', kana: 'つながります', romaji: 'tsunagarimasu', meaning: 'được kết nối, liên quan tới', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '繋げます', kana: 'つなげます', romaji: 'tsunagemasu', meaning: 'kết nối, nối liền', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '蛍光灯', kana: 'けいこうとう', romaji: 'keikōtō', meaning: 'đèn huỳnh quang', partOfSpeech: 'danh từ' },
      { kanji: '警備', kana: 'けいび', romaji: 'keibi', meaning: 'sự canh gác, bảo vệ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '芸能', kana: 'げいのう', romaji: 'geinō', meaning: 'nghệ thuật giải trí', partOfSpeech: 'danh từ' },
      { kanji: '激増', kana: 'げきぞう', romaji: 'gekizō', meaning: 'sự tăng vọt', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 729,
    jlptLevel: 'N2',
    words: [
      { kanji: '隙間', kana: 'すきま', romaji: 'sukima', meaning: 'khe hở, kẽ hở', partOfSpeech: 'danh từ' },
      { kanji: '桁', kana: 'けた', romaji: 'keta', meaning: 'chữ số hàng (đơn vị, chục...)', partOfSpeech: 'danh từ' },
      { kanji: '血圧', kana: 'けつあつ', romaji: 'ketsuatsu', meaning: 'huyết áp', partOfSpeech: 'danh từ' },
      { kanji: '血液', kana: 'けつえき', romaji: 'ketsueki', meaning: 'máu', partOfSpeech: 'danh từ' },
      { kanji: '月給', kana: 'げっきゅう', romaji: 'gekkyū', meaning: 'lương tháng', partOfSpeech: 'danh từ' },
      { kanji: '月日', kana: 'つきひ', romaji: 'tsukihi', meaning: 'ngày tháng, thời gian', partOfSpeech: 'danh từ' },
      { kanji: '月末', kana: 'げつまつ', romaji: 'getsumatsu', meaning: 'cuối tháng', partOfSpeech: 'danh từ' },
      { kanji: '兼ねます', kana: 'かねます', romaji: 'kanemasu', meaning: 'kiêm nhiệm; khó có thể', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '献立', kana: 'こんだて', romaji: 'kondate', meaning: 'thực đơn, kế hoạch bữa ăn', partOfSpeech: 'danh từ' },
      { kanji: '県庁', kana: 'けんちょう', romaji: 'kenchō', meaning: 'văn phòng tỉnh', partOfSpeech: 'danh từ' },
      { kanji: '見下ろします', kana: 'みおろします', romaji: 'mioroshimasu', meaning: 'nhìn xuống, coi thường', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '見学', kana: 'けんがく', romaji: 'kengaku', meaning: 'sự tham quan học tập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '見掛け', kana: 'みかけ', romaji: 'mikake', meaning: 'vẻ bề ngoài', partOfSpeech: 'danh từ' },
    ],
  },
];
