// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 1001-1006.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART18: JlptVocabUnit[] = [
  {
    lessonNumber: 1001,
    jlptLevel: 'N1',
    words: [
      { kanji: '土木', kana: 'どぼく', romaji: 'doboku', meaning: 'công trình xây dựng dân dụng', partOfSpeech: 'danh từ' },
      { kanji: '奴', kana: 'やっこ', romaji: 'yakko', meaning: 'kẻ hầu, gã (thân mật/khinh miệt)', partOfSpeech: 'danh từ' },
      { kanji: '怒ります', kana: 'いかります', romaji: 'ikarimasu', meaning: 'nổi giận, tức giận', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '冬眠', kana: 'とうみん', romaji: 'tōmin', meaning: 'sự ngủ đông', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '投げ出します', kana: 'なげだします', romaji: 'nagedashimasu', meaning: 'vứt bỏ, từ bỏ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '投入', kana: 'とうにゅう', romaji: 'tōnyū', meaning: 'sự đầu tư, đưa vào', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '東', kana: 'あずま', romaji: 'azuma', meaning: 'phía đông (vùng Kanto, cách gọi cổ)', partOfSpeech: 'danh từ' },
      { kanji: '盗み', kana: 'ぬすみ', romaji: 'nusumi', meaning: 'sự ăn trộm', partOfSpeech: 'danh từ' },
      { kanji: '灯', kana: 'ともしび', romaji: 'tomoshibi', meaning: 'ánh đèn', partOfSpeech: 'danh từ' },
      { kanji: '当て字', kana: 'あてじ', romaji: 'ateji', meaning: 'chữ kanji dùng theo âm (ateji)', partOfSpeech: 'danh từ' },
      { kanji: '当人', kana: 'とうにん', romaji: 'tōnin', meaning: 'chính người đó', partOfSpeech: 'danh từ' },
      { kanji: '当選', kana: 'とうせん', romaji: 'tōsen', meaning: 'sự trúng cử, trúng thưởng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '等級', kana: 'とうきゅう', romaji: 'tōkyū', meaning: 'cấp bậc, hạng', partOfSpeech: 'danh từ' },
      { kanji: '統率', kana: 'とうそつ', romaji: 'tōsotsu', meaning: 'sự chỉ huy, thống lĩnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '到達', kana: 'とうたつ', romaji: 'tōtatsu', meaning: 'sự đạt đến, tới nơi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '到底', kana: 'とうてい', romaji: 'tōtei', meaning: 'hoàn toàn không thể (đi với phủ định)', partOfSpeech: 'phó từ' },
      { kanji: '蕩けます', kana: 'とろけます', romaji: 'torokemasu', meaning: 'tan chảy, mê mẩn', partOfSpeech: 'động từ nhóm 2' },
    ],
  },
  {
    lessonNumber: 1002,
    jlptLevel: 'N1',
    words: [
      { kanji: '討議', kana: 'とうぎ', romaji: 'tōgi', meaning: 'sự thảo luận, tranh luận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '踏まえます', kana: 'ふまえます', romaji: 'fumaemasu', meaning: 'dựa trên, căn cứ vào', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '逃げ出します', kana: 'にげだします', romaji: 'nigedashimasu', meaning: 'bỏ chạy, trốn thoát', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '逃します', kana: 'のがします', romaji: 'nogashimasu', meaning: 'để lỡ, để sổng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '逃れます', kana: 'のがれます', romaji: 'nogaremasu', meaning: 'thoát khỏi, trốn thoát', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '逃走', kana: 'とうそう', romaji: 'tōsō', meaning: 'sự bỏ trốn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '逃亡', kana: 'とうぼう', romaji: 'tōbō', meaning: 'sự đào tẩu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '陶器', kana: 'とうき', romaji: 'tōki', meaning: 'đồ gốm sứ', partOfSpeech: 'danh từ' },
      { kanji: '動き', kana: 'うごき', romaji: 'ugoki', meaning: 'sự chuyển động, xu hướng', partOfSpeech: 'danh từ' },
      { kanji: '動員', kana: 'どういん', romaji: 'dōin', meaning: 'sự động viên, huy động', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '動機', kana: 'どうき', romaji: 'dōki', meaning: 'động cơ, lý do thúc đẩy', partOfSpeech: 'danh từ' },
      { kanji: '動的', kana: 'どうてき', romaji: 'dōteki', meaning: 'linh động, năng động', partOfSpeech: 'tính từ na' },
      { kanji: '動力', kana: 'どうりょく', romaji: 'dōryoku', meaning: 'động lực, năng lượng vận hành', partOfSpeech: 'danh từ' },
      { kanji: '同い年', kana: 'おないどし', romaji: 'onaidoshi', meaning: 'cùng tuổi', partOfSpeech: 'danh từ' },
      { kanji: '同感', kana: 'どうかん', romaji: 'dōkan', meaning: 'sự đồng cảm, cùng quan điểm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '同級', kana: 'どうきゅう', romaji: 'dōkyū', meaning: 'cùng lớp, cùng khối', partOfSpeech: 'danh từ' },
      { kanji: '同居', kana: 'どうきょ', romaji: 'dōkyo', meaning: 'sự sống chung', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 1003,
    jlptLevel: 'N1',
    words: [
      { kanji: '同等', kana: 'どうとう', romaji: 'dōtō', meaning: 'ngang hàng, bình đẳng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '同封', kana: 'どうふう', romaji: 'dōfū', meaning: 'sự đính kèm (trong thư)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '同盟', kana: 'どうめい', romaji: 'dōmei', meaning: 'liên minh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '堂々', kana: 'どうどう', romaji: 'dōdō', meaning: 'hiên ngang, đường hoàng', partOfSpeech: 'tính từ na' },
      { kanji: '導きます', kana: 'みちびきます', romaji: 'michibikimasu', meaning: 'dẫn dắt, hướng dẫn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '憧れ', kana: 'あこがれ', romaji: 'akogare', meaning: 'niềm khao khát, ngưỡng mộ', partOfSpeech: 'danh từ' },
      { kanji: '銅', kana: 'あかがね', romaji: 'akagane', meaning: 'đồng (kim loại, cách gọi cổ)', partOfSpeech: 'danh từ' },
      { kanji: '得点', kana: 'とくてん', romaji: 'tokuten', meaning: 'điểm số đạt được', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '特許', kana: 'とっきょ', romaji: 'tokkyo', meaning: 'bằng sáng chế', partOfSpeech: 'danh từ' },
      { kanji: '特権', kana: 'とっけん', romaji: 'tokken', meaning: 'đặc quyền', partOfSpeech: 'danh từ' },
      { kanji: '特産', kana: 'とくさん', romaji: 'tokusan', meaning: 'đặc sản', partOfSpeech: 'danh từ' },
      { kanji: '特集', kana: 'とくしゅう', romaji: 'tokushū', meaning: 'chuyên đề, số đặc biệt', partOfSpeech: 'danh từ' },
      { kanji: '特派', kana: 'とくは', romaji: 'tokuha', meaning: 'sự cử phái viên đặc biệt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '特有', kana: 'とくゆう', romaji: 'tokuyū', meaning: 'đặc trưng riêng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '独占', kana: 'どくせん', romaji: 'dokusen', meaning: 'sự độc quyền', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '読み上げます', kana: 'よみあげます', romaji: 'yomiagemasu', meaning: 'đọc to lên', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '読者', kana: 'どくしゃ', romaji: 'dokusha', meaning: 'độc giả', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 1004,
    jlptLevel: 'N1',
    words: [
      { kanji: '突きます', kana: 'つつきます', romaji: 'tsutsukimasu', meaning: 'chọc, thúc, mổ (chim)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '突っ張ります', kana: 'つっぱります', romaji: 'tsupparimasu', meaning: 'chống đỡ, cứng đầu giữ ý kiến', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '突如', kana: 'とつじょ', romaji: 'totsujo', meaning: 'đột nhiên', partOfSpeech: 'phó từ' },
      { kanji: '突破', kana: 'とっぱ', romaji: 'toppa', meaning: 'sự đột phá, vượt qua', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '届け', kana: 'とどけ', romaji: 'todoke', meaning: 'đơn báo cáo, thông báo', partOfSpeech: 'danh từ' },
      { kanji: '鈍ります', kana: 'なまります', romaji: 'namarimasu', meaning: 'trở nên cùn, kém đi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '鈍感', kana: 'どんかん', romaji: 'donkan', meaning: 'chậm hiểu, kém nhạy cảm', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '内閣', kana: 'ないかく', romaji: 'naikaku', meaning: 'nội các', partOfSpeech: 'danh từ' },
      { kanji: '内臓', kana: 'ないぞう', romaji: 'naizō', meaning: 'nội tạng', partOfSpeech: 'danh từ' },
      { kanji: '内部', kana: 'ないぶ', romaji: 'naibu', meaning: 'bên trong, nội bộ', partOfSpeech: 'danh từ' },
      { kanji: '内訳', kana: 'うちわけ', romaji: 'uchiwake', meaning: 'bảng phân tích chi tiết', partOfSpeech: 'danh từ' },
      { kanji: '内乱', kana: 'ないらん', romaji: 'nairan', meaning: 'nội chiến', partOfSpeech: 'danh từ' },
      { kanji: '内陸', kana: 'ないりく', romaji: 'nairiku', meaning: 'nội địa, trong lục địa', partOfSpeech: 'danh từ' },
      { kanji: '馴れ馴れしい', kana: 'なれなれしい', romaji: 'narenareshii', meaning: 'quá thân mật, sỗ sàng', partOfSpeech: 'tính từ i' },
      { kanji: '二人', kana: 'ににん', romaji: 'ninin', meaning: 'hai người (cách đếm trang trọng)', partOfSpeech: 'danh từ' },
      { kanji: '賑わいます', kana: 'にぎわいます', romaji: 'nigiwaimasu', meaning: 'nhộn nhịp, đông đúc', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '肉親', kana: 'にくしん', romaji: 'nikushin', meaning: 'người thân ruột thịt', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 1005,
    jlptLevel: 'N1',
    words: [
      { kanji: '肉体', kana: 'にくたい', romaji: 'nikutai', meaning: 'thể xác', partOfSpeech: 'danh từ' },
      { kanji: '日々', kana: 'ひび', romaji: 'hibi', meaning: 'hằng ngày', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '日の丸', kana: 'ひのまる', romaji: 'hinomaru', meaning: 'quốc kỳ Nhật Bản', partOfSpeech: 'danh từ' },
      { kanji: '日向', kana: 'ひなた', romaji: 'hinata', meaning: 'chỗ có nắng', partOfSpeech: 'danh từ' },
      { kanji: '日頃', kana: 'ひごろ', romaji: 'higoro', meaning: 'thường ngày', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '日取り', kana: 'ひどり', romaji: 'hidori', meaning: 'ngày ấn định', partOfSpeech: 'danh từ' },
      { kanji: '日焼け', kana: 'ひやけ', romaji: 'hiyake', meaning: 'sự cháy nắng, rám nắng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '日当', kana: 'にっとう', romaji: 'nittō', meaning: 'phụ cấp theo ngày', partOfSpeech: 'danh từ' },
      { kanji: '日夜', kana: 'にちや', romaji: 'nichiya', meaning: 'ngày đêm, luôn luôn', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '入口', kana: 'いりくち', romaji: 'irikuchi', meaning: 'lối vào', partOfSpeech: 'danh từ' },
      { kanji: '入手', kana: 'にゅうしゅ', romaji: 'nyūshu', meaning: 'sự có được, thu được', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '入賞', kana: 'にゅうしょう', romaji: 'nyūshō', meaning: 'sự đoạt giải', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '入浴', kana: 'にゅうよく', romaji: 'nyūyoku', meaning: 'sự tắm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '如何に', kana: 'いかに', romaji: 'ikani', meaning: 'như thế nào, dù thế nào', partOfSpeech: 'phó từ' },
      { kanji: '尿', kana: 'にょう', romaji: 'nyō', meaning: 'nước tiểu', partOfSpeech: 'danh từ' },
      { kanji: '任します', kana: 'まかします', romaji: 'makashimasu', meaning: 'giao phó, ủy thác', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '任務', kana: 'にんむ', romaji: 'ninmu', meaning: 'nhiệm vụ', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 1006,
    jlptLevel: 'N1',
    words: [
      { kanji: '任命', kana: 'にんめい', romaji: 'ninmei', meaning: 'sự bổ nhiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '妊娠', kana: 'にんしん', romaji: 'ninshin', meaning: 'sự mang thai', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '認めます', kana: 'したためます', romaji: 'shitatamemasu', meaning: 'viết, ghi chép (trang trọng)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '熱意', kana: 'ねつい', romaji: 'netsui', meaning: 'nhiệt huyết', partOfSpeech: 'danh từ' },
      { kanji: '熱湯', kana: 'ねっとう', romaji: 'nettō', meaning: 'nước sôi', partOfSpeech: 'danh từ' },
      { kanji: '熱量', kana: 'ねつりょう', romaji: 'netsuryō', meaning: 'nhiệt lượng', partOfSpeech: 'danh từ' },
      { kanji: '年号', kana: 'ねんごう', romaji: 'nengō', meaning: 'niên hiệu', partOfSpeech: 'danh từ' },
      { kanji: '年頃', kana: 'としごろ', romaji: 'toshigoro', meaning: 'độ tuổi, tuổi cập kê', partOfSpeech: 'danh từ' },
      { kanji: '年生', kana: 'ねんせい', romaji: 'nensei', meaning: 'học sinh năm thứ...', partOfSpeech: 'danh từ' },
      { kanji: '年長', kana: 'ねんちょう', romaji: 'nenchō', meaning: 'lớn tuổi hơn', partOfSpeech: 'danh từ' },
      { kanji: '年輪', kana: 'ねんりん', romaji: 'nenrin', meaning: 'vòng tuổi cây (vân gỗ)', partOfSpeech: 'danh từ' },
      { kanji: '念', kana: 'ねん', romaji: 'nen', meaning: 'ý niệm, sự chú tâm', partOfSpeech: 'danh từ' },
      { kanji: '捻じれます', kana: 'ねじれます', romaji: 'nejiremasu', meaning: 'bị vặn xoắn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '燃焼', kana: 'ねんしょう', romaji: 'nenshō', meaning: 'sự đốt cháy', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
];
