// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 953-958.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART10: JlptVocabUnit[] = [
  {
    lessonNumber: 953,
    jlptLevel: 'N1',
    words: [
      { kanji: '済まします', kana: 'すまします', romaji: 'sumashimasu', meaning: 'hoàn tất, giải quyết xong', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '細やか', kana: 'こまやか', romaji: 'komayaka', meaning: 'chu đáo, tình cảm sâu sắc', partOfSpeech: 'tính từ na' },
      { kanji: '細工', kana: 'さいく', romaji: 'saiku', meaning: 'sự chế tác thủ công, mẹo vặt', partOfSpeech: 'danh từ' },
      { kanji: '細胞', kana: 'さいぼう', romaji: 'saibō', meaning: 'tế bào', partOfSpeech: 'danh từ' },
      { kanji: '際', kana: 'きわ', romaji: 'kiwa', meaning: 'bờ mép, ranh giới', partOfSpeech: 'danh từ' },
      { kanji: '財', kana: 'ざい', romaji: 'zai', meaning: 'tài sản, của cải', partOfSpeech: 'danh từ' },
      { kanji: '財源', kana: 'ざいげん', romaji: 'zaigen', meaning: 'nguồn tài chính', partOfSpeech: 'danh từ' },
      { kanji: '冴えます', kana: 'さえます', romaji: 'saemasu', meaning: 'minh mẫn, sáng suốt; lạnh giá', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '作り', kana: 'つくり', romaji: 'tsukuri', meaning: 'cách làm, hình dáng; gỏi cá sống', partOfSpeech: 'danh từ' },
      { kanji: '作戦', kana: 'さくせん', romaji: 'sakusen', meaning: 'chiến thuật, chiến dịch', partOfSpeech: 'danh từ' },
      { kanji: '作物', kana: 'さくぶつ', romaji: 'sakubutsu', meaning: 'tác phẩm văn học', partOfSpeech: 'danh từ' },
      { kanji: '錯誤', kana: 'さくご', romaji: 'sakugo', meaning: 'sự sai lầm, nhầm lẫn', partOfSpeech: 'danh từ' },
      { kanji: '察します', kana: 'さっします', romaji: 'sasshimasu', meaning: 'đoán biết, cảm thông', partOfSpeech: 'động từ する' },
      { kanji: '擦れます', kana: 'すれます', romaji: 'suremasu', meaning: 'cọ xát, trầy xước; từng trải', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '擦れ違い', kana: 'すれちがい', romaji: 'surechigai', meaning: 'sự lỡ gặp nhau', partOfSpeech: 'danh từ' },
      { kanji: '殺人', kana: 'さつじん', romaji: 'satsujin', meaning: 'vụ giết người', partOfSpeech: 'danh từ' },
      { kanji: '雑', kana: 'ざつ', romaji: 'zatsu', meaning: 'cẩu thả, lộn xộn', partOfSpeech: 'danh từ, tính từ na' },
    ],
  },
  {
    lessonNumber: 954,
    jlptLevel: 'N1',
    words: [
      { kanji: '雑貨', kana: 'ざっか', romaji: 'zakka', meaning: 'hàng tạp hóa', partOfSpeech: 'danh từ' },
      { kanji: '雑談', kana: 'ざつだん', romaji: 'zatsudan', meaning: 'chuyện phiếm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '雑木', kana: 'ざつぼく', romaji: 'zatsuboku', meaning: 'cây tạp (nhiều loại cây nhỏ)', partOfSpeech: 'danh từ' },
      { kanji: '三味線', kana: 'さみせん', romaji: 'samisen', meaning: 'đàn shamisen ba dây', partOfSpeech: 'danh từ' },
      { kanji: '参議院', kana: 'さんぎいん', romaji: 'sangiin', meaning: 'Thượng viện (Nhật Bản)', partOfSpeech: 'danh từ' },
      { kanji: '参照', kana: 'さんしょう', romaji: 'sanshō', meaning: 'sự tham chiếu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '参上', kana: 'さんじょう', romaji: 'sanjō', meaning: 'sự đến thăm (khiêm nhường)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '山岳', kana: 'さんがく', romaji: 'sangaku', meaning: 'núi non', partOfSpeech: 'danh từ' },
      { kanji: '山腹', kana: 'さんぷく', romaji: 'sanpuku', meaning: 'sườn núi', partOfSpeech: 'danh từ' },
      { kanji: '山脈', kana: 'さんみゃく', romaji: 'sanmyaku', meaning: 'dãy núi', partOfSpeech: 'danh từ' },
      { kanji: '散蒔きます', kana: 'ばらまきます', romaji: 'baramakimasu', meaning: 'rải ra, phân phát bừa bãi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '桟橋', kana: 'さんばし', romaji: 'sanbashi', meaning: 'cầu tàu, bến cảng', partOfSpeech: 'danh từ' },
      { kanji: '産みます', kana: 'うみます', romaji: 'umimasu', meaning: 'sinh con, sản sinh', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '産休', kana: 'さんきゅう', romaji: 'sankyū', meaning: 'nghỉ thai sản', partOfSpeech: 'danh từ' },
      { kanji: '産後', kana: 'さんご', romaji: 'sango', meaning: 'sau khi sinh', partOfSpeech: 'danh từ' },
      { kanji: '産婦人科', kana: 'さんふじんか', romaji: 'sanfujinka', meaning: 'khoa sản phụ khoa', partOfSpeech: 'danh từ' },
      { kanji: '産物', kana: 'さんぶつ', romaji: 'sanbutsu', meaning: 'sản vật, kết quả', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 955,
    jlptLevel: 'N1',
    words: [
      { kanji: '賛美', kana: 'さんび', romaji: 'sanbi', meaning: 'sự ca ngợi, tán dương', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '残金', kana: 'ざんきん', romaji: 'zankin', meaning: 'số tiền còn lại', partOfSpeech: 'danh từ' },
      { kanji: '残高', kana: 'ざんだか', romaji: 'zandaka', meaning: 'số dư tài khoản', partOfSpeech: 'danh từ' },
      { kanji: '残酷', kana: 'ざんこく', romaji: 'zankoku', meaning: 'sự tàn nhẫn', partOfSpeech: 'tính từ na' },
      { kanji: '仕えます', kana: 'つかえます', romaji: 'tsukaemasu', meaning: 'phục vụ, hầu hạ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '仕掛け', kana: 'しかけ', romaji: 'shikake', meaning: 'cơ chế, cái bẫy, mánh khóe', partOfSpeech: 'danh từ' },
      { kanji: '仕掛けます', kana: 'しかけます', romaji: 'shikakemasu', meaning: 'bắt đầu làm, gài bẫy', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '仕上がり', kana: 'しあがり', romaji: 'shiagari', meaning: 'kết quả hoàn thành', partOfSpeech: 'danh từ' },
      { kanji: '仕上げ', kana: 'しあげ', romaji: 'shiage', meaning: 'công đoạn hoàn thiện', partOfSpeech: 'danh từ' },
      { kanji: '仕上げます', kana: 'しあげます', romaji: 'shiagemasu', meaning: 'hoàn thiện, hoàn tất', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '仕切ります', kana: 'しきります', romaji: 'shikirimasu', meaning: 'ngăn cách, phân chia', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '仕組み', kana: 'しくみ', romaji: 'shikumi', meaning: 'cơ cấu, cấu trúc', partOfSpeech: 'danh từ' },
      { kanji: '仕入れます', kana: 'しいれます', romaji: 'shiiremasu', meaning: 'nhập hàng, tích trữ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '仕付けます', kana: 'しつけます', romaji: 'shitsukemasu', meaning: 'dạy dỗ, uốn nắn (trẻ nhỏ)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '仕立てます', kana: 'したてます', romaji: 'shitatemasu', meaning: 'may đo, đào tạo', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '使い道', kana: 'つかいみち', romaji: 'tsukaimichi', meaning: 'cách sử dụng, công dụng', partOfSpeech: 'danh từ' },
      { kanji: '使用人', kana: 'しようにん', romaji: 'shiyōnin', meaning: 'người làm thuê, gia nhân', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 956,
    jlptLevel: 'N1',
    words: [
      { kanji: '刺', kana: 'とげ', romaji: 'toge', meaning: 'cái gai', partOfSpeech: 'danh từ' },
      { kanji: '刺繍', kana: 'ししゅう', romaji: 'shishū', meaning: 'thêu thùa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '司ります', kana: 'つかさどります', romaji: 'tsukasadorimasu', meaning: 'quản lý, cai quản', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '司法', kana: 'しほう', romaji: 'shihō', meaning: 'tư pháp', partOfSpeech: 'danh từ' },
      { kanji: '始発', kana: 'しはつ', romaji: 'shihatsu', meaning: 'chuyến tàu đầu tiên', partOfSpeech: 'danh từ' },
      { kanji: '子息', kana: 'しそく', romaji: 'shisoku', meaning: 'con trai (cách nói trang trọng)', partOfSpeech: 'danh từ' },
      { kanji: '市街', kana: 'しがい', romaji: 'shigai', meaning: 'khu phố, khu đô thị', partOfSpeech: 'danh từ' },
      { kanji: '志', kana: 'こころざし', romaji: 'kokorozashi', meaning: 'chí hướng, hoài bão', partOfSpeech: 'danh từ' },
      { kanji: '志します', kana: 'こころざします', romaji: 'kokorozashimasu', meaning: 'quyết chí, hướng tới (mục tiêu)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '指差します', kana: 'ゆびさします', romaji: 'yubisashimasu', meaning: 'chỉ tay vào', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '指図', kana: 'さしず', romaji: 'sashizu', meaning: 'sự chỉ thị, ra lệnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '指摘', kana: 'してき', romaji: 'shiteki', meaning: 'sự chỉ ra, chỉ trích', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '指令', kana: 'しれい', romaji: 'shirei', meaning: 'chỉ thị, mệnh lệnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '施します', kana: 'ほどこします', romaji: 'hodokoshimasu', meaning: 'bố thí, thực hiện (biện pháp)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '施行', kana: 'しぎょう', romaji: 'shigyō', meaning: 'sự thi hành, thực thi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '施設', kana: 'しせつ', romaji: 'shisetsu', meaning: 'cơ sở vật chất, cơ sở hạ tầng', partOfSpeech: 'danh từ' },
      { kanji: '止まります', kana: 'とどまります', romaji: 'todomarimasu', meaning: 'dừng lại, giới hạn ở mức', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 957,
    jlptLevel: 'N1',
    words: [
      { kanji: '止めます', kana: 'とどめます', romaji: 'todomemasu', meaning: 'ngăn lại, giữ ở mức', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '死刑', kana: 'しけい', romaji: 'shikei', meaning: 'án tử hình', partOfSpeech: 'danh từ' },
      { kanji: '氏', kana: 'うじ', romaji: 'uji', meaning: 'họ, dòng họ', partOfSpeech: 'danh từ' },
      { kana: 'あたし', romaji: 'atashi', meaning: 'tôi (nữ giới, cách nói thân mật)', partOfSpeech: 'đại từ' },
      { kanji: '私物', kana: 'しぶつ', romaji: 'shibutsu', meaning: 'đồ dùng cá nhân', partOfSpeech: 'danh từ' },
      { kanji: '私有', kana: 'しゆう', romaji: 'shiyū', meaning: 'sở hữu tư nhân', partOfSpeech: 'danh từ' },
      { kanji: '至って', kana: 'いたって', romaji: 'itatte', meaning: 'vô cùng, hết sức', partOfSpeech: 'phó từ' },
      { kanji: '視察', kana: 'しさつ', romaji: 'shisatsu', meaning: 'sự thị sát, thanh tra', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '視野', kana: 'しや', romaji: 'shiya', meaning: 'tầm nhìn, tầm mắt', partOfSpeech: 'danh từ' },
      { kanji: '試み', kana: 'こころみ', romaji: 'kokoromi', meaning: 'sự thử nghiệm', partOfSpeech: 'danh từ' },
      { kanji: '試みます', kana: 'こころみます', romaji: 'kokoromimasu', meaning: 'thử làm, thử nghiệm', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '資金', kana: 'しきん', romaji: 'shikin', meaning: 'vốn, quỹ tài chính', partOfSpeech: 'danh từ' },
      { kanji: '資産', kana: 'しさん', romaji: 'shisan', meaning: 'tài sản', partOfSpeech: 'danh từ' },
      { kanji: '賜ります', kana: 'たまわります', romaji: 'tamawarimasu', meaning: 'được ban tặng (khiêm nhường)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '雌', kana: 'めす', romaji: 'mesu', meaning: 'con cái (động vật)', partOfSpeech: 'danh từ' },
      { kanji: '飼育', kana: 'しいく', romaji: 'shiiku', meaning: 'sự chăn nuôi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '事によると', kana: 'ことによると', romaji: 'kotoniyoruto', meaning: 'tùy theo tình huống, có lẽ', partOfSpeech: 'phó từ' },
    ],
  },
  {
    lessonNumber: 958,
    jlptLevel: 'N1',
    words: [
      { kanji: '事業', kana: 'じぎょう', romaji: 'jigyō', meaning: 'sự nghiệp, dự án kinh doanh', partOfSpeech: 'danh từ' },
      { kanji: '事項', kana: 'じこう', romaji: 'jikō', meaning: 'hạng mục, điều khoản', partOfSpeech: 'danh từ' },
      { kanji: '事前', kana: 'じぜん', romaji: 'jizen', meaning: 'trước khi, sự chuẩn bị trước', partOfSpeech: 'danh từ' },
      { kanji: '事柄', kana: 'ことがら', romaji: 'kotogara', meaning: 'sự việc, vấn đề', partOfSpeech: 'danh từ' },
      { kanji: '似通います', kana: 'にかよいます', romaji: 'nikayoimasu', meaning: 'giống nhau, tương tự', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '侍', kana: 'さむらい', romaji: 'samurai', meaning: 'võ sĩ samurai', partOfSpeech: 'danh từ' },
      { kanji: '字', kana: 'あざ', romaji: 'aza', meaning: 'tiểu khu (đơn vị hành chính nhỏ)', partOfSpeech: 'danh từ' },
      { kanji: '持ち', kana: 'もち', romaji: 'mochi', meaning: 'sự nắm giữ; độ bền', partOfSpeech: 'danh từ' },
      { kanji: '持ち切り', kana: 'もちきり', romaji: 'mochikiri', meaning: 'chủ đề bàn tán khắp nơi', partOfSpeech: 'danh từ' },
      { kanji: '持てます', kana: 'もてます', romaji: 'motemasu', meaning: 'được yêu thích, được ưa chuộng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '持て成します', kana: 'もてなします', romaji: 'motenashimasu', meaning: 'tiếp đãi, chiêu đãi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '時差', kana: 'じさ', romaji: 'jisa', meaning: 'chênh lệch múi giờ', partOfSpeech: 'danh từ' },
      { kanji: '時折', kana: 'ときおり', romaji: 'tokiori', meaning: 'thỉnh thoảng', partOfSpeech: 'phó từ' },
    ],
  },
];
