// Bổ sung kanji N3/N2/N1 để ôn thi — tự soạn tay (không auto-scrape).
// KanjiLesson number mới: N3 310–315, N2 410–417, N1 509–518.

import type { JlptKanjiLesson } from './jlpt-kanji.data';

export const JLPT_KANJI_BOOST2: JlptKanjiLesson[] = [
  // ─────────────────────────────── N3 ───────────────────────────────
  {
    lessonNumber: 310,
    jlptLevel: 'N3',
    title: 'Bài 40 · Kanji N3 bổ sung (1)',
    sortOrder: 3100,
    entries: [
      { character: '腕', hanViet: 'OẢN', onyomi: 'わん', kunyomi: 'うで', meaningVi: 'cánh tay', strokeCount: 12 },
      { character: '胸', hanViet: 'HUNG', onyomi: 'きょう', kunyomi: 'むね, むな-', meaningVi: 'ngực', strokeCount: 10 },
      { character: '腹', hanViet: 'PHÚC', onyomi: 'ふく', kunyomi: 'はら', meaningVi: 'bụng', strokeCount: 13 },
      { character: '腰', hanViet: 'YÊU', onyomi: 'よう', kunyomi: 'こし', meaningVi: 'thắt lưng, hông', strokeCount: 13 },
      { character: '肩', hanViet: 'KIÊN', onyomi: 'けん', kunyomi: 'かた', meaningVi: 'vai', strokeCount: 8 },
      { character: '骨', hanViet: 'CỐT', onyomi: 'こつ', kunyomi: 'ほね', meaningVi: 'xương', strokeCount: 10 },
      { character: '皮', hanViet: 'BÌ', onyomi: 'ひ', kunyomi: 'かわ', meaningVi: 'da, vỏ', strokeCount: 5 },
      { character: '筋', hanViet: 'CÂN', onyomi: 'きん', kunyomi: 'すじ', meaningVi: 'cơ bắp, đường gân', strokeCount: 12 },
      { character: '脳', hanViet: 'NÃO', onyomi: 'のう', meaningVi: 'não bộ', strokeCount: 11 },
      { character: '肺', hanViet: 'PHẾ', onyomi: 'はい', meaningVi: 'phổi', strokeCount: 9 },
      { character: '腸', hanViet: 'TRÀNG', onyomi: 'ちょう', meaningVi: 'ruột', strokeCount: 13 },
      { character: '臓', hanViet: 'TẠNG', onyomi: 'ぞう', meaningVi: 'nội tạng', strokeCount: 19 },
      { character: '毛', hanViet: 'MAO', onyomi: 'もう', kunyomi: 'け', meaningVi: 'lông, tóc', strokeCount: 4 },
      { character: '爪', hanViet: 'TRẢO', onyomi: 'そう', kunyomi: 'つめ', meaningVi: 'móng tay/chân', strokeCount: 4 },
      { character: '涙', hanViet: 'LỆ', onyomi: 'るい', kunyomi: 'なみだ', meaningVi: 'nước mắt', strokeCount: 10 },
      { character: '汗', hanViet: 'HÃN', onyomi: 'かん', kunyomi: 'あせ', meaningVi: 'mồ hôi', strokeCount: 6 },
      { character: '傷', hanViet: 'THƯƠNG', onyomi: 'しょう', kunyomi: 'きず', meaningVi: 'vết thương', strokeCount: 13 },
      { character: '疫', hanViet: 'DỊCH', onyomi: 'えき, やく', meaningVi: 'dịch bệnh', strokeCount: 9 },
      { character: '症', hanViet: 'CHỨNG', onyomi: 'しょう', meaningVi: 'triệu chứng', strokeCount: 10 },
      { character: '療', hanViet: 'LIỆU', onyomi: 'りょう', meaningVi: 'chữa trị (治療)', strokeCount: 17 },
    ],
  },
  {
    lessonNumber: 311,
    jlptLevel: 'N3',
    title: 'Bài 41 · Kanji N3 bổ sung (2)',
    sortOrder: 3110,
    entries: [
      { character: '桜', hanViet: 'ANH', onyomi: 'おう', kunyomi: 'さくら', meaningVi: 'hoa anh đào', strokeCount: 10 },
      { character: '梅', hanViet: 'MAI', onyomi: 'ばい', kunyomi: 'うめ', meaningVi: 'hoa mơ', strokeCount: 10 },
      { character: '菊', hanViet: 'CÚC', onyomi: 'きく', meaningVi: 'hoa cúc', strokeCount: 11 },
      { character: '竹', hanViet: 'TRÚC', onyomi: 'ちく', kunyomi: 'たけ', meaningVi: 'cây tre', strokeCount: 6 },
      { character: '松', hanViet: 'TÙNG', onyomi: 'しょう', kunyomi: 'まつ', meaningVi: 'cây tùng', strokeCount: 8 },
      { character: '葉', hanViet: 'DIỆP', onyomi: 'よう', kunyomi: 'は', meaningVi: 'lá cây', strokeCount: 12 },
      { character: '根', hanViet: 'CĂN', onyomi: 'こん', kunyomi: 'ね', meaningVi: 'rễ cây, căn nguyên', strokeCount: 10 },
      { character: '枝', hanViet: 'CHI', onyomi: 'し', kunyomi: 'えだ', meaningVi: 'cành cây', strokeCount: 8 },
      { character: '幹', hanViet: 'CÀN', onyomi: 'かん', kunyomi: 'みき', meaningVi: 'thân cây, cốt lõi', strokeCount: 13 },
      { character: '芽', hanViet: 'NHA', onyomi: 'が', kunyomi: 'め', meaningVi: 'mầm cây', strokeCount: 8 },
      { character: '穀', hanViet: 'CỐC', onyomi: 'こく', meaningVi: 'ngũ cốc', strokeCount: 14 },
      { character: '麦', hanViet: 'MẠCH', onyomi: 'ばく', kunyomi: 'むぎ', meaningVi: 'lúa mạch', strokeCount: 7 },
      { character: '豆', hanViet: 'ĐẬU', onyomi: 'とう, ず', kunyomi: 'まめ', meaningVi: 'đậu', strokeCount: 7 },
      { character: '稲', hanViet: 'ĐẠO', onyomi: 'とう', kunyomi: 'いね', meaningVi: 'lúa', strokeCount: 14 },
      { character: '穂', hanViet: 'TUỆ', onyomi: 'すい', kunyomi: 'ほ', meaningVi: 'bông lúa', strokeCount: 15 },
      { character: '畑', hanViet: 'ĐIỀN', kunyomi: 'はたけ', meaningVi: 'ruộng rẫy (khô)', strokeCount: 9 },
      { character: '牧', hanViet: 'MỤC', onyomi: 'ぼく', kunyomi: 'まき', meaningVi: 'chăn nuôi', strokeCount: 8 },
      { character: '飼', hanViet: 'TỰ', onyomi: 'し', kunyomi: 'か-う', meaningVi: 'nuôi (thú vật)', strokeCount: 13 },
      { character: '猫', hanViet: 'MIÊU', onyomi: 'びょう', kunyomi: 'ねこ', meaningVi: 'con mèo', strokeCount: 11 },
      { character: '虎', hanViet: 'HỔ', onyomi: 'こ', kunyomi: 'とら', meaningVi: 'con hổ', strokeCount: 8 },
    ],
  },
  {
    lessonNumber: 312,
    jlptLevel: 'N3',
    title: 'Bài 42 · Kanji N3 bổ sung (3)',
    sortOrder: 3120,
    entries: [
      { character: '橋', hanViet: 'KIỀU', onyomi: 'きょう', kunyomi: 'はし', meaningVi: 'cây cầu', strokeCount: 16 },
      { character: '坂', hanViet: 'BẢN', onyomi: 'はん', kunyomi: 'さか', meaningVi: 'con dốc', strokeCount: 7 },
      { character: '岸', hanViet: 'NGẠN', onyomi: 'がん', kunyomi: 'きし', meaningVi: 'bờ (sông, biển)', strokeCount: 8 },
      { character: '湖', hanViet: 'HỒ', onyomi: 'こ', kunyomi: 'みずうみ', meaningVi: 'hồ nước', strokeCount: 12 },
      { character: '泉', hanViet: 'TUYỀN', onyomi: 'せん', kunyomi: 'いずみ', meaningVi: 'suối nước', strokeCount: 9 },
      { character: '滝', hanViet: 'LUNG', onyomi: 'ろう', kunyomi: 'たき', meaningVi: 'thác nước', strokeCount: 13 },
      { character: '洞', hanViet: 'ĐỘNG', onyomi: 'どう', kunyomi: 'ほら', meaningVi: 'hang động', strokeCount: 9 },
      { character: '崎', hanViet: 'KỲ', kunyomi: 'さき', meaningVi: 'mũi đất, ghềnh (địa danh)', strokeCount: 11 },
      { character: '峠', hanViet: 'PHÁI', kunyomi: 'とうげ', meaningVi: 'đỉnh đèo', strokeCount: 9 },
      { character: '谷', hanViet: 'CỐC', onyomi: 'こく', kunyomi: 'たに', meaningVi: 'thung lũng', strokeCount: 7 },
      { character: '沖', hanViet: 'XUNG', onyomi: 'ちゅう', kunyomi: 'おき', meaningVi: 'ngoài khơi', strokeCount: 7 },
      { character: '波', hanViet: 'BA', onyomi: 'は', kunyomi: 'なみ', meaningVi: 'sóng biển', strokeCount: 8 },
      { character: '砂', hanViet: 'SA', onyomi: 'さ, しゃ', kunyomi: 'すな', meaningVi: 'cát', strokeCount: 9 },
      { character: '岩', hanViet: 'NHAM', onyomi: 'がん', kunyomi: 'いわ', meaningVi: 'tảng đá lớn', strokeCount: 8 },
      { character: '洪', hanViet: 'HỒNG', onyomi: 'こう', meaningVi: 'lũ lụt (洪水)', strokeCount: 9 },
      { character: '干', hanViet: 'CAN', onyomi: 'かん', kunyomi: 'ほ-す, ひ-る', meaningVi: 'khô, phơi khô', strokeCount: 3 },
      { character: '燃', hanViet: 'NHIÊN', onyomi: 'ねん', kunyomi: 'も-える, も-やす', meaningVi: 'cháy, đốt', strokeCount: 16 },
      { character: '煙', hanViet: 'YÊN', onyomi: 'えん', kunyomi: 'けむり, けむ-い', meaningVi: 'khói', strokeCount: 13 },
      { character: '炭', hanViet: 'THÁN', onyomi: 'たん', kunyomi: 'すみ', meaningVi: 'than củi', strokeCount: 9 },
      { character: '灰', hanViet: 'HÔI', onyomi: 'かい', kunyomi: 'はい', meaningVi: 'tro', strokeCount: 6 },
    ],
  },
  {
    lessonNumber: 313,
    jlptLevel: 'N3',
    title: 'Bài 43 · Kanji N3 bổ sung (4)',
    sortOrder: 3130,
    entries: [
      { character: '予', hanViet: 'DỰ', onyomi: 'よ', meaningVi: 'lượng trước (dự báo, dự định)', strokeCount: 4 },
      { character: '預', hanViet: 'DỰ', onyomi: 'よ', kunyomi: 'あず-ける, あず-かる', meaningVi: 'gửi (tiền), giữ hộ', strokeCount: 13 },
      { character: '貯', hanViet: 'TRỮ', onyomi: 'ちょ', kunyomi: 'たくわ-える', meaningVi: 'tích trữ (tiền)', strokeCount: 12 },
      { character: '払', hanViet: 'PHẤT', onyomi: 'ふつ', kunyomi: 'はら-う', meaningVi: 'thanh toán, chi trả', strokeCount: 5 },
      { character: '税', hanViet: 'THUẾ', onyomi: 'ぜい', meaningVi: 'thuế', strokeCount: 12 },
      { character: '割', hanViet: 'CÁT', onyomi: 'かつ', kunyomi: 'わ-る, わり', meaningVi: 'chia, cắt; phần mười (tỷ lệ)', strokeCount: 12 },
      { character: '倍', hanViet: 'BỘI', onyomi: 'ばい', meaningVi: 'gấp đôi, bội số', strokeCount: 10 },
      { character: '億', hanViet: 'ỨC', onyomi: 'おく', meaningVi: 'trăm triệu', strokeCount: 15 },
      { character: '兆', hanViet: 'TRIỆU', onyomi: 'ちょう', kunyomi: 'きざ-す', meaningVi: 'nghìn tỷ; điềm báo', strokeCount: 6 },
      { character: '額', hanViet: 'NGẠCH', onyomi: 'がく', kunyomi: 'ひたい', meaningVi: 'số tiền; trán', strokeCount: 18 },
      { character: '貨', hanViet: 'HÓA', onyomi: 'か', meaningVi: 'tiền tệ, hàng hóa', strokeCount: 11 },
      { character: '幣', hanViet: 'TỆ', onyomi: 'へい', meaningVi: 'tiền tệ (紙幣)', strokeCount: 15 },
      { character: '株', hanViet: 'CHU', onyomi: 'しゅ', kunyomi: 'かぶ', meaningVi: 'cổ phần, gốc cây', strokeCount: 10 },
      { character: '証', hanViet: 'CHỨNG', onyomi: 'しょう', meaningVi: 'chứng cứ, bằng chứng', strokeCount: 12 },
      { character: '券', hanViet: 'KHOÁN', onyomi: 'けん', meaningVi: 'vé, phiếu, trái phiếu', strokeCount: 8 },
      { character: '票', hanViet: 'PHIẾU', onyomi: 'ひょう', meaningVi: 'phiếu bầu', strokeCount: 11 },
      { character: '選', hanViet: 'TUYỂN', onyomi: 'せん', kunyomi: 'えら-ぶ', meaningVi: 'lựa chọn, bầu cử', strokeCount: 15 },
      { character: '挙', hanViet: 'CỬ', onyomi: 'きょ', kunyomi: 'あ-げる, あ-がる', meaningVi: 'nâng lên, cử hành', strokeCount: 10 },
      { character: '党', hanViet: 'ĐẢNG', onyomi: 'とう', meaningVi: 'đảng phái', strokeCount: 10 },
      { character: '銭', hanViet: 'TIỀN', onyomi: 'せん', kunyomi: 'ぜに', meaningVi: 'tiền xu, đơn vị tiền nhỏ', strokeCount: 14 },
    ],
  },
  {
    lessonNumber: 314,
    jlptLevel: 'N3',
    title: 'Bài 44 · Kanji N3 bổ sung (5)',
    sortOrder: 3140,
    entries: [
      { character: '劇', hanViet: 'KỊCH', onyomi: 'げき', meaningVi: 'kịch, kịch liệt', strokeCount: 15 },
      { character: '芸', hanViet: 'NGHỆ', onyomi: 'げい', meaningVi: 'nghệ thuật, tài năng', strokeCount: 7 },
      { character: '踊', hanViet: 'DŨNG', onyomi: 'よう', kunyomi: 'おど-る', meaningVi: 'nhảy múa', strokeCount: 14 },
      { character: '舞', hanViet: 'VŨ', onyomi: 'ぶ', kunyomi: 'ま-う, まい', meaningVi: 'múa', strokeCount: 15 },
      { character: '奏', hanViet: 'TẤU', onyomi: 'そう', kunyomi: 'かな-でる', meaningVi: 'diễn tấu nhạc cụ', strokeCount: 9 },
      { character: '奇', hanViet: 'KỲ', onyomi: 'き', meaningVi: 'kỳ lạ', strokeCount: 8 },
      { character: '怪', hanViet: 'QUÁI', onyomi: 'かい', kunyomi: 'あや-しい', meaningVi: 'kỳ quái, bí ẩn', strokeCount: 8 },
      { character: '幻', hanViet: 'HUYỄN', onyomi: 'げん', kunyomi: 'まぼろし', meaningVi: 'ảo ảnh, huyễn hoặc', strokeCount: 4 },
      { character: '妖', hanViet: 'YÊU', onyomi: 'よう', kunyomi: 'あや-しい', meaningVi: 'yêu quái, ma mị', strokeCount: 7 },
      { character: '神', hanViet: 'THẦN', onyomi: 'しん, じん', kunyomi: 'かみ', meaningVi: 'thần linh', strokeCount: 9 },
      { character: '仏', hanViet: 'PHẬT', onyomi: 'ぶつ', kunyomi: 'ほとけ', meaningVi: 'Phật', strokeCount: 4 },
      { character: '魂', hanViet: 'HỒN', onyomi: 'こん', kunyomi: 'たましい', meaningVi: 'linh hồn', strokeCount: 14 },
      { character: '霊', hanViet: 'LINH', onyomi: 'れい', kunyomi: 'たま', meaningVi: 'linh hồn, thiêng liêng', strokeCount: 15 },
      { character: '占', hanViet: 'CHIẾM', onyomi: 'せん', kunyomi: 'し-める, うらな-う', meaningVi: 'chiếm giữ; bói toán', strokeCount: 5 },
      { character: '呪', hanViet: 'CHÚ', onyomi: 'じゅ', kunyomi: 'のろ-う', meaningVi: 'lời nguyền, phù chú', strokeCount: 8 },
      { character: '祈', hanViet: 'KỲ', onyomi: 'き', kunyomi: 'いの-る', meaningVi: 'cầu nguyện', strokeCount: 8 },
      { character: '祝', hanViet: 'CHÚC', onyomi: 'しゅく', kunyomi: 'いわ-う', meaningVi: 'chúc mừng', strokeCount: 9 },
      { character: '儀', hanViet: 'NGHI', onyomi: 'ぎ', meaningVi: 'nghi lễ', strokeCount: 15 },
      { character: '式', hanViet: 'THỨC', onyomi: 'しき', meaningVi: 'nghi thức, công thức', strokeCount: 6 },
      { character: '典', hanViet: 'ĐIỂN', onyomi: 'てん', meaningVi: 'điển lễ, kinh điển, từ điển', strokeCount: 8 },
    ],
  },
  {
    lessonNumber: 315,
    jlptLevel: 'N3',
    title: 'Bài 45 · Kanji N3 bổ sung (6)',
    sortOrder: 3150,
    entries: [
      { character: '刻', hanViet: 'KHẮC', onyomi: 'こく', kunyomi: 'きざ-む', meaningVi: 'khắc (giờ, thời điểm)', strokeCount: 8 },
      { character: '瞬', hanViet: 'THUẤN', onyomi: 'しゅん', kunyomi: 'またた-く', meaningVi: 'chớp mắt, khoảnh khắc', strokeCount: 18 },
      { character: '永', hanViet: 'VĨNH', onyomi: 'えい', kunyomi: 'なが-い', meaningVi: 'vĩnh viễn', strokeCount: 5 },
      { character: '久', hanViet: 'CỬU', onyomi: 'きゅう, く', kunyomi: 'ひさ-しい', meaningVi: 'lâu dài', strokeCount: 3 },
      { character: '暦', hanViet: 'LỊCH', onyomi: 'れき', kunyomi: 'こよみ', meaningVi: 'lịch (ngày tháng)', strokeCount: 14 },
      { character: '暮', hanViet: 'MỘ', onyomi: 'ぼ', kunyomi: 'く-れる, く-らす', meaningVi: 'chiều tối, sinh sống', strokeCount: 14 },
      { character: '宵', hanViet: 'TIÊU', onyomi: 'しょう', kunyomi: 'よい', meaningVi: 'chập tối', strokeCount: 10 },
      { character: '翌', hanViet: 'DỰC', onyomi: 'よく', meaningVi: 'ngày/năm kế tiếp', strokeCount: 11 },
      { character: '頃', hanViet: 'KHOẢNH', onyomi: 'けい', kunyomi: 'ころ', meaningVi: 'khoảng thời gian, độ chừng', strokeCount: 11 },
      { character: '遅', hanViet: 'TRÌ', onyomi: 'ち', kunyomi: 'おく-れる, おそ-い', meaningVi: 'muộn, chậm trễ', strokeCount: 12 },
      { character: '速', hanViet: 'TỐC', onyomi: 'そく', kunyomi: 'はや-い', meaningVi: 'nhanh, tốc độ', strokeCount: 10 },
      { character: '緊', hanViet: 'KHẨN', onyomi: 'きん', meaningVi: 'khẩn cấp, căng thẳng', strokeCount: 15 },
      { character: '迅', hanViet: 'TẤN', onyomi: 'じん', meaningVi: 'nhanh chóng (迅速)', strokeCount: 6 },
      { character: '徐', hanViet: 'TỪ', onyomi: 'じょ', meaningVi: 'từ từ, chậm rãi', strokeCount: 10 },
      { character: '漸', hanViet: 'TIỆM', onyomi: 'ぜん', meaningVi: 'dần dần (漸次)', strokeCount: 14 },
      { character: '継', hanViet: 'KẾ', onyomi: 'けい', kunyomi: 'つ-ぐ', meaningVi: 'kế tục, nối tiếp', strokeCount: 13 },
    ],
  },
];
