// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 977-982.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART14: JlptVocabUnit[] = [
  {
    lessonNumber: 977,
    jlptLevel: 'N1',
    words: [
      { kanji: '水田', kana: 'すいでん', romaji: 'suiden', meaning: 'ruộng lúa nước', partOfSpeech: 'danh từ' },
      { kanji: '衰えます', kana: 'おとろえます', romaji: 'otoroemasu', meaning: 'suy yếu, suy tàn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '遂げます', kana: 'とげます', romaji: 'togemasu', meaning: 'đạt được, hoàn thành', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '崇拝', kana: 'すうはい', romaji: 'sūhai', meaning: 'sự tôn thờ, sùng bái', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '嵩みます', kana: 'かさみます', romaji: 'kasamimasu', meaning: 'tăng lên, chất đống (chi phí)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '嵩張ります', kana: 'かさばります', romaji: 'kasabarimasu', meaning: 'cồng kềnh, choán chỗ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '数詞', kana: 'すうし', romaji: 'sūshi', meaning: 'số từ', partOfSpeech: 'danh từ' },
      { kanji: '雛', kana: 'ひな', romaji: 'hina', meaning: 'chim non, gà con', partOfSpeech: 'danh từ' },
      { kanji: '据えます', kana: 'すえます', romaji: 'suemasu', meaning: 'đặt cố định, lắp đặt', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '据え付けます', kana: 'すえつけます', romaji: 'suetsukemasu', meaning: 'lắp đặt cố định', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '裾', kana: 'すそ', romaji: 'suso', meaning: 'gấu quần/váy; chân núi', partOfSpeech: 'danh từ' },
      { kanji: '世辞', kana: 'せじ', romaji: 'seji', meaning: 'lời nịnh hót', partOfSpeech: 'danh từ' },
      { kanji: '世帯', kana: 'せたい', romaji: 'setai', meaning: 'hộ gia đình', partOfSpeech: 'danh từ' },
      { kanji: '世代', kana: 'せだい', romaji: 'sedai', meaning: 'thế hệ', partOfSpeech: 'danh từ' },
      { kanji: '世論', kana: 'せろん', romaji: 'seron', meaning: 'dư luận xã hội', partOfSpeech: 'danh từ' },
      { kanji: '制します', kana: 'せいします', romaji: 'seishimasu', meaning: 'khống chế, kiểm soát', partOfSpeech: 'động từ する' },
      { kanji: '制裁', kana: 'せいさい', romaji: 'seisai', meaning: 'sự chế tài, trừng phạt', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 978,
    jlptLevel: 'N1',
    words: [
      { kanji: '制定', kana: 'せいてい', romaji: 'seitei', meaning: 'sự ban hành (luật)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '制服', kana: 'せいふく', romaji: 'seifuku', meaning: 'đồng phục', partOfSpeech: 'danh từ' },
      { kanji: '制約', kana: 'せいやく', romaji: 'seiyaku', meaning: 'sự ràng buộc, hạn chế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '勢力', kana: 'せいりょく', romaji: 'seiryoku', meaning: 'thế lực, ảnh hưởng', partOfSpeech: 'danh từ' },
      { kanji: '成り立ちます', kana: 'なりたちます', romaji: 'naritachimasu', meaning: 'được cấu thành, khả thi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '成る丈', kana: 'なるたけ', romaji: 'narutake', meaning: 'càng nhiều càng tốt, nếu có thể', partOfSpeech: 'phó từ' },
      { kanji: '成熟', kana: 'せいじゅく', romaji: 'seijuku', meaning: 'sự trưởng thành, chín muồi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '政権', kana: 'せいけん', romaji: 'seiken', meaning: 'chính quyền', partOfSpeech: 'danh từ' },
      { kanji: '整えます', kana: 'ととのえます', romaji: 'totonoemasu', meaning: 'sắp xếp, chuẩn bị sẵn sàng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '整然', kana: 'せいぜん', romaji: 'seizen', meaning: 'ngăn nắp, trật tự', partOfSpeech: 'tính từ na' },
      { kanji: '整列', kana: 'せいれつ', romaji: 'seiretsu', meaning: 'sự xếp hàng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '星座', kana: 'せいざ', romaji: 'seiza', meaning: 'chòm sao', partOfSpeech: 'danh từ' },
      { kanji: '晴天', kana: 'せいてん', romaji: 'seiten', meaning: 'trời quang, thời tiết đẹp', partOfSpeech: 'danh từ' },
      { kanji: '正しく', kana: 'まさしく', romaji: 'masashiku', meaning: 'đích thực, chắc chắn', partOfSpeech: 'phó từ' },
      { kanji: '正解', kana: 'せいかい', romaji: 'seikai', meaning: 'đáp án đúng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '正義', kana: 'せいぎ', romaji: 'seigi', meaning: 'công lý, chính nghĩa', partOfSpeech: 'danh từ' },
      { kanji: '正常', kana: 'せいじょう', romaji: 'seijō', meaning: 'bình thường', partOfSpeech: 'danh từ, tính từ na' },
    ],
  },
  {
    lessonNumber: 979,
    jlptLevel: 'N1',
    words: [
      { kanji: '清々しい', kana: 'すがすがしい', romaji: 'sugasugashii', meaning: 'sảng khoái, trong lành', partOfSpeech: 'tính từ i' },
      { kanji: '清らか', kana: 'きよらか', romaji: 'kiyoraka', meaning: 'trong sạch, thanh khiết', partOfSpeech: 'tính từ na' },
      { kanji: '清純', kana: 'せいじゅん', romaji: 'seijun', meaning: 'trong sáng, thuần khiết', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '清濁', kana: 'せいだく', romaji: 'seidaku', meaning: 'thiện ác, trong đục', partOfSpeech: 'danh từ' },
      { kanji: '生まれつき', kana: 'うまれつき', romaji: 'umaretsuki', meaning: 'bẩm sinh, từ khi sinh ra', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '生やします', kana: 'はやします', romaji: 'hayashimasu', meaning: 'để mọc (râu, tóc)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '生育', kana: 'せいいく', romaji: 'seiiku', meaning: 'sự sinh trưởng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '生温い', kana: 'なまぬるい', romaji: 'namanurui', meaning: 'âm ấm; nửa vời, không kiên quyết', partOfSpeech: 'tính từ i' },
      { kanji: '生計', kana: 'せいけい', romaji: 'seikei', meaning: 'kế sinh nhai', partOfSpeech: 'danh từ' },
      { kanji: '生死', kana: 'せいし', romaji: 'seishi', meaning: 'sống chết', partOfSpeech: 'danh từ' },
      { kanji: '生臭い', kana: 'なまぐさい', romaji: 'namagusai', meaning: 'tanh (mùi cá, máu)', partOfSpeech: 'tính từ i' },
      { kanji: '生身', kana: 'なまみ', romaji: 'namami', meaning: 'cơ thể sống, xác thịt', partOfSpeech: 'danh từ' },
      { kanji: '盛り上がります', kana: 'もりあがります', romaji: 'moriagarimasu', meaning: 'dâng trào, sôi động lên', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '盛ります', kana: 'さかります', romaji: 'sakarimasu', meaning: 'hưng thịnh, thời kỳ đỉnh cao', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '盛大', kana: 'せいだい', romaji: 'seidai', meaning: 'long trọng, hoành tráng', partOfSpeech: 'tính từ na' },
      { kanji: '精密', kana: 'せいみつ', romaji: 'seimitsu', meaning: 'chính xác, tỉ mỉ', partOfSpeech: 'tính từ na' },
      { kanji: '製鉄', kana: 'せいてつ', romaji: 'seitetsu', meaning: 'luyện sắt, sản xuất thép', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 980,
    jlptLevel: 'N1',
    words: [
      { kanji: '製法', kana: 'せいほう', romaji: 'seihō', meaning: 'phương pháp chế tạo', partOfSpeech: 'danh từ' },
      { kanji: '西日', kana: 'にしび', romaji: 'nishibi', meaning: 'nắng chiều (hướng tây)', partOfSpeech: 'danh từ' },
      { kanji: '誠', kana: 'まこと', romaji: 'makoto', meaning: 'sự chân thành, sự thật', partOfSpeech: 'danh từ' },
      { kanji: '青春', kana: 'せいしゅん', romaji: 'seishun', meaning: 'tuổi thanh xuân', partOfSpeech: 'danh từ' },
      { kanji: '静的', kana: 'せいてき', romaji: 'seiteki', meaning: 'tĩnh, tĩnh tại', partOfSpeech: 'tính từ na' },
      { kanji: '税務署', kana: 'ぜいむしょ', romaji: 'zeimusho', meaning: 'cục thuế', partOfSpeech: 'danh từ' },
      { kanji: '脆い', kana: 'もろい', romaji: 'moroi', meaning: 'giòn, dễ vỡ; yếu đuối', partOfSpeech: 'tính từ i' },
      { kanji: '惜しみます', kana: 'おしみます', romaji: 'oshimimasu', meaning: 'tiếc, quý trọng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '責務', kana: 'せきむ', romaji: 'sekimu', meaning: 'trách nhiệm, nghĩa vụ', partOfSpeech: 'danh từ' },
      { kanji: '赤らみます', kana: 'あからみます', romaji: 'akaramimasu', meaning: 'đỏ mặt, ửng đỏ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '跡継ぎ', kana: 'あとつぎ', romaji: 'atotsugi', meaning: 'người thừa kế', partOfSpeech: 'danh từ' },
      { kanji: '跡切れます', kana: 'とぎれます', romaji: 'togiremasu', meaning: 'bị ngắt quãng, gián đoạn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '切ない', kana: 'せつない', romaji: 'setsunai', meaning: 'đau lòng, quặn thắt', partOfSpeech: 'tính từ i' },
      { kanji: '切り替えます', kana: 'きりかえます', romaji: 'kirikaemasu', meaning: 'chuyển đổi, thay đổi', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '切れ目', kana: 'きれめ', romaji: 'kireme', meaning: 'chỗ ngắt, khe hở', partOfSpeech: 'danh từ' },
      { kanji: '切開', kana: 'せっかい', romaji: 'sekkai', meaning: 'sự mổ xẻ, phẫu thuật cắt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '切実', kana: 'せつじつ', romaji: 'setsujitsu', meaning: 'thiết thực, cấp bách', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 981,
    jlptLevel: 'N1',
    words: [
      { kanji: '接触', kana: 'せっしょく', romaji: 'sesshoku', meaning: 'sự tiếp xúc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '接続詞', kana: 'せつぞくし', romaji: 'setsuzokushi', meaning: 'liên từ', partOfSpeech: 'danh từ' },
      { kanji: '折り返します', kana: 'おりかえします', romaji: 'orikaeshimasu', meaning: 'gấp lại, quay đầu lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '折衷', kana: 'せっちゅう', romaji: 'secchū', meaning: 'sự dung hòa, chiết trung', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '設けます', kana: 'もうけます', romaji: 'mōkemasu', meaning: 'thiết lập, tạo ra', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '設置', kana: 'せっち', romaji: 'secchi', meaning: 'sự lắp đặt, thiết lập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '雪崩', kana: 'なだれ', romaji: 'nadare', meaning: 'trận tuyết lở', partOfSpeech: 'danh từ' },
      { kanji: '絶えます', kana: 'たえます', romaji: 'taemasu', meaning: 'chấm dứt, tuyệt chủng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '絶版', kana: 'ぜっぱん', romaji: 'zeppan', meaning: 'ngừng xuất bản, hết hàng (sách)', partOfSpeech: 'danh từ' },
      { kanji: '絶望', kana: 'ぜつぼう', romaji: 'zetsubō', meaning: 'sự tuyệt vọng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '先だって', kana: 'せんだって', romaji: 'sendatte', meaning: 'hôm trước, mới đây', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '先先週', kana: 'せんせんしゅう', romaji: 'sensenshū', meaning: 'tuần trước nữa', partOfSpeech: 'danh từ' },
      { kanji: '先着', kana: 'せんちゃく', romaji: 'senchaku', meaning: 'người/vật đến trước', partOfSpeech: 'danh từ' },
      { kanji: '先天的', kana: 'せんてんてき', romaji: 'sententeki', meaning: 'bẩm sinh, tiên thiên', partOfSpeech: 'tính từ na' },
      { kanji: '占領', kana: 'せんりょう', romaji: 'senryō', meaning: 'sự chiếm đóng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '宣教', kana: 'せんきょう', romaji: 'senkyō', meaning: 'sự truyền giáo', partOfSpeech: 'danh từ' },
      { kanji: '宣言', kana: 'せんげん', romaji: 'sengen', meaning: 'lời tuyên bố', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 982,
    jlptLevel: 'N1',
    words: [
      { kanji: '専ら', kana: 'もっぱら', romaji: 'moppara', meaning: 'chuyên tâm vào, chủ yếu là', partOfSpeech: 'phó từ' },
      { kanji: '専用', kana: 'せんよう', romaji: 'senyō', meaning: 'dùng riêng, chuyên dụng', partOfSpeech: 'danh từ' },
      { kanji: '戦災', kana: 'せんさい', romaji: 'sensai', meaning: 'thiệt hại do chiến tranh', partOfSpeech: 'danh từ' },
      { kanji: '戦力', kana: 'せんりょく', romaji: 'senryoku', meaning: 'lực lượng chiến đấu', partOfSpeech: 'danh từ' },
      { kanji: '浅ましい', kana: 'あさましい', romaji: 'asamashii', meaning: 'đáng khinh, hèn hạ', partOfSpeech: 'tính từ i' },
      { kanji: '染まります', kana: 'そまります', romaji: 'somarimasu', meaning: 'bị nhuộm màu, bị ảnh hưởng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '染みます', kana: 'しみます', romaji: 'shimimasu', meaning: 'thấm vào, ngấm vào', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '染めます', kana: 'そめます', romaji: 'somemasu', meaning: 'nhuộm màu', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '潜ります', kana: 'くぐります', romaji: 'kugurimasu', meaning: 'chui qua, lách qua', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '潜水', kana: 'せんすい', romaji: 'sensui', meaning: 'sự lặn nước', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '潜入', kana: 'せんにゅう', romaji: 'sennyū', meaning: 'sự xâm nhập, lẻn vào', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '煽てます', kana: 'おだてます', romaji: 'odatemasu', meaning: 'tâng bốc, xúi giục', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '繊維', kana: 'せんい', romaji: 'seni', meaning: 'sợi, chất xơ', partOfSpeech: 'danh từ' },
      { kanji: '船舶', kana: 'せんぱく', romaji: 'senpaku', meaning: 'tàu thuyền', partOfSpeech: 'danh từ' },
      { kanji: '選挙', kana: 'せんきょ', romaji: 'senkyo', meaning: 'cuộc bầu cử', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
];
