// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 1025-1030.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART22: JlptVocabUnit[] = [
  {
    lessonNumber: 1025,
    jlptLevel: 'N1',
    words: [
      { kanji: '無言', kana: 'むごん', romaji: 'mugon', meaning: 'im lặng không nói', partOfSpeech: 'danh từ' },
      { kanji: '無口', kana: 'むくち', romaji: 'mukuchi', meaning: 'ít nói, kiệm lời', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '無邪気', kana: 'むじゃき', romaji: 'mujaki', meaning: 'ngây thơ, hồn nhiên', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '無線', kana: 'むせん', romaji: 'musen', meaning: 'vô tuyến', partOfSpeech: 'danh từ' },
      { kanji: '無駄遣い', kana: 'むだづかい', romaji: 'mudazukai', meaning: 'sự tiêu xài hoang phí', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '無断', kana: 'むだん', romaji: 'mudan', meaning: 'không xin phép, tự tiện', partOfSpeech: 'danh từ' },
      { kanji: '無知', kana: 'むち', romaji: 'muchi', meaning: 'sự thiếu hiểu biết', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '無茶', kana: 'むちゃ', romaji: 'mucha', meaning: 'vô lý, quá đáng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '無茶苦茶', kana: 'むちゃくちゃ', romaji: 'muchakucha', meaning: 'lộn xộn, vô lý cùng cực', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '無難', kana: 'ぶなん', romaji: 'bunan', meaning: 'an toàn, không có gì đáng chê', partOfSpeech: 'tính từ na' },
      { kanji: '無念', kana: 'むねん', romaji: 'munen', meaning: 'sự tiếc nuối, hối hận', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '無能', kana: 'むのう', romaji: 'munō', meaning: 'bất tài, vô năng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '無用', kana: 'むよう', romaji: 'muyō', meaning: 'vô dụng, không cần thiết', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '無礼', kana: 'ぶれい', romaji: 'burei', meaning: 'vô lễ, thô lỗ', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '無論', kana: 'むろん', romaji: 'muron', meaning: 'dĩ nhiên, đương nhiên', partOfSpeech: 'phó từ' },
      { kanji: '婿', kana: 'むこ', romaji: 'muko', meaning: 'con rể', partOfSpeech: 'danh từ' },
      { kanji: '名高い', kana: 'なだかい', romaji: 'nadakai', meaning: 'nổi danh, lừng lẫy', partOfSpeech: 'tính từ i' },
    ],
  },
  {
    lessonNumber: 1026,
    jlptLevel: 'N1',
    words: [
      { kanji: '名札', kana: 'なふだ', romaji: 'nafuda', meaning: 'thẻ tên', partOfSpeech: 'danh từ' },
      { kanji: '名産', kana: 'めいさん', romaji: 'meisan', meaning: 'đặc sản nổi tiếng', partOfSpeech: 'danh từ' },
      { kanji: '名称', kana: 'めいしょう', romaji: 'meishō', meaning: 'tên gọi chính thức', partOfSpeech: 'danh từ' },
      { kanji: '名付けます', kana: 'なづけます', romaji: 'nazukemasu', meaning: 'đặt tên cho', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '名簿', kana: 'めいぼ', romaji: 'meibo', meaning: 'danh sách tên', partOfSpeech: 'danh từ' },
      { kanji: '名誉', kana: 'めいよ', romaji: 'meiyo', meaning: 'danh dự', partOfSpeech: 'danh từ' },
      { kanji: '命中', kana: 'めいちゅう', romaji: 'meichū', meaning: 'sự bắn trúng đích', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '明かします', kana: 'あかします', romaji: 'akashimasu', meaning: 'tiết lộ, thức trắng (đêm)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '明くる', kana: 'あくる', romaji: 'akuru', meaning: 'kế tiếp, sau đó', partOfSpeech: 'từ hạn định' },
      { kana: 'あからさま', romaji: 'akarasama', meaning: 'trắng trợn, lộ liễu', partOfSpeech: 'tính từ na' },
      { kanji: '明朗', kana: 'めいろう', romaji: 'meirō', meaning: 'sáng sủa, vui vẻ', partOfSpeech: 'tính từ na' },
      { kanji: '滅びます', kana: 'ほろびます', romaji: 'horobimasu', meaning: 'diệt vong, sụp đổ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '滅ぼします', kana: 'ほろぼします', romaji: 'horoboshimasu', meaning: 'tiêu diệt, hủy diệt', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '免れます', kana: 'まぬかれます', romaji: 'manukaremasu', meaning: 'thoát khỏi, tránh được', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '免除', kana: 'めんじょ', romaji: 'menjo', meaning: 'sự miễn trừ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '面', kana: 'おも', romaji: 'omo', meaning: 'khuôn mặt (cách nói cổ)', partOfSpeech: 'danh từ' },
      { kanji: '面します', kana: 'めんします', romaji: 'menshimasu', meaning: 'đối diện, hướng ra', partOfSpeech: 'động từ する' },
    ],
  },
  {
    lessonNumber: 1027,
    jlptLevel: 'N1',
    words: [
      { kanji: '面会', kana: 'めんかい', romaji: 'menkai', meaning: 'cuộc gặp mặt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '面目', kana: 'めんぼく', romaji: 'menboku', meaning: 'thể diện, danh dự', partOfSpeech: 'danh từ' },
      { kanji: '面皰', kana: 'にきび', romaji: 'nikibi', meaning: 'mụn trứng cá', partOfSpeech: 'danh từ' },
      { kanji: '模型', kana: 'もけい', romaji: 'mokei', meaning: 'mô hình', partOfSpeech: 'danh từ' },
      { kanji: '模範', kana: 'もはん', romaji: 'mohan', meaning: 'hình mẫu, khuôn mẫu', partOfSpeech: 'danh từ' },
      { kanji: '猛烈', kana: 'もうれつ', romaji: 'mōretsu', meaning: 'dữ dội, mãnh liệt', partOfSpeech: 'tính từ na' },
      { kanji: '盲点', kana: 'もうてん', romaji: 'mōten', meaning: 'điểm mù, sơ hở', partOfSpeech: 'danh từ' },
      { kanji: '網', kana: 'あみ', romaji: 'ami', meaning: 'lưới, mạng lưới', partOfSpeech: 'danh từ' },
      { kanji: '木綿', kana: 'きわた', romaji: 'kiwata', meaning: 'cây bông, cây gạo', partOfSpeech: 'danh từ' },
      { kanji: '目覚しい', kana: 'めざましい', romaji: 'mezamashii', meaning: 'đáng kinh ngạc, nổi bật', partOfSpeech: 'tính từ i' },
      { kanji: '目覚めます', kana: 'めざめます', romaji: 'mezamemasu', meaning: 'thức giấc, tỉnh ngộ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '目盛', kana: 'めもり', romaji: 'memori', meaning: 'vạch chia độ', partOfSpeech: 'danh từ' },
      { kanji: '目付き', kana: 'めつき', romaji: 'metsuki', meaning: 'ánh mắt, cái nhìn', partOfSpeech: 'danh từ' },
      { kanji: '目方', kana: 'めかた', romaji: 'mekata', meaning: 'trọng lượng', partOfSpeech: 'danh từ' },
      { kanji: '目録', kana: 'もくろく', romaji: 'mokuroku', meaning: 'danh mục, mục lục', partOfSpeech: 'danh từ' },
      { kanji: '目論見', kana: 'もくろみ', romaji: 'mokuromi', meaning: 'âm mưu, kế hoạch ngầm', partOfSpeech: 'danh từ' },
      { kanji: '問い合わせます', kana: 'といあわせます', romaji: 'toiawasemasu', meaning: 'hỏi thăm, thắc mắc', partOfSpeech: 'động từ nhóm 2' },
    ],
  },
  {
    lessonNumber: 1028,
    jlptLevel: 'N1',
    words: [
      { kanji: '問屋', kana: 'といや', romaji: 'toiya', meaning: 'cửa hàng bán buôn', partOfSpeech: 'danh từ' },
      { kanji: '夜具', kana: 'やぐ', romaji: 'yagu', meaning: 'chăn đệm, đồ ngủ', partOfSpeech: 'danh từ' },
      { kanji: '夜更かし', kana: 'よふかし', romaji: 'yofukashi', meaning: 'sự thức khuya', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '夜更け', kana: 'よふけ', romaji: 'yofuke', meaning: 'đêm khuya', partOfSpeech: 'danh từ' },
      { kanji: '夜行', kana: 'やぎょう', romaji: 'yagyō', meaning: 'đi đêm, tàu đêm', partOfSpeech: 'danh từ' },
      { kanji: '夜中', kana: 'やちゅう', romaji: 'yachū', meaning: 'suốt đêm', partOfSpeech: 'danh từ' },
      { kanji: '野外', kana: 'やがい', romaji: 'yagai', meaning: 'ngoài trời', partOfSpeech: 'danh từ' },
      { kanji: '野心', kana: 'やしん', romaji: 'yashin', meaning: 'tham vọng', partOfSpeech: 'danh từ' },
      { kanji: '野生', kana: 'やせい', romaji: 'yasei', meaning: 'hoang dã', partOfSpeech: 'danh từ' },
      { kanji: '役場', kana: 'やくば', romaji: 'yakuba', meaning: 'ủy ban xã/phường', partOfSpeech: 'danh từ' },
      { kanji: '役職', kana: 'やくしょく', romaji: 'yakushoku', meaning: 'chức vụ quản lý', partOfSpeech: 'danh từ' },
      { kanji: '役立ちます', kana: 'やくだちます', romaji: 'yakudachimasu', meaning: 'hữu ích, có ích', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '油絵', kana: 'あぶらえ', romaji: 'aburae', meaning: 'tranh sơn dầu', partOfSpeech: 'danh từ' },
      { kanji: '優', kana: 'やさ', romaji: 'yasa', meaning: 'dịu dàng, nhân hậu', partOfSpeech: 'danh từ' },
      { kanji: '優位', kana: 'ゆうい', romaji: 'yūi', meaning: 'vị thế ưu thế', partOfSpeech: 'danh từ' },
      { kanji: '優越', kana: 'ゆうえつ', romaji: 'yūetsu', meaning: 'sự vượt trội', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '優勢', kana: 'ゆうせい', romaji: 'yūsei', meaning: 'ưu thế, chiếm ưu thế', partOfSpeech: 'danh từ, tính từ na' },
    ],
  },
  {
    lessonNumber: 1029,
    jlptLevel: 'N1',
    words: [
      { kanji: '優美', kana: 'ゆうび', romaji: 'yūbi', meaning: 'thanh tao, tao nhã', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '勇敢', kana: 'ゆうかん', romaji: 'yūkan', meaning: 'dũng cảm', partOfSpeech: 'tính từ na' },
      { kanji: '幽霊', kana: 'ゆうれい', romaji: 'yūrei', meaning: 'hồn ma, bóng ma', partOfSpeech: 'danh từ' },
      { kanji: '有します', kana: 'ゆうします', romaji: 'yūshimasu', meaning: 'sở hữu, có (trang trọng)', partOfSpeech: 'động từ する' },
      { kanji: '有りのまま', kana: 'ありのまま', romaji: 'arinomama', meaning: 'đúng như thực tế, thẳng thắn', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '有益', kana: 'ゆうえき', romaji: 'yūeki', meaning: 'hữu ích, có lợi', partOfSpeech: 'tính từ na' },
      { kanji: '有望', kana: 'ゆうぼう', romaji: 'yūbō', meaning: 'đầy triển vọng', partOfSpeech: 'tính từ na' },
      { kanji: '有様', kana: 'ありさま', romaji: 'arisama', meaning: 'tình trạng, thực trạng', partOfSpeech: 'danh từ' },
      { kanji: '有力', kana: 'ゆうりょく', romaji: 'yūryoku', meaning: 'có thế lực, mạnh mẽ', partOfSpeech: 'tính từ na' },
      { kanji: '誘導', kana: 'ゆうどう', romaji: 'yūdō', meaning: 'sự dẫn dắt, hướng dẫn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '誘惑', kana: 'ゆうわく', romaji: 'yūwaku', meaning: 'sự cám dỗ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '遊牧', kana: 'ゆうぼく', romaji: 'yūboku', meaning: 'du mục', partOfSpeech: 'danh từ' },
      { kanji: '夕焼け', kana: 'ゆうやけ', romaji: 'yūyake', meaning: 'ráng chiều', partOfSpeech: 'danh từ' },
      { kanji: '夕暮れ', kana: 'ゆうぐれ', romaji: 'yūgure', meaning: 'hoàng hôn', partOfSpeech: 'danh từ' },
      { kanji: '予め', kana: 'あらかじめ', romaji: 'arakajime', meaning: 'trước, sẵn từ trước', partOfSpeech: 'phó từ' },
      { kanji: '予感', kana: 'よかん', romaji: 'yokan', meaning: 'linh cảm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '余暇', kana: 'よか', romaji: 'yoka', meaning: 'thời gian rảnh rỗi', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 1030,
    jlptLevel: 'N1',
    words: [
      { kanji: '余興', kana: 'よきょう', romaji: 'yokyō', meaning: 'tiết mục giải trí phụ', partOfSpeech: 'danh từ' },
      { kanji: '余所見', kana: 'よそみ', romaji: 'yosomi', meaning: 'nhìn đi chỗ khác', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '余地', kana: 'よち', romaji: 'yochi', meaning: 'khoảng trống, dư địa', partOfSpeech: 'danh từ' },
      { kanji: '余程', kana: 'よっぽど', romaji: 'yoppodo', meaning: 'rất, khá nhiều', partOfSpeech: 'phó từ' },
      { kanji: '与党', kana: 'よとう', romaji: 'yotō', meaning: 'đảng cầm quyền', partOfSpeech: 'danh từ' },
      { kanji: '預金', kana: 'よきん', romaji: 'yokin', meaning: 'tiền gửi ngân hàng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '容易い', kana: 'たやすい', romaji: 'tayasui', meaning: 'dễ dàng, đơn giản', partOfSpeech: 'tính từ i' },
      { kanji: '揺さぶります', kana: 'ゆさぶります', romaji: 'yusaburimasu', meaning: 'lay động, làm rung chuyển', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '揺らぎます', kana: 'ゆらぎます', romaji: 'yuragimasu', meaning: 'dao động, lung lay', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '様', kana: 'さま', romaji: 'sama', meaning: 'hậu tố kính ngữ; hình dáng, vẻ', partOfSpeech: 'hậu tố' },
      { kanji: '様相', kana: 'ようそう', romaji: 'yōsō', meaning: 'diện mạo, khía cạnh', partOfSpeech: 'danh từ' },
      { kanji: '洋風', kana: 'ようふう', romaji: 'yōfū', meaning: 'kiểu Tây phương', partOfSpeech: 'danh từ, tính từ na' },
    ],
  },
];
