// Bổ sung từ vựng N2 đợt 5 — dịch tay từ phần còn lại chưa dùng của nguồn OpenJLPT,
// đối chiếu loại trùng theo 3 lớp: kana chính xác, gốc kanji (bắt các cặp thể từ điển/
// thể ます của cùng một từ), và suy đoán thể ます cho động từ dạng từ điển — tránh lặp
// lại các từ đã có trong DB dưới dạng chia khác. lessonNumber 754-772.
import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST5_N2: JlptVocabUnit[] = [
  {
    lessonNumber: 754,
    jlptLevel: 'N2',
    words: [
      { kana: 'アイデア', romaji: 'aidea', meaning: 'ý tưởng', partOfSpeech: 'danh từ' },
      { kana: 'あげる', romaji: 'ageru', meaning: 'cho, tặng (thân mật)', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'インキ', romaji: 'inki', meaning: 'mực (viết, in)', partOfSpeech: 'danh từ' },
      { kana: 'ウーマン', romaji: 'uuman', meaning: 'phụ nữ', partOfSpeech: 'danh từ' },
      { kana: 'ウエートレス', romaji: 'ueetoresu', meaning: 'nữ phục vụ bàn', partOfSpeech: 'danh từ' },
      { kana: 'おはよう', romaji: 'ohayou', meaning: 'chào buổi sáng', partOfSpeech: 'thán từ' },
      { kana: 'おやすみ', romaji: 'oyasumi', meaning: 'chúc ngủ ngon; ngày nghỉ', partOfSpeech: 'thán từ, danh từ' },
      { kana: 'けれど', romaji: 'keredo', meaning: 'nhưng, tuy nhiên', partOfSpeech: 'liên từ' },
      { kana: 'タイヤ', romaji: 'taiya', meaning: 'lốp xe', partOfSpeech: 'danh từ' },
      { kana: 'やっぱり', romaji: 'yappari', meaning: 'quả nhiên, vẫn như dự đoán', partOfSpeech: 'phó từ' },
      { kana: 'ランチ', romaji: 'ranchi', meaning: 'bữa trưa', partOfSpeech: 'danh từ' },
      { kana: 'レクリエーション', romaji: 'rekurieeshon', meaning: 'giải trí, hoạt động thư giãn', partOfSpeech: 'danh từ' },
      { kanji: '刷る', kana: 'する', romaji: 'suru', meaning: 'in (ấn)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '小便', kana: 'しょうべん', romaji: 'shouben', meaning: 'nước tiểu, đi tiểu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '水曜', kana: 'すいよう', romaji: 'suiyou', meaning: 'thứ Tư', partOfSpeech: 'danh từ' },
      { kanji: '太鼓', kana: 'たいこ', romaji: 'taiko', meaning: 'trống', partOfSpeech: 'danh từ' },
      { kanji: '楕円', kana: 'だえん', romaji: 'daen', meaning: 'hình elip', partOfSpeech: 'danh từ' },
      { kanji: '体積', kana: 'たいせき', romaji: 'taiseki', meaning: 'thể tích', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 755,
    jlptLevel: 'N2',
    words: [
      { kanji: '体操', kana: 'たいそう', romaji: 'taisou', meaning: 'thể dục', partOfSpeech: 'danh từ' },
      { kanji: '待合室', kana: 'まちあいしつ', romaji: 'machiaishitsu', meaning: 'phòng chờ', partOfSpeech: 'danh từ' },
      { kanji: '貸家', kana: 'かしや', romaji: 'kashiya', meaning: 'nhà cho thuê', partOfSpeech: 'danh từ' },
      { kanji: '貸間', kana: 'かしま', romaji: 'kashima', meaning: 'phòng cho thuê', partOfSpeech: 'danh từ' },
      { kanji: '代名詞', kana: 'だいめいし', romaji: 'daimeishi', meaning: 'đại từ', partOfSpeech: 'danh từ' },
      { kanji: '大工', kana: 'だいく', romaji: 'daiku', meaning: 'thợ mộc', partOfSpeech: 'danh từ' },
      { kanji: '大小', kana: 'だいしょう', romaji: 'daishou', meaning: 'lớn nhỏ, kích cỡ', partOfSpeech: 'danh từ' },
      { kanji: '大通り', kana: 'おおどおり', romaji: 'oodoori', meaning: 'đại lộ', partOfSpeech: 'danh từ' },
      { kanji: '大凡', kana: 'おおよそ', romaji: 'ooyoso', meaning: 'khoảng chừng, đại khái', partOfSpeech: 'phó từ' },
      { kanji: '大木', kana: 'たいぼく', romaji: 'taiboku', meaning: 'cây to', partOfSpeech: 'danh từ' },
      { kanji: '題名', kana: 'だいめい', romaji: 'daimei', meaning: 'tựa đề', partOfSpeech: 'danh từ' },
      { kanji: '滝', kana: 'たき', romaji: 'taki', meaning: 'thác nước', partOfSpeech: 'danh từ' },
      { kanji: '単数', kana: 'たんすう', romaji: 'tansuu', meaning: 'số ít', partOfSpeech: 'danh từ' },
      { kanji: '淡水', kana: 'たんすい', romaji: 'tansui', meaning: 'nước ngọt', partOfSpeech: 'danh từ' },
      { kanji: '炭鉱', kana: 'たんこう', romaji: 'tankou', meaning: 'mỏ than', partOfSpeech: 'danh từ' },
      { kanji: '短編', kana: 'たんぺん', romaji: 'tanpen', meaning: 'truyện/phim ngắn', partOfSpeech: 'danh từ' },
      { kanji: '団地', kana: 'だんち', romaji: 'danchi', meaning: 'khu chung cư', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 756,
    jlptLevel: 'N2',
    words: [
      { kanji: '断水', kana: 'だんすい', romaji: 'dansui', meaning: 'cúp nước', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '断定', kana: 'だんてい', romaji: 'dantei', meaning: 'kết luận, khẳng định', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '知人', kana: 'ちじん', romaji: 'chijin', meaning: 'người quen', partOfSpeech: 'danh từ' },
      { kanji: '地下水', kana: 'ちかすい', romaji: 'chikasui', meaning: 'nước ngầm', partOfSpeech: 'danh từ' },
      { kanji: '地質', kana: 'ちしつ', romaji: 'chishitsu', meaning: 'địa chất', partOfSpeech: 'danh từ' },
      { kanji: '地帯', kana: 'ちたい', romaji: 'chitai', meaning: 'khu vực, vùng', partOfSpeech: 'danh từ' },
      { kanji: '地点', kana: 'ちてん', romaji: 'chiten', meaning: 'địa điểm', partOfSpeech: 'danh từ' },
      { kanji: '地盤', kana: 'じばん', romaji: 'jiban', meaning: 'nền đất', partOfSpeech: 'danh từ' },
      { kanji: '地味', kana: 'じみ', romaji: 'jimi', meaning: 'giản dị, đơn giản', partOfSpeech: 'tính từ na' },
      { kanji: '地名', kana: 'ちめい', romaji: 'chimei', meaning: 'tên địa danh', partOfSpeech: 'danh từ' },
      { kanji: '蓄える', kana: 'たくわえる', romaji: 'takuwaeru', meaning: 'tích trữ, để dành', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '着々', kana: 'ちゃくちゃく', romaji: 'chakuchaku', meaning: 'đều đặn, từng bước vững chắc', partOfSpeech: 'phó từ' },
      { kanji: '着替え', kana: 'きがえ', romaji: 'kigae', meaning: 'thay quần áo, đồ thay', partOfSpeech: 'danh từ' },
      { kanji: '中間', kana: 'ちゅうかん', romaji: 'chuukan', meaning: 'khoảng giữa, trung gian', partOfSpeech: 'danh từ' },
      { kanji: '中指', kana: 'なかゆび', romaji: 'nakayubi', meaning: 'ngón tay giữa', partOfSpeech: 'danh từ' },
      { kanji: '中旬', kana: 'ちゅうじゅん', romaji: 'chuujun', meaning: 'trung tuần (tháng)', partOfSpeech: 'danh từ' },
      { kanji: '中世', kana: 'ちゅうせい', romaji: 'chuusei', meaning: 'thời trung cổ', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 757,
    jlptLevel: 'N2',
    words: [
      { kanji: '中途', kana: 'ちゅうと', romaji: 'chuuto', meaning: 'giữa chừng', partOfSpeech: 'danh từ' },
      { kanji: '中年', kana: 'ちゅうねん', romaji: 'chuunen', meaning: 'trung niên', partOfSpeech: 'danh từ' },
      { kanji: '仲直り', kana: 'なかなおり', romaji: 'nakanaori', meaning: 'làm hòa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '仲良し', kana: 'なかよし', romaji: 'nakayoshi', meaning: 'bạn thân', partOfSpeech: 'danh từ' },
      { kanji: '昼寝', kana: 'ひるね', romaji: 'hirune', meaning: 'ngủ trưa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '貯蔵', kana: 'ちょぞう', romaji: 'chozou', meaning: 'lưu trữ, bảo quản', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '超過', kana: 'ちょうか', romaji: 'chouka', meaning: 'vượt quá', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '跳ねる', kana: 'はねる', romaji: 'haneru', meaning: 'nhảy lên, bắn tóe', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '長引く', kana: 'ながびく', romaji: 'nagabiku', meaning: 'kéo dài, dây dưa', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '長女', kana: 'ちょうじょ', romaji: 'choujo', meaning: 'con gái cả', partOfSpeech: 'danh từ' },
      { kanji: '長短', kana: 'ちょうたん', romaji: 'choutan', meaning: 'dài ngắn, ưu khuyết điểm', partOfSpeech: 'danh từ' },
      { kanji: '長方形', kana: 'ちょうほうけい', romaji: 'chouhoukei', meaning: 'hình chữ nhật', partOfSpeech: 'danh từ' },
      { kanji: '直角', kana: 'ちょっかく', romaji: 'chokkaku', meaning: 'góc vuông', partOfSpeech: 'danh từ' },
      { kanji: '直径', kana: 'ちょっけい', romaji: 'chokkei', meaning: 'đường kính', partOfSpeech: 'danh từ' },
      { kanji: '直線', kana: 'ちょくせん', romaji: 'chokusen', meaning: 'đường thẳng', partOfSpeech: 'danh từ' },
      { kanji: '直通', kana: 'ちょくつう', romaji: 'chokutsuu', meaning: 'thông suốt, trực tiếp (tàu, điện thoại)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '直流', kana: 'ちょくりゅう', romaji: 'chokuryuu', meaning: 'dòng điện một chiều', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 758,
    jlptLevel: 'N2',
    words: [
      { kanji: '追加', kana: 'ついか', romaji: 'tsuika', meaning: 'bổ sung, thêm vào', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '通帳', kana: 'つうちょう', romaji: 'tsuuchou', meaning: 'sổ ngân hàng', partOfSpeech: 'danh từ' },
      { kanji: '通訳', kana: 'つうやく', romaji: 'tsuuyaku', meaning: 'phiên dịch (nói)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '通用', kana: 'つうよう', romaji: 'tsuuyou', meaning: 'thông dụng, được chấp nhận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '通路', kana: 'つうろ', romaji: 'tsuuro', meaning: 'lối đi', partOfSpeech: 'danh từ' },
      { kanji: '潰す', kana: 'つぶす', romaji: 'tsubusu', meaning: 'làm bẹp, phá sản', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '潰れる', kana: 'つぶれる', romaji: 'tsubureru', meaning: 'bị bẹp, bị phá sản', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '停止', kana: 'ていし', romaji: 'teishi', meaning: 'dừng lại, đình chỉ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '停電', kana: 'ていでん', romaji: 'teiden', meaning: 'mất điện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '剃る', kana: 'そる', romaji: 'soru', meaning: 'cạo (râu, tóc)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '剃刀', kana: 'かみそり', romaji: 'kamisori', meaning: 'dao cạo', partOfSpeech: 'danh từ' },
      { kanji: '定員', kana: 'ていいん', romaji: 'teiin', meaning: 'sức chứa quy định', partOfSpeech: 'danh từ' },
      { kanji: '定期券', kana: 'ていきけん', romaji: 'teikiken', meaning: 'vé tháng', partOfSpeech: 'danh từ' },
      { kanji: '定規', kana: 'じょうぎ', romaji: 'jougi', meaning: 'thước kẻ', partOfSpeech: 'danh từ' },
      { kanji: '定休日', kana: 'ていきゅうび', romaji: 'teikyuubi', meaning: 'ngày nghỉ định kỳ', partOfSpeech: 'danh từ' },
      { kanji: '釘', kana: 'くぎ', romaji: 'kugi', meaning: 'cái đinh', partOfSpeech: 'danh từ' },
      { kanji: '的確', kana: 'てきかく', romaji: 'tekikaku', meaning: 'chính xác, đúng đắn', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 759,
    jlptLevel: 'N2',
    words: [
      { kanji: '鉄橋', kana: 'てっきょう', romaji: 'tekkyou', meaning: 'cầu sắt', partOfSpeech: 'danh từ' },
      { kanji: '鉄砲', kana: 'てっぽう', romaji: 'teppou', meaning: 'súng', partOfSpeech: 'danh từ' },
      { kanji: '天皇', kana: 'てんのう', romaji: 'tennou', meaning: 'Nhật hoàng', partOfSpeech: 'danh từ' },
      { kanji: '店屋', kana: 'みせや', romaji: 'miseya', meaning: 'cửa hàng', partOfSpeech: 'danh từ' },
      { kanji: '点数', kana: 'てんすう', romaji: 'tensuu', meaning: 'điểm số', partOfSpeech: 'danh từ' },
      { kanji: '田んぼ', kana: 'たんぼ', romaji: 'tanbo', meaning: 'ruộng lúa', partOfSpeech: 'danh từ' },
      { kanji: '田植え', kana: 'たうえ', romaji: 'taue', meaning: 'cấy lúa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '電球', kana: 'でんきゅう', romaji: 'denkyuu', meaning: 'bóng đèn', partOfSpeech: 'danh từ' },
      { kanji: '電柱', kana: 'でんちゅう', romaji: 'denchuu', meaning: 'cột điện', partOfSpeech: 'danh từ' },
      { kanji: '電波', kana: 'でんぱ', romaji: 'denpa', meaning: 'sóng điện từ', partOfSpeech: 'danh từ' },
      { kanji: '電流', kana: 'でんりゅう', romaji: 'denryuu', meaning: 'dòng điện', partOfSpeech: 'danh từ' },
      { kanji: '電力', kana: 'でんりょく', romaji: 'denryoku', meaning: 'điện lực', partOfSpeech: 'danh từ' },
      { kanji: '登場', kana: 'とうじょう', romaji: 'toujou', meaning: 'xuất hiện (trên sân khấu)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '都心', kana: 'としん', romaji: 'toshin', meaning: 'trung tâm thành phố', partOfSpeech: 'danh từ' },
      { kanji: '投書', kana: 'とうしょ', romaji: 'tousho', meaning: 'thư gửi tòa soạn, thư góp ý', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '東西', kana: 'とうざい', romaji: 'touzai', meaning: 'đông và tây', partOfSpeech: 'danh từ' },
      { kanji: '東洋', kana: 'とうよう', romaji: 'touyou', meaning: 'phương Đông', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 760,
    jlptLevel: 'N2',
    words: [
      { kanji: '盗難', kana: 'とうなん', romaji: 'tounan', meaning: 'nạn trộm cắp', partOfSpeech: 'danh từ' },
      { kanji: '湯飲み', kana: 'ゆのみ', romaji: 'yunomi', meaning: 'chén uống trà', partOfSpeech: 'danh từ' },
      { kanji: '湯気', kana: 'ゆげ', romaji: 'yuge', meaning: 'hơi nước', partOfSpeech: 'danh từ' },
      { kanji: '灯台', kana: 'とうだい', romaji: 'toudai', meaning: 'hải đăng', partOfSpeech: 'danh từ' },
      { kanji: '灯油', kana: 'とうゆ', romaji: 'touyu', meaning: 'dầu hỏa', partOfSpeech: 'danh từ' },
      { kanji: '当日', kana: 'とうじつ', romaji: 'toujitsu', meaning: 'ngày đó, ngày quy định', partOfSpeech: 'danh từ' },
      { kanji: '当番', kana: 'とうばん', romaji: 'touban', meaning: 'phiên trực', partOfSpeech: 'danh từ' },
      { kanji: '等分', kana: 'とうぶん', romaji: 'toubun', meaning: 'chia đều', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '統一', kana: 'とういつ', romaji: 'touitsu', meaning: 'thống nhất', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '踏切', kana: 'ふみきり', romaji: 'fumikiri', meaning: 'đường ngang xe lửa', partOfSpeech: 'danh từ' },
      { kanji: '透き通る', kana: 'すきとおる', romaji: 'sukitooru', meaning: 'trong suốt', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '透明', kana: 'とうめい', romaji: 'toumei', meaning: 'trong suốt', partOfSpeech: 'tính từ na' },
      { kanji: '頭脳', kana: 'ずのう', romaji: 'zunou', meaning: 'đầu óc, trí não', partOfSpeech: 'danh từ' },
      { kanji: '動作', kana: 'どうさ', romaji: 'dousa', meaning: 'động tác, hành động', partOfSpeech: 'danh từ' },
      { kanji: '同格', kana: 'どうかく', romaji: 'doukaku', meaning: 'cùng cấp bậc, đồng cách (ngữ pháp)', partOfSpeech: 'danh từ' },
      { kanji: '瞳', kana: 'ひとみ', romaji: 'hitomi', meaning: 'con ngươi (mắt)', partOfSpeech: 'danh từ' },
      { kanji: '童話', kana: 'どうわ', romaji: 'douwa', meaning: 'truyện cổ tích', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 761,
    jlptLevel: 'N2',
    words: [
      { kanji: '道順', kana: 'みちじゅん', romaji: 'michijun', meaning: 'lộ trình', partOfSpeech: 'danh từ' },
      { kanji: '峠', kana: 'とうげ', romaji: 'touge', meaning: 'đèo, đỉnh dốc', partOfSpeech: 'danh từ' },
      { kanji: '特定', kana: 'とくてい', romaji: 'tokutei', meaning: 'đặc định, cụ thể', partOfSpeech: 'danh từ, động từ する, tính từ na' },
      { kanji: '特売', kana: 'とくばい', romaji: 'tokubai', meaning: 'bán đặc biệt, giảm giá', partOfSpeech: 'danh từ' },
      { kanji: '独り言', kana: 'ひとりごと', romaji: 'hitorigoto', meaning: 'nói một mình, độc thoại', partOfSpeech: 'danh từ' },
      { kanji: '凸凹', kana: 'でこぼこ', romaji: 'dekoboko', meaning: 'gồ ghề, lồi lõm', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '呑気', kana: 'のんき', romaji: 'nonki', meaning: 'vô tư, thảnh thơi', partOfSpeech: 'tính từ na' },
      { kanji: '内科', kana: 'ないか', romaji: 'naika', meaning: 'khoa nội', partOfSpeech: 'danh từ' },
      { kanji: '内線', kana: 'ないせん', romaji: 'naisen', meaning: 'số nội bộ, đường dây trong nhà', partOfSpeech: 'danh từ' },
      { kana: 'なぞなぞ', romaji: 'nazonazo', meaning: 'câu đố', partOfSpeech: 'danh từ' },
      { kanji: '南極', kana: 'なんきょく', romaji: 'nankyoku', meaning: 'Nam Cực', partOfSpeech: 'danh từ' },
      { kanji: '南米', kana: 'なんべい', romaji: 'nanbei', meaning: 'Nam Mỹ', partOfSpeech: 'danh từ' },
      { kanji: '南北', kana: 'なんぼく', romaji: 'nanboku', meaning: 'nam bắc', partOfSpeech: 'danh từ' },
      { kanji: '匂う', kana: 'におう', romaji: 'niou', meaning: 'tỏa mùi, có mùi thơm', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '日陰', kana: 'ひかげ', romaji: 'hikage', meaning: 'bóng râm', partOfSpeech: 'danh từ' },
      { kanji: '日課', kana: 'にっか', romaji: 'nikka', meaning: 'thói quen hàng ngày', partOfSpeech: 'danh từ' },
      { kanji: '日帰り', kana: 'ひがえり', romaji: 'higaeri', meaning: 'đi về trong ngày', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 762,
    jlptLevel: 'N2',
    words: [
      { kanji: '日時', kana: 'にちじ', romaji: 'nichiji', meaning: 'ngày giờ', partOfSpeech: 'danh từ' },
      { kanji: '日程', kana: 'にってい', romaji: 'nittei', meaning: 'lịch trình', partOfSpeech: 'danh từ' },
      { kanji: '日用品', kana: 'にちようひん', romaji: 'nichiyouhin', meaning: 'đồ dùng hàng ngày', partOfSpeech: 'danh từ' },
      { kanji: '入社', kana: 'にゅうしゃ', romaji: 'nyuusha', meaning: 'vào làm ở công ty', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '年度', kana: 'ねんど', romaji: 'nendo', meaning: 'niên độ, năm tài chính', partOfSpeech: 'danh từ' },
      { kanji: '濃度', kana: 'のうど', romaji: 'noudo', meaning: 'nồng độ', partOfSpeech: 'danh từ' },
      { kanji: '能率', kana: 'のうりつ', romaji: 'nouritsu', meaning: 'hiệu suất', partOfSpeech: 'danh từ' },
      { kanji: '農産物', kana: 'のうさんぶつ', romaji: 'nousanbutsu', meaning: 'nông sản', partOfSpeech: 'danh từ' },
      { kanji: '農村', kana: 'のうそん', romaji: 'nouson', meaning: 'làng quê, vùng nông thôn', partOfSpeech: 'danh từ' },
      { kanji: '農薬', kana: 'のうやく', romaji: 'nouyaku', meaning: 'thuốc trừ sâu, nông dược', partOfSpeech: 'danh từ' },
      { kanji: '派手', kana: 'はで', romaji: 'hade', meaning: 'sặc sỡ, phô trương', partOfSpeech: 'tính từ na' },
      { kanji: '破片', kana: 'はへん', romaji: 'hahen', meaning: 'mảnh vỡ', partOfSpeech: 'danh từ' },
      { kanji: '俳句', kana: 'はいく', romaji: 'haiku', meaning: 'thơ haiku', partOfSpeech: 'danh từ' },
      { kanji: '拝む', kana: 'おがむ', romaji: 'ogamu', meaning: 'vái lạy, cầu khấn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '背負う', kana: 'せおう', romaji: 'seou', meaning: 'cõng, gánh vác', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '配る', kana: 'くばる', romaji: 'kubaru', meaning: 'phân phát', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '売店', kana: 'ばいてん', romaji: 'baiten', meaning: 'quầy bán hàng', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 763,
    jlptLevel: 'N2',
    words: [
      { kanji: '売買', kana: 'ばいばい', romaji: 'baibai', meaning: 'mua bán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '這う', kana: 'はう', romaji: 'hau', meaning: 'bò, trườn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '秤', kana: 'はかり', romaji: 'hakari', meaning: 'cái cân', partOfSpeech: 'danh từ' },
      { kanji: '白髪', kana: 'しらが', romaji: 'shiraga', meaning: 'tóc bạc', partOfSpeech: 'danh từ' },
      { kanji: '薄暗い', kana: 'うすぐらい', romaji: 'usugurai', meaning: 'hơi tối, mờ mờ', partOfSpeech: 'tính từ i' },
      { kanji: '迫る', kana: 'せまる', romaji: 'semaru', meaning: 'đến gần, thúc ép', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '縛る', kana: 'しばる', romaji: 'shibaru', meaning: 'trói, buộc', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '肌着', kana: 'はだぎ', romaji: 'hadagi', meaning: 'áo lót', partOfSpeech: 'danh từ' },
      { kanji: '発揮', kana: 'はっき', romaji: 'hakki', meaning: 'phát huy', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発電', kana: 'はつでん', romaji: 'hatsuden', meaning: 'phát điện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発売', kana: 'はつばい', romaji: 'hatsubai', meaning: 'phát hành, mở bán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '判事', kana: 'はんじ', romaji: 'hanji', meaning: 'thẩm phán', partOfSpeech: 'danh từ' },
      { kanji: '半径', kana: 'はんけい', romaji: 'hankei', meaning: 'bán kính', partOfSpeech: 'danh từ' },
      { kanji: '半島', kana: 'はんとう', romaji: 'hantou', meaning: 'bán đảo', partOfSpeech: 'danh từ' },
      { kanji: '反省', kana: 'はんせい', romaji: 'hansei', meaning: 'phản tỉnh, tự kiểm điểm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '番地', kana: 'ばんち', romaji: 'banchi', meaning: 'số nhà', partOfSpeech: 'danh từ' },
      { kanji: '卑怯', kana: 'ひきょう', romaji: 'hikyou', meaning: 'hèn nhát, xảo trá', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 764,
    jlptLevel: 'N2',
    words: [
      { kanji: '比較的', kana: 'ひかくてき', romaji: 'hikakuteki', meaning: 'tương đối', partOfSpeech: 'phó từ, tính từ na' },
      { kanji: '皮膚', kana: 'ひふ', romaji: 'hifu', meaning: 'làn da', partOfSpeech: 'danh từ' },
      { kanji: '美容', kana: 'びよう', romaji: 'biyou', meaning: 'làm đẹp, thẩm mỹ', partOfSpeech: 'danh từ' },
      { kanji: '肘', kana: 'ひじ', romaji: 'hiji', meaning: 'khuỷu tay', partOfSpeech: 'danh từ' },
      { kanji: '必需品', kana: 'ひつじゅひん', romaji: 'hitsujuhin', meaning: 'đồ dùng thiết yếu', partOfSpeech: 'danh từ' },
      { kanji: '筆記', kana: 'ひっき', romaji: 'hikki', meaning: 'ghi chép', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '筆者', kana: 'ひっしゃ', romaji: 'hissha', meaning: 'tác giả, người viết', partOfSpeech: 'danh từ' },
      { kanji: '標識', kana: 'ひょうしき', romaji: 'hyoushiki', meaning: 'biển báo', partOfSpeech: 'danh từ' },
      { kanji: '標本', kana: 'ひょうほん', romaji: 'hyouhon', meaning: 'mẫu vật', partOfSpeech: 'danh từ' },
      { kanji: '表紙', kana: 'ひょうし', romaji: 'hyoushi', meaning: 'bìa sách', partOfSpeech: 'danh từ' },
      { kanji: '評論', kana: 'ひょうろん', romaji: 'hyouron', meaning: 'phê bình, bình luận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '瓶詰', kana: 'びんづめ', romaji: 'bindzume', meaning: 'đóng chai, đóng lọ', partOfSpeech: 'danh từ' },
      { kanji: '不運', kana: 'ふうん', romaji: 'fuun', meaning: 'vận rủi, không may', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '不規則', kana: 'ふきそく', romaji: 'fukisoku', meaning: 'không đều đặn', partOfSpeech: 'tính từ na' },
      { kanji: '不潔', kana: 'ふけつ', romaji: 'fuketsu', meaning: 'không sạch, dơ bẩn', partOfSpeech: 'tính từ na' },
      { kanji: '敷く', kana: 'しく', romaji: 'shiku', meaning: 'trải ra, lót', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '敷地', kana: 'しきち', romaji: 'shikichi', meaning: 'khu đất, mặt bằng', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 765,
    jlptLevel: 'N2',
    words: [
      { kanji: '撫でる', kana: 'なでる', romaji: 'naderu', meaning: 'vuốt ve, xoa nhẹ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '武士', kana: 'ぶし', romaji: 'bushi', meaning: 'võ sĩ, samurai', partOfSpeech: 'danh từ' },
      { kanji: '部首', kana: 'ぶしゅ', romaji: 'bushu', meaning: 'bộ thủ (kanji)', partOfSpeech: 'danh từ' },
      { kanji: '部品', kana: 'ぶひん', romaji: 'buhin', meaning: 'linh kiện, phụ tùng', partOfSpeech: 'danh từ' },
      { kanji: '風船', kana: 'ふうせん', romaji: 'fuusen', meaning: 'bóng bay', partOfSpeech: 'danh từ' },
      { kanji: '複写', kana: 'ふくしゃ', romaji: 'fukusha', meaning: 'bản sao', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '複数', kana: 'ふくすう', romaji: 'fukusuu', meaning: 'số nhiều', partOfSpeech: 'danh từ' },
      { kanji: '物差し', kana: 'ものさし', romaji: 'monosashi', meaning: 'cây thước', partOfSpeech: 'danh từ' },
      { kanji: '物凄い', kana: 'ものすごい', romaji: 'monosugoi', meaning: 'khủng khiếp, ghê gớm', partOfSpeech: 'tính từ i' },
      { kanji: '物騒', kana: 'ぶっそう', romaji: 'bussou', meaning: 'nguy hiểm, bất an', partOfSpeech: 'tính từ na' },
      { kanji: '分解', kana: 'ぶんかい', romaji: 'bunkai', meaning: 'phân tích, tháo rời', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '分数', kana: 'ぶんすう', romaji: 'bunsuu', meaning: 'phân số', partOfSpeech: 'danh từ' },
      { kanji: '分布', kana: 'ぶんぷ', romaji: 'bunpu', meaning: 'phân bố', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '分量', kana: 'ぶんりょう', romaji: 'bunryou', meaning: 'khối lượng, lượng', partOfSpeech: 'danh từ' },
      { kanji: '噴火', kana: 'ふんか', romaji: 'funka', meaning: 'phun trào (núi lửa)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '噴水', kana: 'ふんすい', romaji: 'funsui', meaning: 'đài phun nước', partOfSpeech: 'danh từ' },
      { kanji: '文芸', kana: 'ぶんげい', romaji: 'bungei', meaning: 'văn nghệ', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 766,
    jlptLevel: 'N2',
    words: [
      { kanji: '文献', kana: 'ぶんけん', romaji: 'bunken', meaning: 'văn hiến, tài liệu tham khảo', partOfSpeech: 'danh từ' },
      { kanji: '文体', kana: 'ぶんたい', romaji: 'buntai', meaning: 'văn phong', partOfSpeech: 'danh từ' },
      { kanji: '文房具', kana: 'ぶんぼうぐ', romaji: 'bunbougu', meaning: 'văn phòng phẩm', partOfSpeech: 'danh từ' },
      { kanji: '文脈', kana: 'ぶんみゃく', romaji: 'bunmyaku', meaning: 'văn mạch, ngữ cảnh', partOfSpeech: 'danh từ' },
      { kanji: '兵隊', kana: 'へいたい', romaji: 'heitai', meaning: 'binh lính', partOfSpeech: 'danh từ' },
      { kanji: '平凡', kana: 'へいぼん', romaji: 'heibon', meaning: 'bình thường, tầm thường', partOfSpeech: 'tính từ na' },
      { kanji: '平野', kana: 'へいや', romaji: 'heiya', meaning: 'đồng bằng', partOfSpeech: 'danh từ' },
      { kanji: '並木', kana: 'なみき', romaji: 'namiki', meaning: 'hàng cây ven đường', partOfSpeech: 'danh từ' },
      { kanji: '別荘', kana: 'べっそう', romaji: 'bessou', meaning: 'biệt thự (nghỉ dưỡng)', partOfSpeech: 'danh từ' },
      { kanji: '編む', kana: 'あむ', romaji: 'amu', meaning: 'đan (len)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '編物', kana: 'あみもの', romaji: 'amimono', meaning: 'đồ đan len', partOfSpeech: 'danh từ' },
      { kanji: '便所', kana: 'べんじょ', romaji: 'benjo', meaning: 'nhà vệ sinh', partOfSpeech: 'danh từ' },
      { kanji: '便箋', kana: 'びんせん', romaji: 'binsen', meaning: 'giấy viết thư', partOfSpeech: 'danh từ' },
      { kanji: '補う', kana: 'おぎなう', romaji: 'oginau', meaning: 'bù đắp, bổ sung', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '包帯', kana: 'ほうたい', romaji: 'houtai', meaning: 'băng gạc', partOfSpeech: 'danh từ' },
      { kanji: '崩す', kana: 'くずす', romaji: 'kuzusu', meaning: 'phá bỏ, đổi tiền lẻ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '崩れる', kana: 'くずれる', romaji: 'kuzureru', meaning: 'sụp đổ', partOfSpeech: 'động từ nhóm 2' },
    ],
  },
  {
    lessonNumber: 767,
    jlptLevel: 'N2',
    words: [
      { kanji: '包丁', kana: 'ほうちょう', romaji: 'houchou', meaning: 'dao làm bếp', partOfSpeech: 'danh từ' },
      { kanji: '方言', kana: 'ほうげん', romaji: 'hougen', meaning: 'phương ngữ', partOfSpeech: 'danh từ' },
      { kanji: '方程式', kana: 'ほうていしき', romaji: 'houteishiki', meaning: 'phương trình', partOfSpeech: 'danh từ' },
      { kanji: '方面', kana: 'ほうめん', romaji: 'houmen', meaning: 'phương diện, khu vực', partOfSpeech: 'danh từ' },
      { kanji: '法則', kana: 'ほうそく', romaji: 'housoku', meaning: 'quy luật, định luật', partOfSpeech: 'danh từ' },
      { kanji: '縫う', kana: 'ぬう', romaji: 'nuu', meaning: 'khâu, may', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '妨げる', kana: 'さまたげる', romaji: 'samatageru', meaning: 'cản trở, gây trở ngại', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '暴れる', kana: 'あばれる', romaji: 'abareru', meaning: 'quậy phá, hung hãn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '望遠鏡', kana: 'ぼうえんきょう', romaji: 'bouenkyou', meaning: 'kính viễn vọng', partOfSpeech: 'danh từ' },
      { kanji: '膨大', kana: 'ぼうだい', romaji: 'boudai', meaning: 'to lớn, đồ sộ', partOfSpeech: 'tính từ na' },
      { kanji: '防犯', kana: 'ぼうはん', romaji: 'bouhan', meaning: 'phòng chống tội phạm', partOfSpeech: 'danh từ' },
      { kanji: '北極', kana: 'ほっきょく', romaji: 'hokkyoku', meaning: 'Bắc Cực', partOfSpeech: 'danh từ' },
      { kanji: '牧畜', kana: 'ぼくちく', romaji: 'bokuchiku', meaning: 'chăn nuôi gia súc', partOfSpeech: 'danh từ' },
      { kanji: '堀', kana: 'ほり', romaji: 'hori', meaning: 'hào nước', partOfSpeech: 'danh từ' },
      { kanji: '本部', kana: 'ほんぶ', romaji: 'honbu', meaning: 'trụ sở chính', partOfSpeech: 'danh từ' },
      { kanji: '本来', kana: 'ほんらい', romaji: 'honrai', meaning: 'vốn dĩ, bản chất', partOfSpeech: 'phó từ, danh từ' },
      { kanji: '盆', kana: 'ぼん', romaji: 'bon', meaning: 'khay; lễ Vu Lan (Obon)', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 768,
    jlptLevel: 'N2',
    words: [
      { kanji: '盆地', kana: 'ぼんち', romaji: 'bonchi', meaning: 'lòng chảo, bồn địa', partOfSpeech: 'danh từ' },
      { kanji: '枚数', kana: 'まいすう', romaji: 'maisuu', meaning: 'số lượng (tờ, tấm)', partOfSpeech: 'danh từ' },
      { kanji: '毎度', kana: 'まいど', romaji: 'maido', meaning: 'mỗi lần, luôn luôn', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '万歳', kana: 'ばんざい', romaji: 'banzai', meaning: 'vạn tuế, hoan hô', partOfSpeech: 'thán từ' },
      { kanji: '満員', kana: 'まんいん', romaji: 'man\'in', meaning: 'đầy chỗ, hết vé', partOfSpeech: 'danh từ' },
      { kanji: '満点', kana: 'まんてん', romaji: 'manten', meaning: 'điểm tuyệt đối', partOfSpeech: 'danh từ' },
      { kanji: '未満', kana: 'みまん', romaji: 'miman', meaning: 'dưới, chưa đến (mức nào đó)', partOfSpeech: 'danh từ' },
      { kanji: '岬', kana: 'みさき', romaji: 'misaki', meaning: 'mũi đất (ven biển)', partOfSpeech: 'danh từ' },
      { kanji: '民謡', kana: 'みんよう', romaji: 'min\'you', meaning: 'dân ca', partOfSpeech: 'danh từ' },
      { kanji: '無限', kana: 'むげん', romaji: 'mugen', meaning: 'vô hạn', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '無沙汰', kana: 'ぶさた', romaji: 'busata', meaning: 'lâu không liên lạc', partOfSpeech: 'danh từ' },
      { kanji: '無数', kana: 'むすう', romaji: 'musuu', meaning: 'vô số', partOfSpeech: 'tính từ na' },
      { kanji: '無地', kana: 'むじ', romaji: 'muji', meaning: 'trơn, không họa tiết', partOfSpeech: 'danh từ' },
      { kanji: '名字', kana: 'みょうじ', romaji: 'myouji', meaning: 'họ (tên)', partOfSpeech: 'danh từ' },
      { kanji: '名所', kana: 'めいしょ', romaji: 'meisho', meaning: 'danh lam thắng cảnh', partOfSpeech: 'danh từ' },
      { kanji: '名物', kana: 'めいぶつ', romaji: 'meibutsu', meaning: 'đặc sản', partOfSpeech: 'danh từ' },
      { kanji: '迷信', kana: 'めいしん', romaji: 'meishin', meaning: 'mê tín', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 769,
    jlptLevel: 'N2',
    words: [
      { kanji: '銘々', kana: 'めいめい', romaji: 'meimei', meaning: 'mỗi người, riêng lẻ', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '姪', kana: 'めい', romaji: 'mei', meaning: 'cháu gái', partOfSpeech: 'danh từ' },
      { kanji: '面積', kana: 'めんせき', romaji: 'menseki', meaning: 'diện tích', partOfSpeech: 'danh từ' },
      { kanji: '面倒臭い', kana: 'めんどうくさい', romaji: 'mendoukusai', meaning: 'phiền phức, rất rắc rối', partOfSpeech: 'tính từ i' },
      { kanji: '茂る', kana: 'しげる', romaji: 'shigeru', meaning: 'um tùm, rậm rạp', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '毛糸', kana: 'けいと', romaji: 'keito', meaning: 'len (sợi)', partOfSpeech: 'danh từ' },
      { kanji: '毛皮', kana: 'けがわ', romaji: 'kegawa', meaning: 'da lông thú', partOfSpeech: 'danh từ' },
      { kanji: '儲かる', kana: 'もうかる', romaji: 'moukaru', meaning: 'có lãi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '木材', kana: 'もくざい', romaji: 'mokuzai', meaning: 'gỗ, vật liệu gỗ', partOfSpeech: 'danh từ' },
      { kanji: '目安', kana: 'めやす', romaji: 'meyasu', meaning: 'tiêu chuẩn ước lượng', partOfSpeech: 'danh từ' },
      { kanji: '目印', kana: 'めじるし', romaji: 'mejirushi', meaning: 'dấu hiệu nhận biết', partOfSpeech: 'danh từ' },
      { kanji: '目下', kana: 'めした', romaji: 'meshita', meaning: 'cấp dưới; hiện tại', partOfSpeech: 'danh từ' },
      { kanji: '目次', kana: 'もくじ', romaji: 'mokuji', meaning: 'mục lục', partOfSpeech: 'danh từ' },
      { kanji: '目上', kana: 'めうえ', romaji: 'meue', meaning: 'cấp trên, bề trên', partOfSpeech: 'danh từ' },
      { kanji: '目立つ', kana: 'めだつ', romaji: 'medatsu', meaning: 'nổi bật', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '問答', kana: 'もんどう', romaji: 'mondou', meaning: 'hỏi đáp, đối thoại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '役者', kana: 'やくしゃ', romaji: 'yakusha', meaning: 'diễn viên', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 770,
    jlptLevel: 'N2',
    words: [
      { kanji: '役所', kana: 'やくしょ', romaji: 'yakusho', meaning: 'cơ quan hành chính', partOfSpeech: 'danh từ' },
      { kanji: '役人', kana: 'やくにん', romaji: 'yakunin', meaning: 'công chức', partOfSpeech: 'danh từ' },
      { kanji: '役目', kana: 'やくめ', romaji: 'yakume', meaning: 'nhiệm vụ, vai trò', partOfSpeech: 'danh từ' },
      { kanji: '薬局', kana: 'やっきょく', romaji: 'yakkyoku', meaning: 'nhà thuốc', partOfSpeech: 'danh từ' },
      { kanji: '薬指', kana: 'くすりゆび', romaji: 'kusuriyubi', meaning: 'ngón áp út', partOfSpeech: 'danh từ' },
      { kanji: '薬品', kana: 'やくひん', romaji: 'yakuhin', meaning: 'dược phẩm, hóa chất', partOfSpeech: 'danh từ' },
      { kanji: '油断', kana: 'ゆだん', romaji: 'yudan', meaning: 'lơ là, chủ quan', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '輸血', kana: 'ゆけつ', romaji: 'yuketsu', meaning: 'truyền máu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '勇ましい', kana: 'いさましい', romaji: 'isamashii', meaning: 'dũng cảm, hào hùng', partOfSpeech: 'tính từ i' },
      { kanji: '悠々', kana: 'ゆうゆう', romaji: 'yuuyuu', meaning: 'ung dung, thong thả', partOfSpeech: 'phó từ' },
      { kanji: '有難い', kana: 'ありがたい', romaji: 'arigatai', meaning: 'đáng quý, biết ơn', partOfSpeech: 'tính từ i' },
      { kanji: '有料', kana: 'ゆうりょう', romaji: 'yuuryou', meaning: 'có tính phí', partOfSpeech: 'danh từ' },
      { kanji: '遊園地', kana: 'ゆうえんち', romaji: 'yuuenchi', meaning: 'công viên giải trí', partOfSpeech: 'danh từ' },
      { kanji: '郵送', kana: 'ゆうそう', romaji: 'yuusou', meaning: 'gửi bưu điện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '夕日', kana: 'ゆうひ', romaji: 'yuuhi', meaning: 'ánh nắng chiều tà', partOfSpeech: 'danh từ' },
      { kanji: '夕立', kana: 'ゆうだち', romaji: 'yuudachi', meaning: 'mưa rào chiều', partOfSpeech: 'danh từ' },
      { kanji: '予備', kana: 'よび', romaji: 'yobi', meaning: 'dự bị, dự phòng', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 771,
    jlptLevel: 'N2',
    words: [
      { kanji: '余計', kana: 'よけい', romaji: 'yokei', meaning: 'thừa, không cần thiết', partOfSpeech: 'tính từ na, phó từ' },
      { kanji: '余所', kana: 'よそ', romaji: 'yoso', meaning: 'nơi khác', partOfSpeech: 'danh từ' },
      { kanji: '幼稚', kana: 'ようち', romaji: 'youchi', meaning: 'ấu trĩ, non nớt', partOfSpeech: 'tính từ na' },
      { kanji: '容積', kana: 'ようせき', romaji: 'youseki', meaning: 'dung tích', partOfSpeech: 'danh từ' },
      { kanji: '洋品店', kana: 'ようひんてん', romaji: 'youhinten', meaning: 'cửa hàng đồ Tây', partOfSpeech: 'danh từ' },
      { kanji: '溶かす', kana: 'とかす', romaji: 'tokasu', meaning: 'hòa tan, làm chảy', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '溶け込む', kana: 'とけこむ', romaji: 'tokekomu', meaning: 'hòa nhập, tan vào', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '溶岩', kana: 'ようがん', romaji: 'yougan', meaning: 'dung nham', partOfSpeech: 'danh từ' },
      { kanji: '用途', kana: 'ようと', romaji: 'youto', meaning: 'công dụng', partOfSpeech: 'danh từ' },
      { kanji: '羊毛', kana: 'ようもう', romaji: 'youmou', meaning: 'lông cừu', partOfSpeech: 'danh từ' },
      { kanji: '要領', kana: 'ようりょう', romaji: 'youryou', meaning: 'điểm mấu chốt, bí quyết', partOfSpeech: 'danh từ' },
      { kanji: '日差し', kana: 'ひざし', romaji: 'hizashi', meaning: 'ánh nắng', partOfSpeech: 'danh từ' },
      { kanji: '養分', kana: 'ようぶん', romaji: 'youbun', meaning: 'chất dinh dưỡng', partOfSpeech: 'danh từ' },
      { kanji: '欲張り', kana: 'よくばり', romaji: 'yokubari', meaning: 'tham lam', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '浴衣', kana: 'ゆかた', romaji: 'yukata', meaning: 'yukata (kimono mùa hè)', partOfSpeech: 'danh từ' },
      { kanji: '来日', kana: 'らいにち', romaji: 'rainichi', meaning: 'đến Nhật Bản', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '落第', kana: 'らくだい', romaji: 'rakudai', meaning: 'trượt, rớt (thi)', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 772,
    jlptLevel: 'N2',
    words: [
      { kanji: '乱暴', kana: 'らんぼう', romaji: 'ranbou', meaning: 'thô bạo, hung bạo', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '欄', kana: 'らん', romaji: 'ran', meaning: 'cột, mục (trên báo)', partOfSpeech: 'danh từ' },
      { kanji: '理科', kana: 'りか', romaji: 'rika', meaning: 'môn khoa học tự nhiên', partOfSpeech: 'danh từ' },
      { kanji: '裏口', kana: 'うらぐち', romaji: 'uraguchi', meaning: 'cửa sau', partOfSpeech: 'danh từ' },
      { kanji: '略す', kana: 'りゃくす', romaji: 'ryakusu', meaning: 'viết tắt, lược bỏ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '流域', kana: 'りゅういき', romaji: 'ryuuiki', meaning: 'lưu vực (sông)', partOfSpeech: 'danh từ' },
      { kanji: '溜息', kana: 'ためいき', romaji: 'tameiki', meaning: 'tiếng thở dài', partOfSpeech: 'danh từ' },
      { kanji: '粒', kana: 'つぶ', romaji: 'tsubu', meaning: 'hạt (đơn vị đếm)', partOfSpeech: 'danh từ' },
      { kanji: '両側', kana: 'りょうがわ', romaji: 'ryougawa', meaning: 'hai bên', partOfSpeech: 'danh từ' },
      { kanji: '領事', kana: 'りょうじ', romaji: 'ryouji', meaning: 'lãnh sự', partOfSpeech: 'danh từ' },
      { kanji: '領収', kana: 'りょうしゅう', romaji: 'ryoushuu', meaning: 'nhận (tiền), thu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '力強い', kana: 'ちからづよい', romaji: 'chikarazuyoi', meaning: 'mạnh mẽ, vững tâm', partOfSpeech: 'tính từ i' },
      { kanji: '臨時', kana: 'りんじ', romaji: 'rinji', meaning: 'tạm thời, đặc biệt', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '冷凍', kana: 'れいとう', romaji: 'reitou', meaning: 'đông lạnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '鈴', kana: 'すず', romaji: 'suzu', meaning: 'cái chuông nhỏ', partOfSpeech: 'danh từ' },
      { kanji: '零点', kana: 'れいてん', romaji: 'reiten', meaning: 'điểm không', partOfSpeech: 'danh từ' },
      { kanji: '列島', kana: 'れっとう', romaji: 'rettou', meaning: 'quần đảo', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 773,
    jlptLevel: 'N2',
    words: [
      { kanji: '煉瓦', kana: 'れんが', romaji: 'renga', meaning: 'gạch', partOfSpeech: 'danh từ' },
      { kanji: '朗らか', kana: 'ほがらか', romaji: 'hogaraka', meaning: 'vui vẻ, sáng sủa (tính cách)', partOfSpeech: 'tính từ na' },
      { kanji: '蝋燭', kana: 'ろうそく', romaji: 'rousoku', meaning: 'cây nến', partOfSpeech: 'danh từ' },
      { kanji: '麓', kana: 'ふもと', romaji: 'fumoto', meaning: 'chân núi', partOfSpeech: 'danh từ' },
      { kanji: '和英', kana: 'わえい', romaji: 'waei', meaning: 'Nhật-Anh', partOfSpeech: 'danh từ' },
      { kanji: '和服', kana: 'わふく', romaji: 'wafuku', meaning: 'trang phục truyền thống Nhật', partOfSpeech: 'danh từ' },
      { kanji: '話中', kana: 'はなしちゅう', romaji: 'hanashichuu', meaning: 'đang nói, máy bận', partOfSpeech: 'danh từ' },
      { kanji: '囁く', kana: 'ささやく', romaji: 'sasayaku', meaning: 'thì thầm', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '捩る', kana: 'ねじる', romaji: 'nejiru', meaning: 'vặn, xoắn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '狡い', kana: 'ずるい', romaji: 'zurui', meaning: 'xảo quyệt, ranh mãnh', partOfSpeech: 'tính từ i' },
      { kanji: '睨む', kana: 'にらむ', romaji: 'niramu', meaning: 'trừng mắt, nhìn chằm chằm', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '箒', kana: 'ほうき', romaji: 'houki', meaning: 'cái chổi', partOfSpeech: 'danh từ' },
      { kana: 'しいんと', romaji: 'shiinto', meaning: 'im lặng như tờ', partOfSpeech: 'phó từ, động từ する' },
      { kanji: '絨毯', kana: 'じゅうたん', romaji: 'juutan', meaning: 'tấm thảm', partOfSpeech: 'danh từ' },
      { kanji: '第一', kana: 'だいいち', romaji: 'daiichi', meaning: 'trước hết, hàng đầu', partOfSpeech: 'phó từ, danh từ' },
      { kana: 'ミリ', romaji: 'miri', meaning: 'mili- (đơn vị đo lường)', partOfSpeech: 'danh từ' },
    ],
  },
];
