// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 900-904.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART1: JlptVocabUnit[] = [
  {
    lessonNumber: 900,
    jlptLevel: 'N1',
    words: [
      { kana: 'アイデア', romaji: 'aidea', meaning: 'ý tưởng', partOfSpeech: 'danh từ' },
      { kana: 'アクセル', romaji: 'akuseru', meaning: 'chân ga (xe)', partOfSpeech: 'danh từ' },
      { kana: 'あくどい', romaji: 'akudoi', meaning: 'lòe loẹt quá mức; độc ác, thâm hiểm', partOfSpeech: 'tính từ i' },
      { kanji: '嘲笑います', kana: 'あざわらいます', romaji: 'azawaraimasu', meaning: 'cười nhạo, chế giễu', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'あっさり', romaji: 'assari', meaning: 'đơn giản, thanh đạm, dễ dàng', partOfSpeech: 'phó từ' },
      { kana: 'アプローチ', romaji: 'apurōchi', meaning: 'cách tiếp cận', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'あべこべ', romaji: 'abekobe', meaning: 'ngược lại, trái ngược', partOfSpeech: 'danh từ, tính từ na' },
      { kana: 'アマチュア', romaji: 'amachua', meaning: 'nghiệp dư', partOfSpeech: 'danh từ' },
      { kana: 'あやふや', romaji: 'ayafuya', meaning: 'mập mờ, không rõ ràng', partOfSpeech: 'tính từ na' },
      { kana: 'あられ', romaji: 'arare', meaning: 'mưa đá; bánh gạo nhỏ (arare)', partOfSpeech: 'danh từ' },
      { kana: 'アルカリ', romaji: 'arukari', meaning: 'kiềm (hóa học)', partOfSpeech: 'danh từ' },
      { kana: 'アルミ', romaji: 'arumi', meaning: 'nhôm', partOfSpeech: 'danh từ' },
      { kana: 'アンケート', romaji: 'ankēto', meaning: 'bảng khảo sát, phiếu điều tra', partOfSpeech: 'danh từ' },
      { kana: 'アンコール', romaji: 'ankōru', meaning: 'yêu cầu hát/diễn thêm (encore)', partOfSpeech: 'danh từ' },
      { kana: 'いざ', romaji: 'iza', meaning: 'khi thời khắc quan trọng đến', partOfSpeech: 'thán từ' },
      { kana: 'いっそ', romaji: 'isso', meaning: 'thà rằng, thà là', partOfSpeech: 'phó từ' },
      { kana: 'いやに', romaji: 'iyani', meaning: 'kỳ lạ, khác thường (mức độ)', partOfSpeech: 'phó từ' },
    ],
  },
  {
    lessonNumber: 901,
    jlptLevel: 'N1',
    words: [
      { kana: 'インターチェンジ', romaji: 'intāchiぇnji', meaning: 'nút giao thông (đường cao tốc)', partOfSpeech: 'danh từ' },
      { kana: 'インターナショナル', romaji: 'intānashonaru', meaning: 'mang tính quốc tế', partOfSpeech: 'tính từ na' },
      { kana: 'インターフォン', romaji: 'intāfuぉn', meaning: 'chuông cửa có loa', partOfSpeech: 'danh từ' },
      { kana: 'インテリ', romaji: 'interi', meaning: 'tầng lớp trí thức', partOfSpeech: 'danh từ' },
      { kana: 'インフォメーション', romaji: 'infuぉmēshon', meaning: 'thông tin, quầy thông tin', partOfSpeech: 'danh từ' },
      { kana: 'うんざり', romaji: 'unzari', meaning: 'chán ngán, ngán ngẩm', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'エレガント', romaji: 'ereganto', meaning: 'thanh lịch, sang trọng', partOfSpeech: 'tính từ na' },
      { kana: 'オートマチック', romaji: 'ōtomachikku', meaning: 'tự động', partOfSpeech: 'tính từ na, danh từ' },
      { kana: 'おっかない', romaji: 'okkanai', meaning: 'đáng sợ (cách nói thông tục)', partOfSpeech: 'tính từ i' },
      { kana: 'おどおど', romaji: 'odōdo', meaning: 'rụt rè, sợ sệt', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'オリエンテーション', romaji: 'orientēshon', meaning: 'buổi định hướng', partOfSpeech: 'danh từ' },
      { kana: 'オンライン', romaji: 'onrain', meaning: 'trực tuyến', partOfSpeech: 'danh từ' },
      { kanji: 'お宮', kana: 'おみや', romaji: 'omiya', meaning: 'đền thờ Thần đạo', partOfSpeech: 'danh từ' },
      { kanji: 'お供', kana: 'おとも', romaji: 'otomo', meaning: 'người tháp tùng, tùy tùng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: 'お産', kana: 'おさん', romaji: 'osan', meaning: 'sự sinh nở', partOfSpeech: 'danh từ' },
      { kanji: 'お使い', kana: 'おつかい', romaji: 'otsukai', meaning: 'việc vặt, đi sai vặt', partOfSpeech: 'danh từ' },
      { kanji: 'お手上げ', kana: 'おてあげ', romaji: 'oteage', meaning: 'chịu thua, bó tay', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 902,
    jlptLevel: 'N1',
    words: [
      { kanji: 'お世辞', kana: 'おせじ', romaji: 'oseji', meaning: 'lời nịnh hót, lời khen xã giao', partOfSpeech: 'danh từ' },
      { kanji: 'お襁褓', kana: 'おむつ', romaji: 'omutsu', meaning: 'tã lót', partOfSpeech: 'danh từ' },
      { kana: 'カーペット', romaji: 'kāpetto', meaning: 'thảm trải sàn', partOfSpeech: 'danh từ' },
      { kana: 'カクテル', romaji: 'kakuteru', meaning: 'cocktail', partOfSpeech: 'danh từ' },
      { kana: 'がっくり', romaji: 'gakkuri', meaning: 'suy sụp, thất vọng nặng nề', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'がっしり', romaji: 'gasshiri', meaning: 'vạm vỡ, chắc chắn', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'がっちり', romaji: 'gacchiri', meaning: 'chắc nịch; tính toán chặt chẽ', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'カテゴリー', romaji: 'kategorī', meaning: 'phạm trù, danh mục', partOfSpeech: 'danh từ' },
      { kana: 'カムバック', romaji: 'kamubakku', meaning: 'sự trở lại (sau vắng bóng)', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'カメラマン', romaji: 'kameraman', meaning: 'nhiếp ảnh gia, quay phim', partOfSpeech: 'danh từ' },
      { kana: 'カルテ', romaji: 'karute', meaning: 'hồ sơ bệnh án', partOfSpeech: 'danh từ' },
      { kana: 'ガレージ', romaji: 'garēji', meaning: 'nhà để xe (gara)', partOfSpeech: 'danh từ' },
      { kana: 'カンニング', romaji: 'kanningu', meaning: 'sự quay cóp, gian lận thi cử', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'きちっと', romaji: 'kichitto', meaning: 'chính xác, gọn gàng', partOfSpeech: 'phó từ' },
      { kana: 'きっかり', romaji: 'kikkari', meaning: 'chính xác, đúng giờ', partOfSpeech: 'phó từ' },
      { kana: 'きっちり', romaji: 'kicchiri', meaning: 'khít, chính xác', partOfSpeech: 'phó từ' },
      { kana: 'きっぱり', romaji: 'kippari', meaning: 'dứt khoát, rõ ràng', partOfSpeech: 'phó từ' },
    ],
  },
  {
    lessonNumber: 903,
    jlptLevel: 'N1',
    words: [
      { kana: 'キャッチ', romaji: 'kyacchi', meaning: 'sự bắt, nắm bắt', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'キャリア', romaji: 'kyaria', meaning: 'sự nghiệp, kinh nghiệm nghề nghiệp', partOfSpeech: 'danh từ' },
      { kana: 'クイズ', romaji: 'kuizu', meaning: 'câu đố, trò chơi kiến thức', partOfSpeech: 'danh từ' },
      { kana: 'くっきり', romaji: 'kukkiri', meaning: 'rõ nét, nổi bật', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'ぐっと', romaji: 'gutto', meaning: 'mạnh mẽ, đáng kể (hơn hẳn)', partOfSpeech: 'phó từ' },
      { kana: 'グレー', romaji: 'gurē', meaning: 'màu xám', partOfSpeech: 'danh từ' },
      { kana: 'クレーン', romaji: 'kurēn', meaning: 'cần cẩu', partOfSpeech: 'danh từ' },
      { kana: 'ゲスト', romaji: 'gesuto', meaning: 'khách mời', partOfSpeech: 'danh từ' },
      { kana: 'げっそり', romaji: 'gessori', meaning: 'sụt cân, hốc hác; chán nản', partOfSpeech: 'phó từ, động từ する' },
      { kanji: 'ヶ月', kana: 'かげつ', romaji: 'kagetsu', meaning: 'tháng (đơn vị đếm số tháng)', partOfSpeech: 'danh từ' },
      { kanji: '拘ります', kana: 'こだわります', romaji: 'kodawarimasu', meaning: 'câu nệ, khắt khe về (điều gì)', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'コマーシャル', romaji: 'komāsharu', meaning: 'quảng cáo (truyền hình)', partOfSpeech: 'danh từ' },
      { kana: 'コミュニケーション', romaji: 'komyunikēshon', meaning: 'sự giao tiếp', partOfSpeech: 'danh từ' },
      { kana: 'コメント', romaji: 'komento', meaning: 'lời bình luận', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'コンタクト', romaji: 'kontakuto', meaning: 'liên lạc; kính áp tròng', partOfSpeech: 'danh từ' },
      { kana: 'コントラスト', romaji: 'kontorasuto', meaning: 'sự tương phản', partOfSpeech: 'danh từ' },
      { kana: 'コントロール', romaji: 'kontorōru', meaning: 'sự kiểm soát', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 904,
    jlptLevel: 'N1',
    words: [
      { kana: 'コンパス', romaji: 'konpasu', meaning: 'com-pa; la bàn', partOfSpeech: 'danh từ' },
      { kana: 'サイクル', romaji: 'saikuru', meaning: 'chu kỳ', partOfSpeech: 'danh từ' },
      { kana: 'さっと', romaji: 'satto', meaning: 'nhanh chóng, thoáng qua', partOfSpeech: 'phó từ' },
      { kana: 'サボります', romaji: 'saborimasu', meaning: 'trốn học/trốn việc', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'シート', romaji: 'shīto', meaning: 'tấm, tờ; ghế ngồi', partOfSpeech: 'danh từ' },
      { kana: 'ジーパン', romaji: 'jīpan', meaning: 'quần jean', partOfSpeech: 'danh từ' },
      { kana: 'しくじります', romaji: 'shikujirimasu', meaning: 'thất bại, sai sót', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'シック', romaji: 'shikku', meaning: 'sành điệu, tinh tế', partOfSpeech: 'tính từ na' },
      { kana: 'じっくり', romaji: 'jikkuri', meaning: 'kỹ lưỡng, thong thả', partOfSpeech: 'phó từ' },
      { kana: 'シナリオ', romaji: 'shinario', meaning: 'kịch bản', partOfSpeech: 'danh từ' },
      { kana: 'しぶとい', romaji: 'shibutoi', meaning: 'bền bỉ, ương ngạnh', partOfSpeech: 'tính từ i' },
      { kana: 'しまった', romaji: 'shimatta', meaning: 'chết rồi! hỏng rồi! (thán từ)', partOfSpeech: 'thán từ' },
    ],
  },
];
