// Bổ sung từ vựng N2 đợt 3 — tự soạn tay. lessonNumber 425–431.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST3_N2: JlptVocabUnit[] = [
  {
    lessonNumber: 425,
    jlptLevel: 'N2',
    words: [
      { kanji: '認識', kana: 'にんしき', romaji: 'ninshiki', meaning: 'nhận thức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '意識', kana: 'いしき', romaji: 'ishiki', meaning: 'ý thức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '自覚', kana: 'じかく', romaji: 'jikaku', meaning: 'tự nhận thức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '無意識', kana: 'むいしき', romaji: 'muishiki', meaning: 'vô thức', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '本能', kana: 'ほんのう', romaji: 'honnō', meaning: 'bản năng', partOfSpeech: 'danh từ' },
      { kanji: '理性', kana: 'りせい', romaji: 'risei', meaning: 'lý trí', partOfSpeech: 'danh từ' },
      { kanji: '感性', kana: 'かんせい', romaji: 'kansei', meaning: 'cảm tính', partOfSpeech: 'danh từ' },
      { kanji: '直感', kana: 'ちょっかん', romaji: 'chokkan', meaning: 'trực giác', partOfSpeech: 'danh từ' },
      { kanji: '発想', kana: 'はっそう', romaji: 'hassō', meaning: 'ý tưởng, cách nghĩ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '概念', kana: 'がいねん', romaji: 'gainen', meaning: 'khái niệm', partOfSpeech: 'danh từ' },
      { kanji: '価値観', kana: 'かちかん', romaji: 'kachikan', meaning: 'quan điểm giá trị', partOfSpeech: 'danh từ' },
      { kanji: '人生観', kana: 'じんせいかん', romaji: 'jinseikan', meaning: 'quan niệm về cuộc sống', partOfSpeech: 'danh từ' },
      { kanji: '世界観', kana: 'せかいかん', romaji: 'sekaikan', meaning: 'thế giới quan', partOfSpeech: 'danh từ' },
      { kanji: '固定観念', kana: 'こていかんねん', romaji: 'kotei kannen', meaning: 'định kiến cố hữu', partOfSpeech: 'danh từ' },
      { kanji: '常識', kana: 'じょうしき', romaji: 'jōshiki', meaning: 'lẽ thường, thường thức', partOfSpeech: 'danh từ' },
      { kanji: '非常識', kana: 'ひじょうしき', romaji: 'hijōshiki', meaning: 'trái lẽ thường', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '矛盾', kana: 'むじゅん', romaji: 'mujun', meaning: 'mâu thuẫn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '曖昧', kana: 'あいまい', romaji: 'aimai', meaning: 'mơ hồ', partOfSpeech: 'tính từ na' },
      { kanji: '明確', kana: 'めいかく', romaji: 'meikaku', meaning: 'rõ ràng, minh xác', partOfSpeech: 'tính từ na' },
      { kanji: '具体的', kana: 'ぐたいてき', romaji: 'gutaiteki', meaning: 'cụ thể', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 426,
    jlptLevel: 'N2',
    words: [
      { kanji: '抽象的', kana: 'ちゅうしょうてき', romaji: 'chūshōteki', meaning: 'trừu tượng', partOfSpeech: 'tính từ na' },
      { kanji: '客観的', kana: 'きゃっかんてき', romaji: 'kyakkanteki', meaning: 'khách quan', partOfSpeech: 'tính từ na' },
      { kanji: '主観的', kana: 'しゅかんてき', romaji: 'shukanteki', meaning: 'chủ quan', partOfSpeech: 'tính từ na' },
      { kanji: '論理的', kana: 'ろんりてき', romaji: 'ronriteki', meaning: 'mang tính logic', partOfSpeech: 'tính từ na' },
      { kanji: '合理的', kana: 'ごうりてき', romaji: 'gōriteki', meaning: 'hợp lý', partOfSpeech: 'tính từ na' },
      { kanji: '効率的', kana: 'こうりつてき', romaji: 'kōritsuteki', meaning: 'hiệu quả', partOfSpeech: 'tính từ na' },
      { kanji: '積極的', kana: 'せっきょくてき', romaji: 'sekkyokuteki', meaning: 'tích cực', partOfSpeech: 'tính từ na' },
      { kanji: '消極的', kana: 'しょうきょくてき', romaji: 'shōkyokuteki', meaning: 'tiêu cực', partOfSpeech: 'tính từ na' },
      { kanji: '肯定的', kana: 'こうていてき', romaji: 'kōteiteki', meaning: 'mang tính khẳng định', partOfSpeech: 'tính từ na' },
      { kanji: '否定的', kana: 'ひていてき', romaji: 'hiteiteki', meaning: 'mang tính phủ định', partOfSpeech: 'tính từ na' },
      { kanji: '批判的', kana: 'ひはんてき', romaji: 'hihanteki', meaning: 'mang tính phê phán', partOfSpeech: 'tính từ na' },
      { kanji: '一般的', kana: 'いっぱんてき', romaji: 'ippanteki', meaning: 'thông thường, phổ biến', partOfSpeech: 'tính từ na' },
      { kanji: '特殊', kana: 'とくしゅ', romaji: 'tokushu', meaning: 'đặc thù', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '典型的', kana: 'てんけいてき', romaji: 'tenkeiteki', meaning: 'điển hình', partOfSpeech: 'tính từ na' },
      { kanji: '象徴的', kana: 'しょうちょうてき', romaji: 'shōchōteki', meaning: 'mang tính biểu tượng', partOfSpeech: 'tính từ na' },
      { kanji: '理論的', kana: 'りろんてき', romaji: 'rironteki', meaning: 'mang tính lý luận', partOfSpeech: 'tính từ na' },
      { kanji: '理論', kana: 'りろん', romaji: 'riron', meaning: 'lý luận', partOfSpeech: 'danh từ' },
      { kanji: '学説', kana: 'がくせつ', romaji: 'gakusetsu', meaning: 'học thuyết', partOfSpeech: 'danh từ' },
      { kanji: '仮説', kana: 'かせつ', romaji: 'kasetsu', meaning: 'giả thuyết', partOfSpeech: 'danh từ' },
      { kanji: '前提', kana: 'ぜんてい', romaji: 'zentei', meaning: 'tiền đề', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 427,
    jlptLevel: 'N2',
    words: [
      { kanji: '風潮', kana: 'ふうちょう', romaji: 'fūchō', meaning: 'trào lưu xã hội', partOfSpeech: 'danh từ' },
      { kanji: '傾向', kana: 'けいこう', romaji: 'keikō', meaning: 'khuynh hướng', partOfSpeech: 'danh từ' },
      { kanji: '動向', kana: 'どうこう', romaji: 'dōkō', meaning: 'xu hướng, động thái', partOfSpeech: 'danh từ' },
      { kanji: '流行', kana: 'りゅうこう', romaji: 'ryūkō', meaning: 'trào lưu, mốt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '普及', kana: 'ふきゅう', romaji: 'fukyū', meaning: 'phổ cập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '浸透', kana: 'しんとう', romaji: 'shintō', meaning: 'thẩm thấu, lan tỏa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '定着', kana: 'ていちゃく', romaji: 'teichaku', meaning: 'trở nên cố định, bén rễ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '衰退', kana: 'すいたい', romaji: 'suitai', meaning: 'suy thoái', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '消滅', kana: 'しょうめつ', romaji: 'shōmetsu', meaning: 'biến mất', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '復活', kana: 'ふっかつ', romaji: 'fukkatsu', meaning: 'phục hồi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '再生', kana: 'さいせい', romaji: 'saisei', meaning: 'tái sinh, phát lại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '進化', kana: 'しんか', romaji: 'shinka', meaning: 'tiến hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '退化', kana: 'たいか', romaji: 'taika', meaning: 'thoái hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '変容', kana: 'へんよう', romaji: 'hen\'yō', meaning: 'biến đổi hình thái', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '多様化', kana: 'たようか', romaji: 'tayōka', meaning: 'đa dạng hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '単純化', kana: 'たんじゅんか', romaji: 'tanjunka', meaning: 'đơn giản hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '複雑化', kana: 'ふくざつか', romaji: 'fukuzatsuka', meaning: 'phức tạp hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '高齢化', kana: 'こうれいか', romaji: 'kōreika', meaning: 'già hóa dân số', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '少子化', kana: 'しょうしか', romaji: 'shōshika', meaning: 'tỷ lệ sinh giảm', partOfSpeech: 'danh từ' },
      { kanji: '国際化', kana: 'こくさいか', romaji: 'kokusaika', meaning: 'quốc tế hóa', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 428,
    jlptLevel: 'N2',
    words: [
      { kanji: '主催', kana: 'しゅさい', romaji: 'shusai', meaning: 'chủ trì tổ chức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '共催', kana: 'きょうさい', romaji: 'kyōsai', meaning: 'đồng tổ chức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '後援', kana: 'こうえん', romaji: 'kōen', meaning: 'hậu thuẫn, tài trợ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '協賛', kana: 'きょうさん', romaji: 'kyōsan', meaning: 'tán trợ, đồng tài trợ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '主宰', kana: 'しゅさい', romaji: 'shusai', meaning: 'chủ trì (một tổ chức)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '出席者', kana: 'しゅっせきしゃ', romaji: 'shussekisha', meaning: 'người tham dự', partOfSpeech: 'danh từ' },
      { kanji: '主催者', kana: 'しゅさいしゃ', romaji: 'shusaisha', meaning: 'người tổ chức', partOfSpeech: 'danh từ' },
      { kanji: '来賓', kana: 'らいひん', romaji: 'raihin', meaning: 'khách mời danh dự', partOfSpeech: 'danh từ' },
      { kanji: '司会', kana: 'しかい', romaji: 'shikai', meaning: 'người dẫn chương trình', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '進行', kana: 'しんこう', romaji: 'shinkō', meaning: 'điều hành chương trình, tiến triển', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '式典', kana: 'しきてん', romaji: 'shikiten', meaning: 'buổi lễ trang trọng', partOfSpeech: 'danh từ' },
      { kanji: '挨拶', kana: 'あいさつ', romaji: 'aisatsu', meaning: 'lời chào, phát biểu chào mừng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '祝辞', kana: 'しゅくじ', romaji: 'shukuji', meaning: 'lời chúc mừng', partOfSpeech: 'danh từ' },
      { kanji: '演説', kana: 'えんぜつ', romaji: 'enzetsu', meaning: 'bài diễn thuyết', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '講演', kana: 'こうえん', romaji: 'kōen', meaning: 'buổi thuyết trình', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '講師', kana: 'こうし', romaji: 'kōshi', meaning: 'giảng viên, diễn giả', partOfSpeech: 'danh từ' },
      { kanji: '聴衆', kana: 'ちょうしゅう', romaji: 'chōshū', meaning: 'khán giả, người nghe', partOfSpeech: 'danh từ' },
      { kanji: '拍手', kana: 'はくしゅ', romaji: 'hakushu', meaning: 'vỗ tay', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '質疑応答', kana: 'しつぎおうとう', romaji: 'shitsugi ōtō', meaning: 'hỏi đáp', partOfSpeech: 'danh từ' },
      { kanji: '閉会', kana: 'へいかい', romaji: 'heikai', meaning: 'bế mạc', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 429,
    jlptLevel: 'N2',
    words: [
      { kanji: '医療', kana: 'いりょう', romaji: 'iryō', meaning: 'y tế', partOfSpeech: 'danh từ' },
      { kanji: '保険', kana: 'ほけん', romaji: 'hoken', meaning: 'bảo hiểm', partOfSpeech: 'danh từ' },
      { kanji: '年金', kana: 'ねんきん', romaji: 'nenkin', meaning: 'lương hưu', partOfSpeech: 'danh từ' },
      { kanji: '福祉', kana: 'ふくし', romaji: 'fukushi', meaning: 'phúc lợi xã hội', partOfSpeech: 'danh từ' },
      { kanji: '介護', kana: 'かいご', romaji: 'kaigo', meaning: 'chăm sóc người già/bệnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '福祉施設', kana: 'ふくししせつ', romaji: 'fukushi shisetsu', meaning: 'cơ sở phúc lợi xã hội', partOfSpeech: 'danh từ' },
      { kanji: '社会保障', kana: 'しゃかいほしょう', romaji: 'shakai hoshō', meaning: 'an sinh xã hội', partOfSpeech: 'danh từ' },
      { kanji: '生活保護', kana: 'せいかつほご', romaji: 'seikatsu hogo', meaning: 'trợ cấp xã hội', partOfSpeech: 'danh từ' },
      { kanji: '貧困層', kana: 'ひんこんそう', romaji: 'hinkonsō', meaning: 'tầng lớp nghèo', partOfSpeech: 'danh từ' },
      { kanji: '格差社会', kana: 'かくさしゃかい', romaji: 'kakusa shakai', meaning: 'xã hội phân hóa giàu nghèo', partOfSpeech: 'danh từ' },
      { kanji: '経済格差', kana: 'けいざいかくさ', romaji: 'keizai kakusa', meaning: 'chênh lệch kinh tế', partOfSpeech: 'danh từ' },
      { kanji: '所得', kana: 'しょとく', romaji: 'shotoku', meaning: 'thu nhập', partOfSpeech: 'danh từ' },
      { kanji: '納税', kana: 'のうぜい', romaji: 'nōzei', meaning: 'nộp thuế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '財政', kana: 'ざいせい', romaji: 'zaisei', meaning: 'tài chính (nhà nước)', partOfSpeech: 'danh từ' },
      { kanji: '予算', kana: 'よさん', romaji: 'yosan', meaning: 'ngân sách dự trù', partOfSpeech: 'danh từ' },
      { kanji: '赤字', kana: 'あかじ', romaji: 'akaji', meaning: 'thâm hụt, lỗ', partOfSpeech: 'danh từ' },
      { kanji: '黒字', kana: 'くろじ', romaji: 'kuroji', meaning: 'lãi, thặng dư', partOfSpeech: 'danh từ' },
      { kanji: '国債', kana: 'こくさい', romaji: 'kokusai', meaning: 'trái phiếu chính phủ', partOfSpeech: 'danh từ' },
      { kanji: '借金', kana: 'しゃっきん', romaji: 'shakkin', meaning: 'nợ nần', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '返済', kana: 'へんさい', romaji: 'hensai', meaning: 'trả nợ', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 430,
    jlptLevel: 'N2',
    words: [
      { kanji: '演技', kana: 'えんぎ', romaji: 'engi', meaning: 'diễn xuất', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '俳優', kana: 'はいゆう', romaji: 'haiyū', meaning: 'diễn viên', partOfSpeech: 'danh từ' },
      { kanji: '監督', kana: 'かんとく', romaji: 'kantoku', meaning: 'đạo diễn, huấn luyện viên', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '脚本', kana: 'きゃくほん', romaji: 'kyakuhon', meaning: 'kịch bản', partOfSpeech: 'danh từ' },
      { kanji: '台本', kana: 'だいほん', romaji: 'daihon', meaning: 'kịch bản (sân khấu)', partOfSpeech: 'danh từ' },
      { kanji: '撮影', kana: 'さつえい', romaji: 'satsuei', meaning: 'quay phim, chụp ảnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '公開', kana: 'こうかい', romaji: 'kōkai', meaning: 'công chiếu, công khai', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '興行', kana: 'こうぎょう', romaji: 'kōgyō', meaning: 'buổi biểu diễn thương mại', partOfSpeech: 'danh từ' },
      { kanji: '観客', kana: 'かんきゃく', romaji: 'kankyaku', meaning: 'khán giả', partOfSpeech: 'danh từ' },
      { kanji: '客席', kana: 'きゃくせき', romaji: 'kyakuseki', meaning: 'chỗ ngồi khán giả', partOfSpeech: 'danh từ' },
      { kanji: '舞台', kana: 'ぶたい', romaji: 'butai', meaning: 'sân khấu', partOfSpeech: 'danh từ' },
      { kanji: '主役', kana: 'しゅやく', romaji: 'shuyaku', meaning: 'vai chính', partOfSpeech: 'danh từ' },
      { kanji: '脇役', kana: 'わきやく', romaji: 'wakiyaku', meaning: 'vai phụ', partOfSpeech: 'danh từ' },
      { kanji: '配役', kana: 'はいやく', romaji: 'haiyaku', meaning: 'phân vai', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '演出', kana: 'えんしゅつ', romaji: 'enshutsu', meaning: 'dàn dựng, đạo diễn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '興行収入', kana: 'こうぎょうしゅうにゅう', romaji: 'kōgyō shūnyū', meaning: 'doanh thu phòng vé', partOfSpeech: 'danh từ' },
      { kanji: '話題', kana: 'わだい', romaji: 'wadai', meaning: 'chủ đề bàn tán', partOfSpeech: 'danh từ' },
      { kanji: '大ヒット', kana: 'だいヒット', romaji: 'dai hitto', meaning: 'thành công vang dội', partOfSpeech: 'danh từ' },
      { kanji: '興味本位', kana: 'きょうみほんい', romaji: 'kyōmi hon\'i', meaning: 'chỉ vì tò mò', partOfSpeech: 'danh từ' },
      { kanji: '原作者', kana: 'げんさくしゃ', romaji: 'gensakusha', meaning: 'tác giả nguyên tác', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 431,
    jlptLevel: 'N2',
    words: [
      { kanji: '気候', kana: 'きこう', romaji: 'kikō', meaning: 'khí hậu', partOfSpeech: 'danh từ' },
      { kanji: '生態系', kana: 'せいたいけい', romaji: 'seitaikei', meaning: 'hệ sinh thái', partOfSpeech: 'danh từ' },
      { kanji: '絶滅', kana: 'ぜつめつ', romaji: 'zetsumetsu', meaning: 'tuyệt chủng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '種', kana: 'しゅ', romaji: 'shu', meaning: 'loài (sinh vật)', partOfSpeech: 'danh từ' },
      { kanji: '生息', kana: 'せいそく', romaji: 'seisoku', meaning: 'sinh sống (động vật)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '繁殖', kana: 'はんしょく', romaji: 'hanshoku', meaning: 'sinh sản', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '保護', kana: 'ほご', romaji: 'hogo', meaning: 'bảo vệ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '保全', kana: 'ほぜん', romaji: 'hozen', meaning: 'bảo tồn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '森林伐採', kana: 'しんりんばっさい', romaji: 'shinrin bassai', meaning: 'phá rừng', partOfSpeech: 'danh từ' },
      { kanji: '砂漠化', kana: 'さばくか', romaji: 'sabakuka', meaning: 'sa mạc hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '海面上昇', kana: 'かいめんじょうしょう', romaji: 'kaimen jōshō', meaning: 'mực nước biển dâng', partOfSpeech: 'danh từ' },
      { kanji: '氷河', kana: 'ひょうが', romaji: 'hyōga', meaning: 'sông băng', partOfSpeech: 'danh từ' },
      { kanji: '融解', kana: 'ゆうかい', romaji: 'yūkai', meaning: 'tan chảy', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '異常気象', kana: 'いじょうきしょう', romaji: 'ijō kishō', meaning: 'thời tiết cực đoan', partOfSpeech: 'danh từ' },
      { kanji: '干ばつ', kana: 'かんばつ', romaji: 'kanbatsu', meaning: 'hạn hán', partOfSpeech: 'danh từ' },
      { kanji: '豪雨', kana: 'ごうう', romaji: 'gōu', meaning: 'mưa lớn', partOfSpeech: 'danh từ' },
      { kanji: '猛暑', kana: 'もうしょ', romaji: 'mōsho', meaning: 'nắng nóng gay gắt', partOfSpeech: 'danh từ' },
      { kanji: '酷暑', kana: 'こくしょ', romaji: 'kokusho', meaning: 'nóng dữ dội', partOfSpeech: 'danh từ' },
      { kanji: '寒波', kana: 'かんぱ', romaji: 'kanpa', meaning: 'đợt rét đậm', partOfSpeech: 'danh từ' },
      { kanji: '熱波', kana: 'ねっぱ', romaji: 'neppa', meaning: 'đợt nắng nóng', partOfSpeech: 'danh từ' },
    ],
  },
];
