// Bổ sung từ vựng N5–N1 để ôn thi — tự soạn tay (không auto-scrape), tránh lặp
// lỗi tiếng Anh/rác của jlpt-vocab-gap-fill.data.ts (đã tắt, xem seed-jlpt-expand.ts).
// lessonNumber mới, không đụng dải đã dùng: N5 205–209, N4 215–219, N3 317–321,
// N2 420–424, N1 524–528.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_REVIEW_BOOST: JlptVocabUnit[] = [
  // ─────────────────────────────── N5 ───────────────────────────────
  {
    lessonNumber: 205,
    jlptLevel: 'N5',
    words: [
      { kanji: '赤い', kana: 'あかい', romaji: 'akai', meaning: 'đỏ', partOfSpeech: 'tính từ i' },
      { kanji: '白い', kana: 'しろい', romaji: 'shiroi', meaning: 'trắng', partOfSpeech: 'tính từ i' },
      { kanji: '黒い', kana: 'くろい', romaji: 'kuroi', meaning: 'đen', partOfSpeech: 'tính từ i' },
      { kanji: '緑', kana: 'みどり', romaji: 'midori', meaning: 'màu xanh lá', partOfSpeech: 'danh từ' },
      { kanji: '紫', kana: 'むらさき', romaji: 'murasaki', meaning: 'màu tím', partOfSpeech: 'danh từ' },
      { kanji: '空', kana: 'そら', romaji: 'sora', meaning: 'bầu trời', partOfSpeech: 'danh từ' },
      { kanji: '海', kana: 'うみ', romaji: 'umi', meaning: 'biển', partOfSpeech: 'danh từ' },
      { kanji: '山', kana: 'やま', romaji: 'yama', meaning: 'núi', partOfSpeech: 'danh từ' },
      { kanji: '川', kana: 'かわ', romaji: 'kawa', meaning: 'sông', partOfSpeech: 'danh từ' },
      { kanji: '雨', kana: 'あめ', romaji: 'ame', meaning: 'mưa', partOfSpeech: 'danh từ' },
      { kanji: '雪', kana: 'ゆき', romaji: 'yuki', meaning: 'tuyết', partOfSpeech: 'danh từ' },
      { kanji: '風', kana: 'かぜ', romaji: 'kaze', meaning: 'gió', partOfSpeech: 'danh từ' },
      { kanji: '目', kana: 'め', romaji: 'me', meaning: 'mắt', partOfSpeech: 'danh từ' },
      { kanji: '口', kana: 'くち', romaji: 'kuchi', meaning: 'miệng', partOfSpeech: 'danh từ' },
      { kanji: '足', kana: 'あし', romaji: 'ashi', meaning: 'chân', partOfSpeech: 'danh từ' },
      { kanji: '頭', kana: 'あたま', romaji: 'atama', meaning: 'đầu', partOfSpeech: 'danh từ' },
      { kanji: '髪', kana: 'かみ', romaji: 'kami', meaning: 'tóc', partOfSpeech: 'danh từ' },
      { kanji: '弱い', kana: 'よわい', romaji: 'yowai', meaning: 'yếu', partOfSpeech: 'tính từ i' },
      { kanji: '強い', kana: 'つよい', romaji: 'tsuyoi', meaning: 'mạnh', partOfSpeech: 'tính từ i' },
      { kanji: '眠い', kana: 'ねむい', romaji: 'nemui', meaning: 'buồn ngủ', partOfSpeech: 'tính từ i' },
    ],
  },
  {
    lessonNumber: 206,
    jlptLevel: 'N5',
    words: [
      { kanji: '起きます', kana: 'おきます', romaji: 'okimasu', meaning: 'thức dậy', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '寝ます', kana: 'ねます', romaji: 'nemasu', meaning: 'đi ngủ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '洗います', kana: 'あらいます', romaji: 'araimasu', meaning: 'rửa, giặt', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '掃除します', kana: 'そうじします', romaji: 'sōji shimasu', meaning: 'dọn dẹp', partOfSpeech: 'động từ する' },
      { kanji: '洗濯します', kana: 'せんたくします', romaji: 'sentaku shimasu', meaning: 'giặt đồ', partOfSpeech: 'động từ する' },
      { kanji: '料理します', kana: 'りょうりします', romaji: 'ryōri shimasu', meaning: 'nấu ăn', partOfSpeech: 'động từ する' },
      { kanji: '運転します', kana: 'うんてんします', romaji: 'unten shimasu', meaning: 'lái xe', partOfSpeech: 'động từ する' },
      { kanji: '散歩します', kana: 'さんぽします', romaji: 'sanpo shimasu', meaning: 'đi dạo', partOfSpeech: 'động từ する' },
      { kanji: '泳ぎます', kana: 'およぎます', romaji: 'oyogimasu', meaning: 'bơi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '走ります', kana: 'はしります', romaji: 'hashirimasu', meaning: 'chạy', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '歩きます', kana: 'あるきます', romaji: 'arukimasu', meaning: 'đi bộ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '曲がります', kana: 'まがります', romaji: 'magarimasu', meaning: 'rẽ, quẹo', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '渡ります', kana: 'わたります', romaji: 'watarimasu', meaning: 'băng qua', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '止まります', kana: 'とまります', romaji: 'tomarimasu', meaning: 'dừng lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '開きます', kana: 'あきます', romaji: 'akimasu', meaning: 'mở (tự động)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '閉まります', kana: 'しまります', romaji: 'shimarimasu', meaning: 'đóng (tự động)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '壊れます', kana: 'こわれます', romaji: 'kowaremasu', meaning: 'hỏng, vỡ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '消えます', kana: 'きえます', romaji: 'kiemasu', meaning: 'tắt, biến mất', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '付きます', kana: 'つきます', romaji: 'tsukimasu', meaning: 'bật lên, gắn vào', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '入れます', kana: 'いれます', romaji: 'iremasu', meaning: 'cho vào', partOfSpeech: 'động từ nhóm 2' },
    ],
  },
  {
    lessonNumber: 207,
    jlptLevel: 'N5',
    words: [
      { kanji: '父', kana: 'ちち', romaji: 'chichi', meaning: 'bố (của tôi)', partOfSpeech: 'danh từ' },
      { kanji: '母', kana: 'はは', romaji: 'haha', meaning: 'mẹ (của tôi)', partOfSpeech: 'danh từ' },
      { kanji: 'お父さん', kana: 'おとうさん', romaji: 'otōsan', meaning: 'bố (người khác/gọi trực tiếp)', partOfSpeech: 'danh từ' },
      { kanji: 'お母さん', kana: 'おかあさん', romaji: 'okāsan', meaning: 'mẹ (người khác/gọi trực tiếp)', partOfSpeech: 'danh từ' },
      { kanji: '兄', kana: 'あに', romaji: 'ani', meaning: 'anh trai (của tôi)', partOfSpeech: 'danh từ' },
      { kanji: '姉', kana: 'あね', romaji: 'ane', meaning: 'chị gái (của tôi)', partOfSpeech: 'danh từ' },
      { kanji: '弟', kana: 'おとうと', romaji: 'otōto', meaning: 'em trai', partOfSpeech: 'danh từ' },
      { kanji: '妹', kana: 'いもうと', romaji: 'imōto', meaning: 'em gái', partOfSpeech: 'danh từ' },
      { kanji: '家族', kana: 'かぞく', romaji: 'kazoku', meaning: 'gia đình', partOfSpeech: 'danh từ' },
      { kanji: '朝ごはん', kana: 'あさごはん', romaji: 'asagohan', meaning: 'bữa sáng', partOfSpeech: 'danh từ' },
      { kanji: '昼ごはん', kana: 'ひるごはん', romaji: 'hirugohan', meaning: 'bữa trưa', partOfSpeech: 'danh từ' },
      { kanji: '晩ごはん', kana: 'ばんごはん', romaji: 'bangohan', meaning: 'bữa tối', partOfSpeech: 'danh từ' },
      { kanji: '果物', kana: 'くだもの', romaji: 'kudamono', meaning: 'hoa quả', partOfSpeech: 'danh từ' },
      { kanji: '卵', kana: 'たまご', romaji: 'tamago', meaning: 'trứng', partOfSpeech: 'danh từ' },
      { kanji: '魚', kana: 'さかな', romaji: 'sakana', meaning: 'cá', partOfSpeech: 'danh từ' },
      { kanji: 'パン', kana: 'パン', romaji: 'pan', meaning: 'bánh mì', partOfSpeech: 'danh từ' },
      { kanji: '砂糖', kana: 'さとう', romaji: 'satō', meaning: 'đường (gia vị)', partOfSpeech: 'danh từ' },
      { kanji: '塩', kana: 'しお', romaji: 'shio', meaning: 'muối', partOfSpeech: 'danh từ' },
      { kanji: '醤油', kana: 'しょうゆ', romaji: 'shōyu', meaning: 'nước tương', partOfSpeech: 'danh từ' },
      { kanji: '味', kana: 'あじ', romaji: 'aji', meaning: 'vị, hương vị', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 208,
    jlptLevel: 'N5',
    words: [
      { kanji: '駅', kana: 'えき', romaji: 'eki', meaning: 'nhà ga', partOfSpeech: 'danh từ' },
      { kanji: '空港', kana: 'くうこう', romaji: 'kūkō', meaning: 'sân bay', partOfSpeech: 'danh từ' },
      { kanji: '病院', kana: 'びょういん', romaji: 'byōin', meaning: 'bệnh viện', partOfSpeech: 'danh từ' },
      { kanji: '銀行', kana: 'ぎんこう', romaji: 'ginkō', meaning: 'ngân hàng', partOfSpeech: 'danh từ' },
      { kanji: '郵便局', kana: 'ゆうびんきょく', romaji: 'yūbinkyoku', meaning: 'bưu điện', partOfSpeech: 'danh từ' },
      { kanji: '公園', kana: 'こうえん', romaji: 'kōen', meaning: 'công viên', partOfSpeech: 'danh từ' },
      { kanji: '教室', kana: 'きょうしつ', romaji: 'kyōshitsu', meaning: 'phòng học', partOfSpeech: 'danh từ' },
      { kanji: '橋', kana: 'はし', romaji: 'hashi', meaning: 'cây cầu', partOfSpeech: 'danh từ' },
      { kanji: '道', kana: 'みち', romaji: 'michi', meaning: 'con đường', partOfSpeech: 'danh từ' },
      { kanji: '信号', kana: 'しんごう', romaji: 'shingō', meaning: 'đèn giao thông', partOfSpeech: 'danh từ' },
      { kanji: '右', kana: 'みぎ', romaji: 'migi', meaning: 'bên phải', partOfSpeech: 'danh từ' },
      { kanji: '左', kana: 'ひだり', romaji: 'hidari', meaning: 'bên trái', partOfSpeech: 'danh từ' },
      { kanji: '近く', kana: 'ちかく', romaji: 'chikaku', meaning: 'gần đây', partOfSpeech: 'danh từ' },
      { kanji: '遠く', kana: 'とおく', romaji: 'tōku', meaning: 'nơi xa', partOfSpeech: 'danh từ' },
      { kanji: '隣', kana: 'となり', romaji: 'tonari', meaning: 'bên cạnh', partOfSpeech: 'danh từ' },
      { kanji: '間', kana: 'あいだ', romaji: 'aida', meaning: 'khoảng giữa', partOfSpeech: 'danh từ' },
      { kanji: '中', kana: 'なか', romaji: 'naka', meaning: 'bên trong', partOfSpeech: 'danh từ' },
      { kanji: '外', kana: 'そと', romaji: 'soto', meaning: 'bên ngoài', partOfSpeech: 'danh từ' },
      { kanji: '上', kana: 'うえ', romaji: 'ue', meaning: 'phía trên', partOfSpeech: 'danh từ' },
      { kanji: '下', kana: 'した', romaji: 'shita', meaning: 'phía dưới', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 209,
    jlptLevel: 'N5',
    words: [
      { kanji: '暑い', kana: 'あつい', romaji: 'atsui', meaning: 'nóng (thời tiết)', partOfSpeech: 'tính từ i' },
      { kanji: '寒い', kana: 'さむい', romaji: 'samui', meaning: 'lạnh (thời tiết)', partOfSpeech: 'tính từ i' },
      { kanji: '涼しい', kana: 'すずしい', romaji: 'suzushii', meaning: 'mát mẻ', partOfSpeech: 'tính từ i' },
      { kanji: '暖かい', kana: 'あたたかい', romaji: 'atatakai', meaning: 'ấm áp', partOfSpeech: 'tính từ i' },
      { kanji: '忙しい', kana: 'いそがしい', romaji: 'isogashii', meaning: 'bận rộn', partOfSpeech: 'tính từ i' },
      { kanji: '暇', kana: 'ひま', romaji: 'hima', meaning: 'rảnh rỗi', partOfSpeech: 'tính từ na' },
      { kanji: '楽しい', kana: 'たのしい', romaji: 'tanoshii', meaning: 'vui vẻ', partOfSpeech: 'tính từ i' },
      { kanji: '面白い', kana: 'おもしろい', romaji: 'omoshiroi', meaning: 'thú vị', partOfSpeech: 'tính từ i' },
      { kanji: 'つまらない', kana: 'つまらない', romaji: 'tsumaranai', meaning: 'nhàm chán', partOfSpeech: 'tính từ i' },
      { kanji: '難しい', kana: 'むずかしい', romaji: 'muzukashii', meaning: 'khó', partOfSpeech: 'tính từ i' },
      { kanji: '易しい', kana: 'やさしい', romaji: 'yasashii', meaning: 'dễ, hiền lành', partOfSpeech: 'tính từ i' },
      { kanji: '軽い', kana: 'かるい', romaji: 'karui', meaning: 'nhẹ', partOfSpeech: 'tính từ i' },
      { kanji: '重い', kana: 'おもい', romaji: 'omoi', meaning: 'nặng', partOfSpeech: 'tính từ i' },
      { kanji: '高い', kana: 'たかい', romaji: 'takai', meaning: 'cao, đắt', partOfSpeech: 'tính từ i' },
      { kanji: '安い', kana: 'やすい', romaji: 'yasui', meaning: 'rẻ', partOfSpeech: 'tính từ i' },
      { kanji: '新しい', kana: 'あたらしい', romaji: 'atarashii', meaning: 'mới', partOfSpeech: 'tính từ i' },
      { kanji: '古い', kana: 'ふるい', romaji: 'furui', meaning: 'cũ', partOfSpeech: 'tính từ i' },
      { kanji: '狭い', kana: 'せまい', romaji: 'semai', meaning: 'chật, hẹp', partOfSpeech: 'tính từ i' },
      { kanji: '広い', kana: 'ひろい', romaji: 'hiroi', meaning: 'rộng', partOfSpeech: 'tính từ i' },
      { kanji: '汚い', kana: 'きたない', romaji: 'kitanai', meaning: 'bẩn', partOfSpeech: 'tính từ i' },
    ],
  },

  // ─────────────────────────────── N4 ───────────────────────────────
  {
    lessonNumber: 215,
    jlptLevel: 'N4',
    words: [
      { kanji: '約束します', kana: 'やくそくします', romaji: 'yakusoku shimasu', meaning: 'hứa hẹn', partOfSpeech: 'động từ する' },
      { kanji: '案内します', kana: 'あんないします', romaji: 'annai shimasu', meaning: 'hướng dẫn, dẫn đường', partOfSpeech: 'động từ する' },
      { kanji: '説明します', kana: 'せつめいします', romaji: 'setsumei shimasu', meaning: 'giải thích', partOfSpeech: 'động từ する' },
      { kanji: '紹介します', kana: 'しょうかいします', romaji: 'shōkai shimasu', meaning: 'giới thiệu', partOfSpeech: 'động từ する' },
      { kanji: '招待します', kana: 'しょうたいします', romaji: 'shōtai shimasu', meaning: 'mời (dự tiệc...)', partOfSpeech: 'động từ する' },
      { kanji: '準備します', kana: 'じゅんびします', romaji: 'junbi shimasu', meaning: 'chuẩn bị', partOfSpeech: 'động từ する' },
      { kanji: '練習します', kana: 'れんしゅうします', romaji: 'renshū shimasu', meaning: 'luyện tập', partOfSpeech: 'động từ する' },
      { kanji: '経験します', kana: 'けいけんします', romaji: 'keiken shimasu', meaning: 'trải nghiệm', partOfSpeech: 'động từ する' },
      { kanji: '我慢します', kana: 'がまんします', romaji: 'gaman shimasu', meaning: 'chịu đựng, nhẫn nhịn', partOfSpeech: 'động từ する' },
      { kanji: '注意します', kana: 'ちゅういします', romaji: 'chūi shimasu', meaning: 'chú ý, nhắc nhở', partOfSpeech: 'động từ する' },
      { kanji: '心配します', kana: 'しんぱいします', romaji: 'shinpai shimasu', meaning: 'lo lắng', partOfSpeech: 'động từ する' },
      { kanji: '感謝します', kana: 'かんしゃします', romaji: 'kansha shimasu', meaning: 'biết ơn', partOfSpeech: 'động từ する' },
      { kanji: '成功します', kana: 'せいこうします', romaji: 'seikō shimasu', meaning: 'thành công', partOfSpeech: 'động từ する' },
      { kanji: '失敗します', kana: 'しっぱいします', romaji: 'shippai shimasu', meaning: 'thất bại', partOfSpeech: 'động từ する' },
      { kanji: '後悔します', kana: 'こうかいします', romaji: 'kōkai shimasu', meaning: 'hối hận', partOfSpeech: 'động từ する' },
      { kanji: '我々', kana: 'われわれ', romaji: 'wareware', meaning: 'chúng ta (trang trọng)', partOfSpeech: 'đại từ' },
      { kanji: '互いに', kana: 'たがいに', romaji: 'tagai ni', meaning: 'lẫn nhau', partOfSpeech: 'phó từ' },
      { kanji: '一人で', kana: 'ひとりで', romaji: 'hitori de', meaning: 'một mình', partOfSpeech: 'phó từ' },
      { kanji: '自分で', kana: 'じぶんで', romaji: 'jibun de', meaning: 'tự mình', partOfSpeech: 'phó từ' },
      { kanji: 'お互い', kana: 'おたがい', romaji: 'otagai', meaning: 'lẫn nhau (danh từ)', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 216,
    jlptLevel: 'N4',
    words: [
      { kanji: '機会', kana: 'きかい', romaji: 'kikai', meaning: 'cơ hội', partOfSpeech: 'danh từ' },
      { kanji: '機械', kana: 'きかい', romaji: 'kikai', meaning: 'máy móc', partOfSpeech: 'danh từ' },
      { kanji: '道具', kana: 'どうぐ', romaji: 'dōgu', meaning: 'dụng cụ, công cụ', partOfSpeech: 'danh từ' },
      { kanji: '材料', kana: 'ざいりょう', romaji: 'zairyō', meaning: 'nguyên liệu', partOfSpeech: 'danh từ' },
      { kanji: '種類', kana: 'しゅるい', romaji: 'shurui', meaning: 'chủng loại', partOfSpeech: 'danh từ' },
      { kanji: '性格', kana: 'せいかく', romaji: 'seikaku', meaning: 'tính cách', partOfSpeech: 'danh từ' },
      { kanji: '習慣', kana: 'しゅうかん', romaji: 'shūkan', meaning: 'thói quen', partOfSpeech: 'danh từ' },
      { kanji: '伝統', kana: 'でんとう', romaji: 'dentō', meaning: 'truyền thống', partOfSpeech: 'danh từ' },
      { kanji: '文化', kana: 'ぶんか', romaji: 'bunka', meaning: 'văn hóa', partOfSpeech: 'danh từ' },
      { kanji: '宗教', kana: 'しゅうきょう', romaji: 'shūkyō', meaning: 'tôn giáo', partOfSpeech: 'danh từ' },
      { kanji: '規則', kana: 'きそく', romaji: 'kisoku', meaning: 'quy tắc', partOfSpeech: 'danh từ' },
      { kanji: '法律', kana: 'ほうりつ', romaji: 'hōritsu', meaning: 'pháp luật', partOfSpeech: 'danh từ' },
      { kanji: '税金', kana: 'ぜいきん', romaji: 'zeikin', meaning: 'thuế', partOfSpeech: 'danh từ' },
      { kanji: '給料', kana: 'きゅうりょう', romaji: 'kyūryō', meaning: 'tiền lương', partOfSpeech: 'danh từ' },
      { kanji: '価格', kana: 'かかく', romaji: 'kakaku', meaning: 'giá cả', partOfSpeech: 'danh từ' },
      { kanji: '値段', kana: 'ねだん', romaji: 'nedan', meaning: 'giá tiền', partOfSpeech: 'danh từ' },
      { kanji: '品質', kana: 'ひんしつ', romaji: 'hinshitsu', meaning: 'chất lượng', partOfSpeech: 'danh từ' },
      { kanji: '欠点', kana: 'けってん', romaji: 'ketten', meaning: 'khuyết điểm', partOfSpeech: 'danh từ' },
      { kanji: '長所', kana: 'ちょうしょ', romaji: 'chōsho', meaning: 'ưu điểm', partOfSpeech: 'danh từ' },
      { kanji: '短所', kana: 'たんしょ', romaji: 'tansho', meaning: 'nhược điểm', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 217,
    jlptLevel: 'N4',
    words: [
      { kanji: '育てます', kana: 'そだてます', romaji: 'sodatemasu', meaning: 'nuôi dưỡng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '育ちます', kana: 'そだちます', romaji: 'sodachimasu', meaning: 'lớn lên', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '増えます', kana: 'ふえます', romaji: 'fuemasu', meaning: 'tăng lên', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '減ります', kana: 'へります', romaji: 'herimasu', meaning: 'giảm đi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '変わります', kana: 'かわります', romaji: 'kawarimasu', meaning: 'thay đổi (tự động)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '変えます', kana: 'かえます', romaji: 'kaemasu', meaning: 'thay đổi (tha động)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '続けます', kana: 'つづけます', romaji: 'tsuzukemasu', meaning: 'tiếp tục (làm gì)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '続きます', kana: 'つづきます', romaji: 'tsuzukimasu', meaning: 'kéo dài, tiếp diễn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '決めます', kana: 'きめます', romaji: 'kimemasu', meaning: 'quyết định', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '決まります', kana: 'きまります', romaji: 'kimarimasu', meaning: 'được quyết định', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '比べます', kana: 'くらべます', romaji: 'kurabemasu', meaning: 'so sánh', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '選びます', kana: 'えらびます', romaji: 'erabimasu', meaning: 'lựa chọn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '進みます', kana: 'すすみます', romaji: 'susumimasu', meaning: 'tiến lên, tiến triển', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '遅れます', kana: 'おくれます', romaji: 'okuremasu', meaning: 'bị trễ, muộn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '間に合います', kana: 'まにあいます', romaji: 'ma ni aimasu', meaning: 'kịp giờ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '慣れます', kana: 'なれます', romaji: 'naremasu', meaning: 'quen với', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '足ります', kana: 'たります', romaji: 'tarimasu', meaning: 'đủ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '足りません', kana: 'たりません', romaji: 'tarimasen', meaning: 'không đủ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '役に立ちます', kana: 'やくにたちます', romaji: 'yaku ni tachimasu', meaning: 'có ích, hữu dụng', partOfSpeech: 'cụm động từ' },
      { kanji: '気がつきます', kana: 'きがつきます', romaji: 'ki ga tsukimasu', meaning: 'nhận ra, để ý thấy', partOfSpeech: 'cụm động từ' },
    ],
  },
  {
    lessonNumber: 218,
    jlptLevel: 'N4',
    words: [
      { kanji: '若い', kana: 'わかい', romaji: 'wakai', meaning: 'trẻ', partOfSpeech: 'tính từ i' },
      { kanji: '賢い', kana: 'かしこい', romaji: 'kashikoi', meaning: 'thông minh', partOfSpeech: 'tính từ i' },
      { kanji: '正直な', kana: 'しょうじきな', romaji: 'shōjiki na', meaning: 'thành thật', partOfSpeech: 'tính từ na' },
      { kanji: '素直な', kana: 'すなおな', romaji: 'sunao na', meaning: 'ngoan ngoãn, thẳng thắn', partOfSpeech: 'tính từ na' },
      { kanji: '真面目な', kana: 'まじめな', romaji: 'majime na', meaning: 'nghiêm túc, chăm chỉ', partOfSpeech: 'tính từ na' },
      { kanji: '熱心な', kana: 'ねっしんな', romaji: 'nesshin na', meaning: 'nhiệt tình, hăng hái', partOfSpeech: 'tính từ na' },
      { kanji: '積極的な', kana: 'せっきょくてきな', romaji: 'sekkyokuteki na', meaning: 'tích cực, chủ động', partOfSpeech: 'tính từ na' },
      { kanji: '消極的な', kana: 'しょうきょくてきな', romaji: 'shōkyokuteki na', meaning: 'tiêu cực, thụ động', partOfSpeech: 'tính từ na' },
      { kanji: '親切な', kana: 'しんせつな', romaji: 'shinsetsu na', meaning: 'tốt bụng', partOfSpeech: 'tính từ na' },
      { kanji: '丁寧な', kana: 'ていねいな', romaji: 'teinei na', meaning: 'lịch sự, cẩn thận', partOfSpeech: 'tính từ na' },
      { kanji: '失礼な', kana: 'しつれいな', romaji: 'shitsurei na', meaning: 'thất lễ', partOfSpeech: 'tính từ na' },
      { kanji: '自由な', kana: 'じゆうな', romaji: 'jiyū na', meaning: 'tự do', partOfSpeech: 'tính từ na' },
      { kanji: '複雑な', kana: 'ふくざつな', romaji: 'fukuzatsu na', meaning: 'phức tạp', partOfSpeech: 'tính từ na' },
      { kanji: '単純な', kana: 'たんじゅんな', romaji: 'tanjun na', meaning: 'đơn giản', partOfSpeech: 'tính từ na' },
      { kanji: '十分な', kana: 'じゅうぶんな', romaji: 'jūbun na', meaning: 'đầy đủ', partOfSpeech: 'tính từ na' },
      { kanji: '不便な', kana: 'ふべんな', romaji: 'fuben na', meaning: 'bất tiện', partOfSpeech: 'tính từ na' },
      { kanji: '便利な', kana: 'べんりな', romaji: 'benri na', meaning: 'tiện lợi', partOfSpeech: 'tính từ na' },
      { kanji: '安全な', kana: 'あんぜんな', romaji: 'anzen na', meaning: 'an toàn', partOfSpeech: 'tính từ na' },
      { kanji: '危険な', kana: 'きけんな', romaji: 'kiken na', meaning: 'nguy hiểm', partOfSpeech: 'tính từ na' },
      { kanji: '盛んな', kana: 'さかんな', romaji: 'sakan na', meaning: 'thịnh hành, sôi nổi', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 219,
    jlptLevel: 'N4',
    words: [
      { kanji: '確かに', kana: 'たしかに', romaji: 'tashika ni', meaning: 'quả thực, chắc chắn', partOfSpeech: 'phó từ' },
      { kanji: '実は', kana: 'じつは', romaji: 'jitsu wa', meaning: 'thật ra', partOfSpeech: 'phó từ' },
      { kanji: '特に', kana: 'とくに', romaji: 'toku ni', meaning: 'đặc biệt là', partOfSpeech: 'phó từ' },
      { kanji: '必ず', kana: 'かならず', romaji: 'kanarazu', meaning: 'nhất định', partOfSpeech: 'phó từ' },
      { kanji: 'なるべく', kana: 'なるべく', romaji: 'narubeku', meaning: 'càng nhiều càng tốt', partOfSpeech: 'phó từ' },
      { kanji: 'できるだけ', kana: 'できるだけ', romaji: 'dekiru dake', meaning: 'hết mức có thể', partOfSpeech: 'phó từ' },
      { kanji: 'そのまま', kana: 'そのまま', romaji: 'sono mama', meaning: 'cứ để nguyên như vậy', partOfSpeech: 'phó từ' },
      { kanji: 'だんだん', kana: 'だんだん', romaji: 'dandan', meaning: 'dần dần', partOfSpeech: 'phó từ' },
      { kanji: '急に', kana: 'きゅうに', romaji: 'kyū ni', meaning: 'đột nhiên', partOfSpeech: 'phó từ' },
      { kanji: 'すぐに', kana: 'すぐに', romaji: 'sugu ni', meaning: 'ngay lập tức', partOfSpeech: 'phó từ' },
      { kanji: 'しばらく', kana: 'しばらく', romaji: 'shibaraku', meaning: 'một lúc, một thời gian', partOfSpeech: 'phó từ' },
      { kanji: 'いつか', kana: 'いつか', romaji: 'itsuka', meaning: 'một ngày nào đó', partOfSpeech: 'phó từ' },
      { kanji: 'たまに', kana: 'たまに', romaji: 'tama ni', meaning: 'thỉnh thoảng', partOfSpeech: 'phó từ' },
      { kanji: '二度と', kana: 'にどと', romaji: 'nido to', meaning: 'không bao giờ nữa (+ phủ định)', partOfSpeech: 'phó từ' },
      { kanji: 'やっと', kana: 'やっと', romaji: 'yatto', meaning: 'cuối cùng cũng', partOfSpeech: 'phó từ' },
      { kanji: '結局', kana: 'けっきょく', romaji: 'kekkyoku', meaning: 'rốt cuộc', partOfSpeech: 'phó từ' },
      { kanji: '一体', kana: 'いったい', romaji: 'ittai', meaning: 'rốt cuộc là (nhấn mạnh câu hỏi)', partOfSpeech: 'phó từ' },
      { kanji: 'もちろん', kana: 'もちろん', romaji: 'mochiron', meaning: 'tất nhiên', partOfSpeech: 'phó từ' },
      { kanji: 'できれば', kana: 'できれば', romaji: 'dekireba', meaning: 'nếu có thể', partOfSpeech: 'phó từ' },
      { kanji: 'もし', kana: 'もし', romaji: 'moshi', meaning: 'nếu (giả định)', partOfSpeech: 'phó từ' },
    ],
  },

  // ─────────────────────────────── N3 ───────────────────────────────
  {
    lessonNumber: 317,
    jlptLevel: 'N3',
    words: [
      { kanji: '契約', kana: 'けいやく', romaji: 'keiyaku', meaning: 'hợp đồng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '手続き', kana: 'てつづき', romaji: 'tetsuzuki', meaning: 'thủ tục', partOfSpeech: 'danh từ' },
      { kanji: '申請', kana: 'しんせい', romaji: 'shinsei', meaning: 'đơn xin, đăng ký', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '提出', kana: 'ていしゅつ', romaji: 'teishutsu', meaning: 'nộp (hồ sơ)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '承認', kana: 'しょうにん', romaji: 'shōnin', meaning: 'phê chuẩn, chấp thuận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '許可', kana: 'きょか', romaji: 'kyoka', meaning: 'sự cho phép', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '禁止', kana: 'きんし', romaji: 'kinshi', meaning: 'cấm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '義務', kana: 'ぎむ', romaji: 'gimu', meaning: 'nghĩa vụ', partOfSpeech: 'danh từ' },
      { kanji: '権利', kana: 'けんり', romaji: 'kenri', meaning: 'quyền lợi', partOfSpeech: 'danh từ' },
      { kanji: '責任者', kana: 'せきにんしゃ', romaji: 'sekininsha', meaning: 'người chịu trách nhiệm', partOfSpeech: 'danh từ' },
      { kanji: '担当者', kana: 'たんとうしゃ', romaji: 'tantōsha', meaning: 'người phụ trách', partOfSpeech: 'danh từ' },
      { kanji: '窓口', kana: 'まどぐち', romaji: 'madoguchi', meaning: 'quầy tiếp nhận', partOfSpeech: 'danh từ' },
      { kanji: '受付', kana: 'うけつけ', romaji: 'uketsuke', meaning: 'lễ tân, tiếp nhận', partOfSpeech: 'danh từ' },
      { kanji: '面接', kana: 'めんせつ', romaji: 'mensetsu', meaning: 'phỏng vấn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '採用', kana: 'さいよう', romaji: 'saiyō', meaning: 'tuyển dụng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '応募', kana: 'おうぼ', romaji: 'ōbo', meaning: 'ứng tuyển, đăng ký tham gia', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '志望', kana: 'しぼう', romaji: 'shibō', meaning: 'nguyện vọng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '目標', kana: 'もくひょう', romaji: 'mokuhyō', meaning: 'mục tiêu', partOfSpeech: 'danh từ' },
      { kanji: '計画', kana: 'けいかく', romaji: 'keikaku', meaning: 'kế hoạch', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '予定', kana: 'よてい', romaji: 'yotei', meaning: 'dự định, lịch trình', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 318,
    jlptLevel: 'N3',
    words: [
      { kanji: '感動', kana: 'かんどう', romaji: 'kandō', meaning: 'sự cảm động', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '興味', kana: 'きょうみ', romaji: 'kyōmi', meaning: 'sự hứng thú', partOfSpeech: 'danh từ' },
      { kanji: '関心', kana: 'かんしん', romaji: 'kanshin', meaning: 'sự quan tâm', partOfSpeech: 'danh từ' },
      { kanji: '不満', kana: 'ふまん', romaji: 'fuman', meaning: 'sự bất mãn', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '満足', kana: 'まんぞく', romaji: 'manzoku', meaning: 'sự hài lòng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '緊張', kana: 'きんちょう', romaji: 'kinchō', meaning: 'sự căng thẳng, hồi hộp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '安心', kana: 'あんしん', romaji: 'anshin', meaning: 'sự yên tâm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '恐怖', kana: 'きょうふ', romaji: 'kyōfu', meaning: 'nỗi sợ hãi', partOfSpeech: 'danh từ' },
      { kanji: '孤独', kana: 'こどく', romaji: 'kodoku', meaning: 'sự cô đơn', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '幸せ', kana: 'しあわせ', romaji: 'shiawase', meaning: 'hạnh phúc', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '喜び', kana: 'よろこび', romaji: 'yorokobi', meaning: 'niềm vui', partOfSpeech: 'danh từ' },
      { kanji: '怒り', kana: 'いかり', romaji: 'ikari', meaning: 'cơn giận', partOfSpeech: 'danh từ' },
      { kanji: '驚き', kana: 'おどろき', romaji: 'odoroki', meaning: 'sự ngạc nhiên', partOfSpeech: 'danh từ' },
      { kanji: '疑い', kana: 'うたがい', romaji: 'utagai', meaning: 'sự nghi ngờ', partOfSpeech: 'danh từ' },
      { kanji: '信頼', kana: 'しんらい', romaji: 'shinrai', meaning: 'sự tin cậy', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '尊敬', kana: 'そんけい', romaji: 'sonkei', meaning: 'sự tôn kính', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '嫉妬', kana: 'しっと', romaji: 'shitto', meaning: 'sự ghen tị', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '後悔', kana: 'こうかい', romaji: 'kōkai', meaning: 'sự hối hận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '感激', kana: 'かんげき', romaji: 'kangeki', meaning: 'sự xúc động mạnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '同情', kana: 'どうじょう', romaji: 'dōjō', meaning: 'sự đồng cảm', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 319,
    jlptLevel: 'N3',
    words: [
      { kanji: '運送', kana: 'うんそう', romaji: 'unsō', meaning: 'vận chuyển hàng hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '輸送', kana: 'ゆそう', romaji: 'yusō', meaning: 'vận tải', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '到着', kana: 'とうちゃく', romaji: 'tōchaku', meaning: 'đến nơi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '出発', kana: 'しゅっぱつ', romaji: 'shuppatsu', meaning: 'khởi hành', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '通過', kana: 'つうか', romaji: 'tsūka', meaning: 'đi ngang qua', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '渋滞', kana: 'じゅうたい', romaji: 'jūtai', meaning: 'tắc đường', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '事故', kana: 'じこ', romaji: 'jiko', meaning: 'tai nạn', partOfSpeech: 'danh từ' },
      { kanji: '故障', kana: 'こしょう', romaji: 'koshō', meaning: 'hỏng hóc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '修理', kana: 'しゅうり', romaji: 'shūri', meaning: 'sửa chữa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '点検', kana: 'てんけん', romaji: 'tenken', meaning: 'kiểm tra định kỳ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '交換', kana: 'こうかん', romaji: 'kōkan', meaning: 'trao đổi, thay thế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '返却', kana: 'へんきゃく', romaji: 'henkyaku', meaning: 'trả lại (đồ mượn)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '延長', kana: 'えんちょう', romaji: 'enchō', meaning: 'gia hạn, kéo dài', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '予約', kana: 'よやく', romaji: 'yoyaku', meaning: 'đặt trước', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '取り消し', kana: 'とりけし', romaji: 'torikeshi', meaning: 'hủy bỏ', partOfSpeech: 'danh từ' },
      { kanji: '変更', kana: 'へんこう', romaji: 'henkō', meaning: 'thay đổi (kế hoạch...)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '確認', kana: 'かくにん', romaji: 'kakunin', meaning: 'xác nhận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '連絡先', kana: 'れんらくさき', romaji: 'renrakusaki', meaning: 'thông tin liên lạc', partOfSpeech: 'danh từ' },
      { kanji: '住所', kana: 'じゅうしょ', romaji: 'jūsho', meaning: 'địa chỉ', partOfSpeech: 'danh từ' },
      { kanji: '氏名', kana: 'しめい', romaji: 'shimei', meaning: 'họ tên', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 320,
    jlptLevel: 'N3',
    words: [
      { kanji: '観察', kana: 'かんさつ', romaji: 'kansatsu', meaning: 'quan sát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発見', kana: 'はっけん', romaji: 'hakken', meaning: 'phát hiện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発明', kana: 'はつめい', romaji: 'hatsumei', meaning: 'phát minh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '実験', kana: 'じっけん', romaji: 'jikken', meaning: 'thí nghiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '研究', kana: 'けんきゅう', romaji: 'kenkyū', meaning: 'nghiên cứu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '調査', kana: 'ちょうさ', romaji: 'chōsa', meaning: 'điều tra, khảo sát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '分析', kana: 'ぶんせき', romaji: 'bunseki', meaning: 'phân tích', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '証明', kana: 'しょうめい', romaji: 'shōmei', meaning: 'chứng minh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '技術', kana: 'ぎじゅつ', romaji: 'gijutsu', meaning: 'kỹ thuật', partOfSpeech: 'danh từ' },
      { kanji: '知識', kana: 'ちしき', romaji: 'chishiki', meaning: 'kiến thức', partOfSpeech: 'danh từ' },
      { kanji: '能力', kana: 'のうりょく', romaji: 'nōryoku', meaning: 'năng lực', partOfSpeech: 'danh từ' },
      { kanji: '才能', kana: 'さいのう', romaji: 'sainō', meaning: 'tài năng', partOfSpeech: 'danh từ' },
      { kanji: '努力', kana: 'どりょく', romaji: 'doryoku', meaning: 'nỗ lực', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '工夫', kana: 'くふう', romaji: 'kufū', meaning: 'sự sáng tạo, tìm cách', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '改善', kana: 'かいぜん', romaji: 'kaizen', meaning: 'cải thiện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '進歩', kana: 'しんぽ', romaji: 'shinpo', meaning: 'tiến bộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発達', kana: 'はったつ', romaji: 'hattatsu', meaning: 'phát triển', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '普及', kana: 'ふきゅう', romaji: 'fukyū', meaning: 'phổ cập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '維持', kana: 'いじ', romaji: 'iji', meaning: 'duy trì', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '限界', kana: 'げんかい', romaji: 'genkai', meaning: 'giới hạn', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 321,
    jlptLevel: 'N3',
    words: [
      { kanji: '近所', kana: 'きんじょ', romaji: 'kinjo', meaning: 'hàng xóm, khu vực lân cận', partOfSpeech: 'danh từ' },
      { kanji: '地域', kana: 'ちいき', romaji: 'chiiki', meaning: 'khu vực, địa phương', partOfSpeech: 'danh từ' },
      { kanji: '田舎', kana: 'いなか', romaji: 'inaka', meaning: 'quê, nông thôn', partOfSpeech: 'danh từ' },
      { kanji: '都会', kana: 'とかい', romaji: 'tokai', meaning: 'đô thị, thành phố lớn', partOfSpeech: 'danh từ' },
      { kanji: '住民', kana: 'じゅうみん', romaji: 'jūmin', meaning: 'cư dân', partOfSpeech: 'danh từ' },
      { kanji: '人口', kana: 'じんこう', romaji: 'jinkō', meaning: 'dân số', partOfSpeech: 'danh từ' },
      { kanji: '高齢者', kana: 'こうれいしゃ', romaji: 'kōreisha', meaning: 'người cao tuổi', partOfSpeech: 'danh từ' },
      { kanji: '若者', kana: 'わかもの', romaji: 'wakamono', meaning: 'người trẻ', partOfSpeech: 'danh từ' },
      { kanji: '独身', kana: 'どくしん', romaji: 'dokushin', meaning: 'độc thân', partOfSpeech: 'danh từ' },
      { kanji: '夫婦', kana: 'ふうふ', romaji: 'fūfu', meaning: 'vợ chồng', partOfSpeech: 'danh từ' },
      { kanji: '育児', kana: 'いくじ', romaji: 'ikuji', meaning: 'nuôi con', partOfSpeech: 'danh từ' },
      { kanji: '介護', kana: 'かいご', romaji: 'kaigo', meaning: 'chăm sóc người già/bệnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '福祉', kana: 'ふくし', romaji: 'fukushi', meaning: 'phúc lợi xã hội', partOfSpeech: 'danh từ' },
      { kanji: 'ボランティア', kana: 'ボランティア', romaji: 'borantia', meaning: 'tình nguyện viên', partOfSpeech: 'danh từ' },
      { kanji: '寄付', kana: 'きふ', romaji: 'kifu', meaning: 'quyên góp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '募金', kana: 'ぼきん', romaji: 'bokin', meaning: 'gây quỹ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '災害', kana: 'さいがい', romaji: 'saigai', meaning: 'thiên tai', partOfSpeech: 'danh từ' },
      { kanji: '被害', kana: 'ひがい', romaji: 'higai', meaning: 'thiệt hại', partOfSpeech: 'danh từ' },
      { kanji: '避難', kana: 'ひなん', romaji: 'hinan', meaning: 'sơ tán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '救助', kana: 'きゅうじょ', romaji: 'kyūjo', meaning: 'cứu hộ', partOfSpeech: 'danh từ, động từ する' },
    ],
  },

  // ─────────────────────────────── N2 ───────────────────────────────
  {
    lessonNumber: 420,
    jlptLevel: 'N2',
    words: [
      { kanji: '経営', kana: 'けいえい', romaji: 'keiei', meaning: 'kinh doanh, điều hành', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '経費', kana: 'けいひ', romaji: 'keihi', meaning: 'chi phí', partOfSpeech: 'danh từ' },
      { kanji: '売上', kana: 'うりあげ', romaji: 'uriage', meaning: 'doanh thu', partOfSpeech: 'danh từ' },
      { kanji: '利益', kana: 'りえき', romaji: 'rieki', meaning: 'lợi nhuận', partOfSpeech: 'danh từ' },
      { kanji: '損失', kana: 'そんしつ', romaji: 'sonshitsu', meaning: 'tổn thất', partOfSpeech: 'danh từ' },
      { kanji: '倒産', kana: 'とうさん', romaji: 'tōsan', meaning: 'phá sản', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '合併', kana: 'がっぺい', romaji: 'gappei', meaning: 'sáp nhập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '投資', kana: 'とうし', romaji: 'tōshi', meaning: 'đầu tư', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '株式', kana: 'かぶしき', romaji: 'kabushiki', meaning: 'cổ phần', partOfSpeech: 'danh từ' },
      { kanji: '融資', kana: 'ゆうし', romaji: 'yūshi', meaning: 'cho vay vốn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '取引', kana: 'とりひき', romaji: 'torihiki', meaning: 'giao dịch', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '契約書', kana: 'けいやくしょ', romaji: 'keiyakusho', meaning: 'văn bản hợp đồng', partOfSpeech: 'danh từ' },
      { kanji: '請求書', kana: 'せいきゅうしょ', romaji: 'seikyūsho', meaning: 'hóa đơn (yêu cầu thanh toán)', partOfSpeech: 'danh từ' },
      { kanji: '領収書', kana: 'りょうしゅうしょ', romaji: 'ryōshūsho', meaning: 'biên lai, hóa đơn đã trả', partOfSpeech: 'danh từ' },
      { kanji: '見積もり', kana: 'みつもり', romaji: 'mitsumori', meaning: 'bản báo giá', partOfSpeech: 'danh từ' },
      { kanji: '発注', kana: 'はっちゅう', romaji: 'hatchū', meaning: 'đặt hàng (bên mua)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '受注', kana: 'じゅちゅう', romaji: 'juchū', meaning: 'nhận đơn hàng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '納品', kana: 'のうひん', romaji: 'nōhin', meaning: 'giao hàng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '在庫', kana: 'ざいこ', romaji: 'zaiko', meaning: 'hàng tồn kho', partOfSpeech: 'danh từ' },
      { kanji: '倉庫', kana: 'そうこ', romaji: 'sōko', meaning: 'nhà kho', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 421,
    jlptLevel: 'N2',
    words: [
      { kanji: '慎重', kana: 'しんちょう', romaji: 'shinchō', meaning: 'thận trọng', partOfSpeech: 'tính từ na' },
      { kanji: '大胆', kana: 'だいたん', romaji: 'daitan', meaning: 'táo bạo, gan dạ', partOfSpeech: 'tính từ na' },
      { kanji: '冷静', kana: 'れいせい', romaji: 'reisei', meaning: 'bình tĩnh', partOfSpeech: 'tính từ na' },
      { kanji: '率直', kana: 'そっちょく', romaji: 'socchoku', meaning: 'thẳng thắn', partOfSpeech: 'tính từ na' },
      { kanji: '謙虚', kana: 'けんきょ', romaji: 'kenkyo', meaning: 'khiêm tốn', partOfSpeech: 'tính từ na' },
      { kanji: '傲慢', kana: 'ごうまん', romaji: 'gōman', meaning: 'kiêu ngạo', partOfSpeech: 'tính từ na' },
      { kanji: '頑固', kana: 'がんこ', romaji: 'ganko', meaning: 'cố chấp, bảo thủ', partOfSpeech: 'tính từ na' },
      { kanji: '柔軟', kana: 'じゅうなん', romaji: 'jūnan', meaning: 'linh hoạt, mềm dẻo', partOfSpeech: 'tính từ na' },
      { kanji: '几帳面', kana: 'きちょうめん', romaji: 'kichōmen', meaning: 'tỉ mỉ, ngăn nắp', partOfSpeech: 'tính từ na' },
      { kanji: 'いい加減', kana: 'いいかげん', romaji: 'ii kagen', meaning: 'cẩu thả, qua loa', partOfSpeech: 'tính từ na' },
      { kanji: '意欲', kana: 'いよく', romaji: 'iyoku', meaning: 'ý chí, nhiệt huyết', partOfSpeech: 'danh từ' },
      { kanji: '根気', kana: 'こんき', romaji: 'konki', meaning: 'sự kiên nhẫn', partOfSpeech: 'danh từ' },
      { kanji: '忍耐', kana: 'にんたい', romaji: 'nintai', meaning: 'sự nhẫn nại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '覚悟', kana: 'かくご', romaji: 'kakugo', meaning: 'sự quyết tâm, chuẩn bị tinh thần', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '決意', kana: 'けつい', romaji: 'ketsui', meaning: 'quyết ý', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '態度', kana: 'たいど', romaji: 'taido', meaning: 'thái độ', partOfSpeech: 'danh từ' },
      { kanji: '印象', kana: 'いんしょう', romaji: 'inshō', meaning: 'ấn tượng', partOfSpeech: 'danh từ' },
      { kanji: '雰囲気', kana: 'ふんいき', romaji: 'fun\'iki', meaning: 'bầu không khí', partOfSpeech: 'danh từ' },
      { kanji: '魅力', kana: 'みりょく', romaji: 'miryoku', meaning: 'sức hấp dẫn', partOfSpeech: 'danh từ' },
      { kanji: '個性', kana: 'こせい', romaji: 'kosei', meaning: 'cá tính', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 422,
    jlptLevel: 'N2',
    words: [
      { kanji: '把握', kana: 'はあく', romaji: 'haaku', meaning: 'nắm bắt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '検討', kana: 'けんとう', romaji: 'kentō', meaning: 'xem xét, cân nhắc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '判断', kana: 'はんだん', romaji: 'handan', meaning: 'phán đoán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '評価', kana: 'ひょうか', romaji: 'hyōka', meaning: 'đánh giá', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '比較', kana: 'ひかく', romaji: 'hikaku', meaning: 'so sánh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '区別', kana: 'くべつ', romaji: 'kubetsu', meaning: 'phân biệt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '選択', kana: 'せんたく', romaji: 'sentaku', meaning: 'sự lựa chọn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '決定', kana: 'けってい', romaji: 'kettei', meaning: 'quyết định', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '提案', kana: 'ていあん', romaji: 'teian', meaning: 'đề xuất', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '意見', kana: 'いけん', romaji: 'iken', meaning: 'ý kiến', partOfSpeech: 'danh từ' },
      { kanji: '主張', kana: 'しゅちょう', romaji: 'shuchō', meaning: 'chủ trương, khẳng định', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '反論', kana: 'はんろん', romaji: 'hanron', meaning: 'phản bác', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '説得', kana: 'せっとく', romaji: 'settoku', meaning: 'thuyết phục', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '交渉', kana: 'こうしょう', romaji: 'kōshō', meaning: 'đàm phán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '合意', kana: 'ごうい', romaji: 'gōi', meaning: 'sự nhất trí', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '妥協', kana: 'だきょう', romaji: 'dakyō', meaning: 'thỏa hiệp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '対立', kana: 'たいりつ', romaji: 'tairitsu', meaning: 'đối lập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '一致', kana: 'いっち', romaji: 'icchi', meaning: 'trùng khớp, nhất trí', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '矛盾', kana: 'むじゅん', romaji: 'mujun', meaning: 'mâu thuẫn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '根拠', kana: 'こんきょ', romaji: 'konkyo', meaning: 'căn cứ', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 423,
    jlptLevel: 'N2',
    words: [
      { kanji: '環境問題', kana: 'かんきょうもんだい', romaji: 'kankyō mondai', meaning: 'vấn đề môi trường', partOfSpeech: 'danh từ' },
      { kanji: '地球温暖化', kana: 'ちきゅうおんだんか', romaji: 'chikyū ondanka', meaning: 'sự nóng lên toàn cầu', partOfSpeech: 'danh từ' },
      { kanji: '温室効果', kana: 'おんしつこうか', romaji: 'onshitsu kōka', meaning: 'hiệu ứng nhà kính', partOfSpeech: 'danh từ' },
      { kanji: '排出', kana: 'はいしゅつ', romaji: 'haishutsu', meaning: 'thải ra', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '汚染', kana: 'おせん', romaji: 'osen', meaning: 'ô nhiễm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '資源', kana: 'しげん', romaji: 'shigen', meaning: 'tài nguyên', partOfSpeech: 'danh từ' },
      { kanji: 'エネルギー', kana: 'エネルギー', romaji: 'enerugī', meaning: 'năng lượng', partOfSpeech: 'danh từ' },
      { kanji: '再生可能', kana: 'さいせいかのう', romaji: 'saisei kanō', meaning: 'có thể tái tạo', partOfSpeech: 'tính từ na' },
      { kanji: '持続可能', kana: 'じぞくかのう', romaji: 'jizoku kanō', meaning: 'bền vững', partOfSpeech: 'tính từ na' },
      { kanji: '節約', kana: 'せつやく', romaji: 'setsuyaku', meaning: 'tiết kiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '消費', kana: 'しょうひ', romaji: 'shōhi', meaning: 'tiêu thụ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '削減', kana: 'さくげん', romaji: 'sakugen', meaning: 'cắt giảm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '規制', kana: 'きせい', romaji: 'kisei', meaning: 'quy định, hạn chế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '対策', kana: 'たいさく', romaji: 'taisaku', meaning: 'đối sách, biện pháp', partOfSpeech: 'danh từ' },
      { kanji: '影響', kana: 'えいきょう', romaji: 'eikyō', meaning: 'ảnh hưởng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '原因', kana: 'げんいん', romaji: 'gen\'in', meaning: 'nguyên nhân', partOfSpeech: 'danh từ' },
      { kanji: '結果', kana: 'けっか', romaji: 'kekka', meaning: 'kết quả', partOfSpeech: 'danh từ' },
      { kanji: '現象', kana: 'げんしょう', romaji: 'genshō', meaning: 'hiện tượng', partOfSpeech: 'danh từ' },
      { kanji: '異常', kana: 'いじょう', romaji: 'ijō', meaning: 'bất thường', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '深刻', kana: 'しんこく', romaji: 'shinkoku', meaning: 'nghiêm trọng', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 424,
    jlptLevel: 'N2',
    words: [
      { kanji: '教育制度', kana: 'きょういくせいど', romaji: 'kyōiku seido', meaning: 'hệ thống giáo dục', partOfSpeech: 'danh từ' },
      { kanji: '義務教育', kana: 'ぎむきょういく', romaji: 'gimu kyōiku', meaning: 'giáo dục bắt buộc', partOfSpeech: 'danh từ' },
      { kanji: '受験', kana: 'じゅけん', romaji: 'juken', meaning: 'dự thi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '合格', kana: 'ごうかく', romaji: 'gōkaku', meaning: 'đỗ, đạt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '不合格', kana: 'ふごうかく', romaji: 'fugōkaku', meaning: 'trượt, không đạt', partOfSpeech: 'danh từ' },
      { kanji: '成績', kana: 'せいせき', romaji: 'seiseki', meaning: 'thành tích, điểm số', partOfSpeech: 'danh từ' },
      { kanji: '偏差値', kana: 'へんさち', romaji: 'hensachi', meaning: 'điểm chuẩn hóa (thang đánh giá học lực)', partOfSpeech: 'danh từ' },
      { kanji: '奨学金', kana: 'しょうがくきん', romaji: 'shōgakukin', meaning: 'học bổng', partOfSpeech: 'danh từ' },
      { kanji: '授業料', kana: 'じゅぎょうりょう', romaji: 'jugyōryō', meaning: 'học phí', partOfSpeech: 'danh từ' },
      { kanji: '講義', kana: 'こうぎ', romaji: 'kōgi', meaning: 'bài giảng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '講師', kana: 'こうし', romaji: 'kōshi', meaning: 'giảng viên', partOfSpeech: 'danh từ' },
      { kanji: '専攻', kana: 'せんこう', romaji: 'senkō', meaning: 'chuyên ngành', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '論文', kana: 'ろんぶん', romaji: 'ronbun', meaning: 'luận văn', partOfSpeech: 'danh từ' },
      { kanji: '課題', kana: 'かだい', romaji: 'kadai', meaning: 'bài tập lớn, đề tài', partOfSpeech: 'danh từ' },
      { kanji: '単位', kana: 'たんい', romaji: 'tan\'i', meaning: 'tín chỉ, đơn vị', partOfSpeech: 'danh từ' },
      { kanji: '進路', kana: 'しんろ', romaji: 'shinro', meaning: 'hướng đi (học tập/sự nghiệp)', partOfSpeech: 'danh từ' },
      { kanji: '就職活動', kana: 'しゅうしょくかつどう', romaji: 'shūshoku katsudō', meaning: 'hoạt động xin việc', partOfSpeech: 'danh từ' },
      { kanji: '人材', kana: 'じんざい', romaji: 'jinzai', meaning: 'nhân tài', partOfSpeech: 'danh từ' },
      { kanji: '能力主義', kana: 'のうりょくしゅぎ', romaji: 'nōryoku shugi', meaning: 'chủ nghĩa trọng năng lực', partOfSpeech: 'danh từ' },
      { kanji: '格差', kana: 'かくさ', romaji: 'kakusa', meaning: 'khoảng cách, chênh lệch', partOfSpeech: 'danh từ' },
    ],
  },

  // ─────────────────────────────── N1 ───────────────────────────────
  {
    lessonNumber: 524,
    jlptLevel: 'N1',
    words: [
      { kanji: '推移', kana: 'すいい', romaji: 'suii', meaning: 'sự biến chuyển theo thời gian', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '変遷', kana: 'へんせん', romaji: 'hensen', meaning: 'sự biến thiên, thay đổi qua thời gian', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '傾倒', kana: 'けいとう', romaji: 'keitō', meaning: 'say mê, tâm huyết với', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '没頭', kana: 'ぼっとう', romaji: 'bottō', meaning: 'chuyên tâm, đắm chìm vào', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '固執', kana: 'こしつ', romaji: 'koshitsu', meaning: 'cố chấp, khăng khăng giữ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '執着', kana: 'しゅうちゃく', romaji: 'shūchaku', meaning: 'sự chấp niệm, bám víu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '打開', kana: 'だかい', romaji: 'dakai', meaning: 'phá vỡ bế tắc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '克服', kana: 'こくふく', romaji: 'kokufuku', meaning: 'khắc phục', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '妥結', kana: 'だけつ', romaji: 'daketsu', meaning: 'đạt thỏa thuận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '調停', kana: 'ちょうてい', romaji: 'chōtei', meaning: 'hòa giải, trung gian điều đình', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '介入', kana: 'かいにゅう', romaji: 'kainyū', meaning: 'can thiệp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '干渉', kana: 'かんしょう', romaji: 'kanshō', meaning: 'can thiệp, xen vào', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '排除', kana: 'はいじょ', romaji: 'haijo', meaning: 'loại bỏ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '阻止', kana: 'そし', romaji: 'soshi', meaning: 'ngăn chặn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '促進', kana: 'そくしん', romaji: 'sokushin', meaning: 'thúc đẩy', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '抑制', kana: 'よくせい', romaji: 'yokusei', meaning: 'kìm hãm, ức chế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '緩和', kana: 'かんわ', romaji: 'kanwa', meaning: 'nới lỏng, làm dịu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '是正', kana: 'ぜせい', romaji: 'zesei', meaning: 'chỉnh sửa cho đúng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '是認', kana: 'ぜにん', romaji: 'zenin', meaning: 'thừa nhận, tán thành', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '否定', kana: 'ひてい', romaji: 'hitei', meaning: 'phủ định', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 525,
    jlptLevel: 'N1',
    words: [
      { kanji: '風潮', kana: 'ふうちょう', romaji: 'fūchō', meaning: 'trào lưu, xu thế xã hội', partOfSpeech: 'danh từ' },
      { kanji: '風習', kana: 'ふうしゅう', romaji: 'fūshū', meaning: 'phong tục', partOfSpeech: 'danh từ' },
      { kanji: '慣習', kana: 'かんしゅう', romaji: 'kanshū', meaning: 'tập quán', partOfSpeech: 'danh từ' },
      { kanji: '風潮に乗る', kana: 'ふうちょうにのる', romaji: 'fūchō ni noru', meaning: 'theo trào lưu', partOfSpeech: 'cụm từ' },
      { kanji: '奇跡', kana: 'きせき', romaji: 'kiseki', meaning: 'phép màu, kỳ tích', partOfSpeech: 'danh từ' },
      { kanji: '幻想', kana: 'げんそう', romaji: 'gensō', meaning: 'ảo tưởng', partOfSpeech: 'danh từ' },
      { kanji: '錯覚', kana: 'さっかく', romaji: 'sakkaku', meaning: 'ảo giác, sự nhầm lẫn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '妄想', kana: 'もうそう', romaji: 'mōsō', meaning: 'vọng tưởng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '直感', kana: 'ちょっかん', romaji: 'chokkan', meaning: 'trực giác', partOfSpeech: 'danh từ' },
      { kanji: '洞察', kana: 'どうさつ', romaji: 'dōsatsu', meaning: 'sự thấu hiểu sâu sắc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '示唆', kana: 'しさ', romaji: 'shisa', meaning: 'ngụ ý, gợi ý', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '暗示', kana: 'あんじ', romaji: 'anji', meaning: 'ám chỉ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '象徴', kana: 'しょうちょう', romaji: 'shōchō', meaning: 'biểu tượng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '比喩', kana: 'ひゆ', romaji: 'hiyu', meaning: 'phép ẩn dụ, so sánh', partOfSpeech: 'danh từ' },
      { kanji: '皮肉', kana: 'ひにく', romaji: 'hiniku', meaning: 'sự mỉa mai, trớ trêu', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '矛先', kana: 'ほこさき', romaji: 'hokosaki', meaning: 'mũi nhọn (chỉ trích...)', partOfSpeech: 'danh từ' },
      { kanji: '批評', kana: 'ひひょう', romaji: 'hihyō', meaning: 'phê bình', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '論評', kana: 'ろんぴょう', romaji: 'ronpyō', meaning: 'bình luận (có phân tích)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '見解', kana: 'けんかい', romaji: 'kenkai', meaning: 'quan điểm, kiến giải', partOfSpeech: 'danh từ' },
      { kanji: '所見', kana: 'しょけん', romaji: 'shoken', meaning: 'ý kiến riêng, nhận định', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 526,
    jlptLevel: 'N1',
    words: [
      { kanji: '厳密', kana: 'げんみつ', romaji: 'genmitsu', meaning: 'nghiêm ngặt, chặt chẽ', partOfSpeech: 'tính từ na' },
      { kanji: '綿密', kana: 'めんみつ', romaji: 'menmitsu', meaning: 'tỉ mỉ, chu đáo', partOfSpeech: 'tính từ na' },
      { kanji: '入念', kana: 'にゅうねん', romaji: 'nyūnen', meaning: 'kỹ lưỡng, cẩn thận', partOfSpeech: 'tính từ na' },
      { kanji: '簡潔', kana: 'かんけつ', romaji: 'kanketsu', meaning: 'ngắn gọn, súc tích', partOfSpeech: 'tính từ na' },
      { kanji: '冗長', kana: 'じょうちょう', romaji: 'jōchō', meaning: 'dài dòng, lê thê', partOfSpeech: 'tính từ na' },
      { kanji: '曖昧', kana: 'あいまい', romaji: 'aimai', meaning: 'mơ hồ, mập mờ', partOfSpeech: 'tính từ na' },
      { kanji: '明瞭', kana: 'めいりょう', romaji: 'meiryō', meaning: 'rõ ràng, minh bạch', partOfSpeech: 'tính từ na' },
      { kanji: '妥当', kana: 'だとう', romaji: 'datō', meaning: 'thỏa đáng, hợp lý', partOfSpeech: 'tính từ na' },
      { kanji: '不当', kana: 'ふとう', romaji: 'futō', meaning: 'không thỏa đáng, bất công', partOfSpeech: 'tính từ na' },
      { kanji: '公正', kana: 'こうせい', romaji: 'kōsei', meaning: 'công bằng, công chính', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '公平', kana: 'こうへい', romaji: 'kōhei', meaning: 'công bằng', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '偏見', kana: 'へんけん', romaji: 'henken', meaning: 'thành kiến', partOfSpeech: 'danh từ' },
      { kanji: '差別', kana: 'さべつ', romaji: 'sabetsu', meaning: 'sự phân biệt đối xử', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '平等', kana: 'びょうどう', romaji: 'byōdō', meaning: 'sự bình đẳng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '多様性', kana: 'たようせい', romaji: 'tayōsei', meaning: 'tính đa dạng', partOfSpeech: 'danh từ' },
      { kanji: '画一的', kana: 'かくいつてき', romaji: 'kakuitsuteki', meaning: 'mang tính rập khuôn, đồng nhất', partOfSpeech: 'tính từ na' },
      { kanji: '独自', kana: 'どくじ', romaji: 'dokuji', meaning: 'độc đáo, riêng biệt', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '斬新', kana: 'ざんしん', romaji: 'zanshin', meaning: 'mới lạ, đột phá', partOfSpeech: 'tính từ na' },
      { kanji: '陳腐', kana: 'ちんぷ', romaji: 'chinpu', meaning: 'sáo rỗng, cũ kỹ', partOfSpeech: 'tính từ na' },
      { kanji: '画期的', kana: 'かっきてき', romaji: 'kakkiteki', meaning: 'mang tính đột phá thời đại', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 527,
    jlptLevel: 'N1',
    words: [
      { kanji: '逸脱', kana: 'いつだつ', romaji: 'itsudatsu', meaning: 'đi chệch, lệch khỏi (chuẩn mực)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '脱線', kana: 'だっせん', romaji: 'dassen', meaning: 'trật bánh, lạc đề', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '逃避', kana: 'とうひ', romaji: 'tōhi', meaning: 'trốn tránh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '回避', kana: 'かいひ', romaji: 'kaihi', meaning: 'né tránh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '妨害', kana: 'ぼうがい', romaji: 'bōgai', meaning: 'cản trở, phá rối', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '弊害', kana: 'へいがい', romaji: 'heigai', meaning: 'tệ hại, tác hại', partOfSpeech: 'danh từ' },
      { kanji: '悪循環', kana: 'あくじゅんかん', romaji: 'aku junkan', meaning: 'vòng luẩn quẩn', partOfSpeech: 'danh từ' },
      { kanji: '矛盾点', kana: 'むじゅんてん', romaji: 'mujunten', meaning: 'điểm mâu thuẫn', partOfSpeech: 'danh từ' },
      { kanji: '欠陥', kana: 'けっかん', romaji: 'kekkan', meaning: 'khiếm khuyết', partOfSpeech: 'danh từ' },
      { kanji: '不備', kana: 'ふび', romaji: 'fubi', meaning: 'sự thiếu sót', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '過失', kana: 'かしつ', romaji: 'kashitsu', meaning: 'sơ suất, lỗi vô ý', partOfSpeech: 'danh từ' },
      { kanji: '責任転嫁', kana: 'せきにんてんか', romaji: 'sekinin tenka', meaning: 'đùn đẩy trách nhiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '正当化', kana: 'せいとうか', romaji: 'seitōka', meaning: 'sự chính đáng hóa, biện minh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '弁明', kana: 'べんめい', romaji: 'benmei', meaning: 'sự biện minh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '釈明', kana: 'しゃくめい', romaji: 'shakumei', meaning: 'giải thích để làm rõ hiểu lầm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '謝罪', kana: 'しゃざい', romaji: 'shazai', meaning: 'lời xin lỗi (trang trọng)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '賠償', kana: 'ばいしょう', romaji: 'baishō', meaning: 'bồi thường', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '補償', kana: 'ほしょう', romaji: 'hoshō', meaning: 'đền bù', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '救済', kana: 'きゅうさい', romaji: 'kyūsai', meaning: 'cứu tế, cứu trợ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '摘発', kana: 'てきはつ', romaji: 'tekihatsu', meaning: 'phanh phui, phát giác', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 528,
    jlptLevel: 'N1',
    words: [
      { kanji: '兆候', kana: 'ちょうこう', romaji: 'chōkō', meaning: 'dấu hiệu, triệu chứng', partOfSpeech: 'danh từ' },
      { kanji: '前兆', kana: 'ぜんちょう', romaji: 'zenchō', meaning: 'điềm báo trước', partOfSpeech: 'danh từ' },
      { kanji: '兆し', kana: 'きざし', romaji: 'kizashi', meaning: 'điềm, dấu hiệu manh nha', partOfSpeech: 'danh từ' },
      { kanji: '萌芽', kana: 'ほうが', romaji: 'hōga', meaning: 'mầm mống', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発端', kana: 'ほったん', romaji: 'hottan', meaning: 'khởi đầu, căn nguyên', partOfSpeech: 'danh từ' },
      { kanji: '契機', kana: 'けいき', romaji: 'keiki', meaning: 'cơ duyên, chất xúc tác', partOfSpeech: 'danh từ' },
      { kanji: '要因', kana: 'よういん', romaji: 'yōin', meaning: 'nhân tố chính', partOfSpeech: 'danh từ' },
      { kanji: '一環', kana: 'いっかん', romaji: 'ikkan', meaning: 'một khâu, một phần trong tổng thể', partOfSpeech: 'danh từ' },
      { kanji: '一心', kana: 'いっしん', romaji: 'isshin', meaning: 'một lòng, chuyên tâm', partOfSpeech: 'danh từ' },
      { kanji: '一途', kana: 'いちず', romaji: 'ichizu', meaning: 'một lòng một dạ', partOfSpeech: 'tính từ na' },
      { kanji: '究極', kana: 'きゅうきょく', romaji: 'kyūkyoku', meaning: 'tột cùng, cuối cùng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '極端', kana: 'きょくたん', romaji: 'kyokutan', meaning: 'cực đoan, thái quá', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '過剰', kana: 'かじょう', romaji: 'kajō', meaning: 'quá mức', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '過度', kana: 'かど', romaji: 'kado', meaning: 'quá độ', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '適度', kana: 'てきど', romaji: 'tekido', meaning: 'vừa phải', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '均衡', kana: 'きんこう', romaji: 'kinkō', meaning: 'sự cân bằng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '偏り', kana: 'かたより', romaji: 'katayori', meaning: 'sự thiên lệch', partOfSpeech: 'danh từ' },
      { kanji: '傾斜', kana: 'けいしゃ', romaji: 'keisha', meaning: 'độ nghiêng, khuynh hướng nghiêng về', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '基盤', kana: 'きばん', romaji: 'kiban', meaning: 'nền tảng', partOfSpeech: 'danh từ' },
      { kanji: '土台', kana: 'どだい', romaji: 'dodai', meaning: 'nền móng, cơ sở', partOfSpeech: 'danh từ' },
    ],
  },
];
