// Từ vựng bổ sung batch 2 — N5 (201–204), N4 (211–214), N3 (306–311), N2 (411–417), N1 (510–516).
// Gộp vào seed qua jlpt-vocab-expand.data.ts

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_EXPAND_EXTRA: JlptVocabUnit[] = [
  // ─── N5 bổ sung (mục tiêu ~800 tích lũy, Minna ~580) ───
  {
    lessonNumber: 201,
    jlptLevel: 'N5',
    words: [
      { kanji: '朝ごはん', kana: 'あさごはん', romaji: 'asagohan', meaning: 'bữa sáng', partOfSpeech: 'danh từ' },
      { kanji: '昼ごはん', kana: 'ひるごはん', romaji: 'hirugohan', meaning: 'bữa trưa', partOfSpeech: 'danh từ' },
      { kanji: '晩ごはん', kana: 'ばんごはん', romaji: 'bangohan', meaning: 'bữa tối', partOfSpeech: 'danh từ' },
      { kanji: 'おやつ', kana: 'おやつ', romaji: 'oyatsu', meaning: 'bữa phụ, đồ ăn vặt', partOfSpeech: 'danh từ' },
      { kanji: '弁当', kana: 'べんとう', romaji: 'bentō', meaning: 'cơm hộp', partOfSpeech: 'danh từ' },
      { kanji: '箸', kana: 'はし', romaji: 'hashi', meaning: 'đũa', partOfSpeech: 'danh từ' },
      { kanji: '茶碗', kana: 'ちゃわん', romaji: 'chawan', meaning: 'bát cơm, chén trà', partOfSpeech: 'danh từ' },
      { kanji: '皿', kana: 'さら', romaji: 'sara', meaning: 'đĩa', partOfSpeech: 'danh từ' },
      { kanji: '瓶', kana: 'びん', romaji: 'bin', meaning: 'chai, lọ', partOfSpeech: 'danh từ' },
      { kanji: '袋', kana: 'ふくろ', romaji: 'fukuro', meaning: 'túi, bao', partOfSpeech: 'danh từ' },
      { kanji: '箱', kana: 'はこ', romaji: 'hako', meaning: 'hộp, thùng', partOfSpeech: 'danh từ' },
      { kanji: '鍵', kana: 'かぎ', romaji: 'kagi', meaning: 'chìa khóa', partOfSpeech: 'danh từ' },
      { kanji: '財布', kana: 'さいふ', romaji: 'saifu', meaning: 'ví tiền', partOfSpeech: 'danh từ' },
      { kanji: '傘', kana: 'かさ', romaji: 'kasa', meaning: 'ô, dù', partOfSpeech: 'danh từ' },
      { kanji: '眼鏡', kana: 'めがね', romaji: 'megane', meaning: 'kính mắt', partOfSpeech: 'danh từ' },
      { kanji: '時計', kana: 'とけい', romaji: 'tokei', meaning: 'đồng hồ', partOfSpeech: 'danh từ' },
      { kanji: '壁', kana: 'かべ', romaji: 'kabe', meaning: 'bức tường', partOfSpeech: 'danh từ' },
      { kanji: '床', kana: 'ゆか', romaji: 'yuka', meaning: 'sàn nhà', partOfSpeech: 'danh từ' },
      { kanji: '天井', kana: 'てんじょう', romaji: 'tenjō', meaning: 'trần nhà', partOfSpeech: 'danh từ' },
      { kanji: '階段', kana: 'かいだん', romaji: 'kaidan', meaning: 'cầu thang', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 202,
    jlptLevel: 'N5',
    words: [
      { kanji: '走る', kana: 'はしる', romaji: 'hashiru', meaning: 'chạy', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '歩く', kana: 'あるく', romaji: 'aruku', meaning: 'đi bộ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '泳ぐ', kana: 'およぐ', romaji: 'oyogu', meaning: 'bơi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '飛ぶ', kana: 'とぶ', romaji: 'tobu', meaning: 'bay', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '登る', kana: 'のぼる', romaji: 'noboru', meaning: 'leo, lên', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '降りる', kana: 'おりる', romaji: 'oriru', meaning: 'xuống (xe, cầu thang)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '乗る', kana: 'のる', romaji: 'noru', meaning: 'lên (xe)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '曲がる', kana: 'まがる', romaji: 'magaru', meaning: 'rẽ, quẹo', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '渡る', kana: 'わたる', romaji: 'wataru', meaning: 'băng qua', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '止まる', kana: 'とまる', romaji: 'tomaru', meaning: 'dừng lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '始まる', kana: 'はじまる', romaji: 'hajimaru', meaning: 'bắt đầu', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '終わる', kana: 'おわる', romaji: 'owaru', meaning: 'kết thúc', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '開ける', kana: 'あける', romaji: 'akeru', meaning: 'mở', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '閉める', kana: 'しめる', romaji: 'shimeru', meaning: 'đóng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '付ける', kana: 'つける', romaji: 'tsukeru', meaning: 'bật (điện); gắn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '消す', kana: 'けす', romaji: 'kesu', meaning: 'tắt; xóa', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '持つ', kana: 'もつ', romaji: 'motsu', meaning: 'cầm, mang', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '置く', kana: 'おく', romaji: 'oku', meaning: 'đặt, để', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '取る', kana: 'とる', romaji: 'toru', meaning: 'lấy', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '渡す', kana: 'わたす', romaji: 'watasu', meaning: 'đưa cho, băng qua', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 203,
    jlptLevel: 'N5',
    words: [
      { kanji: '暑い', kana: 'あつい', romaji: 'atsui', meaning: 'nóng (thời tiết)', partOfSpeech: 'tính từ i' },
      { kanji: '寒い', kana: 'さむい', romaji: 'samui', meaning: 'lạnh', partOfSpeech: 'tính từ i' },
      { kanji: '暖かい', kana: 'あたたかい', romaji: 'atatakai', meaning: 'ấm', partOfSpeech: 'tính từ i' },
      { kanji: '涼しい', kana: 'すずしい', romaji: 'suzushii', meaning: 'mát', partOfSpeech: 'tính từ i' },
      { kanji: '強い', kana: 'つよい', romaji: 'tsuyoi', meaning: 'mạnh', partOfSpeech: 'tính từ i' },
      { kanji: '弱い', kana: 'よわい', romaji: 'yowai', meaning: 'yếu', partOfSpeech: 'tính từ i' },
      { kanji: '深い', kana: 'ふかい', romaji: 'fukai', meaning: 'sâu', partOfSpeech: 'tính từ i' },
      { kanji: '浅い', kana: 'あさい', romaji: 'asai', meaning: 'nông', partOfSpeech: 'tính từ i' },
      { kanji: '厚い', kana: 'あつい', romaji: 'atsui', meaning: 'dày', partOfSpeech: 'tính từ i' },
      { kanji: '薄い', kana: 'うすい', romaji: 'usui', meaning: 'mỏng, loãng', partOfSpeech: 'tính từ i' },
      { kanji: '重い', kana: 'おもい', romaji: 'omoi', meaning: 'nặng', partOfSpeech: 'tính từ i' },
      { kanji: '軽い', kana: 'かるい', romaji: 'karui', meaning: 'nhẹ', partOfSpeech: 'tính từ i' },
      { kanji: '速い', kana: 'はやい', romaji: 'hayai', meaning: 'nhanh', partOfSpeech: 'tính từ i' },
      { kanji: '遅い', kana: 'おそい', romaji: 'osoi', meaning: 'chậm; muộn', partOfSpeech: 'tính từ i' },
      { kanji: '早い', kana: 'はやい', romaji: 'hayai', meaning: 'sớm', partOfSpeech: 'tính từ i' },
      { kanji: '近い', kana: 'ちかい', romaji: 'chikai', meaning: 'gần', partOfSpeech: 'tính từ i' },
      { kanji: '遠い', kana: 'とおい', romaji: 'tōi', meaning: 'xa', partOfSpeech: 'tính từ i' },
      { kanji: '若い', kana: 'わかい', romaji: 'wakai', meaning: 'trẻ', partOfSpeech: 'tính từ i' },
      { kanji: '悲しい', kana: 'かなしい', romaji: 'kanashii', meaning: 'buồn', partOfSpeech: 'tính từ i' },
      { kanji: '嬉しい', kana: 'うれしい', romaji: 'ureshii', meaning: 'vui', partOfSpeech: 'tính từ i' },
    ],
  },
  {
    lessonNumber: 204,
    jlptLevel: 'N5',
    words: [
      { kanji: '頭', kana: 'あたま', romaji: 'atama', meaning: 'đầu', partOfSpeech: 'danh từ' },
      { kanji: '顔', kana: 'かお', romaji: 'kao', meaning: 'khuôn mặt', partOfSpeech: 'danh từ' },
      { kanji: '首', kana: 'くび', romaji: 'kubi', meaning: 'cổ', partOfSpeech: 'danh từ' },
      { kanji: '肩', kana: 'かた', romaji: 'kata', meaning: 'vai', partOfSpeech: 'danh từ' },
      { kanji: '背中', kana: 'せなか', romaji: 'senaka', meaning: 'lưng', partOfSpeech: 'danh từ' },
      { kanji: 'お腹', kana: 'おなか', romaji: 'onaka', meaning: 'bụng', partOfSpeech: 'danh từ' },
      { kanji: '指', kana: 'ゆび', romaji: 'yubi', meaning: 'ngón tay', partOfSpeech: 'danh từ' },
      { kanji: '爪', kana: 'つめ', romaji: 'tsume', meaning: 'móng tay', partOfSpeech: 'danh từ' },
      { kanji: '歯', kana: 'は', romaji: 'ha', meaning: 'răng', partOfSpeech: 'danh từ' },
      { kanji: '舌', kana: 'した', romaji: 'shita', meaning: 'lưỡi', partOfSpeech: 'danh từ' },
      { kanji: '喉', kana: 'のど', romaji: 'nodo', meaning: 'họng', partOfSpeech: 'danh từ' },
      { kanji: '心', kana: 'こころ', romaji: 'kokoro', meaning: 'trái tim; tâm hồn', partOfSpeech: 'danh từ' },
      { kanji: '血', kana: 'ち', romaji: 'chi', meaning: 'máu', partOfSpeech: 'danh từ' },
      { kanji: '汗', kana: 'あせ', romaji: 'ase', meaning: 'mồ hôi', partOfSpeech: 'danh từ' },
      { kanji: '涙', kana: 'なみだ', romaji: 'namida', meaning: 'nước mắt', partOfSpeech: 'danh từ' },
      { kanji: '声', kana: 'こえ', romaji: 'koe', meaning: 'giọng nói', partOfSpeech: 'danh từ' },
      { kanji: '音', kana: 'おと', romaji: 'oto', meaning: 'âm thanh', partOfSpeech: 'danh từ' },
      { kanji: '匂い', kana: 'におい', romaji: 'nioi', meaning: 'mùi', partOfSpeech: 'danh từ' },
      { kanji: '味', kana: 'あじ', romaji: 'aji', meaning: 'vị', partOfSpeech: 'danh từ' },
      { kanji: '触る', kana: 'さわる', romaji: 'sawaru', meaning: 'chạm, sờ', partOfSpeech: 'động từ nhóm 1' },
    ],
  },

  // ─── N4 bổ sung ───
  {
    lessonNumber: 211,
    jlptLevel: 'N4',
    words: [
      { kanji: '予約', kana: 'よやく', romaji: 'yoyaku', meaning: 'đặt trước', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '取消', kana: 'とりけし', romaji: 'torikeshi', meaning: 'hủy bỏ', partOfSpeech: 'danh từ' },
      { kanji: '変更', kana: 'へんこう', romaji: 'henkō', meaning: 'thay đổi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '遅刻', kana: 'ちこく', romaji: 'chikoku', meaning: 'đến muộn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '欠席', kana: 'けっせき', romaji: 'kesseki', meaning: 'vắng mặt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '出席', kana: 'しゅっせき', romaji: 'shusseki', meaning: 'có mặt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '遅れる', kana: 'おくれる', romaji: 'okureru', meaning: 'trễ, chậm', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '間に合う', kana: 'まにあう', romaji: 'maniau', meaning: 'kịp giờ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '間に合わない', kana: 'まにあわない', romaji: 'maniawanai', meaning: 'không kịp', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '急ぐ', kana: 'いそぐ', romaji: 'isogu', meaning: 'vội, gấp', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '慌てる', kana: 'あわてる', romaji: 'awateru', meaning: 'hoảng hốt', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '安心', kana: 'あんしん', romaji: 'anshin', meaning: 'yên tâm', partOfSpeech: 'danh từ, tính từ na, động từ する' },
      { kanji: '心配', kana: 'しんぱい', romaji: 'shinpai', meaning: 'lo lắng', partOfSpeech: 'danh từ, động từ する, tính từ na' },
      { kanji: '残念', kana: 'ざんねん', romaji: 'zannen', meaning: 'đáng tiếc', partOfSpeech: 'tính từ na' },
      { kanji: '幸せ', kana: 'しあわせ', romaji: 'shiawase', meaning: 'hạnh phúc', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '不便', kana: 'ふべん', romaji: 'fuben', meaning: 'bất tiện', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '都合', kana: 'つごう', romaji: 'tsugō', meaning: 'hoàn cảnh, thuận tiện', partOfSpeech: 'danh từ' },
      { kanji: '用事', kana: 'ようじ', romaji: 'yōji', meaning: 'việc bận', partOfSpeech: 'danh từ' },
      { kanji: '予定', kana: 'よてい', romaji: 'yotei', meaning: 'dự định', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '予想', kana: 'よそう', romaji: 'yosō', meaning: 'dự đoán', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 212,
    jlptLevel: 'N4',
    words: [
      { kanji: '届ける', kana: 'とどける', romaji: 'todokeru', meaning: 'giao đến, nộp', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '送る', kana: 'おくる', romaji: 'okuru', meaning: 'gửi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '届く', kana: 'とどく', romaji: 'todoku', meaning: 'đến nơi (thư, hàng)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '配達', kana: 'はいたつ', romaji: 'haitatsu', meaning: 'giao hàng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '荷物', kana: 'にもつ', romaji: 'nimotsu', meaning: 'hành lý, đồ đạc', partOfSpeech: 'danh từ' },
      { kanji: '小包', kana: 'こづつみ', romaji: 'kozutsumi', meaning: 'bưu kiện nhỏ', partOfSpeech: 'danh từ' },
      { kanji: '封筒', kana: 'ふうとう', romaji: 'fūtō', meaning: 'phong bì', partOfSpeech: 'danh từ' },
      { kanji: '切手', kana: 'きって', romaji: 'kitte', meaning: 'tem thư', partOfSpeech: 'danh từ' },
      { kanji: '住所', kana: 'じゅうしょ', romaji: 'jūsho', meaning: 'địa chỉ', partOfSpeech: 'danh từ' },
      { kanji: '番号', kana: 'ばんごう', romaji: 'bangō', meaning: 'số (thứ tự)', partOfSpeech: 'danh từ' },
      { kanji: '電話番号', kana: 'でんわばんごう', romaji: 'denwabangō', meaning: 'số điện thoại', partOfSpeech: 'danh từ' },
      { kanji: '連絡', kana: 'れんらく', romaji: 'renraku', meaning: 'liên lạc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '消息', kana: 'しょうそく', romaji: 'shōsoku', meaning: 'tin tức (về người quen)', partOfSpeech: 'danh từ' },
      { kanji: '知らせ', kana: 'しらせ', romaji: 'shirase', meaning: 'thông báo', partOfSpeech: 'danh từ' },
      { kanji: '案内', kana: 'あんない', romaji: 'annai', meaning: 'hướng dẫn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '紹介', kana: 'しょうかい', romaji: 'shōkai', meaning: 'giới thiệu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '招待', kana: 'しょうたい', romaji: 'shōtai', meaning: 'mời', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '訪問', kana: 'ほうもん', romaji: 'hōmon', meaning: 'thăm viếng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '訪ねる', kana: 'たずねる', romaji: 'tazuneru', meaning: 'thăm hỏi', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '迎える', kana: 'むかえる', romaji: 'mukaeru', meaning: 'đón', partOfSpeech: 'động từ nhóm 2' },
    ],
  },
  {
    lessonNumber: 213,
    jlptLevel: 'N4',
    words: [
      { kanji: '習慣', kana: 'しゅうかん', romaji: 'shūkan', meaning: 'thói quen', partOfSpeech: 'danh từ' },
      { kanji: '生活', kana: 'せいかつ', romaji: 'seikatsu', meaning: 'cuộc sống sinh hoạt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '暮らし', kana: 'くらし', romaji: 'kurashi', meaning: 'sinh hoạt, đời sống', partOfSpeech: 'danh từ' },
      { kanji: '引っ越し', kana: 'ひっこし', romaji: 'hikkoshi', meaning: 'chuyển nhà', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '引っ越す', kana: 'ひっこす', romaji: 'hikkosu', meaning: 'chuyển nhà', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '修理', kana: 'しゅうり', romaji: 'shūri', meaning: 'sửa chữa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '直す', kana: 'なおす', romaji: 'naosu', meaning: 'sửa, chỉnh', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '壊れる', kana: 'こわれる', romaji: 'kowareru', meaning: 'bị hỏng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '壊す', kana: 'こわす', romaji: 'kowasu', meaning: 'làm hỏng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '汚れる', kana: 'よごれる', romaji: 'yogoreru', meaning: 'bị bẩn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '汚す', kana: 'よごす', romaji: 'yogosu', meaning: 'làm bẩn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '掃除', kana: 'そうじ', romaji: 'sōji', meaning: 'dọn dẹp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '洗濯', kana: 'せんたく', romaji: 'sentaku', meaning: 'giặt giũ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '片付ける', kana: 'かたづける', romaji: 'katazukeru', meaning: 'dọn dẹp', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '片付く', kana: 'かたづく', romaji: 'katazuku', meaning: 'được dọn xong', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '準備', kana: 'じゅんび', romaji: 'junbi', meaning: 'chuẩn bị', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '用意', kana: 'ようい', romaji: 'yōi', meaning: 'chuẩn bị sẵn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '支度', kana: 'したく', romaji: 'shitaku', meaning: 'chuẩn bị (đi ra ngoài)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '忘れ物', kana: 'わすれもの', romaji: 'wasuremono', meaning: 'đồ để quên', partOfSpeech: 'danh từ' },
      { kanji: '落とす', kana: 'おとす', romaji: 'otosu', meaning: 'làm rơi', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 214,
    jlptLevel: 'N4',
    words: [
      { kanji: '趣味', kana: 'しゅみ', romaji: 'shumi', meaning: 'sở thích', partOfSpeech: 'danh từ' },
      { kanji: '特技', kana: 'とくぎ', romaji: 'tokugi', meaning: 'sở trường', partOfSpeech: 'danh từ' },
      { kanji: '才能', kana: 'さいのう', romaji: 'sainō', meaning: 'tài năng', partOfSpeech: 'danh từ' },
      { kanji: '上手', kana: 'じょうず', romaji: 'jōzu', meaning: 'giỏi', partOfSpeech: 'tính từ na' },
      { kanji: '下手', kana: 'へた', romaji: 'heta', meaning: 'kém', partOfSpeech: 'tính từ na' },
      { kanji: '得意', kana: 'とくい', romaji: 'tokui', meaning: 'sở trường, tự tin', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '苦手', kana: 'にがて', romaji: 'nigate', meaning: 'kém, ngại', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '似ている', kana: 'にている', romaji: 'nite iru', meaning: 'giống', partOfSpeech: 'cụm từ' },
      { kanji: '似る', kana: 'にる', romaji: 'niru', meaning: 'giống', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '似合う', kana: 'にあう', romaji: 'niau', meaning: 'hợp, vừa vặn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '反対', kana: 'はんたい', romaji: 'hantai', meaning: 'ngược lại, phản đối', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '賛成', kana: 'さんせい', romaji: 'sansei', meaning: 'tán thành', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '意見', kana: 'いけん', romaji: 'iken', meaning: 'ý kiến', partOfSpeech: 'danh từ' },
      { kanji: '考え', kana: 'かんがえ', romaji: 'kangae', meaning: 'suy nghĩ, ý nghĩ', partOfSpeech: 'danh từ' },
      { kanji: '考え方', kana: 'かんがえかた', romaji: 'kangaekata', meaning: 'cách suy nghĩ', partOfSpeech: 'danh từ' },
      { kanji: '気持ち', kana: 'きもち', romaji: 'kimochi', meaning: 'cảm giác, tâm trạng', partOfSpeech: 'danh từ' },
      { kanji: '気分', kana: 'きぶん', romaji: 'kibun', meaning: 'tâm trạng', partOfSpeech: 'danh từ' },
      { kanji: '機嫌', kana: 'きげん', romaji: 'kigen', meaning: 'tính khí, tâm trạng', partOfSpeech: 'danh từ' },
      { kanji: '冗談', kana: 'じょうだん', romaji: 'jōdan', meaning: 'đùa, nói đùa', partOfSpeech: 'danh từ' },
      { kanji: '本気', kana: 'ほんき', romaji: 'honki', meaning: 'nghiêm túc, thật lòng', partOfSpeech: 'danh từ, tính từ na' },
    ],
  },

  // ─── N3 bổ sung (306–311) ───
  {
    lessonNumber: 306,
    jlptLevel: 'N3',
    words: [
      { kanji: '影響', kana: 'えいきょう', romaji: 'eikyō', meaning: 'ảnh hưởng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '効果', kana: 'こうか', romaji: 'kōka', meaning: 'hiệu quả', partOfSpeech: 'danh từ' },
      { kanji: '作用', kana: 'さよう', romaji: 'sayō', meaning: 'tác dụng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '傾向', kana: 'けいこう', romaji: 'keikō', meaning: 'xu hướng', partOfSpeech: 'danh từ' },
      { kanji: '現象', kana: 'げんしょう', romaji: 'genshō', meaning: 'hiện tượng', partOfSpeech: 'danh từ' },
      { kanji: '状況', kana: 'じょうきょう', romaji: 'jōkyō', meaning: 'tình hình', partOfSpeech: 'danh từ' },
      { kanji: '状態', kana: 'じょうたい', romaji: 'jōtai', meaning: 'trạng thái', partOfSpeech: 'danh từ' },
      { kanji: '条件', kana: 'じょうけん', romaji: 'jōken', meaning: 'điều kiện', partOfSpeech: 'danh từ' },
      { kanji: '基準', kana: 'きじゅん', romaji: 'kijun', meaning: 'tiêu chuẩn', partOfSpeech: 'danh từ' },
      { kanji: '基礎', kana: 'きそ', romaji: 'kiso', meaning: 'cơ bản, nền tảng', partOfSpeech: 'danh từ' },
      { kanji: '要素', kana: 'ようそ', romaji: 'yōso', meaning: 'yếu tố', partOfSpeech: 'danh từ' },
      { kanji: '要因', kana: 'よういん', romaji: 'yōin', meaning: 'nhân tố', partOfSpeech: 'danh từ' },
      { kanji: '背景', kana: 'はいけい', romaji: 'haikei', meaning: 'bối cảnh', partOfSpeech: 'danh từ' },
      { kanji: '前提', kana: 'ぜんてい', romaji: 'zentai', meaning: 'tiền đề', partOfSpeech: 'danh từ' },
      { kanji: '過程', kana: 'かてい', romaji: 'katei', meaning: 'quá trình', partOfSpeech: 'danh từ' },
      { kanji: '段階', kana: 'だんかい', romaji: 'dankai', meaning: 'giai đoạn', partOfSpeech: 'danh từ' },
      { kanji: '範囲', kana: 'はんい', romaji: 'han\'i', meaning: 'phạm vi', partOfSpeech: 'danh từ' },
      { kanji: '限界', kana: 'げんかい', romaji: 'genkai', meaning: 'giới hạn', partOfSpeech: 'danh từ' },
      { kanji: '程度', kana: 'ていど', romaji: 'teido', meaning: 'mức độ', partOfSpeech: 'danh từ' },
      { kanji: '割合', kana: 'わりあい', romaji: 'wariai', meaning: 'tỷ lệ', partOfSpeech: 'danh từ' },
      { kanji: '平均', kana: 'へいきん', romaji: 'heikin', meaning: 'trung bình', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '標準', kana: 'ひょうじゅん', romaji: 'hyōjun', meaning: 'tiêu chuẩn', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 307,
    jlptLevel: 'N3',
    words: [
      { kanji: '努力', kana: 'どりょく', romaji: 'doryoku', meaning: 'nỗ lực', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '成功', kana: 'せいこう', romaji: 'seikō', meaning: 'thành công', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '失敗', kana: 'しっぱい', romaji: 'shippai', meaning: 'thất bại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '達成', kana: 'たっせい', romaji: 'tassei', meaning: 'đạt được', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '克服', kana: 'こくふく', romaji: 'kokufuku', meaning: 'khắc phục', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '改善', kana: 'かいぜん', romaji: 'kaizen', meaning: 'cải thiện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '向上', kana: 'こうじょう', romaji: 'kōjō', meaning: 'nâng cao', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '低下', kana: 'ていか', romaji: 'teika', meaning: 'suy giảm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '増加', kana: 'ぞうか', romaji: 'zōka', meaning: 'tăng thêm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '減少', kana: 'げんしょう', romaji: 'genshō', meaning: 'giảm bớt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '維持', kana: 'いじ', romaji: 'iji', meaning: 'duy trì', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '継続', kana: 'けいぞく', romaji: 'keizoku', meaning: 'tiếp tục', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '中断', kana: 'ちゅうだん', romaji: 'chūdan', meaning: 'gián đoạn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '延期', kana: 'えんき', romaji: 'enki', meaning: 'hoãn lại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '前倒し', kana: 'まえだおし', romaji: 'maedaoshi', meaning: 'làm sớm hơn dự kiến', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '急務', kana: 'きゅうむ', romaji: 'kyūmu', meaning: 'việc cấp bách', partOfSpeech: 'danh từ' },
      { kanji: '優先', kana: 'ゆうせん', romaji: 'yūsen', meaning: 'ưu tiên', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '後回し', kana: 'あとまわし', romaji: 'atomawashi', meaning: 'để sau', partOfSpeech: 'danh từ' },
      { kanji: '取り組む', kana: 'とりくむ', romaji: 'torikumu', meaning: 'dấn thân, cố gắng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '諦める', kana: 'あきらめる', romaji: 'akirameru', meaning: 'từ bỏ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '粘る', kana: 'ねばる', romaji: 'nebaru', meaning: 'kiên trì', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '我慢', kana: 'がまん', romaji: 'gaman', meaning: 'nhẫn nại', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 308,
    jlptLevel: 'N3',
    words: [
      { kanji: '社会', kana: 'しゃかい', romaji: 'shakai', meaning: 'xã hội', partOfSpeech: 'danh từ' },
      { kanji: '文化', kana: 'ぶんか', romaji: 'bunka', meaning: 'văn hóa', partOfSpeech: 'danh từ' },
      { kanji: '伝統', kana: 'でんとう', romaji: 'dentō', meaning: 'truyền thống', partOfSpeech: 'danh từ' },
      { kanji: '習俗', kana: 'しゅうぞく', romaji: 'shūzoku', meaning: 'tập tục', partOfSpeech: 'danh từ' },
      { kanji: '礼儀', kana: 'れいぎ', romaji: 'reigi', meaning: 'lễ nghi', partOfSpeech: 'danh từ' },
      { kanji: 'マナー', kana: 'マナー', romaji: 'manā', meaning: 'phép lịch sự', partOfSpeech: 'danh từ' },
      { kanji: '常識', kana: 'じょうしき', romaji: 'jōshiki', meaning: 'thường thức', partOfSpeech: 'danh từ' },
      { kanji: '偏見', kana: 'へんけん', romaji: 'henken', meaning: 'định kiến', partOfSpeech: 'danh từ' },
      { kanji: '差別', kana: 'さべつ', romaji: 'sabetsu', meaning: 'phân biệt đối xử', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '平等', kana: 'びょうどう', romaji: 'byōdō', meaning: 'bình đẳng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '自由', kana: 'じゆう', romaji: 'jiyū', meaning: 'tự do', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '権利', kana: 'けんり', romaji: 'kenri', meaning: 'quyền lợi', partOfSpeech: 'danh từ' },
      { kanji: '義務', kana: 'ぎむ', romaji: 'gimu', meaning: 'nghĩa vụ', partOfSpeech: 'danh từ' },
      { kanji: '法律', kana: 'ほうりつ', romaji: 'hōritsu', meaning: 'pháp luật', partOfSpeech: 'danh từ' },
      { kanji: '規則', kana: 'きそく', romaji: 'kisoku', meaning: 'quy tắc', partOfSpeech: 'danh từ' },
      { kanji: '禁止', kana: 'きんし', romaji: 'kinshi', meaning: 'cấm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '許可', kana: 'きょか', romaji: 'kyoka', meaning: 'cho phép', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '承認', kana: 'しょうにん', romaji: 'shōnin', meaning: 'phê duyệt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '拒否', kana: 'きょひ', romaji: 'kyohi', meaning: 'từ chối', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '同意', kana: 'どうい', romaji: 'dōi', meaning: 'đồng ý', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '反対', kana: 'はんたい', romaji: 'hantai', meaning: 'phản đối', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '賛成', kana: 'さんせい', romaji: 'sansei', meaning: 'tán thành', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 309,
    jlptLevel: 'N3',
    words: [
      { kanji: '経済', kana: 'けいざい', romaji: 'keizai', meaning: 'kinh tế', partOfSpeech: 'danh từ' },
      { kanji: '政治', kana: 'せいじ', romaji: 'seiji', meaning: 'chính trị', partOfSpeech: 'danh từ' },
      { kanji: '国際', kana: 'こくさい', romaji: 'kokusai', meaning: 'quốc tế', partOfSpeech: 'danh từ' },
      { kanji: '国内', kana: 'こくない', romaji: 'kokunai', meaning: 'trong nước', partOfSpeech: 'danh từ' },
      { kanji: '海外', kana: 'かいがい', romaji: 'kaigai', meaning: 'nước ngoài', partOfSpeech: 'danh từ' },
      { kanji: '貿易', kana: 'ぼうえき', romaji: 'bōeki', meaning: 'thương mại', partOfSpeech: 'danh từ' },
      { kanji: '輸出', kana: 'ゆしゅつ', romaji: 'yushutsu', meaning: 'xuất khẩu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '輸入', kana: 'ゆにゅう', romaji: 'yunyu', meaning: 'nhập khẩu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '物価', kana: 'ぶっか', romaji: 'bukka', meaning: 'giá cả', partOfSpeech: 'danh từ' },
      { kanji: 'インフレ', kana: 'インフレ', romaji: 'infure', meaning: 'lạm phát', partOfSpeech: 'danh từ' },
      { kanji: '景気', kana: 'けいき', romaji: 'keiki', meaning: 'tình hình kinh tế', partOfSpeech: 'danh từ' },
      { kanji: '不況', kana: 'ふきょう', romaji: 'fukyō', meaning: 'suy thoái', partOfSpeech: 'danh từ' },
      { kanji: '税金', kana: 'ぜいきん', romaji: 'zeikin', meaning: 'thuế', partOfSpeech: 'danh từ' },
      { kanji: '予算', kana: 'よさん', romaji: 'yosan', meaning: 'ngân sách', partOfSpeech: 'danh từ' },
      { kanji: '赤字', kana: 'あかじ', romaji: 'akaji', meaning: 'thâm hụt', partOfSpeech: 'danh từ' },
      { kanji: '黒字', kana: 'くろじ', romaji: 'kuroji', meaning: 'thặng dư', partOfSpeech: 'danh từ' },
      { kanji: '投資', kana: 'とうし', romaji: 'tōshi', meaning: 'đầu tư', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '節約', kana: 'せつやく', romaji: 'setsuyaku', meaning: 'tiết kiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '浪費', kana: 'ろうひ', romaji: 'rōhi', meaning: 'lãng phí', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '消費', kana: 'しょうひ', romaji: 'shōhi', meaning: 'tiêu dùng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '需要', kana: 'じゅよう', romaji: 'juyō', meaning: 'nhu cầu', partOfSpeech: 'danh từ' },
      { kanji: '供給', kana: 'きょうきゅう', romaji: 'kyōkyū', meaning: 'cung cấp', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 310,
    jlptLevel: 'N3',
    words: [
      { kanji: '環境', kana: 'かんきょう', romaji: 'kankyō', meaning: 'môi trường', partOfSpeech: 'danh từ' },
      { kanji: '自然', kana: 'しぜん', romaji: 'shizen', meaning: 'tự nhiên', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '資源', kana: 'しげん', romaji: 'shigen', meaning: 'tài nguyên', partOfSpeech: 'danh từ' },
      { kanji: 'エネルギー', kana: 'エネルギー', romaji: 'enerugī', meaning: 'năng lượng', partOfSpeech: 'danh từ' },
      { kanji: '汚染', kana: 'おせん', romaji: 'osen', meaning: 'ô nhiễm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '温暖化', kana: 'おんだんか', romaji: 'ondanka', meaning: 'nóng lên toàn cầu', partOfSpeech: 'danh từ' },
      { kanji: '再生', kana: 'さいせい', romaji: 'saisei', meaning: 'tái sinh, tái chế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '節電', kana: 'せつでん', romaji: 'setsuden', meaning: 'tiết kiệm điện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '節水', kana: 'せっすい', romaji: 'sessui', meaning: 'tiết kiệm nước', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '分別', kana: 'ぶんべつ', romaji: 'bunbetsu', meaning: 'phân loại (rác)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '地球', kana: 'ちきゅう', romaji: 'chikyū', meaning: 'Trái Đất', partOfSpeech: 'danh từ' },
      { kanji: '大気', kana: 'たいき', romaji: 'taiki', meaning: 'khí quyển', partOfSpeech: 'danh từ' },
      { kanji: '森林', kana: 'しんりん', romaji: 'shinrin', meaning: 'rừng', partOfSpeech: 'danh từ' },
      { kanji: '生物', kana: 'せいぶつ', romaji: 'seibutsu', meaning: 'sinh vật', partOfSpeech: 'danh từ' },
      { kanji: '絶滅', kana: 'ぜつめつ', romaji: 'zetsumetsu', meaning: 'tuyệt chủng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '保護', kana: 'ほご', romaji: 'hogo', meaning: 'bảo vệ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '保全', kana: 'ほぜん', romaji: 'hozen', meaning: 'bảo tồn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '持続', kana: 'じぞく', romaji: 'jizoku', meaning: 'bền vững', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '循環', kana: 'じゅんかん', romaji: 'junkan', meaning: 'tuần hoàn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '減らす', kana: 'へらす', romaji: 'herasu', meaning: 'giảm bớt', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '増やす', kana: 'ふやす', romaji: 'fuyasu', meaning: 'tăng thêm', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '枯れる', kana: 'かれる', romaji: 'kareru', meaning: 'héo, khô', partOfSpeech: 'động từ nhóm 2' },
    ],
  },
  {
    lessonNumber: 311,
    jlptLevel: 'N3',
    words: [
      { kanji: '技術', kana: 'ぎじゅつ', romaji: 'gijutsu', meaning: 'kỹ thuật', partOfSpeech: 'danh từ' },
      { kanji: '科学', kana: 'かがく', romaji: 'kagaku', meaning: 'khoa học', partOfSpeech: 'danh từ' },
      { kanji: '研究', kana: 'けんきゅう', romaji: 'kenkyū', meaning: 'nghiên cứu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '実験', kana: 'じっけん', romaji: 'jikken', meaning: 'thí nghiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発明', kana: 'はつめい', romaji: 'hatsumei', meaning: 'phát minh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発見', kana: 'はっけん', romaji: 'hakken', meaning: 'phát hiện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '進歩', kana: 'しんぽ', romaji: 'shinpo', meaning: 'tiến bộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発展', kana: 'はってん', romaji: 'hatten', meaning: 'phát triển', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '革新', kana: 'かくしん', romaji: 'kakushin', meaning: 'đổi mới', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '人工知能', kana: 'じんこうちのう', romaji: 'jinkō chinō', meaning: 'trí tuệ nhân tạo', partOfSpeech: 'danh từ' },
      { kanji: 'ロボット', kana: 'ロボット', romaji: 'robotto', meaning: 'robot', partOfSpeech: 'danh từ' },
      { kanji: '自動', kana: 'じどう', romaji: 'jidō', meaning: 'tự động', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '操作', kana: 'そうさ', romaji: 'sōsa', meaning: 'thao tác', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '設定', kana: 'せってい', romaji: 'settei', meaning: 'cài đặt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '更新', kana: 'こうしん', romaji: 'kōshin', meaning: 'cập nhật', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '接続', kana: 'せつぞく', romaji: 'setsuzoku', meaning: 'kết nối', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '通信', kana: 'つうしん', romaji: 'tsūshin', meaning: 'thông tin liên lạc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '情報', kana: 'じょうほう', romaji: 'jōhō', meaning: 'thông tin', partOfSpeech: 'danh từ' },
      { kanji: 'データ', kana: 'データ', romaji: 'dēta', meaning: 'dữ liệu', partOfSpeech: 'danh từ' },
      { kanji: 'セキュリティ', kana: 'セキュリティ', romaji: 'sekyuriti', meaning: 'bảo mật', partOfSpeech: 'danh từ' },
      { kanji: '故障', kana: 'こしょう', romaji: 'koshō', meaning: 'hỏng hóc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '修理', kana: 'しゅうり', romaji: 'shūri', meaning: 'sửa chữa', partOfSpeech: 'danh từ, động từ する' },
    ],
  },

  // ─── N2 bổ sung (411–417) ───
  {
    lessonNumber: 411,
    jlptLevel: 'N2',
    words: [
      { kanji: '議論', kana: 'ぎろん', romaji: 'giron', meaning: 'tranh luận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '論争', kana: 'ろんそう', romaji: 'ronsō', meaning: 'tranh cãi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '主張', kana: 'しゅちょう', romaji: 'shuchō', meaning: 'chủ trương', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '見解', kana: 'けんかい', romaji: 'kenkai', meaning: 'quan điểm', partOfSpeech: 'danh từ' },
      { kanji: '見方', kana: 'みかた', romaji: 'mikata', meaning: 'cách nhìn', partOfSpeech: 'danh từ' },
      { kanji: '視点', kana: 'してん', romaji: 'shiten', meaning: 'góc nhìn', partOfSpeech: 'danh từ' },
      { kanji: '立場', kana: 'たちば', romaji: 'tachiba', meaning: 'lập trường', partOfSpeech: 'danh từ' },
      { kanji: '利害', kana: 'りがい', romaji: 'rigai', meaning: 'lợi ích', partOfSpeech: 'danh từ' },
      { kanji: '妥協', kana: 'だきょう', romaji: 'dakyō', meaning: 'thỏa hiệp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '合意', kana: 'ごうい', romaji: 'gōi', meaning: 'thỏa thuận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '合意形成', kana: 'ごういけいせい', romaji: 'gōi keisei', meaning: 'hình thành thỏa thuận', partOfSpeech: 'danh từ' },
      { kanji: '調整', kana: 'ちょうせい', romaji: 'chōsei', meaning: 'điều chỉnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '交渉', kana: 'こうしょう', romaji: 'kōshō', meaning: 'đàm phán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '譲歩', kana: 'じょうほ', romaji: 'jōho', meaning: 'nhượng bộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '譲る', kana: 'ゆずる', romaji: 'yuzuru', meaning: 'nhường', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '譲らない', kana: 'ゆずらない', romaji: 'yuzuranai', meaning: 'không nhường', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '納得', kana: 'なっとく', romaji: 'nattoku', meaning: 'thuyết phục, đồng ý', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '納得感', kana: 'なっとくかん', romaji: 'nattokukan', meaning: 'cảm giác thuyết phục', partOfSpeech: 'danh từ' },
      { kanji: '説得', kana: 'せっとく', romaji: 'settoku', meaning: 'thuyết phục', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '説明', kana: 'せつめい', romaji: 'setsumei', meaning: 'giải thích', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '理解', kana: 'りかい', romaji: 'rikai', meaning: 'hiểu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '誤解', kana: 'ごかい', romaji: 'gokai', meaning: 'hiểu lầm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '勘違い', kana: 'かんちがい', romaji: 'kanchigai', meaning: 'nhầm lẫn', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 412,
    jlptLevel: 'N2',
    words: [
      { kanji: '方針', kana: 'ほうしん', romaji: 'hōshin', meaning: 'phương châm', partOfSpeech: 'danh từ' },
      { kanji: '政策', kana: 'せいさく', romaji: 'seisaku', meaning: 'chính sách', partOfSpeech: 'danh từ' },
      { kanji: '戦略', kana: 'せんりゃく', romaji: 'senryaku', meaning: 'chiến lược', partOfSpeech: 'danh từ' },
      { kanji: '戦術', kana: 'せんじゅつ', romaji: 'senjutsu', meaning: 'chiến thuật', partOfSpeech: 'danh từ' },
      { kanji: '方策', kana: 'ほうさく', romaji: 'hōsaku', meaning: 'biện pháp', partOfSpeech: 'danh từ' },
      { kanji: '手段', kana: 'しゅだん', romaji: 'shudan', meaning: 'phương tiện', partOfSpeech: 'danh từ' },
      { kanji: '方法', kana: 'ほうほう', romaji: 'hōhō', meaning: 'phương pháp', partOfSpeech: 'danh từ' },
      { kanji: '手法', kana: 'しゅほう', romaji: 'shuhō', meaning: 'kỹ thuật, phương pháp', partOfSpeech: 'danh từ' },
      { kanji: '実施', kana: 'じっし', romaji: 'jisshi', meaning: 'thực hiện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '実行', kana: 'じっこう', romaji: 'jikkō', meaning: 'thực thi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '遂行', kana: 'すいこう', romaji: 'suikō', meaning: 'tiến hành đến cùng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '着手', kana: 'ちゃくしゅ', romaji: 'chakushu', meaning: 'bắt tay vào', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '完了', kana: 'かんりょう', romaji: 'kanryō', meaning: 'hoàn thành', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '達成', kana: 'たっせい', romaji: 'tassei', meaning: 'đạt được', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '未達', kana: 'みたつ', romaji: 'mitatsu', meaning: 'chưa đạt', partOfSpeech: 'danh từ' },
      { kanji: '遅延', kana: 'ちえん', romaji: 'chien', meaning: 'trì hoãn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '前倒し', kana: 'まえだおし', romaji: 'maedaoshi', meaning: 'làm sớm hơn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '優先順位', kana: 'ゆうせんじゅんい', romaji: 'yūsen jun\'i', meaning: 'thứ tự ưu tiên', partOfSpeech: 'danh từ' },
      { kanji: '段取り', kana: 'だんどり', romaji: 'dandori', meaning: 'sắp xếp trình tự', partOfSpeech: 'danh từ' },
      { kanji: '工程', kana: 'こうてい', romaji: 'kōtei', meaning: 'công đoạn', partOfSpeech: 'danh từ' },
      { kanji: '進捗', kana: 'しんちょく', romaji: 'shinchoku', meaning: 'tiến độ', partOfSpeech: 'danh từ' },
      { kanji: '停滞', kana: 'ていたい', romaji: 'teitai', meaning: 'trì trệ', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 413,
    jlptLevel: 'N2',
    words: [
      { kanji: '評価', kana: 'ひょうか', romaji: 'hyōka', meaning: 'đánh giá', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '判定', kana: 'はんてい', romaji: 'hantei', meaning: 'phán đoán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '判断', kana: 'はんだん', romaji: 'handan', meaning: 'phán đoán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '分析', kana: 'ぶんせき', romaji: 'bunseki', meaning: 'phân tích', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '検討', kana: 'けんとう', romaji: 'kentō', meaning: 'xem xét', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '検証', kana: 'けんしょう', romaji: 'kenshō', meaning: 'kiểm chứng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '確認', kana: 'かくにん', romaji: 'kakunin', meaning: 'xác nhận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '精査', kana: 'せいさ', romaji: 'seisa', meaning: 'rà soát kỹ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '監査', kana: 'かんさ', romaji: 'kansa', meaning: 'kiểm toán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '監視', kana: 'かんし', romaji: 'kanshi', meaning: 'giám sát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '管理', kana: 'かんり', romaji: 'kanri', meaning: 'quản lý', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '運用', kana: 'うんよう', romaji: "un'yō", meaning: 'vận hành', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '運営', kana: 'うんえい', romaji: 'un\'ei', meaning: 'điều hành', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '統制', kana: 'とうせい', romaji: 'tōsei', meaning: 'kiểm soát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '規制', kana: 'きせい', romaji: 'kisei', meaning: 'quy định, kiểm soát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '制限', kana: 'せいげん', romaji: 'seigen', meaning: 'hạn chế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '緩和', kana: 'かんわ', romaji: 'kanwa', meaning: 'nới lỏng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '強化', kana: 'きょうか', romaji: 'kyōka', meaning: 'củng cố', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '徹底', kana: 'てってい', romaji: 'tettei', meaning: 'triệt để', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '徹する', kana: 'てっする', romaji: 'tessuru', meaning: 'thực hiện triệt để', partOfSpeech: 'động từ する' },
      { kanji: '徹底する', kana: 'てっていする', romaji: 'tettei suru', meaning: 'làm triệt để', partOfSpeech: 'động từ する' },
      { kanji: '徹夜', kana: 'てつや', romaji: 'tetsuya', meaning: 'thức trắng', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 414,
    jlptLevel: 'N2',
    words: [
      { kanji: '貢献', kana: 'こうけん', romaji: 'kōken', meaning: 'đóng góp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '協力', kana: 'きょうりょく', romaji: 'kyōryoku', meaning: 'hợp tác', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '連携', kana: 'れんけい', romaji: 'renkei', meaning: 'phối hợp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '提携', kana: 'ていけい', romaji: 'teikei', meaning: 'liên kết (doanh nghiệp)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '共同', kana: 'きょうどう', romaji: 'kyōdō', meaning: 'cùng nhau', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '役割', kana: 'やくわり', romaji: 'yakuwari', meaning: 'vai trò', partOfSpeech: 'danh từ' },
      { kanji: '責任分担', kana: 'せきにんぶんたん', romaji: 'sekinin buntan', meaning: 'phân chia trách nhiệm', partOfSpeech: 'danh từ' },
      { kanji: '支援', kana: 'しえん', romaji: 'shien', meaning: 'hỗ trợ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '援助', kana: 'えんじょ', romaji: 'enjo', meaning: 'viện trợ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '後援', kana: 'こうえん', romaji: 'kōen', meaning: 'hậu thuẫn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '激励', kana: 'げきれい', romaji: 'gekirei', meaning: 'khích lệ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '鼓舞', kana: 'こぶ', romaji: 'kobu', meaning: 'cổ vũ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '信頼', kana: 'しんらい', romaji: 'shinrai', meaning: 'tin cậy', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '信用', kana: 'しんよう', romaji: "shin'yō", meaning: 'tín dụng, tin tưởng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '不信', kana: 'ふしん', romaji: 'fushin', meaning: 'không tin', partOfSpeech: 'danh từ' },
      { kanji: '疑念', kana: 'ぎねん', romaji: 'ginen', meaning: 'nghi ngờ', partOfSpeech: 'danh từ' },
      { kanji: '疑う', kana: 'うたがう', romaji: 'utagau', meaning: 'nghi ngờ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '裏切る', kana: 'うらぎる', romaji: 'uragiru', meaning: 'phản bội', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '裏切り', kana: 'うらぎり', romaji: 'uragiri', meaning: 'sự phản bội', partOfSpeech: 'danh từ' },
      { kanji: '忠実', kana: 'ちゅうじつ', romaji: 'chūjitsu', meaning: 'trung thành', partOfSpeech: 'tính từ na' },
      { kanji: '誠実', kana: 'せいじつ', romaji: 'seijitsu', meaning: 'chân thành', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '寛容', kana: 'かんよう', romaji: 'kan\'yō', meaning: 'khoan dung', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '包容', kana: 'ほうよう', romaji: 'hōyō', meaning: 'bao dung', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '協調', kana: 'きょうちょう', romaji: 'kyōchō', meaning: 'phối hợp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '調和', kana: 'ちょうわ', romaji: 'chōwa', meaning: 'hài hòa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '結束', kana: 'けっそく', romaji: 'kessoku', meaning: 'đoàn kết', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '団結', kana: 'だんけつ', romaji: 'danketsu', meaning: 'đoàn kết', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '一体', kana: 'いったい', romaji: 'ittai', meaning: 'nhất thể', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '一致', kana: 'いっち', romaji: 'icchi', meaning: 'nhất trí', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '連帯', kana: 'れんたい', romaji: 'rentai', meaning: 'liên đới', partOfSpeech: 'danh từ' },
      { kanji: '相互', kana: 'そうご', romaji: 'sōgo', meaning: 'lẫn nhau', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '相互理解', kana: 'そうごりかい', romaji: 'sōgo rikai', meaning: 'hiểu nhau', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 415,
    jlptLevel: 'N2',
    words: [
      { kanji: '危機', kana: 'きき', romaji: 'kiki', meaning: 'khủng hoảng', partOfSpeech: 'danh từ' },
      { kanji: '危険', kana: 'きけん', romaji: 'kiken', meaning: 'nguy hiểm', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: 'リスク', kana: 'リスク', romaji: 'risuku', meaning: 'rủi ro', partOfSpeech: 'danh từ' },
      { kanji: '被害', kana: 'ひがい', romaji: 'higai', meaning: 'thiệt hại', partOfSpeech: 'danh từ' },
      { kanji: '損害', kana: 'そんがい', romaji: 'songai', meaning: 'tổn thất', partOfSpeech: 'danh từ' },
      { kanji: '災害', kana: 'さいがい', romaji: 'saigai', meaning: 'thiên tai', partOfSpeech: 'danh từ' },
      { kanji: '事故', kana: 'じこ', romaji: 'jiko', meaning: 'tai nạn', partOfSpeech: 'danh từ' },
      { kanji: '故障', kana: 'こしょう', romaji: 'koshō', meaning: 'hỏng hóc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '障害', kana: 'しょうがい', romaji: 'shōgai', meaning: 'trở ngại', partOfSpeech: 'danh từ' },
      { kanji: '混乱', kana: 'こんらん', romaji: 'konran', meaning: 'hỗn loạn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '騒動', kana: 'そうどう', romaji: 'sōdō', meaning: 'náo loạn', partOfSpeech: 'danh từ' },
      { kanji: '騒ぎ', kana: 'さわぎ', romaji: 'sawagi', meaning: 'sự ồn ào', partOfSpeech: 'danh từ' },
      { kanji: '騒ぐ', kana: 'さわぐ', romaji: 'sawagu', meaning: 'làm ồn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '騒がしい', kana: 'さわがしい', romaji: 'sawagashii', meaning: 'ồn ào', partOfSpeech: 'tính từ i' },
      { kanji: '緊急', kana: 'きんきゅう', romaji: 'kinkyū', meaning: 'khẩn cấp', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '避難', kana: 'ひなん', romaji: 'hinan', meaning: 'sơ tán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '避ける', kana: 'さける', romaji: 'sakeru', meaning: 'tránh', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '防ぐ', kana: 'ふせぐ', romaji: 'fusegu', meaning: 'ngăn chặn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '防止', kana: 'ぼうし', romaji: 'bōshi', meaning: 'phòng ngừa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '予防', kana: 'よぼう', romaji: 'yobō', meaning: 'dự phòng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '対策', kana: 'たいさく', romaji: 'taisaku', meaning: 'biện pháp đối phó', partOfSpeech: 'danh từ' },
      { kanji: '対応', kana: 'たいおう', romaji: 'taiō', meaning: 'ứng phó', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '復旧', kana: 'ふっきゅう', romaji: 'fukkyū', meaning: 'khôi phục', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '復興', kana: 'ふっこう', romaji: 'fukkō', meaning: 'tái thiết', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
];
