// Bổ sung từ vựng N3 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 320-325.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N3_PART3: JlptVocabUnit[] = [
  {
    lessonNumber: 320,
    jlptLevel: 'N3',
    words: [
      { kanji: '光景', kana: 'こうけい', romaji: 'kōkei', meaning: 'cảnh tượng, quang cảnh', partOfSpeech: 'danh từ' },
      { kanji: '向かい', kana: 'むかい', romaji: 'mukai', meaning: 'phía đối diện', partOfSpeech: 'danh từ' },
      { kanji: '向きます', kana: 'むきます', romaji: 'mukimasu', meaning: 'hướng về, quay mặt về', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '向けます', kana: 'むけます', romaji: 'mukemasu', meaning: 'hướng, chĩa (về phía nào đó)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '好み', kana: 'このみ', romaji: 'konomi', meaning: 'sở thích, thị hiếu', partOfSpeech: 'danh từ' },
      { kanji: '好みます', kana: 'このみます', romaji: 'konomimasu', meaning: 'ưa thích', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '工場', kana: 'こうば', romaji: 'kōba', meaning: 'nhà máy, xưởng (nhỏ)', partOfSpeech: 'danh từ' },
      { kanji: '幸い', kana: 'さいわい', romaji: 'saiwai', meaning: 'may mắn, hạnh phúc', partOfSpeech: 'danh từ, tính từ na, phó từ' },
      { kanji: '幸運', kana: 'こううん', romaji: 'kōun', meaning: 'vận may', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '幸福', kana: 'こうふく', romaji: 'kōfuku', meaning: 'hạnh phúc', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '広がります', kana: 'ひろがります', romaji: 'hirogarimasu', meaning: 'lan rộng, mở rộng ra', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '攻撃', kana: 'こうげき', romaji: 'kōgeki', meaning: 'sự tấn công, công kích', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '更に', kana: 'さらに', romaji: 'sarani', meaning: 'hơn nữa, thêm nữa', partOfSpeech: 'phó từ' },
      { kanji: '航空', kana: 'こうくう', romaji: 'kōkū', meaning: 'hàng không', partOfSpeech: 'danh từ' },
      { kanji: '行き', kana: 'いき', romaji: 'iki', meaning: 'chiều đi, đi đến', partOfSpeech: 'danh từ' },
      { kanji: '行儀', kana: 'ぎょうぎ', romaji: 'gyōgi', meaning: 'phép tắc, cách cư xử', partOfSpeech: 'danh từ' },
      { kanji: '香り', kana: 'かおり', romaji: 'kaori', meaning: 'hương thơm', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 321,
    jlptLevel: 'N3',
    words: [
      { kanji: '高速', kana: 'こうそく', romaji: 'kōsoku', meaning: 'tốc độ cao', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '合図', kana: 'あいず', romaji: 'aizu', meaning: 'dấu hiệu, tín hiệu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '豪華', kana: 'ごうか', romaji: 'gōka', meaning: 'xa hoa, lộng lẫy', partOfSpeech: 'tính từ na' },
      { kanji: '国家', kana: 'こっか', romaji: 'kokka', meaning: 'quốc gia', partOfSpeech: 'danh từ' },
      { kanji: '国会', kana: 'こっかい', romaji: 'kokkai', meaning: 'quốc hội', partOfSpeech: 'danh từ' },
      { kanji: '国境', kana: 'こっきょう', romaji: 'kokkyō', meaning: 'biên giới quốc gia', partOfSpeech: 'danh từ' },
      { kanji: '国語', kana: 'こくご', romaji: 'kokugo', meaning: 'quốc ngữ, môn tiếng Nhật (ở trường)', partOfSpeech: 'danh từ' },
      { kanji: '国民', kana: 'こくみん', romaji: 'kokumin', meaning: 'quốc dân, công dân', partOfSpeech: 'danh từ' },
      { kanji: '穀物', kana: 'こくもつ', romaji: 'kokumotsu', meaning: 'ngũ cốc', partOfSpeech: 'danh từ' },
      { kanji: '黒板', kana: 'こくばん', romaji: 'kokuban', meaning: 'bảng đen', partOfSpeech: 'danh từ' },
      { kanji: '腰', kana: 'こし', romaji: 'koshi', meaning: 'thắt lưng, hông', partOfSpeech: 'danh từ' },
      { kanji: '骨', kana: 'ほね', romaji: 'hone', meaning: 'xương', partOfSpeech: 'danh từ' },
      { kanji: '骨折', kana: 'こっせつ', romaji: 'kossetsu', meaning: 'sự gãy xương', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '今に', kana: 'いまに', romaji: 'imani', meaning: 'chẳng bao lâu nữa, sớm muộn gì', partOfSpeech: 'phó từ' },
      { kanji: '今回', kana: 'こんかい', romaji: 'konkai', meaning: 'lần này', partOfSpeech: 'danh từ' },
      { kanji: '今日', kana: 'こんにち', romaji: 'konnichi', meaning: 'ngày nay, hiện nay', partOfSpeech: 'danh từ' },
      { kanji: '困難', kana: 'こんなん', romaji: 'konnan', meaning: 'sự khó khăn', partOfSpeech: 'danh từ, tính từ na' },
    ],
  },
  {
    lessonNumber: 322,
    jlptLevel: 'N3',
    words: [
      { kanji: '婚約', kana: 'こんやく', romaji: 'konyaku', meaning: 'sự đính hôn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '混雑', kana: 'こんざつ', romaji: 'konzatsu', meaning: 'sự hỗn loạn, đông đúc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '左右', kana: 'さゆう', romaji: 'sayū', meaning: 'trái phải; chi phối', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '差', kana: 'さ', romaji: 'sa', meaning: 'sự chênh lệch, khác biệt', partOfSpeech: 'danh từ' },
      { kanji: '砂漠', kana: 'さばく', romaji: 'sabaku', meaning: 'sa mạc', partOfSpeech: 'danh từ' },
      { kanji: '鎖', kana: 'くさり', romaji: 'kusari', meaning: 'dây xích', partOfSpeech: 'danh từ' },
      { kanji: '座席', kana: 'ざせき', romaji: 'zaseki', meaning: 'chỗ ngồi, ghế ngồi', partOfSpeech: 'danh từ' },
      { kanji: '再び', kana: 'ふたたび', romaji: 'futatabi', meaning: 'một lần nữa, lại lần nữa', partOfSpeech: 'phó từ' },
      { kanji: '最終', kana: 'さいしゅう', romaji: 'saishū', meaning: 'cuối cùng, chuyến cuối', partOfSpeech: 'danh từ' },
      { kanji: '最低', kana: 'さいてい', romaji: 'saitei', meaning: 'thấp nhất, tệ nhất', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '済ませます', kana: 'すませます', romaji: 'sumasemasu', meaning: 'làm xong, hoàn tất', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '際', kana: 'さい', romaji: 'sai', meaning: 'lúc, khi, dịp', partOfSpeech: 'danh từ' },
      { kanji: '罪', kana: 'つみ', romaji: 'tsumi', meaning: 'tội, tội lỗi', partOfSpeech: 'danh từ' },
      { kanji: '財産', kana: 'ざいさん', romaji: 'zaisan', meaning: 'tài sản', partOfSpeech: 'danh từ' },
      { kanji: '作業', kana: 'さぎょう', romaji: 'sagyō', meaning: 'công việc, thao tác', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '作物', kana: 'さくもつ', romaji: 'sakumotsu', meaning: 'nông sản, hoa màu', partOfSpeech: 'danh từ' },
      { kanji: '作法', kana: 'さほう', romaji: 'sahō', meaning: 'phép tắc, lễ nghi', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 323,
    jlptLevel: 'N3',
    words: [
      { kanji: '札', kana: 'さつ', romaji: 'satsu', meaning: 'tờ tiền giấy, thẻ, nhãn', partOfSpeech: 'danh từ' },
      { kanji: '殺します', kana: 'ころします', romaji: 'koroshimasu', meaning: 'giết', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '酸素', kana: 'さんそ', romaji: 'sanso', meaning: 'ô xy', partOfSpeech: 'danh từ' },
      { kanji: '残します', kana: 'のこします', romaji: 'nokoshimasu', meaning: 'để lại, giữ lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '残り', kana: 'のこり', romaji: 'nokori', meaning: 'phần còn lại', partOfSpeech: 'danh từ' },
      { kanji: '使用', kana: 'しよう', romaji: 'shiyō', meaning: 'sự sử dụng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '刺激', kana: 'しげき', romaji: 'shigeki', meaning: 'sự kích thích', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '始まり', kana: 'はじまり', romaji: 'hajimari', meaning: 'khởi nguồn, sự bắt đầu', partOfSpeech: 'danh từ' },
      { kanji: '市場', kana: 'いちば', romaji: 'ichiba', meaning: 'chợ, thị trường', partOfSpeech: 'danh từ' },
      { kanji: '思わず', kana: 'おもわず', romaji: 'omowazu', meaning: 'vô tình, không kìm được mà', partOfSpeech: 'phó từ' },
      { kanji: '思想', kana: 'しそう', romaji: 'shisō', meaning: 'tư tưởng', partOfSpeech: 'danh từ' },
      { kanji: '指導', kana: 'しどう', romaji: 'shidō', meaning: 'sự hướng dẫn, chỉ đạo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '支えます', kana: 'ささえます', romaji: 'sasaemasu', meaning: 'nâng đỡ, chống đỡ, hỗ trợ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '支給', kana: 'しきゅう', romaji: 'shikyū', meaning: 'sự chi trả, cấp phát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '支出', kana: 'ししゅつ', romaji: 'shishutsu', meaning: 'chi tiêu, khoản chi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '支払い', kana: 'しはらい', romaji: 'shiharai', meaning: 'sự thanh toán', partOfSpeech: 'danh từ' },
      { kanji: '支払います', kana: 'しはらいます', romaji: 'shiharaimasu', meaning: 'thanh toán, trả tiền', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 324,
    jlptLevel: 'N3',
    words: [
      { kanji: '止します', kana: 'よします', romaji: 'yoshimasu', meaning: 'từ bỏ, thôi không làm nữa', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '至ります', kana: 'いたります', romaji: 'itarimasu', meaning: 'đi đến, dẫn đến', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '詩人', kana: 'しじん', romaji: 'shijin', meaning: 'nhà thơ', partOfSpeech: 'danh từ' },
      { kanji: '試し', kana: 'ためし', romaji: 'tameshi', meaning: 'sự thử nghiệm', partOfSpeech: 'danh từ' },
      { kanji: '資本', kana: 'しほん', romaji: 'shihon', meaning: 'vốn, tư bản', partOfSpeech: 'danh từ' },
      { kanji: '事態', kana: 'じたい', romaji: 'jitai', meaning: 'tình hình, tình thế', partOfSpeech: 'danh từ' },
      { kanji: '事務', kana: 'じむ', romaji: 'jimu', meaning: 'công việc văn phòng', partOfSpeech: 'danh từ' },
      { kanji: '持ち上げます', kana: 'もちあげます', romaji: 'mochiagemasu', meaning: 'nâng lên, nhấc lên', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '時期', kana: 'じき', romaji: 'jiki', meaning: 'thời kỳ, mùa', partOfSpeech: 'danh từ' },
      { kanji: '時刻', kana: 'じこく', romaji: 'jikoku', meaning: 'thời khắc, giờ giấc', partOfSpeech: 'danh từ' },
      { kanji: '次々', kana: 'つぎつぎ', romaji: 'tsugitsugi', meaning: 'liên tiếp, lần lượt', partOfSpeech: 'phó từ' },
      { kanji: '次第', kana: 'しだい', romaji: 'shidai', meaning: 'tùy thuộc vào; trình tự', partOfSpeech: 'danh từ' },
      { kanji: '示します', kana: 'しめします', romaji: 'shimeshimasu', meaning: 'chỉ ra, biểu thị', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '自殺', kana: 'じさつ', romaji: 'jisatsu', meaning: 'sự tự sát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '自慢', kana: 'じまん', romaji: 'jiman', meaning: 'sự tự hào, khoe khoang', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '辞めます', kana: 'やめます', romaji: 'yamemasu', meaning: 'nghỉ việc, từ chức', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '七', kana: 'しち', romaji: 'shichi', meaning: 'số bảy (cách đọc Hán Nhật)', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 325,
    jlptLevel: 'N3',
    words: [
      { kanji: '失います', kana: 'うしないます', romaji: 'ushinaimasu', meaning: 'mất, đánh mất', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '失望', kana: 'しつぼう', romaji: 'shitsubō', meaning: 'sự thất vọng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '質', kana: 'しつ', romaji: 'shitsu', meaning: 'chất lượng, bản chất', partOfSpeech: 'danh từ' },
      { kanji: '実', kana: 'み', romaji: 'mi', meaning: 'quả, hạt', partOfSpeech: 'danh từ' },
      { kanji: '実に', kana: 'じつに', romaji: 'jitsuni', meaning: 'thật sự, quả thực', partOfSpeech: 'phó từ' },
      { kanji: '芝居', kana: 'しばい', romaji: 'shibai', meaning: 'vở kịch, tuồng', partOfSpeech: 'danh từ' },
      { kanji: '芝生', kana: 'しばふ', romaji: 'shibafu', meaning: 'bãi cỏ', partOfSpeech: 'danh từ' },
      { kanji: '主義', kana: 'しゅぎ', romaji: 'shugi', meaning: 'chủ nghĩa, nguyên tắc', partOfSpeech: 'danh từ' },
      { kanji: '主婦', kana: 'しゅふ', romaji: 'shufu', meaning: 'nội trợ', partOfSpeech: 'danh từ' },
      { kanji: '主要', kana: 'しゅよう', romaji: 'shuyō', meaning: 'chủ yếu, chính', partOfSpeech: 'tính từ na' },
      { kanji: '取り上げます', kana: 'とりあげます', romaji: 'toriagemasu', meaning: 'lấy đi, tịch thu; đề cập tới', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '取れます', kana: 'とれます', romaji: 'toremasu', meaning: 'bị tuột ra, rơi ra', partOfSpeech: 'động từ nhóm 2' },
    ],
  },
];
