// Bổ sung từ vựng N5 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 250-255.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N5: JlptVocabUnit[] = [
  {
    lessonNumber: 250,
    jlptLevel: 'N5',
    words: [
      { kana: 'あの', romaji: 'ano', meaning: 'kia, đó (chỉ vật xa cả người nói và người nghe)', partOfSpeech: 'từ hạn định' },
      { kanji: '浴びます', kana: 'あびます', romaji: 'abimasu', meaning: 'tắm vòi sen, dội nước lên người', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'いかが', romaji: 'ikaga', meaning: 'thế nào (cách nói lịch sự của どう)', partOfSpeech: 'phó từ' },
      { kana: 'おばあさん', romaji: 'obāsan', meaning: 'bà, bà cụ (người phụ nữ lớn tuổi)', partOfSpeech: 'danh từ' },
      { kana: 'おまわりさん', romaji: 'omawarisan', meaning: 'chú công an (cách gọi thân mật)', partOfSpeech: 'danh từ' },
      { kanji: 'お菓子', kana: 'おかし', romaji: 'okashi', meaning: 'bánh kẹo, đồ ngọt', partOfSpeech: 'danh từ' },
      { kanji: 'お皿', kana: 'おさら', romaji: 'osara', meaning: 'cái đĩa', partOfSpeech: 'danh từ' },
      { kanji: 'お酒', kana: 'おさけ', romaji: 'osake', meaning: 'rượu', partOfSpeech: 'danh từ' },
      { kanji: 'お風呂', kana: 'おふろ', romaji: 'ofuro', meaning: 'bồn tắm, sự tắm', partOfSpeech: 'danh từ' },
      { kanji: 'お弁当', kana: 'おべんとう', romaji: 'obentō', meaning: 'cơm hộp', partOfSpeech: 'danh từ' },
      { kana: 'カレー', romaji: 'karē', meaning: 'cà ri', partOfSpeech: 'danh từ' },
      { kana: 'ギター', romaji: 'gitā', meaning: 'đàn ghi-ta', partOfSpeech: 'danh từ' },
      { kana: 'きれい', romaji: 'kirei', meaning: 'đẹp, sạch sẽ', partOfSpeech: 'tính từ na' },
      { kana: 'ください', romaji: 'kudasai', meaning: 'xin hãy cho, làm ơn', partOfSpeech: 'cách nói lịch sự' },
      { kana: 'グラム', romaji: 'guramu', meaning: 'gam (đơn vị khối lượng)', partOfSpeech: 'danh từ' },
      { kana: 'この', romaji: 'kono', meaning: 'này', partOfSpeech: 'từ hạn định' },
      { kana: 'こんな', romaji: 'konna', meaning: 'như thế này', partOfSpeech: 'từ hạn định' },
    ],
  },
  {
    lessonNumber: 251,
    jlptLevel: 'N5',
    words: [
      { kana: 'ストーブ', romaji: 'sutōbu', meaning: 'lò sưởi', partOfSpeech: 'danh từ' },
      { kana: 'スリッパ', romaji: 'surippa', meaning: 'dép đi trong nhà', partOfSpeech: 'danh từ' },
      { kana: 'ゼロ', romaji: 'zero', meaning: 'số không', partOfSpeech: 'danh từ' },
      { kana: 'その', romaji: 'sono', meaning: 'đó', partOfSpeech: 'từ hạn định' },
      { kana: 'そば', romaji: 'soba', meaning: 'bên cạnh, gần', partOfSpeech: 'danh từ' },
      { kana: 'たいへん', romaji: 'taihen', meaning: 'rất, vô cùng; vất vả', partOfSpeech: 'phó từ' },
      { kana: 'たて', romaji: 'tate', meaning: 'chiều dọc', partOfSpeech: 'danh từ' },
      { kana: 'テープ', romaji: 'tēpu', meaning: 'băng (cát-xét, băng dính)', partOfSpeech: 'danh từ' },
      { kana: 'どうぞ', romaji: 'dōzo', meaning: 'xin mời', partOfSpeech: 'phó từ' },
      { kana: 'どの', romaji: 'dono', meaning: 'cái nào', partOfSpeech: 'từ hạn định' },
      { kana: 'など', romaji: 'nado', meaning: 'vân vân, v.v.', partOfSpeech: 'trợ từ' },
      { kana: 'バター', romaji: 'batā', meaning: 'bơ', partOfSpeech: 'danh từ' },
      { kana: 'ページ', romaji: 'pēji', meaning: 'trang (sách)', partOfSpeech: 'danh từ' },
      { kana: 'ペン', romaji: 'pen', meaning: 'bút (bút mực, bút bi)', partOfSpeech: 'danh từ' },
      { kana: 'ほか', romaji: 'hoka', meaning: 'cái khác, phần còn lại', partOfSpeech: 'danh từ' },
      { kana: 'マッチ', romaji: 'macchi', meaning: 'diêm quẹt', partOfSpeech: 'danh từ' },
      { kana: 'メートル', romaji: 'mētoru', meaning: 'mét', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 252,
    jlptLevel: 'N5',
    words: [
      { kanji: 'もう一度', kana: 'もういちど', romaji: 'mōichido', meaning: 'thêm một lần nữa', partOfSpeech: 'phó từ' },
      { kana: 'ゆっくりと', romaji: 'yukkurito', meaning: 'một cách chậm rãi, từ từ', partOfSpeech: 'phó từ' },
      { kana: 'りっぱ', romaji: 'rippa', meaning: 'lộng lẫy, xuất sắc', partOfSpeech: 'tính từ na' },
      { kana: 'レコード', romaji: 'rekōdo', meaning: 'đĩa hát', partOfSpeech: 'danh từ' },
      { kana: 'ワイシャツ', romaji: 'waishatsu', meaning: 'áo sơ mi (mặc với vest)', partOfSpeech: 'danh từ' },
      { kanji: '一', kana: 'いち', romaji: 'ichi', meaning: 'số một', partOfSpeech: 'danh từ' },
      { kanji: '一月', kana: 'ひとつき', romaji: 'hitotsuki', meaning: 'một tháng', partOfSpeech: 'danh từ' },
      { kanji: '一緒', kana: 'いっしょ', romaji: 'issho', meaning: 'cùng nhau', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '一日', kana: 'いちにち', romaji: 'ichinichi', meaning: 'một ngày; ngày mùng một', partOfSpeech: 'danh từ' },
      { kanji: '黄色い', kana: 'きいろい', romaji: 'kiiroi', meaning: 'màu vàng', partOfSpeech: 'tính từ i' },
      { kanji: '温い', kana: 'ぬるい', romaji: 'nurui', meaning: 'hơi ấm, âm ấm (nước, đồ uống nguội bớt)', partOfSpeech: 'tính từ i' },
      { kanji: '夏休み', kana: 'なつやすみ', romaji: 'natsuyasumi', meaning: 'kỳ nghỉ hè', partOfSpeech: 'danh từ' },
      { kanji: '吸います', kana: 'すいます', romaji: 'suimasu', meaning: 'hút (thuốc), hít', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '九', kana: 'きゅう', romaji: 'kyū', meaning: 'số chín', partOfSpeech: 'danh từ' },
      { kanji: '結構', kana: 'けっこう', romaji: 'kekkō', meaning: 'tốt, khá tốt; đủ rồi (từ chối lịch sự)', partOfSpeech: 'tính từ na, phó từ' },
      { kanji: '結婚', kana: 'けっこん', romaji: 'kekkon', meaning: 'kết hôn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '嫌', kana: 'いや', romaji: 'iya', meaning: 'khó chịu, không thích', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 253,
    jlptLevel: 'N5',
    words: [
      { kanji: '嫌い', kana: 'きらい', romaji: 'kirai', meaning: 'ghét, không ưa', partOfSpeech: 'tính từ na' },
      { kanji: '戸', kana: 'と', romaji: 'to', meaning: 'cửa kéo kiểu Nhật', partOfSpeech: 'danh từ' },
      { kanji: '五', kana: 'ご', romaji: 'go', meaning: 'số năm', partOfSpeech: 'danh từ' },
      { kanji: '好き', kana: 'すき', romaji: 'suki', meaning: 'thích, ưa thích', partOfSpeech: 'tính từ na' },
      { kanji: '降ります', kana: 'ふります', romaji: 'furimasu', meaning: 'rơi xuống (mưa, tuyết)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '咲きます', kana: 'さきます', romaji: 'sakimasu', meaning: 'nở (hoa)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '三', kana: 'さん', romaji: 'san', meaning: 'số ba', partOfSpeech: 'danh từ' },
      { kanji: '四', kana: 'よん', romaji: 'yon', meaning: 'số bốn', partOfSpeech: 'danh từ' },
      { kanji: '字引', kana: 'じびき', romaji: 'jibiki', meaning: 'từ điển (cách gọi cũ)', partOfSpeech: 'danh từ' },
      { kanji: '次', kana: 'つぎ', romaji: 'tsugi', meaning: 'tiếp theo, kế tiếp', partOfSpeech: 'danh từ' },
      { kanji: '七', kana: 'なな', romaji: 'nana', meaning: 'số bảy', partOfSpeech: 'danh từ' },
      { kanji: '質問', kana: 'しつもん', romaji: 'shitsumon', meaning: 'câu hỏi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '十', kana: 'じゅう', romaji: 'jū', meaning: 'số mười', partOfSpeech: 'danh từ' },
      { kanji: '出ます', kana: 'でます', romaji: 'demasu', meaning: 'ra khỏi, xuất hiện, tham gia', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '女', kana: 'おんな', romaji: 'onna', meaning: 'phụ nữ, con gái', partOfSpeech: 'danh từ' },
      { kanji: '女の子', kana: 'おんなのこ', romaji: 'onnanoko', meaning: 'bé gái, cô gái', partOfSpeech: 'danh từ' },
      { kanji: '小さな', kana: 'ちいさな', romaji: 'chiisana', meaning: 'nhỏ bé', partOfSpeech: 'từ hạn định' },
    ],
  },
  {
    lessonNumber: 254,
    jlptLevel: 'N5',
    words: [
      { kanji: '少ない', kana: 'すくない', romaji: 'sukunai', meaning: 'ít', partOfSpeech: 'tính từ i' },
      { kanji: '丈夫', kana: 'じょうぶ', romaji: 'jōbu', meaning: 'chắc chắn, khỏe mạnh', partOfSpeech: 'tính từ na' },
      { kanji: '静か', kana: 'しずか', romaji: 'shizuka', meaning: 'yên tĩnh', partOfSpeech: 'tính từ na' },
      { kanji: '先', kana: 'さき', romaji: 'saki', meaning: 'phía trước, tương lai; trước đây', partOfSpeech: 'danh từ' },
      { kanji: '多い', kana: 'おおい', romaji: 'ōi', meaning: 'nhiều', partOfSpeech: 'tính từ i' },
      { kanji: '大きな', kana: 'おおきな', romaji: 'ōkina', meaning: 'to lớn', partOfSpeech: 'từ hạn định' },
      { kanji: '大好き', kana: 'だいすき', romaji: 'daisuki', meaning: 'rất thích', partOfSpeech: 'tính từ na' },
      { kanji: '大丈夫', kana: 'だいじょうぶ', romaji: 'daijōbu', meaning: 'ổn, không sao', partOfSpeech: 'tính từ na' },
      { kanji: '大切', kana: 'たいせつ', romaji: 'taisetsu', meaning: 'quan trọng', partOfSpeech: 'tính từ na' },
      { kanji: '男の子', kana: 'おとこのこ', romaji: 'otokonoko', meaning: 'bé trai, cậu con trai', partOfSpeech: 'danh từ' },
      { kanji: '二', kana: 'に', romaji: 'ni', meaning: 'số hai', partOfSpeech: 'danh từ' },
      { kanji: '二十歳', kana: 'はたち', romaji: 'hatachi', meaning: 'hai mươi tuổi', partOfSpeech: 'danh từ' },
      { kanji: '賑やか', kana: 'にぎやか', romaji: 'nigiyaka', meaning: 'nhộn nhịp, náo nhiệt', partOfSpeech: 'tính từ na' },
      { kanji: '入ります', kana: 'はいります', romaji: 'hairimasu', meaning: 'đi vào, chứa được', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '年', kana: 'とし', romaji: 'toshi', meaning: 'năm, tuổi', partOfSpeech: 'danh từ' },
      { kanji: '背広', kana: 'せびろ', romaji: 'sebiro', meaning: 'bộ vest công sở', partOfSpeech: 'danh từ' },
      { kanji: '買い物', kana: 'かいもの', romaji: 'kaimono', meaning: 'mua sắm', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 255,
    jlptLevel: 'N5',
    words: [
      { kana: 'おじいさん', romaji: 'ojiisan', meaning: 'ông, ông cụ (người đàn ông lớn tuổi)', partOfSpeech: 'danh từ' },
      { kanji: '八', kana: 'はち', romaji: 'hachi', meaning: 'số tám', partOfSpeech: 'danh từ' },
      { kanji: '八百屋', kana: 'やおや', romaji: 'yaoya', meaning: 'cửa hàng rau quả', partOfSpeech: 'danh từ' },
      { kanji: '文章', kana: 'ぶんしょう', romaji: 'bunshō', meaning: 'câu văn, đoạn văn', partOfSpeech: 'danh từ' },
      { kanji: '辺', kana: 'へん', romaji: 'hen', meaning: 'khu vực, vùng lân cận', partOfSpeech: 'danh từ' },
      { kanji: '便利', kana: 'べんり', romaji: 'benri', meaning: 'tiện lợi', partOfSpeech: 'tính từ na' },
      { kanji: '磨きます', kana: 'みがきます', romaji: 'migakimasu', meaning: 'đánh (răng), đánh bóng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '万年筆', kana: 'まんねんひつ', romaji: 'mannenhitsu', meaning: 'bút máy', partOfSpeech: 'danh từ' },
      { kanji: '門', kana: 'もん', romaji: 'mon', meaning: 'cổng', partOfSpeech: 'danh từ' },
      { kanji: '有名', kana: 'ゆうめい', romaji: 'yūmei', meaning: 'nổi tiếng', partOfSpeech: 'tính từ na' },
      { kanji: '夕飯', kana: 'ゆうはん', romaji: 'yūhan', meaning: 'cơm tối', partOfSpeech: 'danh từ' },
      { kanji: '零', kana: 'れい', romaji: 'rei', meaning: 'số không', partOfSpeech: 'danh từ' },
      { kanji: '六', kana: 'ろく', romaji: 'roku', meaning: 'số sáu', partOfSpeech: 'danh từ' },
    ],
  },
];
