// Bổ sung từ vựng N5 đợt 3 — tự soạn tay. lessonNumber 220–224.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST3_N5: JlptVocabUnit[] = [
  {
    lessonNumber: 220,
    jlptLevel: 'N5',
    words: [
      { kanji: '月', kana: 'つき', romaji: 'tsuki', meaning: 'mặt trăng, tháng', partOfSpeech: 'danh từ' },
      { kanji: '星', kana: 'ほし', romaji: 'hoshi', meaning: 'ngôi sao', partOfSpeech: 'danh từ' },
      { kanji: '海外', kana: 'かいがい', romaji: 'kaigai', meaning: 'nước ngoài', partOfSpeech: 'danh từ' },
      { kanji: '外国', kana: 'がいこく', romaji: 'gaikoku', meaning: 'ngoại quốc', partOfSpeech: 'danh từ' },
      { kanji: '外国人', kana: 'がいこくじん', romaji: 'gaikokujin', meaning: 'người nước ngoài', partOfSpeech: 'danh từ' },
      { kanji: '国', kana: 'くに', romaji: 'kuni', meaning: 'đất nước, quê hương', partOfSpeech: 'danh từ' },
      { kanji: '町', kana: 'まち', romaji: 'machi', meaning: 'thị trấn, phố', partOfSpeech: 'danh từ' },
      { kanji: '村', kana: 'むら', romaji: 'mura', meaning: 'làng', partOfSpeech: 'danh từ' },
      { kanji: '建物', kana: 'たてもの', romaji: 'tatemono', meaning: 'tòa nhà', partOfSpeech: 'danh từ' },
      { kanji: '店', kana: 'みせ', romaji: 'mise', meaning: 'cửa hàng', partOfSpeech: 'danh từ' },
      { kanji: '会社', kana: 'かいしゃ', romaji: 'kaisha', meaning: 'công ty', partOfSpeech: 'danh từ' },
      { kanji: '仕事', kana: 'しごと', romaji: 'shigoto', meaning: 'công việc', partOfSpeech: 'danh từ' },
      { kanji: '休み', kana: 'やすみ', romaji: 'yasumi', meaning: 'ngày nghỉ, sự nghỉ ngơi', partOfSpeech: 'danh từ' },
      { kanji: '旅行', kana: 'りょこう', romaji: 'ryokō', meaning: 'du lịch', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '写真', kana: 'しゃしん', romaji: 'shashin', meaning: 'ảnh chụp', partOfSpeech: 'danh từ' },
      { kanji: '地図', kana: 'ちず', romaji: 'chizu', meaning: 'bản đồ', partOfSpeech: 'danh từ' },
      { kanji: '新聞', kana: 'しんぶん', romaji: 'shinbun', meaning: 'báo giấy', partOfSpeech: 'danh từ' },
      { kanji: '雑誌', kana: 'ざっし', romaji: 'zasshi', meaning: 'tạp chí', partOfSpeech: 'danh từ' },
      { kanji: '手紙', kana: 'てがみ', romaji: 'tegami', meaning: 'lá thư', partOfSpeech: 'danh từ' },
      { kanji: '辞書', kana: 'じしょ', romaji: 'jisho', meaning: 'từ điển', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 221,
    jlptLevel: 'N5',
    words: [
      { kanji: '働きます', kana: 'はたらきます', romaji: 'hatarakimasu', meaning: 'làm việc', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '休みます', kana: 'やすみます', romaji: 'yasumimasu', meaning: 'nghỉ ngơi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '習います', kana: 'ならいます', romaji: 'naraimasu', meaning: 'học (từ ai đó)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '教えます', kana: 'おしえます', romaji: 'oshiemasu', meaning: 'dạy', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '貸します', kana: 'かします', romaji: 'kashimasu', meaning: 'cho mượn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '借ります', kana: 'かります', romaji: 'karimasu', meaning: 'mượn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '返します', kana: 'かえします', romaji: 'kaeshimasu', meaning: 'trả lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '送ります', kana: 'おくります', romaji: 'okurimasu', meaning: 'gửi (thư, đồ)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '届きます', kana: 'とどきます', romaji: 'todokimasu', meaning: 'đến nơi (đồ được gửi)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '呼びます', kana: 'よびます', romaji: 'yobimasu', meaning: 'gọi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '答えます', kana: 'こたえます', romaji: 'kotaemasu', meaning: 'trả lời', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '質問します', kana: 'しつもんします', romaji: 'shitsumon shimasu', meaning: 'hỏi, đặt câu hỏi', partOfSpeech: 'động từ する' },
      { kanji: '知っています', kana: 'しっています', romaji: 'shitte imasu', meaning: 'biết (thông tin)', partOfSpeech: 'cụm động từ' },
      { kanji: '忘れます', kana: 'わすれます', romaji: 'wasuremasu', meaning: 'quên', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '覚えます', kana: 'おぼえます', romaji: 'oboemasu', meaning: 'ghi nhớ, học thuộc', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '探します', kana: 'さがします', romaji: 'sagashimasu', meaning: 'tìm kiếm', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '見つけます', kana: 'みつけます', romaji: 'mitsukemasu', meaning: 'tìm thấy', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '無くします', kana: 'なくします', romaji: 'nakushimasu', meaning: 'làm mất', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '落とします', kana: 'おとします', romaji: 'otoshimasu', meaning: 'làm rơi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '拾います', kana: 'ひろいます', romaji: 'hiroimasu', meaning: 'nhặt', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 222,
    jlptLevel: 'N5',
    words: [
      { kanji: '春', kana: 'はる', romaji: 'haru', meaning: 'mùa xuân', partOfSpeech: 'danh từ' },
      { kanji: '夏', kana: 'なつ', romaji: 'natsu', meaning: 'mùa hè', partOfSpeech: 'danh từ' },
      { kanji: '秋', kana: 'あき', romaji: 'aki', meaning: 'mùa thu', partOfSpeech: 'danh từ' },
      { kanji: '冬', kana: 'ふゆ', romaji: 'fuyu', meaning: 'mùa đông', partOfSpeech: 'danh từ' },
      { kanji: '季節', kana: 'きせつ', romaji: 'kisetsu', meaning: 'mùa, thời tiết trong năm', partOfSpeech: 'danh từ' },
      { kanji: '天気', kana: 'てんき', romaji: 'tenki', meaning: 'thời tiết', partOfSpeech: 'danh từ' },
      { kanji: '晴れ', kana: 'はれ', romaji: 'hare', meaning: 'trời nắng, quang đãng', partOfSpeech: 'danh từ' },
      { kanji: '曇り', kana: 'くもり', romaji: 'kumori', meaning: 'trời nhiều mây', partOfSpeech: 'danh từ' },
      { kanji: '台風', kana: 'たいふう', romaji: 'taifū', meaning: 'bão', partOfSpeech: 'danh từ' },
      { kanji: '気温', kana: 'きおん', romaji: 'kion', meaning: 'nhiệt độ (không khí)', partOfSpeech: 'danh từ' },
      { kanji: '天', kana: 'てん', romaji: 'ten', meaning: 'trời, thiên', partOfSpeech: 'danh từ' },
      { kanji: '氷', kana: 'こおり', romaji: 'kōri', meaning: 'nước đá', partOfSpeech: 'danh từ' },
      { kanji: '虹', kana: 'にじ', romaji: 'niji', meaning: 'cầu vồng', partOfSpeech: 'danh từ' },
      { kanji: '光', kana: 'ひかり', romaji: 'hikari', meaning: 'ánh sáng', partOfSpeech: 'danh từ' },
      { kanji: '影', kana: 'かげ', romaji: 'kage', meaning: 'bóng, bóng tối', partOfSpeech: 'danh từ' },
      { kanji: '音', kana: 'おと', romaji: 'oto', meaning: 'âm thanh', partOfSpeech: 'danh từ' },
      { kanji: '声', kana: 'こえ', romaji: 'koe', meaning: 'giọng nói', partOfSpeech: 'danh từ' },
      { kanji: '匂い', kana: 'におい', romaji: 'nioi', meaning: 'mùi hương', partOfSpeech: 'danh từ' },
      { kanji: '色', kana: 'いろ', romaji: 'iro', meaning: 'màu sắc', partOfSpeech: 'danh từ' },
      { kanji: '形', kana: 'かたち', romaji: 'katachi', meaning: 'hình dạng', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 223,
    jlptLevel: 'N5',
    words: [
      { kanji: '着ます', kana: 'きます', romaji: 'kimasu', meaning: 'mặc (áo)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '脱ぎます', kana: 'ぬぎます', romaji: 'nugimasu', meaning: 'cởi (áo, giày)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: 'かぶります', kana: 'かぶります', romaji: 'kaburimasu', meaning: 'đội (mũ)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: 'はきます', kana: 'はきます', romaji: 'hakimasu', meaning: 'mang (giày, quần)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '帽子', kana: 'ぼうし', romaji: 'bōshi', meaning: 'mũ nón', partOfSpeech: 'danh từ' },
      { kanji: '眼鏡', kana: 'めがね', romaji: 'megane', meaning: 'kính đeo mắt', partOfSpeech: 'danh từ' },
      { kanji: '靴', kana: 'くつ', romaji: 'kutsu', meaning: 'giày', partOfSpeech: 'danh từ' },
      { kanji: '靴下', kana: 'くつした', romaji: 'kutsushita', meaning: 'tất chân', partOfSpeech: 'danh từ' },
      { kanji: '時計', kana: 'とけい', romaji: 'tokei', meaning: 'đồng hồ', partOfSpeech: 'danh từ' },
      { kanji: '鞄', kana: 'かばん', romaji: 'kaban', meaning: 'cặp, túi xách', partOfSpeech: 'danh từ' },
      { kanji: '財布', kana: 'さいふ', romaji: 'saifu', meaning: 'ví tiền', partOfSpeech: 'danh từ' },
      { kanji: '傘', kana: 'かさ', romaji: 'kasa', meaning: 'cái ô, dù', partOfSpeech: 'danh từ' },
      { kanji: '洋服', kana: 'ようふく', romaji: 'yōfuku', meaning: 'trang phục kiểu Tây', partOfSpeech: 'danh từ' },
      { kanji: 'ズボン', kana: 'ズボン', romaji: 'zubon', meaning: 'quần dài', partOfSpeech: 'danh từ' },
      { kanji: 'スカート', kana: 'スカート', romaji: 'sukāto', meaning: 'chân váy', partOfSpeech: 'danh từ' },
      { kanji: '指輪', kana: 'ゆびわ', romaji: 'yubiwa', meaning: 'chiếc nhẫn', partOfSpeech: 'danh từ' },
      { kanji: 'ネクタイ', kana: 'ネクタイ', romaji: 'nekutai', meaning: 'cà vạt', partOfSpeech: 'danh từ' },
      { kanji: 'ポケット', kana: 'ポケット', romaji: 'poketto', meaning: 'túi áo/quần', partOfSpeech: 'danh từ' },
      { kanji: '布団', kana: 'ふとん', romaji: 'futon', meaning: 'chăn đệm kiểu Nhật', partOfSpeech: 'danh từ' },
      { kanji: '枕', kana: 'まくら', romaji: 'makura', meaning: 'cái gối', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 224,
    jlptLevel: 'N5',
    words: [
      { kanji: '病気', kana: 'びょうき', romaji: 'byōki', meaning: 'bệnh, ốm', partOfSpeech: 'danh từ' },
      { kanji: '熱', kana: 'ねつ', romaji: 'netsu', meaning: 'cơn sốt', partOfSpeech: 'danh từ' },
      { kanji: '風邪', kana: 'かぜ', romaji: 'kaze', meaning: 'cảm cúm', partOfSpeech: 'danh từ' },
      { kanji: '薬', kana: 'くすり', romaji: 'kusuri', meaning: 'thuốc', partOfSpeech: 'danh từ' },
      { kanji: '医者', kana: 'いしゃ', romaji: 'isha', meaning: 'bác sĩ', partOfSpeech: 'danh từ' },
      { kanji: '看護師', kana: 'かんごし', romaji: 'kangoshi', meaning: 'y tá', partOfSpeech: 'danh từ' },
      { kanji: '痛い', kana: 'いたい', romaji: 'itai', meaning: 'đau', partOfSpeech: 'tính từ i' },
      { kanji: '怪我', kana: 'けが', romaji: 'kega', meaning: 'vết thương, sự bị thương', partOfSpeech: 'danh từ' },
      { kanji: '元気', kana: 'げんき', romaji: 'genki', meaning: 'khỏe mạnh, tràn đầy sức sống', partOfSpeech: 'tính từ na' },
      { kanji: '疲れます', kana: 'つかれます', romaji: 'tsukaremasu', meaning: 'mệt mỏi', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '休みます', kana: 'やすみます', romaji: 'yasumimasu', meaning: 'nghỉ (do bệnh)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '治ります', kana: 'なおります', romaji: 'naorimasu', meaning: 'khỏi bệnh', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '運動します', kana: 'うんどうします', romaji: 'undō shimasu', meaning: 'vận động, tập thể dục', partOfSpeech: 'động từ する' },
      { kanji: '体', kana: 'からだ', romaji: 'karada', meaning: 'cơ thể', partOfSpeech: 'danh từ' },
      { kanji: '力', kana: 'ちから', romaji: 'chikara', meaning: 'sức lực', partOfSpeech: 'danh từ' },
      { kanji: '声援', kana: 'せいえん', romaji: 'seien', meaning: 'sự cổ vũ', partOfSpeech: 'danh từ' },
      { kanji: '注射', kana: 'ちゅうしゃ', romaji: 'chūsha', meaning: 'tiêm thuốc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '入院します', kana: 'にゅういんします', romaji: 'nyūin shimasu', meaning: 'nhập viện', partOfSpeech: 'động từ する' },
      { kanji: '退院します', kana: 'たいいんします', romaji: 'taiin shimasu', meaning: 'xuất viện', partOfSpeech: 'động từ する' },
      { kanji: '救急車', kana: 'きゅうきゅうしゃ', romaji: 'kyūkyūsha', meaning: 'xe cứu thương', partOfSpeech: 'danh từ' },
    ],
  },
];
