// Bổ sung kanji N1 — dịch tay (Hán Việt + nghĩa Việt) dựa trên dữ liệu đọc âm
// (onyomi/kunyomi) và stroke count lấy từ kanjiapi.dev (nguồn mở), không auto-scrape nghĩa tiếng Việt.
// KanjiLesson lessonNumber 816-820.

import type { JlptKanjiLesson } from './jlpt-kanji.data';

export const JLPT_KANJI_BOOST4_N1_D: JlptKanjiLesson[] = [
  {
    lessonNumber: 816,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (1)',
    sortOrder: 8160,
    entries: [
      { character: '撲', hanViet: 'PHÁC', onyomi: 'ぼく', meaningVi: 'đánh, đập', strokeCount: 15 },
      { character: '操', hanViet: 'THAO', onyomi: 'そう, さん', kunyomi: 'みさお, あやつ-る', meaningVi: 'thao tác; tiết tháo', strokeCount: 16 },
      { character: '擬', hanViet: 'NGHĨ', onyomi: 'ぎ', kunyomi: 'まが-い, もど-き', meaningVi: 'mô phỏng, giả định', strokeCount: 17 },
      { character: '攻', hanViet: 'CÔNG', onyomi: 'こう', kunyomi: 'せ-める', meaningVi: 'tấn công', strokeCount: 7 },
      { character: '故', hanViet: 'CỐ', onyomi: 'こ', kunyomi: 'ゆえ, ふる-い, もと', meaningVi: 'cố ý; lý do; cũ', strokeCount: 9 },
      { character: '敏', hanViet: 'MẪN', onyomi: 'びん', kunyomi: 'さとい', meaningVi: 'nhanh nhạy, thông minh', strokeCount: 10 },
      { character: '敢', hanViet: 'CẢM', onyomi: 'かん', kunyomi: 'あ-えて, あ-えない, あ-えず', meaningVi: 'dám, can đảm', strokeCount: 12 },
      { character: '敦', hanViet: 'ĐÔN', onyomi: 'とん, たい, だん, ちょう', kunyomi: 'あつ-い', meaningVi: 'đôn hậu, chân thành', strokeCount: 12 },
      { character: '敵', hanViet: 'ĐỊCH', onyomi: 'てき', kunyomi: 'かたき, あだ, かな-う', meaningVi: 'kẻ địch', strokeCount: 15 },
      { character: '敷', hanViet: 'PHU', onyomi: 'ふ', kunyomi: 'し-く, -し-き', meaningVi: 'trải ra, bày ra', strokeCount: 15 },
      { character: '斉', hanViet: 'TỀ', onyomi: 'せい, さい', kunyomi: 'そろ-う, ひと-しい, ひと-しく, あたる, はやい', meaningVi: 'ngang bằng, đều nhau', strokeCount: 8 },
      { character: '斎', hanViet: 'TRAI', onyomi: 'さい', kunyomi: 'とき, つつし-む, ものいみ, い-む, いわ-う, いつ-く', meaningVi: 'trai giới, phòng thanh tịnh', strokeCount: 11 },
      { character: '斐', hanViet: 'PHI', onyomi: 'ひ, い', meaningVi: 'đẹp, có văn vẻ', strokeCount: 12 },
      { character: '斗', hanViet: 'ĐẨU', onyomi: 'と, とう', meaningVi: 'đấu (đơn vị đo); sao Đẩu', strokeCount: 4 },
      { character: '斜', hanViet: 'TÀ', onyomi: 'しゃ', kunyomi: 'なな-め, はす', meaningVi: 'nghiêng, xiên', strokeCount: 11 },
      { character: '斤', hanViet: 'CÂN', onyomi: 'きん', meaningVi: 'cân (đơn vị khối lượng)', strokeCount: 4 },
      { character: '斥', hanViet: 'XÍCH', onyomi: 'せき', kunyomi: 'しりぞ-ける', meaningVi: 'bài xích, đẩy lùi', strokeCount: 5 },
      { character: '於', hanViet: 'Ư', onyomi: 'お, よ', kunyomi: 'おい-て, お-ける, ああ, より', meaningVi: 'ở, tại (giới từ Hán cổ)', strokeCount: 8 },
      { character: '旗', hanViet: 'KỲ', onyomi: 'き', kunyomi: 'はた', meaningVi: 'lá cờ', strokeCount: 14 },
      { character: '旦', hanViet: 'ĐÁN', onyomi: 'たん, だん', kunyomi: 'あき-らか, あきら, ただし, あさ, あした', meaningVi: 'buổi sáng sớm, rạng đông', strokeCount: 5 },
    ],
  },
  {
    lessonNumber: 817,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (2)',
    sortOrder: 8170,
    entries: [
      { character: '旨', hanViet: 'CHỈ', onyomi: 'し', kunyomi: 'むね, うま-い', meaningVi: 'ý chỉ, mục đích; ngon', strokeCount: 6 },
      { character: '旬', hanViet: 'TUẦN', onyomi: 'じゅん, しゅん', meaningVi: 'tuần (10 ngày)', strokeCount: 6 },
      { character: '旭', hanViet: 'HÚC', onyomi: 'きょく', kunyomi: 'あさひ', meaningVi: 'ánh mặt trời buổi sáng', strokeCount: 6 },
      { character: '旺', hanViet: 'VƯỢNG', onyomi: 'おう', kunyomi: 'さかん', meaningVi: 'hưng thịnh', strokeCount: 8 },
      { character: '昂', hanViet: 'NGANG', onyomi: 'こう, ごう', kunyomi: 'あ-がる, たか-い, たか-ぶる', meaningVi: 'cao, hăng hái', strokeCount: 8 },
      { character: '昆', hanViet: 'CÔN', onyomi: 'こん', meaningVi: 'con cháu; côn trùng', strokeCount: 8 },
      { character: '昌', hanViet: 'XƯƠNG', onyomi: 'しょう', kunyomi: 'さかん', meaningVi: 'hưng thịnh, sáng sủa', strokeCount: 8 },
      { character: '昭', hanViet: 'CHIÊU', onyomi: 'しょう', meaningVi: 'sáng rõ', strokeCount: 9 },
      { character: '是', hanViet: 'THỊ', onyomi: 'ぜ, し', kunyomi: 'これ, この, ここ', meaningVi: 'đúng, phải; cái này', strokeCount: 9 },
      { character: '昴', hanViet: 'MÃO', onyomi: 'こう, ぼう', kunyomi: 'すばる', meaningVi: 'sao Mão (chòm Thất Tinh)', strokeCount: 9 },
      { character: '晃', hanViet: 'HOẢNG', onyomi: 'こう', kunyomi: 'あきらか', meaningVi: 'sáng sủa, rực rỡ', strokeCount: 10 },
      { character: '晋', hanViet: 'TẤN', onyomi: 'しん', kunyomi: 'すす-む', meaningVi: 'tiến lên; nước Tấn', strokeCount: 10 },
      { character: '晏', hanViet: 'YẾN', onyomi: 'あん', kunyomi: 'おそ-い', meaningVi: 'muộn, yên tĩnh', strokeCount: 10 },
      { character: '晟', hanViet: 'THÀNH', onyomi: 'せい, じょう', kunyomi: 'あきらか', meaningVi: 'sáng sủa, hưng thịnh', strokeCount: 10 },
      { character: '晨', hanViet: 'THẦN', onyomi: 'しん', kunyomi: 'あした, とき, あさ', meaningVi: 'buổi sáng sớm', strokeCount: 11 },
      { character: '晶', hanViet: 'TINH', onyomi: 'しょう', meaningVi: 'tinh thể, sáng lấp lánh', strokeCount: 12 },
      { character: '智', hanViet: 'TRÍ', onyomi: 'ち', meaningVi: 'trí tuệ', strokeCount: 12 },
      { character: '暁', hanViet: 'HIỂU', onyomi: 'ぎょう, きょう', kunyomi: 'あかつき, さと-る', meaningVi: 'rạng sáng; hiểu rõ', strokeCount: 12 },
      { character: '暇', hanViet: 'HẠ', onyomi: 'か', kunyomi: 'ひま, いとま', meaningVi: 'thời gian rảnh', strokeCount: 13 },
      { character: '暉', hanViet: 'HUY', onyomi: 'き', kunyomi: 'かが-やく', meaningVi: 'ánh sáng chói', strokeCount: 13 },
    ],
  },
  {
    lessonNumber: 818,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (3)',
    sortOrder: 8180,
    entries: [
      { character: '暢', hanViet: 'SƯỚNG', onyomi: 'ちょう', kunyomi: 'のび-る', meaningVi: 'thông suốt, trôi chảy', strokeCount: 14 },
      { character: '曙', hanViet: 'THỰ', onyomi: 'しょ', kunyomi: 'あけぼの', meaningVi: 'rạng đông', strokeCount: 17 },
      { character: '曹', hanViet: 'TÀO', onyomi: 'そう, ぞう', meaningVi: 'quan chức; bạn bè', strokeCount: 11 },
      { character: '朋', hanViet: 'BẰNG', onyomi: 'ほう', kunyomi: 'とも', meaningVi: 'bạn bè', strokeCount: 8 },
      { character: '朔', hanViet: 'SÓC', onyomi: 'さく', kunyomi: 'ついたち', meaningVi: 'ngày mùng một âm lịch; phương bắc', strokeCount: 10 },
      { character: '朗', hanViet: 'LÃNG', onyomi: 'ろう', kunyomi: 'ほが-らか, あき-らか', meaningVi: 'sáng sủa, vui vẻ', strokeCount: 10 },
      { character: '朱', hanViet: 'CHU', onyomi: 'しゅ', kunyomi: 'あけ', meaningVi: 'màu đỏ son', strokeCount: 6 },
      { character: '朴', hanViet: 'PHÁC', onyomi: 'ぼく', kunyomi: 'ほう, ほお, えのき', meaningVi: 'chất phác, mộc mạc', strokeCount: 6 },
      { character: '朽', hanViet: 'HỦ', onyomi: 'きゅう', kunyomi: 'く-ちる', meaningVi: 'mục nát', strokeCount: 6 },
      { character: '杉', hanViet: 'SAM', onyomi: 'さん', kunyomi: 'すぎ', meaningVi: 'cây tuyết tùng', strokeCount: 7 },
      { character: '李', hanViet: 'LÝ', onyomi: 'り', kunyomi: 'すもも', meaningVi: 'cây mận', strokeCount: 7 },
      { character: '杏', hanViet: 'HẠNH', onyomi: 'きょう, あん, こう', kunyomi: 'あんず', meaningVi: 'cây mơ, quả hạnh', strokeCount: 7 },
      { character: '杜', hanViet: 'ĐỖ', onyomi: 'と, とう, ず', kunyomi: 'もり, ふさ-ぐ, やまなし', meaningVi: 'rừng cây; ngăn chặn', strokeCount: 7 },
      { character: '枢', hanViet: 'KHU', onyomi: 'すう, しゅ', kunyomi: 'とぼそ, からくり', meaningVi: 'trục, bản lề; trung tâm', strokeCount: 8 },
      { character: '架', hanViet: 'GIÁ', onyomi: 'か', kunyomi: 'か-ける, か-かる', meaningVi: 'giá đỡ, kệ', strokeCount: 9 },
      { character: '柄', hanViet: 'BÍNH', onyomi: 'へい', kunyomi: 'がら, え, つか', meaningVi: 'cán, chuôi; tính cách', strokeCount: 9 },
      { character: '某', hanViet: 'MỖ', onyomi: 'ぼう', kunyomi: 'それがし, なにがし', meaningVi: 'ai đó, kẻ nào đó', strokeCount: 9 },
      { character: '柚', hanViet: 'DỮU', onyomi: 'ゆ, ゆう, じく', kunyomi: 'ゆず', meaningVi: 'quả chanh yuzu', strokeCount: 9 },
      { character: '柳', hanViet: 'LIỄU', onyomi: 'りゅう', kunyomi: 'やなぎ', meaningVi: 'cây liễu', strokeCount: 9 },
      { character: '栓', hanViet: 'THUYÊN', onyomi: 'せん', meaningVi: 'nút chai, chốt', strokeCount: 10 },
    ],
  },
  {
    lessonNumber: 819,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (4)',
    sortOrder: 8190,
    entries: [
      { character: '栗', hanViet: 'LẬT', onyomi: 'りつ, り', kunyomi: 'くり, おののく', meaningVi: 'hạt dẻ', strokeCount: 10 },
      { character: '核', hanViet: 'HẠCH', onyomi: 'かく', meaningVi: 'hạt nhân, hạch', strokeCount: 10 },
      { character: '桂', hanViet: 'QUẾ', onyomi: 'けい', kunyomi: 'かつら', meaningVi: 'cây quế', strokeCount: 10 },
      { character: '桃', hanViet: 'ĐÀO', onyomi: 'とう', kunyomi: 'もも', meaningVi: 'cây đào', strokeCount: 10 },
      { character: '桐', hanViet: 'ĐỒNG', onyomi: 'とう, どう', kunyomi: 'きり', meaningVi: 'cây ngô đồng', strokeCount: 10 },
      { character: '桑', hanViet: 'TANG', onyomi: 'そう', kunyomi: 'くわ', meaningVi: 'cây dâu tằm', strokeCount: 10 },
      { character: '桟', hanViet: 'SẠN', onyomi: 'さん, せん', kunyomi: 'かけはし', meaningVi: 'giàn, cầu tạm', strokeCount: 10 },
      { character: '梓', hanViet: 'TỬ', onyomi: 'し', kunyomi: 'あずさ', meaningVi: 'cây tử (gỗ khắc bản in)', strokeCount: 11 },
      { character: '梢', hanViet: 'SAO', onyomi: 'しょう', kunyomi: 'こずえ, くすのき', meaningVi: 'ngọn cây', strokeCount: 11 },
      { character: '梧', hanViet: 'NGÔ', onyomi: 'ご', kunyomi: 'あおぎり', meaningVi: 'cây ngô đồng', strokeCount: 11 },
      { character: '梨', hanViet: 'LÊ', onyomi: 'り', kunyomi: 'なし', meaningVi: 'quả lê', strokeCount: 11 },
      { character: '棋', hanViet: 'KỲ', onyomi: 'き', kunyomi: 'ご', meaningVi: 'cờ (cờ vây, shogi)', strokeCount: 12 },
      { character: '棚', hanViet: 'BẰNG', onyomi: 'ほう', kunyomi: 'たな, -だな', meaningVi: 'cái kệ, giàn', strokeCount: 12 },
      { character: '棟', hanViet: 'ĐỐNG', onyomi: 'とう', kunyomi: 'むね, むな-', meaningVi: 'xà nhà; tòa nhà (đơn vị đếm)', strokeCount: 12 },
      { character: '椎', hanViet: 'CHÙY', onyomi: 'つい, すい', kunyomi: 'つち, う-つ', meaningVi: 'cột sống; cây dẻ gai', strokeCount: 12 },
      { character: '検', hanViet: 'KIỂM', onyomi: 'けん', kunyomi: 'しら-べる', meaningVi: 'kiểm tra', strokeCount: 12 },
      { character: '椰', hanViet: 'DA', onyomi: 'や', kunyomi: 'やし', meaningVi: 'cây dừa', strokeCount: 13 },
      { character: '椿', hanViet: 'XUÂN', onyomi: 'ちん, ちゅん', kunyomi: 'つばき', meaningVi: 'cây trà mi (tsubaki)', strokeCount: 13 },
      { character: '楊', hanViet: 'DƯƠNG', onyomi: 'よう', kunyomi: 'やなぎ', meaningVi: 'cây dương liễu', strokeCount: 13 },
      { character: '楓', hanViet: 'PHONG', onyomi: 'ふう', kunyomi: 'かえで', meaningVi: 'cây phong (lá đỏ)', strokeCount: 13 },
    ],
  },
  {
    lessonNumber: 820,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (5)',
    sortOrder: 8200,
    entries: [
      { character: '楠', hanViet: 'NAM', onyomi: 'なん, だん, ぜん, ねん', kunyomi: 'くす, くすのき', meaningVi: 'cây long não', strokeCount: 13 },
      { character: '楼', hanViet: 'LÂU', onyomi: 'ろう', kunyomi: 'たかどの', meaningVi: 'lầu cao, tháp canh', strokeCount: 13 },
      { character: '槽', hanViet: 'TÀO', onyomi: 'そう', kunyomi: 'ふね', meaningVi: 'máng, bồn', strokeCount: 15 },
      { character: '標', hanViet: 'TIÊU', onyomi: 'ひょう', kunyomi: 'しるべ, しるし', meaningVi: 'dấu hiệu, tiêu chuẩn', strokeCount: 15 },
      { character: '模', hanViet: 'MÔ', onyomi: 'も, ぼ', meaningVi: 'khuôn mẫu, mô phỏng', strokeCount: 14 },
      { character: '樹', hanViet: 'THỤ', onyomi: 'じゅ', kunyomi: 'き', meaningVi: 'cây; thiết lập', strokeCount: 16 },
      { character: '橘', hanViet: 'QUẤT', onyomi: 'きつ', kunyomi: 'たちばな', meaningVi: 'cây quất', strokeCount: 16 },
      { character: '檀', hanViet: 'ĐÀN', onyomi: 'だん, たん', kunyomi: 'まゆみ', meaningVi: 'cây đàn hương', strokeCount: 17 },
      { character: '欄', hanViet: 'LAN', onyomi: 'らん', kunyomi: 'てすり', meaningVi: 'cột, hàng rào chắn (lan can)', strokeCount: 20 },
      { character: '欽', hanViet: 'KHÂM', onyomi: 'きん, こん', kunyomi: 'つつし-む', meaningVi: 'kính trọng', strokeCount: 12 },
      { character: '歓', hanViet: 'HOAN', onyomi: 'かん', kunyomi: 'よろこ-ぶ', meaningVi: 'vui mừng', strokeCount: 15 },
    ],
  },
];
