// Bổ sung từ vựng N3 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 350-354.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N3_PART8: JlptVocabUnit[] = [
  {
    lessonNumber: 350,
    jlptLevel: 'N3',
    words: [
      { kanji: '無事', kana: 'ぶじ', romaji: 'buji', meaning: 'an toàn, bình yên', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '霧', kana: 'きり', romaji: 'kiri', meaning: 'sương mù', partOfSpeech: 'danh từ' },
      { kanji: '名', kana: 'な', romaji: 'na', meaning: 'tên, danh tiếng', partOfSpeech: 'danh từ' },
      { kanji: '名人', kana: 'めいじん', romaji: 'meijin', meaning: 'bậc thầy, chuyên gia', partOfSpeech: 'danh từ' },
      { kanji: '命', kana: 'いのち', romaji: 'inochi', meaning: 'mạng sống, sinh mệnh', partOfSpeech: 'danh từ' },
      { kanji: '命じます', kana: 'めいじます', romaji: 'meijimasu', meaning: 'ra lệnh, bổ nhiệm', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '明かり', kana: 'あかり', romaji: 'akari', meaning: 'ánh sáng, ánh đèn', partOfSpeech: 'danh từ' },
      { kanji: '明らか', kana: 'あきらか', romaji: 'akiraka', meaning: 'rõ ràng, hiển nhiên', partOfSpeech: 'tính từ na' },
      { kanji: '明後日', kana: 'みょうごにち', romaji: 'myōgonichi', meaning: 'ngày kia (cách nói trang trọng)', partOfSpeech: 'danh từ' },
      { kanji: '迷子', kana: 'まいご', romaji: 'maigo', meaning: 'trẻ lạc, người đi lạc', partOfSpeech: 'danh từ' },
      { kanji: '模様', kana: 'もよう', romaji: 'moyō', meaning: 'hoa văn, họa tiết', partOfSpeech: 'danh từ' },
      { kanji: '毛布', kana: 'もうふ', romaji: 'mōfu', meaning: 'chăn, mền', partOfSpeech: 'danh từ' },
      { kanji: '黙ります', kana: 'だまります', romaji: 'damarimasu', meaning: 'im lặng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '問い', kana: 'とい', romaji: 'toi', meaning: 'câu hỏi', partOfSpeech: 'danh từ' },
      { kanji: '夜', kana: 'よ', romaji: 'yo', meaning: 'đêm, buổi tối', partOfSpeech: 'danh từ' },
      { kanji: '夜中', kana: 'よなか', romaji: 'yonaka', meaning: 'nửa đêm', partOfSpeech: 'danh từ' },
      { kanji: '夜明け', kana: 'よあけ', romaji: 'yoake', meaning: 'bình minh, rạng sáng', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 351,
    jlptLevel: 'N3',
    words: [
      { kanji: '野', kana: 'の', romaji: 'no', meaning: 'cánh đồng, đồng cỏ', partOfSpeech: 'danh từ' },
      { kanji: '厄介', kana: 'やっかい', romaji: 'yakkai', meaning: 'phiền phức, rắc rối', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '愉快', kana: 'ゆかい', romaji: 'yukai', meaning: 'vui vẻ, thú vị', partOfSpeech: 'tính từ na' },
      { kanji: '油', kana: 'あぶら', romaji: 'abura', meaning: 'dầu ăn, dầu mỡ', partOfSpeech: 'danh từ' },
      { kanji: '唯一', kana: 'ゆいいつ', romaji: 'yuiitsu', meaning: 'duy nhất', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '優れます', kana: 'すぐれます', romaji: 'suguremasu', meaning: 'xuất sắc, vượt trội', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '優秀', kana: 'ゆうしゅう', romaji: 'yūshū', meaning: 'ưu tú, xuất sắc', partOfSpeech: 'tính từ na' },
      { kanji: '優勝', kana: 'ゆうしょう', romaji: 'yūshō', meaning: 'sự vô địch, chiến thắng chung cuộc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '勇気', kana: 'ゆうき', romaji: 'yūki', meaning: 'lòng dũng cảm', partOfSpeech: 'danh từ' },
      { kanji: '友', kana: 'とも', romaji: 'tomo', meaning: 'bạn bè', partOfSpeech: 'danh từ' },
      { kanji: '友情', kana: 'ゆうじょう', romaji: 'yūjō', meaning: 'tình bạn', partOfSpeech: 'danh từ' },
      { kanji: '友人', kana: 'ゆうじん', romaji: 'yūjin', meaning: 'bạn bè (trang trọng)', partOfSpeech: 'danh từ' },
      { kanji: '有効', kana: 'ゆうこう', romaji: 'yūkō', meaning: 'có hiệu lực, hiệu quả', partOfSpeech: 'tính từ na' },
      { kanji: '有能', kana: 'ゆうのう', romaji: 'yūnō', meaning: 'có năng lực, tài giỏi', partOfSpeech: 'tính từ na' },
      { kanji: '有利', kana: 'ゆうり', romaji: 'yūri', meaning: 'có lợi', partOfSpeech: 'tính từ na' },
      { kanji: '郵便', kana: 'ゆうびん', romaji: 'yūbin', meaning: 'bưu điện, bưu chính', partOfSpeech: 'danh từ' },
      { kanji: '予期', kana: 'よき', romaji: 'yoki', meaning: 'sự dự đoán trước', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 352,
    jlptLevel: 'N3',
    words: [
      { kanji: '予測', kana: 'よそく', romaji: 'yosoku', meaning: 'sự dự đoán, ước tính', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '予報', kana: 'よほう', romaji: 'yohō', meaning: 'dự báo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '余裕', kana: 'よゆう', romaji: 'yoyū', meaning: 'sự dư dả, dư giả (thời gian, tiền bạc)', partOfSpeech: 'danh từ' },
      { kanji: '与えます', kana: 'あたえます', romaji: 'ataemasu', meaning: 'cho, trao tặng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '預けます', kana: 'あずけます', romaji: 'azukemasu', meaning: 'gửi, giao phó (đồ vật, tiền)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '幼い', kana: 'おさない', romaji: 'osanai', meaning: 'còn nhỏ, ấu trĩ', partOfSpeech: 'tính từ i' },
      { kanji: '曜日', kana: 'ようび', romaji: 'yōbi', meaning: 'thứ (trong tuần)', partOfSpeech: 'danh từ' },
      { kanji: '様々', kana: 'さまざま', romaji: 'samazama', meaning: 'đa dạng, nhiều loại', partOfSpeech: 'tính từ na' },
      { kanji: '用います', kana: 'もちいます', romaji: 'mochiimasu', meaning: 'sử dụng, dùng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '用心', kana: 'ようじん', romaji: 'yōjin', meaning: 'sự đề phòng, cẩn thận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '要するに', kana: 'ようするに', romaji: 'yōsuruni', meaning: 'tóm lại, nói ngắn gọn thì', partOfSpeech: 'phó từ' },
      { kanji: '要求', kana: 'ようきゅう', romaji: 'yōkyū', meaning: 'sự yêu cầu, đòi hỏi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '陽気', kana: 'ようき', romaji: 'yōki', meaning: 'vui vẻ, hoạt bát; thời tiết', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '翼', kana: 'つばさ', romaji: 'tsubasa', meaning: 'đôi cánh', partOfSpeech: 'danh từ' },
      { kanji: '裸', kana: 'はだか', romaji: 'hadaka', meaning: 'trần truồng, khỏa thân', partOfSpeech: 'danh từ' },
      { kanji: '来', kana: 'らい', romaji: 'rai', meaning: 'tới, sắp tới (tiền tố chỉ thời gian)', partOfSpeech: 'danh từ' },
      { kanji: '頼ります', kana: 'たよります', romaji: 'tayorimasu', meaning: 'dựa dẫm, nương tựa', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 353,
    jlptLevel: 'N3',
    words: [
      { kanji: '嵐', kana: 'あらし', romaji: 'arashi', meaning: 'cơn bão', partOfSpeech: 'danh từ' },
      { kanji: '利口', kana: 'りこう', romaji: 'rikō', meaning: 'khôn ngoan, thông minh', partOfSpeech: 'tính từ na' },
      { kanji: '離れます', kana: 'はなれます', romaji: 'hanaremasu', meaning: 'tách khỏi, rời xa', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '離婚', kana: 'りこん', romaji: 'rikon', meaning: 'sự ly hôn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '立ち上がります', kana: 'たちあがります', romaji: 'tachiagarimasu', meaning: 'đứng dậy', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '流します', kana: 'ながします', romaji: 'nagashimasu', meaning: 'làm chảy, để trôi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '流れ', kana: 'ながれ', romaji: 'nagare', meaning: 'dòng chảy, luồng', partOfSpeech: 'danh từ' },
      { kanji: '流れます', kana: 'ながれます', romaji: 'nagaremasu', meaning: 'chảy, trôi', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '留学', kana: 'りゅうがく', romaji: 'ryūgaku', meaning: 'du học', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '料金', kana: 'りょうきん', romaji: 'ryōkin', meaning: 'phí, cước phí', partOfSpeech: 'danh từ' },
      { kanji: '輪', kana: 'わ', romaji: 'wa', meaning: 'vòng tròn, cái vòng', partOfSpeech: 'danh từ' },
      { kanji: '列', kana: 'れつ', romaji: 'retsu', meaning: 'hàng, dãy', partOfSpeech: 'danh từ' },
      { kanji: '列車', kana: 'れっしゃ', romaji: 'ressha', meaning: 'đoàn tàu', partOfSpeech: 'danh từ' },
      { kanji: '劣ります', kana: 'おとります', romaji: 'otorimasu', meaning: 'kém hơn, thua kém', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '連れ', kana: 'つれ', romaji: 'tsure', meaning: 'người đi cùng, bạn đồng hành', partOfSpeech: 'danh từ' },
      { kanji: '連想', kana: 'れんそう', romaji: 'rensō', meaning: 'sự liên tưởng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '労働', kana: 'ろうどう', romaji: 'rōdō', meaning: 'lao động', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 354,
    jlptLevel: 'N3',
    words: [
      { kanji: '老い', kana: 'おい', romaji: 'oi', meaning: 'tuổi già, người già', partOfSpeech: 'danh từ' },
      { kanji: '老人', kana: 'ろうじん', romaji: 'rōjin', meaning: 'người già', partOfSpeech: 'danh từ' },
      { kanji: '論じます', kana: 'ろんじます', romaji: 'ronjimasu', meaning: 'bàn luận, tranh luận', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '話し合います', kana: 'はなしあいます', romaji: 'hanashiaimasu', meaning: 'bàn bạc, thảo luận với nhau', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '脇', kana: 'わき', romaji: 'waki', meaning: 'bên cạnh, nách', partOfSpeech: 'danh từ' },
      { kanji: '湾', kana: 'わん', romaji: 'wan', meaning: 'vịnh', partOfSpeech: 'danh từ' },
      { kanji: '籠', kana: 'かご', romaji: 'kago', meaning: 'cái giỏ, lồng', partOfSpeech: 'danh từ' },
      { kanji: '贅沢', kana: 'ぜいたく', romaji: 'zeitaku', meaning: 'sự xa hoa, xa xỉ', partOfSpeech: 'danh từ, tính từ na' },
    ],
  },
];
