// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 1031-1038.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART23: JlptVocabUnit[] = [
  {
    lessonNumber: 1031,
    jlptLevel: 'N1',
    words: [
      { kanji: '溶液', kana: 'ようえき', romaji: 'yōeki', meaning: 'dung dịch', partOfSpeech: 'danh từ' },
      { kanji: '用件', kana: 'ようけん', romaji: 'yōken', meaning: 'công việc cần làm', partOfSpeech: 'danh từ' },
      { kanji: '用品', kana: 'ようひん', romaji: 'yōhin', meaning: 'vật dụng, đồ dùng', partOfSpeech: 'danh từ' },
      { kanji: '用法', kana: 'ようほう', romaji: 'yōhō', meaning: 'cách sử dụng', partOfSpeech: 'danh từ' },
      { kanji: '要します', kana: 'ようします', romaji: 'yōshimasu', meaning: 'cần đến, đòi hỏi', partOfSpeech: 'động từ する' },
      { kanji: '要請', kana: 'ようせい', romaji: 'yōsei', meaning: 'lời yêu cầu chính thức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '要望', kana: 'ようぼう', romaji: 'yōbō', meaning: 'nguyện vọng, yêu cầu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '遥か', kana: 'はるか', romaji: 'haruka', meaning: 'xa xôi, xa xăm', partOfSpeech: 'tính từ na, phó từ' },
      { kanji: '養います', kana: 'やしないます', romaji: 'yashinaimasu', meaning: 'nuôi dưỡng, bồi dưỡng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '養護', kana: 'ようご', romaji: 'yōgo', meaning: 'sự chăm sóc bảo vệ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '抑圧', kana: 'よくあつ', romaji: 'yokuatsu', meaning: 'sự áp bức, đè nén', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '欲深い', kana: 'よくふかい', romaji: 'yokufukai', meaning: 'tham lam', partOfSpeech: 'tính từ i' },
      { kanji: '欲望', kana: 'よくぼう', romaji: 'yokubō', meaning: 'lòng ham muốn', partOfSpeech: 'danh từ' },
      { kanji: '浴室', kana: 'よくしつ', romaji: 'yokushitsu', meaning: 'phòng tắm', partOfSpeech: 'danh từ' },
      { kanji: '裸足', kana: 'はだし', romaji: 'hadashi', meaning: 'chân trần', partOfSpeech: 'danh từ' },
      { kanji: '来る', kana: 'きたる', romaji: 'kitaru', meaning: 'sắp tới (ngày, sự kiện)', partOfSpeech: 'từ hạn định' },
      { kanji: '来場', kana: 'らいじょう', romaji: 'raijō', meaning: 'sự đến tham dự', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 1032,
    jlptLevel: 'N1',
    words: [
      { kanji: '頼み', kana: 'たのみ', romaji: 'tanomi', meaning: 'lời nhờ vả', partOfSpeech: 'danh từ' },
      { kanji: '雷', kana: 'いかずち', romaji: 'ikazuchi', meaning: 'sấm sét (cách nói cổ)', partOfSpeech: 'danh từ' },
      { kanji: '絡みます', kana: 'からみます', romaji: 'karamimasu', meaning: 'quấn vào, dính líu tới', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '落ち込みます', kana: 'おちこみます', romaji: 'ochikomimasu', meaning: 'rơi vào, buồn chán', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '落ち着き', kana: 'おちつき', romaji: 'ochitsuki', meaning: 'sự bình tĩnh', partOfSpeech: 'danh từ' },
      { kanji: '落ち葉', kana: 'おちば', romaji: 'ochiba', meaning: 'lá rụng', partOfSpeech: 'danh từ' },
      { kanji: '落下', kana: 'らっか', romaji: 'rakka', meaning: 'sự rơi xuống', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '酪農', kana: 'らくのう', romaji: 'rakunō', meaning: 'ngành chăn nuôi bò sữa', partOfSpeech: 'danh từ' },
      { kanji: '乱します', kana: 'みだします', romaji: 'midashimasu', meaning: 'làm rối loạn, xáo trộn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '乱れます', kana: 'みだれます', romaji: 'midaremasu', meaning: 'bị rối loạn, mất trật tự', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '濫用', kana: 'らんよう', romaji: 'ranyō', meaning: 'sự lạm dụng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '利子', kana: 'りし', romaji: 'rishi', meaning: 'tiền lãi', partOfSpeech: 'danh từ' },
      { kanji: '利潤', kana: 'りじゅん', romaji: 'rijun', meaning: 'lợi nhuận', partOfSpeech: 'danh từ' },
      { kanji: '利息', kana: 'りそく', romaji: 'risoku', meaning: 'tiền lãi (ngân hàng)', partOfSpeech: 'danh từ' },
      { kanji: '利点', kana: 'りてん', romaji: 'riten', meaning: 'điểm lợi thế', partOfSpeech: 'danh từ' },
      { kanji: '履歴', kana: 'りれき', romaji: 'rireki', meaning: 'lý lịch, lịch sử làm việc', partOfSpeech: 'danh từ' },
      { kanji: '理屈', kana: 'りくつ', romaji: 'rikutsu', meaning: 'lý lẽ, lập luận', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 1033,
    jlptLevel: 'N1',
    words: [
      { kanji: '裏返し', kana: 'うらがえし', romaji: 'uragaeshi', meaning: 'lộn trái, lộn ngược', partOfSpeech: 'danh từ' },
      { kanji: '率います', kana: 'ひきいます', romaji: 'hikiimasu', meaning: 'chỉ huy, dẫn dắt', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '立ち寄ります', kana: 'たちよります', romaji: 'tachiyorimasu', meaning: 'ghé qua', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '立体', kana: 'りったい', romaji: 'rittai', meaning: 'hình khối, vật thể ba chiều', partOfSpeech: 'danh từ' },
      { kanji: '立法', kana: 'りっぽう', romaji: 'rippō', meaning: 'lập pháp', partOfSpeech: 'danh từ' },
      { kanji: '略語', kana: 'りゃくご', romaji: 'ryakugo', meaning: 'từ viết tắt', partOfSpeech: 'danh từ' },
      { kanji: '略奪', kana: 'りゃくだつ', romaji: 'ryakudatsu', meaning: 'sự cướp bóc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '流', kana: 'りゅう', romaji: 'ryū', meaning: 'kiểu, trường phái', partOfSpeech: 'hậu tố' },
      { kanji: '流し', kana: 'ながし', romaji: 'nagashi', meaning: 'bồn rửa', partOfSpeech: 'danh từ' },
      { kanji: '流行', kana: 'はやり', romaji: 'hayari', meaning: 'sự thịnh hành, mốt', partOfSpeech: 'danh từ' },
      { kanji: '流通', kana: 'りゅうつう', romaji: 'ryūtsū', meaning: 'sự lưu thông (hàng hóa, tiền tệ)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '溜まり', kana: 'たまり', romaji: 'tamari', meaning: 'chỗ ứ đọng, nơi tụ tập', partOfSpeech: 'danh từ' },
      { kanji: '旅客', kana: 'りょかく', romaji: 'ryokaku', meaning: 'hành khách', partOfSpeech: 'danh từ' },
      { kanji: '旅券', kana: 'りょけん', romaji: 'ryoken', meaning: 'hộ chiếu', partOfSpeech: 'danh từ' },
      { kanji: '了承', kana: 'りょうしょう', romaji: 'ryōshō', meaning: 'sự chấp thuận, thông cảm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '両極', kana: 'りょうきょく', romaji: 'ryōkyoku', meaning: 'hai cực (địa lý, điện)', partOfSpeech: 'danh từ' },
      { kanji: '凌ぎます', kana: 'しのぎます', romaji: 'shinogimasu', meaning: 'vượt qua, chống chọi', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 1034,
    jlptLevel: 'N1',
    words: [
      { kanji: '良好', kana: 'りょうこう', romaji: 'ryōkō', meaning: 'tốt, thuận lợi', partOfSpeech: 'tính từ na' },
      { kanji: '良識', kana: 'りょうしき', romaji: 'ryōshiki', meaning: 'lương tri, ý thức tốt', partOfSpeech: 'danh từ' },
      { kanji: '良質', kana: 'りょうしつ', romaji: 'ryōshitsu', meaning: 'chất lượng tốt', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '領地', kana: 'りょうち', romaji: 'ryōchi', meaning: 'lãnh địa', partOfSpeech: 'danh từ' },
      { kanji: '領土', kana: 'りょうど', romaji: 'ryōdo', meaning: 'lãnh thổ', partOfSpeech: 'danh từ' },
      { kanji: '林業', kana: 'りんぎょう', romaji: 'ringyō', meaning: 'ngành lâm nghiệp', partOfSpeech: 'danh từ' },
      { kanji: '類', kana: 'たぐい', romaji: 'tagui', meaning: 'loại, kiểu tương tự', partOfSpeech: 'danh từ' },
      { kanji: '類似', kana: 'るいじ', romaji: 'ruiji', meaning: 'sự tương tự', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '類推', kana: 'るいすい', romaji: 'ruisui', meaning: 'phép loại suy', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '冷やかします', kana: 'ひやかします', romaji: 'hiyakashimasu', meaning: 'trêu chọc, giễu cợt', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '冷酷', kana: 'れいこく', romaji: 'reikoku', meaning: 'tàn nhẫn, lạnh lùng', partOfSpeech: 'tính từ na' },
      { kanji: '冷蔵', kana: 'れいぞう', romaji: 'reizō', meaning: 'sự bảo quản lạnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '冷淡', kana: 'れいたん', romaji: 'reitan', meaning: 'lãnh đạm, thờ ơ', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '励みます', kana: 'はげみます', romaji: 'hagemimasu', meaning: 'nỗ lực, cố gắng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '暦', kana: 'こよみ', romaji: 'koyomi', meaning: 'lịch', partOfSpeech: 'danh từ' },
      { kanji: '恋します', kana: 'こいします', romaji: 'koishimasu', meaning: 'yêu, phải lòng', partOfSpeech: 'động từ する' },
      { kanji: '蓮', kana: 'はす', romaji: 'hasu', meaning: 'hoa sen', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 1035,
    jlptLevel: 'N1',
    words: [
      { kanji: '連なります', kana: 'つらなります', romaji: 'tsuranarimasu', meaning: 'nối tiếp thành hàng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '連ねます', kana: 'つらねます', romaji: 'tsuranemasu', meaning: 'nối liền, xếp thành dãy', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '連中', kana: 'れんじゅう', romaji: 'renjū', meaning: 'đồng bọn, nhóm người', partOfSpeech: 'danh từ' },
      { kanji: '連日', kana: 'れんじつ', romaji: 'renjitsu', meaning: 'liên tục nhiều ngày', partOfSpeech: 'danh từ' },
      { kanji: '連邦', kana: 'れんぽう', romaji: 'renpō', meaning: 'liên bang', partOfSpeech: 'danh từ' },
      { kanji: '連盟', kana: 'れんめい', romaji: 'renmei', meaning: 'liên minh, liên đoàn', partOfSpeech: 'danh từ' },
      { kanji: '露骨', kana: 'ろこつ', romaji: 'rokotsu', meaning: 'lộ liễu, thẳng thừng', partOfSpeech: 'tính từ na' },
      { kanji: '労ります', kana: 'いたわります', romaji: 'itawarimasu', meaning: 'an ủi, quan tâm chăm sóc', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '労力', kana: 'ろうりょく', romaji: 'rōryoku', meaning: 'công sức lao động', partOfSpeech: 'danh từ' },
      { kanji: '弄ります', kana: 'いじります', romaji: 'ijirimasu', meaning: 'nghịch, mó máy vào', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '朗読', kana: 'ろうどく', romaji: 'rōdoku', meaning: 'sự đọc diễn cảm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '漏らします', kana: 'もらします', romaji: 'morashimasu', meaning: 'để lộ, làm rò rỉ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '漏れます', kana: 'もれます', romaji: 'moremasu', meaning: 'bị rò rỉ, lọt ra', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '篭ります', kana: 'こもります', romaji: 'komorimasu', meaning: 'ru rú trong nhà, ẩn mình', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '老います', kana: 'おいます', romaji: 'oimasu', meaning: 'già đi', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '老衰', kana: 'ろうすい', romaji: 'rōsui', meaning: 'sự già yếu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '論議', kana: 'ろんぎ', romaji: 'rongi', meaning: 'sự bàn luận', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 1036,
    jlptLevel: 'N1',
    words: [
      { kanji: '和やか', kana: 'なごやか', romaji: 'nagoyaka', meaning: 'hòa nhã, êm dịu', partOfSpeech: 'tính từ na' },
      { kanji: '和らげます', kana: 'やわらげます', romaji: 'yawaragemasu', meaning: 'làm dịu, giảm nhẹ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '和風', kana: 'わふう', romaji: 'wafū', meaning: 'kiểu Nhật', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '和文', kana: 'わぶん', romaji: 'wabun', meaning: 'văn bản tiếng Nhật', partOfSpeech: 'danh từ' },
      { kanji: '話し合い', kana: 'はなしあい', romaji: 'hanashiai', meaning: 'cuộc thảo luận', partOfSpeech: 'danh từ' },
      { kanji: '歪みます', kana: 'ゆがみます', romaji: 'yugamimasu', meaning: 'bị méo mó, cong vênh', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '賄います', kana: 'まかないます', romaji: 'makanaimasu', meaning: 'chu cấp, trang trải (chi phí)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '惑星', kana: 'わくせい', romaji: 'wakusei', meaning: 'hành tinh', partOfSpeech: 'danh từ' },
      { kanji: '詫び', kana: 'わび', romaji: 'wabi', meaning: 'lời xin lỗi', partOfSpeech: 'danh từ' },
      { kanji: '藁', kana: 'わら', romaji: 'wara', meaning: 'rơm rạ', partOfSpeech: 'danh từ' },
      { kanji: '腕前', kana: 'うでまえ', romaji: 'udemae', meaning: 'tay nghề, năng lực', partOfSpeech: 'danh từ' },
      { kanji: '伜', kana: 'せがれ', romaji: 'segare', meaning: 'con trai (khiêm nhường)', partOfSpeech: 'danh từ' },
      { kanji: '傲ります', kana: 'おごります', romaji: 'ogorimasu', meaning: 'kiêu ngạo, tự cao', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '咎めます', kana: 'とがめます', romaji: 'togamemasu', meaning: 'trách móc, quở trách', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '呟きます', kana: 'つぶやきます', romaji: 'tsubuyakimasu', meaning: 'lẩm bẩm, thì thầm', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '咄嗟', kana: 'とっさ', romaji: 'tossa', meaning: 'trong khoảnh khắc, tức thì', partOfSpeech: 'danh từ' },
      { kanji: '嘴', kana: 'くちばし', romaji: 'kuchibashi', meaning: 'mỏ (chim)', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 1037,
    jlptLevel: 'N1',
    words: [
      { kanji: '囀ります', kana: 'さえずります', romaji: 'saezurimasu', meaning: 'hót líu lo (chim)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '夥しい', kana: 'おびただしい', romaji: 'obitadashii', meaning: 'rất nhiều, vô số', partOfSpeech: 'tính từ i' },
      { kanji: '婉曲', kana: 'えんきょく', romaji: 'enkyoku', meaning: 'uyển chuyển, vòng vo', partOfSpeech: 'tính từ na' },
      { kanji: '嫋か', kana: 'しなやか', romaji: 'shinayaka', meaning: 'mềm mại, uyển chuyển', partOfSpeech: 'tính từ na' },
      { kanji: '屎尿', kana: 'しにょう', romaji: 'shinyō', meaning: 'chất thải, phân và nước tiểu', partOfSpeech: 'danh từ' },
      { kanji: '抓ります', kana: 'つねります', romaji: 'tsunerimasu', meaning: 'véo, ngắt', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '拗れます', kana: 'こじれます', romaji: 'kojiremasu', meaning: 'trở nên phức tạp, xấu đi', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '揉めます', kana: 'もめます', romaji: 'momemasu', meaning: 'tranh cãi, bất đồng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '擽ぐったい', kana: 'くすぐったい', romaji: 'kusuguttai', meaning: 'buồn (khi bị cù), nhột', partOfSpeech: 'tính từ i' },
      { kanji: '鬱陶しい', kana: 'うっとうしい', romaji: 'uttōshii', meaning: 'u ám, khó chịu (thời tiết, tâm trạng)', partOfSpeech: 'tính từ i' },
      { kanji: '洒落', kana: 'しゃらく', romaji: 'sharaku', meaning: 'phóng khoáng, cởi mở', partOfSpeech: 'tính từ na' },
      { kanji: '洒落ます', kana: 'しゃれます', romaji: 'sharemasu', meaning: 'chơi chữ, ăn diện', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '滲みます', kana: 'にじみます', romaji: 'nijimimasu', meaning: 'loang ra, thấm ra', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '煌々と', kana: 'こうこうと', romaji: 'kōkōto', meaning: 'sáng rực rỡ', partOfSpeech: 'phó từ' },
      { kanji: '煌びやか', kana: 'きらびやか', romaji: 'kirabiyaka', meaning: 'lộng lẫy, chói lọi', partOfSpeech: 'tính từ na' },
      { kanji: '皺', kana: 'しわ', romaji: 'shiwa', meaning: 'nếp nhăn', partOfSpeech: 'danh từ' },
      { kanji: '瞑ります', kana: 'つぶります', romaji: 'tsuburimasu', meaning: 'nhắm mắt lại', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 1038,
    jlptLevel: 'N1',
    words: [
      { kanji: '碌な', kana: 'ろくな', romaji: 'rokuna', meaning: 'tử tế, ra hồn (đi với phủ định)', partOfSpeech: 'từ hạn định' },
      { kanji: '碌に', kana: 'ろくに', romaji: 'rokuni', meaning: 'một cách đàng hoàng (đi với phủ định)', partOfSpeech: 'phó từ' },
      { kanji: '籤引', kana: 'くじびき', romaji: 'kujibiki', meaning: 'sự bốc thăm', partOfSpeech: 'danh từ' },
      { kanji: '聳えます', kana: 'そびえます', romaji: 'sobiemasu', meaning: 'sừng sững, cao vút', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '蕾', kana: 'つぼみ', romaji: 'tsubomi', meaning: 'nụ hoa', partOfSpeech: 'danh từ' },
      { kanji: '誂えます', kana: 'あつらえます', romaji: 'atsuraemasu', meaning: 'đặt may, đặt làm riêng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '貶します', kana: 'けなします', romaji: 'kenashimasu', meaning: 'chê bai, nói xấu', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '齎らします', kana: 'もたらします', romaji: 'motarashimasu', meaning: 'mang lại, đem đến', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '踵', kana: 'かかと', romaji: 'kakato', meaning: 'gót chân', partOfSpeech: 'danh từ' },
      { kanji: '躾', kana: 'しつけ', romaji: 'shitsuke', meaning: 'sự giáo dục, dạy dỗ (lễ nghi)', partOfSpeech: 'danh từ' },
      { kanji: '軋みます', kana: 'きしみます', romaji: 'kishimimasu', meaning: 'kêu cọt kẹt', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '辟易', kana: 'へきえき', romaji: 'hekieki', meaning: 'chùn bước, ngán ngẩm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '逞しい', kana: 'たくましい', romaji: 'takumashii', meaning: 'cường tráng, khỏe mạnh', partOfSpeech: 'tính từ i' },
      { kanji: '黴菌', kana: 'ばいきん', romaji: 'baikin', meaning: 'vi khuẩn, mầm bệnh', partOfSpeech: 'danh từ' },
      { kanji: '鼾', kana: 'いびき', romaji: 'ibiki', meaning: 'tiếng ngáy', partOfSpeech: 'danh từ' },
    ],
  },
];
