// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 911-916.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART3: JlptVocabUnit[] = [
  {
    lessonNumber: 911,
    jlptLevel: 'N1',
    words: [
      { kana: 'フィルター', romaji: 'fuぃrutā', meaning: 'bộ lọc', partOfSpeech: 'danh từ' },
      { kana: 'ブーツ', romaji: 'būtsu', meaning: 'giày bốt', partOfSpeech: 'danh từ' },
      { kana: 'ブーム', romaji: 'būmu', meaning: 'cơn sốt, trào lưu', partOfSpeech: 'danh từ' },
      { kana: 'フェリー', romaji: 'fuぇrī', meaning: 'phà', partOfSpeech: 'danh từ' },
      { kana: 'フォーム', romaji: 'fuぉmu', meaning: 'tư thế, hình thức', partOfSpeech: 'danh từ' },
      { kana: 'ぶかぶか', romaji: 'bukabuka', meaning: 'quá rộng, lùng bùng', partOfSpeech: 'phó từ, tính từ na' },
      { kana: 'ブザー', romaji: 'buzā', meaning: 'còi báo, chuông báo', partOfSpeech: 'danh từ' },
      { kana: 'ぶらぶら', romaji: 'burabura', meaning: 'lang thang, đung đưa', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'ブルー', romaji: 'burū', meaning: 'màu xanh dương; buồn bã', partOfSpeech: 'danh từ, tính từ na' },
      { kana: 'ふんだん', romaji: 'fundan', meaning: 'dồi dào, phong phú', partOfSpeech: 'tính từ na' },
      { kana: 'ペア', romaji: 'pea', meaning: 'cặp đôi', partOfSpeech: 'danh từ' },
      { kana: 'ベース', romaji: 'bēsu', meaning: 'nền tảng, căn cứ', partOfSpeech: 'danh từ' },
      { kana: 'ぺこぺこ', romaji: 'pekopeko', meaning: 'đói meo; khúm núm', partOfSpeech: 'phó từ, tính từ na, động từ する' },
      { kana: 'ベスト', romaji: 'besuto', meaning: 'tốt nhất; áo gi lê', partOfSpeech: 'danh từ' },
      { kana: 'ベストセラー', romaji: 'besutoserā', meaning: 'sách bán chạy nhất', partOfSpeech: 'danh từ' },
      { kana: 'ボイコット', romaji: 'boikotto', meaning: 'sự tẩy chay', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'ポイント', romaji: 'pointo', meaning: 'điểm mấu chốt, điểm số', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 912,
    jlptLevel: 'N1',
    words: [
      { kana: 'ホース', romaji: 'hōsu', meaning: 'vòi (ống dẫn nước)', partOfSpeech: 'danh từ' },
      { kana: 'ホール', romaji: 'hōru', meaning: 'sảnh, hội trường', partOfSpeech: 'danh từ' },
      { kana: 'ポジション', romaji: 'pojishon', meaning: 'vị trí, chức vụ', partOfSpeech: 'danh từ' },
      { kana: 'ほっと', romaji: 'hotto', meaning: 'thở phào nhẹ nhõm', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'ポット', romaji: 'potto', meaning: 'ấm, bình giữ nhiệt', partOfSpeech: 'danh từ' },
      { kana: 'ぼつぼつ', romaji: 'botsubotsu', meaning: 'dần dần, lác đác', partOfSpeech: 'phó từ' },
      { kanji: 'ぼやきます', kana: 'ぼやきます', romaji: 'boyakimasu', meaning: 'càu nhàu, ca thán', partOfSpeech: 'động từ nhóm 1' },
      { kanji: 'ぼやけます', kana: 'ぼやけます', romaji: 'boyakemasu', meaning: 'trở nên mờ nhạt, mờ đi', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'ボルト', romaji: 'boruto', meaning: 'vôn; bu lông', partOfSpeech: 'danh từ' },
      { kana: 'ポンプ', romaji: 'ponpu', meaning: 'máy bơm', partOfSpeech: 'danh từ' },
      { kanji: 'まごつきます', kana: 'まごつきます', romaji: 'magotsukimasu', meaning: 'bối rối, lúng túng', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'マスコミ', romaji: 'masukomi', meaning: 'truyền thông đại chúng', partOfSpeech: 'danh từ' },
      { kana: 'マッサージ', romaji: 'massāji', meaning: 'sự mát-xa', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'ミスプリント', romaji: 'misupurinto', meaning: 'lỗi in ấn', partOfSpeech: 'danh từ' },
      { kana: 'ミセス', romaji: 'misesu', meaning: 'bà (phụ nữ đã kết hôn)', partOfSpeech: 'danh từ' },
      { kana: 'ムード', romaji: 'mūdo', meaning: 'không khí, tâm trạng chung', partOfSpeech: 'danh từ' },
      { kana: 'メーカー', romaji: 'mēkā', meaning: 'nhà sản xuất', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 913,
    jlptLevel: 'N1',
    words: [
      { kana: 'メッセージ', romaji: 'messēji', meaning: 'thông điệp', partOfSpeech: 'danh từ' },
      { kana: 'メディア', romaji: 'medeぃa', meaning: 'truyền thông, phương tiện', partOfSpeech: 'danh từ' },
      { kana: 'メロディー', romaji: 'merodeぃ', meaning: 'giai điệu', partOfSpeech: 'danh từ' },
      { kana: 'モーテル', romaji: 'mōteru', meaning: 'nhà nghỉ ven đường (motel)', partOfSpeech: 'danh từ' },
      { kana: 'モニター', romaji: 'monitā', meaning: 'màn hình; người theo dõi', partOfSpeech: 'danh từ' },
      { kana: 'もろに', romaji: 'moroni', meaning: 'trực diện, hoàn toàn', partOfSpeech: 'phó từ' },
      { kana: 'ややこしい', romaji: 'yayakoshii', meaning: 'rắc rối, khó hiểu', partOfSpeech: 'tính từ i' },
      { kanji: 'やり遂げます', kana: 'やりとげます', romaji: 'yaritogemasu', meaning: 'hoàn thành trọn vẹn', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'ゆとり', romaji: 'yutori', meaning: 'sự dư dả, khoảng trống', partOfSpeech: 'danh từ' },
      { kana: 'ユニーク', romaji: 'yunīku', meaning: 'độc đáo, có một không hai', partOfSpeech: 'tính từ na' },
      { kana: 'ユニフォーム', romaji: 'yunifuぉmu', meaning: 'đồng phục', partOfSpeech: 'danh từ' },
      { kana: 'ライス', romaji: 'raisu', meaning: 'cơm (kiểu Tây)', partOfSpeech: 'danh từ' },
      { kana: 'ラベル', romaji: 'raberu', meaning: 'nhãn dán', partOfSpeech: 'danh từ' },
      { kana: 'ランプ', romaji: 'ranpu', meaning: 'đèn', partOfSpeech: 'danh từ' },
      { kana: 'ルーズ', romaji: 'rūzu', meaning: 'lỏng lẻo, thiếu kỷ luật', partOfSpeech: 'tính từ na' },
      { kana: 'ルール', romaji: 'rūru', meaning: 'quy tắc', partOfSpeech: 'danh từ' },
      { kana: 'レース', romaji: 'rēsu', meaning: 'cuộc đua; ren (vải)', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 914,
    jlptLevel: 'N1',
    words: [
      { kana: 'レギュラー', romaji: 'regyurā', meaning: 'chính thức, thường xuyên', partOfSpeech: 'danh từ, tính từ na' },
      { kana: 'レッスン', romaji: 'ressun', meaning: 'buổi học, bài học', partOfSpeech: 'danh từ' },
      { kana: 'レディー', romaji: 'redeぃ', meaning: 'quý bà', partOfSpeech: 'danh từ' },
      { kana: 'レンジ', romaji: 'renji', meaning: 'lò vi sóng; phạm vi', partOfSpeech: 'danh từ' },
      { kana: 'レンタカー', romaji: 'rentakā', meaning: 'xe cho thuê', partOfSpeech: 'danh từ' },
      { kana: 'レントゲン', romaji: 'rentogen', meaning: 'chụp X-quang', partOfSpeech: 'danh từ' },
      { kana: 'ロープ', romaji: 'rōpu', meaning: 'dây thừng', partOfSpeech: 'danh từ' },
      { kana: 'ロマンチック', romaji: 'romanchikku', meaning: 'lãng mạn', partOfSpeech: 'tính từ na' },
      { kana: 'ワット', romaji: 'watto', meaning: 'oát (đơn vị công suất)', partOfSpeech: 'danh từ' },
      { kanji: '愛想', kana: 'あいそ', romaji: 'aiso', meaning: 'sự thân thiện, lịch thiệp', partOfSpeech: 'danh từ' },
      { kanji: '悪化', kana: 'あっか', romaji: 'akka', meaning: 'sự xấu đi, trở nên tệ hơn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '悪口', kana: 'あっこう', romaji: 'akkō', meaning: 'lời nói xấu, sỉ nhục', partOfSpeech: 'danh từ' },
      { kanji: '悪者', kana: 'わるもの', romaji: 'warumono', meaning: 'kẻ xấu', partOfSpeech: 'danh từ' },
      { kanji: '葦', kana: 'よし', romaji: 'yoshi', meaning: 'cây sậy', partOfSpeech: 'danh từ' },
      { kanji: '圧力', kana: 'あつりょく', romaji: 'atsuryoku', meaning: 'áp lực', partOfSpeech: 'danh từ' },
      { kanji: '扱い', kana: 'あつかい', romaji: 'atsukai', meaning: 'cách xử lý, cách đối xử', partOfSpeech: 'danh từ' },
      { kanji: '宛', kana: 'あて', romaji: 'ate', meaning: 'gửi đến, dành cho', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 915,
    jlptLevel: 'N1',
    words: [
      { kanji: '安っぽい', kana: 'やすっぽい', romaji: 'yasuppoi', meaning: 'rẻ tiền, kém chất lượng', partOfSpeech: 'tính từ i' },
      { kanji: '安静', kana: 'あんせい', romaji: 'ansei', meaning: 'sự nghỉ ngơi tĩnh dưỡng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '暗殺', kana: 'あんさつ', romaji: 'ansatsu', meaning: 'vụ ám sát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '暗算', kana: 'あんざん', romaji: 'anzan', meaning: 'tính nhẩm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '案じます', kana: 'あんじます', romaji: 'anjimasu', meaning: 'lo lắng, suy tính', partOfSpeech: 'động từ する' },
      { kanji: '案の定', kana: 'あんのじょう', romaji: 'annojō', meaning: 'quả đúng như dự đoán', partOfSpeech: 'phó từ' },
      { kanji: '闇', kana: 'やみ', romaji: 'yami', meaning: 'bóng tối; chợ đen', partOfSpeech: 'danh từ' },
      { kanji: '以て', kana: 'もって', romaji: 'motte', meaning: 'bằng, với; vì lẽ đó', partOfSpeech: 'phó từ' },
      { kanji: '依って', kana: 'よって', romaji: 'yotte', meaning: 'do đó, vì vậy', partOfSpeech: 'liên từ' },
      { kanji: '依存', kana: 'いそん', romaji: 'ison', meaning: 'sự phụ thuộc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '委託', kana: 'いたく', romaji: 'itaku', meaning: 'sự ủy thác, giao phó', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '威力', kana: 'いりょく', romaji: 'iryoku', meaning: 'uy lực, sức mạnh', partOfSpeech: 'danh từ' },
      { kanji: '意気込みます', kana: 'いきごみます', romaji: 'ikigomimasu', meaning: 'hào hứng, hăng hái', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '為来り', kana: 'しきたり', romaji: 'shikitari', meaning: 'tập tục, thông lệ', partOfSpeech: 'danh từ' },
      { kanji: '異性', kana: 'いせい', romaji: 'isei', meaning: 'người khác giới', partOfSpeech: 'danh từ' },
      { kanji: '異論', kana: 'いろん', romaji: 'iron', meaning: 'ý kiến khác, sự phản đối', partOfSpeech: 'danh từ' },
      { kanji: '移住', kana: 'いじゅう', romaji: 'ijū', meaning: 'sự di cư', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 916,
    jlptLevel: 'N1',
    words: [
      { kanji: '移民', kana: 'いみん', romaji: 'imin', meaning: 'người di dân, sự di dân', partOfSpeech: 'danh từ' },
      { kanji: '萎びます', kana: 'しなびます', romaji: 'shinabimasu', meaning: 'héo úa, teo tóp', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '衣装', kana: 'いしょう', romaji: 'ishō', meaning: 'trang phục', partOfSpeech: 'danh từ' },
      { kanji: '衣類', kana: 'いるい', romaji: 'irui', meaning: 'quần áo', partOfSpeech: 'danh từ' },
      { kanji: '違えます', kana: 'ちがえます', romaji: 'chigaemasu', meaning: 'làm sai, làm khác đi', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '遺跡', kana: 'いせき', romaji: 'iseki', meaning: 'di tích lịch sử', partOfSpeech: 'danh từ' },
      { kanji: '育ち', kana: 'そだち', romaji: 'sodachi', meaning: 'sự nuôi dưỡng, trưởng thành', partOfSpeech: 'danh từ' },
      { kanji: '一概に', kana: 'いちがいに', romaji: 'ichigaini', meaning: 'một cách chung chung, khái quát', partOfSpeech: 'phó từ' },
    ],
  },
];
