// Bổ sung từ vựng N2 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 718-723.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N2_PART4: JlptVocabUnit[] = [
  {
    lessonNumber: 718,
    jlptLevel: 'N2',
    words: [
      { kanji: '運河', kana: 'うんが', romaji: 'unga', meaning: 'kênh đào', partOfSpeech: 'danh từ' },
      { kanji: '英文', kana: 'えいぶん', romaji: 'eibun', meaning: 'văn bản tiếng Anh', partOfSpeech: 'danh từ' },
      { kanji: '英和', kana: 'えいわ', romaji: 'eiwa', meaning: 'Anh-Nhật (từ điển)', partOfSpeech: 'danh từ' },
      { kanji: '液体', kana: 'えきたい', romaji: 'ekitai', meaning: 'chất lỏng', partOfSpeech: 'danh từ' },
      { kanji: '円周', kana: 'えんしゅう', romaji: 'enshū', meaning: 'chu vi hình tròn', partOfSpeech: 'danh từ' },
      { kanji: '園芸', kana: 'えんげい', romaji: 'engei', meaning: 'nghề làm vườn', partOfSpeech: 'danh từ' },
      { kanji: '宴会', kana: 'えんかい', romaji: 'enkai', meaning: 'tiệc, buổi liên hoan', partOfSpeech: 'danh từ' },
      { kanji: '演劇', kana: 'えんげき', romaji: 'engeki', meaning: 'kịch nghệ, vở kịch', partOfSpeech: 'danh từ' },
      { kanji: '煙い', kana: 'けむい', romaji: 'kemui', meaning: 'cay khói, ngột ngạt vì khói', partOfSpeech: 'tính từ i' },
      { kanji: '煙突', kana: 'えんとつ', romaji: 'entotsu', meaning: 'ống khói', partOfSpeech: 'danh từ' },
      { kanji: '艶', kana: 'つや', romaji: 'tsuya', meaning: 'độ bóng, sự bóng loáng', partOfSpeech: 'danh từ' },
      { kanji: '遠足', kana: 'えんそく', romaji: 'ensoku', meaning: 'chuyến dã ngoại', partOfSpeech: 'danh từ' },
      { kanji: '塩辛い', kana: 'しおからい', romaji: 'shiokarai', meaning: 'mặn (vị)', partOfSpeech: 'tính từ i' },
      { kanji: '凹みます', kana: 'へこみます', romaji: 'hekomimasu', meaning: 'bị lõm, bị móp', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '応援', kana: 'おうえん', romaji: 'ōen', meaning: 'sự cổ vũ, ủng hộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '応接', kana: 'おうせつ', romaji: 'ōsetsu', meaning: 'sự tiếp đón', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '応対', kana: 'おうたい', romaji: 'ōtai', meaning: 'sự ứng đối, tiếp khách', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 719,
    jlptLevel: 'N2',
    words: [
      { kanji: '押えます', kana: 'おさえます', romaji: 'osaemasu', meaning: 'đè xuống, kìm nén', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '欧米', kana: 'おうべい', romaji: 'ōbei', meaning: 'Âu Mỹ, phương Tây', partOfSpeech: 'danh từ' },
      { kanji: '王女', kana: 'おうじょ', romaji: 'ōjo', meaning: 'công chúa', partOfSpeech: 'danh từ' },
      { kanji: '襖', kana: 'ふすま', romaji: 'fusuma', meaning: 'cửa trượt kiểu Nhật (fusuma)', partOfSpeech: 'danh từ' },
      { kanji: '屋外', kana: 'おくがい', romaji: 'okugai', meaning: 'ngoài trời', partOfSpeech: 'danh từ' },
      { kanji: '温室', kana: 'おんしつ', romaji: 'onshitsu', meaning: 'nhà kính', partOfSpeech: 'danh từ' },
      { kanji: '温帯', kana: 'おんたい', romaji: 'ontai', meaning: 'vùng ôn đới', partOfSpeech: 'danh từ' },
      { kanji: '下ります', kana: 'くだります', romaji: 'kudarimasu', meaning: 'đi xuống, xuống (dốc, sông)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '下車', kana: 'げしゃ', romaji: 'gesha', meaning: 'sự xuống xe', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '下旬', kana: 'げじゅん', romaji: 'gejun', meaning: 'hạ tuần (10 ngày cuối tháng)', partOfSpeech: 'danh từ' },
      { kanji: '下書き', kana: 'したがき', romaji: 'shitagaki', meaning: 'bản nháp', partOfSpeech: 'danh từ' },
      { kanji: '下水', kana: 'げすい', romaji: 'gesui', meaning: 'nước thải, cống rãnh', partOfSpeech: 'danh từ' },
      { kanji: '下線', kana: 'かせん', romaji: 'kasen', meaning: 'gạch chân', partOfSpeech: 'danh từ' },
      { kanji: '下駄', kana: 'げた', romaji: 'geta', meaning: 'guốc gỗ Nhật Bản', partOfSpeech: 'danh từ' },
      { kanji: '下町', kana: 'したまち', romaji: 'shitamachi', meaning: 'khu phố cổ, phố dưới', partOfSpeech: 'danh từ' },
      { kanji: '下品', kana: 'げひん', romaji: 'gehin', meaning: 'thô tục, thiếu lịch sự', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '仮名遣い', kana: 'かなづかい', romaji: 'kanazukai', meaning: 'cách viết chữ kana', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 720,
    jlptLevel: 'N2',
    words: [
      { kanji: '何々', kana: 'なになに', romaji: 'naninani', meaning: 'cái này cái kia (chưa xác định)', partOfSpeech: 'đại từ' },
      { kanji: '何分', kana: 'なにぶん', romaji: 'nanibun', meaning: 'dù sao thì, xin hãy (nhờ vả)', partOfSpeech: 'phó từ' },
      { kanji: '加速', kana: 'かそく', romaji: 'kasoku', meaning: 'sự tăng tốc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '加速度', kana: 'かそくど', romaji: 'kasokudo', meaning: 'gia tốc', partOfSpeech: 'danh từ' },
      { kanji: '加熱', kana: 'かねつ', romaji: 'kanetsu', meaning: 'sự đun nóng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '可決', kana: 'かけつ', romaji: 'kaketsu', meaning: 'sự thông qua (dự luật)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '家屋', kana: 'かおく', romaji: 'kaoku', meaning: 'nhà ở, kiến trúc nhà', partOfSpeech: 'danh từ' },
      { kanji: '家主', kana: 'やぬし', romaji: 'yanushi', meaning: 'chủ nhà', partOfSpeech: 'danh từ' },
      { kanji: '果して', kana: 'はたして', romaji: 'hatashite', meaning: 'quả nhiên, đúng như dự đoán', partOfSpeech: 'phó từ' },
      { kanji: '果実', kana: 'かじつ', romaji: 'kajitsu', meaning: 'quả, trái cây', partOfSpeech: 'danh từ' },
      { kanji: '架空', kana: 'かくう', romaji: 'kakū', meaning: 'hư cấu, tưởng tượng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '火山', kana: 'かざん', romaji: 'kazan', meaning: 'núi lửa', partOfSpeech: 'danh từ' },
      { kanji: '花嫁', kana: 'はなよめ', romaji: 'hanayome', meaning: 'cô dâu', partOfSpeech: 'danh từ' },
      { kanji: '課税', kana: 'かぜい', romaji: 'kazei', meaning: 'sự đánh thuế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '貨物', kana: 'かもつ', romaji: 'kamotsu', meaning: 'hàng hóa (vận chuyển)', partOfSpeech: 'danh từ' },
      { kanji: '過半数', kana: 'かはんすう', romaji: 'kahansū', meaning: 'đa số, quá bán', partOfSpeech: 'danh từ' },
      { kanji: '蚊', kana: 'か', romaji: 'ka', meaning: 'con muỗi', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 721,
    jlptLevel: 'N2',
    words: [
      { kanji: '俄', kana: 'にわか', romaji: 'niwaka', meaning: 'đột ngột, bất chợt', partOfSpeech: 'tính từ na' },
      { kanji: '会館', kana: 'かいかん', romaji: 'kaikan', meaning: 'hội quán, nhà hội họp', partOfSpeech: 'danh từ' },
      { kanji: '解説', kana: 'かいせつ', romaji: 'kaisetsu', meaning: 'lời giải thích, bình luận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '解放', kana: 'かいほう', romaji: 'kaihō', meaning: 'sự giải phóng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '回り道', kana: 'まわりみち', romaji: 'mawarimichi', meaning: 'đường vòng', partOfSpeech: 'danh từ' },
      { kanji: '回数', kana: 'かいすう', romaji: 'kaisū', meaning: 'số lần', partOfSpeech: 'danh từ' },
      { kanji: '回数券', kana: 'かいすうけん', romaji: 'kaisūken', meaning: 'vé tập (dùng nhiều lần)', partOfSpeech: 'danh từ' },
      { kanji: '回転', kana: 'かいてん', romaji: 'kaiten', meaning: 'sự xoay vòng, quay', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '塊', kana: 'かたまり', romaji: 'katamari', meaning: 'cục, khối, đám', partOfSpeech: 'danh từ' },
      { kanji: '快晴', kana: 'かいせい', romaji: 'kaisei', meaning: 'trời quang mây tạnh', partOfSpeech: 'danh từ' },
      { kanji: '怪しい', kana: 'あやしい', romaji: 'ayashii', meaning: 'đáng ngờ, khả nghi', partOfSpeech: 'tính từ i' },
      { kanji: '悔しい', kana: 'くやしい', romaji: 'kuyashii', meaning: 'tức tối, cay cú', partOfSpeech: 'tính từ i' },
      { kanji: '悔やみます', kana: 'くやみます', romaji: 'kuyamimasu', meaning: 'hối tiếc, ân hận', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '懐かしい', kana: 'なつかしい', romaji: 'natsukashii', meaning: 'hoài niệm, nhớ nhung', partOfSpeech: 'tính từ i' },
      { kanji: '改めて', kana: 'あらためて', romaji: 'aratamete', meaning: 'một lần nữa, lại (chính thức)', partOfSpeech: 'phó từ' },
      { kanji: '改めます', kana: 'あらためます', romaji: 'aratamemasu', meaning: 'sửa đổi, cải cách', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '改札', kana: 'かいさつ', romaji: 'kaisatsu', meaning: 'cổng soát vé', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 722,
    jlptLevel: 'N2',
    words: [
      { kanji: '改造', kana: 'かいぞう', romaji: 'kaizō', meaning: 'sự cải tạo, sửa đổi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '海水浴', kana: 'かいすいよく', romaji: 'kaisuiyoku', meaning: 'sự tắm biển', partOfSpeech: 'danh từ' },
      { kanji: '海洋', kana: 'かいよう', romaji: 'kaiyō', meaning: 'đại dương', partOfSpeech: 'danh từ' },
      { kanji: '灰色', kana: 'はいいろ', romaji: 'haiiro', meaning: 'màu xám', partOfSpeech: 'danh từ' },
      { kanji: '絵の具', kana: 'えのぐ', romaji: 'enogu', meaning: 'màu vẽ, hộp màu', partOfSpeech: 'danh từ' },
      { kanji: '開会', kana: 'かいかい', romaji: 'kaikai', meaning: 'sự khai mạc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '開通', kana: 'かいつう', romaji: 'kaitsū', meaning: 'sự thông tuyến, khai thông', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '外れます', kana: 'はずれます', romaji: 'hazuremasu', meaning: 'bị tuột ra, sai lệch (dự đoán)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '外科', kana: 'げか', romaji: 'geka', meaning: 'khoa ngoại (bệnh viện)', partOfSpeech: 'danh từ' },
      { kanji: '外部', kana: 'がいぶ', romaji: 'gaibu', meaning: 'bên ngoài, ngoại bộ', partOfSpeech: 'danh từ' },
      { kanji: '概論', kana: 'がいろん', romaji: 'gairon', meaning: 'khái luận, tổng quan', partOfSpeech: 'danh từ' },
      { kanji: '街角', kana: 'まちかど', romaji: 'machikado', meaning: 'góc phố', partOfSpeech: 'danh từ' },
      { kanji: '垣根', kana: 'かきね', romaji: 'kakine', meaning: 'hàng rào', partOfSpeech: 'danh từ' },
      { kanji: '各々', kana: 'おのおの', romaji: 'onōno', meaning: 'mỗi người, mỗi cái', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '各自', kana: 'かくじ', romaji: 'kakuji', meaning: 'mỗi cá nhân', partOfSpeech: 'danh từ' },
      { kanji: '各地', kana: 'かくち', romaji: 'kakuchi', meaning: 'khắp nơi, mọi nơi', partOfSpeech: 'danh từ' },
      { kanji: '拡充', kana: 'かくじゅう', romaji: 'kakujū', meaning: 'sự mở rộng, tăng cường', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 723,
    jlptLevel: 'N2',
    words: [
      { kanji: '拡張', kana: 'かくちょう', romaji: 'kakuchō', meaning: 'sự mở rộng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '格別', kana: 'かくべつ', romaji: 'kakubetsu', meaning: 'đặc biệt, ngoại lệ', partOfSpeech: 'tính từ na, phó từ' },
      { kanji: '角度', kana: 'かくど', romaji: 'kakudo', meaning: 'góc độ', partOfSpeech: 'danh từ' },
      { kanji: '隔てます', kana: 'へだてます', romaji: 'hedatemasu', meaning: 'ngăn cách, cách biệt', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '学科', kana: 'がっか', romaji: 'gakka', meaning: 'ngành học, môn học', partOfSpeech: 'danh từ' },
      { kanji: '学会', kana: 'がっかい', romaji: 'gakkai', meaning: 'hội học thuật', partOfSpeech: 'danh từ' },
      { kanji: '学級', kana: 'がっきゅう', romaji: 'gakkyū', meaning: 'lớp học', partOfSpeech: 'danh từ' },
      { kanji: '学術', kana: 'がくじゅつ', romaji: 'gakujutsu', meaning: 'học thuật', partOfSpeech: 'danh từ' },
      { kanji: '学年', kana: 'がくねん', romaji: 'gakunen', meaning: 'khối lớp, năm học', partOfSpeech: 'danh từ' },
      { kanji: '学部', kana: 'がくぶ', romaji: 'gakubu', meaning: 'khoa (đại học)', partOfSpeech: 'danh từ' },
      { kanji: '学力', kana: 'がくりょく', romaji: 'gakuryoku', meaning: 'năng lực học tập', partOfSpeech: 'danh từ' },
      { kanji: '掛け算', kana: 'かけざん', romaji: 'kakezan', meaning: 'phép nhân', partOfSpeech: 'danh từ' },
      { kanji: '割と', kana: 'わりと', romaji: 'warito', meaning: 'tương đối, khá là', partOfSpeech: 'phó từ' },
      { kanji: '割算', kana: 'わりざん', romaji: 'warizan', meaning: 'phép chia', partOfSpeech: 'danh từ' },
    ],
  },
];
