// Tail batch — lessons 416–417 (N2), 510–514 (N1)
import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_EXPAND_EXTRA_TAIL: JlptVocabUnit[] = [
  {
    lessonNumber: 416,
    jlptLevel: 'N2',
    words: [
      { kanji: '潮流', kana: 'ちょうりゅう', romaji: 'chōryū', meaning: 'dòng chảy, xu thế', partOfSpeech: 'danh từ' },
      { kanji: '風潮', kana: 'ふうちょう', romaji: 'fūchō', meaning: 'khí thế thời đại', partOfSpeech: 'danh từ' },
      { kanji: '世論', kana: 'よろん', romaji: 'yoron', meaning: 'dư luận', partOfSpeech: 'danh từ' },
      { kanji: '世論調査', kana: 'よろんちょうさ', romaji: 'yoron chōsa', meaning: 'khảo sát dư luận', partOfSpeech: 'danh từ' },
      { kanji: '支持', kana: 'しじ', romaji: 'shiji', meaning: 'ủng hộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '支持率', kana: 'しじりつ', romaji: 'shijiritsu', meaning: 'tỷ lệ ủng hộ', partOfSpeech: 'danh từ' },
      { kanji: '反発', kana: 'はんぱつ', romaji: 'hanpatsu', meaning: 'phản ứng, phản đối', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '反動', kana: 'はんどう', romaji: 'handō', meaning: 'phản ứng ngược', partOfSpeech: 'danh từ' },
      { kanji: '抵抗', kana: 'ていこう', romaji: 'teikō', meaning: 'kháng cự', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '屈折', kana: 'くっせつ', romaji: 'kussetsu', meaning: 'khúc xạ, uốn éo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '推移', kana: 'すいい', romaji: 'suii', meaning: 'biến đổi dần', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '転換', kana: 'てんかん', romaji: 'tenkan', meaning: 'chuyển đổi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '転機', kana: 'てんき', romaji: 'tenki', meaning: 'bước ngoặt', partOfSpeech: 'danh từ' },
      { kanji: '契機', kana: 'けいき', romaji: 'keiki', meaning: 'dịp, cơ hội', partOfSpeech: 'danh từ' },
      { kanji: '好機', kana: 'こうき', romaji: 'kōki', meaning: 'thời cơ tốt', partOfSpeech: 'danh từ' },
      { kanji: '移行', kana: 'いこう', romaji: 'ikō', meaning: 'chuyển tiếp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '過渡期', kana: 'かとき', romaji: 'katoki', meaning: 'giai đoạn chuyển tiếp', partOfSpeech: 'danh từ' },
      { kanji: '変容', kana: 'へんよう', romaji: "hen'yō", meaning: 'biến dạng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '変貌', kana: 'へんぼう', romaji: 'henbō', meaning: 'thay đổi diện mạo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '激変', kana: 'げきへん', romaji: 'gekihen', meaning: 'biến động mạnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '急激', kana: 'きゅうげき', romaji: 'kyūgeki', meaning: 'đột ngột, mạnh', partOfSpeech: 'tính từ na' },
      { kanji: '緩やか', kana: 'ゆるやか', romaji: 'yuruyaka', meaning: 'dịu dàng, từ từ', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 417,
    jlptLevel: 'N2',
    words: [
      { kanji: '資格', kana: 'しかく', romaji: 'shikaku', meaning: 'tư cách, bằng cấp', partOfSpeech: 'danh từ' },
      { kanji: '免許', kana: 'めんきょ', romaji: 'menkyo', meaning: 'giấy phép', partOfSpeech: 'danh từ' },
      { kanji: '資格試験', kana: 'しかくしけん', romaji: 'shikaku shiken', meaning: 'kỳ thi chứng chỉ', partOfSpeech: 'danh từ' },
      { kanji: '合格', kana: 'ごうかく', romaji: 'gōkaku', meaning: 'đậu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '不合格', kana: 'ふごうかく', romaji: 'fugōkaku', meaning: 'trượt', partOfSpeech: 'danh từ' },
      { kanji: '採用', kana: 'さいよう', romaji: 'saiyō', meaning: 'tuyển dụng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '不採用', kana: 'ふさいよう', romaji: 'fusaiyō', meaning: 'không tuyển', partOfSpeech: 'danh từ' },
      { kanji: '選考', kana: 'せんこう', romaji: 'senkō', meaning: 'tuyển chọn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '面接', kana: 'めんせつ', romaji: 'mensetsu', meaning: 'phỏng vấn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '履歴書', kana: 'りれきしょ', romaji: 'rirekisho', meaning: 'sơ yếu lý lịch', partOfSpeech: 'danh từ' },
      { kanji: '推薦', kana: 'すいせん', romaji: 'suisen', meaning: 'tiến cử', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '推薦状', kana: 'すいせんじょう', romaji: 'suisenjō', meaning: 'thư giới thiệu', partOfSpeech: 'danh từ' },
      { kanji: '経歴', kana: 'けいれき', romaji: 'keireki', meaning: 'lý lịch', partOfSpeech: 'danh từ' },
      { kanji: '実績', kana: 'じっせき', romaji: 'jisseki', meaning: 'thành tích', partOfSpeech: 'danh từ' },
      { kanji: '経験', kana: 'けいけん', romaji: 'keiken', meaning: 'kinh nghiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: 'スキル', kana: 'スキル', romaji: 'sukiru', meaning: 'kỹ năng', partOfSpeech: 'danh từ' },
      { kanji: '専門', kana: 'せんもん', romaji: 'senmon', meaning: 'chuyên môn', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '専門家', kana: 'せんもんか', romaji: 'senmonka', meaning: 'chuyên gia', partOfSpeech: 'danh từ' },
      { kanji: '熟練', kana: 'じゅくれん', romaji: 'jukuren', meaning: 'thành thạo', partOfSpeech: 'danh từ, động từ する, tính từ na' },
      { kanji: '未熟', kana: 'みじゅく', romaji: 'mijuku', meaning: 'non nớt', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '研修', kana: 'けんしゅう', romaji: 'kenshū', meaning: 'đào tạo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '育成', kana: 'いくせい', romaji: 'ikusei', meaning: 'bồi dưỡng', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 510,
    jlptLevel: 'N1',
    words: [
      { kanji: '抽象', kana: 'ちゅうしょう', romaji: 'chūshō', meaning: 'trừu tượng', partOfSpeech: 'danh từ, tính từ na, động từ する' },
      { kanji: '具体', kana: 'ぐたい', romaji: 'gutai', meaning: 'cụ thể', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '概念', kana: 'がいねん', romaji: 'gainen', meaning: 'khái niệm', partOfSpeech: 'danh từ' },
      { kanji: '本質', kana: 'ほんしつ', romaji: 'honshitsu', meaning: 'bản chất', partOfSpeech: 'danh từ' },
      { kanji: '認識', kana: 'にんしき', romaji: 'ninshiki', meaning: 'nhận thức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '意識', kana: 'いしき', romaji: 'ishiki', meaning: 'ý thức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '無意識', kana: 'むいしき', romaji: 'muishiki', meaning: 'vô thức', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '潜在', kana: 'せんざい', romaji: 'senzai', meaning: 'tiềm ẩn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '顕在', kana: 'けんざい', romaji: 'kenzai', meaning: 'hiển lộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '直感', kana: 'ちょっかん', romaji: 'chokkan', meaning: 'trực giác', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '洞察', kana: 'どうさつ', romaji: 'dōsatsu', meaning: 'sự thấu hiểu sâu sắc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '思辨', kana: 'しへん', romaji: 'shihen', meaning: 'suy biện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '論理', kana: 'ろんり', romaji: 'ronri', meaning: 'logic', partOfSpeech: 'danh từ' },
      { kanji: '理論', kana: 'りろん', romaji: 'riron', meaning: 'lý thuyết', partOfSpeech: 'danh từ' },
      { kanji: '体系', kana: 'たいけい', romaji: 'taikei', meaning: 'hệ thống', partOfSpeech: 'danh từ' },
      { kanji: '構造', kana: 'こうぞう', romaji: 'kōzō', meaning: 'cấu trúc', partOfSpeech: 'danh từ' },
      { kanji: '枠組み', kana: 'わくぐみ', romaji: 'wakugumi', meaning: 'khuôn khổ', partOfSpeech: 'danh từ' },
      { kanji: '前提', kana: 'ぜんてい', romaji: 'zentai', meaning: 'tiền đề', partOfSpeech: 'danh từ' },
      { kanji: '帰結', kana: 'きけつ', romaji: 'kiketsu', meaning: 'kết luận, hệ quả', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '演繹', kana: 'えんえき', romaji: "en'eki", meaning: 'diễn dịch (logic)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '帰納', kana: 'きのう', romaji: 'kinō', meaning: 'quy nạp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '弁証', kana: 'べんしょう', romaji: 'benshō', meaning: 'biện chứng', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 511,
    jlptLevel: 'N1',
    words: [
      { kanji: '倫理', kana: 'りんり', romaji: 'rinri', meaning: 'đạo đức', partOfSpeech: 'danh từ' },
      { kanji: '道徳', kana: 'どうとく', romaji: 'dōtoku', meaning: 'đạo đức (luân lý)', partOfSpeech: 'danh từ' },
      { kanji: '規範', kana: 'きはん', romaji: 'kihan', meaning: 'chuẩn mực', partOfSpeech: 'danh từ' },
      { kanji: '価値観', kana: 'かちかん', romaji: 'kachikan', meaning: 'giá trị quan', partOfSpeech: 'danh từ' },
      { kanji: '信念', kana: 'しんねん', romaji: 'shinnen', meaning: 'niềm tin', partOfSpeech: 'danh từ' },
      { kanji: '信条', kana: 'しんじょう', romaji: 'shinjō', meaning: 'tín điều', partOfSpeech: 'danh từ' },
      { kanji: '理念', kana: 'りねん', romaji: 'rinen', meaning: 'lý niệm', partOfSpeech: 'danh từ' },
      { kanji: '理想', kana: 'りそう', romaji: 'risō', meaning: 'lý tưởng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '現実', kana: 'げんじつ', romaji: 'genjitsu', meaning: 'thực tế', partOfSpeech: 'danh từ' },
      { kanji: '理想主義', kana: 'りそうしゅぎ', romaji: 'risō shugi', meaning: 'chủ nghĩa lý tưởng', partOfSpeech: 'danh từ' },
      { kanji: '現実主義', kana: 'げんじつしゅぎ', romaji: 'genjitsu shugi', meaning: 'chủ nghĩa thực dụng', partOfSpeech: 'danh từ' },
      { kanji: '功利', kana: 'こうり', romaji: 'kōri', meaning: 'công lợi', partOfSpeech: 'danh từ' },
      { kanji: '利他', kana: 'りた', romaji: 'rita', meaning: 'vị tha', partOfSpeech: 'danh từ' },
      { kanji: '利己', kana: 'りこ', romaji: 'riko', meaning: 'vị kỷ', partOfSpeech: 'danh từ' },
      { kanji: '慈悲', kana: 'じひ', romaji: 'jihi', meaning: 'từ bi', partOfSpeech: 'danh từ' },
      { kanji: '寛容', kana: 'かんよう', romaji: "kan'yō", meaning: 'khoan dung', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '偏見', kana: 'へんけん', romaji: 'henken', meaning: 'định kiến', partOfSpeech: 'danh từ' },
      { kanji: '公正', kana: 'こうせい', romaji: 'kōsei', meaning: 'công bằng', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '公平', kana: 'こうへい', romaji: 'kōhei', meaning: 'công bằng', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '平等', kana: 'びょうどう', romaji: 'byōdō', meaning: 'bình đẳng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '差別', kana: 'さべつ', romaji: 'sabetsu', meaning: 'phân biệt đối xử', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '人権', kana: 'じんけん', romaji: 'jinken', meaning: 'nhân quyền', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 512,
    jlptLevel: 'N1',
    words: [
      { kanji: '統治', kana: 'とうち', romaji: 'tōchi', meaning: 'thống trị', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '支配', kana: 'しはい', romaji: 'shihai', meaning: 'chi phối', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '権力', kana: 'けんりょく', romaji: 'kenryoku', meaning: 'quyền lực', partOfSpeech: 'danh từ' },
      { kanji: '権威', kana: 'けんい', romaji: "ken'i", meaning: 'uy quyền', partOfSpeech: 'danh từ' },
      { kanji: '独裁', kana: 'どくさい', romaji: 'dokusai', meaning: 'độc tài', partOfSpeech: 'danh từ' },
      { kanji: '民主', kana: 'みんしゅ', romaji: 'minshu', meaning: 'dân chủ', partOfSpeech: 'danh từ' },
      { kanji: '共和', kana: 'きょうわ', romaji: 'kyōwa', meaning: 'cộng hòa', partOfSpeech: 'danh từ' },
      { kanji: '立憲', kana: 'りっけん', romaji: 'rikken', meaning: 'lập hiến', partOfSpeech: 'danh từ' },
      { kanji: '憲法', kana: 'けんぽう', romaji: 'kenpō', meaning: 'hiến pháp', partOfSpeech: 'danh từ' },
      { kanji: '法制', kana: 'ほうせい', romaji: 'hōsei', meaning: 'pháp chế', partOfSpeech: 'danh từ' },
      { kanji: '統制', kana: 'とうせい', romaji: 'tōsei', meaning: 'kiểm soát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '監視', kana: 'かんし', romaji: 'kanshi', meaning: 'giám sát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '弾圧', kana: 'だんあつ', romaji: "dan'atsu", meaning: 'đàn áp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '鎮圧', kana: 'ちんあつ', romaji: "chin'atsu", meaning: 'trấn áp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '反乱', kana: 'はんらん', romaji: 'hanran', meaning: 'nổi loạn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '革命', kana: 'かくめい', romaji: 'kakumei', meaning: 'cách mạng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '改革', kana: 'かいかく', romaji: 'kaikaku', meaning: 'cải cách', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '変革', kana: 'へんかく', romaji: 'henkaku', meaning: 'cải cách, biến cách', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '保守', kana: 'ほしゅ', romaji: 'hoshu', meaning: 'bảo thủ', partOfSpeech: 'danh từ, động từ する, tính từ na' },
      { kanji: '革新', kana: 'かくしん', romaji: 'kakushin', meaning: 'đổi mới', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '急進', kana: 'きゅうしん', romaji: 'kyūshin', meaning: 'cấp tiến', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '漸進', kana: 'ぜんしん', romaji: 'zenshin', meaning: 'tiến bộ dần', partOfSpeech: 'danh từ, tính từ na' },
    ],
  },
  {
    lessonNumber: 513,
    jlptLevel: 'N1',
    words: [
      { kanji: '繁栄', kana: 'はんえい', romaji: "han'ei", meaning: 'thịnh vượng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '衰退', kana: 'すいたい', romaji: 'suitai', meaning: 'suy thoái', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '没落', kana: 'ぼつらく', romaji: 'botsuraku', meaning: 'sa sút', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '興亡', kana: 'こうぼう', romaji: 'kōbō', meaning: 'thịnh suy', partOfSpeech: 'danh từ' },
      { kanji: '盛衰', kana: 'せいすい', romaji: 'seisui', meaning: 'thăng trầm', partOfSpeech: 'danh từ' },
      { kanji: '勃興', kana: 'ぼっこう', romaji: 'bokkō', meaning: 'trỗi dậy', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '隆盛', kana: 'りゅうせい', romaji: 'ryūsei', meaning: 'hưng thịnh', partOfSpeech: 'danh từ' },
      { kanji: '全盛', kana: 'ぜんせい', romaji: 'zensei', meaning: 'toàn thịnh', partOfSpeech: 'danh từ' },
      { kanji: '頂点', kana: 'ちょうてん', romaji: 'chōten', meaning: 'đỉnh cao', partOfSpeech: 'danh từ' },
      { kanji: '底辺', kana: 'ていへん', romaji: 'teihen', meaning: 'tầng đáy', partOfSpeech: 'danh từ' },
      { kanji: '転落', kana: 'てんらく', romaji: 'tenraku', meaning: 'sa sút', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '崩壊', kana: 'ほうかい', romaji: 'hōkai', meaning: 'sụp đổ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '瓦解', kana: 'がかい', romaji: 'gakai', meaning: 'tan rã', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '復活', kana: 'ふっかつ', romaji: 'fukkatsu', meaning: 'hồi sinh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '再生', kana: 'さいせい', romaji: 'saisei', meaning: 'tái sinh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '再建', kana: 'さいけん', romaji: 'saiken', meaning: 'tái kiến', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '再興', kana: 'さいこう', romaji: 'saikō', meaning: 'phục hưng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '復権', kana: 'ふっけん', romaji: 'fukken', meaning: 'phục quyền', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '失脚', kana: 'しっきゃく', romaji: 'shikkyaku', meaning: 'mất ghế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '退位', kana: 'たいい', romaji: 'taii', meaning: 'thoái vị', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '継承', kana: 'けいしょう', romaji: 'keishō', meaning: 'kế thừa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '世襲', kana: 'せしゅう', romaji: 'seshū', meaning: 'thế tập', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 514,
    jlptLevel: 'N1',
    words: [
      { kanji: '美学', kana: 'びがく', romaji: 'bigaku', meaning: 'mỹ học', partOfSpeech: 'danh từ' },
      { kanji: '芸術', kana: 'げいじゅつ', romaji: 'geijutsu', meaning: 'nghệ thuật', partOfSpeech: 'danh từ' },
      { kanji: '文学', kana: 'ぶんがく', romaji: 'bungaku', meaning: 'văn học', partOfSpeech: 'danh từ' },
      { kanji: '詩歌', kana: 'しか', romaji: 'shika', meaning: 'thơ ca', partOfSpeech: 'danh từ' },
      { kanji: '叙事', kana: 'じょじ', romaji: 'joji', meaning: 'tự sự', partOfSpeech: 'danh từ' },
      { kanji: '諷刺', kana: 'ふうし', romaji: 'fūshi', meaning: 'mỉa mai', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '比喩', kana: 'ひゆ', romaji: 'hiyu', meaning: 'ẩn dụ', partOfSpeech: 'danh từ' },
      { kanji: '象徴', kana: 'しょうちょう', romaji: 'shōchō', meaning: 'biểu tượng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '寓意', kana: 'ぐうい', romaji: 'gūi', meaning: 'ngụ ý', partOfSpeech: 'danh từ' },
      { kanji: '風刺', kana: 'ふうし', romaji: 'fūshi', meaning: 'châm biếm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '風格', kana: 'ふうかく', romaji: 'fūkaku', meaning: 'phong cách', partOfSpeech: 'danh từ' },
      { kanji: '様式', kana: 'ようしき', romaji: 'yōshiki', meaning: 'hình thức nghệ thuật', partOfSpeech: 'danh từ' },
      { kanji: '流派', kana: 'りゅうは', romaji: 'ryūha', meaning: 'trường phái', partOfSpeech: 'danh từ' },
      { kanji: '巨匠', kana: 'きょしょう', romaji: 'kyoshō', meaning: 'bậc thầy', partOfSpeech: 'danh từ' },
      { kanji: '傑作', kana: 'けっさく', romaji: 'kessaku', meaning: 'kiệt tác', partOfSpeech: 'danh từ' },
      { kanji: '名作', kana: 'めいさく', romaji: 'meisaku', meaning: 'tác phẩm danh', partOfSpeech: 'danh từ' },
      { kanji: '傑出', kana: 'けっしゅつ', romaji: 'kesshutsu', meaning: 'xuất chúng', partOfSpeech: 'danh từ, động từ する, tính từ na' },
      { kanji: '卓越', kana: 'たくえつ', romaji: 'takuetsu', meaning: 'xuất sắc', partOfSpeech: 'danh từ, động từ する, tính từ na' },
      { kanji: '非凡', kana: 'ひぼん', romaji: 'hibon', meaning: 'phi thường', partOfSpeech: 'tính từ na' },
      { kanji: '独創', kana: 'どくそう', romaji: 'dokusō', meaning: 'sáng tạo độc đáo', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
];
