// Bổ sung từ vựng N3 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 314-319.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N3_PART2: JlptVocabUnit[] = [
  {
    lessonNumber: 314,
    jlptLevel: 'N3',
    words: [
      { kanji: '記事', kana: 'きじ', romaji: 'kiji', meaning: 'bài báo, bản tin', partOfSpeech: 'danh từ' },
      { kanji: '輝きます', kana: 'かがやきます', romaji: 'kagayakimasu', meaning: 'chiếu sáng, tỏa sáng, lấp lánh', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '鬼', kana: 'おに', romaji: 'oni', meaning: 'quỷ, yêu quái', partOfSpeech: 'danh từ' },
      { kanji: '技師', kana: 'ぎし', romaji: 'gishi', meaning: 'kỹ sư', partOfSpeech: 'danh từ' },
      { kanji: '議員', kana: 'ぎいん', romaji: 'giin', meaning: 'nghị sĩ, đại biểu quốc hội', partOfSpeech: 'danh từ' },
      { kanji: '議会', kana: 'ぎかい', romaji: 'gikai', meaning: 'quốc hội, nghị viện', partOfSpeech: 'danh từ' },
      { kanji: '議長', kana: 'ぎちょう', romaji: 'gichō', meaning: 'chủ tịch (cuộc họp, quốc hội)', partOfSpeech: 'danh từ' },
      { kanji: '詰めます', kana: 'つめます', romaji: 'tsumemasu', meaning: 'đóng gói, nhồi chặt; rút ngắn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '逆', kana: 'ぎゃく', romaji: 'gyaku', meaning: 'ngược lại, trái lại', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '逆らいます', kana: 'さからいます', romaji: 'sakaraimasu', meaning: 'chống đối, đi ngược lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '丘', kana: 'おか', romaji: 'oka', meaning: 'đồi, gò đất', partOfSpeech: 'danh từ' },
      { kanji: '休暇', kana: 'きゅうか', romaji: 'kyūka', meaning: 'kỳ nghỉ phép', partOfSpeech: 'danh từ' },
      { kanji: '休憩', kana: 'きゅうけい', romaji: 'kyūkei', meaning: 'sự nghỉ giải lao', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '及ぼします', kana: 'およぼします', romaji: 'oyoboshimasu', meaning: 'gây ra, tác động đến', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '吸収', kana: 'きゅうしゅう', romaji: 'kyūshū', meaning: 'sự hấp thụ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '急速', kana: 'きゅうそく', romaji: 'kyūsoku', meaning: 'nhanh chóng, mau lẹ', partOfSpeech: 'tính từ na' },
      { kanji: '救います', kana: 'すくいます', romaji: 'sukuimasu', meaning: 'cứu giúp', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 315,
    jlptLevel: 'N3',
    words: [
      { kanji: '求めます', kana: 'もとめます', romaji: 'motomemasu', meaning: 'yêu cầu, tìm kiếm, mong muốn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '牛', kana: 'うし', romaji: 'ushi', meaning: 'con bò', partOfSpeech: 'danh từ' },
      { kanji: '居眠り', kana: 'いねむり', romaji: 'inemuri', meaning: 'sự ngủ gật', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '巨大', kana: 'きょだい', romaji: 'kyodai', meaning: 'khổng lồ, to lớn', partOfSpeech: 'tính từ na' },
      { kanji: '許します', kana: 'ゆるします', romaji: 'yurushimasu', meaning: 'cho phép, tha thứ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '魚', kana: 'うお', romaji: 'uo', meaning: 'cá (cách đọc khác của 魚)', partOfSpeech: 'danh từ' },
      { kanji: '共に', kana: 'ともに', romaji: 'tomoni', meaning: 'cùng với, cùng nhau', partOfSpeech: 'phó từ' },
      { kanji: '叫びます', kana: 'さけびます', romaji: 'sakebimasu', meaning: 'la hét, kêu gào', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '境', kana: 'さかい', romaji: 'sakai', meaning: 'ranh giới, biên giới', partOfSpeech: 'danh từ' },
      { kanji: '強盗', kana: 'ごうとう', romaji: 'gōtō', meaning: 'kẻ cướp, vụ cướp', partOfSpeech: 'danh từ' },
      { kanji: '恐れます', kana: 'おそれます', romaji: 'osoremasu', meaning: 'sợ hãi, lo sợ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '恐ろしい', kana: 'おそろしい', romaji: 'osoroshii', meaning: 'đáng sợ, khủng khiếp', partOfSpeech: 'tính từ i' },
      { kanji: '教科書', kana: 'きょうかしょ', romaji: 'kyōkasho', meaning: 'sách giáo khoa', partOfSpeech: 'danh từ' },
      { kanji: '教授', kana: 'きょうじゅ', romaji: 'kyōju', meaning: 'giáo sư; sự giảng dạy', partOfSpeech: 'danh từ' },
      { kanji: '狂います', kana: 'くるいます', romaji: 'kuruimasu', meaning: 'phát điên; bị lệch, trục trặc', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '胸', kana: 'むね', romaji: 'mune', meaning: 'ngực', partOfSpeech: 'danh từ' },
      { kanji: '極', kana: 'ごく', romaji: 'goku', meaning: 'rất, cực kỳ', partOfSpeech: 'phó từ' },
    ],
  },
  {
    lessonNumber: 316,
    jlptLevel: 'N3',
    words: [
      { kanji: '玉', kana: 'たま', romaji: 'tama', meaning: 'viên bi, hòn, quả cầu', partOfSpeech: 'danh từ' },
      { kanji: '僅か', kana: 'わずか', romaji: 'wazuka', meaning: 'chỉ một chút, ít ỏi', partOfSpeech: 'tính từ na, phó từ' },
      { kanji: '勤め', kana: 'つとめ', romaji: 'tsutome', meaning: 'công việc, nghĩa vụ', partOfSpeech: 'danh từ' },
      { kanji: '筋', kana: 'すじ', romaji: 'suji', meaning: 'sợi gân, đường vân; mạch truyện', partOfSpeech: 'danh từ' },
      { kanji: '近頃', kana: 'ちかごろ', romaji: 'chikagoro', meaning: 'gần đây, dạo này', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '近代', kana: 'きんだい', romaji: 'kindai', meaning: 'thời cận đại, ngày nay', partOfSpeech: 'danh từ' },
      { kanji: '金', kana: 'かね', romaji: 'kane', meaning: 'tiền; vàng', partOfSpeech: 'danh từ' },
      { kanji: '金庫', kana: 'きんこ', romaji: 'kinko', meaning: 'két sắt, ngân khố', partOfSpeech: 'danh từ' },
      { kanji: '金銭', kana: 'きんせん', romaji: 'kinsen', meaning: 'tiền bạc', partOfSpeech: 'danh từ' },
      { kanji: '金属', kana: 'きんぞく', romaji: 'kinzoku', meaning: 'kim loại', partOfSpeech: 'danh từ' },
      { kanji: '金融', kana: 'きんゆう', romaji: 'kinyū', meaning: 'tài chính, tín dụng', partOfSpeech: 'danh từ' },
      { kanji: '銀', kana: 'ぎん', romaji: 'gin', meaning: 'bạc (kim loại)', partOfSpeech: 'danh từ' },
      { kanji: '苦しい', kana: 'くるしい', romaji: 'kurushii', meaning: 'đau đớn, khó khăn', partOfSpeech: 'tính từ i' },
      { kanji: '苦しみます', kana: 'くるしみます', romaji: 'kurushimimasu', meaning: 'chịu đựng đau khổ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '苦痛', kana: 'くつう', romaji: 'kutsū', meaning: 'sự đau đớn, thống khổ', partOfSpeech: 'danh từ' },
      { kanji: '空', kana: 'から', romaji: 'kara', meaning: 'trống rỗng, rỗng không', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '繰り返します', kana: 'くりかえします', romaji: 'kurikaeshimasu', meaning: 'lặp lại, làm đi làm lại', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 317,
    jlptLevel: 'N3',
    words: [
      { kanji: '訓', kana: 'くん', romaji: 'kun', meaning: 'cách đọc kun (âm thuần Nhật của kanji)', partOfSpeech: 'danh từ' },
      { kanji: '訓練', kana: 'くんれん', romaji: 'kunren', meaning: 'sự huấn luyện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '軍', kana: 'ぐん', romaji: 'gun', meaning: 'quân đội', partOfSpeech: 'danh từ' },
      { kanji: '軍隊', kana: 'ぐんたい', romaji: 'guntai', meaning: 'quân đội, binh đoàn', partOfSpeech: 'danh từ' },
      { kanji: '経由', kana: 'けいゆ', romaji: 'keiyu', meaning: 'quá cảnh, đi qua (một nơi)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '繋ぎます', kana: 'つなぎます', romaji: 'tsunagimasu', meaning: 'buộc, nối, kết nối', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '計算', kana: 'けいさん', romaji: 'keisan', meaning: 'sự tính toán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '警告', kana: 'けいこく', romaji: 'keikoku', meaning: 'lời cảnh cáo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '迎え', kana: 'むかえ', romaji: 'mukae', meaning: 'sự đón tiếp, người đi đón', partOfSpeech: 'danh từ' },
      { kanji: '劇', kana: 'げき', romaji: 'geki', meaning: 'vở kịch', partOfSpeech: 'danh từ' },
      { kanji: '劇場', kana: 'げきじょう', romaji: 'gekijō', meaning: 'nhà hát, rạp kịch', partOfSpeech: 'danh từ' },
      { kanji: '激しい', kana: 'はげしい', romaji: 'hageshii', meaning: 'dữ dội, mãnh liệt', partOfSpeech: 'tính từ i' },
      { kanji: '決まり', kana: 'きまり', romaji: 'kimari', meaning: 'quy định, quy tắc', partOfSpeech: 'danh từ' },
      { kanji: '決心', kana: 'けっしん', romaji: 'kesshin', meaning: 'sự quyết tâm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '穴', kana: 'あな', romaji: 'ana', meaning: 'cái lỗ, hang', partOfSpeech: 'danh từ' },
      { kanji: '結びます', kana: 'むすびます', romaji: 'musubimasu', meaning: 'buộc, thắt, liên kết', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '喧嘩', kana: 'けんか', romaji: 'kenka', meaning: 'cuộc cãi vã, đánh nhau', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 318,
    jlptLevel: 'N3',
    words: [
      { kanji: '嫌います', kana: 'きらいます', romaji: 'kiraimasu', meaning: 'ghét, không thích', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '建設', kana: 'けんせつ', romaji: 'kensetsu', meaning: 'sự xây dựng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '建築', kana: 'けんちく', romaji: 'kenchiku', meaning: 'kiến trúc, sự xây dựng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '見事', kana: 'みごと', romaji: 'migoto', meaning: 'tuyệt đẹp, xuất sắc', partOfSpeech: 'tính từ na' },
      { kanji: '見送り', kana: 'みおくり', romaji: 'miokuri', meaning: 'sự tiễn đưa', partOfSpeech: 'danh từ' },
      { kanji: '見舞い', kana: 'みまい', romaji: 'mimai', meaning: 'sự thăm hỏi (khi ốm đau)', partOfSpeech: 'danh từ' },
      { kanji: '原', kana: 'はら', romaji: 'hara', meaning: 'cánh đồng, đồng cỏ', partOfSpeech: 'danh từ' },
      { kanji: '現します', kana: 'あらわします', romaji: 'arawashimasu', meaning: 'biểu hiện, thể hiện', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '現れ', kana: 'あらわれ', romaji: 'araware', meaning: 'sự biểu hiện, hiện thân', partOfSpeech: 'danh từ' },
      { kanji: '現れます', kana: 'あらわれます', romaji: 'arawaremasu', meaning: 'xuất hiện, hiện ra', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '現場', kana: 'げんば', romaji: 'genba', meaning: 'hiện trường', partOfSpeech: 'danh từ' },
      { kanji: '現代', kana: 'げんだい', romaji: 'gendai', meaning: 'thời hiện đại, ngày nay', partOfSpeech: 'danh từ' },
      { kanji: '言う', kana: 'ゆう', romaji: 'yū', meaning: 'nói (cách đọc thông tục của 言う)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '言わば', kana: 'いわば', romaji: 'iwaba', meaning: 'có thể nói là, tức là', partOfSpeech: 'phó từ' },
      { kanji: '言語', kana: 'げんご', romaji: 'gengo', meaning: 'ngôn ngữ', partOfSpeech: 'danh từ' },
      { kanji: '個人', kana: 'こじん', romaji: 'kojin', meaning: 'cá nhân', partOfSpeech: 'danh từ' },
      { kanji: '呼吸', kana: 'こきゅう', romaji: 'kokyū', meaning: 'hơi thở, sự hô hấp', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 319,
    jlptLevel: 'N3',
    words: [
      { kanji: '故郷', kana: 'こきょう', romaji: 'kokyō', meaning: 'quê hương', partOfSpeech: 'danh từ' },
      { kanji: '虎', kana: 'とら', romaji: 'tora', meaning: 'con hổ', partOfSpeech: 'danh từ' },
      { kanji: '雇います', kana: 'やといます', romaji: 'yatoimasu', meaning: 'thuê, tuyển dụng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '互い', kana: 'たがい', romaji: 'tagai', meaning: 'lẫn nhau, qua lại', partOfSpeech: 'danh từ' },
      { kanji: '後者', kana: 'こうしゃ', romaji: 'kōsha', meaning: 'cái sau, người sau (trong hai đối tượng)', partOfSpeech: 'danh từ' },
      { kanji: '語ります', kana: 'かたります', romaji: 'katarimasu', meaning: 'kể chuyện, thuật lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '語学', kana: 'ごがく', romaji: 'gogaku', meaning: 'ngôn ngữ học, việc học ngoại ngữ', partOfSpeech: 'danh từ' },
      { kanji: '誤り', kana: 'あやまり', romaji: 'ayamari', meaning: 'sai lầm, lỗi', partOfSpeech: 'danh từ' },
      { kanji: '交際', kana: 'こうさい', romaji: 'kōsai', meaning: 'sự giao thiệp, quan hệ qua lại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '候補', kana: 'こうほ', romaji: 'kōho', meaning: 'ứng cử viên', partOfSpeech: 'danh từ' },
    ],
  },
];
