// Bổ sung từ vựng N2 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 730-735.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N2_PART6: JlptVocabUnit[] = [
  {
    lessonNumber: 730,
    jlptLevel: 'N2',
    words: [
      { kanji: '見慣れます', kana: 'みなれます', romaji: 'minaremasu', meaning: 'quen mắt, quen nhìn thấy', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '見出し', kana: 'みだし', romaji: 'midashi', meaning: 'tiêu đề, mục lục', partOfSpeech: 'danh từ' },
      { kanji: '見送ります', kana: 'みおくります', romaji: 'miokurimasu', meaning: 'tiễn đưa, để trôi qua', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '見直します', kana: 'みなおします', romaji: 'minaoshimasu', meaning: 'xem lại, đánh giá lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '見舞います', kana: 'みまいます', romaji: 'mimaimasu', meaning: 'thăm hỏi (người ốm)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '見本', kana: 'みほん', romaji: 'mihon', meaning: 'hàng mẫu', partOfSpeech: 'danh từ' },
      { kanji: '謙遜', kana: 'けんそん', romaji: 'kenson', meaning: 'sự khiêm tốn', partOfSpeech: 'danh từ, tính từ na, động từ する' },
      { kanji: '険しい', kana: 'けわしい', romaji: 'kewashii', meaning: 'hiểm trở, dữ tợn (ánh mắt)', partOfSpeech: 'tính từ i' },
      { kanji: '顕微鏡', kana: 'けんびきょう', romaji: 'kenbikyō', meaning: 'kính hiển vi', partOfSpeech: 'danh từ' },
      { kanji: '原稿', kana: 'げんこう', romaji: 'genkō', meaning: 'bản thảo', partOfSpeech: 'danh từ' },
      { kanji: '原産', kana: 'げんさん', romaji: 'gensan', meaning: 'nguyên sản, nơi xuất xứ', partOfSpeech: 'danh từ' },
      { kanji: '原始', kana: 'げんし', romaji: 'genshi', meaning: 'nguyên thủy', partOfSpeech: 'danh từ' },
      { kanji: '原理', kana: 'げんり', romaji: 'genri', meaning: 'nguyên lý', partOfSpeech: 'danh từ' },
      { kanji: '厳重', kana: 'げんじゅう', romaji: 'genjū', meaning: 'nghiêm ngặt', partOfSpeech: 'tính từ na' },
      { kanji: '現に', kana: 'げんに', romaji: 'genni', meaning: 'thực tế là, quả thực', partOfSpeech: 'phó từ' },
      { kanji: '言い出します', kana: 'いいだします', romaji: 'iidashimasu', meaning: 'bắt đầu nói ra, đề xuất', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '言い付けます', kana: 'いいつけます', romaji: 'iitsukemasu', meaning: 'ra lệnh, mách lẻo', partOfSpeech: 'động từ nhóm 2' },
    ],
  },
  {
    lessonNumber: 731,
    jlptLevel: 'N2',
    words: [
      { kanji: '言付けます', kana: 'ことづけます', romaji: 'kotozukemasu', meaning: 'nhắn lại, gửi lời nhắn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '言葉遣い', kana: 'ことばづかい', romaji: 'kotobazukai', meaning: 'cách dùng từ, cách nói năng', partOfSpeech: 'danh từ' },
      { kanji: '個所', kana: 'かしょ', romaji: 'kasho', meaning: 'chỗ, đoạn, vị trí', partOfSpeech: 'danh từ' },
      { kanji: '個体', kana: 'こたい', romaji: 'kotai', meaning: 'cá thể', partOfSpeech: 'danh từ' },
      { kanji: '古典', kana: 'こてん', romaji: 'koten', meaning: 'tác phẩm cổ điển', partOfSpeech: 'danh từ' },
      { kanji: '呼び掛けます', kana: 'よびかけます', romaji: 'yobikakemasu', meaning: 'kêu gọi, lên tiếng gọi', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '呼び出します', kana: 'よびだします', romaji: 'yobidashimasu', meaning: 'gọi ra, triệu tập', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '固まります', kana: 'かたまります', romaji: 'katamarimasu', meaning: 'đông cứng lại, trở nên chắc chắn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '戸棚', kana: 'とだな', romaji: 'todana', meaning: 'tủ đựng đồ', partOfSpeech: 'danh từ' },
      { kanji: '糊', kana: 'のり', romaji: 'nori', meaning: 'hồ dán', partOfSpeech: 'danh từ' },
      { kanji: '五十音', kana: 'ごじゅうおん', romaji: 'gojūon', meaning: 'bảng 50 âm (bảng chữ cái Nhật)', partOfSpeech: 'danh từ' },
      { kanji: '娯楽', kana: 'ごらく', romaji: 'goraku', meaning: 'sự giải trí', partOfSpeech: 'danh từ' },
      { kanji: '御辞儀', kana: 'おじぎ', romaji: 'ojigi', meaning: 'cái cúi chào', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '御中', kana: 'おんちゅう', romaji: 'onchū', meaning: 'kính gửi (công ty, tổ chức)', partOfSpeech: 'danh từ' },
      { kanji: '御無沙汰', kana: 'ごぶさた', romaji: 'gobusata', meaning: 'sự lâu ngày không liên lạc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '御免', kana: 'ごめん', romaji: 'gomen', meaning: 'xin lỗi, xin phép từ chối', partOfSpeech: 'danh từ' },
      { kanji: '御覧', kana: 'ごらん', romaji: 'goran', meaning: 'xin mời xem (kính ngữ)', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 732,
    jlptLevel: 'N2',
    words: [
      { kanji: '交ざります', kana: 'まざります', romaji: 'mazarimasu', meaning: 'bị trộn lẫn, hòa lẫn với', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '交じります', kana: 'まじります', romaji: 'majirimasu', meaning: 'lẫn vào, hòa lẫn với', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '交差', kana: 'こうさ', romaji: 'kōsa', meaning: 'sự giao nhau, chéo nhau', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '交替', kana: 'こうたい', romaji: 'kōtai', meaning: 'sự thay phiên, luân phiên', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '光線', kana: 'こうせん', romaji: 'kōsen', meaning: 'tia sáng', partOfSpeech: 'danh từ' },
      { kanji: '公式', kana: 'こうしき', romaji: 'kōshiki', meaning: 'công thức; chính thức', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '公衆', kana: 'こうしゅう', romaji: 'kōshū', meaning: 'công chúng', partOfSpeech: 'danh từ' },
      { kanji: '公表', kana: 'こうひょう', romaji: 'kōhyō', meaning: 'sự công bố', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '公務', kana: 'こうむ', romaji: 'kōmu', meaning: 'công vụ, việc công', partOfSpeech: 'danh từ' },
      { kanji: '功績', kana: 'こうせき', romaji: 'kōseki', meaning: 'công lao, thành tích', partOfSpeech: 'danh từ' },
      { kanji: '効力', kana: 'こうりょく', romaji: 'kōryoku', meaning: 'hiệu lực, tác dụng', partOfSpeech: 'danh từ' },
      { kanji: '厚かましい', kana: 'あつかましい', romaji: 'atsukamashii', meaning: 'trơ trẽn, mặt dày', partOfSpeech: 'tính từ i' },
      { kanji: '口紅', kana: 'くちべに', romaji: 'kuchibeni', meaning: 'son môi', partOfSpeech: 'danh từ' },
      { kanji: '口実', kana: 'こうじつ', romaji: 'kōjitsu', meaning: 'cái cớ, lý do biện minh', partOfSpeech: 'danh từ' },
      { kanji: '好き嫌い', kana: 'すききらい', romaji: 'sukikirai', meaning: 'sự thích và ghét, kén chọn', partOfSpeech: 'danh từ' },
      { kanji: '好き好き', kana: 'すきずき', romaji: 'sukizuki', meaning: 'tùy sở thích mỗi người', partOfSpeech: 'danh từ' },
      { kanji: '工員', kana: 'こういん', romaji: 'kōin', meaning: 'công nhân nhà máy', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 733,
    jlptLevel: 'N2',
    words: [
      { kanji: '工芸', kana: 'こうげい', romaji: 'kōgei', meaning: 'thủ công mỹ nghệ', partOfSpeech: 'danh từ' },
      { kanji: '工事', kana: 'こうじ', romaji: 'kōji', meaning: 'công trình xây dựng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '広々', kana: 'ひろびろ', romaji: 'hirobiro', meaning: 'rộng rãi, thoáng đãng', partOfSpeech: 'phó từ' },
      { kanji: '広げます', kana: 'ひろげます', romaji: 'hirogemasu', meaning: 'mở rộng, trải rộng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '広さ', kana: 'ひろさ', romaji: 'hirosa', meaning: 'độ rộng, diện tích', partOfSpeech: 'danh từ' },
      { kanji: '広場', kana: 'ひろば', romaji: 'hiroba', meaning: 'quảng trường', partOfSpeech: 'danh từ' },
      { kanji: '更けます', kana: 'ふけます', romaji: 'fukemasu', meaning: 'về khuya, càng lúc càng muộn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '紅葉', kana: 'こうよう', romaji: 'kōyō', meaning: 'lá đỏ mùa thu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '絞ります', kana: 'しぼります', romaji: 'shiborimasu', meaning: 'vắt, siết chặt', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '綱', kana: 'つな', romaji: 'tsuna', meaning: 'dây thừng lớn', partOfSpeech: 'danh từ' },
      { kanji: '耕します', kana: 'たがやします', romaji: 'tagayashimasu', meaning: 'cày cấy, canh tác', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '耕地', kana: 'こうち', romaji: 'kōchi', meaning: 'đất canh tác', partOfSpeech: 'danh từ' },
      { kanji: '荒い', kana: 'あらい', romaji: 'arai', meaning: 'thô bạo, dữ dội', partOfSpeech: 'tính từ i' },
      { kanji: '行列', kana: 'ぎょうれつ', romaji: 'gyōretsu', meaning: 'hàng dài người xếp hàng; ma trận (toán)', partOfSpeech: 'danh từ' },
      { kanji: '鉱物', kana: 'こうぶつ', romaji: 'kōbutsu', meaning: 'khoáng vật', partOfSpeech: 'danh từ' },
      { kanji: '項目', kana: 'こうもく', romaji: 'kōmoku', meaning: 'mục, khoản', partOfSpeech: 'danh từ' },
      { kanji: '香水', kana: 'こうすい', romaji: 'kōsui', meaning: 'nước hoa', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 734,
    jlptLevel: 'N2',
    words: [
      { kanji: '高めます', kana: 'たかめます', romaji: 'takamemasu', meaning: 'nâng cao, tăng cường', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '高層', kana: 'こうそう', romaji: 'kōsō', meaning: 'cao tầng', partOfSpeech: 'danh từ' },
      { kanji: '高度', kana: 'こうど', romaji: 'kōdo', meaning: 'độ cao; trình độ cao', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '高等', kana: 'こうとう', romaji: 'kōtō', meaning: 'cao cấp, trình độ cao', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '合同', kana: 'ごうどう', romaji: 'gōdō', meaning: 'sự kết hợp, liên kết', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '合理', kana: 'ごうり', romaji: 'gōri', meaning: 'hợp lý', partOfSpeech: 'danh từ' },
      { kanji: '合流', kana: 'ごうりゅう', romaji: 'gōryū', meaning: 'sự hợp lưu, nhập lại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '刻みます', kana: 'きざみます', romaji: 'kizamimasu', meaning: 'băm nhỏ, khắc lên', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '国王', kana: 'こくおう', romaji: 'kokuō', meaning: 'quốc vương', partOfSpeech: 'danh từ' },
      { kanji: '国籍', kana: 'こくせき', romaji: 'kokuseki', meaning: 'quốc tịch', partOfSpeech: 'danh từ' },
      { kanji: '国立', kana: 'こくりつ', romaji: 'kokuritsu', meaning: 'thuộc nhà nước, quốc lập', partOfSpeech: 'danh từ' },
      { kanji: '腰掛け', kana: 'こしかけ', romaji: 'koshikake', meaning: 'ghế ngồi', partOfSpeech: 'danh từ' },
      { kanji: '腰掛けます', kana: 'こしかけます', romaji: 'koshikakemasu', meaning: 'ngồi xuống', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '恨み', kana: 'うらみ', romaji: 'urami', meaning: 'sự oán hận', partOfSpeech: 'danh từ' },
      { kanji: '恨みます', kana: 'うらみます', romaji: 'uramimasu', meaning: 'oán hận, oán trách', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '差し引き', kana: 'さしひき', romaji: 'sashihiki', meaning: 'sự trừ đi, số dư', partOfSpeech: 'danh từ' },
      { kanji: '差し支え', kana: 'さしつかえ', romaji: 'sashitsukae', meaning: 'sự trở ngại, bất tiện', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 735,
    jlptLevel: 'N2',
    words: [
      { kanji: '座布団', kana: 'ざぶとん', romaji: 'zabuton', meaning: 'đệm ngồi kiểu Nhật', partOfSpeech: 'danh từ' },
      { kanji: '座敷', kana: 'ざしき', romaji: 'zashiki', meaning: 'phòng chiếu tatami', partOfSpeech: 'danh từ' },
      { kanji: '催し', kana: 'もよおし', romaji: 'moyōshi', meaning: 'sự kiện, buổi lễ', partOfSpeech: 'danh từ' },
      { kanji: '催促', kana: 'さいそく', romaji: 'saisoku', meaning: 'sự thúc giục, giục giã', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '再三', kana: 'さいさん', romaji: 'saisan', meaning: 'nhiều lần, lặp đi lặp lại', partOfSpeech: 'phó từ' },
      { kanji: '塞がります', kana: 'ふさがります', romaji: 'fusagarimasu', meaning: 'bị bịt kín, bị chiếm hết', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '塞ぎます', kana: 'ふさぎます', romaji: 'fusagimasu', meaning: 'bịt kín, lấp lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '採点', kana: 'さいてん', romaji: 'saiten', meaning: 'sự chấm điểm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '災難', kana: 'さいなん', romaji: 'sainan', meaning: 'tai họa, tai ương', partOfSpeech: 'danh từ' },
      { kanji: '砕きます', kana: 'くだきます', romaji: 'kudakimasu', meaning: 'đập vỡ, nghiền nát', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '砕けます', kana: 'くだけます', romaji: 'kudakemasu', meaning: 'bị vỡ vụn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '祭ります', kana: 'まつります', romaji: 'matsurimasu', meaning: 'thờ cúng, tôn thờ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '祭日', kana: 'さいじつ', romaji: 'saijitsu', meaning: 'ngày lễ quốc gia', partOfSpeech: 'danh từ' },
      { kanji: '裁縫', kana: 'さいほう', romaji: 'saihō', meaning: 'may vá', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '在学', kana: 'ざいがく', romaji: 'zaigaku', meaning: 'đang theo học (ở trường)', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
];
