// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 971-976.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART13: JlptVocabUnit[] = [
  {
    lessonNumber: 971,
    jlptLevel: 'N1',
    words: [
      { kanji: '上演', kana: 'じょうえん', romaji: 'jōen', meaning: 'sự công diễn (kịch, phim)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '上下', kana: 'うえした', romaji: 'ueshita', meaning: 'trên dưới, đảo lộn', partOfSpeech: 'danh từ' },
      { kanji: '上回ります', kana: 'うわまわります', romaji: 'uwamawarimasu', meaning: 'vượt quá, vượt trội', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '上空', kana: 'じょうくう', romaji: 'jōkū', meaning: 'bầu trời phía trên, trên không', partOfSpeech: 'danh từ' },
      { kanji: '上手', kana: 'うわて', romaji: 'uwate', meaning: 'phần trên, phía thượng nguồn; khéo léo hơn', partOfSpeech: 'danh từ' },
      { kanji: '上昇', kana: 'じょうしょう', romaji: 'jōshō', meaning: 'sự tăng lên, bay lên', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '上陸', kana: 'じょうりく', romaji: 'jōriku', meaning: 'sự đổ bộ lên bờ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '丈', kana: 'たけ', romaji: 'take', meaning: 'chiều cao, chiều dài', partOfSpeech: 'danh từ' },
      { kanji: '丈夫', kana: 'じょうふ', romaji: 'jōfu', meaning: 'trang nam nhi, người mạnh khỏe', partOfSpeech: 'danh từ' },
      { kanji: '乗っ取ります', kana: 'のっとります', romaji: 'nottorimasu', meaning: 'chiếm đoạt, cướp quyền kiểm soát', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '乗り込みます', kana: 'のりこみます', romaji: 'norikomimasu', meaning: 'lên xe/tàu, tiến vào', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '城下', kana: 'じょうか', romaji: 'jōka', meaning: 'vùng đất quanh lâu đài', partOfSpeech: 'danh từ' },
      { kanji: '情け', kana: 'なさけ', romaji: 'nasake', meaning: 'lòng trắc ẩn, sự thương cảm', partOfSpeech: 'danh từ' },
      { kanji: '情け深い', kana: 'なさけぶかい', romaji: 'nasakebukai', meaning: 'nhân hậu, giàu lòng trắc ẩn', partOfSpeech: 'tính từ i' },
      { kanji: '情緒', kana: 'じょうしょ', romaji: 'jōsho', meaning: 'cảm xúc, tình cảm', partOfSpeech: 'danh từ' },
      { kanji: '情勢', kana: 'じょうせい', romaji: 'jōsei', meaning: 'tình hình, cục diện', partOfSpeech: 'danh từ' },
      { kanji: '情熱', kana: 'じょうねつ', romaji: 'jōnetsu', meaning: 'nhiệt huyết, đam mê', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 972,
    jlptLevel: 'N1',
    words: [
      { kanji: '条約', kana: 'じょうやく', romaji: 'jōyaku', meaning: 'hiệp ước', partOfSpeech: 'danh từ' },
      { kanji: '杖', kana: 'つえ', romaji: 'tsue', meaning: 'cây gậy chống', partOfSpeech: 'danh từ' },
      { kanji: '蒸留', kana: 'じょうりゅう', romaji: 'jōryū', meaning: 'sự chưng cất', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '植わります', kana: 'うわります', romaji: 'uwarimasu', meaning: 'được trồng (cây)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '植民地', kana: 'しょくみんち', romaji: 'shokuminchi', meaning: 'thuộc địa', partOfSpeech: 'danh từ' },
      { kanji: '織', kana: 'おり', romaji: 'ori', meaning: 'sự dệt, hàng dệt', partOfSpeech: 'danh từ' },
      { kanji: '織物', kana: 'おりもの', romaji: 'orimono', meaning: 'vải dệt', partOfSpeech: 'danh từ' },
      { kanji: '職員', kana: 'しょくいん', romaji: 'shokuin', meaning: 'nhân viên (cơ quan)', partOfSpeech: 'danh từ' },
      { kanji: '職務', kana: 'しょくむ', romaji: 'shokumu', meaning: 'nhiệm vụ công việc', partOfSpeech: 'danh từ' },
      { kanji: '色彩', kana: 'しきさい', romaji: 'shikisai', meaning: 'sắc màu, màu sắc', partOfSpeech: 'danh từ' },
      { kanji: '食い違います', kana: 'くいちがいます', romaji: 'kuichigaimasu', meaning: 'không khớp nhau, mâu thuẫn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '信者', kana: 'しんじゃ', romaji: 'shinja', meaning: 'tín đồ', partOfSpeech: 'danh từ' },
      { kanji: '信任', kana: 'しんにん', romaji: 'shinnin', meaning: 'sự tín nhiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '侵します', kana: 'おかします', romaji: 'okashimasu', meaning: 'xâm phạm, xâm lược', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '侵略', kana: 'しんりゃく', romaji: 'shinryaku', meaning: 'sự xâm lược', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '寝かせます', kana: 'ねかせます', romaji: 'nekasemasu', meaning: 'cho nằm xuống, ủ men', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '審議', kana: 'しんぎ', romaji: 'shingi', meaning: 'sự thẩm nghị, bàn bạc', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 973,
    jlptLevel: 'N1',
    words: [
      { kanji: '審査', kana: 'しんさ', romaji: 'shinsa', meaning: 'sự thẩm định, xét duyệt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '心掛け', kana: 'こころがけ', romaji: 'kokorogake', meaning: 'sự lưu tâm, chủ tâm', partOfSpeech: 'danh từ' },
      { kanji: '心掛けます', kana: 'こころがけます', romaji: 'kokorogakemasu', meaning: 'luôn lưu tâm, cố gắng làm', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '心強い', kana: 'こころづよい', romaji: 'kokorozuyoi', meaning: 'yên tâm, vững lòng', partOfSpeech: 'tính từ i' },
      { kanji: '心細い', kana: 'こころぼそい', romaji: 'kokorobosoi', meaning: 'lo lắng, bất an', partOfSpeech: 'tính từ i' },
      { kanji: '心地', kana: 'ここち', romaji: 'kokochi', meaning: 'cảm giác, tâm trạng', partOfSpeech: 'danh từ' },
      { kanji: '心中', kana: 'しんじゅう', romaji: 'shinjū', meaning: 'vụ tự sát tập thể (vì tình)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '心得', kana: 'こころえ', romaji: 'kokoroe', meaning: 'sự hiểu biết, kinh nghiệm', partOfSpeech: 'danh từ' },
      { kanji: '慎みます', kana: 'つつしみます', romaji: 'tsutsushimimasu', meaning: 'thận trọng, kiềm chế', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '振り出し', kana: 'ふりだし', romaji: 'furidashi', meaning: 'điểm khởi đầu', partOfSpeech: 'danh từ' },
      { kanji: '振動', kana: 'しんどう', romaji: 'shindō', meaning: 'sự rung động', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '新婚', kana: 'しんこん', romaji: 'shinkon', meaning: 'mới cưới', partOfSpeech: 'danh từ' },
      { kanji: '新人', kana: 'しんじん', romaji: 'shinjin', meaning: 'người mới, tân binh', partOfSpeech: 'danh từ' },
      { kanji: '新築', kana: 'しんちく', romaji: 'shinchiku', meaning: 'nhà mới xây', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '新入生', kana: 'しんにゅうせい', romaji: 'shinnyūsei', meaning: 'học sinh mới, tân sinh viên', partOfSpeech: 'danh từ' },
      { kanji: '深めます', kana: 'ふかめます', romaji: 'fukamemasu', meaning: 'làm sâu sắc thêm', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '申し出ます', kana: 'もうしでます', romaji: 'mōshidemasu', meaning: 'đề xuất, trình bày (nguyện vọng)', partOfSpeech: 'động từ nhóm 2' },
    ],
  },
  {
    lessonNumber: 974,
    jlptLevel: 'N1',
    words: [
      { kanji: '申し入れます', kana: 'もうしいれます', romaji: 'mōshiiremasu', meaning: 'đề nghị, đưa ra yêu cầu', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '申し分', kana: 'もうしぶん', romaji: 'mōshibun', meaning: 'điểm chê trách, thiếu sót', partOfSpeech: 'danh từ' },
      { kanji: '申出', kana: 'もうしで', romaji: 'mōshide', meaning: 'lời đề nghị, yêu cầu', partOfSpeech: 'danh từ' },
      { kanji: '真っ二つ', kana: 'まっぷたつ', romaji: 'mapputatsu', meaning: 'chia đôi bằng nhau', partOfSpeech: 'danh từ' },
      { kanji: '真に', kana: 'まことに', romaji: 'makotoni', meaning: 'thực sự, quả thật', partOfSpeech: 'phó từ' },
      { kanji: '真ん丸い', kana: 'まんまるい', romaji: 'manmarui', meaning: 'tròn xoe', partOfSpeech: 'tính từ i' },
      { kanji: '真ん前', kana: 'まんまえ', romaji: 'manmae', meaning: 'ngay trước mặt', partOfSpeech: 'danh từ' },
      { kanji: '真下', kana: 'ました', romaji: 'mashita', meaning: 'ngay bên dưới', partOfSpeech: 'danh từ' },
      { kanji: '真珠', kana: 'しんじゅ', romaji: 'shinju', meaning: 'ngọc trai', partOfSpeech: 'danh từ' },
      { kanji: '真上', kana: 'まうえ', romaji: 'maue', meaning: 'ngay phía trên', partOfSpeech: 'danh từ' },
      { kanji: '真心', kana: 'まこころ', romaji: 'makokoro', meaning: 'tấm lòng chân thành', partOfSpeech: 'danh từ' },
      { kanji: '真相', kana: 'しんそう', romaji: 'shinsō', meaning: 'sự thật, chân tướng', partOfSpeech: 'danh từ' },
      { kanji: '神殿', kana: 'しんでん', romaji: 'shinden', meaning: 'đền thờ, thánh điện', partOfSpeech: 'danh từ' },
      { kanji: '神秘', kana: 'しんぴ', romaji: 'shinpi', meaning: 'sự huyền bí', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '紳士', kana: 'しんし', romaji: 'shinshi', meaning: 'quý ông, người lịch lãm', partOfSpeech: 'danh từ' },
      { kanji: '親しみます', kana: 'したしみます', romaji: 'shitashimimasu', meaning: 'trở nên thân thiết', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '親善', kana: 'しんぜん', romaji: 'shinzen', meaning: 'tình hữu nghị', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 975,
    jlptLevel: 'N1',
    words: [
      { kanji: '診療', kana: 'しんりょう', romaji: 'shinryō', meaning: 'sự khám và điều trị', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '身なり', kana: 'みなり', romaji: 'minari', meaning: 'diện mạo, cách ăn mặc', partOfSpeech: 'danh từ' },
      { kanji: '身近', kana: 'みぢか', romaji: 'mijika', meaning: 'gần gũi, quen thuộc', partOfSpeech: 'tính từ na' },
      { kanji: '身振り', kana: 'みぶり', romaji: 'miburi', meaning: 'cử chỉ, điệu bộ', partOfSpeech: 'danh từ' },
      { kanji: '辛うじて', kana: 'かろうじて', romaji: 'karōjite', meaning: 'chật vật lắm mới, suýt nữa thì không', partOfSpeech: 'phó từ' },
      { kanji: '辛抱', kana: 'しんぼう', romaji: 'shinbō', meaning: 'sự kiên nhẫn, chịu đựng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '進み', kana: 'すすみ', romaji: 'susumi', meaning: 'sự tiến triển', partOfSpeech: 'danh từ' },
      { kanji: '進出', kana: 'しんしゅつ', romaji: 'shinshutsu', meaning: 'sự tiến vào, mở rộng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '進呈', kana: 'しんてい', romaji: 'shintei', meaning: 'sự tặng, biếu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '進展', kana: 'しんてん', romaji: 'shinten', meaning: 'sự tiến triển', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '進度', kana: 'しんど', romaji: 'shindo', meaning: 'tiến độ', partOfSpeech: 'danh từ' },
      { kanji: '震わせます', kana: 'ふるわせます', romaji: 'furuwasemasu', meaning: 'làm rung động, làm run rẩy', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '人', kana: 'じん', romaji: 'jin', meaning: 'người (hậu tố chỉ người)', partOfSpeech: 'hậu tố' },
      { kanji: '人格', kana: 'じんかく', romaji: 'jinkaku', meaning: 'nhân cách', partOfSpeech: 'danh từ' },
      { kanji: '人質', kana: 'ひとじち', romaji: 'hitojichi', meaning: 'con tin', partOfSpeech: 'danh từ' },
      { kanji: '人情', kana: 'にんじょう', romaji: 'ninjō', meaning: 'tình người', partOfSpeech: 'danh từ' },
      { kanji: '人体', kana: 'じんたい', romaji: 'jintai', meaning: 'cơ thể người', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 976,
    jlptLevel: 'N1',
    words: [
      { kanji: '人柄', kana: 'ひとがら', romaji: 'hitogara', meaning: 'tính cách, nhân phẩm', partOfSpeech: 'danh từ' },
      { kanji: '人民', kana: 'じんみん', romaji: 'jinmin', meaning: 'nhân dân', partOfSpeech: 'danh từ' },
      { kanji: '人目', kana: 'じんもく', romaji: 'jinmoku', meaning: 'sự để ý của người khác', partOfSpeech: 'danh từ' },
      { kanji: '塵取り', kana: 'ちりとり', romaji: 'chiritori', meaning: 'cái hót rác', partOfSpeech: 'danh từ' },
      { kanji: '甚だ', kana: 'はなはだ', romaji: 'hanahada', meaning: 'hết sức, vô cùng', partOfSpeech: 'phó từ' },
      { kanji: '尽くします', kana: 'つくします', romaji: 'tsukushimasu', meaning: 'cống hiến, hết lòng vì', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '迅速', kana: 'じんそく', romaji: 'jinsoku', meaning: 'nhanh chóng, mau lẹ', partOfSpeech: 'tính từ na' },
      { kanji: '吹奏', kana: 'すいそう', romaji: 'suisō', meaning: 'sự thổi kèn (nhạc cụ hơi)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '垂れます', kana: 'たれます', romaji: 'taremasu', meaning: 'rủ xuống, nhỏ giọt', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '推理', kana: 'すいり', romaji: 'suiri', meaning: 'sự suy luận, suy lý', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '水気', kana: 'すいき', romaji: 'suiki', meaning: 'hơi ẩm, độ ẩm', partOfSpeech: 'danh từ' },
      { kanji: '水源', kana: 'すいげん', romaji: 'suigen', meaning: 'nguồn nước, đầu nguồn', partOfSpeech: 'danh từ' },
    ],
  },
];
