// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 941-946.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART8: JlptVocabUnit[] = [
  {
    lessonNumber: 941,
    jlptLevel: 'N1',
    words: [
      { kanji: '傾ける', kana: 'かたむける', romaji: 'katamukeru', meaning: 'làm nghiêng, dồn hết (tâm sức)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '刑罰', kana: 'けいばつ', romaji: 'keibatsu', meaning: 'hình phạt', partOfSpeech: 'danh từ' },
      { kanji: '形勢', kana: 'けいせい', romaji: 'keisei', meaning: 'tình thế, cục diện', partOfSpeech: 'danh từ' },
      { kanji: '形態', kana: 'けいたい', romaji: 'keitai', meaning: 'hình thái, hình dạng', partOfSpeech: 'danh từ' },
      { kanji: '恵み', kana: 'めぐみ', romaji: 'megumi', meaning: 'ân huệ, phước lành', partOfSpeech: 'danh từ' },
      { kanji: '恵みます', kana: 'めぐみます', romaji: 'megumimasu', meaning: 'ban phước, ban ơn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '掲げます', kana: 'かかげます', romaji: 'kakagemasu', meaning: 'treo lên, đăng tải (bài báo)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '携わります', kana: 'たずさわります', romaji: 'tazusawarimasu', meaning: 'tham gia, đảm nhận (công việc)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '経緯', kana: 'いきさつ', romaji: 'ikisatsu', meaning: 'diễn biến sự việc, đầu đuôi câu chuyện', partOfSpeech: 'danh từ' },
      { kanji: '経過', kana: 'けいか', romaji: 'keika', meaning: 'quá trình, sự trôi qua', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '経路', kana: 'けいろ', romaji: 'keiro', meaning: 'lộ trình, con đường đi', partOfSpeech: 'danh từ' },
      { kanji: '継ぎ目', kana: 'つぎめ', romaji: 'tsugime', meaning: 'chỗ nối, mối nối', partOfSpeech: 'danh từ' },
      { kanji: '茎', kana: 'くき', romaji: 'kuki', meaning: 'thân cây, cuống', partOfSpeech: 'danh từ' },
      { kanji: '警戒', kana: 'けいかい', romaji: 'keikai', meaning: 'sự cảnh giác, đề phòng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '警部', kana: 'けいぶ', romaji: 'keibu', meaning: 'cảnh sát trưởng khu vực', partOfSpeech: 'danh từ' },
      { kanji: '軽減', kana: 'けいげん', romaji: 'keigen', meaning: 'sự giảm nhẹ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '軽蔑', kana: 'けいべつ', romaji: 'keibetsu', meaning: 'sự khinh miệt', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 942,
    jlptLevel: 'N1',
    words: [
      { kanji: '軽率', kana: 'けいそつ', romaji: 'keisotsu', meaning: 'khinh suất, hấp tấp', partOfSpeech: 'tính từ na' },
      { kanji: '劇団', kana: 'げきだん', romaji: 'gekidan', meaning: 'đoàn kịch', partOfSpeech: 'danh từ' },
      { kanji: '決まり悪い', kana: 'きまりわるい', romaji: 'kimariwarui', meaning: 'ngượng ngùng, xấu hổ', partOfSpeech: 'tính từ i' },
      { kanji: '決議', kana: 'けつぎ', romaji: 'ketsugi', meaning: 'nghị quyết', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '決算', kana: 'けっさん', romaji: 'kessan', meaning: 'quyết toán, bảng cân đối', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '決勝', kana: 'けっしょう', romaji: 'kesshō', meaning: 'trận chung kết', partOfSpeech: 'danh từ' },
      { kanji: '決断', kana: 'けつだん', romaji: 'ketsudan', meaning: 'sự quyết đoán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '結び', kana: 'むすび', romaji: 'musubi', meaning: 'phần kết, sự kết thúc', partOfSpeech: 'danh từ' },
      { kanji: '結び付き', kana: 'むすびつき', romaji: 'musubitsuki', meaning: 'mối liên kết', partOfSpeech: 'danh từ' },
      { kanji: '結び付きます', kana: 'むすびつきます', romaji: 'musubitsukimasu', meaning: 'gắn kết với nhau', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '結び付けます', kana: 'むすびつけます', romaji: 'musubitsukemasu', meaning: 'kết nối, gắn liền', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '結核', kana: 'けっかく', romaji: 'kekkaku', meaning: 'bệnh lao', partOfSpeech: 'danh từ' },
      { kanji: '結合', kana: 'けつごう', romaji: 'ketsugō', meaning: 'sự kết hợp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '結成', kana: 'けっせい', romaji: 'kessei', meaning: 'sự thành lập, tổ chức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '月謝', kana: 'げっしゃ', romaji: 'gessha', meaning: 'học phí hàng tháng', partOfSpeech: 'danh từ' },
      { kanji: '月日', kana: 'がっぴ', romaji: 'gappi', meaning: 'ngày tháng (ghi trên giấy tờ)', partOfSpeech: 'danh từ' },
      { kanji: '月賦', kana: 'げっぷ', romaji: 'geppu', meaning: 'trả góp hàng tháng', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 943,
    jlptLevel: 'N1',
    words: [
      { kanji: '月並み', kana: 'つきなみ', romaji: 'tsukinami', meaning: 'tầm thường, thông thường', partOfSpeech: 'tính từ na' },
      { kanji: '件', kana: 'くだん', romaji: 'kudan', meaning: 'việc đã nói ở trên, việc thường lệ', partOfSpeech: 'danh từ' },
      { kanji: '倹約', kana: 'けんやく', romaji: 'kenyaku', meaning: 'sự tiết kiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '健やか', kana: 'すこやか', romaji: 'sukoyaka', meaning: 'khỏe mạnh, cường tráng', partOfSpeech: 'tính từ na' },
      { kanji: '健全', kana: 'けんぜん', romaji: 'kenzen', meaning: 'lành mạnh, khỏe mạnh', partOfSpeech: 'tính từ na' },
      { kanji: '兼ねて', kana: 'かねて', romaji: 'kanete', meaning: 'từ trước, đã từ lâu', partOfSpeech: 'phó từ' },
      { kanji: '兼業', kana: 'けんぎょう', romaji: 'kengyō', meaning: 'nghề tay trái, kiêm nghiệp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '兼用', kana: 'けんよう', romaji: 'kenyō', meaning: 'dùng chung cho nhiều mục đích', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '捲ります', kana: 'まくります', romaji: 'makurimasu', meaning: 'vén lên, xắn lên (tay áo)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '検事', kana: 'けんじ', romaji: 'kenji', meaning: 'công tố viên', partOfSpeech: 'danh từ' },
      { kanji: '研ぎます', kana: 'とぎます', romaji: 'togimasu', meaning: 'mài, vo (gạo)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '見すぼらしい', kana: 'みすぼらしい', romaji: 'misuborashii', meaning: 'tồi tàn, xoàng xĩnh', partOfSpeech: 'tính từ i' },
      { kanji: '見せびらかします', kana: 'みせびらかします', romaji: 'misebirakashimasu', meaning: 'phô trương, khoe khoang', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '見せ物', kana: 'みせもの', romaji: 'misemono', meaning: 'buổi trình diễn, trò triển lãm', partOfSpeech: 'danh từ' },
      { kanji: '見掛けます', kana: 'みかけます', romaji: 'mikakemasu', meaning: 'tình cờ nhìn thấy', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '見苦しい', kana: 'みぐるしい', romaji: 'migurushii', meaning: 'khó coi, xấu xí', partOfSpeech: 'tính từ i' },
      { kanji: '見合い', kana: 'みあい', romaji: 'miai', meaning: 'buổi xem mắt (hôn nhân)', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 944,
    jlptLevel: 'N1',
    words: [
      { kanji: '見合わせます', kana: 'みあわせます', romaji: 'miawasemasu', meaning: 'tạm hoãn, nhìn nhau', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '見込み', kana: 'みこみ', romaji: 'mikomi', meaning: 'triển vọng, dự kiến', partOfSpeech: 'danh từ' },
      { kanji: '見晴らし', kana: 'みはらし', romaji: 'miharashi', meaning: 'tầm nhìn, quang cảnh', partOfSpeech: 'danh từ' },
      { kanji: '見地', kana: 'けんち', romaji: 'kenchi', meaning: 'quan điểm, góc nhìn', partOfSpeech: 'danh từ' },
      { kanji: '見通し', kana: 'みとおし', romaji: 'mitōshi', meaning: 'triển vọng, dự đoán', partOfSpeech: 'danh từ' },
      { kanji: '見渡します', kana: 'みわたします', romaji: 'miwatashimasu', meaning: 'nhìn bao quát, phóng tầm mắt', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '見逃します', kana: 'みのがします', romaji: 'minogashimasu', meaning: 'bỏ lỡ, bỏ qua', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '見落とします', kana: 'みおとします', romaji: 'miotoshimasu', meaning: 'nhìn sót, bỏ sót', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '謙ります', kana: 'へりくだります', romaji: 'herikudarimasu', meaning: 'khiêm nhường, hạ mình', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '賢明', kana: 'けんめい', romaji: 'kenmei', meaning: 'khôn ngoan, sáng suốt', partOfSpeech: 'tính từ na' },
      { kanji: '軒並み', kana: 'のきなみ', romaji: 'nokinami', meaning: 'hàng loạt nhà cửa; đồng loạt', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '遣い', kana: 'つかい', romaji: 'tsukai', meaning: 'việc sai bảo, sứ mệnh', partOfSpeech: 'danh từ' },
      { kanji: '遣り通します', kana: 'やりとおします', romaji: 'yaritōshimasu', meaning: 'làm đến cùng, hoàn thành trọn vẹn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '元首', kana: 'げんしゅ', romaji: 'genshu', meaning: 'nguyên thủ quốc gia', partOfSpeech: 'danh từ' },
      { kanji: '元素', kana: 'げんそ', romaji: 'genso', meaning: 'nguyên tố (hóa học)', partOfSpeech: 'danh từ' },
      { kanji: '元年', kana: 'がんねん', romaji: 'gannen', meaning: 'năm đầu tiên (của một niên hiệu)', partOfSpeech: 'danh từ' },
      { kanji: '元来', kana: 'がんらい', romaji: 'ganrai', meaning: 'vốn dĩ, ban đầu', partOfSpeech: 'phó từ' },
    ],
  },
  {
    lessonNumber: 945,
    jlptLevel: 'N1',
    words: [
      { kanji: '原', kana: 'げん', romaji: 'gen', meaning: 'gốc, nguyên bản', partOfSpeech: 'danh từ' },
      { kanji: '原っぱ', kana: 'はらっぱ', romaji: 'harappa', meaning: 'bãi đất trống', partOfSpeech: 'danh từ' },
      { kanji: '原形', kana: 'げんけい', romaji: 'genkei', meaning: 'hình dạng ban đầu', partOfSpeech: 'danh từ' },
      { kanji: '原書', kana: 'げんしょ', romaji: 'gensho', meaning: 'sách nguyên bản (chưa dịch)', partOfSpeech: 'danh từ' },
      { kanji: '原典', kana: 'げんてん', romaji: 'genten', meaning: 'văn bản gốc', partOfSpeech: 'danh từ' },
      { kanji: '原爆', kana: 'げんばく', romaji: 'genbaku', meaning: 'bom nguyên tử', partOfSpeech: 'danh từ' },
      { kanji: '原文', kana: 'げんぶん', romaji: 'genbun', meaning: 'nguyên văn', partOfSpeech: 'danh từ' },
      { kanji: '原油', kana: 'げんゆ', romaji: 'genyu', meaning: 'dầu thô', partOfSpeech: 'danh từ' },
      { kanji: '厳か', kana: 'おごそか', romaji: 'ogosoka', meaning: 'trang nghiêm, uy nghi', partOfSpeech: 'tính từ na' },
      { kanji: '源', kana: 'みなもと', romaji: 'minamoto', meaning: 'nguồn gốc, cội nguồn', partOfSpeech: 'danh từ' },
      { kanji: '玄人', kana: 'くろうと', romaji: 'kurōto', meaning: 'chuyên gia, người sành nghề', partOfSpeech: 'danh từ' },
      { kanji: '現像', kana: 'げんぞう', romaji: 'genzō', meaning: 'sự tráng phim', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '現地', kana: 'げんち', romaji: 'genchi', meaning: 'tại chỗ, hiện trường', partOfSpeech: 'danh từ' },
      { kanji: '言い訳', kana: 'いいわけ', romaji: 'iiwake', meaning: 'lời bào chữa, lý do biện minh', partOfSpeech: 'danh từ' },
      { kanji: '言伝', kana: 'ことづて', romaji: 'kotozute', meaning: 'lời nhắn, tin đồn', partOfSpeech: 'danh từ' },
      { kanji: '言論', kana: 'げんろん', romaji: 'genron', meaning: 'ngôn luận', partOfSpeech: 'danh từ' },
      { kanji: '限定', kana: 'げんてい', romaji: 'gentei', meaning: 'sự giới hạn', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 946,
    jlptLevel: 'N1',
    words: [
      { kanji: '個別', kana: 'こべつ', romaji: 'kobetsu', meaning: 'riêng lẻ, cá biệt', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '古', kana: 'いにしえ', romaji: 'inishie', meaning: 'thời xưa', partOfSpeech: 'danh từ' },
      { kanji: '古代', kana: 'こだい', romaji: 'kodai', meaning: 'thời cổ đại', partOfSpeech: 'danh từ' },
      { kanji: '呼び止めます', kana: 'よびとめます', romaji: 'yobitomemasu', meaning: 'gọi lại, chặn lại', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '固めます', kana: 'かためます', romaji: 'katamemasu', meaning: 'làm cứng lại, củng cố', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '固定', kana: 'こてい', romaji: 'kotei', meaning: 'sự cố định', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '固有', kana: 'こゆう', romaji: 'koyū', meaning: 'đặc trưng riêng, vốn có', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '孤児', kana: 'こじ', romaji: 'koji', meaning: 'trẻ mồ côi', partOfSpeech: 'danh từ' },
      { kanji: '孤立', kana: 'こりつ', romaji: 'koritsu', meaning: 'sự cô lập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '戸締り', kana: 'とじまり', romaji: 'tojimari', meaning: 'sự khóa cửa cẩn thận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '誇ります', kana: 'ほこります', romaji: 'hokorimasu', meaning: 'tự hào về', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '誇張', kana: 'こちょう', romaji: 'kochō', meaning: 'sự phóng đại', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
];
