// Bổ sung kanji N2 — dịch tay (Hán Việt + nghĩa Việt) dựa trên dữ liệu đọc âm
// (onyomi/kunyomi) và stroke count lấy từ kanjiapi.dev (nguồn mở), không auto-scrape nghĩa tiếng Việt.
// KanjiLesson lessonNumber 700-708.

import type { JlptKanjiLesson } from './jlpt-kanji.data';

export const JLPT_KANJI_BOOST3_N2: JlptKanjiLesson[] = [
  {
    lessonNumber: 700,
    jlptLevel: 'N2',
    title: 'Kanji N2 bổ sung (1)',
    sortOrder: 7000,
    entries: [
      { character: '並', hanViet: 'TỊNH', onyomi: 'へい, ほう', kunyomi: 'な-み, なみ, なら-べる, なら-ぶ, なら-びに', meaningVi: 'song song, ngang hàng, và', strokeCount: 8 },
      { character: '乱', hanViet: 'LOẠN', onyomi: 'らん, ろん', kunyomi: 'みだ-れる, みだ-る, みだ-す, みだ, おさ-める, わた-る', meaningVi: 'hỗn loạn, rối loạn', strokeCount: 7 },
      { character: '乳', hanViet: 'NHŨ', onyomi: 'にゅう', kunyomi: 'ちち, ち', meaningVi: 'sữa', strokeCount: 8 },
      { character: '乾', hanViet: 'CÀN', onyomi: 'かん, けん', kunyomi: 'かわ-く, かわ-かす, ほ-す, ひ-る, いぬい', meaningVi: 'khô, khô hạn', strokeCount: 11 },
      { character: '了', hanViet: 'LIỄU', onyomi: 'りょう', meaningVi: 'hoàn thành, xong', strokeCount: 2 },
      { character: '介', hanViet: 'GIỚI', onyomi: 'かい', meaningVi: 'giới thiệu, xen vào giữa', strokeCount: 4 },
      { character: '仲', hanViet: 'TRỌNG', onyomi: 'ちゅう', kunyomi: 'なか', meaningVi: 'trung gian, quan hệ', strokeCount: 6 },
      { character: '伺', hanViet: 'TỨ', onyomi: 'し', kunyomi: 'うかが-う', meaningVi: 'hỏi thăm, viếng thăm (khiêm nhường)', strokeCount: 7 },
      { character: '像', hanViet: 'TƯỢNG', onyomi: 'ぞう', meaningVi: 'bức tượng, hình ảnh', strokeCount: 14 },
      { character: '児', hanViet: 'NHI', onyomi: 'じ, に, げい', kunyomi: 'こ, -こ, -っこ', meaningVi: 'trẻ em', strokeCount: 7 },
      { character: '兵', hanViet: 'BINH', onyomi: 'へい, ひょう', kunyomi: 'つわもの', meaningVi: 'binh lính', strokeCount: 7 },
      { character: '再', hanViet: 'TÁI', onyomi: 'さい, さ', kunyomi: 'ふたた-び', meaningVi: 'lại, một lần nữa', strokeCount: 6 },
      { character: '凍', hanViet: 'ĐÔNG', onyomi: 'とう', kunyomi: 'こお-る, こご-える, こご-る, い-てる, し-みる', meaningVi: 'đóng băng', strokeCount: 10 },
      { character: '刊', hanViet: 'SAN', onyomi: 'かん', meaningVi: 'xuất bản, khắc in', strokeCount: 5 },
      { character: '刷', hanViet: 'LOÁT', onyomi: 'さつ', kunyomi: 'す-る, -ず-り, -ずり, は-く', meaningVi: 'in ấn', strokeCount: 8 },
      { character: '効', hanViet: 'HIỆU', onyomi: 'こう', kunyomi: 'き-く, ききめ, なら-う', meaningVi: 'hiệu quả, hiệu lực', strokeCount: 8 },
      { character: '勇', hanViet: 'DŨNG', onyomi: 'ゆう', kunyomi: 'いさ-む', meaningVi: 'dũng cảm', strokeCount: 9 },
      { character: '勢', hanViet: 'THẾ', onyomi: 'せい, ぜい', kunyomi: 'いきお-い, はずみ', meaningVi: 'thế lực, khí thế', strokeCount: 13 },
      { character: '包', hanViet: 'BAO', onyomi: 'ほう', kunyomi: 'つつ-む, くる-む', meaningVi: 'bao bọc, gói lại', strokeCount: 5 },
      { character: '匹', hanViet: 'THẤT', onyomi: 'ひつ', kunyomi: 'ひき', meaningVi: 'con (đơn vị đếm thú nhỏ)', strokeCount: 4 },
    ],
  },
  {
    lessonNumber: 701,
    jlptLevel: 'N2',
    title: 'Kanji N2 bổ sung (2)',
    sortOrder: 7010,
    entries: [
      { character: '印', hanViet: 'ẤN', onyomi: 'いん', kunyomi: 'しるし, -じるし, しる-す', meaningVi: 'con dấu, dấu hiệu', strokeCount: 6 },
      { character: '厚', hanViet: 'HẬU', onyomi: 'こう', kunyomi: 'あつ-い, あか', meaningVi: 'dày, hậu hĩnh', strokeCount: 9 },
      { character: '双', hanViet: 'SONG', onyomi: 'そう', kunyomi: 'ふた, たぐい, ならぶ, ふたつ', meaningVi: 'đôi, cặp', strokeCount: 4 },
      { character: '叫', hanViet: 'KHIẾU', onyomi: 'きょう', kunyomi: 'さけ-ぶ', meaningVi: 'kêu la, hét lên', strokeCount: 6 },
      { character: '召', hanViet: 'TRIỆU', onyomi: 'しょう', kunyomi: 'め-す', meaningVi: 'triệu tập, gọi đến', strokeCount: 5 },
      { character: '史', hanViet: 'SỬ', onyomi: 'し', meaningVi: 'lịch sử', strokeCount: 5 },
      { character: '含', hanViet: 'HÀM', onyomi: 'がん', kunyomi: 'ふく-む, ふく-める', meaningVi: 'bao gồm, ngậm', strokeCount: 7 },
      { character: '咲', hanViet: 'TIẾU', onyomi: 'しょう', kunyomi: 'さ-く, -ざき', meaningVi: 'nở (hoa)', strokeCount: 9 },
      { character: '喫', hanViet: 'KHIẾT', onyomi: 'きつ', kunyomi: 'の-む', meaningVi: 'ăn uống, hút (thuốc)', strokeCount: 12 },
      { character: '均', hanViet: 'QUÂN', onyomi: 'きん', kunyomi: 'なら-す', meaningVi: 'đều, quân bình', strokeCount: 7 },
      { character: '型', hanViet: 'HÌNH', onyomi: 'けい', kunyomi: 'かた, -がた', meaningVi: 'khuôn mẫu, kiểu dáng', strokeCount: 9 },
      { character: '城', hanViet: 'THÀNH', onyomi: 'じょう, せい', kunyomi: 'しろ', meaningVi: 'thành trì, lâu đài', strokeCount: 9 },
      { character: '塗', hanViet: 'ĐỒ', onyomi: 'と', kunyomi: 'ぬ-る, ぬ-り, まみ-れる', meaningVi: 'sơn, quét, bôi', strokeCount: 13 },
      { character: '姓', hanViet: 'TÍNH', onyomi: 'せい, しょう', meaningVi: 'họ (tên họ)', strokeCount: 8 },
      { character: '季', hanViet: 'QUÝ', onyomi: 'き', meaningVi: 'mùa, quý (thời gian)', strokeCount: 8 },
      { character: '宇', hanViet: 'VŨ', onyomi: 'う', meaningVi: 'vũ trụ, mái nhà', strokeCount: 6 },
      { character: '宝', hanViet: 'BẢO', onyomi: 'ほう', kunyomi: 'たから', meaningVi: 'báu vật', strokeCount: 8 },
      { character: '封', hanViet: 'PHONG', onyomi: 'ふう, ほう', meaningVi: 'niêm phong', strokeCount: 9 },
      { character: '専', hanViet: 'CHUYÊN', onyomi: 'せん', kunyomi: 'もっぱ-ら', meaningVi: 'chuyên, riêng biệt', strokeCount: 9 },
      { character: '州', hanViet: 'CHÂU', onyomi: 'しゅう, す', kunyomi: 'す', meaningVi: 'châu, bang', strokeCount: 6 },
    ],
  },
  {
    lessonNumber: 702,
    jlptLevel: 'N2',
    title: 'Kanji N2 bổ sung (3)',
    sortOrder: 7020,
    entries: [
      { character: '巨', hanViet: 'CỰ', onyomi: 'きょ', meaningVi: 'khổng lồ, to lớn', strokeCount: 5 },
      { character: '布', hanViet: 'BỐ', onyomi: 'ふ, ほ', kunyomi: 'ぬの, し-く, きれ', meaningVi: 'vải, phân bố', strokeCount: 5 },
      { character: '帯', hanViet: 'ĐỚI', onyomi: 'たい', kunyomi: 'お-びる, おび', meaningVi: 'đai, vùng, dải', strokeCount: 10 },
      { character: '帽', hanViet: 'MẠO', onyomi: 'ぼう, もう', kunyomi: 'ずきん, おお-う', meaningVi: 'mũ', strokeCount: 12 },
      { character: '幼', hanViet: 'ẤU', onyomi: 'よう', kunyomi: 'おさな-い', meaningVi: 'ấu thơ, nhỏ tuổi', strokeCount: 5 },
      { character: '庁', hanViet: 'SẢNH', onyomi: 'ちょう, てい', kunyomi: 'やくしょ', meaningVi: 'sảnh, cơ quan chính phủ', strokeCount: 5 },
      { character: '床', hanViet: 'SÀNG', onyomi: 'しょう', kunyomi: 'とこ, ゆか', meaningVi: 'giường, sàn nhà', strokeCount: 7 },
      { character: '底', hanViet: 'ĐỂ', onyomi: 'てい', kunyomi: 'そこ', meaningVi: 'đáy', strokeCount: 8 },
      { character: '府', hanViet: 'PHỦ', onyomi: 'ふ', meaningVi: 'phủ, cơ quan hành chính', strokeCount: 8 },
      { character: '庫', hanViet: 'KHỐ', onyomi: 'こ, く', kunyomi: 'くら', meaningVi: 'kho', strokeCount: 10 },
      { character: '快', hanViet: 'KHOÁI', onyomi: 'かい', kunyomi: 'こころよ-い', meaningVi: 'vui vẻ, sảng khoái', strokeCount: 7 },
      { character: '恋', hanViet: 'LUYẾN', onyomi: 'れん', kunyomi: 'こ-う, こい, こい-しい', meaningVi: 'yêu, luyến ái', strokeCount: 10 },
      { character: '患', hanViet: 'HOẠN', onyomi: 'かん', kunyomi: 'わずら-う', meaningVi: 'bệnh tật, lo lắng', strokeCount: 11 },
      { character: '憎', hanViet: 'TĂNG', onyomi: 'ぞう', kunyomi: 'にく-む, にく-い, にく-らしい, にく-しみ', meaningVi: 'ghét, căm ghét', strokeCount: 14 },
      { character: '担', hanViet: 'ĐẢM', onyomi: 'たん', kunyomi: 'かつ-ぐ, にな-う', meaningVi: 'gánh vác, đảm nhận', strokeCount: 8 },
      { character: '捜', hanViet: 'SƯU', onyomi: 'そう, しゅ, しゅう', kunyomi: 'さが-す', meaningVi: 'tìm kiếm, lục soát', strokeCount: 10 },
      { character: '掘', hanViet: 'QUẬT', onyomi: 'くつ', kunyomi: 'ほ-る', meaningVi: 'đào, khai quật', strokeCount: 11 },
      { character: '採', hanViet: 'THÁI', onyomi: 'さい', kunyomi: 'と-る', meaningVi: 'hái, thu thập, chọn lấy', strokeCount: 11 },
      { character: '接', hanViet: 'TIẾP', onyomi: 'せつ, しょう', kunyomi: 'つ-ぐ', meaningVi: 'tiếp xúc, nối liền', strokeCount: 11 },
      { character: '換', hanViet: 'HOÁN', onyomi: 'かん', kunyomi: 'か-える, -か-える, か-わる', meaningVi: 'đổi, chuyển đổi', strokeCount: 12 },
    ],
  },
  {
    lessonNumber: 703,
    jlptLevel: 'N2',
    title: 'Kanji N2 bổ sung (4)',
    sortOrder: 7030,
    entries: [
      { character: '旧', hanViet: 'CỰU', onyomi: 'きゅう', kunyomi: 'ふる-い, もと', meaningVi: 'cũ, cựu', strokeCount: 5 },
      { character: '昇', hanViet: 'THĂNG', onyomi: 'しょう', kunyomi: 'のぼ-る', meaningVi: 'thăng lên, dâng lên', strokeCount: 8 },
      { character: '普', hanViet: 'PHỔ', onyomi: 'ふ', kunyomi: 'あまね-く, あまねし', meaningVi: 'phổ biến, rộng khắp', strokeCount: 12 },
      { character: '曇', hanViet: 'ĐÀM', onyomi: 'どん', kunyomi: 'くも-る', meaningVi: 'u ám, nhiều mây', strokeCount: 16 },
      { character: '替', hanViet: 'THẾ', onyomi: 'たい', kunyomi: 'か-える, か-え-, か-わる', meaningVi: 'thay thế, đổi', strokeCount: 12 },
      { character: '札', hanViet: 'TRÁT', onyomi: 'さつ', kunyomi: 'ふだ', meaningVi: 'thẻ, tiền giấy', strokeCount: 5 },
      { character: '机', hanViet: 'KỶ', onyomi: 'き', kunyomi: 'つくえ', meaningVi: 'cái bàn', strokeCount: 6 },
      { character: '材', hanViet: 'TÀI', onyomi: 'ざい', meaningVi: 'vật liệu, gỗ', strokeCount: 7 },
      { character: '板', hanViet: 'BẢN', onyomi: 'はん, ばん', kunyomi: 'いた', meaningVi: 'tấm ván, bảng', strokeCount: 8 },
      { character: '枯', hanViet: 'KHÔ', onyomi: 'こ', kunyomi: 'か-れる, か-らす', meaningVi: 'khô héo', strokeCount: 9 },
      { character: '柔', hanViet: 'NHU', onyomi: 'じゅう, にゅう', kunyomi: 'やわ-らか, やわ-らかい, やわ, やわ-ら', meaningVi: 'mềm mại, nhu nhược', strokeCount: 9 },
      { character: '柱', hanViet: 'TRỤ', onyomi: 'ちゅう', kunyomi: 'はしら', meaningVi: 'cột trụ', strokeCount: 9 },
      { character: '械', hanViet: 'GIỚI', onyomi: 'かい', kunyomi: 'かせ', meaningVi: 'công cụ, máy móc', strokeCount: 11 },
      { character: '棒', hanViet: 'BỔNG', onyomi: 'ぼう', meaningVi: 'cây gậy', strokeCount: 12 },
      { character: '植', hanViet: 'THỰC', onyomi: 'しょく', kunyomi: 'う-える, う-わる', meaningVi: 'trồng cây', strokeCount: 12 },
      { character: '極', hanViet: 'CỰC', onyomi: 'きょく, ごく', kunyomi: 'きわ-める, きわ-まる, きわ-まり, きわ-み, き-める, -ぎ-め, き-まる', meaningVi: 'cực điểm, rất', strokeCount: 12 },
      { character: '欧', hanViet: 'ÂU', onyomi: 'おう', kunyomi: 'うた-う, は-く', meaningVi: 'châu Âu', strokeCount: 8 },
      { character: '武', hanViet: 'VÕ', onyomi: 'ぶ, む', kunyomi: 'たけ, たけ-し', meaningVi: 'võ thuật, quân sự', strokeCount: 8 },
      { character: '歴', hanViet: 'LỊCH', onyomi: 'れき, れっき', meaningVi: 'lịch sử, trải qua', strokeCount: 14 },
      { character: '毒', hanViet: 'ĐỘC', onyomi: 'どく', meaningVi: 'chất độc', strokeCount: 8 },
    ],
  },
  {
    lessonNumber: 704,
    jlptLevel: 'N2',
    title: 'Kanji N2 bổ sung (5)',
    sortOrder: 7040,
    entries: [
      { character: '氷', hanViet: 'BĂNG', onyomi: 'ひょう', kunyomi: 'こおり, ひ, こお-る', meaningVi: 'băng, nước đá', strokeCount: 5 },
      { character: '沈', hanViet: 'TRẦM', onyomi: 'ちん, じん', kunyomi: 'しず-む, しず-める', meaningVi: 'chìm, trầm lắng', strokeCount: 7 },
      { character: '河', hanViet: 'HÀ', onyomi: 'か', kunyomi: 'かわ', meaningVi: 'sông', strokeCount: 8 },
      { character: '沸', hanViet: 'PHÍ', onyomi: 'ふつ', kunyomi: 'わ-く, わ-かす', meaningVi: 'sôi trào', strokeCount: 8 },
      { character: '油', hanViet: 'DU', onyomi: 'ゆ, ゆう', kunyomi: 'あぶら', meaningVi: 'dầu', strokeCount: 8 },
      { character: '況', hanViet: 'HUỐNG', onyomi: 'きょう', kunyomi: 'まし-て, いわ-んや, おもむき', meaningVi: 'huống chi, tình huống', strokeCount: 8 },
      { character: '泥', hanViet: 'NÊ', onyomi: 'でい, ない, で, に', kunyomi: 'どろ, なず-む', meaningVi: 'bùn', strokeCount: 8 },
      { character: '浴', hanViet: 'DỤC', onyomi: 'よく', kunyomi: 'あ-びる, あ-びせる', meaningVi: 'tắm', strokeCount: 10 },
      { character: '液', hanViet: 'DỊCH', onyomi: 'えき', meaningVi: 'chất lỏng', strokeCount: 11 },
      { character: '清', hanViet: 'THANH', onyomi: 'せい, しょう, しん', kunyomi: 'きよ-い, きよ-まる, きよ-める', meaningVi: 'trong sạch, thanh khiết', strokeCount: 11 },
      { character: '湯', hanViet: 'THANG', onyomi: 'とう', kunyomi: 'ゆ', meaningVi: 'nước nóng', strokeCount: 12 },
      { character: '湾', hanViet: 'LOAN', onyomi: 'わん', kunyomi: 'いりえ', meaningVi: 'vịnh', strokeCount: 12 },
      { character: '湿', hanViet: 'THẤP', onyomi: 'しつ, しゅう', kunyomi: 'しめ-る, しめ-す, うるお-う, うるお-す', meaningVi: 'ẩm ướt', strokeCount: 12 },
      { character: '準', hanViet: 'CHUẨN', onyomi: 'じゅん', kunyomi: 'じゅん-じる, じゅん-ずる, なぞら-える, のり, ひと-しい, みずもり', meaningVi: 'chuẩn mực, tiêu chuẩn', strokeCount: 13 },
      { character: '灯', hanViet: 'ĐĂNG', onyomi: 'とう', kunyomi: 'ひ, ほ-, ともしび, とも-す, あかり', meaningVi: 'đèn', strokeCount: 6 },
      { character: '照', hanViet: 'CHIẾU', onyomi: 'しょう', kunyomi: 'て-る, て-らす, て-れる', meaningVi: 'chiếu sáng', strokeCount: 13 },
      { character: '燥', hanViet: 'TÁO', onyomi: 'そう', kunyomi: 'はしゃ-ぐ', meaningVi: 'khô ráo', strokeCount: 17 },
      { character: '版', hanViet: 'BẢN', onyomi: 'はん', meaningVi: 'bản in', strokeCount: 8 },
      { character: '玉', hanViet: 'NGỌC', onyomi: 'ぎょく', kunyomi: 'たま, たま-, -だま', meaningVi: 'ngọc, viên bi', strokeCount: 5 },
      { character: '珍', hanViet: 'TRÂN', onyomi: 'ちん', kunyomi: 'めずら-しい, たから', meaningVi: 'quý hiếm', strokeCount: 9 },
    ],
  },
  {
    lessonNumber: 705,
    jlptLevel: 'N2',
    title: 'Kanji N2 bổ sung (6)',
    sortOrder: 7050,
    entries: [
      { character: '瓶', hanViet: 'BÌNH', onyomi: 'びん, へい', kunyomi: 'かめ', meaningVi: 'cái bình, chai', strokeCount: 11 },
      { character: '畜', hanViet: 'SÚC', onyomi: 'ちく', meaningVi: 'gia súc', strokeCount: 10 },
      { character: '畳', hanViet: 'ĐIỆP', onyomi: 'じょう, ちょう', kunyomi: 'たた-む, たたみ, かさ-なる', meaningVi: 'chiếu tatami, xếp chồng', strokeCount: 12 },
      { character: '省', hanViet: 'TỈNH', onyomi: 'せい, しょう', kunyomi: 'かえり-みる, はぶ-く', meaningVi: 'bộ (chính phủ); tiết kiệm, xem xét lại', strokeCount: 9 },
      { character: '硬', hanViet: 'NGẠNH', onyomi: 'こう', kunyomi: 'かた-い', meaningVi: 'cứng', strokeCount: 12 },
      { character: '秒', hanViet: 'MIỂU', onyomi: 'びょう', meaningVi: 'giây (thời gian)', strokeCount: 9 },
      { character: '移', hanViet: 'DI', onyomi: 'い', kunyomi: 'うつ-る, うつ-す', meaningVi: 'di chuyển, dời', strokeCount: 11 },
      { character: '章', hanViet: 'CHƯƠNG', onyomi: 'しょう', meaningVi: 'chương, huy hiệu', strokeCount: 11 },
      { character: '童', hanViet: 'ĐỒNG', onyomi: 'どう', kunyomi: 'わらべ', meaningVi: 'trẻ con', strokeCount: 12 },
      { character: '符', hanViet: 'PHÙ', onyomi: 'ふ', meaningVi: 'bùa, ký hiệu', strokeCount: 11 },
      { character: '筒', hanViet: 'ĐỒNG', onyomi: 'とう', kunyomi: 'つつ', meaningVi: 'ống', strokeCount: 12 },
      { character: '築', hanViet: 'TRÚC', onyomi: 'ちく', kunyomi: 'きず-く', meaningVi: 'xây dựng', strokeCount: 16 },
      { character: '粒', hanViet: 'LẠP', onyomi: 'りゅう', kunyomi: 'つぶ', meaningVi: 'hạt', strokeCount: 11 },
      { character: '紅', hanViet: 'HỒNG', onyomi: 'こう, く', kunyomi: 'べに, くれない, あか-い', meaningVi: 'màu hồng, đỏ', strokeCount: 9 },
      { character: '紹', hanViet: 'THIỆU', onyomi: 'しょう', meaningVi: 'giới thiệu', strokeCount: 11 },
      { character: '綿', hanViet: 'MIÊN', onyomi: 'めん', kunyomi: 'わた', meaningVi: 'bông vải', strokeCount: 14 },
      { character: '総', hanViet: 'TỔNG', onyomi: 'そう', kunyomi: 'す-べて, すべ-て, ふさ', meaningVi: 'tổng thể', strokeCount: 14 },
      { character: '緑', hanViet: 'LỤC', onyomi: 'りょく, ろく', kunyomi: 'みどり', meaningVi: 'màu xanh lá', strokeCount: 14 },
      { character: '線', hanViet: 'TUYẾN', onyomi: 'せん', kunyomi: 'すじ', meaningVi: 'đường kẻ, tuyến', strokeCount: 15 },
      { character: '績', hanViet: 'TÍCH', onyomi: 'せき', meaningVi: 'thành tích, công trạng', strokeCount: 17 },
    ],
  },
  {
    lessonNumber: 706,
    jlptLevel: 'N2',
    title: 'Kanji N2 bổ sung (7)',
    sortOrder: 7060,
    entries: [
      { character: '缶', hanViet: 'PHẪU', onyomi: 'かん', kunyomi: 'かま', meaningVi: 'lon, hộp thiếc', strokeCount: 6 },
      { character: '肌', hanViet: 'CƠ', onyomi: 'き', kunyomi: 'はだ', meaningVi: 'làn da, thớ thịt', strokeCount: 6 },
      { character: '肯', hanViet: 'KHẲNG', onyomi: 'こう', kunyomi: 'がえんじ-る', meaningVi: 'khẳng định, đồng ý', strokeCount: 8 },
      { character: '胃', hanViet: 'VỊ', onyomi: 'い', meaningVi: 'dạ dày', strokeCount: 9 },
      { character: '脂', hanViet: 'CHI', onyomi: 'し', kunyomi: 'あぶら', meaningVi: 'mỡ, chất béo', strokeCount: 10 },
      { character: '膚', hanViet: 'PHU', onyomi: 'ふ', kunyomi: 'はだ', meaningVi: 'da', strokeCount: 15 },
      { character: '臣', hanViet: 'THẦN', onyomi: 'しん, じん', meaningVi: 'bề tôi, quan lại', strokeCount: 7 },
      { character: '舟', hanViet: 'CHÂU', onyomi: 'しゅう', kunyomi: 'ふね, ふな-, -ぶね', meaningVi: 'thuyền', strokeCount: 6 },
      { character: '航', hanViet: 'HÀNG', onyomi: 'こう', meaningVi: 'hàng hải, bay', strokeCount: 10 },
      { character: '般', hanViet: 'BAN', onyomi: 'はん', meaningVi: 'loại, chung chung', strokeCount: 10 },
      { character: '荒', hanViet: 'HOANG', onyomi: 'こう', kunyomi: 'あ-らす, あ-れる, あら-い, すさ-ぶ, すさ-む, あ-らし', meaningVi: 'hoang vu, hoang dã', strokeCount: 9 },
      { character: '菓', hanViet: 'QUẢ', onyomi: 'か', meaningVi: 'bánh kẹo, hoa quả', strokeCount: 11 },
      { character: '著', hanViet: 'TRỨ', onyomi: 'ちょ, ちゃく', kunyomi: 'あらわ-す, いちじる-しい', meaningVi: 'nổi tiếng, viết (sách)', strokeCount: 11 },
      { character: '蒸', hanViet: 'CHƯNG', onyomi: 'じょう, せい', kunyomi: 'む-す, む-れる, む-らす', meaningVi: 'hấp, chưng cất', strokeCount: 13 },
      { character: '蔵', hanViet: 'TÀNG', onyomi: 'ぞう, そう', kunyomi: 'くら, おさ-める, かく-れる', meaningVi: 'cất giữ, kho', strokeCount: 15 },
      { character: '薄', hanViet: 'BẠC', onyomi: 'はく', kunyomi: 'うす-い, うす-, -うす, うす-める, うす-まる, うす-らぐ, うす-ら-, うす-れる, すすき', meaningVi: 'mỏng, nhạt', strokeCount: 16 },
      { character: '衣', hanViet: 'Y', onyomi: 'い, え', kunyomi: 'ころも, きぬ, -ぎ', meaningVi: 'áo, quần áo', strokeCount: 6 },
      { character: '袋', hanViet: 'ĐẠI', onyomi: 'たい, だい', kunyomi: 'ふくろ', meaningVi: 'cái túi', strokeCount: 11 },
      { character: '装', hanViet: 'TRANG', onyomi: 'そう, しょう', kunyomi: 'よそお-う, よそお-い', meaningVi: 'trang phục, trang bị', strokeCount: 12 },
      { character: '角', hanViet: 'GIÁC', onyomi: 'かく', kunyomi: 'かど, つの', meaningVi: 'góc, sừng', strokeCount: 7 },
    ],
  },
  {
    lessonNumber: 707,
    jlptLevel: 'N2',
    title: 'Kanji N2 bổ sung (8)',
    sortOrder: 7070,
    entries: [
      { character: '触', hanViet: 'XÚC', onyomi: 'しょく', kunyomi: 'ふ-れる, さわ-る, さわ', meaningVi: 'chạm, tiếp xúc', strokeCount: 13 },
      { character: '訓', hanViet: 'HUẤN', onyomi: 'くん, きん', kunyomi: 'おし-える, よ-む, くん-ずる', meaningVi: 'huấn luyện, giáo huấn', strokeCount: 10 },
      { character: '設', hanViet: 'THIẾT', onyomi: 'せつ', kunyomi: 'もう-ける', meaningVi: 'thiết lập, xây dựng', strokeCount: 11 },
      { character: '誌', hanViet: 'CHÍ', onyomi: 'し', meaningVi: 'tạp chí, ghi chép', strokeCount: 14 },
      { character: '課', hanViet: 'KHÓA', onyomi: 'か', meaningVi: 'bài học, khóa (phòng ban)', strokeCount: 15 },
      { character: '諸', hanViet: 'CHƯ', onyomi: 'しょ', kunyomi: 'もろ', meaningVi: 'các, mọi', strokeCount: 15 },
      { character: '講', hanViet: 'GIẢNG', onyomi: 'こう', meaningVi: 'giảng dạy, bài giảng', strokeCount: 17 },
      { character: '豊', hanViet: 'PHONG', onyomi: 'ほう, ぶ', kunyomi: 'ゆた-か, とよ', meaningVi: 'phong phú, dồi dào', strokeCount: 13 },
      { character: '販', hanViet: 'PHIẾN', onyomi: 'はん', meaningVi: 'buôn bán, kinh doanh', strokeCount: 11 },
      { character: '貿', hanViet: 'MẬU', onyomi: 'ぼう', meaningVi: 'mậu dịch, buôn bán', strokeCount: 12 },
      { character: '賞', hanViet: 'THƯỞNG', onyomi: 'しょう', kunyomi: 'ほ-める', meaningVi: 'phần thưởng', strokeCount: 15 },
      { character: '軒', hanViet: 'HIÊN', onyomi: 'けん', kunyomi: 'のき', meaningVi: 'mái hiên; căn (đếm nhà)', strokeCount: 10 },
      { character: '軟', hanViet: 'NHUYỄN', onyomi: 'なん', kunyomi: 'やわ-らか, やわ-らかい', meaningVi: 'mềm', strokeCount: 11 },
      { character: '輪', hanViet: 'LUÂN', onyomi: 'りん', kunyomi: 'わ', meaningVi: 'bánh xe, vòng', strokeCount: 15 },
      { character: '農', hanViet: 'NÔNG', onyomi: 'のう', meaningVi: 'nông nghiệp', strokeCount: 13 },
      { character: '辺', hanViet: 'BIÊN', onyomi: 'へん', kunyomi: 'あた-り, ほと-り, -べ', meaningVi: 'bên cạnh, vùng lân cận', strokeCount: 5 },
      { character: '造', hanViet: 'TẠO', onyomi: 'ぞう', kunyomi: 'つく-る, つく-り, -づく-り', meaningVi: 'tạo ra, chế tạo', strokeCount: 10 },
      { character: '郊', hanViet: 'GIAO', onyomi: 'こう', meaningVi: 'ngoại ô', strokeCount: 9 },
      { character: '郵', hanViet: 'BƯU', onyomi: 'ゆう', meaningVi: 'bưu điện', strokeCount: 11 },
      { character: '針', hanViet: 'CHÂM', onyomi: 'しん', kunyomi: 'はり', meaningVi: 'cây kim', strokeCount: 10 },
    ],
  },
  {
    lessonNumber: 708,
    jlptLevel: 'N2',
    title: 'Kanji N2 bổ sung (9)',
    sortOrder: 7080,
    entries: [
      { character: '鉱', hanViet: 'KHOÁNG', onyomi: 'こう', kunyomi: 'あらがね', meaningVi: 'khoáng sản', strokeCount: 13 },
      { character: '銅', hanViet: 'ĐỒNG', onyomi: 'どう', kunyomi: 'あかがね', meaningVi: 'đồng (kim loại)', strokeCount: 14 },
      { character: '録', hanViet: 'LỤC', onyomi: 'ろく', kunyomi: 'しる-す, と-る', meaningVi: 'ghi chép', strokeCount: 16 },
      { character: '防', hanViet: 'PHÒNG', onyomi: 'ぼう', kunyomi: 'ふせ-ぐ', meaningVi: 'phòng ngừa', strokeCount: 7 },
      { character: '隅', hanViet: 'NGUNG', onyomi: 'ぐう', kunyomi: 'すみ', meaningVi: 'góc, xó', strokeCount: 12 },
      { character: '隻', hanViet: 'CHIẾC', onyomi: 'せき', meaningVi: 'chiếc (đơn vị đếm tàu thuyền)', strokeCount: 10 },
      { character: '雲', hanViet: 'VÂN', onyomi: 'うん', kunyomi: 'くも, -ぐも', meaningVi: 'mây', strokeCount: 12 },
      { character: '零', hanViet: 'LINH', onyomi: 'れい', kunyomi: 'ぜろ, こぼ-す, こぼ-れる', meaningVi: 'số không', strokeCount: 13 },
      { character: '革', hanViet: 'CÁCH', onyomi: 'かく', kunyomi: 'かわ', meaningVi: 'da thuộc, cải cách', strokeCount: 9 },
      { character: '順', hanViet: 'THUẬN', onyomi: 'じゅん', meaningVi: 'thuận theo, thứ tự', strokeCount: 12 },
      { character: '香', hanViet: 'HƯƠNG', onyomi: 'こう, きょう', kunyomi: 'か, かお-り, かお-る', meaningVi: 'hương thơm', strokeCount: 9 },
      { character: '黄', hanViet: 'HOÀNG', onyomi: 'こう, おう', kunyomi: 'き, こ-', meaningVi: 'màu vàng', strokeCount: 11 },
      { character: '鼻', hanViet: 'TỴ', onyomi: 'び', kunyomi: 'はな', meaningVi: 'cái mũi', strokeCount: 14 },
      { character: '齢', hanViet: 'LINH', onyomi: 'れい', kunyomi: 'よわい, とし', meaningVi: 'tuổi tác', strokeCount: 17 },
    ],
  },
];
