// Bổ sung từ vựng N2 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 712-717.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N2_PART3: JlptVocabUnit[] = [
  {
    lessonNumber: 712,
    jlptLevel: 'N2',
    words: [
      { kana: 'ぶつぶつ', romaji: 'butsubutsu', meaning: 'lẩm bẩm, càu nhàu', partOfSpeech: 'phó từ, danh từ' },
      { kana: 'フライパン', romaji: 'furaipan', meaning: 'chảo rán', partOfSpeech: 'danh từ' },
      { kana: 'ブラウス', romaji: 'burausu', meaning: 'áo sơ mi nữ', partOfSpeech: 'danh từ' },
      { kanji: 'ぶら下げます', kana: 'ぶらさげます', romaji: 'burasagemasu', meaning: 'treo lủng lẳng, xách', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'ブラシ', romaji: 'burashi', meaning: 'cái bàn chải', partOfSpeech: 'danh từ' },
      { kana: 'プラスチック', romaji: 'purasuchikku', meaning: 'nhựa (chất liệu)', partOfSpeech: 'danh từ' },
      { kana: 'プラットホーム', romaji: 'purattohōmu', meaning: 'sân ga', partOfSpeech: 'danh từ' },
      { kana: 'フリー', romaji: 'furī', meaning: 'tự do, miễn phí', partOfSpeech: 'tính từ na' },
      { kana: 'プリント', romaji: 'purinto', meaning: 'bản in, tờ phát tay', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'ブローチ', romaji: 'burōchi', meaning: 'trâm cài áo', partOfSpeech: 'danh từ' },
      { kana: 'プログラム', romaji: 'puroguramu', meaning: 'chương trình', partOfSpeech: 'danh từ' },
      { kana: 'ふわふわ', romaji: 'fuwafuwa', meaning: 'mềm mại, bồng bềnh', partOfSpeech: 'phó từ, tính từ na' },
      { kana: 'へそ', romaji: 'heso', meaning: 'rốn', partOfSpeech: 'danh từ' },
      { kana: 'ベテラン', romaji: 'beteran', meaning: 'người kỳ cựu, lão luyện', partOfSpeech: 'danh từ' },
      { kana: 'ヘリコプター', romaji: 'herikoputā', meaning: 'máy bay trực thăng', partOfSpeech: 'danh từ' },
      { kana: 'ペンチ', romaji: 'penchi', meaning: 'kìm (dụng cụ)', partOfSpeech: 'danh từ' },
      { kanji: '解きます', kana: 'ほどきます', romaji: 'hodokimasu', meaning: 'tháo ra, cởi ra (nút thắt)', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 713,
    jlptLevel: 'N2',
    words: [
      { kana: 'ぼろ', romaji: 'boro', meaning: 'giẻ rách, đồ cũ nát', partOfSpeech: 'danh từ' },
      { kana: 'まあまあ', romaji: 'māmā', meaning: 'tàm tạm, cũng được', partOfSpeech: 'tính từ na, phó từ' },
      { kana: 'マイナス', romaji: 'mainasu', meaning: 'âm, trừ, bất lợi', partOfSpeech: 'danh từ' },
      { kana: 'まごまご', romaji: 'magomago', meaning: 'lúng túng, bối rối', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'マスク', romaji: 'masuku', meaning: 'khẩu trang, mặt nạ', partOfSpeech: 'danh từ' },
      { kanji: '跨ぎます', kana: 'またぎます', romaji: 'matagimasu', meaning: 'bước qua, dạng chân qua', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'まぶしい', romaji: 'mabushii', meaning: 'chói mắt, lóa mắt', partOfSpeech: 'tính từ i' },
      { kana: 'まぶた', romaji: 'mabuta', meaning: 'mí mắt', partOfSpeech: 'danh từ' },
      { kana: 'マフラー', romaji: 'mafurā', meaning: 'khăn quàng cổ (mùa đông)', partOfSpeech: 'danh từ' },
      { kana: 'みじめ', romaji: 'mijime', meaning: 'thảm hại, khốn khổ', partOfSpeech: 'tính từ na' },
      { kana: 'ミシン', romaji: 'mishin', meaning: 'máy khâu, máy may', partOfSpeech: 'danh từ' },
      { kana: 'みっともない', romaji: 'mittomonai', meaning: 'xấu hổ, khó coi', partOfSpeech: 'tính từ i' },
      { kana: 'ミリ', romaji: 'miri', meaning: 'mi-li-mét', partOfSpeech: 'danh từ' },
      { kana: 'メーター', romaji: 'mētā', meaning: 'đồng hồ đo (điện, nước)', partOfSpeech: 'danh từ' },
      { kana: 'めっきり', romaji: 'mekkiri', meaning: 'rõ rệt, đáng kể', partOfSpeech: 'phó từ' },
      { kana: 'めでたい', romaji: 'medetai', meaning: 'đáng mừng, tốt lành', partOfSpeech: 'tính từ i' },
      { kana: 'メニュー', romaji: 'menyū', meaning: 'thực đơn', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 714,
    jlptLevel: 'N2',
    words: [
      { kana: 'めまい', romaji: 'memai', meaning: 'chóng mặt, hoa mắt', partOfSpeech: 'danh từ' },
      { kana: 'モーター', romaji: 'mōtā', meaning: 'động cơ, mô tơ', partOfSpeech: 'danh từ' },
      { kana: 'もしかすると', romaji: 'moshikasuruto', meaning: 'có lẽ, có khi', partOfSpeech: 'phó từ' },
      { kanji: '凭れます', kana: 'もたれます', romaji: 'motaremasu', meaning: 'dựa vào; khó tiêu (bụng)', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'モダン', romaji: 'modan', meaning: 'hiện đại', partOfSpeech: 'tính từ na' },
      { kana: 'もったいない', romaji: 'mottainai', meaning: 'phí phạm, uổng phí', partOfSpeech: 'tính từ i' },
      { kana: 'モデル', romaji: 'moderu', meaning: 'người mẫu, mô hình', partOfSpeech: 'danh từ' },
      { kana: 'モノレール', romaji: 'monorēru', meaning: 'tàu điện một ray', partOfSpeech: 'danh từ' },
      { kana: 'やかましい', romaji: 'yakamashii', meaning: 'ồn ào; khắt khe', partOfSpeech: 'tính từ i' },
      { kana: 'やたらに', romaji: 'yatarani', meaning: 'một cách bừa bãi, quá mức', partOfSpeech: 'phó từ' },
      { kanji: '遣っ付けます', kana: 'やっつけます', romaji: 'yattsukemasu', meaning: 'đánh bại, làm cho xong (đối thủ)', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'やむをえない', romaji: 'yamuoenai', meaning: 'bất đắc dĩ, không thể tránh khỏi', partOfSpeech: 'tính từ i' },
      { kanji: '茹でます', kana: 'ゆでます', romaji: 'yudemasu', meaning: 'luộc', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '寄越します', kana: 'よこします', romaji: 'yokoshimasu', meaning: 'gửi tới, đưa tới', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'ラッシュアワー', romaji: 'rasshuawā', meaning: 'giờ cao điểm', partOfSpeech: 'danh từ' },
      { kana: 'ランニング', romaji: 'ranningu', meaning: 'chạy bộ; áo ba lỗ', partOfSpeech: 'danh từ' },
      { kana: 'リズム', romaji: 'rizumu', meaning: 'nhịp điệu', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 715,
    jlptLevel: 'N2',
    words: [
      { kana: 'リットル', romaji: 'rittoru', meaning: 'lít', partOfSpeech: 'danh từ' },
      { kana: 'リポート', romaji: 'ripōto', meaning: 'bản báo cáo', partOfSpeech: 'danh từ' },
      { kana: 'リボン', romaji: 'ribon', meaning: 'dải ruy băng', partOfSpeech: 'danh từ' },
      { kana: 'レインコート', romaji: 'reinkōto', meaning: 'áo mưa', partOfSpeech: 'danh từ' },
      { kana: 'レジャー', romaji: 'rejā', meaning: 'sự giải trí, thời gian rảnh', partOfSpeech: 'danh từ' },
      { kana: 'レベル', romaji: 'reberu', meaning: 'trình độ, mức độ', partOfSpeech: 'danh từ' },
      { kana: 'レンズ', romaji: 'renzu', meaning: 'thấu kính, ống kính', partOfSpeech: 'danh từ' },
      { kana: 'ロッカー', romaji: 'rokkā', meaning: 'tủ khóa cá nhân', partOfSpeech: 'danh từ' },
      { kana: 'わりあいに', romaji: 'wariaini', meaning: 'tương đối, so ra thì', partOfSpeech: 'phó từ' },
      { kana: 'ワンピース', romaji: 'wanpīsu', meaning: 'váy liền thân', partOfSpeech: 'danh từ' },
      { kanji: '圧縮', kana: 'あっしゅく', romaji: 'asshuku', meaning: 'sự nén, nén ép', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '宛名', kana: 'あてな', romaji: 'atena', meaning: 'tên và địa chỉ người nhận', partOfSpeech: 'danh từ' },
      { kanji: '安易', kana: 'あんい', romaji: 'ani', meaning: 'dễ dàng, xuề xòa', partOfSpeech: 'tính từ na' },
      { kanji: '以後', kana: 'いご', romaji: 'igo', meaning: 'từ nay về sau', partOfSpeech: 'danh từ' },
      { kanji: '威張ります', kana: 'いばります', romaji: 'ibarimasu', meaning: 'vênh váo, ra oai', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '意地悪', kana: 'いじわる', romaji: 'ijiwaru', meaning: 'ác ý, hay bắt nạt', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '慰めます', kana: 'なぐさめます', romaji: 'nagusamemasu', meaning: 'an ủi, dỗ dành', partOfSpeech: 'động từ nhóm 2' },
    ],
  },
  {
    lessonNumber: 716,
    jlptLevel: 'N2',
    words: [
      { kanji: '為替', kana: 'かわせ', romaji: 'kawase', meaning: 'hối đoái, phiếu chuyển tiền', partOfSpeech: 'danh từ' },
      { kanji: '移転', kana: 'いてん', romaji: 'iten', meaning: 'sự di dời, chuyển địa điểm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '緯度', kana: 'いど', romaji: 'ido', meaning: 'vĩ độ', partOfSpeech: 'danh từ' },
      { kanji: '衣食住', kana: 'いしょくじゅう', romaji: 'ishokujū', meaning: 'ăn mặc ở (nhu cầu thiết yếu)', partOfSpeech: 'danh từ' },
      { kanji: '一応', kana: 'いちおう', romaji: 'ichiō', meaning: 'tạm thời, sơ qua', partOfSpeech: 'phó từ' },
      { kanji: '一休み', kana: 'ひとやすみ', romaji: 'hitoyasumi', meaning: 'sự nghỉ ngơi chốc lát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '一昨日', kana: 'いっさくじつ', romaji: 'issakujitsu', meaning: 'hôm kia (cách đọc trang trọng)', partOfSpeech: 'danh từ' },
      { kanji: '一昨年', kana: 'いっさくねん', romaji: 'issakunen', meaning: 'năm kia (cách đọc trang trọng)', partOfSpeech: 'danh từ' },
      { kanji: '一斉', kana: 'いっせい', romaji: 'issei', meaning: 'đồng loạt, cùng một lúc', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '一旦', kana: 'いったん', romaji: 'ittan', meaning: 'một khi đã, tạm thời', partOfSpeech: 'phó từ' },
      { kanji: '一段と', kana: 'いちだんと', romaji: 'ichidanto', meaning: 'càng thêm, hơn nữa', partOfSpeech: 'phó từ' },
      { kanji: '一通り', kana: 'ひととおり', romaji: 'hitotōri', meaning: 'sơ qua, đại khái', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '一定', kana: 'いってい', romaji: 'ittei', meaning: 'cố định, nhất định', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '一流', kana: 'いちりゅう', romaji: 'ichiryū', meaning: 'hạng nhất, đẳng cấp', partOfSpeech: 'danh từ' },
      { kanji: '逸れます', kana: 'それます', romaji: 'soremasu', meaning: 'chệch hướng, lạc đề', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '引き止めます', kana: 'ひきとめます', romaji: 'hikitomemasu', meaning: 'giữ lại, ngăn cản', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '引っ掛かります', kana: 'ひっかかります', romaji: 'hikkakarimasu', meaning: 'bị mắc kẹt, bị lừa', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 717,
    jlptLevel: 'N2',
    words: [
      { kanji: '引っ繰り返します', kana: 'ひっくりかえします', romaji: 'hikkurikaeshimasu', meaning: 'lật ngược, đảo lộn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '引っ繰り返ります', kana: 'ひっくりかえります', romaji: 'hikkurikaerimasu', meaning: 'bị lật, bị đảo lộn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '引っ込みます', kana: 'ひっこみます', romaji: 'hikkomimasu', meaning: 'rút lui, thụt vào', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '引算', kana: 'ひきざん', romaji: 'hikizan', meaning: 'phép trừ', partOfSpeech: 'danh từ' },
      { kanji: '引き受けます', kana: 'ひきうけます', romaji: 'hikiukemasu', meaning: 'đảm nhận, nhận trách nhiệm', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '引分け', kana: 'ひきわけ', romaji: 'hikiwake', meaning: 'trận hòa', partOfSpeech: 'danh từ' },
      { kanji: '引き返します', kana: 'ひきかえします', romaji: 'hikikaeshimasu', meaning: 'quay trở lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '引力', kana: 'いんりょく', romaji: 'inryoku', meaning: 'lực hấp dẫn', partOfSpeech: 'danh từ' },
      { kanji: '羽根', kana: 'はね', romaji: 'hane', meaning: 'cầu lông (quả cầu); cánh, lông vũ', partOfSpeech: 'danh từ' },
      { kanji: '雨戸', kana: 'あまど', romaji: 'amado', meaning: 'cửa chớp chống mưa', partOfSpeech: 'danh từ' },
    ],
  },
];
