// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 959-964.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART11: JlptVocabUnit[] = [
  {
    lessonNumber: 959,
    jlptLevel: 'N1',
    words: [
      { kanji: '治まります', kana: 'おさまります', romaji: 'osamarimasu', meaning: 'yên ổn, lắng dịu', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '治安', kana: 'ちあん', romaji: 'chian', meaning: 'trật tự an ninh', partOfSpeech: 'danh từ' },
      { kanji: '耳鼻科', kana: 'じびか', romaji: 'jibika', meaning: 'khoa tai mũi họng', partOfSpeech: 'danh từ' },
      { kanji: '自ずから', kana: 'おのずから', romaji: 'onozukara', meaning: 'tự nhiên, đương nhiên', partOfSpeech: 'phó từ' },
      { kanji: '自我', kana: 'じが', romaji: 'jiga', meaning: 'cái tôi, bản ngã', partOfSpeech: 'danh từ' },
      { kanji: '自惚れ', kana: 'うぬぼれ', romaji: 'unubore', meaning: 'sự tự phụ, kiêu ngạo', partOfSpeech: 'danh từ' },
      { kanji: '自在', kana: 'じざい', romaji: 'jizai', meaning: 'tự do, tùy ý', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '自主', kana: 'じしゅ', romaji: 'jishu', meaning: 'tính tự chủ', partOfSpeech: 'danh từ' },
      { kanji: '自尊心', kana: 'じそんしん', romaji: 'jisonshin', meaning: 'lòng tự trọng', partOfSpeech: 'danh từ' },
      { kanji: '自動詞', kana: 'じどうし', romaji: 'jidōshi', meaning: 'tự động từ (nội động từ)', partOfSpeech: 'danh từ' },
      { kanji: '自立', kana: 'じりつ', romaji: 'jiritsu', meaning: 'sự tự lập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '辞職', kana: 'じしょく', romaji: 'jishoku', meaning: 'sự từ chức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '式場', kana: 'しきじょう', romaji: 'shikijō', meaning: 'hội trường tổ chức lễ', partOfSpeech: 'danh từ' },
      { kanji: '軸', kana: 'じく', romaji: 'jiku', meaning: 'trục, cán', partOfSpeech: 'danh từ' },
      { kanji: '雫', kana: 'しずく', romaji: 'shizuku', meaning: 'giọt nước', partOfSpeech: 'danh từ' },
      { kanji: '七日', kana: 'なぬか', romaji: 'nanuka', meaning: 'bảy ngày, ngày mùng bảy', partOfSpeech: 'danh từ' },
      { kanji: '執着', kana: 'しゅうじゃく', romaji: 'shūjaku', meaning: 'sự bám víu, cố chấp', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 960,
    jlptLevel: 'N1',
    words: [
      { kanji: '失格', kana: 'しっかく', romaji: 'shikkaku', meaning: 'sự mất tư cách, bị loại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '失調', kana: 'しっちょう', romaji: 'shicchō', meaning: 'sự mất cân bằng, rối loạn', partOfSpeech: 'danh từ' },
      { kanji: '湿気ます', kana: 'しけます', romaji: 'shikemasu', meaning: 'bị ẩm, ỉu (bánh)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '質疑', kana: 'しつぎ', romaji: 'shitsugi', meaning: 'câu hỏi chất vấn', partOfSpeech: 'danh từ' },
      { kanji: '質素', kana: 'しっそ', romaji: 'shisso', meaning: 'giản dị, tiết kiệm', partOfSpeech: 'tính từ na' },
      { kanji: '実', kana: 'じつ', romaji: 'jitsu', meaning: 'sự thật, chân thành', partOfSpeech: 'danh từ' },
      { kanji: '実業家', kana: 'じつぎょうか', romaji: 'jitsugyōka', meaning: 'doanh nhân, nhà công nghiệp', partOfSpeech: 'danh từ' },
      { kanji: '実質', kana: 'じっしつ', romaji: 'jisshitsu', meaning: 'thực chất, bản chất', partOfSpeech: 'danh từ' },
      { kanji: '実情', kana: 'じつじょう', romaji: 'jitsujō', meaning: 'tình hình thực tế', partOfSpeech: 'danh từ' },
      { kanji: '実践', kana: 'じっせん', romaji: 'jissen', meaning: 'sự thực hành, thực tiễn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '実態', kana: 'じったい', romaji: 'jittai', meaning: 'thực trạng', partOfSpeech: 'danh từ' },
      { kanji: '実費', kana: 'じっぴ', romaji: 'jippi', meaning: 'chi phí thực tế', partOfSpeech: 'danh từ' },
      { kanji: '芝', kana: 'しば', romaji: 'shiba', meaning: 'cỏ, bãi cỏ', partOfSpeech: 'danh từ' },
      { kanji: '写し', kana: 'うつし', romaji: 'utsushi', meaning: 'bản sao, bản chép', partOfSpeech: 'danh từ' },
      { kanji: '斜面', kana: 'しゃめん', romaji: 'shamen', meaning: 'mặt dốc, mặt nghiêng', partOfSpeech: 'danh từ' },
      { kanji: '社', kana: 'やしろ', romaji: 'yashiro', meaning: 'đền thờ Thần đạo', partOfSpeech: 'danh từ' },
      { kanji: '社交', kana: 'しゃこう', romaji: 'shakō', meaning: 'sự giao tiếp xã hội', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 961,
    jlptLevel: 'N1',
    words: [
      { kanji: '社宅', kana: 'しゃたく', romaji: 'shataku', meaning: 'nhà ở công ty cấp', partOfSpeech: 'danh từ' },
      { kanji: '謝絶', kana: 'しゃぜつ', romaji: 'shazetsu', meaning: 'sự từ chối (khéo léo)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '遮ります', kana: 'さえぎります', romaji: 'saegirimasu', meaning: 'che khuất, ngắt lời', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '若しくは', kana: 'もしくは', romaji: 'moshikuha', meaning: 'hoặc là', partOfSpeech: 'liên từ' },
      { kanji: '若干', kana: 'じゃっかん', romaji: 'jakkan', meaning: 'một số, ít nhiều', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '弱', kana: 'じゃく', romaji: 'jaku', meaning: 'hơi kém, hơi ít hơn (mức nêu ra)', partOfSpeech: 'hậu tố' },
      { kanji: '弱まります', kana: 'よわまります', romaji: 'yowamarimasu', meaning: 'yếu đi, suy giảm', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '弱めます', kana: 'よわめます', romaji: 'yowamemasu', meaning: 'làm yếu đi, giảm bớt', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '弱ります', kana: 'よわります', romaji: 'yowarimasu', meaning: 'suy yếu, lúng túng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '主演', kana: 'しゅえん', romaji: 'shuen', meaning: 'vai chính (phim, kịch)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '主観', kana: 'しゅかん', romaji: 'shukan', meaning: 'tính chủ quan', partOfSpeech: 'danh từ' },
      { kanji: '主権', kana: 'しゅけん', romaji: 'shuken', meaning: 'chủ quyền', partOfSpeech: 'danh từ' },
      { kanji: '主食', kana: 'しゅしょく', romaji: 'shushoku', meaning: 'lương thực chính', partOfSpeech: 'danh từ' },
      { kanji: '主体', kana: 'しゅたい', romaji: 'shutai', meaning: 'chủ thể', partOfSpeech: 'danh từ' },
      { kanji: '主題', kana: 'しゅだい', romaji: 'shudai', meaning: 'chủ đề', partOfSpeech: 'danh từ' },
      { kanji: '主導', kana: 'しゅどう', romaji: 'shudō', meaning: 'sự chủ đạo, dẫn dắt', partOfSpeech: 'danh từ' },
      { kanji: '主任', kana: 'しゅにん', romaji: 'shunin', meaning: 'người phụ trách chính', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 962,
    jlptLevel: 'N1',
    words: [
      { kanji: '取っ手', kana: 'とって', romaji: 'totte', meaning: 'tay cầm, tay nắm', partOfSpeech: 'danh từ' },
      { kanji: '取りあえず', kana: 'とりあえず', romaji: 'toriaezu', meaning: 'trước hết, tạm thời', partOfSpeech: 'phó từ' },
      { kanji: '取り扱い', kana: 'とりあつかい', romaji: 'toriatsukai', meaning: 'cách xử lý, cách đối xử', partOfSpeech: 'danh từ' },
      { kanji: '取り扱います', kana: 'とりあつかいます', romaji: 'toriatsukaimasu', meaning: 'xử lý, kinh doanh (mặt hàng)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '取り巻きます', kana: 'とりまきます', romaji: 'torimakimasu', meaning: 'bao quanh, vây quanh', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '取り寄せます', kana: 'とりよせます', romaji: 'toriyosemasu', meaning: 'đặt hàng từ xa', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '取り混ぜます', kana: 'とりまぜます', romaji: 'torimazemasu', meaning: 'trộn lẫn với nhau', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '取り次ぎます', kana: 'とりつぎます', romaji: 'toritsugimasu', meaning: 'chuyển lời, làm trung gian', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '取り除きます', kana: 'とりのぞきます', romaji: 'torinozokimasu', meaning: 'loại bỏ, tháo bỏ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '取り替え', kana: 'とりかえ', romaji: 'torikae', meaning: 'sự thay thế, trao đổi', partOfSpeech: 'danh từ' },
      { kanji: '取り調べます', kana: 'とりしらべます', romaji: 'torishirabemasu', meaning: 'điều tra, thẩm vấn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '取り締まり', kana: 'とりしまり', romaji: 'torishimari', meaning: 'sự quản lý, kiểm soát', partOfSpeech: 'danh từ' },
      { kanji: '取り締まります', kana: 'とりしまります', romaji: 'torishimarimasu', meaning: 'quản lý, kiểm soát', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '取り戻します', kana: 'とりもどします', romaji: 'torimodoshimasu', meaning: 'lấy lại, giành lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '取り立てます', kana: 'とりたてます', romaji: 'toritatemasu', meaning: 'thu, đòi (nợ); đề bạt', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '守衛', kana: 'しゅえい', romaji: 'shuei', meaning: 'bảo vệ, người gác cổng', partOfSpeech: 'danh từ' },
      { kanji: '守備', kana: 'しゅび', romaji: 'shubi', meaning: 'sự phòng thủ', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 963,
    jlptLevel: 'N1',
    words: [
      { kanji: '手引き', kana: 'てびき', romaji: 'tebiki', meaning: 'sách hướng dẫn', partOfSpeech: 'danh từ' },
      { kanji: '手回し', kana: 'てまわし', romaji: 'temawashi', meaning: 'sự chuẩn bị, thu xếp', partOfSpeech: 'danh từ' },
      { kanji: '手掛けます', kana: 'てがけます', romaji: 'tegakemasu', meaning: 'đảm nhận, trực tiếp phụ trách', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '手近', kana: 'てぢか', romaji: 'tejika', meaning: 'gần tay, quen thuộc', partOfSpeech: 'tính từ na' },
      { kanji: '手軽', kana: 'てがる', romaji: 'tegaru', meaning: 'đơn giản, dễ dàng', partOfSpeech: 'tính từ na' },
      { kanji: '手芸', kana: 'しゅげい', romaji: 'shugei', meaning: 'thủ công mỹ nghệ (đan, thêu)', partOfSpeech: 'danh từ' },
      { kanji: '手元', kana: 'てもと', romaji: 'temoto', meaning: 'trong tay, bên cạnh', partOfSpeech: 'danh từ' },
      { kanji: '手際', kana: 'てぎわ', romaji: 'tegiwa', meaning: 'sự khéo léo, tài xử lý', partOfSpeech: 'danh từ' },
      { kanji: '手順', kana: 'てじゅん', romaji: 'tejun', meaning: 'trình tự, quy trình', partOfSpeech: 'danh từ' },
      { kanji: '手錠', kana: 'てじょう', romaji: 'tejō', meaning: 'còng tay', partOfSpeech: 'danh từ' },
      { kanji: '手数', kana: 'てかず', romaji: 'tekazu', meaning: 'công sức, sự phiền phức', partOfSpeech: 'danh từ' },
      { kanji: '手遅れ', kana: 'ておくれ', romaji: 'teokure', meaning: 'quá muộn', partOfSpeech: 'danh từ' },
      { kanji: '手当て', kana: 'てあて', romaji: 'teate', meaning: 'trợ cấp; sự sơ cứu', partOfSpeech: 'danh từ' },
      { kanji: '手配', kana: 'てはい', romaji: 'tehai', meaning: 'sự sắp xếp, bố trí; truy nã', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '手筈', kana: 'てはず', romaji: 'tehazu', meaning: 'kế hoạch, sự chuẩn bị', partOfSpeech: 'danh từ' },
      { kanji: '手分け', kana: 'てわけ', romaji: 'tewake', meaning: 'sự phân công', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '手本', kana: 'てほん', romaji: 'tehon', meaning: 'khuôn mẫu, hình mẫu', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 964,
    jlptLevel: 'N1',
    words: [
      { kanji: '種々', kana: 'くさぐさ', romaji: 'kusagusa', meaning: 'đủ loại, đa dạng', partOfSpeech: 'danh từ' },
      { kanji: '趣', kana: 'おもむき', romaji: 'omomuki', meaning: 'phong vị, nét thú vị', partOfSpeech: 'danh từ' },
      { kanji: '首飾り', kana: 'くびかざり', romaji: 'kubikazari', meaning: 'vòng cổ trang sức', partOfSpeech: 'danh từ' },
      { kanji: '首脳', kana: 'しゅのう', romaji: 'shunō', meaning: 'người đứng đầu, lãnh đạo cấp cao', partOfSpeech: 'danh từ' },
      { kanji: '首輪', kana: 'くびわ', romaji: 'kubiwa', meaning: 'vòng cổ (cho thú cưng)', partOfSpeech: 'danh từ' },
      { kanji: '受かります', kana: 'うかります', romaji: 'ukarimasu', meaning: 'thi đỗ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '受け継ぎます', kana: 'うけつぎます', romaji: 'uketsugimasu', meaning: 'kế thừa, thừa hưởng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '受け止めます', kana: 'うけとめます', romaji: 'uketomemasu', meaning: 'đón nhận, tiếp nhận (ý kiến)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '受け入れ', kana: 'うけいれ', romaji: 'ukeire', meaning: 'sự tiếp nhận', partOfSpeech: 'danh từ' },
      { kanji: '受け入れます', kana: 'うけいれます', romaji: 'ukeiremasu', meaning: 'tiếp nhận, chấp nhận', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '受け付けます', kana: 'うけつけます', romaji: 'uketsukemasu', meaning: 'tiếp nhận (hồ sơ, đơn)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '受身', kana: 'うけみ', romaji: 'ukemi', meaning: 'thể bị động', partOfSpeech: 'danh từ' },
      { kanji: '授けます', kana: 'さずけます', romaji: 'sazukemasu', meaning: 'trao tặng, truyền dạy', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '樹木', kana: 'じゅもく', romaji: 'jumoku', meaning: 'cây cối', partOfSpeech: 'danh từ' },
    ],
  },
];
