// Bổ sung kanji N1 — dịch tay (Hán Việt + nghĩa Việt) dựa trên dữ liệu đọc âm
// (onyomi/kunyomi) và stroke count lấy từ kanjiapi.dev (nguồn mở), không auto-scrape nghĩa tiếng Việt.
// KanjiLesson lessonNumber 800-805.

import type { JlptKanjiLesson } from './jlpt-kanji.data';

export const JLPT_KANJI_BOOST4_N1_A: JlptKanjiLesson[] = [
  {
    lessonNumber: 800,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (1)',
    sortOrder: 8000,
    entries: [
      { character: '丁', hanViet: 'ĐINH', onyomi: 'ちょう, てい, ちん, とう, ち', kunyomi: 'ひのと', meaningVi: 'phố, khu phố; đơn vị đếm đồ vật', strokeCount: 2 },
      { character: '丑', hanViet: 'SỬU', onyomi: 'ちゅう', kunyomi: 'うし', meaningVi: 'năm/giờ Sửu (con trâu)', strokeCount: 4 },
      { character: '且', hanViet: 'THẢ', onyomi: 'しょ, そ, しょう', kunyomi: 'か-つ', meaningVi: 'hơn nữa, và', strokeCount: 5 },
      { character: '丘', hanViet: 'KHÂU', onyomi: 'きゅう', kunyomi: 'おか', meaningVi: 'gò đồi', strokeCount: 5 },
      { character: '丙', hanViet: 'BÍNH', onyomi: 'へい', kunyomi: 'ひのえ', meaningVi: 'hạng ba, can Bính', strokeCount: 5 },
      { character: '丞', hanViet: 'THỪA', onyomi: 'じょう, しょう', kunyomi: 'すく-う, たす-ける', meaningVi: 'giúp đỡ, chức quan phụ tá', strokeCount: 6 },
      { character: '丹', hanViet: 'ĐAN', onyomi: 'たん', kunyomi: 'に', meaningVi: 'màu đỏ son, thuốc viên', strokeCount: 4 },
      { character: '乃', hanViet: 'NÃI', onyomi: 'ない, だい, の, あい', kunyomi: 'の, すなわ-ち, なんじ', meaningVi: 'bèn, thì (trợ từ cổ)', strokeCount: 2 },
      { character: '之', hanViet: 'CHI', onyomi: 'し', kunyomi: 'の, これ, ゆく, この', meaningVi: 'của, này (trợ từ Hán cổ)', strokeCount: 3 },
      { character: '乙', hanViet: 'ẤT', onyomi: 'おつ, いつ', kunyomi: 'おと-, きのと', meaningVi: 'hạng nhì, can Ất', strokeCount: 1 },
      { character: '也', hanViet: 'DÃ', onyomi: 'や, え', kunyomi: 'なり, か, また', meaningVi: 'là, vậy (trợ từ cổ)', strokeCount: 3 },
      { character: '井', hanViet: 'TỈNH', onyomi: 'せい, しょう', kunyomi: 'い', meaningVi: 'giếng nước', strokeCount: 4 },
      { character: '亘', hanViet: 'TUYÊN', onyomi: 'こう, かん, せん', kunyomi: 'わた-る, もと-める', meaningVi: 'trải dài suốt, kéo dài', strokeCount: 6 },
      { character: '亜', hanViet: 'Á', onyomi: 'あ', kunyomi: 'つ-ぐ', meaningVi: 'châu Á; hạng nhì, thứ', strokeCount: 7 },
      { character: '亥', hanViet: 'HỢI', onyomi: 'がい, かい', kunyomi: 'い', meaningVi: 'năm/giờ Hợi (con lợn)', strokeCount: 6 },
      { character: '亦', hanViet: 'DIỆC', onyomi: 'えき, やく', kunyomi: 'また', meaningVi: 'cũng, lại', strokeCount: 6 },
      { character: '亨', hanViet: 'HANH', onyomi: 'こう, きょう, ほう', kunyomi: 'とお-る', meaningVi: 'hanh thông, trôi chảy', strokeCount: 7 },
      { character: '享', hanViet: 'HƯỞNG', onyomi: 'きょう, こう', kunyomi: 'う-ける', meaningVi: 'hưởng thụ, nhận lấy', strokeCount: 8 },
      { character: '亭', hanViet: 'ĐÌNH', onyomi: 'てい, ちん', meaningVi: 'đình, quán nhỏ', strokeCount: 9 },
      { character: '亮', hanViet: 'LƯỢNG', onyomi: 'りょう', kunyomi: 'あきらか', meaningVi: 'sáng sủa, rõ ràng', strokeCount: 9 },
    ],
  },
  {
    lessonNumber: 801,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (2)',
    sortOrder: 8010,
    entries: [
      { character: '仁', hanViet: 'NHÂN', onyomi: 'じん, に, にん', meaningVi: 'nhân đức, lòng nhân', strokeCount: 4 },
      { character: '仙', hanViet: 'TIÊN', onyomi: 'せん, せんと', meaningVi: 'tiên, thần tiên', strokeCount: 5 },
      { character: '仮', hanViet: 'GIẢ', onyomi: 'か, け', kunyomi: 'かり, かり-', meaningVi: 'giả, tạm thời', strokeCount: 6 },
      { character: '仰', hanViet: 'NGƯỠNG', onyomi: 'ぎょう, こう', kunyomi: 'あお-ぐ, おお-せ, お-っしゃる, おっしゃ-る', meaningVi: 'ngưỡng mộ, ngẩng lên', strokeCount: 6 },
      { character: '伊', hanViet: 'Y', onyomi: 'い', kunyomi: 'かれ', meaningVi: 'nước Ý; đó, ấy', strokeCount: 6 },
      { character: '伍', hanViet: 'NGŨ', onyomi: 'ご', kunyomi: 'いつつ', meaningVi: 'số năm, hàng ngũ', strokeCount: 6 },
      { character: '伎', hanViet: 'KỸ', onyomi: 'ぎ, き', kunyomi: 'わざ, わざおぎ', meaningVi: 'tài nghệ, kỹ nữ', strokeCount: 6 },
      { character: '伏', hanViet: 'PHỤC', onyomi: 'ふく', kunyomi: 'ふ-せる, ふ-す', meaningVi: 'phục xuống, ẩn nấp', strokeCount: 6 },
      { character: '伯', hanViet: 'BÁ', onyomi: 'はく', meaningVi: 'bác (anh của cha)', strokeCount: 7 },
      { character: '伴', hanViet: 'BẠN', onyomi: 'はん, ばん', kunyomi: 'ともな-う', meaningVi: 'bạn đồng hành, đi cùng', strokeCount: 7 },
      { character: '伶', hanViet: 'LINH', onyomi: 'れい, りょう', kunyomi: 'わざおぎ', meaningVi: 'linh hoạt, diễn viên (cổ)', strokeCount: 7 },
      { character: '伽', hanViet: 'GIÀ', onyomi: 'か, が, きゃ, ぎゃ', kunyomi: 'とぎ', meaningVi: 'chăm sóc; hộ giá (Phật giáo)', strokeCount: 7 },
      { character: '但', hanViet: 'ĐÃN', onyomi: 'たん', kunyomi: 'ただ-し', meaningVi: 'nhưng, tuy nhiên', strokeCount: 7 },
      { character: '佐', hanViet: 'TÁ', onyomi: 'さ', meaningVi: 'phụ tá, giúp đỡ', strokeCount: 7 },
      { character: '佑', hanViet: 'HỰU', onyomi: 'ゆう, う', kunyomi: 'たす-ける', meaningVi: 'phù hộ, giúp đỡ', strokeCount: 7 },
      { character: '佳', hanViet: 'GIAI', onyomi: 'か', meaningVi: 'đẹp, tốt', strokeCount: 8 },
      { character: '併', hanViet: 'TÍNH', onyomi: 'へい', kunyomi: 'あわ-せる', meaningVi: 'gộp lại, hợp nhất', strokeCount: 8 },
      { character: '侃', hanViet: 'KHẢN', onyomi: 'かん', kunyomi: 'つよ-い', meaningVi: 'cương trực, mạnh mẽ', strokeCount: 8 },
      { character: '侍', hanViet: 'THỊ', onyomi: 'じ, し', kunyomi: 'さむらい, はべ-る', meaningVi: 'hầu hạ; võ sĩ samurai', strokeCount: 8 },
      { character: '侑', hanViet: 'HỰU', onyomi: 'ゆう, う', kunyomi: 'すす-める, たす-ける', meaningVi: 'mời ăn, giúp đỡ', strokeCount: 8 },
    ],
  },
  {
    lessonNumber: 802,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (3)',
    sortOrder: 8020,
    entries: [
      { character: '侯', hanViet: 'HẦU', onyomi: 'こう', meaningVi: 'tước hầu, chư hầu', strokeCount: 9 },
      { character: '俊', hanViet: 'TUẤN', onyomi: 'しゅん', meaningVi: 'tài giỏi, tuấn tú', strokeCount: 9 },
      { character: '修', hanViet: 'TU', onyomi: 'しゅう, しゅ', kunyomi: 'おさ-める, おさ-まる', meaningVi: 'tu dưỡng, sửa chữa', strokeCount: 10 },
      { character: '俳', hanViet: 'BÀI', onyomi: 'はい', meaningVi: 'diễn viên; thơ haiku', strokeCount: 10 },
      { character: '俵', hanViet: 'BIỂU', onyomi: 'ひょう', kunyomi: 'たわら', meaningVi: 'bao tải (đựng gạo)', strokeCount: 10 },
      { character: '俸', hanViet: 'BỔNG', onyomi: 'ほう', meaningVi: 'lương bổng', strokeCount: 10 },
      { character: '倉', hanViet: 'THƯƠNG', onyomi: 'そう', kunyomi: 'くら', meaningVi: 'kho chứa', strokeCount: 10 },
      { character: '倖', hanViet: 'HẠNH', onyomi: 'こう', kunyomi: 'しあわ-せ, さいわ-い', meaningVi: 'may mắn, hạnh phúc', strokeCount: 10 },
      { character: '倣', hanViet: 'PHỎNG', onyomi: 'ほう', kunyomi: 'なら-う', meaningVi: 'bắt chước, mô phỏng', strokeCount: 10 },
      { character: '倫', hanViet: 'LUÂN', onyomi: 'りん', meaningVi: 'luân lý, đạo đức', strokeCount: 10 },
      { character: '倭', hanViet: 'OA', onyomi: 'わ, い', kunyomi: 'やまと, したが-う', meaningVi: 'nước Nhật cổ (Yamato)', strokeCount: 10 },
      { character: '倹', hanViet: 'KIỆM', onyomi: 'けん', kunyomi: 'つま-しい, つづまやか', meaningVi: 'tiết kiệm', strokeCount: 10 },
      { character: '健', hanViet: 'KIỆN', onyomi: 'けん', kunyomi: 'すこ-やか', meaningVi: 'khỏe mạnh', strokeCount: 11 },
      { character: '偲', hanViet: 'TƯ', onyomi: 'さい, し', kunyomi: 'しの-ぶ', meaningVi: 'hoài niệm, nhớ lại', strokeCount: 11 },
      { character: '偵', hanViet: 'TRINH', onyomi: 'てい', meaningVi: 'trinh sát, do thám', strokeCount: 11 },
      { character: '傍', hanViet: 'BÀNG', onyomi: 'ぼう', kunyomi: 'かたわ-ら, わき, おか-, はた, そば', meaningVi: 'bên cạnh', strokeCount: 12 },
      { character: '傑', hanViet: 'KIỆT', onyomi: 'けつ', kunyomi: 'すぐ-れる', meaningVi: 'kiệt xuất, xuất sắc', strokeCount: 13 },
      { character: '傘', hanViet: 'TÁN', onyomi: 'さん', kunyomi: 'かさ', meaningVi: 'cái ô, dù', strokeCount: 12 },
      { character: '催', hanViet: 'THÔI', onyomi: 'さい', kunyomi: 'もよう-す, もよお-す', meaningVi: 'tổ chức, giục giã', strokeCount: 13 },
      { character: '債', hanViet: 'TRÁI', onyomi: 'さい', meaningVi: 'nợ, trái phiếu', strokeCount: 13 },
    ],
  },
  {
    lessonNumber: 803,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (4)',
    sortOrder: 8030,
    entries: [
      { character: '僕', hanViet: 'BỘC', onyomi: 'ぼく', kunyomi: 'しもべ', meaningVi: 'tôi tớ; tôi (nam tự xưng)', strokeCount: 14 },
      { character: '僚', hanViet: 'LIÊU', onyomi: 'りょう', meaningVi: 'đồng liêu, đồng nghiệp', strokeCount: 14 },
      { character: '僧', hanViet: 'TĂNG', onyomi: 'そう', meaningVi: 'nhà sư', strokeCount: 13 },
      { character: '儒', hanViet: 'NHO', onyomi: 'じゅ', meaningVi: 'Nho giáo', strokeCount: 16 },
      { character: '允', hanViet: 'DUẪN', onyomi: 'いん', kunyomi: 'じょう, まこと-に, ゆるす', meaningVi: 'cho phép, thành thật', strokeCount: 4 },
      { character: '克', hanViet: 'KHẮC', onyomi: 'こく', kunyomi: 'か-つ', meaningVi: 'khắc phục, chiến thắng', strokeCount: 7 },
      { character: '免', hanViet: 'MIỄN', onyomi: 'めん', kunyomi: 'まぬか-れる, まぬが-れる', meaningVi: 'miễn trừ, tha thứ', strokeCount: 8 },
      { character: '冒', hanViet: 'MẠO', onyomi: 'ぼう', kunyomi: 'おか-す', meaningVi: 'mạo hiểm, xâm phạm', strokeCount: 9 },
      { character: '冗', hanViet: 'NHŨNG', onyomi: 'じょう', meaningVi: 'thừa, dư thừa', strokeCount: 4 },
      { character: '冠', hanViet: 'QUAN', onyomi: 'かん', kunyomi: 'かんむり', meaningVi: 'vương miện, đứng đầu', strokeCount: 9 },
      { character: '冴', hanViet: 'HỖ', onyomi: 'ご, こ', kunyomi: 'さ-える, こお-る, ひ-える', meaningVi: 'trong sáng, minh mẫn; lạnh giá', strokeCount: 7 },
      { character: '冶', hanViet: 'DÃ', onyomi: 'や', kunyomi: 'い-る', meaningVi: 'luyện kim, nung chảy', strokeCount: 7 },
      { character: '凌', hanViet: 'LĂNG', onyomi: 'りょう', kunyomi: 'しの-ぐ', meaningVi: 'lấn át, vượt qua', strokeCount: 10 },
      { character: '凜', hanViet: 'LẪM', onyomi: 'りん', kunyomi: 'きびし-い', meaningVi: 'nghiêm khắc, lạnh lẽo', strokeCount: 15 },
      { character: '凝', hanViet: 'NGƯNG', onyomi: 'ぎょう', kunyomi: 'こ-る, こ-らす, こご-らす, こご-らせる, こご-る', meaningVi: 'ngưng tụ, đông đặc', strokeCount: 16 },
      { character: '凡', hanViet: 'PHÀM', onyomi: 'ぼん, はん', kunyomi: 'およ-そ, おうよ-そ, すべ-て', meaningVi: 'phàm tục, tầm thường', strokeCount: 3 },
      { character: '凱', hanViet: 'KHẢI', onyomi: 'がい, かい', kunyomi: 'かちどき, やわらぐ', meaningVi: 'khải hoàn, chiến thắng', strokeCount: 12 },
      { character: '凶', hanViet: 'HUNG', onyomi: 'きょう', meaningVi: 'hung dữ, điềm xấu', strokeCount: 4 },
      { character: '凸', hanViet: 'ĐỘT', onyomi: 'とつ', kunyomi: 'でこ', meaningVi: 'lồi ra', strokeCount: 5 },
      { character: '凹', hanViet: 'OA', onyomi: 'おう', kunyomi: 'くぼ-む, へこ-む, ぼこ', meaningVi: 'lõm vào', strokeCount: 5 },
    ],
  },
  {
    lessonNumber: 804,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (5)',
    sortOrder: 8040,
    entries: [
      { character: '刈', hanViet: 'NGẢI', onyomi: 'がい, かい', kunyomi: 'か-る', meaningVi: 'cắt, xén (cỏ, tóc)', strokeCount: 4 },
      { character: '剖', hanViet: 'PHẪU', onyomi: 'ぼう', meaningVi: 'mổ xẻ, phân tích', strokeCount: 10 },
      { character: '剛', hanViet: 'CƯƠNG', onyomi: 'ごう', meaningVi: 'cương cường, cứng rắn', strokeCount: 10 },
      { character: '剤', hanViet: 'TỄ', onyomi: 'ざい, すい, せい', kunyomi: 'かる, けず-る', meaningVi: 'liều thuốc, dược tễ', strokeCount: 10 },
      { character: '創', hanViet: 'SÁNG', onyomi: 'そう, しょう', kunyomi: 'つく-る, はじ-める, きず, けず-しける', meaningVi: 'sáng tạo, sáng lập; vết thương', strokeCount: 12 },
      { character: '功', hanViet: 'CÔNG', onyomi: 'こう, く', kunyomi: 'いさお', meaningVi: 'công lao, thành công', strokeCount: 5 },
      { character: '劣', hanViet: 'LIỆT', onyomi: 'れつ', kunyomi: 'おと-る', meaningVi: 'kém cỏi, thua kém', strokeCount: 6 },
      { character: '劾', hanViet: 'HẶC', onyomi: 'がい', meaningVi: 'đàn hặc, tố cáo', strokeCount: 8 },
      { character: '勁', hanViet: 'KÍNH', onyomi: 'けい', kunyomi: 'つよ-い', meaningVi: 'mạnh mẽ, cứng cỏi', strokeCount: 9 },
      { character: '勅', hanViet: 'SẮC', onyomi: 'ちょく', kunyomi: 'いまし-める, みことのり', meaningVi: 'sắc lệnh của vua', strokeCount: 9 },
      { character: '勘', hanViet: 'KHAM', onyomi: 'かん', meaningVi: 'trực giác; xem xét, khám xét', strokeCount: 11 },
      { character: '勧', hanViet: 'KHUYẾN', onyomi: 'かん, けん', kunyomi: 'すす-める', meaningVi: 'khuyến khích, khuyên bảo', strokeCount: 13 },
      { character: '勲', hanViet: 'HUÂN', onyomi: 'くん', kunyomi: 'いさお', meaningVi: 'huân chương, công trạng', strokeCount: 15 },
      { character: '勺', hanViet: 'THƯỚC', onyomi: 'しゃく', meaningVi: 'đơn vị đo lường nhỏ', strokeCount: 3 },
      { character: '匡', hanViet: 'KHUÔNG', onyomi: 'きょう, おう', kunyomi: 'すく-う, ただ-す', meaningVi: 'sửa chữa, giúp đỡ, khuôn phép', strokeCount: 6 },
      { character: '升', hanViet: 'THĂNG', onyomi: 'しょう', kunyomi: 'ます', meaningVi: 'đấu, thưng (đơn vị đo lường)', strokeCount: 4 },
      { character: '卓', hanViet: 'TRÁC', onyomi: 'たく', meaningVi: 'cao vượt trội; cái bàn', strokeCount: 8 },
      { character: '卯', hanViet: 'MÃO', onyomi: 'ぼう, もう', kunyomi: 'う', meaningVi: 'năm/giờ Mão (con mèo)', strokeCount: 5 },
      { character: '却', hanViet: 'KHƯỚC', onyomi: 'きゃく', kunyomi: 'かえ-って, しりぞ-く, しりぞ-ける', meaningVi: 'ngược lại, từ chối', strokeCount: 7 },
      { character: '卸', hanViet: 'TẢ', onyomi: 'しゃ', kunyomi: 'おろ-す, おろし, おろ-し', meaningVi: 'bán buôn, dỡ hàng', strokeCount: 9 },
    ],
  },
  {
    lessonNumber: 805,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (6)',
    sortOrder: 8050,
    entries: [
      { character: '厄', hanViet: 'ÁCH', onyomi: 'やく', meaningVi: 'tai ách, vận rủi', strokeCount: 4 },
      { character: '厘', hanViet: 'LY', onyomi: 'りん', meaningVi: 'đơn vị đo lường rất nhỏ', strokeCount: 9 },
      { character: '又', hanViet: 'HỰU', onyomi: 'ゆう', kunyomi: 'また, また-, また-の-', meaningVi: 'lại, hơn nữa', strokeCount: 2 },
      { character: '叔', hanViet: 'THÚC', onyomi: 'しゅく', meaningVi: 'chú (em của cha)', strokeCount: 8 },
      { character: '叙', hanViet: 'TỰ', onyomi: 'じょ', kunyomi: 'つい-ず, ついで', meaningVi: 'trần thuật, kể lại; phong tước', strokeCount: 9 },
      { character: '叡', hanViet: 'DUỆ', onyomi: 'えい', kunyomi: 'あき-らか', meaningVi: 'sáng suốt, thông minh (hoàng gia)', strokeCount: 16 },
      { character: '只', hanViet: 'CHỈ', onyomi: 'し', kunyomi: 'ただ', meaningVi: 'chỉ, chỉ là', strokeCount: 5 },
      { character: '叶', hanViet: 'HIỆP', onyomi: 'きょう', kunyomi: 'かな-える, かな-う', meaningVi: 'hợp, ứng nghiệm (điều ước)', strokeCount: 5 },
      { character: '司', hanViet: 'TY', onyomi: 'し', kunyomi: 'つかさど-る', meaningVi: 'quản lý, cai quản', strokeCount: 5 },
      { character: '后', hanViet: 'HẬU', onyomi: 'こう, ご', kunyomi: 'きさき', meaningVi: 'hoàng hậu; sau', strokeCount: 6 },
      { character: '吏', hanViet: 'LẠI', onyomi: 'り', meaningVi: 'quan lại, viên chức', strokeCount: 6 },
      { character: '吐', hanViet: 'THỔ', onyomi: 'と', kunyomi: 'は-く, つ-く', meaningVi: 'nôn, phun ra', strokeCount: 6 },
      { character: '吟', hanViet: 'NGÂM', onyomi: 'ぎん', meaningVi: 'ngâm thơ, xướng', strokeCount: 7 },
      { character: '呉', hanViet: 'NGÔ', onyomi: 'ご', kunyomi: 'く-れる, くれ', meaningVi: 'nước Ngô (Trung Quốc cổ)', strokeCount: 7 },
      { character: '哉', hanViet: 'TAI', onyomi: 'さい', kunyomi: 'かな, や', meaningVi: 'thay! (thán từ cổ)', strokeCount: 9 },
      { character: '唄', hanViet: 'BỐI', onyomi: 'ばい', kunyomi: 'うた, うた-う', meaningVi: 'bài hát, ca khúc', strokeCount: 10 },
      { character: '唆', hanViet: 'SOA', onyomi: 'さ', kunyomi: 'そそ-る, そそのか-す', meaningVi: 'xúi giục, kích động', strokeCount: 10 },
      { character: '唇', hanViet: 'THẦN', onyomi: 'しん', kunyomi: 'くちびる', meaningVi: 'môi', strokeCount: 10 },
    ],
  },
];
