// Bổ sung từ vựng N1 đợt 3 — tự soạn tay. lessonNumber 529–535.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST3_N1: JlptVocabUnit[] = [
  {
    lessonNumber: 529,
    jlptLevel: 'N1',
    words: [
      { kanji: '施策', kana: 'しさく', romaji: 'shisaku', meaning: 'chính sách, biện pháp thực thi', partOfSpeech: 'danh từ' },
      { kanji: '政策', kana: 'せいさく', romaji: 'seisaku', meaning: 'chính sách', partOfSpeech: 'danh từ' },
      { kanji: '施行', kana: 'しこう', romaji: 'shikō', meaning: 'thi hành (luật)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発足', kana: 'ほっそく', romaji: 'hossoku', meaning: 'khởi động, thành lập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '創設', kana: 'そうせつ', romaji: 'sōsetsu', meaning: 'sáng lập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '設立', kana: 'せつりつ', romaji: 'setsuritsu', meaning: 'thành lập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '廃止', kana: 'はいし', romaji: 'haishi', meaning: 'bãi bỏ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '撤廃', kana: 'てっぱい', romaji: 'teppai', meaning: 'xóa bỏ hoàn toàn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '解散', kana: 'かいさん', romaji: 'kaisan', meaning: 'giải tán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '統合', kana: 'とうごう', romaji: 'tōgō', meaning: 'thống hợp, hợp nhất', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '分裂', kana: 'ぶんれつ', romaji: 'bunretsu', meaning: 'chia rẽ, phân liệt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '再編', kana: 'さいへん', romaji: 'saihen', meaning: 'tái cơ cấu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '刷新', kana: 'さっしん', romaji: 'sasshin', meaning: 'đổi mới toàn diện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '一新', kana: 'いっしん', romaji: 'isshin', meaning: 'làm mới hoàn toàn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '見直し', kana: 'みなおし', romaji: 'minaoshi', meaning: 'sự xem xét lại', partOfSpeech: 'danh từ' },
      { kanji: '是正措置', kana: 'ぜせいそち', romaji: 'zesei sochi', meaning: 'biện pháp chấn chỉnh', partOfSpeech: 'danh từ' },
      { kanji: '暫定的', kana: 'ざんていてき', romaji: 'zanteiteki', meaning: 'mang tính tạm thời', partOfSpeech: 'tính từ na' },
      { kanji: '恒久的', kana: 'こうきゅうてき', romaji: 'kōkyūteki', meaning: 'mang tính vĩnh viễn', partOfSpeech: 'tính từ na' },
      { kanji: '抜本的', kana: 'ばっぽんてき', romaji: 'happonteki', meaning: 'triệt để, tận gốc', partOfSpeech: 'tính từ na' },
      { kanji: '根本的', kana: 'こんぽんてき', romaji: 'konponteki', meaning: 'mang tính căn bản', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 530,
    jlptLevel: 'N1',
    words: [
      { kanji: '相応', kana: 'そうおう', romaji: 'sōō', meaning: 'tương xứng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '該当', kana: 'がいとう', romaji: 'gaitō', meaning: 'thuộc diện tương ứng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '準ずる', kana: 'じゅんずる', romaji: 'junzuru', meaning: 'noi theo, tương đương với', partOfSpeech: 'động từ nhóm 3' },
      { kanji: '準拠', kana: 'じゅんきょ', romaji: 'junkyo', meaning: 'dựa theo tiêu chuẩn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '照合', kana: 'しょうごう', romaji: 'shōgō', meaning: 'đối chiếu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '対照', kana: 'たいしょう', romaji: 'taishō', meaning: 'sự đối chiếu, tương phản', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '照会', kana: 'しょうかい', romaji: 'shōkai', meaning: 'hỏi thông tin (xác minh)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '打診', kana: 'だしん', romaji: 'dashin', meaning: 'dò hỏi ý kiến trước', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '示唆', kana: 'しさ', romaji: 'shisa', meaning: 'ngụ ý, gợi ý', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '暗示', kana: 'あんじ', romaji: 'anji', meaning: 'ám chỉ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '露呈', kana: 'ろてい', romaji: 'rotei', meaning: 'bộc lộ, phơi bày', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発覚', kana: 'はっかく', romaji: 'hakkaku', meaning: 'bị phát giác', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '露見', kana: 'ろけん', romaji: 'roken', meaning: 'lộ ra, bại lộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '隠蔽', kana: 'いんぺい', romaji: 'inpei', meaning: 'che giấu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '偽装', kana: 'ぎそう', romaji: 'gisō', meaning: 'ngụy trang, giả mạo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '捏造', kana: 'ねつぞう', romaji: 'netsuzō', meaning: 'bịa đặt, ngụy tạo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '改ざん', kana: 'かいざん', romaji: 'kaizan', meaning: 'sửa đổi trái phép (tài liệu)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '偽造', kana: 'ぎぞう', romaji: 'gizō', meaning: 'làm giả', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '横領', kana: 'おうりょう', romaji: 'ōryō', meaning: 'biển thủ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '着服', kana: 'ちゃくふく', romaji: 'chakufuku', meaning: 'tham ô (tiền)', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 531,
    jlptLevel: 'N1',
    words: [
      { kanji: '布石', kana: 'ふせき', romaji: 'fuseki', meaning: 'nước cờ chuẩn bị, bước đệm', partOfSpeech: 'danh từ' },
      { kanji: '足掛かり', kana: 'あしがかり', romaji: 'ashigakari', meaning: 'bàn đạp, điểm tựa', partOfSpeech: 'danh từ' },
      { kanji: '糸口', kana: 'いとぐち', romaji: 'itoguchi', meaning: 'manh mối, đầu mối', partOfSpeech: 'danh từ' },
      { kanji: '手掛かり', kana: 'てがかり', romaji: 'tegakari', meaning: 'manh mối', partOfSpeech: 'danh từ' },
      { kanji: '突破口', kana: 'とっぱこう', romaji: 'toppakō', meaning: 'lối thoát đột phá', partOfSpeech: 'danh từ' },
      { kanji: '打開策', kana: 'だかいさく', romaji: 'dakaisaku', meaning: 'biện pháp phá thế bế tắc', partOfSpeech: 'danh từ' },
      { kanji: '妙案', kana: 'みょうあん', romaji: 'myōan', meaning: 'diệu kế, ý hay', partOfSpeech: 'danh từ' },
      { kanji: '苦肉の策', kana: 'くにくのさく', romaji: 'kuniku no saku', meaning: 'kế sách bất đắc dĩ', partOfSpeech: 'cụm từ' },
      { kanji: '窮余の策', kana: 'きゅうよのさく', romaji: 'kyūyo no saku', meaning: 'kế sách cùng đường', partOfSpeech: 'cụm từ' },
      { kanji: '奇策', kana: 'きさく', romaji: 'kisaku', meaning: 'kế lạ, sách lược khác thường', partOfSpeech: 'danh từ' },
      { kanji: '思惑', kana: 'おもわく', romaji: 'omowaku', meaning: 'tính toán ngầm, dự tính', partOfSpeech: 'danh từ' },
      { kanji: '魂胆', kana: 'こんたん', romaji: 'kontan', meaning: 'ý đồ ngầm', partOfSpeech: 'danh từ' },
      { kanji: '思案', kana: 'しあん', romaji: 'shian', meaning: 'suy tính, cân nhắc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '苦心', kana: 'くしん', romaji: 'kushin', meaning: 'khổ tâm suy nghĩ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '苦慮', kana: 'くりょ', romaji: 'kuryo', meaning: 'lo lắng khổ sở', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '思索', kana: 'しさく', romaji: 'shisaku', meaning: 'tư duy, suy tưởng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '熟考', kana: 'じゅっこう', romaji: 'jukkō', meaning: 'suy nghĩ kỹ lưỡng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '考案', kana: 'こうあん', romaji: 'kōan', meaning: 'nghĩ ra, sáng chế ý tưởng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発案', kana: 'はつあん', romaji: 'hatsuan', meaning: 'đề xuất ý tưởng đầu tiên', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '立案', kana: 'りつあん', romaji: 'ritsuan', meaning: 'lập kế hoạch, dự thảo', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 532,
    jlptLevel: 'N1',
    words: [
      { kanji: '几帳面', kana: 'きちょうめん', romaji: 'kichōmen', meaning: 'tỉ mỉ, ngăn nắp', partOfSpeech: 'tính từ na' },
      { kanji: '無頓着', kana: 'むとんちゃく', romaji: 'mutonchaku', meaning: 'không để tâm, thờ ơ', partOfSpeech: 'tính từ na' },
      { kanji: '無造作', kana: 'むぞうさ', romaji: 'muzōsa', meaning: 'tùy tiện, không cầu kỳ', partOfSpeech: 'tính từ na' },
      { kanji: '杜撰', kana: 'ずさん', romaji: 'zusan', meaning: 'cẩu thả, sơ sài', partOfSpeech: 'tính từ na' },
      { kanji: '几帳', kana: 'きちょう', romaji: 'kichō', meaning: 'bình phong (cổ, hiếm dùng độc lập)', partOfSpeech: 'danh từ' },
      { kanji: '横柄', kana: 'おうへい', romaji: 'ōhei', meaning: 'hống hách', partOfSpeech: 'tính từ na' },
      { kanji: '尊大', kana: 'そんだい', romaji: 'sondai', meaning: 'kiêu căng tự phụ', partOfSpeech: 'tính từ na' },
      { kanji: '卑屈', kana: 'ひくつ', romaji: 'hikutsu', meaning: 'quỵ lụy, hèn nhát', partOfSpeech: 'tính từ na' },
      { kanji: '従順', kana: 'じゅうじゅん', romaji: 'jūjun', meaning: 'ngoan ngoãn, phục tùng', partOfSpeech: 'tính từ na' },
      { kanji: '柔和', kana: 'にゅうわ', romaji: 'nyūwa', meaning: 'dịu dàng, ôn hòa', partOfSpeech: 'tính từ na' },
      { kanji: '寛大', kana: 'かんだい', romaji: 'kandai', meaning: 'khoan dung, độ lượng', partOfSpeech: 'tính từ na' },
      { kanji: '狭量', kana: 'きょうりょう', romaji: 'kyōryō', meaning: 'hẹp hòi', partOfSpeech: 'tính từ na' },
      { kanji: '几帳面さ', kana: 'きちょうめんさ', romaji: 'kichōmensa', meaning: 'tính tỉ mỉ (danh từ hóa)', partOfSpeech: 'danh từ' },
      { kanji: '生真面目', kana: 'きまじめ', romaji: 'kimajime', meaning: 'nghiêm túc thái quá', partOfSpeech: 'tính từ na' },
      { kanji: '几帳面な性格', kana: 'きちょうめんなせいかく', romaji: 'kichōmen na seikaku', meaning: 'tính cách tỉ mỉ', partOfSpeech: 'cụm từ' },
      { kanji: '大雑把', kana: 'おおざっぱ', romaji: 'ōzappa', meaning: 'đại khái, xuề xòa', partOfSpeech: 'tính từ na' },
      { kanji: '几帳面過ぎる', kana: 'きちょうめんすぎる', romaji: 'kichōmen sugiru', meaning: 'quá tỉ mỉ', partOfSpeech: 'cụm từ' },
      { kanji: '融通', kana: 'ゆうずう', romaji: 'yūzū', meaning: 'sự linh hoạt, xoay xở', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '臨機応変', kana: 'りんきおうへん', romaji: 'rinki ōhen', meaning: 'ứng biến tùy tình huống', partOfSpeech: 'danh từ' },
      { kanji: '融通が利く', kana: 'ゆうずうがきく', romaji: 'yūzū ga kiku', meaning: 'linh hoạt, dễ xoay xở', partOfSpeech: 'cụm từ' },
    ],
  },
  {
    lessonNumber: 533,
    jlptLevel: 'N1',
    words: [
      { kanji: '躍進', kana: 'やくしん', romaji: 'yakushin', meaning: 'phát triển vượt bậc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '飛躍', kana: 'ひやく', romaji: 'hiyaku', meaning: 'bước nhảy vọt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '台頭', kana: 'たいとう', romaji: 'taitō', meaning: 'nổi lên, trỗi dậy', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '興隆', kana: 'こうりゅう', romaji: 'kōryū', meaning: 'hưng thịnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '隆盛', kana: 'りゅうせい', romaji: 'ryūsei', meaning: 'thịnh vượng', partOfSpeech: 'danh từ' },
      { kanji: '凋落', kana: 'ちょうらく', romaji: 'chōraku', meaning: 'suy tàn (văn viết)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '没落', kana: 'ぼつらく', romaji: 'botsuraku', meaning: 'sa sút, sụp đổ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '衰亡', kana: 'すいぼう', romaji: 'suibō', meaning: 'suy vong', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '滅亡', kana: 'めつぼう', romaji: 'metsubō', meaning: 'diệt vong', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '興亡', kana: 'こうぼう', romaji: 'kōbō', meaning: 'sự hưng vong', partOfSpeech: 'danh từ' },
      { kanji: '存亡', kana: 'そんぼう', romaji: 'sonbō', meaning: 'sự tồn vong', partOfSpeech: 'danh từ' },
      { kanji: '危機', kana: 'きき', romaji: 'kiki', meaning: 'nguy cơ, khủng hoảng', partOfSpeech: 'danh từ' },
      { kanji: '危惧', kana: 'きぐ', romaji: 'kigu', meaning: 'lo ngại (về nguy cơ)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '懸念', kana: 'けねん', romaji: 'kenen', meaning: 'sự quan ngại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '憂慮', kana: 'ゆうりょ', romaji: 'yūryo', meaning: 'lo âu sâu sắc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '杞憂', kana: 'きゆう', romaji: 'kiyū', meaning: 'lo xa không cần thiết', partOfSpeech: 'danh từ' },
      { kanji: '危惧種', kana: 'きぐしゅ', romaji: 'kigushu', meaning: 'loài có nguy cơ tuyệt chủng', partOfSpeech: 'danh từ' },
      { kanji: '安泰', kana: 'あんたい', romaji: 'antai', meaning: 'an ổn, thái bình', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '平穏', kana: 'へいおん', romaji: 'heion', meaning: 'bình yên', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '波乱', kana: 'はらん', romaji: 'haran', meaning: 'sóng gió, biến động', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 534,
    jlptLevel: 'N1',
    words: [
      { kanji: '折衝', kana: 'せっしょう', romaji: 'sesshō', meaning: 'đàm phán ngoại giao', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '駆け引き', kana: 'かけひき', romaji: 'kakehiki', meaning: 'mặc cả, đấu trí', partOfSpeech: 'danh từ' },
      { kanji: '譲歩', kana: 'じょうほ', romaji: 'jōho', meaning: 'nhượng bộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '妥結', kana: 'だけつ', romaji: 'daketsu', meaning: 'đạt được thỏa thuận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '決裂', kana: 'けつれつ', romaji: 'ketsuretsu', meaning: 'đàm phán đổ vỡ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '膠着', kana: 'こうちゃく', romaji: 'kōchaku', meaning: 'bế tắc, giằng co', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '停滞', kana: 'ていたい', romaji: 'teitai', meaning: 'trì trệ, đình trệ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '打破', kana: 'だは', romaji: 'daha', meaning: 'phá vỡ (tình trạng cũ)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '突入', kana: 'とつにゅう', romaji: 'totsunyū', meaning: 'xông vào, bước vào giai đoạn mới', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '介在', kana: 'かいざい', romaji: 'kaizai', meaning: 'xen vào giữa, tồn tại xen kẽ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '仲裁', kana: 'ちゅうさい', romaji: 'chūsai', meaning: 'trọng tài, hòa giải', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '仲介', kana: 'ちゅうかい', romaji: 'chūkai', meaning: 'môi giới trung gian', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '斡旋', kana: 'あっせん', romaji: 'assen', meaning: 'giới thiệu, thu xếp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '調停', kana: 'ちょうてい', romaji: 'chōtei', meaning: 'hòa giải chính thức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '和解', kana: 'わかい', romaji: 'wakai', meaning: 'hòa giải', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '折り合い', kana: 'おりあい', romaji: 'oriai', meaning: 'sự dung hòa, thỏa hiệp', partOfSpeech: 'danh từ' },
      { kanji: '歩み寄り', kana: 'あゆみより', romaji: 'ayumiyori', meaning: 'sự nhân nhượng lẫn nhau', partOfSpeech: 'danh từ' },
      { kanji: '合意形成', kana: 'ごういけいせい', romaji: 'gōi keisei', meaning: 'hình thành sự đồng thuận', partOfSpeech: 'danh từ' },
      { kanji: '協調', kana: 'きょうちょう', romaji: 'kyōchō', meaning: 'sự hợp tác hài hòa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '連携', kana: 'れんけい', romaji: 'renkei', meaning: 'liên kết phối hợp', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 535,
    jlptLevel: 'N1',
    words: [
      { kanji: '風化', kana: 'ふうか', romaji: 'fūka', meaning: 'phong hóa, bị lãng quên dần', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '陳腐化', kana: 'ちんぷか', romaji: 'chinpuka', meaning: 'trở nên lỗi thời', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '形骸化', kana: 'けいがいか', romaji: 'keigaika', meaning: 'trở thành hình thức rỗng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '空洞化', kana: 'くうどうか', romaji: 'kūdōka', meaning: 'rỗng hóa, mất thực chất', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '硬直化', kana: 'こうちょくか', romaji: 'kōchokuka', meaning: 'trở nên cứng nhắc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '画一化', kana: 'かくいつか', romaji: 'kakuitsuka', meaning: 'đồng nhất hóa, rập khuôn hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '均質化', kana: 'きんしつか', romaji: 'kinshitsuka', meaning: 'đồng đều hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '個別化', kana: 'こべつか', romaji: 'kobetsuka', meaning: 'cá thể hóa, riêng biệt hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '細分化', kana: 'さいぶんか', romaji: 'saibunka', meaning: 'phân nhỏ chi tiết', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '専門化', kana: 'せんもんか', romaji: 'senmonka', meaning: 'chuyên môn hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '効率化', kana: 'こうりつか', romaji: 'kōritsuka', meaning: 'hiệu quả hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '合理化', kana: 'ごうりか', romaji: 'gōrika', meaning: 'hợp lý hóa, tinh giản', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '簡素化', kana: 'かんそか', romaji: 'kansoka', meaning: 'đơn giản hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '複合化', kana: 'ふくごうか', romaji: 'fukugōka', meaning: 'phức hợp hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '体系化', kana: 'たいけいか', romaji: 'taikeika', meaning: 'hệ thống hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '制度化', kana: 'せいどか', romaji: 'seidoka', meaning: 'thể chế hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '法制化', kana: 'ほうせいか', romaji: 'hōseika', meaning: 'luật pháp hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '義務化', kana: 'ぎむか', romaji: 'gimuka', meaning: 'bắt buộc hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '自由化', kana: 'じゆうか', romaji: 'jiyūka', meaning: 'tự do hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '民営化', kana: 'みんえいか', romaji: 'min\'eika', meaning: 'tư nhân hóa', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
];
