// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 1013-1018.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART20: JlptVocabUnit[] = [
  {
    lessonNumber: 1013,
    jlptLevel: 'N1',
    words: [
      { kanji: '敏感', kana: 'びんかん', romaji: 'binkan', meaning: 'nhạy cảm', partOfSpeech: 'tính từ na' },
      { kanji: '不意', kana: 'ふい', romaji: 'fui', meaning: 'đột ngột, bất ngờ', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '不吉', kana: 'ふきつ', romaji: 'fukitsu', meaning: 'điềm xấu, gở', partOfSpeech: 'tính từ na' },
      { kanji: '不景気', kana: 'ふけいき', romaji: 'fukeiki', meaning: 'suy thoái kinh tế', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '不在', kana: 'ふざい', romaji: 'fuzai', meaning: 'sự vắng mặt', partOfSpeech: 'danh từ' },
      { kanji: '不順', kana: 'ふじゅん', romaji: 'fujun', meaning: 'bất thường, thất thường (thời tiết)', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '不調', kana: 'ふちょう', romaji: 'fuchō', meaning: 'tình trạng không tốt, trục trặc', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '不評', kana: 'ふひょう', romaji: 'fuhyō', meaning: 'tiếng xấu, không được ưa chuộng', partOfSpeech: 'danh từ' },
      { kanji: '不服', kana: 'ふふく', romaji: 'fufuku', meaning: 'sự bất bình, không phục', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '不便', kana: 'ふびん', romaji: 'fubin', meaning: 'đáng thương, tội nghiệp', partOfSpeech: 'tính từ na' },
      { kanji: '不明', kana: 'ふめい', romaji: 'fumei', meaning: 'không rõ, chưa xác định', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '不良', kana: 'ふりょう', romaji: 'furyō', meaning: 'hư hỏng, kém chất lượng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '付き合います', kana: 'つきあいます', romaji: 'tsukiaimasu', meaning: 'giao du, hẹn hò', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '付け加えます', kana: 'つけくわえます', romaji: 'tsukekuwaemasu', meaning: 'thêm vào, bổ sung', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '付属', kana: 'ふぞく', romaji: 'fuzoku', meaning: 'trực thuộc, phụ thuộc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '付録', kana: 'ふろく', romaji: 'furoku', meaning: 'phụ lục', partOfSpeech: 'danh từ' },
      { kanji: '富', kana: 'とみ', romaji: 'tomi', meaning: 'sự giàu có', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 1014,
    jlptLevel: 'N1',
    words: [
      { kanji: '富みます', kana: 'とみます', romaji: 'tomimasu', meaning: 'trở nên giàu có', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '富豪', kana: 'ふごう', romaji: 'fugō', meaning: 'phú hào, triệu phú', partOfSpeech: 'danh từ' },
      { kanji: '布巾', kana: 'ふきん', romaji: 'fukin', meaning: 'khăn lau bát đĩa', partOfSpeech: 'danh từ' },
      { kanji: '布告', kana: 'ふこく', romaji: 'fukoku', meaning: 'sự tuyên bố (chính thức)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '扶養', kana: 'ふよう', romaji: 'fuyō', meaning: 'sự nuôi dưỡng, cấp dưỡng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '普遍', kana: 'ふへん', romaji: 'fuhen', meaning: 'tính phổ quát', partOfSpeech: 'danh từ' },
      { kanji: '浮かびます', kana: 'うかびます', romaji: 'ukabimasu', meaning: 'nổi lên, hiện ra trong đầu', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '浮気', kana: 'うわき', romaji: 'uwaki', meaning: 'sự ngoại tình, lăng nhăng', partOfSpeech: 'danh từ, tính từ na, động từ する' },
      { kanji: '浮力', kana: 'ふりょく', romaji: 'furyoku', meaning: 'lực nổi', partOfSpeech: 'danh từ' },
      { kanji: '父母', kana: 'ちちはは', romaji: 'chichihaha', meaning: 'cha mẹ', partOfSpeech: 'danh từ' },
      { kanji: '腐敗', kana: 'ふはい', romaji: 'fuhai', meaning: 'sự thối rữa, thối nát (đạo đức)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '負債', kana: 'ふさい', romaji: 'fusai', meaning: 'nợ nần', partOfSpeech: 'danh từ' },
      { kanji: '負傷', kana: 'ふしょう', romaji: 'fushō', meaning: 'sự bị thương', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '負担', kana: 'ふたん', romaji: 'futan', meaning: 'gánh nặng, trách nhiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '赴きます', kana: 'おもむきます', romaji: 'omomukimasu', meaning: 'đi đến, tiến tới (nơi công tác)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '赴任', kana: 'ふにん', romaji: 'funin', meaning: 'sự nhậm chức nơi mới', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '侮辱', kana: 'ぶじょく', romaji: 'bujoku', meaning: 'sự lăng mạ, xúc phạm', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 1015,
    jlptLevel: 'N1',
    words: [
      { kanji: '武装', kana: 'ぶそう', romaji: 'busō', meaning: 'sự vũ trang', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '武力', kana: 'ぶりょく', romaji: 'buryoku', meaning: 'vũ lực', partOfSpeech: 'danh từ' },
      { kanji: '舞います', kana: 'まいます', romaji: 'maimasu', meaning: 'múa, bay lượn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '部', kana: 'ぶ', romaji: 'bu', meaning: 'bộ phận, ban (đơn vị tổ chức)', partOfSpeech: 'danh từ' },
      { kanji: '部門', kana: 'ぶもん', romaji: 'bumon', meaning: 'bộ phận, lĩnh vực', partOfSpeech: 'danh từ' },
      { kanji: '封', kana: 'ふう', romaji: 'fū', meaning: 'sự niêm phong', partOfSpeech: 'danh từ' },
      { kanji: '封建', kana: 'ほうけん', romaji: 'hōken', meaning: 'phong kiến', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '封鎖', kana: 'ふうさ', romaji: 'fūsa', meaning: 'sự phong tỏa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '風車', kana: 'かざぐるま', romaji: 'kazaguruma', meaning: 'cối xay gió, chong chóng', partOfSpeech: 'danh từ' },
      { kanji: '風俗', kana: 'ふうぞく', romaji: 'fūzoku', meaning: 'phong tục', partOfSpeech: 'danh từ' },
      { kanji: '風土', kana: 'ふうど', romaji: 'fūdo', meaning: 'phong thổ, khí hậu địa phương', partOfSpeech: 'danh từ' },
      { kanji: '復旧', kana: 'ふくきゅう', romaji: 'fukukyū', meaning: 'sự khôi phục', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '腹立ち', kana: 'はらだち', romaji: 'haradachi', meaning: 'sự tức giận', partOfSpeech: 'danh từ' },
      { kanji: '覆面', kana: 'ふくめん', romaji: 'fukumen', meaning: 'sự che mặt, mặt nạ', partOfSpeech: 'danh từ' },
      { kanji: '沸騰', kana: 'ふっとう', romaji: 'futtō', meaning: 'sự sôi trào', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '仏', kana: 'ふつ', romaji: 'futsu', meaning: 'Pháp (nước Pháp, ateji)', partOfSpeech: 'danh từ' },
      { kanji: '仏像', kana: 'ぶつぞう', romaji: 'butsuzō', meaning: 'tượng Phật', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 1016,
    jlptLevel: 'N1',
    words: [
      { kanji: '物議', kana: 'ぶつぎ', romaji: 'butsugi', meaning: 'sự chỉ trích, bàn tán của công chúng', partOfSpeech: 'danh từ' },
      { kanji: '物好き', kana: 'ものずき', romaji: 'monozuki', meaning: 'tính tò mò, sở thích lạ', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '物資', kana: 'ぶっし', romaji: 'busshi', meaning: 'vật tư, hàng hóa', partOfSpeech: 'danh từ' },
      { kanji: '物足りない', kana: 'ものたりない', romaji: 'monotarinai', meaning: 'chưa thỏa mãn, còn thiếu gì đó', partOfSpeech: 'tính từ i' },
      { kanji: '物体', kana: 'ぶったい', romaji: 'buttai', meaning: 'vật thể', partOfSpeech: 'danh từ' },
      { kanji: '物置き', kana: 'ものおき', romaji: 'monōki', meaning: 'nhà kho', partOfSpeech: 'danh từ' },
      { kanji: '分', kana: 'ふん', romaji: 'fun', meaning: 'phút', partOfSpeech: 'danh từ' },
      { kanji: '分業', kana: 'ぶんぎょう', romaji: 'bungyō', meaning: 'sự phân công lao động', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '分散', kana: 'ぶんさん', romaji: 'bunsan', meaning: 'sự phân tán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '分子', kana: 'ぶんし', romaji: 'bunshi', meaning: 'tử số; phân tử', partOfSpeech: 'danh từ' },
      { kanji: '分担', kana: 'ぶんたん', romaji: 'buntan', meaning: 'sự phân chia trách nhiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '分配', kana: 'ぶんぱい', romaji: 'bunpai', meaning: 'sự phân phối', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '分母', kana: 'ぶんぼ', romaji: 'bunbo', meaning: 'mẫu số', partOfSpeech: 'danh từ' },
      { kanji: '分離', kana: 'ぶんり', romaji: 'bunri', meaning: 'sự tách rời, phân ly', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '噴出', kana: 'ふんしゅつ', romaji: 'funshutsu', meaning: 'sự phun trào', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '憤慨', kana: 'ふんがい', romaji: 'fungai', meaning: 'sự phẫn nộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '焚火', kana: 'たきび', romaji: 'takibi', meaning: 'đống lửa trại', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 1017,
    jlptLevel: 'N1',
    words: [
      { kanji: '奮闘', kana: 'ふんとう', romaji: 'funtō', meaning: 'sự phấn đấu, chiến đấu quyết liệt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '粉々', kana: 'こなごな', romaji: 'konagona', meaning: 'vỡ vụn thành mảnh nhỏ', partOfSpeech: 'tính từ na' },
      { kanji: '粉末', kana: 'ふんまつ', romaji: 'funmatsu', meaning: 'dạng bột mịn', partOfSpeech: 'danh từ' },
      { kanji: '紛れます', kana: 'まぎれます', romaji: 'magiremasu', meaning: 'bị lẫn vào, khuây khỏa', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '紛失', kana: 'ふんしつ', romaji: 'funshitsu', meaning: 'sự làm mất', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '紛争', kana: 'ふんそう', romaji: 'funsō', meaning: 'cuộc xung đột, tranh chấp', partOfSpeech: 'danh từ' },
      { kanji: '文', kana: 'ふみ', romaji: 'fumi', meaning: 'lá thư, văn thư (cổ)', partOfSpeech: 'danh từ' },
      { kanji: '文化財', kana: 'ぶんかざい', romaji: 'bunkazai', meaning: 'di sản văn hóa', partOfSpeech: 'danh từ' },
      { kanji: '文語', kana: 'ぶんご', romaji: 'bungo', meaning: 'văn ngôn, ngôn ngữ viết cổ', partOfSpeech: 'danh từ' },
      { kanji: '文書', kana: 'ぶんしょ', romaji: 'bunsho', meaning: 'văn bản, tài liệu', partOfSpeech: 'danh từ' },
      { kanji: '聞き取り', kana: 'ききとり', romaji: 'kikitori', meaning: 'nghe hiểu (luyện nghe)', partOfSpeech: 'danh từ' },
      { kanji: '兵器', kana: 'へいき', romaji: 'heiki', meaning: 'vũ khí quân sự', partOfSpeech: 'danh từ' },
      { kanji: '兵士', kana: 'へいし', romaji: 'heishi', meaning: 'binh sĩ', partOfSpeech: 'danh từ' },
      { kanji: '平たい', kana: 'ひらたい', romaji: 'hiratai', meaning: 'phẳng, dẹt', partOfSpeech: 'tính từ i' },
      { kanji: '平行', kana: 'へいこう', romaji: 'heikō', meaning: 'song song', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '平常', kana: 'へいじょう', romaji: 'heijō', meaning: 'bình thường', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '平方', kana: 'へいほう', romaji: 'heihō', meaning: 'bình phương, vuông (đơn vị đo)', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 1018,
    jlptLevel: 'N1',
    words: [
      { kanji: '並びに', kana: 'ならびに', romaji: 'narabini', meaning: 'và, cùng với', partOfSpeech: 'liên từ' },
      { kanji: '並列', kana: 'へいれつ', romaji: 'heiretsu', meaning: 'sự xếp song song', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '閉鎖', kana: 'へいさ', romaji: 'heisa', meaning: 'sự đóng cửa, phong tỏa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '偏ります', kana: 'かたよります', romaji: 'katayorimasu', meaning: 'thiên lệch, mất cân bằng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '変動', kana: 'へんどう', romaji: 'hendō', meaning: 'sự biến động', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '片言', kana: 'かたこと', romaji: 'katakoto', meaning: 'nói bập bẹ, nói ngọng', partOfSpeech: 'danh từ' },
      { kanji: '片思い', kana: 'かたおもい', romaji: 'kataomoi', meaning: 'yêu đơn phương', partOfSpeech: 'danh từ' },
      { kanji: '片付け', kana: 'かたづけ', romaji: 'katazuke', meaning: 'sự dọn dẹp', partOfSpeech: 'danh từ' },
      { kanji: '辺り', kana: 'ほとり', romaji: 'hotori', meaning: 'ven, bên cạnh (sông, hồ)', partOfSpeech: 'danh từ' },
      { kanji: '返還', kana: 'へんかん', romaji: 'henkan', meaning: 'sự hoàn trả', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '返答', kana: 'へんとう', romaji: 'hentō', meaning: 'câu trả lời', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '便宜', kana: 'べんぎ', romaji: 'bengi', meaning: 'sự thuận tiện, linh động', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '弁解', kana: 'べんかい', romaji: 'benkai', meaning: 'lời biện hộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '弁論', kana: 'べんろん', romaji: 'benron', meaning: 'tranh luận, biện luận', partOfSpeech: 'danh từ' },
    ],
  },
];
