// Bổ sung kanji N1 — dịch tay (Hán Việt + nghĩa Việt) dựa trên dữ liệu đọc âm
// (onyomi/kunyomi) và stroke count lấy từ kanjiapi.dev (nguồn mở), không auto-scrape nghĩa tiếng Việt.
// KanjiLesson lessonNumber 811-815.

import type { JlptKanjiLesson } from './jlpt-kanji.data';

export const JLPT_KANJI_BOOST4_N1_C: JlptKanjiLesson[] = [
  {
    lessonNumber: 811,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (1)',
    sortOrder: 8110,
    entries: [
      { character: '巌', hanViet: 'NHAM', onyomi: 'がん', kunyomi: 'いわ, いわお, けわ-しい', meaningVi: 'đá lớn, vách đá', strokeCount: 20 },
      { character: '巣', hanViet: 'SÀO', onyomi: 'そう', kunyomi: 'す, す-くう', meaningVi: 'tổ (chim, sâu bọ)', strokeCount: 11 },
      { character: '己', hanViet: 'KỶ', onyomi: 'こ, き', kunyomi: 'おのれ, つちのと, な', meaningVi: 'bản thân, mình', strokeCount: 3 },
      { character: '巳', hanViet: 'TỴ', onyomi: 'し', kunyomi: 'み', meaningVi: 'năm/giờ Tỵ (con rắn)', strokeCount: 3 },
      { character: '巴', hanViet: 'BA', onyomi: 'は', kunyomi: 'ともえ, うずまき', meaningVi: 'hình xoáy (tomoe)', strokeCount: 4 },
      { character: '巽', hanViet: 'TỐN', onyomi: 'そん', kunyomi: 'たつみ', meaningVi: 'hướng đông nam (bát quái)', strokeCount: 12 },
      { character: '帆', hanViet: 'PHÀM', onyomi: 'はん', kunyomi: 'ほ', meaningVi: 'cánh buồm', strokeCount: 6 },
      { character: '帝', hanViet: 'ĐẾ', onyomi: 'てい', kunyomi: 'みかど', meaningVi: 'hoàng đế, đấng tối cao', strokeCount: 9 },
      { character: '帥', hanViet: 'SOÁI', onyomi: 'すい', meaningVi: 'thống soái, chỉ huy', strokeCount: 9 },
      { character: '帳', hanViet: 'TRƯỚNG', onyomi: 'ちょう', kunyomi: 'とばり', meaningVi: 'sổ sách; màn trướng', strokeCount: 11 },
      { character: '幕', hanViet: 'MẠC', onyomi: 'まく, ばく', kunyomi: 'とばり', meaningVi: 'màn (sân khấu)', strokeCount: 13 },
      { character: '幽', hanViet: 'U', onyomi: 'ゆう', kunyomi: 'ふか-い, かす-か, くら-い, しろ-い', meaningVi: 'u tối, sâu kín', strokeCount: 9 },
      { character: '庄', hanViet: 'TRANG', onyomi: 'しょう, そ, そう, ほう', meaningVi: 'trang trại, làng quê', strokeCount: 6 },
      { character: '庶', hanViet: 'THỨ', onyomi: 'しょ', meaningVi: 'dân thường; con thứ', strokeCount: 11 },
      { character: '康', hanViet: 'KHANG', onyomi: 'こう', meaningVi: 'khang kiện, an bình', strokeCount: 11 },
      { character: '庸', hanViet: 'DUNG', onyomi: 'よう', meaningVi: 'tầm thường, bình thường', strokeCount: 11 },
      { character: '廃', hanViet: 'PHẾ', onyomi: 'はい', kunyomi: 'すた-れる, すた-る', meaningVi: 'bỏ phế, hủy bỏ', strokeCount: 12 },
      { character: '廉', hanViet: 'LIÊM', onyomi: 'れん', meaningVi: 'liêm khiết; giá rẻ', strokeCount: 13 },
      { character: '廊', hanViet: 'LANG', onyomi: 'ろう', meaningVi: 'hành lang', strokeCount: 12 },
      { character: '廷', hanViet: 'ĐÌNH', onyomi: 'てい', meaningVi: 'triều đình, tòa án', strokeCount: 7 },
    ],
  },
  {
    lessonNumber: 812,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (2)',
    sortOrder: 8120,
    entries: [
      { character: '弊', hanViet: 'TỆ', onyomi: 'へい', meaningVi: 'tệ nạn, hư hỏng', strokeCount: 15 },
      { character: '弐', hanViet: 'NHỊ', onyomi: 'に, じ', kunyomi: 'ふた-つ, そえ', meaningVi: 'số hai (dùng trong văn kiện)', strokeCount: 6 },
      { character: '弘', hanViet: 'HOẰNG', onyomi: 'こう, ぐ', kunyomi: 'ひろ-い', meaningVi: 'rộng lớn', strokeCount: 5 },
      { character: '弥', hanViet: 'DI', onyomi: 'み, び', kunyomi: 'や, いや, いよ-いよ, わた-る', meaningVi: 'càng thêm, khắp', strokeCount: 8 },
      { character: '弦', hanViet: 'HUYỀN', onyomi: 'げん', kunyomi: 'つる', meaningVi: 'dây cung, cạnh huyền', strokeCount: 8 },
      { character: '弧', hanViet: 'HỒ', onyomi: 'こ', meaningVi: 'cung tròn', strokeCount: 9 },
      { character: '張', hanViet: 'TRƯƠNG', onyomi: 'ちょう', kunyomi: 'は-る, -は-り, -ば-り', meaningVi: 'căng, giương; đơn vị đếm cây cung', strokeCount: 11 },
      { character: '彗', hanViet: 'TUỆ', onyomi: 'すい, え, けい, せい', kunyomi: 'ほうき', meaningVi: 'sao chổi', strokeCount: 11 },
      { character: '彦', hanViet: 'NGẠN', onyomi: 'げん', kunyomi: 'ひこ', meaningVi: 'chàng trai tài giỏi', strokeCount: 9 },
      { character: '彪', hanViet: 'BƯU', onyomi: 'ひょう, ひゅう', kunyomi: 'あや', meaningVi: 'vằn hổ; nhỏ nhắn', strokeCount: 11 },
      { character: '彬', hanViet: 'BÂN', onyomi: 'ひん, ふん', kunyomi: 'うるわ-しい, あき-らか', meaningVi: 'văn nhã, thanh tú', strokeCount: 11 },
      { character: '彰', hanViet: 'CHƯƠNG', onyomi: 'しょう', meaningVi: 'hiển rõ, biểu dương', strokeCount: 14 },
      { character: '影', hanViet: 'ẢNH', onyomi: 'えい', kunyomi: 'かげ', meaningVi: 'bóng, hình bóng', strokeCount: 15 },
      { character: '往', hanViet: 'VÃNG', onyomi: 'おう', kunyomi: 'い-く, いにしえ, さき-に, ゆ-く', meaningVi: 'đi, quá khứ', strokeCount: 8 },
      { character: '径', hanViet: 'KÍNH', onyomi: 'けい', kunyomi: 'みち, こみち, さしわたし, ただちに', meaningVi: 'đường kính, lối đi', strokeCount: 8 },
      { character: '従', hanViet: 'TÙNG', onyomi: 'じゅう, しょう, じゅ', kunyomi: 'したが-う, したが-える, より', meaningVi: 'tuân theo, đi theo', strokeCount: 10 },
      { character: '微', hanViet: 'VI', onyomi: 'び', kunyomi: 'かす-か', meaningVi: 'vi tế, nhỏ bé', strokeCount: 13 },
      { character: '徳', hanViet: 'ĐỨC', onyomi: 'とく', meaningVi: 'đạo đức, ân đức', strokeCount: 14 },
      { character: '忌', hanViet: 'KỴ', onyomi: 'き', kunyomi: 'い-む, い-み, い-まわしい', meaningVi: 'kiêng kỵ; ngày giỗ', strokeCount: 7 },
      { character: '忍', hanViet: 'NHẪN', onyomi: 'にん', kunyomi: 'しの-ぶ, しの-ばせる', meaningVi: 'nhẫn nại, chịu đựng', strokeCount: 7 },
    ],
  },
  {
    lessonNumber: 813,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (3)',
    sortOrder: 8130,
    entries: [
      { character: '志', hanViet: 'CHÍ', onyomi: 'し', kunyomi: 'シリング, こころざ-す, こころざし', meaningVi: 'chí hướng, ý định', strokeCount: 7 },
      { character: '応', hanViet: 'ỨNG', onyomi: 'おう, よう, -のう', kunyomi: 'あた-る, まさに, こた-える', meaningVi: 'đáp ứng, phản ứng', strokeCount: 7 },
      { character: '忠', hanViet: 'TRUNG', onyomi: 'ちゅう', meaningVi: 'trung thành', strokeCount: 8 },
      { character: '怜', hanViet: 'LINH', onyomi: 'れい, れん, りょう', kunyomi: 'あわ-れむ, さと-い', meaningVi: 'khôn ngoan, thương xót', strokeCount: 8 },
      { character: '怠', hanViet: 'ĐÃI', onyomi: 'たい', kunyomi: 'おこた-る, なま-ける', meaningVi: 'lười biếng, xao nhãng', strokeCount: 9 },
      { character: '恕', hanViet: 'THỨ', onyomi: 'じょ, しょ', kunyomi: 'ゆる-す', meaningVi: 'tha thứ, khoan dung', strokeCount: 10 },
      { character: '恩', hanViet: 'ÂN', onyomi: 'おん', meaningVi: 'ân huệ, ân đức', strokeCount: 10 },
      { character: '恵', hanViet: 'HUỆ', onyomi: 'けい, え', kunyomi: 'めぐ-む, めぐ-み', meaningVi: 'ân huệ, ban phước', strokeCount: 10 },
      { character: '悌', hanViet: 'ĐỄ', onyomi: 'てい, だい', meaningVi: 'kính nhường anh chị (đạo hiếu đễ)', strokeCount: 10 },
      { character: '悠', hanViet: 'DU', onyomi: 'ゆう', meaningVi: 'lâu dài, thong thả', strokeCount: 11 },
      { character: '惇', hanViet: 'ĐÔN', onyomi: 'しゅん, じゅん, とん', kunyomi: 'あつ-い', meaningVi: 'chân thành, hậu hĩnh', strokeCount: 11 },
      { character: '惜', hanViet: 'TÍCH', onyomi: 'せき', kunyomi: 'お-しい, お-しむ', meaningVi: 'tiếc, quý trọng', strokeCount: 11 },
      { character: '惟', hanViet: 'DUY', onyomi: 'い, ゆい', kunyomi: 'おも-んみる, これ, おも-うに', meaningVi: 'suy nghĩ; chỉ có', strokeCount: 11 },
      { character: '惣', hanViet: 'TỔNG', onyomi: 'そう', kunyomi: 'すべ-て', meaningVi: 'tất cả', strokeCount: 12 },
      { character: '惨', hanViet: 'THẢM', onyomi: 'さん, ざん', kunyomi: 'みじ-め, いた-む, むご-い', meaningVi: 'thảm thương, bi thảm', strokeCount: 11 },
      { character: '惰', hanViet: 'ĐỌA', onyomi: 'だ', meaningVi: 'lười biếng', strokeCount: 12 },
      { character: '愁', hanViet: 'SẦU', onyomi: 'しゅう', kunyomi: 'うれ-える, うれ-い', meaningVi: 'sầu muộn, lo lắng', strokeCount: 13 },
      { character: '愉', hanViet: 'DU', onyomi: 'ゆ', kunyomi: 'たの-しい, たの-しむ', meaningVi: 'vui vẻ', strokeCount: 12 },
      { character: '慧', hanViet: 'TUỆ', onyomi: 'けい, え', kunyomi: 'さとい', meaningVi: 'trí tuệ, thông minh', strokeCount: 15 },
      { character: '憩', hanViet: 'KHẾ', onyomi: 'けい', kunyomi: 'いこ-い, いこ-う', meaningVi: 'nghỉ ngơi', strokeCount: 16 },
    ],
  },
  {
    lessonNumber: 814,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (4)',
    sortOrder: 8140,
    entries: [
      { character: '憲', hanViet: 'HIẾN', onyomi: 'けん', meaningVi: 'hiến pháp, pháp luật', strokeCount: 16 },
      { character: '懇', hanViet: 'KHẨN', onyomi: 'こん', kunyomi: 'ねんご-ろ', meaningVi: 'khẩn khoản, chân thành', strokeCount: 17 },
      { character: '懐', hanViet: 'HOÀI', onyomi: 'かい, え', kunyomi: 'ふところ, なつ-かしい, なつ-かしむ, なつ-く, なつ-ける, なず-ける, いだ-く, おも-う', meaningVi: 'hoài niệm, ôm ấp', strokeCount: 16 },
      { character: '懸', hanViet: 'HUYỀN', onyomi: 'けん, け', kunyomi: 'か-ける, か-かる', meaningVi: 'treo, treo lơ lửng', strokeCount: 20 },
      { character: '我', hanViet: 'NGÃ', onyomi: 'が', kunyomi: 'われ, わ, わ-が-, わが-', meaningVi: 'cái tôi, bản thân', strokeCount: 7 },
      { character: '戒', hanViet: 'GIỚI', onyomi: 'かい', kunyomi: 'いまし-める', meaningVi: 'răn dạy, cảnh giới', strokeCount: 7 },
      { character: '戯', hanViet: 'HÝ', onyomi: 'ぎ, げ', kunyomi: 'たわむ-れる, ざ-れる, じゃ-れる', meaningVi: 'đùa giỡn, vui chơi', strokeCount: 15 },
      { character: '房', hanViet: 'PHÒNG', onyomi: 'ぼう', kunyomi: 'ふさ', meaningVi: 'buồng, phòng; tua', strokeCount: 8 },
      { character: '扇', hanViet: 'PHIẾN', onyomi: 'せん', kunyomi: 'おうぎ', meaningVi: 'cái quạt', strokeCount: 10 },
      { character: '扉', hanViet: 'PHI', onyomi: 'ひ', kunyomi: 'とびら', meaningVi: 'cánh cửa', strokeCount: 12 },
      { character: '扱', hanViet: 'SÁP', onyomi: 'そう, きゅう', kunyomi: 'あつか-い, あつか-う, あつか-る, こ-く', meaningVi: 'xử lý, đối xử', strokeCount: 6 },
      { character: '抄', hanViet: 'SAO', onyomi: 'しょう', meaningVi: 'trích lục, sao chép', strokeCount: 7 },
      { character: '把', hanViet: 'BÁ', onyomi: 'は, わ', meaningVi: 'nắm, cầm; bó (đơn vị đếm)', strokeCount: 7 },
      { character: '択', hanViet: 'TRẠCH', onyomi: 'たく', kunyomi: 'えら-ぶ', meaningVi: 'lựa chọn', strokeCount: 7 },
      { character: '披', hanViet: 'PHI', onyomi: 'ひ', meaningVi: 'phơi bày, mở ra', strokeCount: 8 },
      { character: '抵', hanViet: 'ĐỂ', onyomi: 'てい', meaningVi: 'chống lại, đạt tới', strokeCount: 8 },
      { character: '抹', hanViet: 'MẠT', onyomi: 'まつ', meaningVi: 'xóa, quét, bôi', strokeCount: 8 },
      { character: '抽', hanViet: 'TRỪU', onyomi: 'ちゅう', kunyomi: 'ひき-', meaningVi: 'rút ra, trừu tượng', strokeCount: 8 },
      { character: '拍', hanViet: 'PHÁCH', onyomi: 'はく, ひょう', meaningVi: 'vỗ tay, nhịp phách', strokeCount: 8 },
      { character: '拐', hanViet: 'QUẢI', onyomi: 'かい', meaningVi: 'bắt cóc, lừa gạt', strokeCount: 8 },
    ],
  },
  {
    lessonNumber: 815,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (5)',
    sortOrder: 8150,
    entries: [
      { character: '拓', hanViet: 'THÁC', onyomi: 'たく', kunyomi: 'ひら-く', meaningVi: 'khai khẩn, in rập', strokeCount: 8 },
      { character: '拙', hanViet: 'CHUYẾT', onyomi: 'せつ', kunyomi: 'つたな-い', meaningVi: 'vụng về, kém cỏi', strokeCount: 8 },
      { character: '拠', hanViet: 'CỨ', onyomi: 'きょ, こ', kunyomi: 'よ-る', meaningVi: 'căn cứ, dựa vào', strokeCount: 8 },
      { character: '拳', hanViet: 'QUYỀN', onyomi: 'けん, げん', kunyomi: 'こぶし', meaningVi: 'nắm đấm, quyền anh', strokeCount: 10 },
      { character: '拷', hanViet: 'KHẢO', onyomi: 'ごう', meaningVi: 'tra tấn, tra khảo', strokeCount: 9 },
      { character: '挑', hanViet: 'KHIÊU', onyomi: 'ちょう', kunyomi: 'いど-む', meaningVi: 'khiêu khích, thách thức', strokeCount: 9 },
      { character: '振', hanViet: 'CHẤN', onyomi: 'しん', kunyomi: 'ふ-る, ふ-れる, ふ-るう', meaningVi: 'rung lắc, chấn động', strokeCount: 10 },
      { character: '据', hanViet: 'CỨ', onyomi: 'きょ', kunyomi: 'す-える, す-わる', meaningVi: 'đặt, lắp đặt', strokeCount: 11 },
      { character: '捷', hanViet: 'TIỆP', onyomi: 'しょう, そう', kunyomi: 'はや-い', meaningVi: 'chiến thắng, nhanh nhẹn', strokeCount: 11 },
      { character: '捺', hanViet: 'NẠI', onyomi: 'なつ, だつ', kunyomi: 'さ-す, お-す', meaningVi: 'ấn, đóng dấu', strokeCount: 11 },
      { character: '掌', hanViet: 'CHƯỞNG', onyomi: 'しょう', kunyomi: 'てのひら, たなごころ', meaningVi: 'lòng bàn tay; cai quản', strokeCount: 12 },
      { character: '排', hanViet: 'BÀI', onyomi: 'はい', meaningVi: 'bài trừ, loại bỏ', strokeCount: 11 },
      { character: '描', hanViet: 'MIÊU', onyomi: 'びょう', kunyomi: 'えが-く, か-く', meaningVi: 'vẽ, miêu tả', strokeCount: 11 },
      { character: '提', hanViet: 'ĐỀ', onyomi: 'てい, ちょう, だい', kunyomi: 'さ-げる', meaningVi: 'đề xuất, xách', strokeCount: 12 },
      { character: '揚', hanViet: 'DƯƠNG', onyomi: 'よう', kunyomi: 'あ-げる, -あ-げ, あ-がる', meaningVi: 'nâng lên, phát huy', strokeCount: 12 },
      { character: '揮', hanViet: 'HUY', onyomi: 'き', kunyomi: 'ふる-う', meaningVi: 'vung, chỉ huy', strokeCount: 12 },
      { character: '携', hanViet: 'HUỀ', onyomi: 'けい', kunyomi: 'たずさ-える, たずさ-わる', meaningVi: 'mang theo, dắt tay', strokeCount: 13 },
      { character: '搾', hanViet: 'TẠC', onyomi: 'さく', kunyomi: 'しぼ-る', meaningVi: 'vắt, bóc lột', strokeCount: 13 },
      { character: '撤', hanViet: 'TRIỆT', onyomi: 'てつ', meaningVi: 'rút lui, dỡ bỏ', strokeCount: 15 },
      { character: '撮', hanViet: 'TOÁT', onyomi: 'さつ', kunyomi: 'と-る, つま-む, -ど-り', meaningVi: 'chụp ảnh, tóm lược', strokeCount: 15 },
    ],
  },
];
