// Bổ sung từ vựng N4 đợt 3 — tự soạn tay. lessonNumber 225–234.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST3_N4: JlptVocabUnit[] = [
  {
    lessonNumber: 225,
    jlptLevel: 'N4',
    words: [
      { kanji: '空港', kana: 'くうこう', romaji: 'kūkō', meaning: 'sân bay', partOfSpeech: 'danh từ' },
      { kanji: '飛行機', kana: 'ひこうき', romaji: 'hikōki', meaning: 'máy bay', partOfSpeech: 'danh từ' },
      { kanji: '新幹線', kana: 'しんかんせん', romaji: 'shinkansen', meaning: 'tàu cao tốc Shinkansen', partOfSpeech: 'danh từ' },
      { kanji: '船', kana: 'ふね', romaji: 'fune', meaning: 'tàu thuyền', partOfSpeech: 'danh từ' },
      { kanji: '切符', kana: 'きっぷ', romaji: 'kippu', meaning: 'vé (tàu, xe)', partOfSpeech: 'danh từ' },
      { kanji: '往復', kana: 'おうふく', romaji: 'ōfuku', meaning: 'khứ hồi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '片道', kana: 'かたみち', romaji: 'katamichi', meaning: 'một chiều', partOfSpeech: 'danh từ' },
      { kanji: '乗り換えます', kana: 'のりかえます', romaji: 'norikaemasu', meaning: 'chuyển tàu/xe', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '乗ります', kana: 'のります', romaji: 'norimasu', meaning: 'lên (xe, tàu)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '降ります', kana: 'おります', romaji: 'orimasu', meaning: 'xuống (xe, tàu)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '到着します', kana: 'とうちゃくします', romaji: 'tōchaku shimasu', meaning: 'đến nơi', partOfSpeech: 'động từ する' },
      { kanji: '出発します', kana: 'しゅっぱつします', romaji: 'shuppatsu shimasu', meaning: 'khởi hành', partOfSpeech: 'động từ する' },
      { kanji: '観光', kana: 'かんこう', romaji: 'kankō', meaning: 'tham quan du lịch', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '案内', kana: 'あんない', romaji: 'annai', meaning: 'hướng dẫn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '免税', kana: 'めんぜい', romaji: 'menzei', meaning: 'miễn thuế', partOfSpeech: 'danh từ' },
      { kanji: '両替', kana: 'りょうがえ', romaji: 'ryōgae', meaning: 'đổi tiền', partOfSpeech: 'danh từ, động từ する' },
      { kanji: 'パスポート', kana: 'パスポート', romaji: 'pasupōto', meaning: 'hộ chiếu', partOfSpeech: 'danh từ' },
      { kanji: 'ビザ', kana: 'ビザ', romaji: 'biza', meaning: 'thị thực (visa)', partOfSpeech: 'danh từ' },
      { kanji: '国際', kana: 'こくさい', romaji: 'kokusai', meaning: 'quốc tế', partOfSpeech: 'danh từ' },
      { kanji: '荷物', kana: 'にもつ', romaji: 'nimotsu', meaning: 'hành lý', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 226,
    jlptLevel: 'N4',
    words: [
      { kanji: '感じます', kana: 'かんじます', romaji: 'kanjimasu', meaning: 'cảm thấy', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '驚きます', kana: 'おどろきます', romaji: 'odorokimasu', meaning: 'ngạc nhiên', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '怒ります', kana: 'おこります', romaji: 'okorimasu', meaning: 'tức giận', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '泣きます', kana: 'なきます', romaji: 'nakimasu', meaning: 'khóc', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '笑います', kana: 'わらいます', romaji: 'waraimasu', meaning: 'cười', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '喜びます', kana: 'よろこびます', romaji: 'yorokobimasu', meaning: 'vui mừng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '悲しいです', kana: 'かなしいです', romaji: 'kanashii desu', meaning: 'buồn', partOfSpeech: 'tính từ i' },
      { kanji: '寂しいです', kana: 'さびしいです', romaji: 'sabishii desu', meaning: 'cô đơn', partOfSpeech: 'tính từ i' },
      { kanji: '恥ずかしいです', kana: 'はずかしいです', romaji: 'hazukashii desu', meaning: 'xấu hổ', partOfSpeech: 'tính từ i' },
      { kanji: '羨ましいです', kana: 'うらやましいです', romaji: 'urayamashii desu', meaning: 'ghen tị (đáng ao ước)', partOfSpeech: 'tính từ i' },
      { kanji: '懐かしいです', kana: 'なつかしいです', romaji: 'natsukashii desu', meaning: 'hoài niệm, nhớ nhung', partOfSpeech: 'tính từ i' },
      { kanji: '緊張します', kana: 'きんちょうします', romaji: 'kinchō shimasu', meaning: 'căng thẳng, hồi hộp', partOfSpeech: 'động từ する' },
      { kanji: '安心します', kana: 'あんしんします', romaji: 'anshin shimasu', meaning: 'yên tâm', partOfSpeech: 'động từ する' },
      { kanji: '満足します', kana: 'まんぞくします', romaji: 'manzoku shimasu', meaning: 'hài lòng', partOfSpeech: 'động từ する' },
      { kanji: '感動します', kana: 'かんどうします', romaji: 'kandō shimasu', meaning: 'cảm động', partOfSpeech: 'động từ する' },
      { kanji: '期待します', kana: 'きたいします', romaji: 'kitai shimasu', meaning: 'kỳ vọng', partOfSpeech: 'động từ する' },
      { kanji: 'がっかりします', kana: 'がっかりします', romaji: 'gakkari shimasu', meaning: 'thất vọng', partOfSpeech: 'động từ する' },
      { kanji: '興奮します', kana: 'こうふんします', romaji: 'kōfun shimasu', meaning: 'phấn khích', partOfSpeech: 'động từ する' },
      { kanji: '落ち着きます', kana: 'おちつきます', romaji: 'ochitsukimasu', meaning: 'bình tĩnh lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '心', kana: 'こころ', romaji: 'kokoro', meaning: 'trái tim, tâm hồn', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 227,
    jlptLevel: 'N4',
    words: [
      { kanji: '経済', kana: 'けいざい', romaji: 'keizai', meaning: 'kinh tế', partOfSpeech: 'danh từ' },
      { kanji: '社会', kana: 'しゃかい', romaji: 'shakai', meaning: 'xã hội', partOfSpeech: 'danh từ' },
      { kanji: '政治', kana: 'せいじ', romaji: 'seiji', meaning: 'chính trị', partOfSpeech: 'danh từ' },
      { kanji: '文化', kana: 'ぶんか', romaji: 'bunka', meaning: 'văn hóa', partOfSpeech: 'danh từ' },
      { kanji: '歴史', kana: 'れきし', romaji: 'rekishi', meaning: 'lịch sử', partOfSpeech: 'danh từ' },
      { kanji: '宗教', kana: 'しゅうきょう', romaji: 'shūkyō', meaning: 'tôn giáo', partOfSpeech: 'danh từ' },
      { kanji: '会議', kana: 'かいぎ', romaji: 'kaigi', meaning: 'cuộc họp', partOfSpeech: 'danh từ' },
      { kanji: '書類', kana: 'しょるい', romaji: 'shorui', meaning: 'giấy tờ, hồ sơ', partOfSpeech: 'danh từ' },
      { kanji: '印刷します', kana: 'いんさつします', romaji: 'insatsu shimasu', meaning: 'in ấn', partOfSpeech: 'động từ する' },
      { kanji: 'コピーします', kana: 'コピーします', romaji: 'kopī shimasu', meaning: 'photo, sao chép', partOfSpeech: 'động từ する' },
      { kanji: '署名します', kana: 'しょめいします', romaji: 'shomei shimasu', meaning: 'ký tên', partOfSpeech: 'động từ する' },
      { kanji: '印鑑', kana: 'いんかん', romaji: 'inkan', meaning: 'con dấu cá nhân', partOfSpeech: 'danh từ' },
      { kanji: '担当', kana: 'たんとう', romaji: 'tantō', meaning: 'phụ trách', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '部長', kana: 'ぶちょう', romaji: 'buchō', meaning: 'trưởng phòng', partOfSpeech: 'danh từ' },
      { kanji: '課長', kana: 'かちょう', romaji: 'kachō', meaning: 'trưởng nhóm/ban', partOfSpeech: 'danh từ' },
      { kanji: '社長', kana: 'しゃちょう', romaji: 'shachō', meaning: 'giám đốc công ty', partOfSpeech: 'danh từ' },
      { kanji: '同僚', kana: 'どうりょう', romaji: 'dōryō', meaning: 'đồng nghiệp', partOfSpeech: 'danh từ' },
      { kanji: '出張', kana: 'しゅっちょう', romaji: 'shutchō', meaning: 'đi công tác', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '残業', kana: 'ざんぎょう', romaji: 'zangyō', meaning: 'tăng ca', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '給料', kana: 'きゅうりょう', romaji: 'kyūryō', meaning: 'tiền lương', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 228,
    jlptLevel: 'N4',
    words: [
      { kanji: '育てます', kana: 'そだてます', romaji: 'sodatemasu', meaning: 'nuôi dạy', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '育児', kana: 'いくじ', romaji: 'ikuji', meaning: 'nuôi con', partOfSpeech: 'danh từ' },
      { kanji: '幼稚園', kana: 'ようちえん', romaji: 'yōchien', meaning: 'trường mẫu giáo', partOfSpeech: 'danh từ' },
      { kanji: '小学校', kana: 'しょうがっこう', romaji: 'shōgakkō', meaning: 'trường tiểu học', partOfSpeech: 'danh từ' },
      { kanji: '中学校', kana: 'ちゅうがっこう', romaji: 'chūgakkō', meaning: 'trường trung học cơ sở', partOfSpeech: 'danh từ' },
      { kanji: '高校', kana: 'こうこう', romaji: 'kōkō', meaning: 'trường trung học phổ thông', partOfSpeech: 'danh từ' },
      { kanji: '大学', kana: 'だいがく', romaji: 'daigaku', meaning: 'trường đại học', partOfSpeech: 'danh từ' },
      { kanji: '入学します', kana: 'にゅうがくします', romaji: 'nyūgaku shimasu', meaning: 'nhập học', partOfSpeech: 'động từ する' },
      { kanji: '卒業します', kana: 'そつぎょうします', romaji: 'sotsugyō shimasu', meaning: 'tốt nghiệp', partOfSpeech: 'động từ する' },
      { kanji: '試験', kana: 'しけん', romaji: 'shiken', meaning: 'kỳ thi', partOfSpeech: 'danh từ' },
      { kanji: '合格します', kana: 'ごうかくします', romaji: 'gōkaku shimasu', meaning: 'đỗ (thi)', partOfSpeech: 'động từ する' },
      { kanji: '成績', kana: 'せいせき', romaji: 'seiseki', meaning: 'thành tích học tập', partOfSpeech: 'danh từ' },
      { kanji: '宿題', kana: 'しゅくだい', romaji: 'shukudai', meaning: 'bài tập về nhà', partOfSpeech: 'danh từ' },
      { kanji: '授業', kana: 'じゅぎょう', romaji: 'jugyō', meaning: 'tiết học', partOfSpeech: 'danh từ' },
      { kanji: '先輩', kana: 'せんぱい', romaji: 'senpai', meaning: 'tiền bối, đàn anh/chị', partOfSpeech: 'danh từ' },
      { kanji: '後輩', kana: 'こうはい', romaji: 'kōhai', meaning: 'hậu bối, đàn em', partOfSpeech: 'danh từ' },
      { kanji: '同級生', kana: 'どうきゅうせい', romaji: 'dōkyūsei', meaning: 'bạn cùng lớp', partOfSpeech: 'danh từ' },
      { kanji: '部活', kana: 'ぶかつ', romaji: 'bukatsu', meaning: 'câu lạc bộ (trường học)', partOfSpeech: 'danh từ' },
      { kanji: '卒業式', kana: 'そつぎょうしき', romaji: 'sotsugyōshiki', meaning: 'lễ tốt nghiệp', partOfSpeech: 'danh từ' },
      { kanji: '入学式', kana: 'にゅうがくしき', romaji: 'nyūgakushiki', meaning: 'lễ nhập học', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 229,
    jlptLevel: 'N4',
    words: [
      { kanji: '相談します', kana: 'そうだんします', romaji: 'sōdan shimasu', meaning: 'bàn bạc, tư vấn', partOfSpeech: 'động từ する' },
      { kanji: '決めます', kana: 'きめます', romaji: 'kimemasu', meaning: 'quyết định', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '選びます', kana: 'えらびます', romaji: 'erabimasu', meaning: 'lựa chọn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '比べます', kana: 'くらべます', romaji: 'kurabemasu', meaning: 'so sánh', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '違います', kana: 'ちがいます', romaji: 'chigaimasu', meaning: 'khác nhau', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '合わせます', kana: 'あわせます', romaji: 'awasemasu', meaning: 'kết hợp, làm khớp', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '集めます', kana: 'あつめます', romaji: 'atsumemasu', meaning: 'thu thập, tập hợp', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '集まります', kana: 'あつまります', romaji: 'atsumarimasu', meaning: 'tập trung lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '分けます', kana: 'わけます', romaji: 'wakemasu', meaning: 'chia ra', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '並べます', kana: 'ならべます', romaji: 'narabemasu', meaning: 'xếp thành hàng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '並びます', kana: 'ならびます', romaji: 'narabimasu', meaning: 'xếp hàng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '整理します', kana: 'せいりします', romaji: 'seiri shimasu', meaning: 'sắp xếp gọn gàng', partOfSpeech: 'động từ する' },
      { kanji: '片付けます', kana: 'かたづけます', romaji: 'katazukemasu', meaning: 'dọn dẹp', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '準備します', kana: 'じゅんびします', romaji: 'junbi shimasu', meaning: 'chuẩn bị', partOfSpeech: 'động từ する' },
      { kanji: '用意します', kana: 'よういします', romaji: 'yōi shimasu', meaning: 'sẵn sàng, chuẩn bị', partOfSpeech: 'động từ する' },
      { kanji: '確認します', kana: 'かくにんします', romaji: 'kakunin shimasu', meaning: 'xác nhận', partOfSpeech: 'động từ する' },
      { kanji: '調べます', kana: 'しらべます', romaji: 'shirabemasu', meaning: 'điều tra, tra cứu', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '試します', kana: 'ためします', romaji: 'tameshimasu', meaning: 'thử nghiệm', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '失敗します', kana: 'しっぱいします', romaji: 'shippai shimasu', meaning: 'thất bại', partOfSpeech: 'động từ する' },
      { kanji: '成功します', kana: 'せいこうします', romaji: 'seikō shimasu', meaning: 'thành công', partOfSpeech: 'động từ する' },
    ],
  },
  {
    lessonNumber: 230,
    jlptLevel: 'N4',
    words: [
      { kanji: '道具', kana: 'どうぐ', romaji: 'dōgu', meaning: 'dụng cụ', partOfSpeech: 'danh từ' },
      { kanji: '機械', kana: 'きかい', romaji: 'kikai', meaning: 'máy móc', partOfSpeech: 'danh từ' },
      { kanji: '工場', kana: 'こうじょう', romaji: 'kōjō', meaning: 'nhà máy', partOfSpeech: 'danh từ' },
      { kanji: '製品', kana: 'せいひん', romaji: 'seihin', meaning: 'sản phẩm', partOfSpeech: 'danh từ' },
      { kanji: '材料', kana: 'ざいりょう', romaji: 'zairyō', meaning: 'nguyên liệu', partOfSpeech: 'danh từ' },
      { kanji: '作ります', kana: 'つくります', romaji: 'tsukurimasu', meaning: 'làm ra, chế tạo', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '造ります', kana: 'つくります', romaji: 'tsukurimasu', meaning: 'xây dựng, chế tạo (quy mô lớn)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '直します', kana: 'なおします', romaji: 'naoshimasu', meaning: 'sửa chữa, chỉnh sửa', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '壊します', kana: 'こわします', romaji: 'kowashimasu', meaning: 'làm hỏng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '壊れます', kana: 'こわれます', romaji: 'kowaremasu', meaning: 'bị hỏng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '動かします', kana: 'うごかします', romaji: 'ugokashimasu', meaning: 'vận hành, di chuyển (vật)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '動きます', kana: 'うごきます', romaji: 'ugokimasu', meaning: 'chuyển động', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '止めます', kana: 'とめます', romaji: 'tomemasu', meaning: 'dừng lại (tha động)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '止まります', kana: 'とまります', romaji: 'tomarimasu', meaning: 'dừng lại (tự động)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '進みます', kana: 'すすみます', romaji: 'susumimasu', meaning: 'tiến lên', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '戻ります', kana: 'もどります', romaji: 'modorimasu', meaning: 'quay trở lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '戻します', kana: 'もどします', romaji: 'modoshimasu', meaning: 'đưa trả lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '倒れます', kana: 'たおれます', romaji: 'taoremasu', meaning: 'ngã, đổ sụp', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '倒します', kana: 'たおします', romaji: 'taoshimasu', meaning: 'làm đổ, đánh gục', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '運びます', kana: 'はこびます', romaji: 'hakobimasu', meaning: 'vận chuyển', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 231,
    jlptLevel: 'N4',
    words: [
      { kanji: '不動産', kana: 'ふどうさん', romaji: 'fudōsan', meaning: 'bất động sản', partOfSpeech: 'danh từ' },
      { kanji: '家賃', kana: 'やちん', romaji: 'yachin', meaning: 'tiền thuê nhà', partOfSpeech: 'danh từ' },
      { kanji: '引っ越します', kana: 'ひっこします', romaji: 'hikkoshimasu', meaning: 'chuyển nhà', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '契約します', kana: 'けいやくします', romaji: 'keiyaku shimasu', meaning: 'ký hợp đồng', partOfSpeech: 'động từ する' },
      { kanji: '敷金', kana: 'しききん', romaji: 'shikikin', meaning: 'tiền đặt cọc thuê nhà', partOfSpeech: 'danh từ' },
      { kanji: '大家', kana: 'おおや', romaji: 'ōya', meaning: 'chủ nhà trọ', partOfSpeech: 'danh từ' },
      { kanji: 'アパート', kana: 'アパート', romaji: 'apāto', meaning: 'chung cư nhỏ', partOfSpeech: 'danh từ' },
      { kanji: 'マンション', kana: 'マンション', romaji: 'manshon', meaning: 'chung cư cao cấp', partOfSpeech: 'danh từ' },
      { kanji: '階', kana: 'かい', romaji: 'kai', meaning: 'tầng (nhà)', partOfSpeech: 'danh từ' },
      { kanji: '台所', kana: 'だいどころ', romaji: 'daidokoro', meaning: 'nhà bếp', partOfSpeech: 'danh từ' },
      { kanji: '風呂', kana: 'ふろ', romaji: 'furo', meaning: 'bồn tắm, phòng tắm', partOfSpeech: 'danh từ' },
      { kanji: 'トイレ', kana: 'トイレ', romaji: 'toire', meaning: 'nhà vệ sinh', partOfSpeech: 'danh từ' },
      { kanji: '庭', kana: 'にわ', romaji: 'niwa', meaning: 'sân vườn', partOfSpeech: 'danh từ' },
      { kanji: '駐車場', kana: 'ちゅうしゃじょう', romaji: 'chūshajō', meaning: 'bãi đỗ xe', partOfSpeech: 'danh từ' },
      { kanji: '家具', kana: 'かぐ', romaji: 'kagu', meaning: 'đồ nội thất', partOfSpeech: 'danh từ' },
      { kanji: '冷蔵庫', kana: 'れいぞうこ', romaji: 'reizōko', meaning: 'tủ lạnh', partOfSpeech: 'danh từ' },
      { kanji: '洗濯機', kana: 'せんたくき', romaji: 'sentakuki', meaning: 'máy giặt', partOfSpeech: 'danh từ' },
      { kanji: 'エアコン', kana: 'エアコン', romaji: 'eakon', meaning: 'máy điều hòa', partOfSpeech: 'danh từ' },
      { kanji: '電気代', kana: 'でんきだい', romaji: 'denkidai', meaning: 'tiền điện', partOfSpeech: 'danh từ' },
      { kanji: '水道', kana: 'すいどう', romaji: 'suidō', meaning: 'nước máy, hệ thống cấp nước', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 232,
    jlptLevel: 'N4',
    words: [
      { kanji: '性格', kana: 'せいかく', romaji: 'seikaku', meaning: 'tính cách', partOfSpeech: 'danh từ' },
      { kanji: '優しいです', kana: 'やさしいです', romaji: 'yasashii desu', meaning: 'hiền lành', partOfSpeech: 'tính từ i' },
      { kanji: '厳しいです', kana: 'きびしいです', romaji: 'kibishii desu', meaning: 'nghiêm khắc', partOfSpeech: 'tính từ i' },
      { kanji: '明るいです', kana: 'あかるいです', romaji: 'akarui desu', meaning: 'vui vẻ, tươi sáng', partOfSpeech: 'tính từ i' },
      { kanji: '暗いです', kana: 'くらいです', romaji: 'kurai desu', meaning: 'u ám, tối tăm', partOfSpeech: 'tính từ i' },
      { kanji: '正直です', kana: 'しょうじきです', romaji: 'shōjiki desu', meaning: 'thành thật', partOfSpeech: 'tính từ na' },
      { kanji: '親切です', kana: 'しんせつです', romaji: 'shinsetsu desu', meaning: 'tốt bụng', partOfSpeech: 'tính từ na' },
      { kanji: '真面目です', kana: 'まじめです', romaji: 'majime desu', meaning: 'nghiêm túc, chăm chỉ', partOfSpeech: 'tính từ na' },
      { kanji: '素直です', kana: 'すなおです', romaji: 'sunao desu', meaning: 'ngoan ngoãn', partOfSpeech: 'tính từ na' },
      { kanji: '頑固です', kana: 'がんこです', romaji: 'ganko desu', meaning: 'cố chấp', partOfSpeech: 'tính từ na' },
      { kanji: '積極的です', kana: 'せっきょくてきです', romaji: 'sekkyokuteki desu', meaning: 'tích cực', partOfSpeech: 'tính từ na' },
      { kanji: '面白いです', kana: 'おもしろいです', romaji: 'omoshiroi desu', meaning: 'thú vị', partOfSpeech: 'tính từ i' },
      { kanji: '静かです', kana: 'しずかです', romaji: 'shizuka desu', meaning: 'yên tĩnh', partOfSpeech: 'tính từ na' },
      { kanji: 'にぎやかです', kana: 'にぎやかです', romaji: 'nigiyaka desu', meaning: 'nhộn nhịp, sôi động', partOfSpeech: 'tính từ na' },
      { kanji: '優秀です', kana: 'ゆうしゅうです', romaji: 'yūshū desu', meaning: 'ưu tú, xuất sắc', partOfSpeech: 'tính từ na' },
      { kanji: '有名です', kana: 'ゆうめいです', romaji: 'yūmei desu', meaning: 'nổi tiếng', partOfSpeech: 'tính từ na' },
      { kanji: '人気', kana: 'にんき', romaji: 'ninki', meaning: 'sự nổi tiếng, được yêu thích', partOfSpeech: 'danh từ' },
      { kanji: '性別', kana: 'せいべつ', romaji: 'seibetsu', meaning: 'giới tính', partOfSpeech: 'danh từ' },
      { kanji: '年齢', kana: 'ねんれい', romaji: 'nenrei', meaning: 'độ tuổi', partOfSpeech: 'danh từ' },
      { kanji: '趣味', kana: 'しゅみ', romaji: 'shumi', meaning: 'sở thích', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 233,
    jlptLevel: 'N4',
    words: [
      { kanji: '環境', kana: 'かんきょう', romaji: 'kankyō', meaning: 'môi trường', partOfSpeech: 'danh từ' },
      { kanji: '自然', kana: 'しぜん', romaji: 'shizen', meaning: 'tự nhiên, thiên nhiên', partOfSpeech: 'danh từ' },
      { kanji: '空気', kana: 'くうき', romaji: 'kūki', meaning: 'không khí', partOfSpeech: 'danh từ' },
      { kanji: 'ごみ', kana: 'ごみ', romaji: 'gomi', meaning: 'rác', partOfSpeech: 'danh từ' },
      { kanji: '捨てます', kana: 'すてます', romaji: 'sutemasu', meaning: 'vứt bỏ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: 'リサイクルします', kana: 'リサイクルします', romaji: 'risaikuru shimasu', meaning: 'tái chế', partOfSpeech: 'động từ する' },
      { kanji: '節約します', kana: 'せつやくします', romaji: 'setsuyaku shimasu', meaning: 'tiết kiệm', partOfSpeech: 'động từ する' },
      { kanji: '汚れます', kana: 'よごれます', romaji: 'yogoremasu', meaning: 'bị bẩn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '汚します', kana: 'よごします', romaji: 'yogoshimasu', meaning: 'làm bẩn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: 'きれいです', kana: 'きれいです', romaji: 'kirei desu', meaning: 'sạch sẽ, đẹp', partOfSpeech: 'tính từ na' },
      { kanji: '地震', kana: 'じしん', romaji: 'jishin', meaning: 'động đất', partOfSpeech: 'danh từ' },
      { kanji: '台風', kana: 'たいふう', romaji: 'taifū', meaning: 'bão', partOfSpeech: 'danh từ' },
      { kanji: '洪水', kana: 'こうずい', romaji: 'kōzui', meaning: 'lũ lụt', partOfSpeech: 'danh từ' },
      { kanji: '火事', kana: 'かじ', romaji: 'kaji', meaning: 'hỏa hoạn', partOfSpeech: 'danh từ' },
      { kanji: '危険です', kana: 'きけんです', romaji: 'kiken desu', meaning: 'nguy hiểm', partOfSpeech: 'tính từ na' },
      { kanji: '安全です', kana: 'あんぜんです', romaji: 'anzen desu', meaning: 'an toàn', partOfSpeech: 'tính từ na' },
      { kanji: '避難します', kana: 'ひなんします', romaji: 'hinan shimasu', meaning: 'sơ tán', partOfSpeech: 'động từ する' },
      { kanji: '注意します', kana: 'ちゅういします', romaji: 'chūi shimasu', meaning: 'chú ý, cẩn thận', partOfSpeech: 'động từ する' },
      { kanji: '守ります', kana: 'まもります', romaji: 'mamorimasu', meaning: 'bảo vệ, tuân thủ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '温暖化', kana: 'おんだんか', romaji: 'ondanka', meaning: 'sự nóng lên (khí hậu)', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 234,
    jlptLevel: 'N4',
    words: [
      { kanji: '予定', kana: 'よてい', romaji: 'yotei', meaning: 'dự định, lịch trình', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '計画', kana: 'けいかく', romaji: 'keikaku', meaning: 'kế hoạch', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '目的', kana: 'もくてき', romaji: 'mokuteki', meaning: 'mục đích', partOfSpeech: 'danh từ' },
      { kanji: '理由', kana: 'りゆう', romaji: 'riyū', meaning: 'lý do', partOfSpeech: 'danh từ' },
      { kanji: '原因', kana: 'げんいん', romaji: 'gen\'in', meaning: 'nguyên nhân', partOfSpeech: 'danh từ' },
      { kanji: '結果', kana: 'けっか', romaji: 'kekka', meaning: 'kết quả', partOfSpeech: 'danh từ' },
      { kanji: '方法', kana: 'ほうほう', romaji: 'hōhō', meaning: 'phương pháp', partOfSpeech: 'danh từ' },
      { kanji: '機会', kana: 'きかい', romaji: 'kikai', meaning: 'cơ hội', partOfSpeech: 'danh từ' },
      { kanji: '経験', kana: 'けいけん', romaji: 'keiken', meaning: 'kinh nghiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '練習します', kana: 'れんしゅうします', romaji: 'renshū shimasu', meaning: 'luyện tập', partOfSpeech: 'động từ する' },
      { kanji: '努力します', kana: 'どりょくします', romaji: 'doryoku shimasu', meaning: 'nỗ lực', partOfSpeech: 'động từ する' },
      { kanji: '頑張ります', kana: 'がんばります', romaji: 'ganbarimasu', meaning: 'cố gắng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '諦めます', kana: 'あきらめます', romaji: 'akiramemasu', meaning: 'từ bỏ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '続けます', kana: 'つづけます', romaji: 'tsuzukemasu', meaning: 'tiếp tục', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '始めます', kana: 'はじめます', romaji: 'hajimemasu', meaning: 'bắt đầu', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '終わります', kana: 'おわります', romaji: 'owarimasu', meaning: 'kết thúc', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '完成します', kana: 'かんせいします', romaji: 'kansei shimasu', meaning: 'hoàn thành', partOfSpeech: 'động từ する' },
      { kanji: '達成します', kana: 'たっせいします', romaji: 'tassei shimasu', meaning: 'đạt được', partOfSpeech: 'động từ する' },
      { kanji: '夢', kana: 'ゆめ', romaji: 'yume', meaning: 'ước mơ', partOfSpeech: 'danh từ' },
      { kanji: '将来', kana: 'しょうらい', romaji: 'shōrai', meaning: 'tương lai', partOfSpeech: 'danh từ' },
    ],
  },
];
