// Bổ sung kanji N1 — dịch tay (Hán Việt + nghĩa Việt) dựa trên dữ liệu đọc âm
// (onyomi/kunyomi) và stroke count lấy từ kanjiapi.dev (nguồn mở), không auto-scrape nghĩa tiếng Việt.
// KanjiLesson lessonNumber 821-825.

import type { JlptKanjiLesson } from './jlpt-kanji.data';

export const JLPT_KANJI_BOOST4_N1_E: JlptKanjiLesson[] = [
  {
    lessonNumber: 821,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (1)',
    sortOrder: 8210,
    entries: [
      { character: '殉', hanViet: 'TUẪN', onyomi: 'じゅん', meaningVi: 'tuẫn tiết, hy sinh vì lý tưởng', strokeCount: 10 },
      { character: '殊', hanViet: 'THÙ', onyomi: 'しゅ', kunyomi: 'こと', meaningVi: 'đặc biệt, khác thường', strokeCount: 10 },
      { character: '殖', hanViet: 'THỰC', onyomi: 'しょく', kunyomi: 'ふ-える, ふ-やす', meaningVi: 'sinh sôi, tăng trưởng', strokeCount: 12 },
      { character: '毅', hanViet: 'NGHỊ', onyomi: 'き, ぎ', kunyomi: 'つよ-い', meaningVi: 'kiên nghị, cứng cỏi', strokeCount: 15 },
      { character: '毬', hanViet: 'CẦU', onyomi: 'きゅう', kunyomi: 'いが, まり', meaningVi: 'quả cầu, trái bóng', strokeCount: 11 },
      { character: '汁', hanViet: 'TRẤP', onyomi: 'じゅう', kunyomi: 'しる, -しる, つゆ', meaningVi: 'nước canh, nước cốt', strokeCount: 5 },
      { character: '汐', hanViet: 'TỊCH', onyomi: 'せき', kunyomi: 'しお, うしお, せい', meaningVi: 'thủy triều buổi tối', strokeCount: 6 },
      { character: '江', hanViet: 'GIANG', onyomi: 'こう', kunyomi: 'え', meaningVi: 'sông lớn, cửa sông', strokeCount: 6 },
      { character: '汰', hanViet: 'THÁI', onyomi: 'た, たい', kunyomi: 'おご-る, にご-る, よな-げる', meaningVi: 'sàng lọc, đào thải', strokeCount: 7 },
      { character: '汽', hanViet: 'KHÍ', onyomi: 'き', meaningVi: 'hơi nước', strokeCount: 7 },
      { character: '沙', hanViet: 'SA', onyomi: 'さ, しゃ', kunyomi: 'すな, よなげる', meaningVi: 'cát', strokeCount: 7 },
      { character: '没', hanViet: 'MỘT', onyomi: 'ぼつ, もつ', kunyomi: 'おぼ-れる, しず-む, ない', meaningVi: 'chìm, mất, không', strokeCount: 7 },
      { character: '沢', hanViet: 'TRẠCH', onyomi: 'たく', kunyomi: 'さわ, うるお-い, うるお-す, つや', meaningVi: 'đầm lầy; ân huệ', strokeCount: 7 },
      { character: '沼', hanViet: 'CHIỂU', onyomi: 'しょう', kunyomi: 'ぬま', meaningVi: 'đầm, ao', strokeCount: 8 },
      { character: '泌', hanViet: 'BÍ', onyomi: 'ひつ, ひ', meaningVi: 'tiết ra, thấm ra', strokeCount: 8 },
      { character: '泡', hanViet: 'BÀO', onyomi: 'ほう', kunyomi: 'あわ', meaningVi: 'bọt nước', strokeCount: 8 },
      { character: '泰', hanViet: 'THÁI', onyomi: 'たい', meaningVi: 'yên ổn, thái bình', strokeCount: 10 },
      { character: '津', hanViet: 'TÂN', onyomi: 'しん', kunyomi: 'つ', meaningVi: 'bến đò, bến cảng', strokeCount: 9 },
      { character: '洲', hanViet: 'CHÂU', onyomi: 'しゅう, す', kunyomi: 'しま', meaningVi: 'châu lục, cồn cát', strokeCount: 9 },
      { character: '派', hanViet: 'PHÁI', onyomi: 'は', meaningVi: 'phe phái', strokeCount: 9 },
    ],
  },
  {
    lessonNumber: 822,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (2)',
    sortOrder: 8220,
    entries: [
      { character: '浄', hanViet: 'TỊNH', onyomi: 'じょう, せい', kunyomi: 'きよ-める, きよ-い', meaningVi: 'trong sạch, thanh tịnh', strokeCount: 9 },
      { character: '浜', hanViet: 'TÂN', onyomi: 'ひん', kunyomi: 'はま', meaningVi: 'bờ biển', strokeCount: 10 },
      { character: '浦', hanViet: 'PHỐ', onyomi: 'ほ', kunyomi: 'うら', meaningVi: 'vũng, vịnh nhỏ', strokeCount: 10 },
      { character: '浩', hanViet: 'HẠO', onyomi: 'こう', kunyomi: 'おおき-い, ひろ-い', meaningVi: 'rộng lớn, mênh mông', strokeCount: 10 },
      { character: '浪', hanViet: 'LÃNG', onyomi: 'ろう', meaningVi: 'sóng; lang thang', strokeCount: 10 },
      { character: '淑', hanViet: 'THỤC', onyomi: 'しゅく', kunyomi: 'しと-やか', meaningVi: 'đoan trang, hiền thục', strokeCount: 11 },
      { character: '淳', hanViet: 'THUẦN', onyomi: 'じゅん, しゅん', kunyomi: 'あつ-い', meaningVi: 'thuần khiết, chân thành', strokeCount: 11 },
      { character: '渉', hanViet: 'THIỆP', onyomi: 'しょう', kunyomi: 'わた-る', meaningVi: 'lội qua, giao thiệp', strokeCount: 11 },
      { character: '渓', hanViet: 'KHÊ', onyomi: 'けい', kunyomi: 'たに, たにがわ', meaningVi: 'khe suối, thung lũng', strokeCount: 11 },
      { character: '渚', hanViet: 'CHỮ', onyomi: 'しょ', kunyomi: 'なぎさ', meaningVi: 'bãi bồi, bờ nước', strokeCount: 11 },
      { character: '湧', hanViet: 'DŨNG', onyomi: 'ゆう, よう, ゆ', kunyomi: 'わ-く', meaningVi: 'trào lên, sôi trào', strokeCount: 12 },
      { character: '溝', hanViet: 'CÂU', onyomi: 'こう', kunyomi: 'みぞ', meaningVi: 'rãnh, mương', strokeCount: 13 },
      { character: '滋', hanViet: 'TƯ', onyomi: 'じ, し', meaningVi: 'bồi bổ, tươi tốt', strokeCount: 12 },
      { character: '漂', hanViet: 'PHIÊU', onyomi: 'ひょう', kunyomi: 'ただよ-う', meaningVi: 'trôi nổi', strokeCount: 14 },
      { character: '漆', hanViet: 'TẤT', onyomi: 'しつ', kunyomi: 'うるし', meaningVi: 'sơn mài', strokeCount: 14 },
      { character: '漠', hanViet: 'MẠC', onyomi: 'ばく', meaningVi: 'sa mạc; mơ hồ', strokeCount: 13 },
      { character: '漫', hanViet: 'MẠN', onyomi: 'まん', kunyomi: 'みだり-に, そぞ-ろ', meaningVi: 'tản mạn, tự do', strokeCount: 14 },
      { character: '漱', hanViet: 'THẤU', onyomi: 'そう, しゅう, す', kunyomi: 'くちすす-ぐ, くちそそ-ぐ, うがい, すす-ぐ', meaningVi: 'súc miệng', strokeCount: 14 },
      { character: '潔', hanViet: 'KHIẾT', onyomi: 'けつ', kunyomi: 'いさぎよ-い', meaningVi: 'trong sạch, thanh khiết', strokeCount: 15 },
      { character: '潤', hanViet: 'NHUẬN', onyomi: 'じゅん', kunyomi: 'うるお-う, うるお-す, うる-む', meaningVi: 'ẩm ướt, lợi nhuận', strokeCount: 15 },
    ],
  },
  {
    lessonNumber: 823,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (3)',
    sortOrder: 8230,
    entries: [
      { character: '潮', hanViet: 'TRIỀU', onyomi: 'ちょう', kunyomi: 'しお, うしお', meaningVi: 'thủy triều', strokeCount: 15 },
      { character: '激', hanViet: 'KÍCH', onyomi: 'げき', kunyomi: 'はげ-しい', meaningVi: 'kích động, dữ dội', strokeCount: 16 },
      { character: '災', hanViet: 'TAI', onyomi: 'さい', kunyomi: 'わざわ-い', meaningVi: 'tai họa', strokeCount: 7 },
      { character: '炉', hanViet: 'LÔ', onyomi: 'ろ', kunyomi: 'いろり', meaningVi: 'lò sưởi', strokeCount: 8 },
      { character: '炊', hanViet: 'XUY', onyomi: 'すい', kunyomi: 'た-く, -だ-き', meaningVi: 'nấu cơm', strokeCount: 8 },
      { character: '炎', hanViet: 'VIÊM', onyomi: 'えん', kunyomi: 'ほのお', meaningVi: 'viêm; ngọn lửa', strokeCount: 8 },
      { character: '為', hanViet: 'VI', onyomi: 'い', kunyomi: 'ため, な-る, な-す, す-る, たり, つく-る, なり', meaningVi: 'làm, vì', strokeCount: 9 },
      { character: '烈', hanViet: 'LIỆT', onyomi: 'れつ', kunyomi: 'はげ-しい', meaningVi: 'mãnh liệt', strokeCount: 10 },
      { character: '焦', hanViet: 'TIÊU', onyomi: 'しょう', kunyomi: 'こ-げる, こ-がす, こ-がれる, あせ-る, じ-れる, じ-らす', meaningVi: 'cháy khét; sốt ruột', strokeCount: 12 },
      { character: '煮', hanViet: 'CHỬ', onyomi: 'しゃ', kunyomi: 'に-る, -に, に-える, に-やす', meaningVi: 'nấu, luộc', strokeCount: 12 },
      { character: '熊', hanViet: 'HÙNG', onyomi: 'ゆう', kunyomi: 'くま', meaningVi: 'con gấu', strokeCount: 14 },
      { character: '熟', hanViet: 'THỤC', onyomi: 'じゅく', kunyomi: 'う-れる', meaningVi: 'chín, thuần thục', strokeCount: 15 },
      { character: '爵', hanViet: 'TƯỚC', onyomi: 'しゃく', meaningVi: 'tước vị', strokeCount: 17 },
      { character: '爽', hanViet: 'SẢNG', onyomi: 'そう', kunyomi: 'あき-らか, さわ-やか, たがう', meaningVi: 'sảng khoái, rõ ràng', strokeCount: 11 },
      { character: '爾', hanViet: 'NHĨ', onyomi: 'じ, に', kunyomi: 'なんじ, しかり, その, のみ, おれ, しか', meaningVi: 'ngươi, mày (cổ)', strokeCount: 14 },
      { character: '牲', hanViet: 'SINH', onyomi: 'せい', meaningVi: 'vật hiến tế', strokeCount: 9 },
      { character: '犠', hanViet: 'HY', onyomi: 'ぎ, き', kunyomi: 'いけにえ', meaningVi: 'hy sinh', strokeCount: 17 },
      { character: '狂', hanViet: 'CUỒNG', onyomi: 'きょう', kunyomi: 'くる-う, くる-おしい, くるお-しい', meaningVi: 'điên cuồng', strokeCount: 7 },
      { character: '猛', hanViet: 'MÃNH', onyomi: 'もう', meaningVi: 'mãnh liệt, dữ tợn', strokeCount: 11 },
      { character: '猪', hanViet: 'TRỮ', onyomi: 'ちょ', kunyomi: 'い, いのしし', meaningVi: 'lợn rừng', strokeCount: 11 },
    ],
  },
  {
    lessonNumber: 824,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (4)',
    sortOrder: 8240,
    entries: [
      { character: '猶', hanViet: 'DO', onyomi: 'ゆう, ゆ', kunyomi: 'なお', meaningVi: 'còn, vẫn', strokeCount: 12 },
      { character: '猿', hanViet: 'VIÊN', onyomi: 'えん', kunyomi: 'さる', meaningVi: 'con khỉ', strokeCount: 13 },
      { character: '獄', hanViet: 'NGỤC', onyomi: 'ごく', meaningVi: 'nhà tù', strokeCount: 14 },
      { character: '獣', hanViet: 'THÚ', onyomi: 'じゅう', kunyomi: 'けもの, けだもの', meaningVi: 'dã thú', strokeCount: 16 },
      { character: '玲', hanViet: 'LINH', onyomi: 'れい', meaningVi: 'tiếng ngọc va chạm, trong trẻo', strokeCount: 9 },
      { character: '珠', hanViet: 'CHÂU', onyomi: 'しゅ', kunyomi: 'たま', meaningVi: 'hạt ngọc trai', strokeCount: 10 },
      { character: '班', hanViet: 'BAN', onyomi: 'はん', meaningVi: 'tổ, nhóm', strokeCount: 10 },
      { character: '琉', hanViet: 'LƯU', onyomi: 'りゅう, る', meaningVi: 'đá quý màu xanh (lưu ly)', strokeCount: 11 },
      { character: '琢', hanViet: 'TRÁC', onyomi: 'たく', kunyomi: 'みが-く', meaningVi: 'mài giũa (ngọc)', strokeCount: 11 },
      { character: '瑚', hanViet: 'HỒ', onyomi: 'こ, ご', meaningVi: 'san hô', strokeCount: 13 },
      { character: '瑛', hanViet: 'ANH', onyomi: 'えい', meaningVi: 'ánh sáng của ngọc', strokeCount: 12 },
      { character: '瑞', hanViet: 'THỤY', onyomi: 'ずい, すい', kunyomi: 'みず-, しるし', meaningVi: 'điềm lành', strokeCount: 13 },
      { character: '瑠', hanViet: 'LƯU', onyomi: 'る, りゅう', meaningVi: 'đá quý màu xanh (lưu ly)', strokeCount: 14 },
      { character: '瑶', hanViet: 'DAO', onyomi: 'よう', kunyomi: 'たま', meaningVi: 'ngọc đẹp', strokeCount: 13 },
      { character: '璃', hanViet: 'LY', onyomi: 'り', meaningVi: 'thủy tinh, pha lê (lưu ly)', strokeCount: 15 },
      { character: '甫', hanViet: 'PHỦ', onyomi: 'ほ, ふ', kunyomi: 'はじ-めて', meaningVi: 'lần đầu, mới bắt đầu', strokeCount: 7 },
      { character: '畔', hanViet: 'BÁN', onyomi: 'はん', kunyomi: 'あぜ, くろ, ほとり', meaningVi: 'bờ ruộng', strokeCount: 10 },
      { character: '畝', hanViet: 'MẪU', onyomi: 'ぼう, ほ, も, む', kunyomi: 'せ, うね', meaningVi: 'luống đất; đơn vị diện tích', strokeCount: 10 },
      { character: '疎', hanViet: 'SƠ', onyomi: 'そ, しょ', kunyomi: 'うと-い, うと-む, まば-ら', meaningVi: 'xa cách, thưa thớt', strokeCount: 12 },
      { character: '疾', hanViet: 'TẬT', onyomi: 'しつ', kunyomi: 'はや-い', meaningVi: 'nhanh; bệnh tật', strokeCount: 10 },
    ],
  },
  {
    lessonNumber: 825,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (5)',
    sortOrder: 8250,
    entries: [
      { character: '痘', hanViet: 'ĐẬU', onyomi: 'とう', meaningVi: 'bệnh đậu mùa', strokeCount: 12 },
      { character: '痢', hanViet: 'LỴ', onyomi: 'り', meaningVi: 'bệnh lỵ, tiêu chảy', strokeCount: 12 },
      { character: '痴', hanViet: 'SI', onyomi: 'ち', kunyomi: 'し-れる, おろか', meaningVi: 'ngu si, ngốc nghếch', strokeCount: 13 },
      { character: '癒', hanViet: 'DỤ', onyomi: 'ゆ', kunyomi: 'い-える, いや-す, い-やす', meaningVi: 'chữa lành', strokeCount: 18 },
      { character: '癖', hanViet: 'TÍCH', onyomi: 'へき', kunyomi: 'くせ, くせ-に', meaningVi: 'thói quen, tật xấu', strokeCount: 18 },
    ],
  },
];
