// Bổ sung từ vựng N3 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 300-313.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N3_PART1: JlptVocabUnit[] = [
  {
    lessonNumber: 300,
    jlptLevel: 'N3',
    words: [
      { kana: 'アイロン', romaji: 'airon', meaning: 'bàn là, bàn ủi', partOfSpeech: 'danh từ' },
      { kana: 'アウト', romaji: 'auto', meaning: 'ra ngoài, out (thể thao)', partOfSpeech: 'danh từ' },
      { kana: 'あちこち', romaji: 'achikochi', meaning: 'khắp nơi, chỗ này chỗ kia', partOfSpeech: 'danh từ, phó từ' },
      { kana: 'あっ', romaji: 'a', meaning: 'ôi! (thán từ ngạc nhiên)', partOfSpeech: 'thán từ' },
      { kana: 'あらゆる', romaji: 'arayuru', meaning: 'mọi, tất cả', partOfSpeech: 'từ hạn định' },
      { kana: 'あるいは', romaji: 'aruiha', meaning: 'hoặc là, có thể là', partOfSpeech: 'phó từ, liên từ' },
      { kana: 'あんまり', romaji: 'anmari', meaning: 'không mấy, không lắm', partOfSpeech: 'phó từ' },
      { kana: 'いけません', romaji: 'ikemasen', meaning: 'không được (làm gì), không tốt', partOfSpeech: 'cụm từ' },
      { kana: 'いずれ', romaji: 'izure', meaning: 'rồi sẽ, chẳng bao lâu nữa; cái nào', partOfSpeech: 'phó từ, đại từ' },
      { kana: 'いたずら', romaji: 'itazura', meaning: 'trò nghịch ngợm, trò đùa tai quái', partOfSpeech: 'danh từ, tính từ na' },
      { kana: 'いつまでも', romaji: 'itsumademo', meaning: 'mãi mãi, vĩnh viễn', partOfSpeech: 'phó từ' },
      { kana: 'いらいら', romaji: 'iraira', meaning: 'bực bội, khó chịu', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'インク', romaji: 'inku', meaning: 'mực (viết, in)', partOfSpeech: 'danh từ' },
      { kana: 'ウイスキー', romaji: 'uisukī', meaning: 'rượu whisky', partOfSpeech: 'danh từ' },
      { kana: 'うがい', romaji: 'ugai', meaning: 'sự súc miệng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '唸ります', kana: 'うなります', romaji: 'unarimasu', meaning: 'rên rỉ, gầm gừ', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'オーバー', romaji: 'ōbā', meaning: 'áo khoác; vượt quá', partOfSpeech: 'danh từ, tính từ na' },
    ],
  },
  {
    lessonNumber: 301,
    jlptLevel: 'N3',
    words: [
      { kana: 'おしゃべり', romaji: 'oshaberi', meaning: 'sự buôn chuyện, nói chuyện phiếm', partOfSpeech: 'danh từ, tính từ na, động từ する' },
      { kana: 'おそらく', romaji: 'osoraku', meaning: 'có lẽ, e rằng', partOfSpeech: 'phó từ' },
      { kana: 'オフィス', romaji: 'ofuぃsu', meaning: 'văn phòng', partOfSpeech: 'danh từ' },
      { kana: 'おまえ', romaji: 'omae', meaning: 'mày, cậu (cách gọi thân mật, suồng sã)', partOfSpeech: 'đại từ' },
      { kana: 'およそ', romaji: 'oyoso', meaning: 'khoảng chừng, đại khái', partOfSpeech: 'phó từ, danh từ' },
      { kanji: 'お昼', kana: 'おひる', romaji: 'ohiru', meaning: 'buổi trưa, bữa trưa', partOfSpeech: 'danh từ' },
      { kana: 'がっかり', romaji: 'gakkari', meaning: 'thất vọng, chán nản', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'かもしれません', romaji: 'kamoshiremasen', meaning: 'có lẽ, có thể', partOfSpeech: 'cụm từ' },
      { kana: 'かわいそう', romaji: 'kawaisō', meaning: 'đáng thương, tội nghiệp', partOfSpeech: 'tính từ na' },
      { kana: 'かわいらしい', romaji: 'kawairashii', meaning: 'dễ thương, đáng yêu', partOfSpeech: 'tính từ i' },
      { kana: 'きつい', romaji: 'kitsui', meaning: 'chật, khắt khe, vất vả', partOfSpeech: 'tính từ i' },
      { kana: 'ぐっすり', romaji: 'gussuri', meaning: 'ngủ say', partOfSpeech: 'phó từ' },
      { kana: 'グラス', romaji: 'gurasu', meaning: 'cốc thủy tinh', partOfSpeech: 'danh từ' },
      { kana: 'クリーム', romaji: 'kurīmu', meaning: 'kem (mỹ phẩm, thực phẩm)', partOfSpeech: 'danh từ' },
      { kana: 'ケース', romaji: 'kēsu', meaning: 'hộp đựng, trường hợp', partOfSpeech: 'danh từ' },
      { kana: 'けち', romaji: 'kechi', meaning: 'keo kiệt, bủn xỉn', partOfSpeech: 'danh từ, tính từ na' },
      { kana: 'コーチ', romaji: 'kōchi', meaning: 'huấn luyện viên', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 302,
    jlptLevel: 'N3',
    words: [
      { kana: 'コード', romaji: 'kōdo', meaning: 'mã, dây điện', partOfSpeech: 'danh từ' },
      { kana: 'ゴール', romaji: 'gōru', meaning: 'đích đến, khung thành', partOfSpeech: 'danh từ' },
      { kana: 'ごめんなさい', romaji: 'gomennasai', meaning: 'xin lỗi', partOfSpeech: 'cụm từ' },
      { kana: 'サイン', romaji: 'sain', meaning: 'chữ ký, dấu hiệu', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'ざっと', romaji: 'zatto', meaning: 'sơ qua, đại khái', partOfSpeech: 'phó từ' },
      { kana: 'さっぱり', romaji: 'sappari', meaning: 'sảng khoái, gọn gàng; hoàn toàn (không)', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'さて', romaji: 'sate', meaning: 'vậy thì, giờ thì', partOfSpeech: 'liên từ' },
      { kana: 'ジーンズ', romaji: 'jīnzu', meaning: 'quần jean', partOfSpeech: 'danh từ' },
      { kanji: 'ジェット機', kana: 'ジェットき', romaji: 'jiぇttoki', meaning: 'máy bay phản lực', partOfSpeech: 'danh từ' },
      { kana: 'しかも', romaji: 'shikamo', meaning: 'hơn nữa, vả lại', partOfSpeech: 'liên từ' },
      { kana: 'しきりに', romaji: 'shikirini', meaning: 'liên tục, không ngớt', partOfSpeech: 'phó từ' },
      { kana: 'したがって', romaji: 'shitagatte', meaning: 'do đó, vì vậy', partOfSpeech: 'liên từ' },
      { kana: 'じっと', romaji: 'jitto', meaning: 'im lặng bất động, chăm chú', partOfSpeech: 'phó từ, động từ する' },
      { kanji: 'お仕舞い', kana: 'おしまい', romaji: 'oshimai', meaning: 'sự kết thúc, hết rồi', partOfSpeech: 'danh từ' },
      { kana: 'じゃあ', romaji: 'jā', meaning: 'vậy thì, thế thì', partOfSpeech: 'liên từ' },
      { kanji: '喋ります', kana: 'しゃべります', romaji: 'shaberimasu', meaning: 'nói chuyện, tán gẫu', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'スケート', romaji: 'sukēto', meaning: 'trượt băng', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 303,
    jlptLevel: 'N3',
    words: [
      { kana: 'スタイル', romaji: 'sutairu', meaning: 'phong cách, dáng vóc', partOfSpeech: 'danh từ' },
      { kana: 'すてき', romaji: 'suteki', meaning: 'tuyệt vời, tuyệt đẹp', partOfSpeech: 'tính từ na' },
      { kana: 'すなわち', romaji: 'sunawachi', meaning: 'tức là, nghĩa là', partOfSpeech: 'liên từ' },
      { kana: 'そこで', romaji: 'sokode', meaning: 'vì thế, do đó', partOfSpeech: 'liên từ' },
      { kana: 'そっと', romaji: 'sotto', meaning: 'nhẹ nhàng, lặng lẽ', partOfSpeech: 'phó từ' },
      { kana: 'ソファー', romaji: 'sofuぁ', meaning: 'ghế sofa', partOfSpeech: 'danh từ' },
      { kana: 'それぞれ', romaji: 'sorezore', meaning: 'mỗi, từng cái một', partOfSpeech: 'danh từ, phó từ' },
      { kana: 'それとも', romaji: 'soretomo', meaning: 'hay là', partOfSpeech: 'liên từ' },
      { kana: 'タイプライター', romaji: 'taipuraitā', meaning: 'máy đánh chữ', partOfSpeech: 'danh từ' },
      { kana: 'だけど', romaji: 'dakedo', meaning: 'nhưng mà', partOfSpeech: 'liên từ' },
      { kana: 'ただ', romaji: 'tada', meaning: 'miễn phí; chỉ là', partOfSpeech: 'danh từ, phó từ' },
      { kana: 'だって', romaji: 'datte', meaning: 'nhưng mà, vì', partOfSpeech: 'liên từ' },
      { kana: 'ちょうだい', romaji: 'chōdai', meaning: 'cho tôi xin (cách nói thân mật)', partOfSpeech: 'cụm từ' },
      { kana: 'デモ', romaji: 'demo', meaning: 'cuộc biểu tình; bản demo', partOfSpeech: 'danh từ' },
      { kana: 'テント', romaji: 'tento', meaning: 'lều trại', partOfSpeech: 'danh từ' },
      { kana: 'どうか', romaji: 'dōka', meaning: 'xin hãy; bằng cách nào đó', partOfSpeech: 'phó từ' },
      { kana: 'どうしても', romaji: 'dōshitemo', meaning: 'dù thế nào cũng, nhất định', partOfSpeech: 'phó từ' },
    ],
  },
  {
    lessonNumber: 304,
    jlptLevel: 'N3',
    words: [
      { kana: 'ところが', romaji: 'tokoroga', meaning: 'thế nhưng, tuy vậy', partOfSpeech: 'liên từ' },
      { kana: 'トランプ', romaji: 'toranpu', meaning: 'bài tây (bộ bài)', partOfSpeech: 'danh từ' },
      { kana: 'ドレス', romaji: 'doresu', meaning: 'váy dạ hội', partOfSpeech: 'danh từ' },
      { kana: 'とんでもない', romaji: 'tondemonai', meaning: 'vô lý, không ngờ tới, đâu có chuyện đó', partOfSpeech: 'tính từ i' },
      { kana: 'どんなに', romaji: 'donnani', meaning: 'dù thế nào, cho dù', partOfSpeech: 'phó từ' },
      { kana: 'トンネル', romaji: 'tonneru', meaning: 'đường hầm', partOfSpeech: 'danh từ' },
      { kana: 'なお', romaji: 'nao', meaning: 'hơn nữa, ngoài ra; vẫn còn', partOfSpeech: 'liên từ, phó từ' },
      { kana: 'なぜなら', romaji: 'nazenara', meaning: 'bởi vì', partOfSpeech: 'liên từ' },
      { kana: 'なにも', romaji: 'nanimo', meaning: 'không gì cả (đi với phủ định)', partOfSpeech: 'phó từ' },
      { kana: 'にっこり', romaji: 'nikkori', meaning: 'mỉm cười', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'のんびり', romaji: 'nonbiri', meaning: 'thong thả, nhàn nhã', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'バイオリン', romaji: 'baiorin', meaning: 'đàn violin', partOfSpeech: 'danh từ' },
      { kana: 'ばったり', romaji: 'battari', meaning: 'bất chợt (gặp); đột ngột (dừng)', partOfSpeech: 'phó từ' },
      { kana: 'ハンサム', romaji: 'hansamu', meaning: 'đẹp trai', partOfSpeech: 'tính từ na' },
      { kana: 'ピクニック', romaji: 'pikunikku', meaning: 'buổi dã ngoại', partOfSpeech: 'danh từ' },
      { kana: 'びっくり', romaji: 'bikkuri', meaning: 'giật mình, ngạc nhiên', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'ふと', romaji: 'futo', meaning: 'bỗng nhiên, tình cờ', partOfSpeech: 'phó từ' },
    ],
  },
  {
    lessonNumber: 305,
    jlptLevel: 'N3',
    words: [
      { kana: 'プラン', romaji: 'puran', meaning: 'kế hoạch, dự định', partOfSpeech: 'danh từ' },
      { kana: 'ブレーキ', romaji: 'burēki', meaning: 'cái phanh', partOfSpeech: 'danh từ' },
      { kana: 'プロ', romaji: 'puro', meaning: 'chuyên nghiệp', partOfSpeech: 'danh từ' },
      { kana: 'ベルト', romaji: 'beruto', meaning: 'thắt lưng, dây đai', partOfSpeech: 'danh từ' },
      { kana: 'ペンキ', romaji: 'penki', meaning: 'sơn (dùng để quét)', partOfSpeech: 'danh từ' },
      { kana: 'ベンチ', romaji: 'benchi', meaning: 'ghế băng dài', partOfSpeech: 'danh từ' },
      { kana: 'ホーム', romaji: 'hōmu', meaning: 'sân ga; mái ấm', partOfSpeech: 'danh từ' },
      { kana: 'ほぼ', romaji: 'hobo', meaning: 'hầu như, gần như', partOfSpeech: 'phó từ' },
      { kana: 'ぼんやり', romaji: 'bonyari', meaning: 'lơ đãng, mờ mịt', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'まあ', romaji: 'mā', meaning: 'thôi thì, chậc (thán từ nhẹ nhàng)', partOfSpeech: 'thán từ' },
      { kana: 'マイク', romaji: 'maiku', meaning: 'micro', partOfSpeech: 'danh từ' },
      { kana: 'まさに', romaji: 'masani', meaning: 'đúng là, chính xác là', partOfSpeech: 'phó từ' },
      { kana: 'マスター', romaji: 'masutā', meaning: 'chủ quán, người thành thạo', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'ますます', romaji: 'masumasu', meaning: 'ngày càng, càng thêm', partOfSpeech: 'phó từ' },
      { kana: 'まるで', romaji: 'marude', meaning: 'cứ như là, hoàn toàn (giống)', partOfSpeech: 'phó từ' },
      { kana: 'ミス', romaji: 'misu', meaning: 'sai sót, lỗi', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'メモ', romaji: 'memo', meaning: 'ghi chú, giấy nhớ', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 306,
    jlptLevel: 'N3',
    words: [
      { kana: 'メンバー', romaji: 'menbā', meaning: 'thành viên', partOfSpeech: 'danh từ' },
      { kana: 'もしも', romaji: 'moshimo', meaning: 'nếu như, giả sử', partOfSpeech: 'phó từ' },
      { kana: 'やがて', romaji: 'yagate', meaning: 'chẳng bao lâu, rồi thì', partOfSpeech: 'phó từ' },
      { kana: 'やはり', romaji: 'yahari', meaning: 'quả nhiên, vẫn là, đúng như dự đoán', partOfSpeech: 'phó từ' },
      { kana: 'やや', romaji: 'yaya', meaning: 'hơi, một chút', partOfSpeech: 'phó từ' },
      { kana: 'ヨット', romaji: 'yotto', meaning: 'du thuyền buồm', partOfSpeech: 'danh từ' },
      { kana: 'よろしく', romaji: 'yoroshiku', meaning: 'xin gửi lời chào, mong được giúp đỡ', partOfSpeech: 'cụm từ' },
      { kana: 'ライター', romaji: 'raitā', meaning: 'bật lửa; người viết', partOfSpeech: 'danh từ' },
      { kana: 'ラケット', romaji: 'raketto', meaning: 'vợt (tennis, cầu lông)', partOfSpeech: 'danh từ' },
      { kana: 'ロケット', romaji: 'roketto', meaning: 'tên lửa', partOfSpeech: 'danh từ' },
      { kana: 'わがまま', romaji: 'wagamama', meaning: 'ích kỷ, bướng bỉnh, làm theo ý mình', partOfSpeech: 'danh từ, tính từ na' },
      { kana: 'わざと', romaji: 'wazato', meaning: 'cố ý, cố tình', partOfSpeech: 'phó từ' },
      { kanji: '哀れ', kana: 'あわれ', romaji: 'aware', meaning: 'đáng thương, thương xót', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '愛', kana: 'あい', romaji: 'ai', meaning: 'tình yêu', partOfSpeech: 'danh từ' },
      { kanji: '愛します', kana: 'あいします', romaji: 'aishimasu', meaning: 'yêu', partOfSpeech: 'động từ する' },
      { kanji: '愛情', kana: 'あいじょう', romaji: 'aijō', meaning: 'tình yêu thương', partOfSpeech: 'danh từ' },
      { kanji: '悪口', kana: 'わるくち', romaji: 'warukuchi', meaning: 'lời nói xấu, chửi rủa', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 307,
    jlptLevel: 'N3',
    words: [
      { kanji: '悪魔', kana: 'あくま', romaji: 'akuma', meaning: 'ác quỷ, quỷ dữ', partOfSpeech: 'danh từ' },
      { kanji: '握ります', kana: 'にぎります', romaji: 'nigirimasu', meaning: 'nắm, cầm chặt; nặn (sushi)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '握手', kana: 'あくしゅ', romaji: 'akushu', meaning: 'cái bắt tay', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '扱います', kana: 'あつかいます', romaji: 'atsukaimasu', meaning: 'xử lý, đối xử', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '安定', kana: 'あんてい', romaji: 'antei', meaning: 'sự ổn định', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '暗記', kana: 'あんき', romaji: 'anki', meaning: 'sự học thuộc lòng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '案', kana: 'あん', romaji: 'an', meaning: 'phương án, ý kiến', partOfSpeech: 'danh từ' },
      { kanji: '以前', kana: 'いぜん', romaji: 'izen', meaning: 'trước đây, trước kia', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '偉大', kana: 'いだい', romaji: 'idai', meaning: 'vĩ đại', partOfSpeech: 'tính từ na' },
      { kanji: '囲みます', kana: 'かこみます', romaji: 'kakomimasu', meaning: 'bao quanh, vây quanh', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '委員', kana: 'いいん', romaji: 'iin', meaning: 'ủy viên, thành viên ủy ban', partOfSpeech: 'danh từ' },
      { kanji: '異なります', kana: 'ことなります', romaji: 'kotonarimasu', meaning: 'khác nhau, khác biệt', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '移動', kana: 'いどう', romaji: 'idō', meaning: 'sự di chuyển', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '衣服', kana: 'いふく', romaji: 'ifuku', meaning: 'y phục, quần áo', partOfSpeech: 'danh từ' },
      { kanji: '違い', kana: 'ちがい', romaji: 'chigai', meaning: 'sự khác biệt', partOfSpeech: 'danh từ' },
      { kanji: '違いない', kana: 'ちがいない', romaji: 'chigainai', meaning: 'chắc chắn là, không nghi ngờ gì', partOfSpeech: 'cụm từ' },
      { kanji: '一家', kana: 'いっか', romaji: 'ikka', meaning: 'một nhà, một gia đình', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 308,
    jlptLevel: 'N3',
    words: [
      { kanji: '一時', kana: 'いちじ', romaji: 'ichiji', meaning: 'một thời điểm, tạm thời', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '一種', kana: 'いっしゅ', romaji: 'isshu', meaning: 'một loại, một kiểu', partOfSpeech: 'danh từ' },
      { kanji: '一瞬', kana: 'いっしゅん', romaji: 'isshun', meaning: 'một khoảnh khắc', partOfSpeech: 'danh từ' },
      { kanji: '一人一人', kana: 'ひとりひとり', romaji: 'hitorihitori', meaning: 'từng người một', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '一層', kana: 'いっそう', romaji: 'issō', meaning: 'càng thêm, hơn nữa', partOfSpeech: 'phó từ' },
      { kanji: '一度に', kana: 'いちどに', romaji: 'ichidoni', meaning: 'cùng một lúc', partOfSpeech: 'phó từ' },
      { kanji: '一般', kana: 'いっぱん', romaji: 'ippan', meaning: 'thông thường, phổ biến', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '稲', kana: 'いね', romaji: 'ine', meaning: 'cây lúa', partOfSpeech: 'danh từ' },
      { kanji: '印', kana: 'しるし', romaji: 'shirushi', meaning: 'dấu hiệu, ký hiệu', partOfSpeech: 'danh từ' },
      { kanji: '印刷', kana: 'いんさつ', romaji: 'insatsu', meaning: 'sự in ấn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '引っ張ります', kana: 'ひっぱります', romaji: 'hipparimasu', meaning: 'kéo, lôi kéo', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '引退', kana: 'いんたい', romaji: 'intai', meaning: 'sự nghỉ hưu, giải nghệ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '引用', kana: 'いんよう', romaji: 'inyō', meaning: 'sự trích dẫn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '隠します', kana: 'かくします', romaji: 'kakushimasu', meaning: 'giấu, che giấu', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '隠れます', kana: 'かくれます', romaji: 'kakuremasu', meaning: 'trốn, ẩn nấp', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '噂', kana: 'うわさ', romaji: 'uwasa', meaning: 'lời đồn, tin đồn', partOfSpeech: 'danh từ' },
      { kanji: '永遠', kana: 'えいえん', romaji: 'eien', meaning: 'vĩnh viễn, vĩnh cửu', partOfSpeech: 'danh từ, tính từ na' },
    ],
  },
  {
    lessonNumber: 309,
    jlptLevel: 'N3',
    words: [
      { kanji: '永久', kana: 'えいきゅう', romaji: 'eikyū', meaning: 'vĩnh cửu, lâu dài', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '泳ぎ', kana: 'およぎ', romaji: 'oyogi', meaning: 'sự bơi lội', partOfSpeech: 'danh từ' },
      { kanji: '衛星', kana: 'えいせい', romaji: 'eisei', meaning: 'vệ tinh', partOfSpeech: 'danh từ' },
      { kanji: '鋭い', kana: 'するどい', romaji: 'surudoi', meaning: 'sắc bén, nhạy bén', partOfSpeech: 'tính từ i' },
      { kanji: '越えます', kana: 'こえます', romaji: 'koemasu', meaning: 'vượt qua, băng qua', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '越します', kana: 'こします', romaji: 'koshimasu', meaning: 'vượt qua, chuyển nhà (引っ越す)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '演奏', kana: 'えんそう', romaji: 'ensō', meaning: 'sự biểu diễn (nhạc cụ)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '炎', kana: 'ほのお', romaji: 'honō', meaning: 'ngọn lửa', partOfSpeech: 'danh từ' },
      { kanji: '縁', kana: 'ふち', romaji: 'fuchi', meaning: 'mép, viền, rìa', partOfSpeech: 'danh từ' },
      { kanji: '応じます', kana: 'おうじます', romaji: 'ōjimasu', meaning: 'đáp ứng, tương ứng với', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '横切ります', kana: 'よこぎります', romaji: 'yokogirimasu', meaning: 'băng qua, cắt ngang', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '横断', kana: 'おうだん', romaji: 'ōdan', meaning: 'sự băng qua, cắt ngang', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '王', kana: 'おう', romaji: 'ō', meaning: 'vua', partOfSpeech: 'danh từ' },
      { kanji: '王子', kana: 'おうじ', romaji: 'ōji', meaning: 'hoàng tử', partOfSpeech: 'danh từ' },
      { kanji: '王様', kana: 'おうさま', romaji: 'ōsama', meaning: 'đức vua (cách gọi kính trọng)', partOfSpeech: 'danh từ' },
      { kanji: '沖', kana: 'おき', romaji: 'oki', meaning: 'ngoài khơi', partOfSpeech: 'danh từ' },
      { kanji: '屋根', kana: 'やね', romaji: 'yane', meaning: 'mái nhà', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 310,
    jlptLevel: 'N3',
    words: [
      { kanji: '恩', kana: 'おん', romaji: 'on', meaning: 'ơn, ân huệ', partOfSpeech: 'danh từ' },
      { kanji: '温暖', kana: 'おんだん', romaji: 'ondan', meaning: 'ấm áp (khí hậu)', partOfSpeech: 'tính từ na' },
      { kanji: '穏やか', kana: 'おだやか', romaji: 'odayaka', meaning: 'êm dịu, ôn hòa', partOfSpeech: 'tính từ na' },
      { kanji: '下り', kana: 'くだり', romaji: 'kudari', meaning: 'chiều xuống, tàu đi xuống (rời trung tâm)', partOfSpeech: 'danh từ' },
      { kanji: '何で', kana: 'なんで', romaji: 'nande', meaning: 'tại sao, vì lý do gì', partOfSpeech: 'phó từ' },
      { kanji: '何とか', kana: 'なんとか', romaji: 'nantoka', meaning: 'bằng cách nào đó', partOfSpeech: 'phó từ' },
      { kanji: '加えます', kana: 'くわえます', romaji: 'kuwaemasu', meaning: 'thêm vào, cộng thêm', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '加わります', kana: 'くわわります', romaji: 'kuwawarimasu', meaning: 'tham gia, gia nhập', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '加減', kana: 'かげん', romaji: 'kagen', meaning: 'mức độ, tình trạng', partOfSpeech: 'danh từ' },
      { kanji: '可能', kana: 'かのう', romaji: 'kanō', meaning: 'có thể, khả thi', partOfSpeech: 'tính từ na' },
      { kanji: '嫁', kana: 'よめ', romaji: 'yome', meaning: 'con dâu, cô dâu', partOfSpeech: 'danh từ' },
      { kanji: '科目', kana: 'かもく', romaji: 'kamoku', meaning: 'môn học', partOfSpeech: 'danh từ' },
      { kanji: '火災', kana: 'かさい', romaji: 'kasai', meaning: 'hỏa hoạn', partOfSpeech: 'danh từ' },
      { kanji: '稼ぎます', kana: 'かせぎます', romaji: 'kasegimasu', meaning: 'kiếm tiền', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '画家', kana: 'がか', romaji: 'gaka', meaning: 'họa sĩ', partOfSpeech: 'danh từ' },
      { kanji: '会計', kana: 'かいけい', romaji: 'kaikei', meaning: 'kế toán, thanh toán', partOfSpeech: 'danh từ' },
      { kanji: '会合', kana: 'かいごう', romaji: 'kaigō', meaning: 'cuộc họp mặt', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 311,
    jlptLevel: 'N3',
    words: [
      { kanji: '解きます', kana: 'ときます', romaji: 'tokimasu', meaning: 'giải (bài toán), cởi (nút thắt)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '解けます', kana: 'とけます', romaji: 'tokemasu', meaning: 'được giải, được tháo ra', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '回復', kana: 'かいふく', romaji: 'kaifuku', meaning: 'sự hồi phục', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '快適', kana: 'かいてき', romaji: 'kaiteki', meaning: 'thoải mái, dễ chịu', partOfSpeech: 'tính từ na' },
      { kanji: '絵画', kana: 'かいが', romaji: 'kaiga', meaning: 'tranh vẽ, hội họa', partOfSpeech: 'danh từ' },
      { kanji: '開始', kana: 'かいし', romaji: 'kaishi', meaning: 'sự bắt đầu, khởi đầu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '外します', kana: 'はずします', romaji: 'hazushimasu', meaning: 'tháo ra, bỏ ra', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '外交', kana: 'がいこう', romaji: 'gaikō', meaning: 'ngoại giao', partOfSpeech: 'danh từ' },
      { kanji: '外出', kana: 'がいしゅつ', romaji: 'gaishutsu', meaning: 'sự ra ngoài', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '害', kana: 'がい', romaji: 'gai', meaning: 'sự gây hại, tác hại', partOfSpeech: 'danh từ' },
      { kanji: '拡大', kana: 'かくだい', romaji: 'kakudai', meaning: 'sự phóng to, mở rộng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '確実', kana: 'かくじつ', romaji: 'kakujitsu', meaning: 'chắc chắn, xác thực', partOfSpeech: 'tính từ na' },
      { kanji: '覚まします', kana: 'さまします', romaji: 'samashimasu', meaning: 'đánh thức, làm tỉnh', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '覚めます', kana: 'さめます', romaji: 'samemasu', meaning: 'tỉnh giấc, tỉnh táo lại', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '学', kana: 'がく', romaji: 'gaku', meaning: 'sự học vấn, kiến thức', partOfSpeech: 'danh từ' },
      { kanji: '学びます', kana: 'まなびます', romaji: 'manabimasu', meaning: 'học tập, học hỏi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '学期', kana: 'がっき', romaji: 'gakki', meaning: 'học kỳ', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 312,
    jlptLevel: 'N3',
    words: [
      { kanji: '学者', kana: 'がくしゃ', romaji: 'gakusha', meaning: 'học giả', partOfSpeech: 'danh từ' },
      { kanji: '学習', kana: 'がくしゅう', romaji: 'gakushū', meaning: 'sự học tập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '楽', kana: 'らく', romaji: 'raku', meaning: 'sự thoải mái, nhàn hạ', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '活気', kana: 'かっき', romaji: 'kakki', meaning: 'sự sôi động, sức sống', partOfSpeech: 'danh từ' },
      { kanji: '活用', kana: 'かつよう', romaji: 'katsuyō', meaning: 'sự vận dụng, biến đổi (ngữ pháp)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '株', kana: 'かぶ', romaji: 'kabu', meaning: 'cổ phiếu; gốc cây', partOfSpeech: 'danh từ' },
      { kanji: '勘定', kana: 'かんじょう', romaji: 'kanjō', meaning: 'sự tính toán, thanh toán tiền', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '勧めます', kana: 'すすめます', romaji: 'susumemasu', meaning: 'khuyên, đề nghị', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '完全', kana: 'かんぜん', romaji: 'kanzen', meaning: 'hoàn toàn, hoàn hảo', partOfSpeech: 'tính từ na' },
      { kanji: '患者', kana: 'かんじゃ', romaji: 'kanja', meaning: 'bệnh nhân', partOfSpeech: 'danh từ' },
      { kanji: '感覚', kana: 'かんかく', romaji: 'kankaku', meaning: 'cảm giác, giác quan', partOfSpeech: 'danh từ' },
      { kanji: '感謝', kana: 'かんしゃ', romaji: 'kansha', meaning: 'lòng biết ơn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '歓迎', kana: 'かんげい', romaji: 'kangei', meaning: 'sự chào đón, hoan nghênh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '管', kana: 'くだ', romaji: 'kuda', meaning: 'ống, ống dẫn', partOfSpeech: 'danh từ' },
      { kanji: '間', kana: 'ま', romaji: 'ma', meaning: 'khoảng cách, khoảng thời gian', partOfSpeech: 'danh từ' },
      { kanji: '関します', kana: 'かんします', romaji: 'kanshimasu', meaning: 'liên quan đến', partOfSpeech: 'động từ する' },
      { kanji: '含みます', kana: 'ふくみます', romaji: 'fukumimasu', meaning: 'bao gồm, chứa đựng', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 313,
    jlptLevel: 'N3',
    words: [
      { kanji: '岸', kana: 'きし', romaji: 'kishi', meaning: 'bờ (sông, biển)', partOfSpeech: 'danh từ' },
      { kanji: '岩', kana: 'いわ', romaji: 'iwa', meaning: 'tảng đá', partOfSpeech: 'danh từ' },
      { kanji: '願い', kana: 'ねがい', romaji: 'negai', meaning: 'ước nguyện, lời thỉnh cầu', partOfSpeech: 'danh từ' },
      { kanji: '願います', kana: 'ねがいます', romaji: 'negaimasu', meaning: 'mong muốn, thỉnh cầu', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '企業', kana: 'きぎょう', romaji: 'kigyō', meaning: 'doanh nghiệp', partOfSpeech: 'danh từ' },
      { kanji: '器用', kana: 'きよう', romaji: 'kiyō', meaning: 'khéo tay', partOfSpeech: 'tính từ na' },
      { kanji: '基', kana: 'もと', romaji: 'moto', meaning: 'cơ sở, nền tảng', partOfSpeech: 'danh từ' },
      { kanji: '基づきます', kana: 'もとづきます', romaji: 'motozukimasu', meaning: 'dựa trên, căn cứ vào', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '奇妙', kana: 'きみょう', romaji: 'kimyō', meaning: 'kỳ lạ, kỳ quái', partOfSpeech: 'tính từ na' },
      { kanji: '旗', kana: 'はた', romaji: 'hata', meaning: 'lá cờ', partOfSpeech: 'danh từ' },
      { kanji: '既に', kana: 'すでに', romaji: 'sudeni', meaning: 'đã, rồi (nhấn mạnh việc đã xảy ra)', partOfSpeech: 'phó từ' },
      { kanji: '期待', kana: 'きたい', romaji: 'kitai', meaning: 'sự mong đợi, kỳ vọng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '帰宅', kana: 'きたく', romaji: 'kitaku', meaning: 'sự về nhà', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '気に入ります', kana: 'きにいります', romaji: 'kiniirimasu', meaning: 'vừa ý, ưng ý', partOfSpeech: 'cụm động từ' },
      { kanji: '気の毒', kana: 'きのどく', romaji: 'kinodoku', meaning: 'đáng thương, tội nghiệp', partOfSpeech: 'tính từ na' },
      { kanji: '気付きます', kana: 'きづきます', romaji: 'kizukimasu', meaning: 'nhận ra, để ý thấy', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
];
