// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 989-994.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART16: JlptVocabUnit[] = [
  {
    lessonNumber: 989,
    jlptLevel: 'N1',
    words: [
      { kanji: '退治', kana: 'たいじ', romaji: 'taiji', meaning: 'sự tiêu diệt, trừ khử', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '代わる代わる', kana: 'かわるがわる', romaji: 'kawarugawaru', meaning: 'thay phiên nhau', partOfSpeech: 'phó từ' },
      { kanji: '代弁', kana: 'だいべん', romaji: 'daiben', meaning: 'sự nói thay, thanh toán thay', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '代用', kana: 'だいよう', romaji: 'daiyō', meaning: 'sự thay thế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '台無し', kana: 'だいなし', romaji: 'dainashi', meaning: 'hỏng bét, tan tành', partOfSpeech: 'danh từ' },
      { kanji: '大げさ', kana: 'おおげさ', romaji: 'ōgesa', meaning: 'phóng đại, cường điệu', partOfSpeech: 'tính từ na' },
      { kanji: '大概', kana: 'たいがい', romaji: 'taigai', meaning: 'phần lớn, đại khái', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '大筋', kana: 'おおすじ', romaji: 'ōsuji', meaning: 'đại cương, nét chính', partOfSpeech: 'danh từ' },
      { kanji: '大金', kana: 'たいきん', romaji: 'taikin', meaning: 'số tiền lớn', partOfSpeech: 'danh từ' },
      { kanji: '大空', kana: 'おおぞら', romaji: 'ōzora', meaning: 'bầu trời rộng lớn', partOfSpeech: 'danh từ' },
      { kanji: '大事', kana: 'おおごと', romaji: 'ōgoto', meaning: 'chuyện to tát, sự việc nghiêm trọng', partOfSpeech: 'danh từ' },
      { kanji: '大水', kana: 'おおみず', romaji: 'ōmizu', meaning: 'lũ lụt', partOfSpeech: 'danh từ' },
      { kanji: '大部', kana: 'たいぶ', romaji: 'taibu', meaning: 'phần lớn, đa phần', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '大柄', kana: 'おおがら', romaji: 'ōgara', meaning: 'vóc dáng to lớn; hoa văn to', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '大方', kana: 'おおかた', romaji: 'ōkata', meaning: 'phần lớn, gần như', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '濯ぎます', kana: 'すすぎます', romaji: 'susugimasu', meaning: 'tráng, giặt xả', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '達者', kana: 'たっしゃ', romaji: 'tassha', meaning: 'giỏi, khỏe mạnh', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 990,
    jlptLevel: 'N1',
    words: [
      { kanji: '脱します', kana: 'だっします', romaji: 'dasshimasu', meaning: 'thoát khỏi, ra khỏi', partOfSpeech: 'động từ する' },
      { kanji: '脱出', kana: 'だっしゅつ', romaji: 'dasshutsu', meaning: 'sự thoát ra', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '脱退', kana: 'だったい', romaji: 'dattai', meaning: 'sự rút lui, ly khai', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '辿り着きます', kana: 'たどりつきます', romaji: 'tadoritsukimasu', meaning: 'lần mò đến được, đạt tới sau gian nan', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '辿ります', kana: 'たどります', romaji: 'tadorimasu', meaning: 'lần theo, dõi theo (dấu vết)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '単', kana: 'ひとえ', romaji: 'hitoe', meaning: 'một lớp, đơn giản', partOfSpeech: 'danh từ' },
      { kanji: '単一', kana: 'たんいつ', romaji: 'tanitsu', meaning: 'đơn nhất, đơn lẻ', partOfSpeech: 'tính từ na' },
      { kanji: '単調', kana: 'たんちょう', romaji: 'tanchō', meaning: 'đơn điệu, nhàm chán', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '単独', kana: 'たんどく', romaji: 'tandoku', meaning: 'đơn độc, riêng lẻ', partOfSpeech: 'danh từ' },
      { kanji: '嘆きます', kana: 'なげきます', romaji: 'nagekimasu', meaning: 'than thở, than khóc', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '担います', kana: 'にないます', romaji: 'ninaimasu', meaning: 'gánh vác, đảm nhận', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '担架', kana: 'たんか', romaji: 'tanka', meaning: 'cáng cứu thương', partOfSpeech: 'danh từ' },
      { kanji: '探検', kana: 'たんけん', romaji: 'tanken', meaning: 'sự thám hiểm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '旦那', kana: 'だんな', romaji: 'danna', meaning: 'ông chủ; chồng (thân mật)', partOfSpeech: 'danh từ' },
      { kanji: '炭素', kana: 'たんそ', romaji: 'tanso', meaning: 'cacbon', partOfSpeech: 'danh từ' },
      { kanji: '短気', kana: 'たんき', romaji: 'tanki', meaning: 'nóng tính', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '短大', kana: 'たんだい', romaji: 'tandai', meaning: 'trường cao đẳng (2 năm)', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 991,
    jlptLevel: 'N1',
    words: [
      { kanji: '短波', kana: 'たんぱ', romaji: 'tanpa', meaning: 'sóng ngắn', partOfSpeech: 'danh từ' },
      { kanji: '綻びます', kana: 'ほころびます', romaji: 'hokorobimasu', meaning: 'sổ chỉ, bung ra; nở hé (hoa)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '蛋白質', kana: 'たんぱくしつ', romaji: 'tanpakushitsu', meaning: 'chất đạm, protein', partOfSpeech: 'danh từ' },
      { kanji: '鍛えます', kana: 'きたえます', romaji: 'kitaemasu', meaning: 'tôi luyện, rèn luyện', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '団扇', kana: 'うちわ', romaji: 'uchiwa', meaning: 'quạt tay (không xếp)', partOfSpeech: 'danh từ' },
      { kanji: '弾きます', kana: 'はじきます', romaji: 'hajikimasu', meaning: 'búng, bật ra', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '弾みます', kana: 'はずみます', romaji: 'hazumimasu', meaning: 'nảy lên, hào hứng lên', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '弾力', kana: 'だんりょく', romaji: 'danryoku', meaning: 'độ đàn hồi, sự linh hoạt', partOfSpeech: 'danh từ' },
      { kanji: '断言', kana: 'だんげん', romaji: 'dangen', meaning: 'lời khẳng định chắc chắn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '断然', kana: 'だんぜん', romaji: 'danzen', meaning: 'kiên quyết, dứt khoát', partOfSpeech: 'phó từ' },
      { kanji: '断面', kana: 'だんめん', romaji: 'danmen', meaning: 'mặt cắt ngang', partOfSpeech: 'danh từ' },
      { kanji: '値', kana: 'あたい', romaji: 'atai', meaning: 'giá trị, giá cả', partOfSpeech: 'danh từ' },
      { kanji: '値します', kana: 'あたいします', romaji: 'ataishimasu', meaning: 'xứng đáng, đáng giá', partOfSpeech: 'động từ する' },
      { kanji: '値引き', kana: 'ねびき', romaji: 'nebiki', meaning: 'sự giảm giá', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '値打ち', kana: 'ねうち', romaji: 'neuchi', meaning: 'giá trị', partOfSpeech: 'danh từ' },
      { kanji: '知り合い', kana: 'しりあい', romaji: 'shiriai', meaning: 'người quen', partOfSpeech: 'danh từ' },
      { kanji: '知性', kana: 'ちせい', romaji: 'chisei', meaning: 'trí tuệ', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 992,
    jlptLevel: 'N1',
    words: [
      { kanji: '知的', kana: 'ちてき', romaji: 'chiteki', meaning: 'trí tuệ, tri thức', partOfSpeech: 'tính từ na' },
      { kanji: '地元', kana: 'じもと', romaji: 'jimoto', meaning: 'địa phương sở tại', partOfSpeech: 'danh từ' },
      { kanji: '地獄', kana: 'じごく', romaji: 'jigoku', meaning: 'địa ngục', partOfSpeech: 'danh từ' },
      { kanji: '地主', kana: 'じぬし', romaji: 'jinushi', meaning: 'địa chủ', partOfSpeech: 'danh từ' },
      { kanji: '地方', kana: 'じかた', romaji: 'jikata', meaning: 'vùng nông thôn (đối lập thành thị)', partOfSpeech: 'danh từ' },
      { kanji: '弛み', kana: 'たるみ', romaji: 'tarumi', meaning: 'sự chùng, chảy xệ', partOfSpeech: 'danh từ' },
      { kanji: '弛みます', kana: 'たるみます', romaji: 'tarumimasu', meaning: 'chùng xuống, lơi lỏng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '恥', kana: 'はじ', romaji: 'haji', meaning: 'sự xấu hổ', partOfSpeech: 'danh từ' },
      { kanji: '恥じらいます', kana: 'はじらいます', romaji: 'hajiraimasu', meaning: 'e thẹn, ngượng ngùng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '恥じます', kana: 'はじます', romaji: 'hajimasu', meaning: 'cảm thấy xấu hổ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '遅くとも', kana: 'おそくとも', romaji: 'osokutomo', meaning: 'chậm nhất là', partOfSpeech: 'phó từ' },
      { kanji: '遅らします', kana: 'おくらします', romaji: 'okurashimasu', meaning: 'làm chậm trễ, hoãn lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '遅れ', kana: 'おくれ', romaji: 'okure', meaning: 'sự chậm trễ', partOfSpeech: 'danh từ' },
      { kanji: '築きます', kana: 'きずきます', romaji: 'kizukimasu', meaning: 'xây dựng, gây dựng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '畜産', kana: 'ちくさん', romaji: 'chikusan', meaning: 'chăn nuôi gia súc', partOfSpeech: 'danh từ' },
      { kanji: '畜生', kana: 'ちくしょう', romaji: 'chikushō', meaning: 'súc vật; chết tiệt (chửi thề)', partOfSpeech: 'danh từ' },
      { kanji: '蓄積', kana: 'ちくせき', romaji: 'chikuseki', meaning: 'sự tích lũy', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 993,
    jlptLevel: 'N1',
    words: [
      { kanji: '秩序', kana: 'ちつじょ', romaji: 'chitsujo', meaning: 'trật tự', partOfSpeech: 'danh từ' },
      { kanji: '窒息', kana: 'ちっそく', romaji: 'chissoku', meaning: 'sự ngạt thở', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '茶の間', kana: 'ちゃのま', romaji: 'chanoma', meaning: 'phòng sinh hoạt chung kiểu Nhật', partOfSpeech: 'danh từ' },
      { kanji: '茶の湯', kana: 'ちゃのゆ', romaji: 'chanoyu', meaning: 'trà đạo', partOfSpeech: 'danh từ' },
      { kanji: '着工', kana: 'ちゃっこう', romaji: 'chakkō', meaning: 'sự khởi công', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '着飾ります', kana: 'きかざります', romaji: 'kikazarimasu', meaning: 'ăn diện, chưng diện', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '着色', kana: 'ちゃくしょく', romaji: 'chakushoku', meaning: 'sự tô màu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '着席', kana: 'ちゃくせき', romaji: 'chakuseki', meaning: 'sự ngồi vào chỗ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '着目', kana: 'ちゃくもく', romaji: 'chakumoku', meaning: 'sự chú ý tới', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '着陸', kana: 'ちゃくりく', romaji: 'chakuriku', meaning: 'sự hạ cánh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '中継', kana: 'ちゅうけい', romaji: 'chūkei', meaning: 'sự tiếp sóng, trung chuyển', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '中枢', kana: 'ちゅうすう', romaji: 'chūsū', meaning: 'trung khu, hạt nhân trung tâm', partOfSpeech: 'danh từ' },
      { kanji: '中程', kana: 'なかほど', romaji: 'nakahodo', meaning: 'khoảng giữa', partOfSpeech: 'danh từ' },
      { kanji: '中毒', kana: 'ちゅうどく', romaji: 'chūdoku', meaning: 'sự ngộ độc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '中腹', kana: 'ちゅうふく', romaji: 'chūfuku', meaning: 'lưng chừng núi', partOfSpeech: 'danh từ' },
      { kanji: '中立', kana: 'ちゅうりつ', romaji: 'chūritsu', meaning: 'tính trung lập', partOfSpeech: 'danh từ' },
      { kanji: '中和', kana: 'ちゅうわ', romaji: 'chūwa', meaning: 'sự trung hòa', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 994,
    jlptLevel: 'N1',
    words: [
      { kanji: '仲人', kana: 'なこうど', romaji: 'nakōdo', meaning: 'người mai mối', partOfSpeech: 'danh từ' },
      { kanji: '宙返り', kana: 'ちゅうがえり', romaji: 'chūgaeri', meaning: 'cú lộn nhào', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '忠告', kana: 'ちゅうこく', romaji: 'chūkoku', meaning: 'lời khuyên can', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '抽選', kana: 'ちゅうせん', romaji: 'chūsen', meaning: 'sự rút thăm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '昼飯', kana: 'ちゅうはん', romaji: 'chūhan', meaning: 'bữa trưa (cách nói trang trọng)', partOfSpeech: 'danh từ' },
      { kanji: '柱', kana: 'はしら', romaji: 'hashira', meaning: 'cột trụ', partOfSpeech: 'danh từ' },
      { kanji: '著書', kana: 'ちょしょ', romaji: 'chosho', meaning: 'tác phẩm, sách đã viết', partOfSpeech: 'danh từ' },
      { kanji: '著名', kana: 'ちょめい', romaji: 'chomei', meaning: 'nổi tiếng', partOfSpeech: 'tính từ na' },
      { kanji: '丁目', kana: 'ちょうめ', romaji: 'chōme', meaning: 'khu phố (đơn vị địa chỉ)', partOfSpeech: 'danh từ' },
      { kanji: '帳', kana: 'とばり', romaji: 'tobari', meaning: 'màn che, bức màn', partOfSpeech: 'danh từ' },
      { kanji: '庁', kana: 'ちょう', romaji: 'chō', meaning: 'cục, sở (cơ quan chính phủ)', partOfSpeech: 'danh từ' },
    ],
  },
];
