// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 1019-1024.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART21: JlptVocabUnit[] = [
  {
    lessonNumber: 1019,
    jlptLevel: 'N1',
    words: [
      { kanji: '保ちます', kana: 'たもちます', romaji: 'tamochimasu', meaning: 'duy trì, giữ vững', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '保育', kana: 'ほいく', romaji: 'hoiku', meaning: 'sự nuôi dạy trẻ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '保温', kana: 'ほおん', romaji: 'hōn', meaning: 'sự giữ nhiệt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '保管', kana: 'ほかん', romaji: 'hokan', meaning: 'sự bảo quản, cất giữ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '保養', kana: 'ほよう', romaji: 'hoyō', meaning: 'sự dưỡng sức, nghỉ dưỡng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '舗装', kana: 'ほそう', romaji: 'hosō', meaning: 'sự trải nhựa đường', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '捕獲', kana: 'ほかく', romaji: 'hokaku', meaning: 'sự bắt giữ, săn bắt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '捕鯨', kana: 'ほげい', romaji: 'hogei', meaning: 'săn bắt cá voi', partOfSpeech: 'danh từ' },
      { kanji: '捕虜', kana: 'ほりょ', romaji: 'horyo', meaning: 'tù binh', partOfSpeech: 'danh từ' },
      { kanji: '歩み', kana: 'あゆみ', romaji: 'ayumi', meaning: 'bước đi, tiến trình', partOfSpeech: 'danh từ' },
      { kanji: '歩みます', kana: 'あゆみます', romaji: 'ayumimasu', meaning: 'bước đi, tiến bước', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '補給', kana: 'ほきゅう', romaji: 'hokyū', meaning: 'sự tiếp tế, bổ sung', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '補強', kana: 'ほきょう', romaji: 'hokyō', meaning: 'sự gia cố, tăng cường', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '補充', kana: 'ほじゅう', romaji: 'hojū', meaning: 'sự bổ sung', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '補助', kana: 'ほじょ', romaji: 'hojo', meaning: 'sự hỗ trợ, trợ giúp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '補足', kana: 'ほそく', romaji: 'hosoku', meaning: 'sự bổ khuyết, phần bổ sung', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '穂', kana: 'ほ', romaji: 'ho', meaning: 'bông lúa', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 1020,
    jlptLevel: 'N1',
    words: [
      { kanji: '募ります', kana: 'つのります', romaji: 'tsunorimasu', meaning: 'kêu gọi, chiêu mộ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '墓地', kana: 'ぼち', romaji: 'bochi', meaning: 'nghĩa trang', partOfSpeech: 'danh từ' },
      { kanji: '慕います', kana: 'したいます', romaji: 'shitaimasu', meaning: 'kính mến, ngưỡng mộ, nhớ nhung', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '母校', kana: 'ぼこう', romaji: 'bokō', meaning: 'trường cũ', partOfSpeech: 'danh từ' },
      { kanji: '呆気ない', kana: 'あっけない', romaji: 'akkenai', meaning: 'quá ngắn ngủi, chóng vánh', partOfSpeech: 'tính từ i' },
      { kanji: '呆然', kana: 'ぼうぜん', romaji: 'bōzen', meaning: 'sững sờ, ngơ ngác', partOfSpeech: 'tính từ na' },
      { kanji: '報じます', kana: 'ほうじます', romaji: 'hōjimasu', meaning: 'đưa tin, báo cáo', partOfSpeech: 'động từ する' },
      { kanji: '報酬', kana: 'ほうしゅう', romaji: 'hōshū', meaning: 'tiền thù lao', partOfSpeech: 'danh từ' },
      { kanji: '奉ります', kana: 'たてまつります', romaji: 'tatematsurimasu', meaning: 'dâng lên, kính tặng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '奉仕', kana: 'ほうし', romaji: 'hōshi', meaning: 'sự phục vụ, cống hiến', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '峰', kana: 'みね', romaji: 'mine', meaning: 'đỉnh núi', partOfSpeech: 'danh từ' },
      { kanji: '捧げます', kana: 'ささげます', romaji: 'sasagemasu', meaning: 'dâng hiến, cống hiến', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '放り込みます', kana: 'ほうりこみます', romaji: 'hōrikomimasu', meaning: 'ném vào, quẳng vào', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '放り出します', kana: 'ほうりだします', romaji: 'hōridashimasu', meaning: 'vứt bỏ, tống ra', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '放射', kana: 'ほうしゃ', romaji: 'hōsha', meaning: 'sự bức xạ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '放射能', kana: 'ほうしゃのう', romaji: 'hōshanō', meaning: 'chất phóng xạ', partOfSpeech: 'danh từ' },
      { kanji: '放出', kana: 'ほうしゅつ', romaji: 'hōshutsu', meaning: 'sự phát ra, giải phóng', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 1021,
    jlptLevel: 'N1',
    words: [
      { kanji: '放置', kana: 'ほうち', romaji: 'hōchi', meaning: 'sự bỏ mặc, để yên', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '方式', kana: 'ほうしき', romaji: 'hōshiki', meaning: 'phương thức', partOfSpeech: 'danh từ' },
      { kanji: '法案', kana: 'ほうあん', romaji: 'hōan', meaning: 'dự luật', partOfSpeech: 'danh từ' },
      { kanji: '法学', kana: 'ほうがく', romaji: 'hōgaku', meaning: 'luật học', partOfSpeech: 'danh từ' },
      { kanji: '法廷', kana: 'ほうてい', romaji: 'hōtei', meaning: 'tòa án', partOfSpeech: 'danh từ' },
      { kanji: '蜂蜜', kana: 'はちみつ', romaji: 'hachimitsu', meaning: 'mật ong', partOfSpeech: 'danh từ' },
      { kanji: '褒美', kana: 'ほうび', romaji: 'hōbi', meaning: 'phần thưởng', partOfSpeech: 'danh từ' },
      { kanji: '訪れます', kana: 'おとずれます', romaji: 'otozuremasu', meaning: 'ghé thăm', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '飽和', kana: 'ほうわ', romaji: 'hōwa', meaning: 'sự bão hòa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '乏しい', kana: 'とぼしい', romaji: 'toboshii', meaning: 'thiếu thốn, khan hiếm', partOfSpeech: 'tính từ i' },
      { kanji: '傍ら', kana: 'かたわら', romaji: 'katawara', meaning: 'bên cạnh; trong lúc', partOfSpeech: 'danh từ' },
      { kanji: '坊ちゃん', kana: 'ぼっちゃん', romaji: 'bocchan', meaning: 'cậu ấm (con trai nhà người khác)', partOfSpeech: 'danh từ' },
      { kanji: '暴動', kana: 'ぼうどう', romaji: 'bōdō', meaning: 'cuộc bạo động', partOfSpeech: 'danh từ' },
      { kanji: '暴風', kana: 'ぼうふう', romaji: 'bōfū', meaning: 'bão lớn', partOfSpeech: 'danh từ' },
      { kanji: '暴力', kana: 'ぼうりょく', romaji: 'bōryoku', meaning: 'bạo lực', partOfSpeech: 'danh từ' },
      { kanji: '望ましい', kana: 'のぞましい', romaji: 'nozomashii', meaning: 'đáng mong đợi, lý tưởng', partOfSpeech: 'tính từ i' },
      { kanji: '冒頭', kana: 'ぼうとう', romaji: 'bōtō', meaning: 'phần mở đầu', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 1022,
    jlptLevel: 'N1',
    words: [
      { kanji: '紡績', kana: 'ぼうせき', romaji: 'bōseki', meaning: 'ngành kéo sợi, dệt may', partOfSpeech: 'danh từ' },
      { kanji: '膨れます', kana: 'ふくれます', romaji: 'fukuremasu', meaning: 'phồng lên, sưng lên; hờn dỗi', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '防衛', kana: 'ぼうえい', romaji: 'bōei', meaning: 'sự phòng vệ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '防火', kana: 'ぼうか', romaji: 'bōka', meaning: 'sự phòng cháy', partOfSpeech: 'danh từ' },
      { kanji: '頬っぺた', kana: 'ほっぺた', romaji: 'hoppeta', meaning: 'má (cách nói thân mật)', partOfSpeech: 'danh từ' },
      { kanji: '僕', kana: 'しもべ', romaji: 'shimobe', meaning: 'kẻ tôi tớ, đầy tớ', partOfSpeech: 'danh từ' },
      { kanji: '牧師', kana: 'ぼくし', romaji: 'bokushi', meaning: 'mục sư', partOfSpeech: 'danh từ' },
      { kanji: '没収', kana: 'ぼっしゅう', romaji: 'bosshū', meaning: 'sự tịch thu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '本の', kana: 'ほんの', romaji: 'honno', meaning: 'chỉ là, một chút', partOfSpeech: 'từ hạn định' },
      { kanji: '本格', kana: 'ほんかく', romaji: 'honkaku', meaning: 'chính thống, đúng bài bản', partOfSpeech: 'danh từ' },
      { kanji: '本館', kana: 'ほんかん', romaji: 'honkan', meaning: 'tòa nhà chính', partOfSpeech: 'danh từ' },
      { kanji: '本場', kana: 'ほんば', romaji: 'honba', meaning: 'nơi chính gốc, xuất xứ đích thực', partOfSpeech: 'danh từ' },
      { kanji: '本体', kana: 'ほんたい', romaji: 'hontai', meaning: 'bản thể, phần chính (máy móc)', partOfSpeech: 'danh từ' },
      { kanji: '本文', kana: 'ほんぶん', romaji: 'honbun', meaning: 'nội dung chính (văn bản)', partOfSpeech: 'danh từ' },
      { kanji: '本名', kana: 'ほんみょう', romaji: 'honmyō', meaning: 'tên thật', partOfSpeech: 'danh từ' },
      { kanji: '麻酔', kana: 'ますい', romaji: 'masui', meaning: 'sự gây mê', partOfSpeech: 'danh từ' },
      { kanji: '麻痺', kana: 'まひ', romaji: 'mahi', meaning: 'sự tê liệt', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 1023,
    jlptLevel: 'N1',
    words: [
      { kanji: '埋まります', kana: 'うずまります', romaji: 'uzumarimasu', meaning: 'bị vùi lấp, được lấp đầy', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '埋め込みます', kana: 'うめこみます', romaji: 'umekomimasu', meaning: 'chôn sâu, nhúng vào', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '埋蔵', kana: 'まいぞう', romaji: 'maizō', meaning: 'sự chôn giấu, trữ lượng (khoáng sản)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '枚', kana: 'まい', romaji: 'mai', meaning: 'tờ, tấm (đơn vị đếm vật phẳng)', partOfSpeech: 'danh từ' },
      { kanji: '毎', kana: 'ごと', romaji: 'goto', meaning: 'mỗi, cứ mỗi', partOfSpeech: 'hậu tố' },
      { kanji: '末期', kana: 'まっき', romaji: 'makki', meaning: 'giai đoạn cuối', partOfSpeech: 'danh từ' },
      { kanji: '万人', kana: 'ばんじん', romaji: 'banjin', meaning: 'mọi người, tất cả mọi người', partOfSpeech: 'danh từ' },
      { kanji: '万能', kana: 'ばんのう', romaji: 'bannō', meaning: 'vạn năng, toàn năng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '満たします', kana: 'みたします', romaji: 'mitashimasu', meaning: 'làm thỏa mãn, lấp đầy', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '満月', kana: 'まんげつ', romaji: 'mangetsu', meaning: 'trăng tròn', partOfSpeech: 'danh từ' },
      { kanji: '満場', kana: 'まんじょう', romaji: 'manjō', meaning: 'toàn thể hội trường, nhất trí', partOfSpeech: 'danh từ' },
      { kanji: '味わい', kana: 'あじわい', romaji: 'ajiwai', meaning: 'hương vị, ý vị', partOfSpeech: 'danh từ' },
      { kanji: '味覚', kana: 'みかく', romaji: 'mikaku', meaning: 'vị giác', partOfSpeech: 'danh từ' },
      { kanji: '未', kana: 'ひつじ', romaji: 'hitsuji', meaning: 'năm Mùi (12 con giáp)', partOfSpeech: 'danh từ' },
      { kanji: '未だ', kana: 'いまだ', romaji: 'imada', meaning: 'vẫn chưa (đi với phủ định)', partOfSpeech: 'phó từ' },
      { kanji: '未開', kana: 'みかい', romaji: 'mikai', meaning: 'chưa khai hóa, hoang sơ', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '未婚', kana: 'みこん', romaji: 'mikon', meaning: 'chưa kết hôn', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 1024,
    jlptLevel: 'N1',
    words: [
      { kanji: '未定', kana: 'みてい', romaji: 'mitei', meaning: 'chưa quyết định', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '密か', kana: 'ひそか', romaji: 'hisoka', meaning: 'âm thầm, bí mật', partOfSpeech: 'tính từ na' },
      { kanji: '密集', kana: 'みっしゅう', romaji: 'misshū', meaning: 'sự tập trung dày đặc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '密接', kana: 'みっせつ', romaji: 'missetsu', meaning: 'liên quan mật thiết', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '密度', kana: 'みつど', romaji: 'mitsudo', meaning: 'mật độ', partOfSpeech: 'danh từ' },
      { kanji: '脈', kana: 'みゃく', romaji: 'myaku', meaning: 'mạch (đập)', partOfSpeech: 'danh từ' },
      { kanji: '民宿', kana: 'みんしゅく', romaji: 'minshuku', meaning: 'nhà nghỉ tư nhân', partOfSpeech: 'danh từ' },
      { kanji: '民俗', kana: 'みんぞく', romaji: 'minzoku', meaning: 'phong tục dân gian', partOfSpeech: 'danh từ' },
      { kanji: '眠たい', kana: 'ねむたい', romaji: 'nemutai', meaning: 'buồn ngủ', partOfSpeech: 'tính từ i' },
      { kanji: '無闇に', kana: 'むやみに', romaji: 'muyamini', meaning: 'bừa bãi, vô cớ', partOfSpeech: 'phó từ' },
      { kanji: '無意味', kana: 'むいみ', romaji: 'muimi', meaning: 'vô nghĩa', partOfSpeech: 'danh từ, tính từ na' },
    ],
  },
];
