// Bổ sung kanji N1 — dịch tay (Hán Việt + nghĩa Việt) dựa trên dữ liệu đọc âm
// (onyomi/kunyomi) và stroke count lấy từ kanjiapi.dev (nguồn mở), không auto-scrape nghĩa tiếng Việt.
// KanjiLesson lessonNumber 826-830.

import type { JlptKanjiLesson } from './jlpt-kanji.data';

export const JLPT_KANJI_BOOST4_N1_F: JlptKanjiLesson[] = [
  {
    lessonNumber: 826,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (1)',
    sortOrder: 8260,
    entries: [
      { character: '皓', hanViet: 'HẠO', onyomi: 'こう', kunyomi: 'しろ-い, ひか-る', meaningVi: 'trắng, sáng', strokeCount: 12 },
      { character: '盆', hanViet: 'BỒN', onyomi: 'ぼん', meaningVi: 'chậu, khay; lễ Vu Lan', strokeCount: 9 },
      { character: '盟', hanViet: 'MINH', onyomi: 'めい', meaningVi: 'đồng minh, thề nguyền', strokeCount: 13 },
      { character: '盤', hanViet: 'BÀN', onyomi: 'ばん', meaningVi: 'mâm, khay; bàn cờ', strokeCount: 15 },
      { character: '盲', hanViet: 'MANH', onyomi: 'もう', kunyomi: 'めくら', meaningVi: 'mù, mù quáng', strokeCount: 8 },
      { character: '眉', hanViet: 'MI', onyomi: 'び, み', kunyomi: 'まゆ', meaningVi: 'lông mày', strokeCount: 9 },
      { character: '看', hanViet: 'KHÁN', onyomi: 'かん', kunyomi: 'み-る', meaningVi: 'xem, trông coi', strokeCount: 9 },
      { character: '眸', hanViet: 'MÂU', onyomi: 'ぼう, む', kunyomi: 'ひとみ', meaningVi: 'con ngươi mắt', strokeCount: 11 },
      { character: '眺', hanViet: 'THIẾU', onyomi: 'ちょう', kunyomi: 'なが-める', meaningVi: 'nhìn ngắm', strokeCount: 11 },
      { character: '眼', hanViet: 'NHÃN', onyomi: 'がん, げん', kunyomi: 'まなこ, め', meaningVi: 'con mắt', strokeCount: 11 },
      { character: '睡', hanViet: 'THỤY', onyomi: 'すい', kunyomi: 'ねむ-る, ねむ-い', meaningVi: 'ngủ, buồn ngủ', strokeCount: 13 },
      { character: '睦', hanViet: 'MỤC', onyomi: 'ぼく, もく', kunyomi: 'むつ-まじい, むつ-む, むつ-ぶ', meaningVi: 'hòa thuận, thân thiết', strokeCount: 13 },
      { character: '瞳', hanViet: 'ĐỒNG', onyomi: 'どう, とう', kunyomi: 'ひとみ', meaningVi: 'con ngươi mắt', strokeCount: 17 },
      { character: '矛', hanViet: 'MÂU', onyomi: 'む, ぼう', kunyomi: 'ほこ', meaningVi: 'cây giáo; mâu thuẫn', strokeCount: 5 },
      { character: '硝', hanViet: 'TIÊU', onyomi: 'しょう', meaningVi: 'diêm tiêu', strokeCount: 12 },
      { character: '硫', hanViet: 'LƯU', onyomi: 'りゅう', meaningVi: 'lưu huỳnh', strokeCount: 12 },
      { character: '碁', hanViet: 'KỲ', onyomi: 'ご', meaningVi: 'cờ vây', strokeCount: 13 },
      { character: '碑', hanViet: 'BI', onyomi: 'ひ', kunyomi: 'いしぶみ', meaningVi: 'bia đá', strokeCount: 14 },
      { character: '碧', hanViet: 'BÍCH', onyomi: 'へき, ひゃく', meaningVi: 'xanh biếc', strokeCount: 14 },
      { character: '碩', hanViet: 'THẠC', onyomi: 'せき', kunyomi: 'おお-きい', meaningVi: 'to lớn, uyên bác', strokeCount: 14 },
    ],
  },
  {
    lessonNumber: 827,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (2)',
    sortOrder: 8270,
    entries: [
      { character: '磁', hanViet: 'TỪ', onyomi: 'じ', meaningVi: 'từ tính; đồ sứ', strokeCount: 14 },
      { character: '礁', hanViet: 'TIÊU', onyomi: 'しょう', meaningVi: 'đá ngầm', strokeCount: 17 },
      { character: '礎', hanViet: 'SỞ', onyomi: 'そ', kunyomi: 'いしずえ', meaningVi: 'nền móng', strokeCount: 18 },
      { character: '祉', hanViet: 'CHỈ', onyomi: 'し', meaningVi: 'phúc lợi, hạnh phúc', strokeCount: 8 },
      { character: '祐', hanViet: 'HỰU', onyomi: 'ゆう, う', kunyomi: 'たす-ける', meaningVi: 'giúp đỡ, phù hộ', strokeCount: 9 },
      { character: '祥', hanViet: 'TƯỜNG', onyomi: 'しょう', kunyomi: 'さいわ-い, きざ-し, よ-い, つまび-らか', meaningVi: 'điềm lành', strokeCount: 10 },
      { character: '禄', hanViet: 'LỘC', onyomi: 'ろく', kunyomi: 'さいわ-い, ふち', meaningVi: 'bổng lộc', strokeCount: 12 },
      { character: '禅', hanViet: 'THIỀN', onyomi: 'ぜん, せん', kunyomi: 'しずか, ゆず-る', meaningVi: 'thiền định', strokeCount: 13 },
      { character: '禍', hanViet: 'HỌA', onyomi: 'か', kunyomi: 'わざわい', meaningVi: 'tai họa', strokeCount: 13 },
      { character: '秀', hanViet: 'TÚ', onyomi: 'しゅう', kunyomi: 'ひい-でる', meaningVi: 'tú lệ, xuất sắc', strokeCount: 7 },
      { character: '租', hanViet: 'TÔ', onyomi: 'そ', meaningVi: 'thuế, thuê', strokeCount: 10 },
      { character: '秦', hanViet: 'TẦN', onyomi: 'しん', kunyomi: 'はた', meaningVi: 'nước Tần (Trung Quốc cổ)', strokeCount: 10 },
      { character: '秩', hanViet: 'TRẬT', onyomi: 'ちつ', meaningVi: 'trật tự, thứ bậc', strokeCount: 10 },
      { character: '稀', hanViet: 'HY', onyomi: 'き, け', kunyomi: 'まれ, まばら', meaningVi: 'hiếm, hy hữu', strokeCount: 12 },
      { character: '稚', hanViet: 'TRĨ', onyomi: 'ち, じ', kunyomi: 'いとけない, おさない, おくて, おでる', meaningVi: 'ấu trĩ, non nớt', strokeCount: 13 },
      { character: '稜', hanViet: 'LĂNG', onyomi: 'りょう, ろう', kunyomi: 'いつ, かど', meaningVi: 'góc cạnh, uy quyền', strokeCount: 13 },
      { character: '稼', hanViet: 'GIÁ', onyomi: 'か', kunyomi: 'かせ-ぐ', meaningVi: 'kiếm tiền, làm việc', strokeCount: 15 },
      { character: '稿', hanViet: 'CẢO', onyomi: 'こう', kunyomi: 'わら, したがき', meaningVi: 'bản thảo', strokeCount: 15 },
      { character: '穏', hanViet: 'ỔN', onyomi: 'おん', kunyomi: 'おだ-やか', meaningVi: 'ổn định, yên bình', strokeCount: 16 },
      { character: '窃', hanViet: 'THIẾT', onyomi: 'せつ', kunyomi: 'ぬす-む, ひそ-か', meaningVi: 'trộm cắp, lén lút', strokeCount: 9 },
    ],
  },
  {
    lessonNumber: 828,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (3)',
    sortOrder: 8280,
    entries: [
      { character: '窒', hanViet: 'CHẤT', onyomi: 'ちつ', meaningVi: 'nghẽn, tắc', strokeCount: 11 },
      { character: '窯', hanViet: 'DIÊU', onyomi: 'よう', kunyomi: 'かま', meaningVi: 'lò nung gốm', strokeCount: 15 },
      { character: '竜', hanViet: 'LONG', onyomi: 'りゅう, りょう, ろう', kunyomi: 'たつ, いせ', meaningVi: 'rồng', strokeCount: 10 },
      { character: '笙', hanViet: 'SANH', onyomi: 'しょう, そう', kunyomi: 'ふえ', meaningVi: 'kèn sênh (nhạc cụ)', strokeCount: 11 },
      { character: '笛', hanViet: 'ĐỊCH', onyomi: 'てき', kunyomi: 'ふえ', meaningVi: 'cây sáo', strokeCount: 11 },
      { character: '第', hanViet: 'ĐỆ', onyomi: 'だい, てい', meaningVi: 'thứ tự; dinh thự', strokeCount: 11 },
      { character: '箇', hanViet: 'CÁ', onyomi: 'か, こ', meaningVi: 'cái, đơn vị đếm', strokeCount: 14 },
      { character: '節', hanViet: 'TIẾT', onyomi: 'せつ, せち', kunyomi: 'ふし, -ぶし, のっと', meaningVi: 'mắt tre; tiết, mùa', strokeCount: 13 },
      { character: '篤', hanViet: 'ĐỐC', onyomi: 'とく', kunyomi: 'あつ-い', meaningVi: 'chân thành; nặng (bệnh)', strokeCount: 16 },
      { character: '簿', hanViet: 'BẠ', onyomi: 'ぼ', meaningVi: 'sổ sách', strokeCount: 19 },
      { character: '粘', hanViet: 'NIÊM', onyomi: 'ねん', kunyomi: 'ねば-る', meaningVi: 'dính, kết dính', strokeCount: 11 },
      { character: '糖', hanViet: 'ĐƯỜNG', onyomi: 'とう', meaningVi: 'đường (thực phẩm)', strokeCount: 16 },
      { character: '系', hanViet: 'HỆ', onyomi: 'けい', meaningVi: 'hệ thống, dòng dõi', strokeCount: 7 },
      { character: '糾', hanViet: 'CỨU', onyomi: 'きゅう', kunyomi: 'ただ-す', meaningVi: 'xoắn lại; điều tra', strokeCount: 9 },
      { character: '紀', hanViet: 'KỶ', onyomi: 'き', meaningVi: 'kỷ nguyên, ghi chép', strokeCount: 9 },
      { character: '紋', hanViet: 'VĂN', onyomi: 'もん', meaningVi: 'hoa văn, gia huy', strokeCount: 10 },
      { character: '納', hanViet: 'NẠP', onyomi: 'のう, なっ, な, なん, とう', kunyomi: 'おさ-める, -おさ-める, おさ-まる', meaningVi: 'nộp, thu nhận', strokeCount: 10 },
      { character: '紗', hanViet: 'SA', onyomi: 'さ, しゃ', kunyomi: 'うすぎぬ', meaningVi: 'vải sa, the mỏng', strokeCount: 10 },
      { character: '級', hanViet: 'CẤP', onyomi: 'きゅう', meaningVi: 'lớp, cấp bậc', strokeCount: 9 },
      { character: '素', hanViet: 'TỐ', onyomi: 'そ, す', kunyomi: 'もと', meaningVi: 'yếu tố; mộc mạc', strokeCount: 10 },
    ],
  },
  {
    lessonNumber: 829,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (4)',
    sortOrder: 8290,
    entries: [
      { character: '紡', hanViet: 'PHỎNG', onyomi: 'ぼう', kunyomi: 'つむ-ぐ', meaningVi: 'kéo sợi, dệt vải', strokeCount: 10 },
      { character: '紫', hanViet: 'TỬ', onyomi: 'し', kunyomi: 'むらさき', meaningVi: 'màu tím', strokeCount: 12 },
      { character: '紳', hanViet: 'THÂN', onyomi: 'しん', meaningVi: 'quý ông (thân sĩ)', strokeCount: 11 },
      { character: '絃', hanViet: 'HUYỀN', onyomi: 'げん', kunyomi: 'いと', meaningVi: 'dây đàn', strokeCount: 11 },
      { character: '絞', hanViet: 'GIẢO', onyomi: 'こう', kunyomi: 'しぼ-る, し-める, し-まる', meaningVi: 'siết, thắt', strokeCount: 12 },
      { character: '絹', hanViet: 'QUYÊN', onyomi: 'けん', kunyomi: 'きぬ', meaningVi: 'lụa', strokeCount: 13 },
      { character: '綱', hanViet: 'CƯƠNG', onyomi: 'こう', kunyomi: 'つな', meaningVi: 'giường mối, kỷ cương; dây thừng lớn', strokeCount: 14 },
      { character: '綸', hanViet: 'LUÂN', onyomi: 'りん, かん', kunyomi: 'いと', meaningVi: 'sợi tơ, chỉ lụa', strokeCount: 14 },
      { character: '綺', hanViet: 'KỲ', onyomi: 'き', kunyomi: 'あや', meaningVi: 'vải gấm đẹp', strokeCount: 14 },
      { character: '綾', hanViet: 'LĂNG', onyomi: 'りん', kunyomi: 'あや', meaningVi: 'lụa hoa văn', strokeCount: 14 },
      { character: '緋', hanViet: 'PHI', onyomi: 'ひ', kunyomi: 'あけ, あか', meaningVi: 'màu đỏ tươi', strokeCount: 14 },
      { character: '緯', hanViet: 'VĨ', onyomi: 'い', kunyomi: 'よこいと, ぬき', meaningVi: 'vĩ tuyến; sợi ngang', strokeCount: 16 },
      { character: '縁', hanViet: 'DUYÊN', onyomi: 'えん, -ねん', kunyomi: 'ふち, ふち-どる, ゆかり, よすが, へり, えにし', meaningVi: 'duyên phận; cạnh, viền', strokeCount: 15 },
      { character: '縄', hanViet: 'THẰNG', onyomi: 'じょう', kunyomi: 'なわ, ただ-す', meaningVi: 'dây thừng', strokeCount: 15 },
      { character: '縫', hanViet: 'PHÙNG', onyomi: 'ほう', kunyomi: 'ぬ-う', meaningVi: 'khâu, may', strokeCount: 16 },
      { character: '繁', hanViet: 'PHỒN', onyomi: 'はん', kunyomi: 'しげ-る, しげ-く', meaningVi: 'phồn thịnh, rậm rạp', strokeCount: 16 },
      { character: '織', hanViet: 'CHỨC', onyomi: 'しょく, しき', kunyomi: 'お-る, お-り, おり, -おり, -お-り', meaningVi: 'dệt', strokeCount: 18 },
      { character: '繕', hanViet: 'THIỆN', onyomi: 'ぜん', kunyomi: 'つくろ-う', meaningVi: 'sửa chữa, vá', strokeCount: 18 },
      { character: '繭', hanViet: 'KIÊN', onyomi: 'けん', kunyomi: 'まゆ, きぬ', meaningVi: 'kén tằm', strokeCount: 18 },
      { character: '罷', hanViet: 'BÃI', onyomi: 'ひ', kunyomi: 'まか-り-, や-める', meaningVi: 'bãi bỏ, ngừng', strokeCount: 15 },
    ],
  },
  {
    lessonNumber: 830,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (5)',
    sortOrder: 8300,
    entries: [
      { character: '羅', hanViet: 'LA', onyomi: 'ら', kunyomi: 'うすもの', meaningVi: 'the lụa; bủa lưới', strokeCount: 19 },
      { character: '翁', hanViet: 'ÔNG', onyomi: 'おう', kunyomi: 'おきな', meaningVi: 'ông già đáng kính', strokeCount: 10 },
      { character: '翔', hanViet: 'TƯỜNG', onyomi: 'しょう', kunyomi: 'かけ-る, と-ぶ', meaningVi: 'bay lượn', strokeCount: 12 },
      { character: '翠', hanViet: 'THÚY', onyomi: 'すい', kunyomi: 'かわせみ, みどり', meaningVi: 'màu xanh biếc', strokeCount: 14 },
      { character: '翻', hanViet: 'PHIÊN', onyomi: 'ほん, はん', kunyomi: 'ひるがえ-る, ひるがえ-す', meaningVi: 'lật, dịch (phiên dịch)', strokeCount: 18 },
      { character: '翼', hanViet: 'DỰC', onyomi: 'よく', kunyomi: 'つばさ', meaningVi: 'cánh', strokeCount: 17 },
      { character: '耐', hanViet: 'NẠI', onyomi: 'たい', kunyomi: 'た-える', meaningVi: 'chịu đựng, bền', strokeCount: 9 },
    ],
  },
];
