// Bổ sung từ vựng N3 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 338-343.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N3_PART6: JlptVocabUnit[] = [
  {
    lessonNumber: 338,
    jlptLevel: 'N3',
    words: [
      { kanji: '地方', kana: 'ちほう', romaji: 'chihō', meaning: 'địa phương, vùng miền', partOfSpeech: 'danh từ' },
      { kanji: '茶', kana: 'ちゃ', romaji: 'cha', meaning: 'trà', partOfSpeech: 'danh từ' },
      { kanji: '中', kana: 'ちゅう', romaji: 'chū', meaning: 'bên trong, đang (làm gì)', partOfSpeech: 'danh từ' },
      { kanji: '中央', kana: 'ちゅうおう', romaji: 'chūō', meaning: 'trung tâm', partOfSpeech: 'danh từ' },
      { kanji: '中学', kana: 'ちゅうがく', romaji: 'chūgaku', meaning: 'trường trung học cơ sở', partOfSpeech: 'danh từ' },
      { kanji: '中古', kana: 'ちゅうこ', romaji: 'chūko', meaning: 'đồ cũ, đã qua sử dụng', partOfSpeech: 'danh từ' },
      { kanji: '昼食', kana: 'ちゅうしょく', romaji: 'chūshoku', meaning: 'bữa trưa', partOfSpeech: 'danh từ' },
      { kanji: '注目', kana: 'ちゅうもく', romaji: 'chūmoku', meaning: 'sự chú ý, quan tâm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '虫歯', kana: 'むしば', romaji: 'mushiba', meaning: 'sâu răng', partOfSpeech: 'danh từ' },
      { kanji: '著者', kana: 'ちょしゃ', romaji: 'chosha', meaning: 'tác giả', partOfSpeech: 'danh từ' },
      { kanji: '眺め', kana: 'ながめ', romaji: 'nagame', meaning: 'cảnh quan, tầm nhìn', partOfSpeech: 'danh từ' },
      { kanji: '眺めます', kana: 'ながめます', romaji: 'nagamemasu', meaning: 'ngắm nhìn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '長期', kana: 'ちょうき', romaji: 'chōki', meaning: 'dài hạn', partOfSpeech: 'danh từ' },
      { kanji: '頂上', kana: 'ちょうじょう', romaji: 'chōjō', meaning: 'đỉnh núi, đỉnh cao', partOfSpeech: 'danh từ' },
      { kanji: '直ちに', kana: 'ただちに', romaji: 'tadachini', meaning: 'ngay lập tức', partOfSpeech: 'phó từ' },
      { kanji: '直に', kana: 'じかに', romaji: 'jikani', meaning: 'trực tiếp, không qua trung gian', partOfSpeech: 'phó từ' },
      { kanji: '沈みます', kana: 'しずみます', romaji: 'shizumimasu', meaning: 'chìm xuống; cảm thấy chán nản', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 339,
    jlptLevel: 'N3',
    words: [
      { kanji: '追い付きます', kana: 'おいつきます', romaji: 'oitsukimasu', meaning: 'đuổi kịp, bắt kịp', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '痛み', kana: 'いたみ', romaji: 'itami', meaning: 'cơn đau, nỗi đau', partOfSpeech: 'danh từ' },
      { kanji: '通じます', kana: 'つうじます', romaji: 'tsūjimasu', meaning: 'thông suốt, hiểu nhau, dẫn tới', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '通します', kana: 'とおします', romaji: 'tōshimasu', meaning: 'cho đi qua, để lọt qua', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '通り過ぎます', kana: 'とおりすぎます', romaji: 'tōrisugimasu', meaning: 'đi ngang qua, vượt qua', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '通行', kana: 'つうこう', romaji: 'tsūkō', meaning: 'sự đi lại, lưu thông', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '掴みます', kana: 'つかみます', romaji: 'tsukamimasu', meaning: 'nắm bắt, tóm lấy', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '停留所', kana: 'ていりゅうじょ', romaji: 'teiryūjo', meaning: 'trạm dừng xe buýt', partOfSpeech: 'danh từ' },
      { kanji: '定期', kana: 'ていき', romaji: 'teiki', meaning: 'định kỳ', partOfSpeech: 'danh từ' },
      { kanji: '泥', kana: 'どろ', romaji: 'doro', meaning: 'bùn đất', partOfSpeech: 'danh từ' },
      { kanji: '敵', kana: 'てき', romaji: 'teki', meaning: 'kẻ thù, đối thủ', partOfSpeech: 'danh từ' },
      { kanji: '笛', kana: 'ふえ', romaji: 'fue', meaning: 'cây sáo, cây kèn', partOfSpeech: 'danh từ' },
      { kanji: '適します', kana: 'てきします', romaji: 'tekishimasu', meaning: 'phù hợp, thích hợp', partOfSpeech: 'động từ する' },
      { kanji: '適用', kana: 'てきよう', romaji: 'tekiyō', meaning: 'sự áp dụng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '溺れます', kana: 'おぼれます', romaji: 'oboremasu', meaning: 'chết đuối; đắm chìm (vào việc gì)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '鉄', kana: 'てつ', romaji: 'tetsu', meaning: 'sắt', partOfSpeech: 'danh từ' },
      { kanji: '鉄道', kana: 'てつどう', romaji: 'tetsudō', meaning: 'đường sắt', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 340,
    jlptLevel: 'N3',
    words: [
      { kanji: '典型', kana: 'てんけい', romaji: 'tenkei', meaning: 'điển hình', partOfSpeech: 'danh từ' },
      { kanji: '天候', kana: 'てんこう', romaji: 'tenkō', meaning: 'thời tiết', partOfSpeech: 'danh từ' },
      { kanji: '天然', kana: 'てんねん', romaji: 'tennen', meaning: 'thiên nhiên, tự nhiên', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '電子', kana: 'でんし', romaji: 'denshi', meaning: 'điện tử', partOfSpeech: 'danh từ' },
      { kanji: '兎', kana: 'うさぎ', romaji: 'usagi', meaning: 'con thỏ', partOfSpeech: 'danh từ' },
      { kanji: '登山', kana: 'とざん', romaji: 'tozan', meaning: 'sự leo núi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '途端', kana: 'とたん', romaji: 'totan', meaning: 'ngay khi, vừa lúc', partOfSpeech: 'danh từ' },
      { kanji: '都', kana: 'みやこ', romaji: 'miyako', meaning: 'kinh đô, thủ đô', partOfSpeech: 'danh từ' },
      { kanji: '度', kana: 'たび', romaji: 'tabi', meaning: 'lần, mỗi lần', partOfSpeech: 'danh từ' },
      { kanji: '土', kana: 'つち', romaji: 'tsuchi', meaning: 'đất', partOfSpeech: 'danh từ' },
      { kanji: '土産', kana: 'みやげ', romaji: 'miyage', meaning: 'quà lưu niệm, đặc sản', partOfSpeech: 'danh từ' },
      { kanji: '党', kana: 'とう', romaji: 'tō', meaning: 'đảng phái chính trị', partOfSpeech: 'danh từ' },
      { kanji: '凍ります', kana: 'こおります', romaji: 'kōrimasu', meaning: 'đóng băng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '刀', kana: 'かたな', romaji: 'katana', meaning: 'thanh kiếm, đao', partOfSpeech: 'danh từ' },
      { kanji: '投票', kana: 'とうひょう', romaji: 'tōhyō', meaning: 'sự bỏ phiếu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '当たります', kana: 'あたります', romaji: 'atarimasu', meaning: 'trúng, đúng, tương đương với', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '当てます', kana: 'あてます', romaji: 'atemasu', meaning: 'áp vào, đoán trúng', partOfSpeech: 'động từ nhóm 2' },
    ],
  },
  {
    lessonNumber: 341,
    jlptLevel: 'N3',
    words: [
      { kanji: '等しい', kana: 'ひとしい', romaji: 'hitoshii', meaning: 'bằng nhau, ngang nhau', partOfSpeech: 'tính từ i' },
      { kanji: '答案', kana: 'とうあん', romaji: 'tōan', meaning: 'bài thi, bài làm', partOfSpeech: 'danh từ' },
      { kanji: '豆', kana: 'まめ', romaji: 'mame', meaning: 'đậu, hạt đậu', partOfSpeech: 'danh từ' },
      { kanji: '頭痛', kana: 'ずつう', romaji: 'zutsū', meaning: 'đau đầu', partOfSpeech: 'danh từ' },
      { kanji: '働き', kana: 'はたらき', romaji: 'hataraki', meaning: 'sự làm việc, chức năng', partOfSpeech: 'danh từ' },
      { kanji: '動詞', kana: 'どうし', romaji: 'dōshi', meaning: 'động từ', partOfSpeech: 'danh từ' },
      { kanji: '同一', kana: 'どういつ', romaji: 'dōitsu', meaning: 'đồng nhất, giống nhau', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '同時', kana: 'どうじ', romaji: 'dōji', meaning: 'đồng thời, cùng lúc', partOfSpeech: 'danh từ' },
      { kanji: '同様', kana: 'どうよう', romaji: 'dōyō', meaning: 'tương tự, giống như', partOfSpeech: 'tính từ na' },
      { kanji: '道路', kana: 'どうろ', romaji: 'dōro', meaning: 'đường bộ, đường sá', partOfSpeech: 'danh từ' },
      { kanji: '得ます', kana: 'えます', romaji: 'emasu', meaning: 'đạt được, thu được', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '毒', kana: 'どく', romaji: 'doku', meaning: 'chất độc', partOfSpeech: 'danh từ' },
      { kanji: '独立', kana: 'どくりつ', romaji: 'dokuritsu', meaning: 'sự độc lập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '読み', kana: 'よみ', romaji: 'yomi', meaning: 'cách đọc', partOfSpeech: 'danh từ' },
      { kanji: '読書', kana: 'どくしょ', romaji: 'dokusho', meaning: 'sự đọc sách', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '謎', kana: 'なぞ', romaji: 'nazo', meaning: 'câu đố, điều bí ẩn', partOfSpeech: 'danh từ' },
      { kanji: '縄', kana: 'なわ', romaji: 'nawa', meaning: 'sợi dây thừng', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 342,
    jlptLevel: 'N3',
    words: [
      { kanji: '日常', kana: 'にちじょう', romaji: 'nichijō', meaning: 'thường ngày, hàng ngày', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '日中', kana: 'にっちゅう', romaji: 'nicchū', meaning: 'ban ngày', partOfSpeech: 'danh từ' },
      { kanji: '日付', kana: 'ひづけ', romaji: 'hizuke', meaning: 'ngày tháng (ghi trên văn bản)', partOfSpeech: 'danh từ' },
      { kanji: '入場', kana: 'にゅうじょう', romaji: 'nyūjō', meaning: 'sự vào cửa, nhập trường', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '寧ろ', kana: 'むしろ', romaji: 'mushiro', meaning: 'thà rằng, đúng hơn là', partOfSpeech: 'phó từ' },
      { kanji: '熱帯', kana: 'ねったい', romaji: 'nettai', meaning: 'vùng nhiệt đới', partOfSpeech: 'danh từ' },
      { kanji: '熱中', kana: 'ねっちゅう', romaji: 'necchū', meaning: 'sự say mê, nhiệt tình', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '年間', kana: 'ねんかん', romaji: 'nenkan', meaning: 'trong khoảng một năm', partOfSpeech: 'danh từ' },
      { kanji: '年寄', kana: 'としより', romaji: 'toshiyori', meaning: 'người già', partOfSpeech: 'danh từ' },
      { kanji: '年月', kana: 'としつき', romaji: 'toshitsuki', meaning: 'năm tháng, thời gian dài', partOfSpeech: 'danh từ' },
      { kanji: '年代', kana: 'ねんだい', romaji: 'nendai', meaning: 'thời đại, niên đại', partOfSpeech: 'danh từ' },
      { kanji: '年中', kana: 'ねんじゅう', romaji: 'nenjū', meaning: 'quanh năm, suốt năm', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '悩みます', kana: 'なやみます', romaji: 'nayamimasu', meaning: 'lo lắng, phiền muộn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '農家', kana: 'のうか', romaji: 'nōka', meaning: 'nhà nông, nông dân', partOfSpeech: 'danh từ' },
      { kanji: '農業', kana: 'のうぎょう', romaji: 'nōgyō', meaning: 'nông nghiệp', partOfSpeech: 'danh từ' },
      { kanji: '農民', kana: 'のうみん', romaji: 'nōmin', meaning: 'nông dân', partOfSpeech: 'danh từ' },
      { kanji: '破ります', kana: 'やぶります', romaji: 'yaburimasu', meaning: 'xé rách; phá vỡ, đánh bại', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 343,
    jlptLevel: 'N3',
    words: [
      { kanji: '破産', kana: 'はさん', romaji: 'hasan', meaning: 'sự phá sản', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '馬鹿', kana: 'ばか', romaji: 'baka', meaning: 'ngu ngốc, kẻ ngốc', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '梅雨', kana: 'つゆ', romaji: 'tsuyu', meaning: 'mùa mưa (đầu hè ở Nhật)', partOfSpeech: 'danh từ' },
      { kanji: '売れます', kana: 'うれます', romaji: 'uremasu', meaning: 'bán chạy, được bán', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '博物館', kana: 'はくぶつかん', romaji: 'hakubutsukan', meaning: 'bảo tàng', partOfSpeech: 'danh từ' },
      { kanji: '爆発', kana: 'ばくはつ', romaji: 'bakuhatsu', meaning: 'sự nổ, vụ nổ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '莫大', kana: 'ばくだい', romaji: 'bakudai', meaning: 'to lớn, khổng lồ', partOfSpeech: 'tính từ na' },
      { kanji: '肌', kana: 'はだ', romaji: 'hada', meaning: 'làn da', partOfSpeech: 'danh từ' },
      { kanji: '畑', kana: 'はたけ', romaji: 'hatake', meaning: 'ruộng, nương rẫy', partOfSpeech: 'danh từ' },
    ],
  },
];
