// Bổ sung kanji N1 — dịch tay (Hán Việt + nghĩa Việt) dựa trên dữ liệu đọc âm
// (onyomi/kunyomi) và stroke count lấy từ kanjiapi.dev (nguồn mở), không auto-scrape nghĩa tiếng Việt.
// KanjiLesson lessonNumber 836-840.

import type { JlptKanjiLesson } from './jlpt-kanji.data';

export const JLPT_KANJI_BOOST4_N1_H: JlptKanjiLesson[] = [
  {
    lessonNumber: 836,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (1)',
    sortOrder: 8360,
    entries: [
      { character: '諒', hanViet: 'LƯỢNG', onyomi: 'りょう', kunyomi: 'あきら-か, まことに', meaningVi: 'hiểu rõ, thông cảm', strokeCount: 15 },
      { character: '諭', hanViet: 'DỤ', onyomi: 'ゆ', kunyomi: 'さと-す', meaningVi: 'khuyên bảo, dụ dỗ', strokeCount: 16 },
      { character: '諾', hanViet: 'NẶC', onyomi: 'だく', meaningVi: 'đồng ý, ưng thuận', strokeCount: 15 },
      { character: '謄', hanViet: 'ĐẰNG', onyomi: 'とう', meaningVi: 'sao chép (bản sao)', strokeCount: 17 },
      { character: '謝', hanViet: 'TẠ', onyomi: 'しゃ', kunyomi: 'あやま-る', meaningVi: 'cảm ơn; xin lỗi', strokeCount: 17 },
      { character: '謡', hanViet: 'DAO', onyomi: 'よう', kunyomi: 'うた-い, うた-う', meaningVi: 'bài hát dân ca, ca dao', strokeCount: 16 },
      { character: '譜', hanViet: 'PHỔ', onyomi: 'ふ', meaningVi: 'bản nhạc, gia phả', strokeCount: 19 },
      { character: '譲', hanViet: 'NHƯỢNG', onyomi: 'じょう', kunyomi: 'ゆず-る', meaningVi: 'nhường nhịn, chuyển giao', strokeCount: 20 },
      { character: '豪', hanViet: 'HÀO', onyomi: 'ごう', kunyomi: 'えら-い', meaningVi: 'hào kiệt, mạnh mẽ', strokeCount: 14 },
      { character: '貞', hanViet: 'TRINH', onyomi: 'てい, じょう', kunyomi: 'ただし-い, さだ', meaningVi: 'trinh tiết, ngay thẳng', strokeCount: 9 },
      { character: '貢', hanViet: 'CỐNG', onyomi: 'こう, く', kunyomi: 'みつ-ぐ', meaningVi: 'cống nạp, đóng góp', strokeCount: 10 },
      { character: '賀', hanViet: 'HẠ', onyomi: 'が', meaningVi: 'chúc mừng', strokeCount: 12 },
      { character: '賊', hanViet: 'TẶC', onyomi: 'ぞく', meaningVi: 'giặc, kẻ trộm', strokeCount: 13 },
      { character: '賦', hanViet: 'PHÚ', onyomi: 'ふ, ぶ', meaningVi: 'phú (thể văn); thuế', strokeCount: 15 },
      { character: '購', hanViet: 'CẤU', onyomi: 'こう', meaningVi: 'mua sắm', strokeCount: 17 },
      { character: '赦', hanViet: 'XÁ', onyomi: 'しゃ', kunyomi: 'ゆる-す', meaningVi: 'tha thứ, ân xá', strokeCount: 11 },
      { character: '赴', hanViet: 'PHÓ', onyomi: 'ふ', kunyomi: 'おもむ-く', meaningVi: 'đi đến, phó nhậm', strokeCount: 9 },
      { character: '趣', hanViet: 'THÚ', onyomi: 'しゅ', kunyomi: 'おもむき, おもむ-く', meaningVi: 'thú vị, ý vị', strokeCount: 15 },
      { character: '距', hanViet: 'CỰ', onyomi: 'きょ', kunyomi: 'へだ-たる, けづめ', meaningVi: 'khoảng cách', strokeCount: 12 },
      { character: '践', hanViet: 'TIỄN', onyomi: 'せん', kunyomi: 'ふ-む', meaningVi: 'giẫm lên, thực hành', strokeCount: 13 },
    ],
  },
  {
    lessonNumber: 837,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (2)',
    sortOrder: 8370,
    entries: [
      { character: '軸', hanViet: 'TRỤC', onyomi: 'じく', meaningVi: 'trục', strokeCount: 12 },
      { character: '輔', hanViet: 'PHỤ', onyomi: 'ほ, ふ', kunyomi: 'たす-ける', meaningVi: 'giúp đỡ, phụ tá', strokeCount: 14 },
      { character: '輝', hanViet: 'HUY', onyomi: 'き', kunyomi: 'かがや-く', meaningVi: 'sáng chói, rực rỡ', strokeCount: 15 },
      { character: '輩', hanViet: 'BỐI', onyomi: 'はい', kunyomi: '-ばら, やから, やかい, ともがら', meaningVi: 'lứa, bọn, thế hệ', strokeCount: 15 },
      { character: '辰', hanViet: 'THÌN', onyomi: 'しん, じん', kunyomi: 'たつ', meaningVi: 'năm/giờ Thìn (con rồng)', strokeCount: 7 },
      { character: '迭', hanViet: 'ĐIỆT', onyomi: 'てつ', meaningVi: 'thay đổi, luân phiên', strokeCount: 8 },
      { character: '逐', hanViet: 'TRỤC', onyomi: 'ちく', meaningVi: 'đuổi theo, trục xuất', strokeCount: 10 },
      { character: '逓', hanViet: 'ĐỆ', onyomi: 'てい', kunyomi: 'かわ-る, たがいに', meaningVi: 'chuyển tiếp, luân phiên', strokeCount: 10 },
      { character: '逝', hanViet: 'THỆ', onyomi: 'せい', kunyomi: 'ゆ-く, い-く', meaningVi: 'qua đời, ra đi', strokeCount: 10 },
      { character: '逮', hanViet: 'ĐÃI', onyomi: 'たい', meaningVi: 'bắt giữ', strokeCount: 11 },
      { character: '逸', hanViet: 'DẬT', onyomi: 'いつ', kunyomi: 'そ-れる, そ-らす, はぐ-れる', meaningVi: 'an nhàn; lệch khỏi', strokeCount: 11 },
      { character: '遇', hanViet: 'NGỘ', onyomi: 'ぐう', kunyomi: 'あ-う', meaningVi: 'gặp gỡ, đối xử', strokeCount: 12 },
      { character: '遍', hanViet: 'BIẾN', onyomi: 'へん', kunyomi: 'あまね-く', meaningVi: 'khắp nơi, lần', strokeCount: 12 },
      { character: '遣', hanViet: 'KHIỂN', onyomi: 'けん', kunyomi: 'つか-う, -つか-い, -づか-い, つか-わす, や-る', meaningVi: 'phái đi, sai khiến', strokeCount: 13 },
      { character: '遥', hanViet: 'DAO', onyomi: 'よう', kunyomi: 'はる-か', meaningVi: 'xa xôi', strokeCount: 12 },
      { character: '遭', hanViet: 'TAO', onyomi: 'そう', kunyomi: 'あ-う, あ-わせる', meaningVi: 'gặp phải (tai nạn)', strokeCount: 14 },
      { character: '遵', hanViet: 'TUÂN', onyomi: 'じゅん', meaningVi: 'tuân theo', strokeCount: 15 },
      { character: '遷', hanViet: 'THIÊN', onyomi: 'せん', kunyomi: 'うつ-る, うつ-す, みやこがえ', meaningVi: 'di chuyển, biến đổi', strokeCount: 15 },
      { character: '避', hanViet: 'TỊ', onyomi: 'ひ', kunyomi: 'さ-ける, よ-ける', meaningVi: 'tránh né', strokeCount: 16 },
      { character: '還', hanViet: 'HOÀN', onyomi: 'かん', kunyomi: 'かえ-る', meaningVi: 'trở về, trả lại', strokeCount: 16 },
    ],
  },
  {
    lessonNumber: 838,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (3)',
    sortOrder: 8380,
    entries: [
      { character: '邑', hanViet: 'ẤP', onyomi: 'ゆう', kunyomi: 'むら', meaningVi: 'làng xã, ấp', strokeCount: 7 },
      { character: '邦', hanViet: 'BANG', onyomi: 'ほう', kunyomi: 'くに', meaningVi: 'đất nước, quốc gia', strokeCount: 7 },
      { character: '邪', hanViet: 'TÀ', onyomi: 'じゃ', kunyomi: 'よこし-ま', meaningVi: 'tà ác, gian tà', strokeCount: 8 },
      { character: '邸', hanViet: 'ĐỆ', onyomi: 'てい', kunyomi: 'やしき', meaningVi: 'dinh thự', strokeCount: 8 },
      { character: '郁', hanViet: 'ÚC', onyomi: 'いく', meaningVi: 'hương thơm; văn hóa phát triển', strokeCount: 9 },
      { character: '郎', hanViet: 'LANG', onyomi: 'ろう, りょう', kunyomi: 'おとこ', meaningVi: 'chàng trai', strokeCount: 9 },
      { character: '郡', hanViet: 'QUẬN', onyomi: 'ぐん', kunyomi: 'こおり', meaningVi: 'quận, huyện', strokeCount: 10 },
      { character: '郭', hanViet: 'QUÁCH', onyomi: 'かく', kunyomi: 'くるわ', meaningVi: 'thành quách, khu vực', strokeCount: 11 },
      { character: '郷', hanViet: 'HƯƠNG', onyomi: 'きょう, ごう', kunyomi: 'さと', meaningVi: 'quê hương, làng', strokeCount: 11 },
      { character: '酉', hanViet: 'DẬU', onyomi: 'ゆう', kunyomi: 'とり', meaningVi: 'năm/giờ Dậu (con gà)', strokeCount: 7 },
      { character: '酢', hanViet: 'THỐ', onyomi: 'さく', kunyomi: 'す', meaningVi: 'giấm', strokeCount: 12 },
      { character: '酪', hanViet: 'LẠC', onyomi: 'らく', meaningVi: 'sản phẩm từ sữa', strokeCount: 13 },
      { character: '酬', hanViet: 'THÙ', onyomi: 'しゅう, しゅ, とう', kunyomi: 'むく-いる', meaningVi: 'đền đáp, trả ơn', strokeCount: 13 },
      { character: '酵', hanViet: 'HIỆU', onyomi: 'こう', meaningVi: 'lên men', strokeCount: 14 },
      { character: '酷', hanViet: 'KHỐC', onyomi: 'こく', kunyomi: 'ひど-い', meaningVi: 'tàn khốc, khắc nghiệt', strokeCount: 14 },
      { character: '酸', hanViet: 'TOAN', onyomi: 'さん', kunyomi: 'す-い', meaningVi: 'chua, axit', strokeCount: 14 },
      { character: '醸', hanViet: 'NHƯỠNG', onyomi: 'じょう', kunyomi: 'かも-す', meaningVi: 'ủ men, gây ra', strokeCount: 20 },
      { character: '采', hanViet: 'THÁI', onyomi: 'さい', kunyomi: 'と-る, いろどり', meaningVi: 'chọn lấy, sắc thái', strokeCount: 8 },
      { character: '釈', hanViet: 'THÍCH', onyomi: 'しゃく, せき', kunyomi: 'とく, す-てる, ゆる-す', meaningVi: 'giải thích', strokeCount: 11 },
      { character: '釣', hanViet: 'ĐIẾU', onyomi: 'ちょう', kunyomi: 'つ-る, つ-り, つ-り-', meaningVi: 'câu cá', strokeCount: 11 },
    ],
  },
  {
    lessonNumber: 839,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (4)',
    sortOrder: 8390,
    entries: [
      { character: '鈴', hanViet: 'LINH', onyomi: 'れい, りん', kunyomi: 'すず', meaningVi: 'chuông nhỏ', strokeCount: 13 },
      { character: '鉛', hanViet: 'DIÊN', onyomi: 'えん', kunyomi: 'なまり', meaningVi: 'chì (kim loại)', strokeCount: 13 },
      { character: '鉢', hanViet: 'BÁT', onyomi: 'はち, はつ', meaningVi: 'cái bát, chậu', strokeCount: 13 },
      { character: '銘', hanViet: 'MINH', onyomi: 'めい', meaningVi: 'khắc chữ, ghi nhớ', strokeCount: 14 },
      { character: '鋳', hanViet: 'CHÚ', onyomi: 'ちゅう, い, しゅ, しゅう', kunyomi: 'い-る', meaningVi: 'đúc (kim loại)', strokeCount: 15 },
      { character: '鋼', hanViet: 'CƯƠNG', onyomi: 'こう', kunyomi: 'はがね', meaningVi: 'thép', strokeCount: 16 },
      { character: '錘', hanViet: 'CHÙY', onyomi: 'すい', kunyomi: 'つむ, おもり', meaningVi: 'quả nặng, con thoi', strokeCount: 16 },
      { character: '錠', hanViet: 'ĐĨNH', onyomi: 'じょう', meaningVi: 'ổ khóa; viên (thuốc)', strokeCount: 16 },
      { character: '錦', hanViet: 'CẨM', onyomi: 'きん', kunyomi: 'にしき', meaningVi: 'gấm vóc', strokeCount: 16 },
      { character: '錯', hanViet: 'THÁC', onyomi: 'さく, しゃく', meaningVi: 'rối loạn, sai lầm', strokeCount: 16 },
      { character: '鎌', hanViet: 'LIÊM', onyomi: 'れん, けん', kunyomi: 'かま', meaningVi: 'cái liềm', strokeCount: 18 },
      { character: '鎖', hanViet: 'TỎA', onyomi: 'さ', kunyomi: 'くさり, とざ-す', meaningVi: 'dây xích, khóa', strokeCount: 18 },
      { character: '鎮', hanViet: 'TRẤN', onyomi: 'ちん', kunyomi: 'しず-める, しず-まる, おさえ', meaningVi: 'trấn an, trấn giữ', strokeCount: 18 },
      { character: '鏡', hanViet: 'KÍNH', onyomi: 'きょう, けい', kunyomi: 'かがみ', meaningVi: 'cái gương', strokeCount: 19 },
      { character: '鐘', hanViet: 'CHUNG', onyomi: 'しょう', kunyomi: 'かね', meaningVi: 'cái chuông', strokeCount: 20 },
      { character: '閑', hanViet: 'NHÀN', onyomi: 'かん', meaningVi: 'nhàn rỗi', strokeCount: 12 },
      { character: '閣', hanViet: 'CÁC', onyomi: 'かく', meaningVi: 'lầu gác, nội các', strokeCount: 14 },
      { character: '閥', hanViet: 'PHIỆT', onyomi: 'ばつ', meaningVi: 'phe cánh, dòng dõi', strokeCount: 14 },
      { character: '閲', hanViet: 'DUYỆT', onyomi: 'えつ', kunyomi: 'けみ-する', meaningVi: 'duyệt xét, xem lại', strokeCount: 15 },
      { character: '阿', hanViet: 'A', onyomi: 'あ, お', kunyomi: 'おもね-る, くま', meaningVi: 'châu Phi; nịnh bợ; góc', strokeCount: 8 },
    ],
  },
  {
    lessonNumber: 840,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (5)',
    sortOrder: 8400,
    entries: [
      { character: '附', hanViet: 'PHỤ', onyomi: 'ふ', kunyomi: 'つ-ける, つ-く', meaningVi: 'phụ thêm, đính kèm', strokeCount: 8 },
      { character: '陪', hanViet: 'BỒI', onyomi: 'ばい', meaningVi: 'tháp tùng, hầu cận', strokeCount: 11 },
      { character: '陰', hanViet: 'ÂM', onyomi: 'いん', kunyomi: 'かげ, かげ-る', meaningVi: 'âm (đối lập dương); bóng râm', strokeCount: 11 },
      { character: '陵', hanViet: 'LĂNG', onyomi: 'りょう', kunyomi: 'みささぎ', meaningVi: 'lăng mộ, gò đồi', strokeCount: 11 },
      { character: '陶', hanViet: 'ĐÀO', onyomi: 'とう', kunyomi: 'すえ', meaningVi: 'đồ gốm sứ', strokeCount: 11 },
      { character: '隆', hanViet: 'LONG', onyomi: 'りゅう', meaningVi: 'hưng thịnh, cao', strokeCount: 11 },
      { character: '随', hanViet: 'TÙY', onyomi: 'ずい', kunyomi: 'まにま-に, したが-う', meaningVi: 'tùy theo, đi theo', strokeCount: 12 },
      { character: '隔', hanViet: 'CÁCH', onyomi: 'かく', kunyomi: 'へだ-てる, へだ-たる', meaningVi: 'cách biệt, ngăn cách', strokeCount: 13 },
      { character: '障', hanViet: 'CHƯỚNG', onyomi: 'しょう', kunyomi: 'さわ-る', meaningVi: 'cản trở, chướng ngại', strokeCount: 14 },
      { character: '隣', hanViet: 'LÂN', onyomi: 'りん', kunyomi: 'とな-る, となり', meaningVi: 'hàng xóm, láng giềng', strokeCount: 16 },
      { character: '隷', hanViet: 'LỆ', onyomi: 'れい', kunyomi: 'したが-う, しもべ', meaningVi: 'nô lệ; chữ lệ', strokeCount: 16 },
      { character: '隼', hanViet: 'CHUẨN', onyomi: 'しゅん, じゅん', kunyomi: 'はやぶさ', meaningVi: 'chim cắt (chim săn mồi)', strokeCount: 10 },
      { character: '雄', hanViet: 'HÙNG', onyomi: 'ゆう', kunyomi: 'お-, おす, おん', meaningVi: 'hùng dũng, giống đực', strokeCount: 12 },
      { character: '雅', hanViet: 'NHÃ', onyomi: 'が', kunyomi: 'みや-び', meaningVi: 'thanh nhã, tao nhã', strokeCount: 13 },
      { character: '雌', hanViet: 'THƯ', onyomi: 'し', kunyomi: 'め-, めす, めん', meaningVi: 'giống cái', strokeCount: 14 },
    ],
  },
];
