// Bổ sung từ vựng N2 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 700-705.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N2_PART1: JlptVocabUnit[] = [
  {
    lessonNumber: 700,
    jlptLevel: 'N2',
    words: [
      { kanji: '呆れます', kana: 'あきれます', romaji: 'akiremasu', meaning: 'sững sờ, ngán ngẩm', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'アクセント', romaji: 'akusento', meaning: 'trọng âm, ngữ điệu', partOfSpeech: 'danh từ' },
      { kana: 'あくび', romaji: 'akubi', meaning: 'cái ngáp', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'あたりまえ', romaji: 'atarimae', meaning: 'đương nhiên, bình thường', partOfSpeech: 'tính từ na' },
      { kana: 'あちらこちら', romaji: 'achirakochira', meaning: 'khắp nơi, chỗ này chỗ kia', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '当てはまります', kana: 'あてはまります', romaji: 'atehamarimasu', meaning: 'phù hợp, đúng với (trường hợp nào đó)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '当てはめます', kana: 'あてはめます', romaji: 'atehamemasu', meaning: 'áp dụng vào, cho phù hợp với', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '炙ります', kana: 'あぶります', romaji: 'aburimasu', meaning: 'nướng, hơ lửa', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '溢れます', kana: 'あふれます', romaji: 'afuremasu', meaning: 'tràn ra, đầy ứ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '粗筋', kana: 'あらすじ', romaji: 'arasuji', meaning: 'tóm tắt nội dung', partOfSpeech: 'danh từ' },
      { kana: 'あれこれ', romaji: 'arekore', meaning: 'cái này cái kia', partOfSpeech: 'danh từ, phó từ' },
      { kana: 'あわただしい', romaji: 'awatadashii', meaning: 'vội vã, bận rộn', partOfSpeech: 'tính từ i' },
      { kana: 'アンテナ', romaji: 'antena', meaning: 'ăng-ten', partOfSpeech: 'danh từ' },
      { kana: 'イコール', romaji: 'ikōru', meaning: 'bằng nhau, dấu bằng', partOfSpeech: 'danh từ' },
      { kana: 'いちいち', romaji: 'ichiichi', meaning: 'từng cái một, chi tiết', partOfSpeech: 'phó từ' },
      { kana: 'インタビュー', romaji: 'intabyū', meaning: 'cuộc phỏng vấn', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'ウール', romaji: 'ūru', meaning: 'len (chất liệu)', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 701,
    jlptLevel: 'N2',
    words: [
      { kana: 'うっかり', romaji: 'ukkari', meaning: 'vô ý, lơ đễnh', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'うどん', romaji: 'udon', meaning: 'mì udon', partOfSpeech: 'danh từ' },
      { kana: 'うろうろ', romaji: 'urōro', meaning: 'đi lang thang, quanh quẩn', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'うんと', romaji: 'unto', meaning: 'rất nhiều, hết sức', partOfSpeech: 'phó từ' },
      { kana: 'ええと', romaji: 'eeto', meaning: 'à... để xem nào (thán từ ngập ngừng)', partOfSpeech: 'thán từ' },
      { kana: 'エチケット', romaji: 'echiketto', meaning: 'phép lịch sự, quy tắc ứng xử', partOfSpeech: 'danh từ' },
      { kana: 'エプロン', romaji: 'epuron', meaning: 'tạp dề', partOfSpeech: 'danh từ' },
      { kana: 'オイル', romaji: 'oiru', meaning: 'dầu (máy, nhớt)', partOfSpeech: 'danh từ' },
      { kana: 'オーケストラ', romaji: 'ōkesutora', meaning: 'dàn nhạc giao hưởng', partOfSpeech: 'danh từ' },
      { kana: 'オートメーション', romaji: 'ōtomēshon', meaning: 'sự tự động hóa', partOfSpeech: 'danh từ' },
      { kanji: 'お先に', kana: 'おさきに', romaji: 'osakini', meaning: 'trước, đi trước', partOfSpeech: 'phó từ' },
      { kana: 'おじゃまします', romaji: 'ojamashimasu', meaning: 'xin phép làm phiền (khi vào nhà ai)', partOfSpeech: 'cụm từ' },
      { kana: 'おしゃれ', romaji: 'oshare', meaning: 'sành điệu, ăn mặc đẹp', partOfSpeech: 'danh từ, tính từ na' },
      { kana: 'おだいじに', romaji: 'odaijini', meaning: 'mong bạn mau khỏe (nói với người ốm)', partOfSpeech: 'cụm từ' },
      { kanji: '脅かします', kana: 'おどかします', romaji: 'odokashimasu', meaning: 'dọa nạt, làm giật mình', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'おねがいします', romaji: 'onegaishimasu', meaning: 'xin nhờ, làm ơn', partOfSpeech: 'cụm từ' },
      { kana: 'おまたせしました', romaji: 'omataseshimashita', meaning: 'xin lỗi đã để bạn đợi lâu', partOfSpeech: 'cụm từ' },
    ],
  },
  {
    lessonNumber: 702,
    jlptLevel: 'N2',
    words: [
      { kana: 'おまちください', romaji: 'omachikudasai', meaning: 'xin vui lòng chờ', partOfSpeech: 'cụm từ' },
      { kana: 'おまちどおさま', romaji: 'omachidōsama', meaning: 'xin lỗi đã để bạn đợi lâu', partOfSpeech: 'cụm từ' },
      { kana: 'おめでたい', romaji: 'omedetai', meaning: 'đáng mừng, hỷ sự', partOfSpeech: 'tính từ i' },
      { kana: 'オルガン', romaji: 'orugan', meaning: 'đàn organ', partOfSpeech: 'danh từ' },
      { kanji: 'お帰り', kana: 'おかえり', romaji: 'okaeri', meaning: 'chào mừng bạn về (nói khi ai đó về nhà)', partOfSpeech: 'cụm từ' },
      { kanji: 'お参り', kana: 'おまいり', romaji: 'omairi', meaning: 'sự viếng thăm đền chùa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: 'お手伝いさん', kana: 'おてつだいさん', romaji: 'otetsudaisan', meaning: 'người giúp việc', partOfSpeech: 'danh từ' },
      { kanji: 'お代わり', kana: 'おかわり', romaji: 'okawari', meaning: 'thêm suất, ăn/uống thêm', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'カーブ', romaji: 'kābu', meaning: 'khúc cua, đường cong', partOfSpeech: 'danh từ' },
      { kana: 'かしこまりました', romaji: 'kashikomarimashita', meaning: 'vâng, tôi hiểu rồi (kính ngữ)', partOfSpeech: 'cụm từ' },
      { kanji: '齧ります', kana: 'かじります', romaji: 'kajirimasu', meaning: 'gặm, nhấm nháp', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'カセット', romaji: 'kasetto', meaning: 'băng cát-xét', partOfSpeech: 'danh từ' },
      { kana: 'カバー', romaji: 'kabā', meaning: 'vỏ bọc, bìa bọc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '痒い', kana: 'かゆい', romaji: 'kayui', meaning: 'ngứa', partOfSpeech: 'tính từ i' },
      { kana: 'カラー', romaji: 'karā', meaning: 'màu sắc; cổ áo', partOfSpeech: 'danh từ' },
      { kanji: '揶揄います', kana: 'からかいます', romaji: 'karakaimasu', meaning: 'trêu chọc, chế giễu', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'かるた', romaji: 'karuta', meaning: 'bài karuta (trò chơi bài Nhật)', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 703,
    jlptLevel: 'N2',
    words: [
      { kana: 'カロリー', romaji: 'karorī', meaning: 'calo', partOfSpeech: 'danh từ' },
      { kanji: '可愛がります', kana: 'かわいがります', romaji: 'kawaigarimasu', meaning: 'yêu thương, cưng chiều', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'きっかけ', romaji: 'kikkake', meaning: 'cơ hội, duyên cớ', partOfSpeech: 'danh từ' },
      { kana: 'ぎっしり', romaji: 'gisshiri', meaning: 'chật ních, đầy ắp', partOfSpeech: 'phó từ' },
      { kana: 'ギャング', romaji: 'gyangu', meaning: 'băng đảng, tên cướp', partOfSpeech: 'danh từ' },
      { kana: 'キャンパス', romaji: 'kyanpasu', meaning: 'khuôn viên trường', partOfSpeech: 'danh từ' },
      { kana: 'クーラー', romaji: 'kūrā', meaning: 'máy điều hòa', partOfSpeech: 'danh từ' },
      { kana: 'くしゃみ', romaji: 'kushami', meaning: 'cái hắt hơi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '草臥れます', kana: 'くたびれます', romaji: 'kutabiremasu', meaning: 'mệt mỏi, kiệt sức', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'くだらない', romaji: 'kudaranai', meaning: 'vô nghĩa, vớ vẩn', partOfSpeech: 'tính từ i' },
      { kanji: 'くっ付きます', kana: 'くっつきます', romaji: 'kuttsukimasu', meaning: 'dính vào, bám sát', partOfSpeech: 'động từ nhóm 1' },
      { kanji: 'くっ付けます', kana: 'くっつけます', romaji: 'kuttsukemasu', meaning: 'gắn vào, dán vào', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'くどい', romaji: 'kudoi', meaning: 'dài dòng, ngán (vị đậm)', partOfSpeech: 'tính từ i' },
      { kanji: '包みます', kana: 'くるみます', romaji: 'kurumimasu', meaning: 'bọc, gói lại', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'くれぐれも', romaji: 'kureguremo', meaning: 'hết sức, tha thiết (dặn dò)', partOfSpeech: 'phó từ' },
      { kana: 'こうして', romaji: 'kōshite', meaning: 'như thế này, bằng cách này', partOfSpeech: 'phó từ' },
      { kana: 'コーラス', romaji: 'kōrasu', meaning: 'hợp xướng', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 704,
    jlptLevel: 'N2',
    words: [
      { kana: 'ごくろうさま', romaji: 'gokurōsama', meaning: 'cảm ơn bạn đã vất vả', partOfSpeech: 'cụm từ' },
      { kanji: '拵えます', kana: 'こしらえます', romaji: 'koshiraemasu', meaning: 'làm ra, chế tạo', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'ごちそうさま', romaji: 'gochisōsama', meaning: 'cảm ơn vì bữa ăn', partOfSpeech: 'cụm từ' },
      { kana: 'こちらこそ', romaji: 'kochirakoso', meaning: 'chính tôi mới phải nói vậy', partOfSpeech: 'cụm từ' },
      { kana: 'コック', romaji: 'kokku', meaning: 'đầu bếp; vòi khóa', partOfSpeech: 'danh từ' },
      { kana: 'こっそり', romaji: 'kossori', meaning: 'lén lút, âm thầm', partOfSpeech: 'phó từ' },
      { kana: 'こないだ', romaji: 'konaida', meaning: 'hôm nọ, dạo gần đây', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '零します', kana: 'こぼします', romaji: 'koboshimasu', meaning: 'làm đổ, làm tràn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '零れます', kana: 'こぼれます', romaji: 'koboremasu', meaning: 'bị đổ, bị tràn ra', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'ゴム', romaji: 'gomu', meaning: 'cao su', partOfSpeech: 'danh từ' },
      { kana: 'ごめんください', romaji: 'gomenkudasai', meaning: 'xin phép, có ai ở nhà không', partOfSpeech: 'cụm từ' },
      { kanji: '堪えます', kana: 'こらえます', romaji: 'koraemasu', meaning: 'chịu đựng, nhẫn nhịn', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'コレクション', romaji: 'korekushon', meaning: 'bộ sưu tập', partOfSpeech: 'danh từ' },
      { kana: 'コンクール', romaji: 'konkūru', meaning: 'cuộc thi (âm nhạc, nghệ thuật)', partOfSpeech: 'danh từ' },
      { kana: 'コンクリート', romaji: 'konkurīto', meaning: 'bê tông', partOfSpeech: 'danh từ' },
      { kana: 'コンセント', romaji: 'konsento', meaning: 'ổ cắm điện', partOfSpeech: 'danh từ' },
      { kana: 'こんばんは', romaji: 'konbanha', meaning: 'chào buổi tối', partOfSpeech: 'cụm từ' },
    ],
  },
  {
    lessonNumber: 705,
    jlptLevel: 'N2',
    words: [
      { kana: 'サークル', romaji: 'sākuru', meaning: 'câu lạc bộ, nhóm sinh hoạt', partOfSpeech: 'danh từ' },
      { kana: 'サイレン', romaji: 'sairen', meaning: 'còi báo động', partOfSpeech: 'danh từ' },
      { kana: 'さきおととい', romaji: 'sakiototoi', meaning: 'ba ngày trước', partOfSpeech: 'danh từ' },
      { kana: 'さっさと', romaji: 'sassato', meaning: 'nhanh chóng, mau lẹ', partOfSpeech: 'phó từ' },
      { kana: 'さようなら', romaji: 'sayōnara', meaning: 'tạm biệt', partOfSpeech: 'cụm từ' },
      { kana: 'さわやか', romaji: 'sawayaka', meaning: 'sảng khoái, trong lành', partOfSpeech: 'tính từ na' },
      { kana: 'サンプル', romaji: 'sanpuru', meaning: 'mẫu thử', partOfSpeech: 'danh từ' },
      { kana: 'しあさって', romaji: 'shiasatte', meaning: 'ngày kia nữa (3 ngày sau)', partOfSpeech: 'danh từ' },
      { kana: 'シーズン', romaji: 'shīzun', meaning: 'mùa (thể thao, du lịch)', partOfSpeech: 'danh từ' },
      { kana: 'シーツ', romaji: 'shītsu', meaning: 'ga trải giường', partOfSpeech: 'danh từ' },
    ],
  },
];
