// Bổ sung từ vựng N3 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 332-337.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N3_PART5: JlptVocabUnit[] = [
  {
    lessonNumber: 332,
    jlptLevel: 'N3',
    words: [
      { kanji: '世の中', kana: 'よのなか', romaji: 'yononaka', meaning: 'cuộc đời, xã hội', partOfSpeech: 'danh từ' },
      { kanji: '世間', kana: 'せけん', romaji: 'seken', meaning: 'thế gian, xã hội', partOfSpeech: 'danh từ' },
      { kanji: '世紀', kana: 'せいき', romaji: 'seiki', meaning: 'thế kỷ', partOfSpeech: 'danh từ' },
      { kanji: '世話', kana: 'せわ', romaji: 'sewa', meaning: 'sự chăm sóc, giúp đỡ', partOfSpeech: 'danh từ' },
      { kanji: '制度', kana: 'せいど', romaji: 'seido', meaning: 'chế độ, hệ thống', partOfSpeech: 'danh từ' },
      { kanji: '勢い', kana: 'いきおい', romaji: 'ikioi', meaning: 'khí thế, đà, sức mạnh', partOfSpeech: 'danh từ' },
      { kanji: '成人', kana: 'せいじん', romaji: 'seijin', meaning: 'người trưởng thành', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '成長', kana: 'せいちょう', romaji: 'seichō', meaning: 'sự trưởng thành, tăng trưởng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '政府', kana: 'せいふ', romaji: 'seifu', meaning: 'chính phủ', partOfSpeech: 'danh từ' },
      { kanji: '正午', kana: 'しょうご', romaji: 'shōgo', meaning: 'giữa trưa', partOfSpeech: 'danh từ' },
      { kanji: '正式', kana: 'せいしき', romaji: 'seishiki', meaning: 'chính thức', partOfSpeech: 'tính từ na' },
      { kanji: '正直', kana: 'しょうじき', romaji: 'shōjiki', meaning: 'trung thực, thật thà', partOfSpeech: 'tính từ na' },
      { kanji: '清潔', kana: 'せいけつ', romaji: 'seiketsu', meaning: 'sạch sẽ, trong sạch', partOfSpeech: 'tính từ na' },
      { kanji: '生き物', kana: 'いきもの', romaji: 'ikimono', meaning: 'sinh vật', partOfSpeech: 'danh từ' },
      { kanji: '生じます', kana: 'しょうじます', romaji: 'shōjimasu', meaning: 'phát sinh, nảy sinh', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '生まれ', kana: 'うまれ', romaji: 'umare', meaning: 'nơi sinh ra, xuất thân', partOfSpeech: 'danh từ' },
      { kanji: '生命', kana: 'せいめい', romaji: 'seimei', meaning: 'sinh mệnh, sự sống', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 333,
    jlptLevel: 'N3',
    words: [
      { kanji: '盛り', kana: 'さかり', romaji: 'sakari', meaning: 'thời kỳ đỉnh cao, lúc rộ nhất', partOfSpeech: 'danh từ' },
      { kanji: '精々', kana: 'せいぜい', romaji: 'seizei', meaning: 'cùng lắm là, tối đa là', partOfSpeech: 'phó từ' },
      { kanji: '精神', kana: 'せいしん', romaji: 'seishin', meaning: 'tinh thần', partOfSpeech: 'danh từ' },
      { kanji: '請求', kana: 'せいきゅう', romaji: 'seikyū', meaning: 'sự yêu cầu, đòi hỏi (thanh toán)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '青年', kana: 'せいねん', romaji: 'seinen', meaning: 'thanh niên', partOfSpeech: 'danh từ' },
      { kanji: '石炭', kana: 'せきたん', romaji: 'sekitan', meaning: 'than đá', partOfSpeech: 'danh từ' },
      { kanji: '積もります', kana: 'つもります', romaji: 'tsumorimasu', meaning: 'chất đống, tích tụ (tuyết, bụi)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '責めます', kana: 'せめます', romaji: 'sememasu', meaning: 'trách móc, khiển trách', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '切れ', kana: 'きれ', romaji: 'kire', meaning: 'mảnh vải, miếng cắt', partOfSpeech: 'danh từ' },
      { kanji: '切れます', kana: 'きれます', romaji: 'kiremasu', meaning: 'đứt, hết hạn; sắc bén', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '設計', kana: 'せっけい', romaji: 'sekkei', meaning: 'sự thiết kế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '節', kana: 'ふし', romaji: 'fushi', meaning: 'đốt, mắt (tre, xương); giai điệu', partOfSpeech: 'danh từ' },
      { kanji: '説', kana: 'せつ', romaji: 'setsu', meaning: 'học thuyết, giả thuyết', partOfSpeech: 'danh từ' },
      { kanji: '絶対', kana: 'ぜったい', romaji: 'zettai', meaning: 'tuyệt đối', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '戦い', kana: 'たたかい', romaji: 'tatakai', meaning: 'cuộc chiến, trận đấu', partOfSpeech: 'danh từ' },
      { kanji: '戦います', kana: 'たたかいます', romaji: 'tatakaimasu', meaning: 'chiến đấu, đấu tranh', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '泉', kana: 'いずみ', romaji: 'izumi', meaning: 'suối, mạch nước', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 334,
    jlptLevel: 'N3',
    words: [
      { kanji: '選手', kana: 'せんしゅ', romaji: 'senshu', meaning: 'vận động viên, tuyển thủ', partOfSpeech: 'danh từ' },
      { kanji: '前者', kana: 'ぜんしゃ', romaji: 'zensha', meaning: 'cái trước, người trước (trong hai đối tượng)', partOfSpeech: 'danh từ' },
      { kanji: '全く', kana: 'まったく', romaji: 'mattaku', meaning: 'hoàn toàn, thực sự', partOfSpeech: 'phó từ' },
      { kanji: '全て', kana: 'すべて', romaji: 'subete', meaning: 'tất cả', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '全員', kana: 'ぜんいん', romaji: 'zenin', meaning: 'tất cả mọi người, toàn thể thành viên', partOfSpeech: 'danh từ' },
      { kanji: '全国', kana: 'ぜんこく', romaji: 'zenkoku', meaning: 'toàn quốc', partOfSpeech: 'danh từ' },
      { kanji: '全体', kana: 'ぜんたい', romaji: 'zentai', meaning: 'toàn thể, tổng thể', partOfSpeech: 'danh từ' },
      { kanji: '粗', kana: 'あら', romaji: 'ara', meaning: 'khuyết điểm, chỗ thô', partOfSpeech: 'danh từ' },
      { kanji: '粗末', kana: 'そまつ', romaji: 'somatsu', meaning: 'sơ sài, thô sơ', partOfSpeech: 'tính từ na' },
      { kanji: '組', kana: 'くみ', romaji: 'kumi', meaning: 'nhóm, tổ, lớp', partOfSpeech: 'danh từ' },
      { kanji: '組みます', kana: 'くみます', romaji: 'kumimasu', meaning: 'ghép lại, kết hợp', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '組合', kana: 'くみあい', romaji: 'kumiai', meaning: 'hiệp hội, công đoàn', partOfSpeech: 'danh từ' },
      { kanji: '訴えます', kana: 'うったえます', romaji: 'uttaemasu', meaning: 'kiện, khởi kiện; kêu gọi', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '相続', kana: 'そうぞく', romaji: 'sōzoku', meaning: 'sự thừa kế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '装置', kana: 'そうち', romaji: 'sōchi', meaning: 'thiết bị, bộ máy', partOfSpeech: 'danh từ' },
      { kanji: '霜', kana: 'しも', romaji: 'shimo', meaning: 'sương giá', partOfSpeech: 'danh từ' },
      { kanji: '増します', kana: 'まします', romaji: 'mashimasu', meaning: 'tăng lên, gia tăng', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 335,
    jlptLevel: 'N3',
    words: [
      { kanji: '束', kana: 'たば', romaji: 'taba', meaning: 'bó, chùm', partOfSpeech: 'danh từ' },
      { kanji: '続き', kana: 'つづき', romaji: 'tsuzuki', meaning: 'phần tiếp theo', partOfSpeech: 'danh từ' },
      { kanji: '袖', kana: 'そで', romaji: 'sode', meaning: 'tay áo', partOfSpeech: 'danh từ' },
      { kanji: '存在', kana: 'そんざい', romaji: 'sonzai', meaning: 'sự tồn tại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '尊重', kana: 'そんちょう', romaji: 'sonchō', meaning: 'sự tôn trọng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '損', kana: 'そん', romaji: 'son', meaning: 'sự thua lỗ, thiệt hại', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '他', kana: 'た', romaji: 'ta', meaning: 'cái khác, nơi khác', partOfSpeech: 'danh từ' },
      { kanji: '他人', kana: 'たにん', romaji: 'tanin', meaning: 'người khác, người ngoài', partOfSpeech: 'danh từ' },
      { kanji: '多少', kana: 'たしょう', romaji: 'tashō', meaning: 'ít nhiều, một chút', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '打ちます', kana: 'ぶちます', romaji: 'buchimasu', meaning: 'đánh, đấm (cách nói thông tục của 打つ)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '体育', kana: 'たいいく', romaji: 'taiiku', meaning: 'thể dục, giáo dục thể chất', partOfSpeech: 'danh từ' },
      { kanji: '体温', kana: 'たいおん', romaji: 'taion', meaning: 'thân nhiệt', partOfSpeech: 'danh từ' },
      { kanji: '対', kana: 'たい', romaji: 'tai', meaning: 'cặp, đôi; đối', partOfSpeech: 'danh từ' },
      { kanji: '対します', kana: 'たいします', romaji: 'taishimasu', meaning: 'đối diện, đối với', partOfSpeech: 'động từ する' },
      { kanji: '帯', kana: 'おび', romaji: 'obi', meaning: 'đai, dải băng', partOfSpeech: 'danh từ' },
      { kanji: '怠けます', kana: 'なまけます', romaji: 'namakemasu', meaning: 'lười biếng, xao nhãng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '滞在', kana: 'たいざい', romaji: 'taizai', meaning: 'sự lưu trú, ở lại', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 336,
    jlptLevel: 'N3',
    words: [
      { kanji: '退屈', kana: 'たいくつ', romaji: 'taikutsu', meaning: 'sự buồn chán, nhàm chán', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '逮捕', kana: 'たいほ', romaji: 'taiho', meaning: 'sự bắt giữ, bắt giam', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '代金', kana: 'だいきん', romaji: 'daikin', meaning: 'tiền hàng, giá tiền', partOfSpeech: 'danh từ' },
      { kanji: '代表', kana: 'だいひょう', romaji: 'daihyō', meaning: 'đại diện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '代理', kana: 'だいり', romaji: 'dairi', meaning: 'sự đại diện, ủy quyền', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '台', kana: 'だい', romaji: 'dai', meaning: 'cái bệ, giá đỡ', partOfSpeech: 'danh từ' },
      { kanji: '大いに', kana: 'おおいに', romaji: 'ōini', meaning: 'rất, hết sức', partOfSpeech: 'phó từ' },
      { kanji: '大した', kana: 'たいした', romaji: 'taishita', meaning: 'đáng kể, ghê gớm', partOfSpeech: 'từ hạn định' },
      { kanji: '大使', kana: 'たいし', romaji: 'taishi', meaning: 'đại sứ', partOfSpeech: 'danh từ' },
      { kanji: '大臣', kana: 'だいじん', romaji: 'daijin', meaning: 'bộ trưởng', partOfSpeech: 'danh từ' },
      { kanji: '大戦', kana: 'たいせん', romaji: 'taisen', meaning: 'cuộc chiến lớn, thế chiến', partOfSpeech: 'danh từ' },
      { kanji: '大半', kana: 'たいはん', romaji: 'taihan', meaning: 'phần lớn, đa số', partOfSpeech: 'danh từ' },
      { kanji: '大部分', kana: 'だいぶぶん', romaji: 'daibubun', meaning: 'phần lớn, đại đa số', partOfSpeech: 'danh từ' },
      { kanji: '大陸', kana: 'たいりく', romaji: 'tairiku', meaning: 'lục địa', partOfSpeech: 'danh từ' },
      { kanji: '宅', kana: 'たく', romaji: 'taku', meaning: 'nhà, nhà riêng', partOfSpeech: 'danh từ' },
      { kanji: '叩きます', kana: 'たたきます', romaji: 'tatakimasu', meaning: 'đập, gõ, vỗ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '達します', kana: 'たっします', romaji: 'tasshimasu', meaning: 'đạt đến, tới nơi', partOfSpeech: 'động từ する' },
    ],
  },
  {
    lessonNumber: 337,
    jlptLevel: 'N3',
    words: [
      { kanji: '奪います', kana: 'うばいます', romaji: 'ubaimasu', meaning: 'cướp đoạt, tước đoạt', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '谷', kana: 'たに', romaji: 'tani', meaning: 'thung lũng', partOfSpeech: 'danh từ' },
      { kanji: '単なる', kana: 'たんなる', romaji: 'tannaru', meaning: 'chỉ đơn thuần là', partOfSpeech: 'từ hạn định' },
      { kanji: '単に', kana: 'たんに', romaji: 'tanni', meaning: 'chỉ đơn giản là', partOfSpeech: 'phó từ' },
      { kanji: '単語', kana: 'たんご', romaji: 'tango', meaning: 'từ vựng, từ đơn', partOfSpeech: 'danh từ' },
      { kanji: '単純', kana: 'たんじゅん', romaji: 'tanjun', meaning: 'đơn giản', partOfSpeech: 'tính từ na' },
      { kanji: '誕生', kana: 'たんじょう', romaji: 'tanjō', meaning: 'sự ra đời, sự chào đời', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '段', kana: 'だん', romaji: 'dan', meaning: 'bậc thang, cấp độ', partOfSpeech: 'danh từ' },
      { kanji: '男の人', kana: 'おとこのひと', romaji: 'otokonohito', meaning: 'người đàn ông', partOfSpeech: 'danh từ' },
      { kanji: '男子', kana: 'だんし', romaji: 'danshi', meaning: 'nam giới, con trai', partOfSpeech: 'danh từ' },
      { kanji: '知恵', kana: 'ちえ', romaji: 'chie', meaning: 'trí tuệ, sự khôn ngoan', partOfSpeech: 'danh từ' },
      { kanji: '知事', kana: 'ちじ', romaji: 'chiji', meaning: 'tỉnh trưởng', partOfSpeech: 'danh từ' },
      { kanji: '地位', kana: 'ちい', romaji: 'chii', meaning: 'địa vị xã hội', partOfSpeech: 'danh từ' },
      { kanji: '地区', kana: 'ちく', romaji: 'chiku', meaning: 'khu vực, vùng', partOfSpeech: 'danh từ' },
      { kanji: '地平線', kana: 'ちへいせん', romaji: 'chiheisen', meaning: 'đường chân trời', partOfSpeech: 'danh từ' },
    ],
  },
];
