// Bổ sung từ vựng N4 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 260-270.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N4: JlptVocabUnit[] = [
  {
    lessonNumber: 260,
    jlptLevel: 'N4',
    words: [
      { kanji: '挨拶します', kana: 'あいさつします', romaji: 'aisatsushimasu', meaning: 'chào hỏi', partOfSpeech: 'động từ する' },
      { kana: 'アクセサリー', romaji: 'akusesarī', meaning: 'đồ trang sức, phụ kiện', partOfSpeech: 'danh từ' },
      { kana: 'アナウンサー', romaji: 'anaunsā', meaning: 'phát thanh viên', partOfSpeech: 'danh từ' },
      { kana: 'アルコール', romaji: 'arukōru', meaning: 'cồn, rượu (nói chung)', partOfSpeech: 'danh từ' },
      { kana: 'あんな', romaji: 'anna', meaning: 'như thế kia', partOfSpeech: 'từ hạn định' },
      { kana: 'いっぱい', romaji: 'ippai', meaning: 'đầy, nhiều', partOfSpeech: 'tính từ na, phó từ' },
      { kana: 'おいでになります', romaji: 'oideninarimasu', meaning: 'có, đến, đi (kính ngữ)', partOfSpeech: 'động từ nhóm 1 (kính ngữ)' },
      { kana: 'おかげ', romaji: 'okage', meaning: 'nhờ có, nhờ vào', partOfSpeech: 'danh từ' },
      { kanji: 'お金持ち', kana: 'おかねもち', romaji: 'okanemochi', meaning: 'người giàu có', partOfSpeech: 'danh từ' },
      { kanji: 'お見舞い', kana: 'おみまい', romaji: 'omimai', meaning: 'sự thăm hỏi (người ốm)', partOfSpeech: 'danh từ' },
      { kanji: 'お祭り', kana: 'おまつり', romaji: 'omatsuri', meaning: 'lễ hội', partOfSpeech: 'danh từ' },
      { kanji: 'お嬢さん', kana: 'おじょうさん', romaji: 'ojōsan', meaning: 'tiểu thư, con gái (người khác, cách gọi lịch sự)', partOfSpeech: 'danh từ' },
      { kana: 'ガソリンスタンド', romaji: 'gasorinsutando', meaning: 'trạm xăng', partOfSpeech: 'danh từ' },
      { kana: 'かっこう', romaji: 'kakkō', meaning: 'hình dáng, dáng vẻ', partOfSpeech: 'danh từ' },
      { kana: 'かまいます', romaji: 'kamaimasu', meaning: 'để ý, bận tâm', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '怪我します', kana: 'けがします', romaji: 'kegashimasu', meaning: 'bị thương', partOfSpeech: 'động từ する' },
      { kana: 'こう', romaji: 'kō', meaning: 'như thế này', partOfSpeech: 'phó từ' },
    ],
  },
  {
    lessonNumber: 261,
    jlptLevel: 'N4',
    words: [
      { kana: 'ごちそう', romaji: 'gochisō', meaning: 'bữa ăn thịnh soạn, sự chiêu đãi', partOfSpeech: 'danh từ' },
      { kana: 'ごらんになります', romaji: 'goranninarimasu', meaning: 'xem, nhìn (kính ngữ)', partOfSpeech: 'động từ nhóm 1 (kính ngữ)' },
      { kanji: 'ご存じ', kana: 'ごぞんじ', romaji: 'gozonji', meaning: 'sự biết, quen biết (kính ngữ)', partOfSpeech: 'danh từ (kính ngữ)' },
      { kana: 'サラダ', romaji: 'sarada', meaning: 'món xà lách, salad', partOfSpeech: 'danh từ' },
      { kana: 'サンダル', romaji: 'sandaru', meaning: 'dép xăng đan', partOfSpeech: 'danh từ' },
      { kana: 'しっかり', romaji: 'shikkari', meaning: 'chắc chắn, vững vàng', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'じゃま', romaji: 'jama', meaning: 'sự cản trở, làm phiền', partOfSpeech: 'danh từ, tính từ na' },
      { kana: 'ジャム', romaji: 'jamu', meaning: 'mứt', partOfSpeech: 'danh từ' },
      { kana: 'スーツケース', romaji: 'sūtsukēsu', meaning: 'va li', partOfSpeech: 'danh từ' },
      { kana: 'すきます', romaji: 'sukimasu', meaning: 'trở nên vắng, trống chỗ', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'スクリーン', romaji: 'sukurīn', meaning: 'màn hình chiếu', partOfSpeech: 'danh từ' },
      { kana: 'すっかり', romaji: 'sukkari', meaning: 'hoàn toàn', partOfSpeech: 'phó từ' },
      { kana: 'すっと', romaji: 'sutto', meaning: 'nhanh chóng, thẳng; nhẹ nhõm', partOfSpeech: 'phó từ' },
      { kana: 'ステーキ', romaji: 'sutēki', meaning: 'món bít tết', partOfSpeech: 'danh từ' },
      { kana: 'すり', romaji: 'suri', meaning: 'kẻ móc túi', partOfSpeech: 'danh từ' },
      { kana: 'それほど', romaji: 'sorehodo', meaning: 'đến mức đó', partOfSpeech: 'phó từ' },
      { kana: 'そろそろ', romaji: 'sorosoro', meaning: 'dần dần, sắp sửa', partOfSpeech: 'phó từ' },
    ],
  },
  {
    lessonNumber: 262,
    jlptLevel: 'N4',
    words: [
      { kana: 'そんな', romaji: 'sonna', meaning: 'như thế đó', partOfSpeech: 'từ hạn định' },
      { kana: 'タイプ', romaji: 'taipu', meaning: 'kiểu, loại', partOfSpeech: 'danh từ' },
      { kana: 'だから', romaji: 'dakara', meaning: 'vì vậy, cho nên', partOfSpeech: 'liên từ' },
      { kana: 'だめ', romaji: 'dame', meaning: 'không được, vô ích', partOfSpeech: 'tính từ na' },
      { kanji: 'チェックします', kana: 'チェックします', romaji: 'chiぇkkushimasu', meaning: 'kiểm tra', partOfSpeech: 'động từ する' },
      { kana: 'ちゃん', romaji: 'chan', meaning: 'hậu tố gọi thân mật (trẻ em, người thân)', partOfSpeech: 'trợ từ' },
      { kana: 'つもり', romaji: 'tsumori', meaning: 'ý định, dự định', partOfSpeech: 'danh từ' },
      { kana: 'テキスト', romaji: 'tekisuto', meaning: 'sách giáo trình', partOfSpeech: 'danh từ' },
      { kana: 'どんどん', romaji: 'dondon', meaning: 'ngày càng, liên tục', partOfSpeech: 'phó từ' },
      { kana: 'なるほど', romaji: 'naruhodo', meaning: 'quả đúng vậy, ra là thế', partOfSpeech: 'phó từ, thán từ' },
      { kanji: '濡れます', kana: 'ぬれます', romaji: 'nuremasu', meaning: 'bị ướt', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'ねっしん', romaji: 'nesshin', meaning: 'sự nhiệt tình, hăng hái', partOfSpeech: 'tính từ na' },
      { kana: 'パート', romaji: 'pāto', meaning: 'làm việc bán thời gian', partOfSpeech: 'danh từ' },
      { kana: 'はず', romaji: 'hazu', meaning: 'lẽ ra, hẳn là', partOfSpeech: 'danh từ hình thức' },
      { kana: 'ハンドバッグ', romaji: 'handobaggu', meaning: 'túi xách tay', partOfSpeech: 'danh từ' },
      { kana: 'ひげ', romaji: 'hige', meaning: 'râu', partOfSpeech: 'danh từ' },
      { kana: 'ファックス', romaji: 'fuぁkkusu', meaning: 'máy fax', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 263,
    jlptLevel: 'N4',
    words: [
      { kana: 'ぶどう', romaji: 'budō', meaning: 'nho', partOfSpeech: 'danh từ' },
      { kana: 'ほど', romaji: 'hodo', meaning: 'chừng mực, mức độ', partOfSpeech: 'trợ từ' },
      { kana: 'まじめ', romaji: 'majime', meaning: 'nghiêm túc, chăm chỉ', partOfSpeech: 'tính từ na' },
      { kana: 'または', romaji: 'mataha', meaning: 'hoặc là', partOfSpeech: 'liên từ' },
      { kana: 'もっとも', romaji: 'mottomo', meaning: 'hết sức, nhất', partOfSpeech: 'phó từ' },
      { kana: 'よろしい', romaji: 'yoroshii', meaning: 'được, tốt (lịch sự)', partOfSpeech: 'tính từ i' },
      { kana: 'レジ', romaji: 'reji', meaning: 'quầy thu ngân', partOfSpeech: 'danh từ' },
      { kanji: '以下', kana: 'いか', romaji: 'ika', meaning: 'trở xuống, dưới mức', partOfSpeech: 'danh từ' },
      { kanji: '以内', kana: 'いない', romaji: 'inai', meaning: 'trong vòng, trong phạm vi', partOfSpeech: 'danh từ' },
      { kanji: '為', kana: 'ため', romaji: 'tame', meaning: 'vì, để', partOfSpeech: 'danh từ hình thức' },
      { kanji: '移ります', kana: 'うつります', romaji: 'utsurimasu', meaning: 'chuyển (nhà, chỗ ở)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '引き出します', kana: 'ひきだします', romaji: 'hikidashimasu', meaning: 'rút (tiền)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '雲', kana: 'くも', romaji: 'kumo', meaning: 'đám mây', partOfSpeech: 'danh từ' },
      { kanji: '泳ぎ方', kana: 'およぎかた', romaji: 'oyogikata', meaning: 'cách bơi', partOfSpeech: 'danh từ' },
      { kanji: '遠慮します', kana: 'えんりょします', romaji: 'enryoshimasu', meaning: 'khách sáo, giữ ý, từ chối khéo', partOfSpeech: 'động từ する' },
      { kanji: '下がります', kana: 'さがります', romaji: 'sagarimasu', meaning: 'hạ xuống, giảm xuống', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '下宿', kana: 'げしゅく', romaji: 'geshuku', meaning: 'nhà trọ, ở trọ', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 264,
    jlptLevel: 'N4',
    words: [
      { kanji: '家内', kana: 'かない', romaji: 'kanai', meaning: 'vợ (cách gọi khiêm nhường)', partOfSpeech: 'danh từ' },
      { kanji: '花見', kana: 'はなみ', romaji: 'hanami', meaning: 'ngắm hoa anh đào', partOfSpeech: 'danh từ' },
      { kanji: '過ぎます', kana: 'すぎます', romaji: 'sugimasu', meaning: 'vượt quá, quá (thời gian, mức độ)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '回ります', kana: 'まわります', romaji: 'mawarimasu', meaning: 'xoay vòng, đi vòng quanh', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '皆', kana: 'みな', romaji: 'mina', meaning: 'tất cả mọi người', partOfSpeech: 'danh từ' },
      { kanji: '開きます', kana: 'ひらきます', romaji: 'hirakimasu', meaning: 'mở, tổ chức (sự kiện)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '割れます', kana: 'われます', romaji: 'waremasu', meaning: 'bị vỡ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '乾きます', kana: 'かわきます', romaji: 'kawakimasu', meaning: 'khô đi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '看護婦', kana: 'かんごふ', romaji: 'kangofu', meaning: 'y tá (nữ)', partOfSpeech: 'danh từ' },
      { kanji: '簡単', kana: 'かんたん', romaji: 'kantan', meaning: 'đơn giản', partOfSpeech: 'tính từ na' },
      { kanji: '客', kana: 'きゃく', romaji: 'kyaku', meaning: 'khách, khách hàng', partOfSpeech: 'danh từ' },
      { kanji: '競争', kana: 'きょうそう', romaji: 'kyōsō', meaning: 'sự cạnh tranh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '計画します', kana: 'けいかくします', romaji: 'keikakushimasu', meaning: 'lập kế hoạch', partOfSpeech: 'động từ する' },
      { kanji: '決して', kana: 'けっして', romaji: 'kesshite', meaning: 'quyết không, nhất định không', partOfSpeech: 'phó từ' },
      { kanji: '絹', kana: 'きぬ', romaji: 'kinu', meaning: 'lụa, tơ', partOfSpeech: 'danh từ' },
      { kanji: '見えます', kana: 'みえます', romaji: 'miemasu', meaning: 'nhìn thấy được, hiện rõ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '見つかります', kana: 'みつかります', romaji: 'mitsukarimasu', meaning: 'được tìm thấy', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 265,
    jlptLevel: 'N4',
    words: [
      { kanji: '見物', kana: 'けんぶつ', romaji: 'kenbutsu', meaning: 'sự tham quan, ngắm cảnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '故障します', kana: 'こしょうします', romaji: 'koshōshimasu', meaning: 'bị hỏng, trục trặc', partOfSpeech: 'động từ する' },
      { kanji: '湖', kana: 'みずうみ', romaji: 'mizūmi', meaning: 'hồ', partOfSpeech: 'danh từ' },
      { kanji: '光ります', kana: 'ひかります', romaji: 'hikarimasu', meaning: 'phát sáng, lấp lánh', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '校長', kana: 'こうちょう', romaji: 'kōchō', meaning: 'hiệu trưởng', partOfSpeech: 'danh từ' },
      { kanji: '降り出します', kana: 'ふりだします', romaji: 'furidashimasu', meaning: 'bắt đầu mưa, bắt đầu rơi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '高校生', kana: 'こうこうせい', romaji: 'kōkōsei', meaning: 'học sinh cấp 3', partOfSpeech: 'danh từ' },
      { kanji: '高等学校', kana: 'こうとうがっこう', romaji: 'kōtōgakkō', meaning: 'trường trung học phổ thông', partOfSpeech: 'danh từ' },
      { kanji: '込みます', kana: 'こみます', romaji: 'komimasu', meaning: 'đông đúc, chật ních', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '差し上げます', kana: 'さしあげます', romaji: 'sashiagemasu', meaning: 'biếu, tặng (khiêm nhường)', partOfSpeech: 'động từ nhóm 2 (khiêm ngữ)' },
      { kanji: '砂', kana: 'すな', romaji: 'suna', meaning: 'cát', partOfSpeech: 'danh từ' },
      { kanji: '最後', kana: 'さいご', romaji: 'saigo', meaning: 'cuối cùng', partOfSpeech: 'danh từ' },
      { kanji: '最初', kana: 'さいしょ', romaji: 'saisho', meaning: 'đầu tiên, ban đầu', partOfSpeech: 'danh từ' },
      { kanji: '妻', kana: 'つま', romaji: 'tsuma', meaning: 'vợ (cách gọi khiêm nhường)', partOfSpeech: 'danh từ' },
      { kanji: '坂', kana: 'さか', romaji: 'saka', meaning: 'con dốc', partOfSpeech: 'danh từ' },
      { kanji: '子', kana: 'こ', romaji: 'ko', meaning: 'đứa trẻ, con', partOfSpeech: 'danh từ' },
      { kanji: '市', kana: 'し', romaji: 'shi', meaning: 'thành phố', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 266,
    jlptLevel: 'N4',
    words: [
      { kanji: '市民', kana: 'しみん', romaji: 'shimin', meaning: 'thị dân, công dân thành phố', partOfSpeech: 'danh từ' },
      { kanji: '支度します', kana: 'したくします', romaji: 'shitakushimasu', meaning: 'chuẩn bị (đồ đạc, việc)', partOfSpeech: 'động từ する' },
      { kanji: '止みます', kana: 'やみます', romaji: 'yamimasu', meaning: 'ngừng, tạnh (mưa)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '糸', kana: 'いと', romaji: 'ito', meaning: 'sợi chỉ', partOfSpeech: 'danh từ' },
      { kanji: '時代', kana: 'じだい', romaji: 'jidai', meaning: 'thời đại', partOfSpeech: 'danh từ' },
      { kanji: '辞典', kana: 'じてん', romaji: 'jiten', meaning: 'từ điển', partOfSpeech: 'danh từ' },
      { kanji: '写します', kana: 'うつします', romaji: 'utsushimasu', meaning: 'chụp, sao chép', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '受けます', kana: 'うけます', romaji: 'ukemasu', meaning: 'tham gia (thi, học), nhận', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '出席します', kana: 'しゅっせきします', romaji: 'shussekishimasu', meaning: 'tham dự, có mặt', partOfSpeech: 'động từ する' },
      { kanji: '小鳥', kana: 'ことり', romaji: 'kotori', meaning: 'chim nhỏ', partOfSpeech: 'danh từ' },
      { kanji: '承知します', kana: 'しょうちします', romaji: 'shōchishimasu', meaning: 'đồng ý, chấp thuận', partOfSpeech: 'động từ する' },
      { kanji: '消しゴム', kana: 'けしゴム', romaji: 'keshigomu', meaning: 'cục tẩy', partOfSpeech: 'danh từ' },
      { kanji: '焼けます', kana: 'やけます', romaji: 'yakemasu', meaning: 'bị cháy, được nướng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '上がります', kana: 'あがります', romaji: 'agarimasu', meaning: 'tăng lên, đi lên', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '場合', kana: 'ばあい', romaji: 'bāi', meaning: 'trường hợp', partOfSpeech: 'danh từ' },
      { kanji: '畳', kana: 'たたみ', romaji: 'tatami', meaning: 'chiếu tatami', partOfSpeech: 'danh từ' },
      { kanji: '食料品', kana: 'しょくりょうひん', romaji: 'shokuryōhin', meaning: 'thực phẩm', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 267,
    jlptLevel: 'N4',
    words: [
      { kanji: '寝坊', kana: 'ねぼう', romaji: 'nebō', meaning: 'sự ngủ dậy muộn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '森', kana: 'もり', romaji: 'mori', meaning: 'rừng', partOfSpeech: 'danh từ' },
      { kanji: '申し上げます', kana: 'もうしあげます', romaji: 'mōshiagemasu', meaning: 'nói, thưa (khiêm nhường)', partOfSpeech: 'động từ nhóm 2 (khiêm ngữ)' },
      { kanji: '親切', kana: 'しんせつ', romaji: 'shinsetsu', meaning: 'tử tế, tốt bụng', partOfSpeech: 'tính từ na' },
      { kanji: '数学', kana: 'すうがく', romaji: 'sūgaku', meaning: 'môn toán', partOfSpeech: 'danh từ' },
      { kanji: '世話します', kana: 'せわします', romaji: 'sewashimasu', meaning: 'chăm sóc, trông nom', partOfSpeech: 'động từ する' },
      { kanji: '生産します', kana: 'せいさんします', romaji: 'seisanshimasu', meaning: 'sản xuất', partOfSpeech: 'động từ する' },
      { kanji: '盛ん', kana: 'さかん', romaji: 'sakan', meaning: 'thịnh vượng, sôi nổi', partOfSpeech: 'tính từ na' },
      { kanji: '西洋', kana: 'せいよう', romaji: 'seiyō', meaning: 'phương Tây', partOfSpeech: 'danh từ' },
      { kanji: '赤ん坊', kana: 'あかんぼう', romaji: 'akanbō', meaning: 'em bé', partOfSpeech: 'danh từ' },
      { kanji: '折れます', kana: 'おれます', romaji: 'oremasu', meaning: 'bị gãy', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '草', kana: 'くさ', romaji: 'kusa', meaning: 'cỏ', partOfSpeech: 'danh từ' },
      { kanji: '足します', kana: 'たします', romaji: 'tashimasu', meaning: 'cộng thêm, thêm vào', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '卒業', kana: 'そつぎょう', romaji: 'sotsugyō', meaning: 'sự tốt nghiệp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '打ちます', kana: 'うちます', romaji: 'uchimasu', meaning: 'đánh, gõ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '代わり', kana: 'かわり', romaji: 'kawari', meaning: 'sự thay thế', partOfSpeech: 'danh từ' },
      { kanji: '大事', kana: 'だいじ', romaji: 'daiji', meaning: 'quan trọng, quý giá', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 268,
    jlptLevel: 'N4',
    words: [
      { kanji: '大分', kana: 'だいぶ', romaji: 'daibu', meaning: 'khá nhiều, phần lớn', partOfSpeech: 'phó từ' },
      { kanji: '地理', kana: 'ちり', romaji: 'chiri', meaning: 'địa lý', partOfSpeech: 'danh từ' },
      { kanji: '虫', kana: 'むし', romaji: 'mushi', meaning: 'côn trùng', partOfSpeech: 'danh từ' },
      { kanji: '丁寧', kana: 'ていねい', romaji: 'teinei', meaning: 'lịch sự, cẩn thận', partOfSpeech: 'tính từ na' },
      { kanji: '通います', kana: 'かよいます', romaji: 'kayoimasu', meaning: 'đi lại thường xuyên (đi làm, đi học)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '通ります', kana: 'とおります', romaji: 'tōrimasu', meaning: 'đi qua', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '釣ります', kana: 'つります', romaji: 'tsurimasu', meaning: 'câu (cá)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '適当', kana: 'てきとう', romaji: 'tekitō', meaning: 'thích hợp; qua loa', partOfSpeech: 'tính từ na' },
      { kanji: '店員', kana: 'てんいん', romaji: 'tenin', meaning: 'nhân viên cửa hàng', partOfSpeech: 'danh từ' },
      { kanji: '塗ります', kana: 'ぬります', romaji: 'nurimasu', meaning: 'sơn, quét, bôi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '盗みます', kana: 'ぬすみます', romaji: 'nusumimasu', meaning: 'ăn trộm', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '湯', kana: 'ゆ', romaji: 'yu', meaning: 'nước nóng', partOfSpeech: 'danh từ' },
      { kanji: '特別', kana: 'とくべつ', romaji: 'tokubetsu', meaning: 'đặc biệt', partOfSpeech: 'tính từ na' },
      { kanji: '二階建て', kana: 'にかいだて', romaji: 'nikaidate', meaning: 'nhà hai tầng', partOfSpeech: 'danh từ' },
      { kanji: '倍', kana: 'ばい', romaji: 'bai', meaning: 'gấp đôi, lần', partOfSpeech: 'danh từ' },
      { kanji: '彼ら', kana: 'かれら', romaji: 'karera', meaning: 'họ, bọn họ', partOfSpeech: 'đại từ' },
      { kanji: '非常に', kana: 'ひじょうに', romaji: 'hijōni', meaning: 'cực kỳ, vô cùng', partOfSpeech: 'phó từ' },
    ],
  },
  {
    lessonNumber: 269,
    jlptLevel: 'N4',
    words: [
      { kanji: '飛行場', kana: 'ひこうじょう', romaji: 'hikōjō', meaning: 'sân bay', partOfSpeech: 'danh từ' },
      { kanji: '必要', kana: 'ひつよう', romaji: 'hitsuyō', meaning: 'cần thiết', partOfSpeech: 'tính từ na' },
      { kanji: '夫', kana: 'おっと', romaji: 'otto', meaning: 'chồng', partOfSpeech: 'danh từ' },
      { kanji: '復習', kana: 'ふくしゅう', romaji: 'fukushū', meaning: 'sự ôn tập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '複雑', kana: 'ふくざつ', romaji: 'fukuzatsu', meaning: 'phức tạp', partOfSpeech: 'tính từ na' },
      { kanji: '聞こえます', kana: 'きこえます', romaji: 'kikoemasu', meaning: 'nghe thấy được', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '別', kana: 'べつ', romaji: 'betsu', meaning: 'khác, riêng biệt', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '捕まえます', kana: 'つかまえます', romaji: 'tsukamaemasu', meaning: 'bắt giữ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '味噌', kana: 'みそ', romaji: 'miso', meaning: 'tương miso', partOfSpeech: 'danh từ' },
      { kanji: '無理', kana: 'むり', romaji: 'muri', meaning: 'không thể, quá sức', partOfSpeech: 'tính từ na' },
      { kanji: '毛', kana: 'け', romaji: 'ke', meaning: 'lông, tóc', partOfSpeech: 'danh từ' },
      { kanji: '木綿', kana: 'もめん', romaji: 'momen', meaning: 'vải bông, cotton', partOfSpeech: 'danh từ' },
      { kanji: '訳', kana: 'わけ', romaji: 'wake', meaning: 'lý do, ý nghĩa', partOfSpeech: 'danh từ' },
      { kanji: '遊び', kana: 'あそび', romaji: 'asobi', meaning: 'sự chơi đùa, trò chơi', partOfSpeech: 'danh từ' },
      { kanji: '予習', kana: 'よしゅう', romaji: 'yoshū', meaning: 'sự chuẩn bị bài trước khi học', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '揺れます', kana: 'ゆれます', romaji: 'yuremasu', meaning: 'lắc lư, rung động', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '踊り', kana: 'おどり', romaji: 'odori', meaning: 'điệu nhảy, điệu múa', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 270,
    jlptLevel: 'N4',
    words: [
      { kanji: '落ちます', kana: 'おちます', romaji: 'ochimasu', meaning: 'rơi xuống, rớt', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '両方', kana: 'りょうほう', romaji: 'ryōhō', meaning: 'cả hai phía', partOfSpeech: 'danh từ' },
      { kanji: '林', kana: 'はやし', romaji: 'hayashi', meaning: 'rừng cây (nhỏ hơn 森)', partOfSpeech: 'danh từ' },
      { kanji: '冷えます', kana: 'ひえます', romaji: 'hiemasu', meaning: 'trở nên lạnh', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '連れます', kana: 'つれます', romaji: 'tsuremasu', meaning: 'dẫn theo, đưa theo', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '腕', kana: 'うで', romaji: 'ude', meaning: 'cánh tay', partOfSpeech: 'danh từ' },
      { kanji: '用', kana: 'よう', romaji: 'yō', meaning: 'việc, công việc cần làm', partOfSpeech: 'danh từ' },
    ],
  },
];
