// Bổ sung từ vựng N2 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 748-753.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N2_PART9: JlptVocabUnit[] = [
  {
    lessonNumber: 748,
    jlptLevel: 'N2',
    words: [
      { kanji: '垂直', kana: 'すいちょく', romaji: 'suichoku', meaning: 'phương thẳng đứng, vuông góc', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '推定', kana: 'すいてい', romaji: 'suitei', meaning: 'sự suy đoán, ước tính', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '水産', kana: 'すいさん', romaji: 'suisan', meaning: 'thủy sản', partOfSpeech: 'danh từ' },
      { kanji: '水蒸気', kana: 'すいじょうき', romaji: 'suijōki', meaning: 'hơi nước', partOfSpeech: 'danh từ' },
      { kanji: '水素', kana: 'すいそ', romaji: 'suiso', meaning: 'khí hydro', partOfSpeech: 'danh từ' },
      { kanji: '水滴', kana: 'すいてき', romaji: 'suiteki', meaning: 'giọt nước', partOfSpeech: 'danh từ' },
      { kanji: '水筒', kana: 'すいとう', romaji: 'suitō', meaning: 'bình nước cá nhân', partOfSpeech: 'danh từ' },
      { kanji: '水分', kana: 'すいぶん', romaji: 'suibun', meaning: 'độ ẩm, hàm lượng nước', partOfSpeech: 'danh từ' },
      { kanji: '水平', kana: 'すいへい', romaji: 'suihei', meaning: 'phương ngang, mặt phẳng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '水平線', kana: 'すいへいせん', romaji: 'suiheisen', meaning: 'đường chân trời (trên biển)', partOfSpeech: 'danh từ' },
      { kanji: '炊事', kana: 'すいじ', romaji: 'suiji', meaning: 'việc nấu ăn, bếp núc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '酔っ払い', kana: 'よっぱらい', romaji: 'yopparai', meaning: 'người say rượu', partOfSpeech: 'danh từ' },
      { kanji: '随筆', kana: 'ずいひつ', romaji: 'zuihitsu', meaning: 'tùy bút', partOfSpeech: 'danh từ' },
      { kanji: '杉', kana: 'すぎ', romaji: 'sugi', meaning: 'cây tuyết tùng Nhật', partOfSpeech: 'danh từ' },
      { kanji: '寸法', kana: 'すんぽう', romaji: 'sunpō', meaning: 'kích thước, số đo', partOfSpeech: 'danh từ' },
      { kanji: '瀬戸物', kana: 'せともの', romaji: 'setomono', meaning: 'đồ gốm sứ', partOfSpeech: 'danh từ' },
      { kanji: '性能', kana: 'せいのう', romaji: 'seinō', meaning: 'hiệu năng, tính năng', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 749,
    jlptLevel: 'N2',
    words: [
      { kanji: '成分', kana: 'せいぶん', romaji: 'seibun', meaning: 'thành phần', partOfSpeech: 'danh từ' },
      { kanji: '成立', kana: 'せいりつ', romaji: 'seiritsu', meaning: 'sự thành lập, hình thành', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '政党', kana: 'せいとう', romaji: 'seitō', meaning: 'đảng phái chính trị', partOfSpeech: 'danh từ' },
      { kanji: '整います', kana: 'ととのいます', romaji: 'totonoimasu', meaning: 'được chuẩn bị sẵn sàng, trật tự', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '整数', kana: 'せいすう', romaji: 'seisū', meaning: 'số nguyên', partOfSpeech: 'danh từ' },
      { kanji: '整備', kana: 'せいび', romaji: 'seibi', meaning: 'sự bảo dưỡng, hoàn thiện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '正方形', kana: 'せいほうけい', romaji: 'seihōkei', meaning: 'hình vuông', partOfSpeech: 'danh từ' },
      { kanji: '正味', kana: 'しょうみ', romaji: 'shōmi', meaning: 'trọng lượng tịnh, thực chất', partOfSpeech: 'danh từ' },
      { kanji: '正面', kana: 'しょうめん', romaji: 'shōmen', meaning: 'mặt trước, chính diện', partOfSpeech: 'danh từ' },
      { kanji: '正門', kana: 'せいもん', romaji: 'seimon', meaning: 'cổng chính', partOfSpeech: 'danh từ' },
      { kanji: '清い', kana: 'きよい', romaji: 'kiyoi', meaning: 'trong sạch, thanh khiết', partOfSpeech: 'tính từ i' },
      { kanji: '清書', kana: 'せいしょ', romaji: 'seisho', meaning: 'bản sạch, bản chính thức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '清掃', kana: 'せいそう', romaji: 'seisō', meaning: 'sự dọn dẹp, vệ sinh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '生えます', kana: 'はえます', romaji: 'haemasu', meaning: 'mọc lên (cây, tóc, răng)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '生き生き', kana: 'いきいき', romaji: 'ikiiki', meaning: 'sống động, tràn đầy sức sống', partOfSpeech: 'phó từ, động từ する' },
      { kanji: '生意気', kana: 'なまいき', romaji: 'namaiki', meaning: 'hỗn xược, láo xược', partOfSpeech: 'tính từ na' },
      { kanji: '生存', kana: 'せいぞん', romaji: 'seizon', meaning: 'sự sinh tồn', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 750,
    jlptLevel: 'N2',
    words: [
      { kanji: '生年月日', kana: 'せいねんがっぴ', romaji: 'seinengappi', meaning: 'ngày tháng năm sinh', partOfSpeech: 'danh từ' },
      { kanji: '盛ります', kana: 'もります', romaji: 'morimasu', meaning: 'xới, bày (đồ ăn) lên', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '西暦', kana: 'せいれき', romaji: 'seireki', meaning: 'công lịch, dương lịch', partOfSpeech: 'danh từ' },
      { kanji: '誓います', kana: 'ちかいます', romaji: 'chikaimasu', meaning: 'thề, tuyên thệ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '青少年', kana: 'せいしょうねん', romaji: 'seishōnen', meaning: 'thanh thiếu niên', partOfSpeech: 'danh từ' },
      { kanji: '青白い', kana: 'あおじろい', romaji: 'aojiroi', meaning: 'xanh xao, nhợt nhạt', partOfSpeech: 'tính từ i' },
      { kanji: '静まります', kana: 'しずまります', romaji: 'shizumarimasu', meaning: 'lắng xuống, trở nên yên tĩnh', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '税関', kana: 'ぜいかん', romaji: 'zeikan', meaning: 'hải quan', partOfSpeech: 'danh từ' },
      { kanji: '惜しい', kana: 'おしい', romaji: 'oshii', meaning: 'đáng tiếc, đáng quý', partOfSpeech: 'tính từ i' },
      { kanji: '赤道', kana: 'せきどう', romaji: 'sekidō', meaning: 'đường xích đạo', partOfSpeech: 'danh từ' },
      { kanji: '接します', kana: 'せっします', romaji: 'sesshimasu', meaning: 'tiếp xúc, giáp ranh', partOfSpeech: 'động từ する' },
      { kanji: '接近', kana: 'せっきん', romaji: 'sekkin', meaning: 'sự tiếp cận, đến gần', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '絶えず', kana: 'たえず', romaji: 'taezu', meaning: 'không ngừng, liên tục', partOfSpeech: 'phó từ' },
      { kanji: '先々月', kana: 'せんせんげつ', romaji: 'sensengetsu', meaning: 'tháng trước nữa (2 tháng trước)', partOfSpeech: 'danh từ' },
      { kanji: '先祖', kana: 'せんぞ', romaji: 'senzo', meaning: 'tổ tiên', partOfSpeech: 'danh từ' },
      { kanji: '先端', kana: 'せんたん', romaji: 'sentan', meaning: 'đầu mút, mũi nhọn', partOfSpeech: 'danh từ' },
      { kanji: '先程', kana: 'さきほど', romaji: 'sakihodo', meaning: 'vừa nãy, lúc nãy', partOfSpeech: 'phó từ' },
    ],
  },
  {
    lessonNumber: 751,
    jlptLevel: 'N2',
    words: [
      { kanji: '先頭', kana: 'せんとう', romaji: 'sentō', meaning: 'hàng đầu, dẫn đầu', partOfSpeech: 'danh từ' },
      { kanji: '占います', kana: 'うらないます', romaji: 'uranaimasu', meaning: 'bói toán, dự đoán', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '尖ります', kana: 'とがります', romaji: 'togarimasu', meaning: 'nhọn, sắc; cau có', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '扇ぎます', kana: 'あおぎます', romaji: 'aogimasu', meaning: 'quạt (gió)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '扇子', kana: 'せんす', romaji: 'sensu', meaning: 'quạt xếp', partOfSpeech: 'danh từ' },
      { kanji: '扇風機', kana: 'せんぷうき', romaji: 'senpūki', meaning: 'quạt điện', partOfSpeech: 'danh từ' },
      { kanji: '潜ります', kana: 'もぐります', romaji: 'mogurimasu', meaning: 'lặn, chui vào', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '線路', kana: 'せんろ', romaji: 'senro', meaning: 'đường ray', partOfSpeech: 'danh từ' },
      { kanji: '羨ましい', kana: 'うらやましい', romaji: 'urayamashii', meaning: 'đáng ghen tị', partOfSpeech: 'tính từ i' },
      { kanji: '羨みます', kana: 'うらやみます', romaji: 'urayamimasu', meaning: 'ghen tị, ganh tị', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '全集', kana: 'ぜんしゅう', romaji: 'zenshū', meaning: 'toàn tập (tác phẩm)', partOfSpeech: 'danh từ' },
      { kanji: '全般', kana: 'ぜんぱん', romaji: 'zenpan', meaning: 'toàn bộ, nói chung', partOfSpeech: 'danh từ' },
      { kanji: '狙い', kana: 'ねらい', romaji: 'nerai', meaning: 'mục tiêu, ý đồ', partOfSpeech: 'danh từ' },
      { kanji: '狙います', kana: 'ねらいます', romaji: 'neraimasu', meaning: 'nhắm vào, nhắm tới', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '祖先', kana: 'そせん', romaji: 'sosen', meaning: 'tổ tiên', partOfSpeech: 'danh từ' },
      { kanji: '素質', kana: 'そしつ', romaji: 'soshitsu', meaning: 'tố chất, tư chất', partOfSpeech: 'danh từ' },
      { kanji: '素人', kana: 'しろうと', romaji: 'shirōto', meaning: 'người nghiệp dư, tay ngang', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 752,
    jlptLevel: 'N2',
    words: [
      { kanji: '素直', kana: 'すなお', romaji: 'sunao', meaning: 'ngoan ngoãn, thật thà', partOfSpeech: 'tính từ na' },
      { kanji: '組合せ', kana: 'くみあわせ', romaji: 'kumiawase', meaning: 'sự kết hợp, tổ hợp', partOfSpeech: 'danh từ' },
      { kanji: '蘇ります', kana: 'よみがえります', romaji: 'yomigaerimasu', meaning: 'hồi sinh, sống lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '遡ります', kana: 'さかのぼります', romaji: 'sakanoborimasu', meaning: 'ngược dòng, truy ngược về quá khứ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '創作', kana: 'そうさく', romaji: 'sōsaku', meaning: 'sự sáng tác', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '早口', kana: 'はやくち', romaji: 'hayakuchi', meaning: 'nói nhanh', partOfSpeech: 'danh từ' },
      { kanji: '早速', kana: 'さっそく', romaji: 'sassoku', meaning: 'ngay lập tức, không chậm trễ', partOfSpeech: 'phó từ' },
      { kanji: '争います', kana: 'あらそいます', romaji: 'arasoimasu', meaning: 'tranh cãi, tranh giành', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '相違', kana: 'そうい', romaji: 'sōi', meaning: 'sự khác biệt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '総理大臣', kana: 'そうりだいじん', romaji: 'sōridaijin', meaning: 'thủ tướng', partOfSpeech: 'danh từ' },
      { kanji: '草履', kana: 'ぞうり', romaji: 'zōri', meaning: 'dép rơm/dép Nhật truyền thống', partOfSpeech: 'danh từ' },
      { kanji: '葬式', kana: 'そうしき', romaji: 'sōshiki', meaning: 'đám tang', partOfSpeech: 'danh từ' },
      { kanji: '送り仮名', kana: 'おくりがな', romaji: 'okurigana', meaning: 'phần kana viết kèm sau chữ Hán', partOfSpeech: 'danh từ' },
      { kanji: '送別', kana: 'そうべつ', romaji: 'sōbetsu', meaning: 'sự tiễn biệt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '送料', kana: 'そうりょう', romaji: 'sōryō', meaning: 'phí gửi hàng, cước phí', partOfSpeech: 'danh từ' },
      { kanji: '騒々しい', kana: 'そうぞうしい', romaji: 'sōzōshii', meaning: 'ồn ào, náo động', partOfSpeech: 'tính từ i' },
      { kanji: '増減', kana: 'ぞうげん', romaji: 'zōgen', meaning: 'sự tăng giảm', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 753,
    jlptLevel: 'N2',
    words: [
      { kanji: '増大', kana: 'ぞうだい', romaji: 'zōdai', meaning: 'sự gia tăng, mở rộng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '憎い', kana: 'にくい', romaji: 'nikui', meaning: 'đáng ghét, đáng căm ghét', partOfSpeech: 'tính từ i' },
      { kanji: '憎みます', kana: 'にくみます', romaji: 'nikumimasu', meaning: 'căm ghét, thù ghét', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '憎らしい', kana: 'にくらしい', romaji: 'nikurashii', meaning: 'đáng ghét, khả ố', partOfSpeech: 'tính từ i' },
      { kanji: '造船', kana: 'ぞうせん', romaji: 'zōsen', meaning: 'sự đóng tàu', partOfSpeech: 'danh từ' },
      { kanji: '測量', kana: 'そくりょう', romaji: 'sokuryō', meaning: 'sự đo đạc, khảo sát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '足跡', kana: 'あしあと', romaji: 'ashiato', meaning: 'dấu chân', partOfSpeech: 'danh từ' },
      { kanji: '速力', kana: 'そくりょく', romaji: 'sokuryoku', meaning: 'tốc độ', partOfSpeech: 'danh từ' },
      { kanji: '属します', kana: 'ぞくします', romaji: 'zokushimasu', meaning: 'thuộc về, trực thuộc', partOfSpeech: 'động từ する' },
      { kanji: '続々', kana: 'ぞくぞく', romaji: 'zokuzoku', meaning: 'liên tiếp, dồn dập', partOfSpeech: 'phó từ' },
      { kanji: '揃います', kana: 'そろいます', romaji: 'soroimasu', meaning: 'đầy đủ, tập hợp đủ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '揃えます', kana: 'そろえます', romaji: 'soroemasu', meaning: 'sắp xếp đồng đều, chuẩn bị đủ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '損得', kana: 'そんとく', romaji: 'sontoku', meaning: 'lời lỗ, được mất', partOfSpeech: 'danh từ' },
    ],
  },
];
