// Bổ sung từ vựng N3 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 344-349.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N3_PART7: JlptVocabUnit[] = [
  {
    lessonNumber: 344,
    jlptLevel: 'N3',
    words: [
      { kanji: '発行', kana: 'はっこう', romaji: 'hakkō', meaning: 'sự phát hành, xuất bản', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発車', kana: 'はっしゃ', romaji: 'hassha', meaning: 'xe khởi hành', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '髪の毛', kana: 'かみのけ', romaji: 'kaminoke', meaning: 'tóc', partOfSpeech: 'danh từ' },
      { kanji: '罰します', kana: 'ばっします', romaji: 'basshimasu', meaning: 'trừng phạt', partOfSpeech: 'động từ する' },
      { kanji: '抜きます', kana: 'ぬきます', romaji: 'nukimasu', meaning: 'rút ra, nhổ ra; bỏ qua', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '抜けます', kana: 'ぬけます', romaji: 'nukemasu', meaning: 'rơi ra, tuột ra; bị thiếu', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '半ば', kana: 'なかば', romaji: 'nakaba', meaning: 'giữa chừng, một nửa', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '反抗', kana: 'はんこう', romaji: 'hankō', meaning: 'sự phản kháng, chống đối', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '板', kana: 'いた', romaji: 'ita', meaning: 'tấm ván', partOfSpeech: 'danh từ' },
      { kanji: '犯罪', kana: 'はんざい', romaji: 'hanzai', meaning: 'tội phạm', partOfSpeech: 'danh từ' },
      { kanji: '飯', kana: 'めし', romaji: 'meshi', meaning: 'cơm, bữa ăn (cách nói suồng sã)', partOfSpeech: 'danh từ' },
      { kanji: '悲しみます', kana: 'かなしみます', romaji: 'kanashimimasu', meaning: 'buồn bã, đau buồn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '悲劇', kana: 'ひげき', romaji: 'higeki', meaning: 'bi kịch', partOfSpeech: 'danh từ' },
      { kanji: '疲れ', kana: 'つかれ', romaji: 'tsukare', meaning: 'sự mệt mỏi', partOfSpeech: 'danh từ' },
      { kanji: '非常', kana: 'ひじょう', romaji: 'hijō', meaning: 'khẩn cấp, phi thường', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '飛ばします', kana: 'とばします', romaji: 'tobashimasu', meaning: 'cho bay; bỏ qua', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '飛び出します', kana: 'とびだします', romaji: 'tobidashimasu', meaning: 'lao ra, nhảy vọt ra', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 345,
    jlptLevel: 'N3',
    words: [
      { kanji: '飛行', kana: 'ひこう', romaji: 'hikō', meaning: 'sự bay, hàng không', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '備えます', kana: 'そなえます', romaji: 'sonaemasu', meaning: 'trang bị, chuẩn bị sẵn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '微笑みます', kana: 'ほほえみます', romaji: 'hohoemimasu', meaning: 'mỉm cười', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '微妙', kana: 'びみょう', romaji: 'bimyō', meaning: 'tinh tế, tế nhị', partOfSpeech: 'tính từ na' },
      { kanji: '美人', kana: 'びじん', romaji: 'bijin', meaning: 'người đẹp', partOfSpeech: 'danh từ' },
      { kanji: '膝', kana: 'ひざ', romaji: 'hiza', meaning: 'đầu gối', partOfSpeech: 'danh từ' },
      { kanji: '必ずしも', kana: 'かならずしも', romaji: 'kanarazushimo', meaning: 'không hẳn là, không nhất thiết (đi với phủ định)', partOfSpeech: 'phó từ' },
      { kanji: '必死', kana: 'ひっし', romaji: 'hisshi', meaning: 'sự liều mạng, cố gắng hết sức', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '筆', kana: 'ふで', romaji: 'fude', meaning: 'bút lông', partOfSpeech: 'danh từ' },
      { kanji: '表', kana: 'ひょう', romaji: 'hyō', meaning: 'bảng biểu', partOfSpeech: 'danh từ' },
      { kanji: '表情', kana: 'ひょうじょう', romaji: 'hyōjō', meaning: 'biểu cảm khuôn mặt', partOfSpeech: 'danh từ' },
      { kanji: '表面', kana: 'ひょうめん', romaji: 'hyōmen', meaning: 'bề mặt', partOfSpeech: 'danh từ' },
      { kanji: '描きます', kana: 'えがきます', romaji: 'egakimasu', meaning: 'vẽ, mô tả', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '品', kana: 'しな', romaji: 'shina', meaning: 'món hàng, vật phẩm', partOfSpeech: 'danh từ' },
      { kanji: '貧しい', kana: 'まずしい', romaji: 'mazushii', meaning: 'nghèo khó', partOfSpeech: 'tính từ i' },
      { kanji: '不安', kana: 'ふあん', romaji: 'fuan', meaning: 'sự bất an, lo lắng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '不可', kana: 'ふか', romaji: 'fuka', meaning: 'không được phép, không ổn', partOfSpeech: 'danh từ, tính từ na' },
    ],
  },
  {
    lessonNumber: 346,
    jlptLevel: 'N3',
    words: [
      { kanji: '不幸', kana: 'ふこう', romaji: 'fukō', meaning: 'sự bất hạnh, tai họa', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '不思議', kana: 'ふしぎ', romaji: 'fushigi', meaning: 'kỳ lạ, khó hiểu', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '不自由', kana: 'ふじゆう', romaji: 'fujiyū', meaning: 'sự bất tiện, thiếu thốn', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '不正', kana: 'ふせい', romaji: 'fusei', meaning: 'sự bất chính, gian lận', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '不平', kana: 'ふへい', romaji: 'fuhei', meaning: 'lời phàn nàn, sự bất mãn', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '不利', kana: 'ふり', romaji: 'furi', meaning: 'bất lợi', partOfSpeech: 'tính từ na' },
      { kanji: '付き合い', kana: 'つきあい', romaji: 'tsukiai', meaning: 'sự giao thiệp, qua lại', partOfSpeech: 'danh từ' },
      { kanji: '夫人', kana: 'ふじん', romaji: 'fujin', meaning: 'phu nhân, vợ', partOfSpeech: 'danh từ' },
      { kanji: '布', kana: 'ぬの', romaji: 'nuno', meaning: 'vải', partOfSpeech: 'danh từ' },
      { kanji: '普段', kana: 'ふだん', romaji: 'fudan', meaning: 'bình thường, thường ngày', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '父親', kana: 'ちちおや', romaji: 'chichioya', meaning: 'cha, bố', partOfSpeech: 'danh từ' },
      { kanji: '腐ります', kana: 'くさります', romaji: 'kusarimasu', meaning: 'thối rữa, hỏng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '負け', kana: 'まけ', romaji: 'make', meaning: 'sự thua cuộc', partOfSpeech: 'danh từ' },
      { kanji: '武器', kana: 'ぶき', romaji: 'buki', meaning: 'vũ khí', partOfSpeech: 'danh từ' },
      { kanji: '部分', kana: 'ぶぶん', romaji: 'bubun', meaning: 'bộ phận, phần', partOfSpeech: 'danh từ' },
      { kanji: '風景', kana: 'ふうけい', romaji: 'fūkei', meaning: 'phong cảnh', partOfSpeech: 'danh từ' },
      { kanji: '幅', kana: 'はば', romaji: 'haba', meaning: 'chiều rộng', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 347,
    jlptLevel: 'N3',
    words: [
      { kanji: '服装', kana: 'ふくそう', romaji: 'fukusō', meaning: 'trang phục', partOfSpeech: 'danh từ' },
      { kanji: '覆います', kana: 'おおいます', romaji: 'ōimasu', meaning: 'che phủ, bao trùm', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '仏', kana: 'ほとけ', romaji: 'hotoke', meaning: 'Phật, tượng Phật', partOfSpeech: 'danh từ' },
      { kanji: '物音', kana: 'ものおと', romaji: 'monōto', meaning: 'tiếng động', partOfSpeech: 'danh từ' },
      { kanji: '物事', kana: 'ものごと', romaji: 'monogoto', meaning: 'sự việc, mọi chuyện', partOfSpeech: 'danh từ' },
      { kanji: '物理', kana: 'ぶつり', romaji: 'butsuri', meaning: 'vật lý', partOfSpeech: 'danh từ' },
      { kanji: '分野', kana: 'ぶんや', romaji: 'bunya', meaning: 'lĩnh vực', partOfSpeech: 'danh từ' },
      { kanji: '粉', kana: 'こな', romaji: 'kona', meaning: 'bột', partOfSpeech: 'danh từ' },
      { kanji: '文', kana: 'ぶん', romaji: 'bun', meaning: 'câu văn', partOfSpeech: 'danh từ' },
      { kanji: '文字', kana: 'もじ', romaji: 'moji', meaning: 'chữ viết, ký tự', partOfSpeech: 'danh từ' },
      { kanji: '文明', kana: 'ぶんめい', romaji: 'bunmei', meaning: 'văn minh', partOfSpeech: 'danh từ' },
      { kanji: '塀', kana: 'へい', romaji: 'hei', meaning: 'hàng rào, tường bao', partOfSpeech: 'danh từ' },
      { kanji: '平ら', kana: 'たいら', romaji: 'taira', meaning: 'bằng phẳng', partOfSpeech: 'tính từ na' },
      { kanji: '癖', kana: 'くせ', romaji: 'kuse', meaning: 'thói quen (thường là xấu)', partOfSpeech: 'danh từ' },
      { kanji: '別に', kana: 'べつに', romaji: 'betsuni', meaning: 'không đặc biệt, không có gì (đi với phủ định)', partOfSpeech: 'phó từ' },
      { kanji: '辺り', kana: 'あたり', romaji: 'atari', meaning: 'khu vực xung quanh', partOfSpeech: 'danh từ' },
      { kanji: '便り', kana: 'たより', romaji: 'tayori', meaning: 'tin tức, thư từ', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 348,
    jlptLevel: 'N3',
    words: [
      { kanji: '保存', kana: 'ほぞん', romaji: 'hozon', meaning: 'sự bảo quản, lưu giữ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '捕まります', kana: 'つかまります', romaji: 'tsukamarimasu', meaning: 'bị bắt, bị tóm', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '歩道', kana: 'ほどう', romaji: 'hodō', meaning: 'vỉa hè', partOfSpeech: 'danh từ' },
      { kanji: '墓', kana: 'はか', romaji: 'haka', meaning: 'ngôi mộ', partOfSpeech: 'danh từ' },
      { kanji: '暮れ', kana: 'くれ', romaji: 'kure', meaning: 'cuối năm, lúc chạng vạng', partOfSpeech: 'danh từ' },
      { kanji: '母親', kana: 'ははおや', romaji: 'hahaoya', meaning: 'mẹ', partOfSpeech: 'danh từ' },
      { kanji: '包み', kana: 'つつみ', romaji: 'tsutsumi', meaning: 'gói hàng, bọc đồ', partOfSpeech: 'danh từ' },
      { kanji: '宝', kana: 'たから', romaji: 'takara', meaning: 'kho báu', partOfSpeech: 'danh từ' },
      { kanji: '宝石', kana: 'ほうせき', romaji: 'hōseki', meaning: 'đá quý, châu báu', partOfSpeech: 'danh từ' },
      { kanji: '抱えます', kana: 'かかえます', romaji: 'kakaemasu', meaning: 'ôm, mang vác (trong tay/nách)', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '抱きます', kana: 'いだきます', romaji: 'idakimasu', meaning: 'ôm ấp, mang trong lòng (cảm xúc)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '方々', kana: 'かたがた', romaji: 'katagata', meaning: 'mọi người (kính ngữ); khắp nơi', partOfSpeech: 'danh từ' },
      { kanji: '方向', kana: 'ほうこう', romaji: 'hōkō', meaning: 'phương hướng', partOfSpeech: 'danh từ' },
      { kanji: '泡', kana: 'あわ', romaji: 'awa', meaning: 'bọt', partOfSpeech: 'danh từ' },
      { kanji: '豊か', kana: 'ゆたか', romaji: 'yutaka', meaning: 'phong phú, giàu có', partOfSpeech: 'tính từ na' },
      { kanji: '豊富', kana: 'ほうふ', romaji: 'hōfu', meaning: 'sự phong phú, dồi dào', partOfSpeech: 'tính từ na' },
      { kanji: '望みます', kana: 'のぞみます', romaji: 'nozomimasu', meaning: 'mong muốn, kỳ vọng', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 349,
    jlptLevel: 'N3',
    words: [
      { kanji: '棒', kana: 'ぼう', romaji: 'bō', meaning: 'cây gậy, thanh', partOfSpeech: 'danh từ' },
      { kanji: '冒険', kana: 'ぼうけん', romaji: 'bōken', meaning: 'sự phiêu lưu, mạo hiểm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '吠えます', kana: 'ほえます', romaji: 'hoemasu', meaning: 'sủa, gầm rú', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '頬', kana: 'ほほ', romaji: 'hoho', meaning: 'má (mặt)', partOfSpeech: 'danh từ' },
      { kanji: '本人', kana: 'ほんにん', romaji: 'honnin', meaning: 'chính người đó, bản thân người ấy', partOfSpeech: 'danh từ' },
      { kanji: '幕', kana: 'まく', romaji: 'maku', meaning: 'màn (sân khấu, kịch)', partOfSpeech: 'danh từ' },
      { kanji: '末', kana: 'すえ', romaji: 'sue', meaning: 'cuối, phần cuối', partOfSpeech: 'danh từ' },
      { kanji: '万一', kana: 'まんいち', romaji: 'manichi', meaning: 'vạn nhất, lỡ như', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '満ちます', kana: 'みちます', romaji: 'michimasu', meaning: 'đầy lên, tràn đầy', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '妙', kana: 'みょう', romaji: 'myō', meaning: 'kỳ lạ, khác thường', partOfSpeech: 'tính từ na' },
      { kanji: '夢中', kana: 'むちゅう', romaji: 'muchū', meaning: 'say mê, mải mê', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '無し', kana: 'なし', romaji: 'nashi', meaning: 'không có', partOfSpeech: 'danh từ' },
    ],
  },
];
