// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 983-988.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART15: JlptVocabUnit[] = [
  {
    lessonNumber: 983,
    jlptLevel: 'N1',
    words: [
      { kanji: '鮮やか', kana: 'あざやか', romaji: 'azayaka', meaning: 'tươi sáng, rực rỡ', partOfSpeech: 'tính từ na' },
      { kanji: '前もって', kana: 'まえもって', romaji: 'maemotte', meaning: 'trước, từ trước', partOfSpeech: 'phó từ' },
      { kanji: '前置き', kana: 'まえおき', romaji: 'maeoki', meaning: 'lời mở đầu', partOfSpeech: 'danh từ' },
      { kanji: '前途', kana: 'ぜんと', romaji: 'zento', meaning: 'tương lai phía trước', partOfSpeech: 'danh từ' },
      { kanji: '前売り', kana: 'まえうり', romaji: 'maeuri', meaning: 'bán vé trước', partOfSpeech: 'danh từ' },
      { kanji: '善し悪し', kana: 'よしあし', romaji: 'yoshiashi', meaning: 'tốt xấu, ưu khuyết điểm', partOfSpeech: 'danh từ' },
      { kanji: '善良', kana: 'ぜんりょう', romaji: 'zenryō', meaning: 'hiền lành, tốt bụng', partOfSpeech: 'tính từ na' },
      { kanji: '然しながら', kana: 'しかしながら', romaji: 'shikashinagara', meaning: 'tuy nhiên, dù vậy', partOfSpeech: 'liên từ' },
      { kanji: '然も', kana: 'さも', romaji: 'samo', meaning: 'có vẻ như thật, ra chiều', partOfSpeech: 'phó từ' },
      { kanji: '全快', kana: 'ぜんかい', romaji: 'zenkai', meaning: 'sự bình phục hoàn toàn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '全滅', kana: 'ぜんめつ', romaji: 'zenmetsu', meaning: 'sự tiêu diệt hoàn toàn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '繕います', kana: 'つくろいます', romaji: 'tsukuroimasu', meaning: 'vá, sửa chữa; che đậy (thể diện)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '疎か', kana: 'おろそか', romaji: 'orosoka', meaning: 'sao nhãng, cẩu thả', partOfSpeech: 'tính từ na' },
      { kanji: '素っ気ない', kana: 'そっけない', romaji: 'sokkenai', meaning: 'lạnh nhạt, cộc lốc', partOfSpeech: 'tính từ i' },
      { kanji: '素材', kana: 'そざい', romaji: 'sozai', meaning: 'nguyên liệu, chất liệu', partOfSpeech: 'danh từ' },
      { kanji: '素早い', kana: 'すばやい', romaji: 'subayai', meaning: 'nhanh nhẹn', partOfSpeech: 'tính từ i' },
      { kanji: '素朴', kana: 'そぼく', romaji: 'soboku', meaning: 'mộc mạc, giản dị', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 984,
    jlptLevel: 'N1',
    words: [
      { kanji: '組み合わせます', kana: 'くみあわせます', romaji: 'kumiawasemasu', meaning: 'kết hợp, ghép lại', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '組み込みます', kana: 'くみこみます', romaji: 'kumikomimasu', meaning: 'lồng vào, tích hợp', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '訴え', kana: 'うったえ', romaji: 'uttae', meaning: 'đơn kiện, lời khiếu nại', partOfSpeech: 'danh từ' },
      { kanji: '阻みます', kana: 'はばみます', romaji: 'habamimasu', meaning: 'ngăn cản, cản trở', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '創刊', kana: 'そうかん', romaji: 'sōkan', meaning: 'số phát hành đầu tiên', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '創立', kana: 'そうりつ', romaji: 'sōritsu', meaning: 'sự thành lập, sáng lập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '壮大', kana: 'そうだい', romaji: 'sōdai', meaning: 'hùng vĩ, hoành tráng', partOfSpeech: 'tính từ na' },
      { kanji: '掻き回します', kana: 'かきまわします', romaji: 'kakimawashimasu', meaning: 'khuấy đảo, làm xáo trộn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '操ります', kana: 'あやつります', romaji: 'ayatsurimasu', meaning: 'điều khiển, giật dây', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '操縦', kana: 'そうじゅう', romaji: 'sōjū', meaning: 'sự điều khiển (máy móc)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '早めます', kana: 'はやめます', romaji: 'hayamemasu', meaning: 'làm sớm hơn, đẩy nhanh', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '早急', kana: 'さっきゅう', romaji: 'sakkyū', meaning: 'khẩn cấp, gấp rút', partOfSpeech: 'tính từ na' },
      { kanji: '漕ぎます', kana: 'こぎます', romaji: 'kogimasu', meaning: 'chèo thuyền, đạp (xe đạp)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '争い', kana: 'あらそい', romaji: 'arasoi', meaning: 'cuộc tranh chấp', partOfSpeech: 'danh từ' },
      { kanji: '相場', kana: 'そうば', romaji: 'sōba', meaning: 'giá thị trường', partOfSpeech: 'danh từ' },
      { kanji: '相対', kana: 'あいたい', romaji: 'aitai', meaning: 'sự đối mặt trực tiếp', partOfSpeech: 'danh từ' },
      { kanji: '総会', kana: 'そうかい', romaji: 'sōkai', meaning: 'đại hội toàn thể', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 985,
    jlptLevel: 'N1',
    words: [
      { kanji: '葬ります', kana: 'ほうむります', romaji: 'hōmurimasu', meaning: 'chôn cất, vùi lấp', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '藻掻きます', kana: 'もがきます', romaji: 'mogakimasu', meaning: 'vùng vẫy, giãy giụa', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '装飾', kana: 'そうしょく', romaji: 'sōshoku', meaning: 'sự trang trí', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '装備', kana: 'そうび', romaji: 'sōbi', meaning: 'trang thiết bị', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '走行', kana: 'そうこう', romaji: 'sōkō', meaning: 'sự chạy xe, hành trình', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '送金', kana: 'そうきん', romaji: 'sōkin', meaning: 'sự chuyển tiền', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '遭難', kana: 'そうなん', romaji: 'sōnan', meaning: 'tai nạn, gặp nạn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '増し', kana: 'まし', romaji: 'mashi', meaning: 'phần tăng thêm; tốt hơn', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '増強', kana: 'ぞうきょう', romaji: 'zōkyō', meaning: 'sự tăng cường', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '増進', kana: 'ぞうしん', romaji: 'zōshin', meaning: 'sự thúc đẩy, tăng cường', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '憎しみ', kana: 'にくしみ', romaji: 'nikushimi', meaning: 'sự căm ghét', partOfSpeech: 'danh từ' },
      { kanji: '蔵', kana: 'くら', romaji: 'kura', meaning: 'kho chứa đồ', partOfSpeech: 'danh từ' },
      { kanji: '蔵相', kana: 'ぞうしょう', romaji: 'zōshō', meaning: 'bộ trưởng tài chính', partOfSpeech: 'danh từ' },
      { kanji: '側面', kana: 'そくめん', romaji: 'sokumen', meaning: 'mặt bên, khía cạnh', partOfSpeech: 'danh từ' },
      { kanji: '即します', kana: 'そくします', romaji: 'sokushimasu', meaning: 'dựa theo, phù hợp với', partOfSpeech: 'động từ する' },
      { kanji: '即座に', kana: 'そくざに', romaji: 'sokuzani', meaning: 'ngay lập tức', partOfSpeech: 'phó từ' },
      { kanji: '束の間', kana: 'つかのま', romaji: 'tsukanoma', meaning: 'khoảnh khắc ngắn ngủi', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 986,
    jlptLevel: 'N1',
    words: [
      { kanji: '束縛', kana: 'そくばく', romaji: 'sokubaku', meaning: 'sự trói buộc, ràng buộc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '足し算', kana: 'たしざん', romaji: 'tashizan', meaning: 'phép cộng', partOfSpeech: 'danh từ' },
      { kanji: '其れ故', kana: 'それゆえ', romaji: 'soreyue', meaning: 'vì vậy, do đó', partOfSpeech: 'liên từ' },
      { kanji: '其処ら', kana: 'そこら', romaji: 'sokora', meaning: 'quanh đó, khoảng chừng', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '揃い', kana: 'そろい', romaji: 'soroi', meaning: 'bộ, cặp đồng bộ', partOfSpeech: 'danh từ' },
      { kanji: '存続', kana: 'そんぞく', romaji: 'sonzoku', meaning: 'sự tồn tại lâu dài', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '尊びます', kana: 'たっとびます', romaji: 'tattobimasu', meaning: 'tôn kính, coi trọng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '損ないます', kana: 'そこないます', romaji: 'sokonaimasu', meaning: 'làm tổn hại, làm hỏng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '他動詞', kana: 'たどうし', romaji: 'tadōshi', meaning: 'tha động từ (ngoại động từ)', partOfSpeech: 'danh từ' },
      { kanji: '他方', kana: 'たほう', romaji: 'tahō', meaning: 'mặt khác, phía khác', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '多数決', kana: 'たすうけつ', romaji: 'tasūketsu', meaning: 'nguyên tắc đa số', partOfSpeech: 'danh từ' },
      { kanji: '多忙', kana: 'たぼう', romaji: 'tabō', meaning: 'bận rộn', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '多様', kana: 'たよう', romaji: 'tayō', meaning: 'đa dạng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '唾', kana: 'つば', romaji: 'tsuba', meaning: 'nước bọt', partOfSpeech: 'danh từ' },
      { kanji: '打ち合わせ', kana: 'うちあわせ', romaji: 'uchiawase', meaning: 'buổi họp bàn, sự thống nhất trước', partOfSpeech: 'danh từ' },
      { kanji: '打ち合わせます', kana: 'うちあわせます', romaji: 'uchiawasemasu', meaning: 'bàn bạc, thống nhất trước', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '打ち込みます', kana: 'うちこみます', romaji: 'uchikomimasu', meaning: 'đóng vào; dồn hết tâm huyết', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 987,
    jlptLevel: 'N1',
    words: [
      { kanji: '打ち消し', kana: 'うちけし', romaji: 'uchikeshi', meaning: 'sự phủ định', partOfSpeech: 'danh từ' },
      { kanji: '打ち切ります', kana: 'うちきります', romaji: 'uchikirimasu', meaning: 'chấm dứt, ngừng lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '打撃', kana: 'だげき', romaji: 'dageki', meaning: 'cú đánh, tổn thất nặng nề', partOfSpeech: 'danh từ' },
      { kanji: '駄作', kana: 'ださく', romaji: 'dasaku', meaning: 'tác phẩm tồi, sản phẩm dở', partOfSpeech: 'danh từ' },
      { kanji: '体', kana: 'てい', romaji: 'tei', meaning: 'vẻ ngoài, hình thức', partOfSpeech: 'danh từ' },
      { kanji: '体格', kana: 'たいかく', romaji: 'taikaku', meaning: 'thể chất, vóc dáng', partOfSpeech: 'danh từ' },
      { kanji: '体験', kana: 'たいけん', romaji: 'taiken', meaning: 'kinh nghiệm bản thân', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '体裁', kana: 'ていさい', romaji: 'teisai', meaning: 'hình thức bên ngoài, thể diện', partOfSpeech: 'danh từ' },
      { kanji: '体付き', kana: 'からだつき', romaji: 'karadatsuki', meaning: 'vóc dáng cơ thể', partOfSpeech: 'danh từ' },
      { kanji: '対決', kana: 'たいけつ', romaji: 'taiketsu', meaning: 'cuộc đối đầu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '対抗', kana: 'たいこう', romaji: 'taikō', meaning: 'sự đối kháng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '対談', kana: 'たいだん', romaji: 'taidan', meaning: 'cuộc đối thoại, trò chuyện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '対比', kana: 'たいひ', romaji: 'taihi', meaning: 'sự so sánh, đối chiếu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '対面', kana: 'たいめん', romaji: 'taimen', meaning: 'sự gặp mặt trực tiếp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '対話', kana: 'たいわ', romaji: 'taiwa', meaning: 'cuộc đối thoại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '帯びます', kana: 'おびます', romaji: 'obimasu', meaning: 'mang, đeo; nhuốm màu', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '待ち遠しい', kana: 'まちどおしい', romaji: 'machidōshii', meaning: 'mong chờ, nóng lòng mong đợi', partOfSpeech: 'tính từ i' },
    ],
  },
  {
    lessonNumber: 988,
    jlptLevel: 'N1',
    words: [
      { kanji: '待ち合わせ', kana: 'まちあわせ', romaji: 'machiawase', meaning: 'cuộc hẹn gặp', partOfSpeech: 'danh từ' },
      { kanji: '待ち望みます', kana: 'まちのぞみます', romaji: 'machinozomimasu', meaning: 'mong đợi, ngóng chờ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '待望', kana: 'たいぼう', romaji: 'taibō', meaning: 'sự mong đợi từ lâu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '怠い', kana: 'だるい', romaji: 'darui', meaning: 'mệt mỏi, uể oải', partOfSpeech: 'tính từ i' },
      { kanji: '怠慢', kana: 'たいまん', romaji: 'taiman', meaning: 'sự lơ là, cẩu thả', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '態勢', kana: 'たいせい', romaji: 'taisei', meaning: 'tư thế sẵn sàng, thái độ', partOfSpeech: 'danh từ' },
      { kanji: '滞ります', kana: 'とどこおります', romaji: 'todokōrimasu', meaning: 'bị đình trệ, chậm trễ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '滞納', kana: 'たいのう', romaji: 'tainō', meaning: 'sự nợ đọng, chậm nộp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '腿', kana: 'もも', romaji: 'momo', meaning: 'đùi', partOfSpeech: 'danh từ' },
      { kanji: '退きます', kana: 'しりぞきます', romaji: 'shirizokimasu', meaning: 'lùi lại, rút lui', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '退けます', kana: 'しりぞけます', romaji: 'shirizokemasu', meaning: 'đẩy lùi, xua đuổi', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '退学', kana: 'たいがく', romaji: 'taigaku', meaning: 'sự thôi học, bỏ học', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
];
