// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 1007-1012.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART19: JlptVocabUnit[] = [
  {
    lessonNumber: 1007,
    jlptLevel: 'N1',
    words: [
      { kanji: '燃料', kana: 'ねんりょう', romaji: 'nenryō', meaning: 'nhiên liệu', partOfSpeech: 'danh từ' },
      { kanji: '粘り', kana: 'ねばり', romaji: 'nebari', meaning: 'độ dính, sự bền bỉ', partOfSpeech: 'danh từ' },
      { kanji: '乃至', kana: 'ないし', romaji: 'naishi', meaning: 'hoặc, từ...đến...', partOfSpeech: 'liên từ' },
      { kanji: '悩ましい', kana: 'なやましい', romaji: 'nayamashii', meaning: 'quyến rũ; phiền muộn', partOfSpeech: 'tính từ i' },
      { kanji: '悩まします', kana: 'なやまします', romaji: 'nayamashimasu', meaning: 'làm phiền, gây khó chịu', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '納入', kana: 'のうにゅう', romaji: 'nōnyū', meaning: 'sự nộp, cung cấp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '農耕', kana: 'のうこう', romaji: 'nōkō', meaning: 'canh tác nông nghiệp', partOfSpeech: 'danh từ' },
      { kanji: '農場', kana: 'のうじょう', romaji: 'nōjō', meaning: 'nông trại', partOfSpeech: 'danh từ' },
      { kanji: '農地', kana: 'のうち', romaji: 'nōchi', meaning: 'đất nông nghiệp', partOfSpeech: 'danh từ' },
      { kanji: '派遣', kana: 'はけん', romaji: 'haken', meaning: 'sự cử phái, biệt phái', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '破壊', kana: 'はかい', romaji: 'hakai', meaning: 'sự phá hủy', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '破棄', kana: 'はき', romaji: 'haki', meaning: 'sự hủy bỏ (hợp đồng)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '破損', kana: 'はそん', romaji: 'hason', meaning: 'sự hư hỏng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '破裂', kana: 'はれつ', romaji: 'haretsu', meaning: 'sự nổ vỡ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '罵ります', kana: 'ののしります', romaji: 'nonoshirimasu', meaning: 'chửi mắng, mắng nhiếc', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '馬鹿馬鹿しい', kana: 'ばかばかしい', romaji: 'bakabakashii', meaning: 'hết sức ngớ ngẩn', partOfSpeech: 'tính từ i' },
      { kanji: '廃れます', kana: 'すたれます', romaji: 'sutaremasu', meaning: 'lỗi thời, mai một', partOfSpeech: 'động từ nhóm 2' },
    ],
  },
  {
    lessonNumber: 1008,
    jlptLevel: 'N1',
    words: [
      { kanji: '廃棄', kana: 'はいき', romaji: 'haiki', meaning: 'sự loại bỏ, hủy bỏ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '拝借', kana: 'はいしゃく', romaji: 'haishaku', meaning: 'sự mượn (khiêm nhường)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '排水', kana: 'はいすい', romaji: 'haisui', meaning: 'sự thoát nước', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '敗戦', kana: 'はいせん', romaji: 'haisen', meaning: 'sự thua trận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '杯', kana: 'さかずき', romaji: 'sakazuki', meaning: 'chén rượu', partOfSpeech: 'danh từ' },
      { kanji: '背きます', kana: 'そむきます', romaji: 'somukimasu', meaning: 'chống lại, làm trái', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '背後', kana: 'はいご', romaji: 'haigo', meaning: 'phía sau lưng', partOfSpeech: 'danh từ' },
      { kanji: '配給', kana: 'はいきゅう', romaji: 'haikyū', meaning: 'sự phân phối', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '配偶者', kana: 'はいぐうしゃ', romaji: 'haigūsha', meaning: 'người phối ngẫu (vợ/chồng)', partOfSpeech: 'danh từ' },
      { kanji: '配置', kana: 'はいち', romaji: 'haichi', meaning: 'sự bố trí, sắp xếp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '配布', kana: 'はいふ', romaji: 'haifu', meaning: 'sự phát cho, phân phát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '配分', kana: 'はいぶん', romaji: 'haibun', meaning: 'sự phân bổ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '配慮', kana: 'はいりょ', romaji: 'hairyo', meaning: 'sự cân nhắc, quan tâm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '配列', kana: 'はいれつ', romaji: 'hairetsu', meaning: 'sự sắp xếp, mảng (lập trình)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '梅干', kana: 'うめぼし', romaji: 'umeboshi', meaning: 'mơ muối', partOfSpeech: 'danh từ' },
      { kanji: '売り出し', kana: 'うりだし', romaji: 'uridashi', meaning: 'đợt giảm giá bán', partOfSpeech: 'danh từ' },
      { kanji: '売り出します', kana: 'うりだします', romaji: 'uridashimasu', meaning: 'tung ra bán, bắt đầu nổi tiếng', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 1009,
    jlptLevel: 'N1',
    words: [
      { kanji: '売れ行き', kana: 'うれゆき', romaji: 'ureyuki', meaning: 'tình hình bán hàng', partOfSpeech: 'danh từ' },
      { kanji: '剥がします', kana: 'はがします', romaji: 'hagashimasu', meaning: 'bóc ra, lột ra', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '剥ぎます', kana: 'はぎます', romaji: 'hagimasu', meaning: 'lột, bóc vỏ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '白状', kana: 'はくじょう', romaji: 'hakujō', meaning: 'lời thú tội', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '薄弱', kana: 'はくじゃく', romaji: 'hakujaku', meaning: 'yếu ớt, thiếu ý chí', partOfSpeech: 'tính từ na' },
      { kanji: '迫害', kana: 'はくがい', romaji: 'hakugai', meaning: 'sự đàn áp, bức hại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '漠然', kana: 'ばくぜん', romaji: 'bakuzen', meaning: 'mơ hồ, không rõ ràng', partOfSpeech: 'tính từ na' },
      { kanji: '爆破', kana: 'ばくは', romaji: 'bakuha', meaning: 'sự đánh bom, cho nổ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発育', kana: 'はついく', romaji: 'hatsuiku', meaning: 'sự phát triển thể chất', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発芽', kana: 'はつが', romaji: 'hatsuga', meaning: 'sự nảy mầm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発掘', kana: 'はっくつ', romaji: 'hakkutsu', meaning: 'sự khai quật', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発言', kana: 'はつげん', romaji: 'hatsugen', meaning: 'lời phát biểu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発作', kana: 'ほっさ', romaji: 'hossa', meaning: 'cơn co giật, cơn phát bệnh', partOfSpeech: 'danh từ' },
      { kanji: '発生', kana: 'はっせい', romaji: 'hassei', meaning: 'sự phát sinh, xảy ra', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発足', kana: 'はっそく', romaji: 'hassoku', meaning: 'sự khởi động, ra mắt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発病', kana: 'はつびょう', romaji: 'hatsubyō', meaning: 'sự phát bệnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '罰', kana: 'ばち', romaji: 'bachi', meaning: 'sự trừng phạt của trời', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 1010,
    jlptLevel: 'N1',
    words: [
      { kanji: '抜かします', kana: 'ぬかします', romaji: 'nukashimasu', meaning: 'bỏ sót, bỏ qua', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '抜け出します', kana: 'ぬけだします', romaji: 'nukedashimasu', meaning: 'lẻn ra, trốn ra ngoài', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '伴います', kana: 'ともないます', romaji: 'tomonaimasu', meaning: 'đi kèm, kéo theo', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '半端', kana: 'はんぱ', romaji: 'hanpa', meaning: 'dở dang, không trọn vẹn', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '反します', kana: 'はんします', romaji: 'hanshimasu', meaning: 'trái ngược, vi phạm', partOfSpeech: 'động từ する' },
      { kanji: '反り', kana: 'そり', romaji: 'sori', meaning: 'độ cong, độ vênh', partOfSpeech: 'danh từ' },
      { kanji: '反感', kana: 'はんかん', romaji: 'hankan', meaning: 'sự phản cảm, ác cảm', partOfSpeech: 'danh từ' },
      { kanji: '反響', kana: 'はんきょう', romaji: 'hankyō', meaning: 'tiếng vang, phản ứng dư luận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '反撃', kana: 'はんげき', romaji: 'hangeki', meaning: 'cuộc phản công', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '反射', kana: 'はんしゃ', romaji: 'hansha', meaning: 'sự phản xạ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '斑', kana: 'ぶち', romaji: 'buchi', meaning: 'đốm, vệt loang', partOfSpeech: 'danh từ' },
      { kanji: '版画', kana: 'はんが', romaji: 'hanga', meaning: 'tranh khắc gỗ, bản in', partOfSpeech: 'danh từ' },
      { kanji: '繁盛', kana: 'はんじょう', romaji: 'hanjō', meaning: 'sự thịnh vượng (buôn bán)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '番目', kana: 'ばんめ', romaji: 'banme', meaning: 'hậu tố chỉ thứ tự', partOfSpeech: 'hậu tố' },
      { kanji: '卑しい', kana: 'いやしい', romaji: 'iyashii', meaning: 'hèn hạ, thấp kém', partOfSpeech: 'tính từ i' },
      { kanji: '否決', kana: 'ひけつ', romaji: 'hiketsu', meaning: 'sự bác bỏ, phủ quyết', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '悲観', kana: 'ひかん', romaji: 'hikan', meaning: 'sự bi quan', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 1011,
    jlptLevel: 'N1',
    words: [
      { kanji: '悲惨', kana: 'ひさん', romaji: 'hisan', meaning: 'thảm thương, bi thảm', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '悲鳴', kana: 'ひめい', romaji: 'himei', meaning: 'tiếng thét, tiếng kêu la', partOfSpeech: 'danh từ' },
      { kanji: '扉', kana: 'とびら', romaji: 'tobira', meaning: 'cánh cửa', partOfSpeech: 'danh từ' },
      { kanji: '比重', kana: 'ひじゅう', romaji: 'hijū', meaning: 'tỷ trọng', partOfSpeech: 'danh từ' },
      { kanji: '比率', kana: 'ひりつ', romaji: 'hiritsu', meaning: 'tỷ lệ', partOfSpeech: 'danh từ' },
      { kanji: '比例', kana: 'ひれい', romaji: 'hirei', meaning: 'tỷ lệ thuận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '秘書', kana: 'ひしょ', romaji: 'hisho', meaning: 'thư ký riêng', partOfSpeech: 'danh từ' },
      { kanji: '肥料', kana: 'ひりょう', romaji: 'hiryō', meaning: 'phân bón', partOfSpeech: 'danh từ' },
      { kanji: '費やします', kana: 'ついやします', romaji: 'tsuiyashimasu', meaning: 'tiêu tốn, dành (thời gian, tiền)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '備え付けます', kana: 'そなえつけます', romaji: 'sonaetsukemasu', meaning: 'trang bị sẵn, lắp đặt sẵn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '備わります', kana: 'そなわります', romaji: 'sonawarimasu', meaning: 'được trang bị, vốn có', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '微か', kana: 'かすか', romaji: 'kasuka', meaning: 'mờ nhạt, yếu ớt', partOfSpeech: 'tính từ na' },
      { kanji: '微笑', kana: 'びしょう', romaji: 'bishō', meaning: 'nụ cười mỉm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '微塵', kana: 'みじん', romaji: 'mijin', meaning: 'hạt bụi nhỏ, chút xíu', partOfSpeech: 'danh từ' },
      { kanji: '微量', kana: 'びりょう', romaji: 'biryō', meaning: 'lượng rất nhỏ', partOfSpeech: 'danh từ' },
      { kanji: '眉', kana: 'まゆ', romaji: 'mayu', meaning: 'lông mày', partOfSpeech: 'danh từ' },
      { kanji: '美', kana: 'び', romaji: 'bi', meaning: 'cái đẹp', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 1012,
    jlptLevel: 'N1',
    words: [
      { kanji: '匹', kana: 'ひき', romaji: 'hiki', meaning: 'con (đơn vị đếm động vật nhỏ)', partOfSpeech: 'danh từ' },
      { kanji: '匹敵', kana: 'ひってき', romaji: 'hitteki', meaning: 'sự sánh ngang, tương đương', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '必修', kana: 'ひっしゅう', romaji: 'hisshū', meaning: 'môn học bắt buộc', partOfSpeech: 'danh từ' },
      { kanji: '標語', kana: 'ひょうご', romaji: 'hyōgo', meaning: 'khẩu hiệu', partOfSpeech: 'danh từ' },
      { kanji: '漂います', kana: 'ただよいます', romaji: 'tadayoimasu', meaning: 'trôi nổi, lơ lửng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '病', kana: 'やまい', romaji: 'yamai', meaning: 'bệnh tật', partOfSpeech: 'danh từ' },
      { kanji: '苗', kana: 'なえ', romaji: 'nae', meaning: 'cây mạ, cây giống', partOfSpeech: 'danh từ' },
      { kanji: '品種', kana: 'ひんしゅ', romaji: 'hinshu', meaning: 'chủng loại, giống loài', partOfSpeech: 'danh từ' },
      { kanji: '浜', kana: 'はま', romaji: 'hama', meaning: 'bờ biển', partOfSpeech: 'danh từ' },
      { kanji: '浜辺', kana: 'はまべ', romaji: 'hamabe', meaning: 'bãi biển', partOfSpeech: 'danh từ' },
      { kanji: '貧弱', kana: 'ひんじゃく', romaji: 'hinjaku', meaning: 'nghèo nàn, ít ỏi', partOfSpeech: 'tính từ na' },
      { kanji: '貧乏', kana: 'びんぼう', romaji: 'binbō', meaning: 'nghèo túng', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '頻繁', kana: 'ひんぱん', romaji: 'hinpan', meaning: 'thường xuyên, liên tục', partOfSpeech: 'tính từ na' },
    ],
  },
];
