// Từ vựng JLPT N3 / N2 / N1 — biên soạn best-effort, ưu tiên từ tần suất cao.
// Mỗi unit dùng CHUNG lessonNumber với unit ngữ pháp (jlpt-grammar.data.ts),
// nên mỗi "Bài" JLPT có cả ngữ pháp lẫn từ vựng.
// Mở rộng: thêm phần tử vào `words` hoặc thêm unit mới.

export type JlptVocabLevel = 'N3' | 'N2' | 'N1';

export type JlptVocabWord = {
  kanji?: string;
  kana: string;
  romaji: string;
  meaning: string; // tiếng Việt
  partOfSpeech?: string;
  exampleJa?: string;
  exampleKana?: string;
  exampleVi?: string;
};

export type JlptVocabUnit = {
  lessonNumber: number;
  jlptLevel: JlptVocabLevel;
  words: JlptVocabWord[];
};

export const JLPT_VOCAB_UNITS: JlptVocabUnit[] = [
  // ─────────────────────────────── N3 ───────────────────────────────
  {
    lessonNumber: 301,
    jlptLevel: 'N3',
    words: [
      { kanji: '目的', kana: 'もくてき', romaji: 'mokuteki', meaning: 'mục đích', partOfSpeech: 'danh từ',
        exampleJa: '旅行の目的は何ですか。', exampleKana: 'りょこうのもくてきはなんですか。', exampleVi: 'Mục đích chuyến đi là gì?' },
      { kanji: '原因', kana: 'げんいん', romaji: 'gen\'in', meaning: 'nguyên nhân', partOfSpeech: 'danh từ',
        exampleJa: '事故の原因を調べている。', exampleKana: 'じこのげんいんをしらべている。', exampleVi: 'Đang điều tra nguyên nhân vụ tai nạn.' },
      { kanji: '結果', kana: 'けっか', romaji: 'kekka', meaning: 'kết quả', partOfSpeech: 'danh từ',
        exampleJa: '努力の結果、合格した。', exampleKana: 'どりょくのけっか、ごうかくした。', exampleVi: 'Nhờ nỗ lực, tôi đã đỗ.' },
      { kanji: '理由', kana: 'りゆう', romaji: 'riyū', meaning: 'lý do', partOfSpeech: 'danh từ' },
      { kanji: '目標', kana: 'もくひょう', romaji: 'mokuhyō', meaning: 'mục tiêu', partOfSpeech: 'danh từ' },
      { kanji: '計画', kana: 'けいかく', romaji: 'keikaku', meaning: 'kế hoạch', partOfSpeech: 'danh từ, động từ する',
        exampleJa: '夏休みの計画を立てた。', exampleKana: 'なつやすみのけいかくをたてた。', exampleVi: 'Tôi đã lập kế hoạch cho kỳ nghỉ hè.' },
      { kanji: '準備', kana: 'じゅんび', romaji: 'junbi', meaning: 'sự chuẩn bị', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '努力', kana: 'どりょく', romaji: 'doryoku', meaning: 'sự nỗ lực', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '成功', kana: 'せいこう', romaji: 'seikō', meaning: 'thành công', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '失敗', kana: 'しっぱい', romaji: 'shippai', meaning: 'thất bại', partOfSpeech: 'danh từ, động từ する',
        exampleJa: '失敗を恐れないでください。', exampleKana: 'しっぱいをおそれないでください。', exampleVi: 'Đừng sợ thất bại.' },
      { kanji: '決める', kana: 'きめる', romaji: 'kimeru', meaning: 'quyết định', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '決まる', kana: 'きまる', romaji: 'kimaru', meaning: 'được quyết định', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '選ぶ', kana: 'えらぶ', romaji: 'erabu', meaning: 'lựa chọn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '比べる', kana: 'くらべる', romaji: 'kuraberu', meaning: 'so sánh', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '増える', kana: 'ふえる', romaji: 'fueru', meaning: 'tăng lên', partOfSpeech: 'động từ nhóm 2',
        exampleJa: '外国人観光客が増えている。', exampleKana: 'がいこくじんかんこうきゃくがふえている。', exampleVi: 'Khách du lịch nước ngoài đang tăng.' },
      { kanji: '減る', kana: 'へる', romaji: 'heru', meaning: 'giảm đi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '変化', kana: 'へんか', romaji: 'henka', meaning: 'sự thay đổi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '影響', kana: 'えいきょう', romaji: 'eikyō', meaning: 'ảnh hưởng', partOfSpeech: 'danh từ, động từ する',
        exampleJa: '天気は気分に影響する。', exampleKana: 'てんきはきぶんにえいきょうする。', exampleVi: 'Thời tiết ảnh hưởng đến tâm trạng.' },
      { kanji: '関係', kana: 'かんけい', romaji: 'kankei', meaning: 'quan hệ', partOfSpeech: 'danh từ' },
      { kana: 'せっかく', romaji: 'sekkaku', meaning: 'cất công, mất công (mà...)', partOfSpeech: 'phó từ',
        exampleJa: 'せっかく来たのに、店は閉まっていた。', exampleKana: 'せっかくきたのに、みせはしまっていた。', exampleVi: 'Cất công đến mà quán đóng cửa.' },
      { kana: 'わざわざ', romaji: 'wazawaza', meaning: 'cố ý bỏ công sức', partOfSpeech: 'phó từ' },
      { kana: 'とうとう', romaji: 'tōtō', meaning: 'cuối cùng thì (cũng)', partOfSpeech: 'phó từ' },
      { kana: 'ついに', romaji: 'tsui ni', meaning: 'rốt cuộc, cuối cùng', partOfSpeech: 'phó từ' },
      { kana: 'いよいよ', romaji: 'iyoiyo', meaning: 'rốt cuộc cũng đến lúc; ngày càng', partOfSpeech: 'phó từ' },
      { kanji: '実は', kana: 'じつは', romaji: 'jitsu wa', meaning: 'thật ra là', partOfSpeech: 'phó từ' },
      { kanji: '確かに', kana: 'たしかに', romaji: 'tashika ni', meaning: 'đúng là, quả thực', partOfSpeech: 'phó từ' },
      { kanji: '主に', kana: 'おもに', romaji: 'omo ni', meaning: 'chủ yếu', partOfSpeech: 'phó từ' },
      { kanji: '特に', kana: 'とくに', romaji: 'toku ni', meaning: 'đặc biệt là', partOfSpeech: 'phó từ' },
      { kanji: '実際に', kana: 'じっさいに', romaji: 'jissai ni', meaning: 'trên thực tế', partOfSpeech: 'phó từ' },
      { kanji: '結局', kana: 'けっきょく', romaji: 'kekkyoku', meaning: 'rốt cuộc', partOfSpeech: 'phó từ',
        exampleJa: '結局、彼は来なかった。', exampleKana: 'けっきょく、かれはこなかった。', exampleVi: 'Rốt cuộc anh ấy không đến.' },
    ],
  },
  {
    lessonNumber: 302,
    jlptLevel: 'N3',
    words: [
      { kanji: '情報', kana: 'じょうほう', romaji: 'jōhō', meaning: 'thông tin', partOfSpeech: 'danh từ' },
      { kanji: '知らせる', kana: 'しらせる', romaji: 'shiraseru', meaning: 'thông báo cho', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '伝える', kana: 'つたえる', romaji: 'tsutaeru', meaning: 'truyền đạt, nhắn lại', partOfSpeech: 'động từ nhóm 2',
        exampleJa: '母によろしくお伝えください。', exampleKana: 'ははによろしくおつたえください。', exampleVi: 'Cho tôi gửi lời hỏi thăm mẹ bạn.' },
      { kanji: '報告', kana: 'ほうこく', romaji: 'hōkoku', meaning: 'báo cáo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '連絡', kana: 'れんらく', romaji: 'renraku', meaning: 'liên lạc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '相談', kana: 'そうだん', romaji: 'sōdan', meaning: 'bàn bạc, xin tư vấn', partOfSpeech: 'danh từ, động từ する',
        exampleJa: '先生に進路を相談した。', exampleKana: 'せんせいにしんろをそうだんした。', exampleVi: 'Tôi đã xin thầy tư vấn về hướng đi.' },
      { kanji: '説明', kana: 'せつめい', romaji: 'setsumei', meaning: 'giải thích', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '意見', kana: 'いけん', romaji: 'iken', meaning: 'ý kiến', partOfSpeech: 'danh từ' },
      { kanji: '確認', kana: 'かくにん', romaji: 'kakunin', meaning: 'xác nhận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '約束', kana: 'やくそく', romaji: 'yakusoku', meaning: 'lời hứa, cuộc hẹn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '状態', kana: 'じょうたい', romaji: 'jōtai', meaning: 'trạng thái', partOfSpeech: 'danh từ' },
      { kanji: '調子', kana: 'ちょうし', romaji: 'chōshi', meaning: 'tình trạng, phong độ', partOfSpeech: 'danh từ',
        exampleJa: '今日は体の調子がいい。', exampleKana: 'きょうはからだのちょうしがいい。', exampleVi: 'Hôm nay cơ thể tôi khỏe.' },
      { kanji: '様子', kana: 'ようす', romaji: 'yōsu', meaning: 'vẻ, tình hình, dáng vẻ', partOfSpeech: 'danh từ' },
      { kanji: '態度', kana: 'たいど', romaji: 'taido', meaning: 'thái độ', partOfSpeech: 'danh từ' },
      { kanji: '性格', kana: 'せいかく', romaji: 'seikaku', meaning: 'tính cách', partOfSpeech: 'danh từ' },
      { kanji: '気分', kana: 'きぶん', romaji: 'kibun', meaning: 'tâm trạng', partOfSpeech: 'danh từ' },
      { kanji: '気持ち', kana: 'きもち', romaji: 'kimochi', meaning: 'cảm xúc, tấm lòng', partOfSpeech: 'danh từ' },
      { kanji: '感じる', kana: 'かんじる', romaji: 'kanjiru', meaning: 'cảm thấy', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '感想', kana: 'かんそう', romaji: 'kansō', meaning: 'cảm tưởng', partOfSpeech: 'danh từ' },
      { kanji: '印象', kana: 'いんしょう', romaji: 'inshō', meaning: 'ấn tượng', partOfSpeech: 'danh từ',
        exampleJa: '彼の第一印象はよかった。', exampleKana: 'かれのだいいちいんしょうはよかった。', exampleVi: 'Ấn tượng đầu về anh ấy rất tốt.' },
      { kanji: '想像', kana: 'そうぞう', romaji: 'sōzō', meaning: 'tưởng tượng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '予想', kana: 'よそう', romaji: 'yosō', meaning: 'dự đoán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '判断', kana: 'はんだん', romaji: 'handan', meaning: 'phán đoán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '記憶', kana: 'きおく', romaji: 'kioku', meaning: 'trí nhớ, ký ức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '記録', kana: 'きろく', romaji: 'kiroku', meaning: 'ghi chép, kỷ lục', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'はっきり', romaji: 'hakkiri', meaning: 'rõ ràng', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'そっくり', romaji: 'sokkuri', meaning: 'giống hệt', partOfSpeech: 'tính từ na, phó từ',
        exampleJa: '娘は母親にそっくりだ。', exampleKana: 'むすめはははおやにそっくりだ。', exampleVi: 'Con gái giống hệt mẹ.' },
      { kana: 'ぴったり', romaji: 'pittari', meaning: 'vừa khít, hợp', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'めちゃくちゃ', romaji: 'mechakucha', meaning: 'lộn xộn; cực kỳ', partOfSpeech: 'tính từ na, phó từ' },
      { kana: 'なんとなく', romaji: 'nantonaku', meaning: 'không rõ vì sao, mơ hồ', partOfSpeech: 'phó từ' },
    ],
  },
  {
    lessonNumber: 303,
    jlptLevel: 'N3',
    words: [
      { kanji: '就職', kana: 'しゅうしょく', romaji: 'shūshoku', meaning: 'xin việc làm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '面接', kana: 'めんせつ', romaji: 'mensetsu', meaning: 'phỏng vấn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '給料', kana: 'きゅうりょう', romaji: 'kyūryō', meaning: 'lương', partOfSpeech: 'danh từ' },
      { kanji: '残業', kana: 'ざんぎょう', romaji: 'zangyō', meaning: 'tăng ca', partOfSpeech: 'danh từ, động từ する',
        exampleJa: '今日は残業しなければならない。', exampleKana: 'きょうはざんぎょうしなければならない。', exampleVi: 'Hôm nay tôi phải tăng ca.' },
      { kanji: '出張', kana: 'しゅっちょう', romaji: 'shutchō', meaning: 'đi công tác', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '会議', kana: 'かいぎ', romaji: 'kaigi', meaning: 'cuộc họp', partOfSpeech: 'danh từ' },
      { kanji: '資料', kana: 'しりょう', romaji: 'shiryō', meaning: 'tài liệu', partOfSpeech: 'danh từ' },
      { kanji: '書類', kana: 'しょるい', romaji: 'shorui', meaning: 'giấy tờ, hồ sơ', partOfSpeech: 'danh từ' },
      { kanji: '担当', kana: 'たんとう', romaji: 'tantō', meaning: 'phụ trách', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '部長', kana: 'ぶちょう', romaji: 'buchō', meaning: 'trưởng phòng', partOfSpeech: 'danh từ' },
      { kanji: '同僚', kana: 'どうりょう', romaji: 'dōryō', meaning: 'đồng nghiệp', partOfSpeech: 'danh từ' },
      { kanji: '部下', kana: 'ぶか', romaji: 'buka', meaning: 'cấp dưới', partOfSpeech: 'danh từ' },
      { kanji: '上司', kana: 'じょうし', romaji: 'jōshi', meaning: 'cấp trên', partOfSpeech: 'danh từ' },
      { kanji: '取引先', kana: 'とりひきさき', romaji: 'torihikisaki', meaning: 'đối tác làm ăn', partOfSpeech: 'danh từ' },
      { kanji: '営業', kana: 'えいぎょう', romaji: 'eigyō', meaning: 'kinh doanh, bán hàng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '契約', kana: 'けいやく', romaji: 'keiyaku', meaning: 'hợp đồng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '許可', kana: 'きょか', romaji: 'kyoka', meaning: 'sự cho phép', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '禁止', kana: 'きんし', romaji: 'kinshi', meaning: 'cấm', partOfSpeech: 'danh từ, động từ する',
        exampleJa: 'ここは駐車禁止です。', exampleKana: 'ここはちゅうしゃきんしです。', exampleVi: 'Ở đây cấm đỗ xe.' },
      { kanji: '命令', kana: 'めいれい', romaji: 'meirei', meaning: 'mệnh lệnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '注意', kana: 'ちゅうい', romaji: 'chūi', meaning: 'chú ý, nhắc nhở', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '文句', kana: 'もんく', romaji: 'monku', meaning: 'lời than phiền', partOfSpeech: 'danh từ' },
      { kanji: '謝る', kana: 'あやまる', romaji: 'ayamaru', meaning: 'xin lỗi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '断る', kana: 'ことわる', romaji: 'kotowaru', meaning: 'từ chối', partOfSpeech: 'động từ nhóm 1',
        exampleJa: '残念ですが、お断りします。', exampleKana: 'ざんねんですが、おことわりします。', exampleVi: 'Rất tiếc, tôi xin từ chối.' },
      { kanji: '任せる', kana: 'まかせる', romaji: 'makaseru', meaning: 'giao phó', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '認める', kana: 'みとめる', romaji: 'mitomeru', meaning: 'công nhận, thừa nhận', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '守る', kana: 'まもる', romaji: 'mamoru', meaning: 'bảo vệ, tuân thủ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '協力', kana: 'きょうりょく', romaji: 'kyōryoku', meaning: 'hợp tác', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '責任', kana: 'せきにん', romaji: 'sekinin', meaning: 'trách nhiệm', partOfSpeech: 'danh từ' },
      { kanji: '経験', kana: 'けいけん', romaji: 'keiken', meaning: 'kinh nghiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '能力', kana: 'のうりょく', romaji: 'nōryoku', meaning: 'năng lực', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 304,
    jlptLevel: 'N3',
    words: [
      { kanji: '経済', kana: 'けいざい', romaji: 'keizai', meaning: 'kinh tế', partOfSpeech: 'danh từ' },
      { kanji: '政治', kana: 'せいじ', romaji: 'seiji', meaning: 'chính trị', partOfSpeech: 'danh từ' },
      { kanji: '社会', kana: 'しゃかい', romaji: 'shakai', meaning: 'xã hội', partOfSpeech: 'danh từ' },
      { kanji: '文化', kana: 'ぶんか', romaji: 'bunka', meaning: 'văn hóa', partOfSpeech: 'danh từ' },
      { kanji: '環境', kana: 'かんきょう', romaji: 'kankyō', meaning: 'môi trường', partOfSpeech: 'danh từ',
        exampleJa: '環境を守ることは大切だ。', exampleKana: 'かんきょうをまもることはたいせつだ。', exampleVi: 'Bảo vệ môi trường là điều quan trọng.' },
      { kanji: '人口', kana: 'じんこう', romaji: 'jinkō', meaning: 'dân số', partOfSpeech: 'danh từ' },
      { kanji: '教育', kana: 'きょういく', romaji: 'kyōiku', meaning: 'giáo dục', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '技術', kana: 'ぎじゅつ', romaji: 'gijutsu', meaning: 'kỹ thuật', partOfSpeech: 'danh từ' },
      { kanji: '産業', kana: 'さんぎょう', romaji: 'sangyō', meaning: 'ngành công nghiệp', partOfSpeech: 'danh từ' },
      { kanji: '製品', kana: 'せいひん', romaji: 'seihin', meaning: 'sản phẩm', partOfSpeech: 'danh từ' },
      { kanji: '商品', kana: 'しょうひん', romaji: 'shōhin', meaning: 'hàng hóa', partOfSpeech: 'danh từ' },
      { kanji: '値段', kana: 'ねだん', romaji: 'nedan', meaning: 'giá cả', partOfSpeech: 'danh từ' },
      { kanji: '価格', kana: 'かかく', romaji: 'kakaku', meaning: 'giá (trang trọng)', partOfSpeech: 'danh từ' },
      { kanji: '費用', kana: 'ひよう', romaji: 'hiyō', meaning: 'chi phí', partOfSpeech: 'danh từ' },
      { kanji: '税金', kana: 'ぜいきん', romaji: 'zeikin', meaning: 'thuế', partOfSpeech: 'danh từ' },
      { kanji: '貯金', kana: 'ちょきん', romaji: 'chokin', meaning: 'tiền tiết kiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '借金', kana: 'しゃっきん', romaji: 'shakkin', meaning: 'nợ nần', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '節約', kana: 'せつやく', romaji: 'setsuyaku', meaning: 'tiết kiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '無駄', kana: 'むだ', romaji: 'muda', meaning: 'lãng phí, vô ích', partOfSpeech: 'tính từ na, danh từ',
        exampleJa: '時間を無駄にしたくない。', exampleKana: 'じかんをむだにしたくない。', exampleVi: 'Tôi không muốn lãng phí thời gian.' },
      { kanji: '発展', kana: 'はってん', romaji: 'hatten', meaning: 'phát triển', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '発達', kana: 'はったつ', romaji: 'hattatsu', meaning: 'phát đạt, tiến bộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '進歩', kana: 'しんぽ', romaji: 'shinpo', meaning: 'tiến bộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '解決', kana: 'かいけつ', romaji: 'kaiketsu', meaning: 'giải quyết', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '問題', kana: 'もんだい', romaji: 'mondai', meaning: 'vấn đề', partOfSpeech: 'danh từ' },
      { kanji: '状況', kana: 'じょうきょう', romaji: 'jōkyō', meaning: 'tình hình', partOfSpeech: 'danh từ' },
      { kanji: '現状', kana: 'げんじょう', romaji: 'genjō', meaning: 'hiện trạng', partOfSpeech: 'danh từ' },
      { kana: 'とにかく', romaji: 'tonikaku', meaning: 'dù sao thì, nói chung', partOfSpeech: 'phó từ' },
      { kana: 'ただし', romaji: 'tadashi', meaning: 'tuy nhiên, với điều kiện', partOfSpeech: 'liên từ' },
      { kanji: '一方', kana: 'いっぽう', romaji: 'ippō', meaning: 'mặt khác', partOfSpeech: 'liên từ' },
      { kana: 'つまり', romaji: 'tsumari', meaning: 'nói cách khác, tức là', partOfSpeech: 'liên từ' },
    ],
  },

  {
    lessonNumber: 305,
    jlptLevel: 'N3',
    words: [
      { kanji: '交通', kana: 'こうつう', romaji: 'kōtsū', meaning: 'giao thông', partOfSpeech: 'danh từ' },
      { kanji: '渋滞', kana: 'じゅうたい', romaji: 'jūtai', meaning: 'tắc đường', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '事故', kana: 'じこ', romaji: 'jiko', meaning: 'tai nạn', partOfSpeech: 'danh từ' },
      { kanji: '故障', kana: 'こしょう', romaji: 'koshō', meaning: 'hỏng hóc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '修理', kana: 'しゅうり', romaji: 'shūri', meaning: 'sửa chữa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '交換', kana: 'こうかん', romaji: 'kōkan', meaning: 'trao đổi, thay thế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '利用', kana: 'りよう', romaji: 'riyō', meaning: 'sử dụng, tận dụng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '予約', kana: 'よやく', romaji: 'yoyaku', meaning: 'đặt trước', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '申し込む', kana: 'もうしこむ', romaji: 'mōshikomu', meaning: 'đăng ký, nộp đơn', partOfSpeech: 'động từ nhóm 1',
        exampleJa: '奨学金を申し込みたい。', exampleKana: 'しょうがくきんをもうしこみたい。', exampleVi: 'Tôi muốn xin học bổng.' },
      { kanji: '募集', kana: 'ぼしゅう', romaji: 'boshū', meaning: 'tuyển, kêu gọi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '受付', kana: 'うけつけ', romaji: 'uketsuke', meaning: 'lễ tân, tiếp nhận', partOfSpeech: 'danh từ' },
      { kanji: '手続き', kana: 'てつづき', romaji: 'tetsuzuki', meaning: 'thủ tục', partOfSpeech: 'danh từ' },
      { kanji: '書類', kana: 'しょるい', romaji: 'shorui', meaning: 'hồ sơ, giấy tờ', partOfSpeech: 'danh từ' },
      { kanji: '記入', kana: 'きにゅう', romaji: 'kinyū', meaning: 'điền vào', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '提出', kana: 'ていしゅつ', romaji: 'teishutsu', meaning: 'nộp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '締め切り', kana: 'しめきり', romaji: 'shimekiri', meaning: 'hạn chót', partOfSpeech: 'danh từ' },
      { kanji: '延長', kana: 'えんちょう', romaji: 'enchō', meaning: 'gia hạn, kéo dài', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '短縮', kana: 'たんしゅく', romaji: 'tanshuku', meaning: 'rút ngắn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '割引', kana: 'わりびき', romaji: 'waribiki', meaning: 'giảm giá', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '返品', kana: 'へんぴん', romaji: 'henpin', meaning: 'trả lại hàng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '注文', kana: 'ちゅうもん', romaji: 'chūmon', meaning: 'đặt hàng, gọi món', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '配達', kana: 'はいたつ', romaji: 'haitatsu', meaning: 'giao hàng', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'ちゃんと', romaji: 'chanto', meaning: 'đàng hoàng, chỉnh chu', partOfSpeech: 'phó từ' },
      { kana: 'きちんと', romaji: 'kichinto', meaning: 'ngăn nắp, đúng mực', partOfSpeech: 'phó từ' },
      { kana: 'そのうち', romaji: 'sono uchi', meaning: 'nay mai, chẳng bao lâu nữa', partOfSpeech: 'phó từ' },
      { kana: 'いつのまにか', romaji: 'itsu no ma ni ka', meaning: 'lúc nào không hay', partOfSpeech: 'phó từ' },
    ],
  },

  // ─────────────────────────────── N2 ───────────────────────────────
  {
    lessonNumber: 401,
    jlptLevel: 'N2',
    words: [
      { kanji: '瞬間', kana: 'しゅんかん', romaji: 'shunkan', meaning: 'khoảnh khắc', partOfSpeech: 'danh từ',
        exampleJa: 'その瞬間、全員が息をのんだ。', exampleKana: 'そのしゅんかん、ぜんいんがいきをのんだ。', exampleVi: 'Khoảnh khắc đó, tất cả nín thở.' },
      { kanji: '直後', kana: 'ちょくご', romaji: 'chokugo', meaning: 'ngay sau', partOfSpeech: 'danh từ' },
      { kanji: '直前', kana: 'ちょくぜん', romaji: 'chokuzen', meaning: 'ngay trước', partOfSpeech: 'danh từ' },
      { kanji: '当時', kana: 'とうじ', romaji: 'tōji', meaning: 'thời điểm đó, hồi ấy', partOfSpeech: 'danh từ' },
      { kanji: '今後', kana: 'こんご', romaji: 'kongo', meaning: 'từ nay về sau', partOfSpeech: 'danh từ' },
      { kanji: '最中', kana: 'さいちゅう', romaji: 'saichū', meaning: 'đang lúc, giữa chừng', partOfSpeech: 'danh từ' },
      { kanji: '途中', kana: 'とちゅう', romaji: 'tochū', meaning: 'giữa đường, giữa chừng', partOfSpeech: 'danh từ' },
      { kanji: '期間', kana: 'きかん', romaji: 'kikan', meaning: 'khoảng thời gian, kỳ hạn', partOfSpeech: 'danh từ' },
      { kanji: '期限', kana: 'きげん', romaji: 'kigen', meaning: 'kỳ hạn, hạn chót', partOfSpeech: 'danh từ',
        exampleJa: '提出期限は明日です。', exampleKana: 'ていしゅつきげんはあすです。', exampleVi: 'Hạn nộp là ngày mai.' },
      { kanji: '締め切り', kana: 'しめきり', romaji: 'shimekiri', meaning: 'hạn cuối', partOfSpeech: 'danh từ' },
      { kanji: '延期', kana: 'えんき', romaji: 'enki', meaning: 'hoãn lại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '中止', kana: 'ちゅうし', romaji: 'chūshi', meaning: 'hủy bỏ, đình chỉ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '実施', kana: 'じっし', romaji: 'jisshi', meaning: 'thực thi, tiến hành', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '開催', kana: 'かいさい', romaji: 'kaisai', meaning: 'tổ chức (sự kiện)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '参加', kana: 'さんか', romaji: 'sanka', meaning: 'tham gia', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '出席', kana: 'しゅっせき', romaji: 'shusseki', meaning: 'có mặt, tham dự', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '欠席', kana: 'けっせき', romaji: 'kesseki', meaning: 'vắng mặt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '遅刻', kana: 'ちこく', romaji: 'chikoku', meaning: 'đến muộn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '早退', kana: 'そうたい', romaji: 'sōtai', meaning: 'về sớm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '訪問', kana: 'ほうもん', romaji: 'hōmon', meaning: 'thăm viếng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '到着', kana: 'とうちゃく', romaji: 'tōchaku', meaning: 'đến nơi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '出発', kana: 'しゅっぱつ', romaji: 'shuppatsu', meaning: 'khởi hành', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '通勤', kana: 'つうきん', romaji: 'tsūkin', meaning: 'đi làm (thông cần)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '通学', kana: 'つうがく', romaji: 'tsūgaku', meaning: 'đi học (thông học)', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'たびたび', romaji: 'tabitabi', meaning: 'nhiều lần, thường xuyên', partOfSpeech: 'phó từ' },
      { kana: 'しばしば', romaji: 'shibashiba', meaning: 'thường xuyên (văn viết)', partOfSpeech: 'phó từ' },
      { kana: 'めったに', romaji: 'metta ni', meaning: 'hiếm khi (+ phủ định)', partOfSpeech: 'phó từ',
        exampleJa: '彼はめったに怒らない。', exampleKana: 'かれはめったにおこらない。', exampleVi: 'Anh ấy hiếm khi tức giận.' },
      { kana: 'たまたま', romaji: 'tamatama', meaning: 'tình cờ', partOfSpeech: 'phó từ' },
      { kana: 'いきなり', romaji: 'ikinari', meaning: 'đột ngột', partOfSpeech: 'phó từ' },
      { kanji: '突然', kana: 'とつぜん', romaji: 'totsuzen', meaning: 'bỗng nhiên', partOfSpeech: 'phó từ' },
    ],
  },
  {
    lessonNumber: 402,
    jlptLevel: 'N2',
    words: [
      { kanji: '基準', kana: 'きじゅん', romaji: 'kijun', meaning: 'tiêu chuẩn', partOfSpeech: 'danh từ' },
      { kanji: '基本', kana: 'きほん', romaji: 'kihon', meaning: 'cơ bản', partOfSpeech: 'danh từ' },
      { kanji: '原則', kana: 'げんそく', romaji: 'gensoku', meaning: 'nguyên tắc', partOfSpeech: 'danh từ' },
      { kanji: '条件', kana: 'じょうけん', romaji: 'jōken', meaning: 'điều kiện', partOfSpeech: 'danh từ',
        exampleJa: 'その条件なら受け入れられる。', exampleKana: 'そのじょうけんならうけいれられる。', exampleVi: 'Điều kiện đó thì tôi chấp nhận được.' },
      { kanji: '立場', kana: 'たちば', romaji: 'tachiba', meaning: 'lập trường, vị thế', partOfSpeech: 'danh từ' },
      { kanji: '観点', kana: 'かんてん', romaji: 'kanten', meaning: 'quan điểm', partOfSpeech: 'danh từ' },
      { kanji: '価値', kana: 'かち', romaji: 'kachi', meaning: 'giá trị', partOfSpeech: 'danh từ' },
      { kanji: '評価', kana: 'ひょうか', romaji: 'hyōka', meaning: 'đánh giá', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '判定', kana: 'はんてい', romaji: 'hantei', meaning: 'phán định', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '対象', kana: 'たいしょう', romaji: 'taishō', meaning: 'đối tượng', partOfSpeech: 'danh từ' },
      { kanji: '対応', kana: 'たいおう', romaji: 'taiō', meaning: 'ứng phó, xử lý', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '関連', kana: 'かんれん', romaji: 'kanren', meaning: 'liên quan', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '要素', kana: 'ようそ', romaji: 'yōso', meaning: 'yếu tố', partOfSpeech: 'danh từ' },
      { kanji: '内容', kana: 'ないよう', romaji: 'naiyō', meaning: 'nội dung', partOfSpeech: 'danh từ' },
      { kanji: '傾向', kana: 'けいこう', romaji: 'keikō', meaning: 'khuynh hướng', partOfSpeech: 'danh từ',
        exampleJa: '最近、晩婚化の傾向がある。', exampleKana: 'さいきん、ばんこんかのけいこうがある。', exampleVi: 'Gần đây có xu hướng kết hôn muộn.' },
      { kanji: '特徴', kana: 'とくちょう', romaji: 'tokuchō', meaning: 'đặc trưng', partOfSpeech: 'danh từ' },
      { kanji: '性質', kana: 'せいしつ', romaji: 'seishitsu', meaning: 'tính chất', partOfSpeech: 'danh từ' },
      { kanji: '程度', kana: 'ていど', romaji: 'teido', meaning: 'mức độ', partOfSpeech: 'danh từ' },
      { kanji: '範囲', kana: 'はんい', romaji: 'han\'i', meaning: 'phạm vi', partOfSpeech: 'danh từ' },
      { kanji: '割合', kana: 'わりあい', romaji: 'wariai', meaning: 'tỷ lệ', partOfSpeech: 'danh từ' },
      { kanji: '平均', kana: 'へいきん', romaji: 'heikin', meaning: 'trung bình', partOfSpeech: 'danh từ' },
      { kanji: '合計', kana: 'ごうけい', romaji: 'gōkei', meaning: 'tổng cộng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '増加', kana: 'ぞうか', romaji: 'zōka', meaning: 'sự gia tăng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '減少', kana: 'げんしょう', romaji: 'genshō', meaning: 'sự giảm sút', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '比較', kana: 'ひかく', romaji: 'hikaku', meaning: 'so sánh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '区別', kana: 'くべつ', romaji: 'kubetsu', meaning: 'phân biệt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '共通', kana: 'きょうつう', romaji: 'kyōtsū', meaning: 'điểm chung', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '相互', kana: 'そうご', romaji: 'sōgo', meaning: 'lẫn nhau, tương hỗ', partOfSpeech: 'danh từ' },
      { kanji: '主張', kana: 'しゅちょう', romaji: 'shuchō', meaning: 'chủ trương, khẳng định', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '反対', kana: 'はんたい', romaji: 'hantai', meaning: 'phản đối; ngược lại', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 403,
    jlptLevel: 'N2',
    words: [
      { kanji: '我慢', kana: 'がまん', romaji: 'gaman', meaning: 'nhẫn nhịn, chịu đựng', partOfSpeech: 'danh từ, động từ する',
        exampleJa: '痛みを我慢した。', exampleKana: 'いたみをがまんした。', exampleVi: 'Tôi đã chịu đựng cơn đau.' },
      { kanji: '遠慮', kana: 'えんりょ', romaji: 'enryo', meaning: 'sự khách sáo, e ngại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '努める', kana: 'つとめる', romaji: 'tsutomeru', meaning: 'nỗ lực, cố gắng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '諦める', kana: 'あきらめる', romaji: 'akirameru', meaning: 'từ bỏ, buông xuôi', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '我慢強い', kana: 'がまんづよい', romaji: 'gamanzuyoi', meaning: 'kiên nhẫn', partOfSpeech: 'tính từ i' },
      { kanji: '苦労', kana: 'くろう', romaji: 'kurō', meaning: 'vất vả, lao đao', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '面倒', kana: 'めんどう', romaji: 'mendō', meaning: 'phiền phức', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '迷惑', kana: 'めいわく', romaji: 'meiwaku', meaning: 'phiền hà', partOfSpeech: 'tính từ na, danh từ, động từ する',
        exampleJa: 'ご迷惑をおかけしました。', exampleKana: 'ごめいわくをおかけしました。', exampleVi: 'Tôi đã làm phiền quý vị.' },
      { kanji: '文句を言う', kana: 'もんくをいう', romaji: 'monku o iu', meaning: 'than phiền', partOfSpeech: 'cụm động từ' },
      { kanji: '限る', kana: 'かぎる', romaji: 'kagiru', meaning: 'giới hạn; không hẳn (〜とは限らない)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '限界', kana: 'げんかい', romaji: 'genkai', meaning: 'giới hạn', partOfSpeech: 'danh từ' },
      { kanji: '制限', kana: 'せいげん', romaji: 'seigen', meaning: 'hạn chế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '不足', kana: 'ふそく', romaji: 'fusoku', meaning: 'thiếu hụt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '余る', kana: 'あまる', romaji: 'amaru', meaning: 'thừa, dư', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '余分', kana: 'よぶん', romaji: 'yobun', meaning: 'phần dư, thừa', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '十分', kana: 'じゅうぶん', romaji: 'jūbun', meaning: 'đầy đủ', partOfSpeech: 'tính từ na, phó từ' },
      { kanji: '実は', kana: 'じつは', romaji: 'jitsu wa', meaning: 'thật ra', partOfSpeech: 'phó từ' },
      { kana: 'まさか', romaji: 'masaka', meaning: 'chẳng lẽ, không thể nào', partOfSpeech: 'phó từ',
        exampleJa: 'まさか彼が来るとは思わなかった。', exampleKana: 'まさかかれがくるとはおもわなかった。', exampleVi: 'Không ngờ anh ấy lại đến.' },
      { kana: 'どうせ', romaji: 'dōse', meaning: 'đằng nào cũng, dù sao cũng', partOfSpeech: 'phó từ' },
      { kana: 'せめて', romaji: 'semete', meaning: 'ít nhất thì, chí ít', partOfSpeech: 'phó từ' },
      { kana: 'たとえ', romaji: 'tatoe', meaning: 'cho dù (~ても)', partOfSpeech: 'phó từ' },
      { kana: 'もしかしたら', romaji: 'moshikashitara', meaning: 'biết đâu, có thể', partOfSpeech: 'phó từ' },
      { kana: 'あいにく', romaji: 'ainiku', meaning: 'không may, đáng tiếc là', partOfSpeech: 'phó từ' },
      { kana: 'さすが', romaji: 'sasuga', meaning: 'quả nhiên, đúng là (xứng danh)', partOfSpeech: 'phó từ' },
      { kana: 'いくら〜ても', romaji: 'ikura ~ temo', meaning: 'dù ~ đến mấy cũng', partOfSpeech: 'cấu trúc phó từ' },
      { kanji: '相変わらず', kana: 'あいかわらず', romaji: 'aikawarazu', meaning: 'vẫn như mọi khi', partOfSpeech: 'phó từ' },
      { kana: 'かえって', romaji: 'kaette', meaning: 'trái lại, ngược lại', partOfSpeech: 'phó từ' },
      { kanji: '案外', kana: 'あんがい', romaji: 'angai', meaning: 'ngoài dự đoán, không ngờ', partOfSpeech: 'phó từ, tính từ na' },
      { kanji: '意外', kana: 'いがい', romaji: 'igai', meaning: 'bất ngờ', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '当然', kana: 'とうぜん', romaji: 'tōzen', meaning: 'đương nhiên', partOfSpeech: 'tính từ na, phó từ' },
    ],
  },
  {
    lessonNumber: 404,
    jlptLevel: 'N2',
    words: [
      { kanji: '解釈', kana: 'かいしゃく', romaji: 'kaishaku', meaning: 'sự diễn giải', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '検討', kana: 'けんとう', romaji: 'kentō', meaning: 'xem xét, cân nhắc', partOfSpeech: 'danh từ, động từ する',
        exampleJa: '前向きに検討します。', exampleKana: 'まえむきにけんとうします。', exampleVi: 'Chúng tôi sẽ cân nhắc tích cực.' },
      { kanji: '考慮', kana: 'こうりょ', romaji: 'kōryo', meaning: 'cân nhắc, chiếu cố', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '検査', kana: 'けんさ', romaji: 'kensa', meaning: 'kiểm tra (y tế/kỹ thuật)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '調査', kana: 'ちょうさ', romaji: 'chōsa', meaning: 'điều tra, khảo sát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '観察', kana: 'かんさつ', romaji: 'kansatsu', meaning: 'quan sát', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '分析', kana: 'ぶんせき', romaji: 'bunseki', meaning: 'phân tích', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '実験', kana: 'じっけん', romaji: 'jikken', meaning: 'thí nghiệm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '証明', kana: 'しょうめい', romaji: 'shōmei', meaning: 'chứng minh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '証拠', kana: 'しょうこ', romaji: 'shōko', meaning: 'bằng chứng', partOfSpeech: 'danh từ' },
      { kanji: '事実', kana: 'じじつ', romaji: 'jijitsu', meaning: 'sự thật', partOfSpeech: 'danh từ' },
      { kanji: '真実', kana: 'しんじつ', romaji: 'shinjitsu', meaning: 'chân lý, sự thật', partOfSpeech: 'danh từ' },
      { kanji: '事情', kana: 'じじょう', romaji: 'jijō', meaning: 'hoàn cảnh, nguyên do', partOfSpeech: 'danh từ' },
      { kanji: '背景', kana: 'はいけい', romaji: 'haikei', meaning: 'bối cảnh', partOfSpeech: 'danh từ' },
      { kanji: '前提', kana: 'ぜんてい', romaji: 'zentei', meaning: 'tiền đề', partOfSpeech: 'danh từ' },
      { kanji: '仮定', kana: 'かてい', romaji: 'katei', meaning: 'giả định', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '結論', kana: 'けつろん', romaji: 'ketsuron', meaning: 'kết luận', partOfSpeech: 'danh từ' },
      { kanji: '要点', kana: 'ようてん', romaji: 'yōten', meaning: 'điểm chính', partOfSpeech: 'danh từ' },
      { kanji: '要約', kana: 'ようやく', romaji: 'yōyaku', meaning: 'tóm tắt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '矛盾', kana: 'むじゅん', romaji: 'mujun', meaning: 'mâu thuẫn', partOfSpeech: 'danh từ, động từ する',
        exampleJa: '彼の話には矛盾がある。', exampleKana: 'かれのはなしにはむじゅんがある。', exampleVi: 'Lời anh ta có mâu thuẫn.' },
      { kanji: '疑問', kana: 'ぎもん', romaji: 'gimon', meaning: 'nghi vấn, thắc mắc', partOfSpeech: 'danh từ' },
      { kanji: '誤解', kana: 'ごかい', romaji: 'gokai', meaning: 'hiểu lầm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '納得', kana: 'なっとく', romaji: 'nattoku', meaning: 'thông hiểu, chấp thuận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '賛成', kana: 'さんせい', romaji: 'sansei', meaning: 'tán thành', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '批判', kana: 'ひはん', romaji: 'hihan', meaning: 'phê phán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '否定', kana: 'ひてい', romaji: 'hitei', meaning: 'phủ định', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '肯定', kana: 'こうてい', romaji: 'kōtei', meaning: 'khẳng định', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '曖昧', kana: 'あいまい', romaji: 'aimai', meaning: 'mơ hồ, mập mờ', partOfSpeech: 'tính từ na' },
      { kanji: '明確', kana: 'めいかく', romaji: 'meikaku', meaning: 'rõ ràng, minh xác', partOfSpeech: 'tính từ na' },
      { kanji: '適切', kana: 'てきせつ', romaji: 'tekisetsu', meaning: 'thích hợp, đúng đắn', partOfSpeech: 'tính từ na' },
    ],
  },

  {
    lessonNumber: 405,
    jlptLevel: 'N2',
    words: [
      { kanji: '効果', kana: 'こうか', romaji: 'kōka', meaning: 'hiệu quả', partOfSpeech: 'danh từ' },
      { kanji: '効率', kana: 'こうりつ', romaji: 'kōritsu', meaning: 'hiệu suất', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '成果', kana: 'せいか', romaji: 'seika', meaning: 'thành quả', partOfSpeech: 'danh từ' },
      { kanji: '影響', kana: 'えいきょう', romaji: 'eikyō', meaning: 'ảnh hưởng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '結果', kana: 'けっか', romaji: 'kekka', meaning: 'kết quả', partOfSpeech: 'danh từ' },
      { kanji: '原因', kana: 'げんいん', romaji: 'gen\'in', meaning: 'nguyên nhân', partOfSpeech: 'danh từ' },
      { kanji: '要因', kana: 'よういん', romaji: 'yōin', meaning: 'nhân tố', partOfSpeech: 'danh từ' },
      { kanji: '相当', kana: 'そうとう', romaji: 'sōtō', meaning: 'tương đương; khá là', partOfSpeech: 'tính từ na, phó từ, động từ する' },
      { kanji: '大幅', kana: 'おおはば', romaji: 'ōhaba', meaning: 'mức độ lớn, đáng kể', partOfSpeech: 'tính từ na, danh từ',
        exampleJa: '価格が大幅に下がった。', exampleKana: 'かかくがおおはばにさがった。', exampleVi: 'Giá giảm đáng kể.' },
      { kanji: '急激', kana: 'きゅうげき', romaji: 'kyūgeki', meaning: 'đột ngột, mãnh liệt', partOfSpeech: 'tính từ na' },
      { kanji: '徐々に', kana: 'じょじょに', romaji: 'jojo ni', meaning: 'dần dần', partOfSpeech: 'phó từ' },
      { kanji: '次第に', kana: 'しだいに', romaji: 'shidai ni', meaning: 'dần dà', partOfSpeech: 'phó từ' },
      { kanji: '一気に', kana: 'いっきに', romaji: 'ikki ni', meaning: 'một hơi, một mạch', partOfSpeech: 'phó từ' },
      { kanji: '相次いで', kana: 'あいついで', romaji: 'aitsuide', meaning: 'liên tiếp', partOfSpeech: 'phó từ' },
      { kanji: '実現', kana: 'じつげん', romaji: 'jitsugen', meaning: 'hiện thực hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '達成', kana: 'たっせい', romaji: 'tassei', meaning: 'đạt được', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '実行', kana: 'じっこう', romaji: 'jikkō', meaning: 'thực hiện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '中心', kana: 'ちゅうしん', romaji: 'chūshin', meaning: 'trung tâm', partOfSpeech: 'danh từ' },
      { kanji: '中核', kana: 'ちゅうかく', romaji: 'chūkaku', meaning: 'hạt nhân, cốt lõi', partOfSpeech: 'danh từ' },
      { kanji: '重点', kana: 'じゅうてん', romaji: 'jūten', meaning: 'trọng điểm', partOfSpeech: 'danh từ' },
      { kanji: '前後', kana: 'ぜんご', romaji: 'zengo', meaning: 'trước sau; khoảng chừng', partOfSpeech: 'danh từ' },
      { kanji: '主に', kana: 'おもに', romaji: 'omo ni', meaning: 'chủ yếu', partOfSpeech: 'phó từ' },
      { kana: 'ことに', romaji: 'koto ni', meaning: 'đặc biệt là', partOfSpeech: 'phó từ' },
      { kana: 'いわゆる', romaji: 'iwayuru', meaning: 'cái gọi là', partOfSpeech: 'liên thể từ' },
    ],
  },

  // ─────────────────────────────── N1 ───────────────────────────────
  {
    lessonNumber: 501,
    jlptLevel: 'N1',
    words: [
      { kanji: '概念', kana: 'がいねん', romaji: 'gainen', meaning: 'khái niệm', partOfSpeech: 'danh từ' },
      { kanji: '前提', kana: 'ぜんてい', romaji: 'zentei', meaning: 'tiền đề', partOfSpeech: 'danh từ' },
      { kanji: '本質', kana: 'ほんしつ', romaji: 'honshitsu', meaning: 'bản chất', partOfSpeech: 'danh từ',
        exampleJa: '問題の本質を見抜く。', exampleKana: 'もんだいのほんしつをみぬく。', exampleVi: 'Nhìn thấu bản chất vấn đề.' },
      { kanji: '要因', kana: 'よういん', romaji: 'yōin', meaning: 'nhân tố chính', partOfSpeech: 'danh từ' },
      { kanji: '根拠', kana: 'こんきょ', romaji: 'konkyo', meaning: 'căn cứ', partOfSpeech: 'danh từ' },
      { kanji: '観念', kana: 'かんねん', romaji: 'kannen', meaning: 'quan niệm', partOfSpeech: 'danh từ' },
      { kanji: '理念', kana: 'りねん', romaji: 'rinen', meaning: 'lý tưởng, triết lý', partOfSpeech: 'danh từ' },
      { kanji: '意義', kana: 'いぎ', romaji: 'igi', meaning: 'ý nghĩa (giá trị)', partOfSpeech: 'danh từ' },
      { kanji: '趣旨', kana: 'しゅし', romaji: 'shushi', meaning: 'tôn chỉ, ý chính', partOfSpeech: 'danh từ' },
      { kanji: '傾向', kana: 'けいこう', romaji: 'keikō', meaning: 'khuynh hướng', partOfSpeech: 'danh từ' },
      { kanji: '本音', kana: 'ほんね', romaji: 'honne', meaning: 'suy nghĩ thật', partOfSpeech: 'danh từ' },
      { kanji: '建前', kana: 'たてまえ', romaji: 'tatemae', meaning: 'lời nói khách sáo bề ngoài', partOfSpeech: 'danh từ' },
      { kanji: '偏見', kana: 'へんけん', romaji: 'henken', meaning: 'thành kiến', partOfSpeech: 'danh từ' },
      { kanji: '固定観念', kana: 'こていかんねん', romaji: 'kotei kannen', meaning: 'định kiến cố hữu', partOfSpeech: 'danh từ' },
      { kanji: '見解', kana: 'けんかい', romaji: 'kenkai', meaning: 'quan điểm, kiến giải', partOfSpeech: 'danh từ' },
      { kanji: '妥協', kana: 'だきょう', romaji: 'dakyō', meaning: 'thỏa hiệp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '譲歩', kana: 'じょうほ', romaji: 'jōho', meaning: 'nhượng bộ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '合意', kana: 'ごうい', romaji: 'gōi', meaning: 'sự nhất trí', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '交渉', kana: 'こうしょう', romaji: 'kōshō', meaning: 'đàm phán', partOfSpeech: 'danh từ, động từ する',
        exampleJa: '賃金の交渉が難航している。', exampleKana: 'ちんぎんのこうしょうがなんこうしている。', exampleVi: 'Đàm phán lương đang bế tắc.' },
      { kanji: '対立', kana: 'たいりつ', romaji: 'tairitsu', meaning: 'đối lập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '摩擦', kana: 'まさつ', romaji: 'masatsu', meaning: 'ma sát, xích mích', partOfSpeech: 'danh từ' },
      { kanji: '調和', kana: 'ちょうわ', romaji: 'chōwa', meaning: 'hài hòa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '均衡', kana: 'きんこう', romaji: 'kinkō', meaning: 'cân bằng', partOfSpeech: 'danh từ' },
      { kanji: '是非', kana: 'ぜひ', romaji: 'zehi', meaning: 'đúng sai, phải trái', partOfSpeech: 'danh từ' },
      { kanji: '妥当', kana: 'だとう', romaji: 'datō', meaning: 'thỏa đáng', partOfSpeech: 'tính từ na' },
      { kanji: '顕著', kana: 'けんちょ', romaji: 'kencho', meaning: 'rõ rệt, nổi bật', partOfSpeech: 'tính từ na' },
      { kanji: '深刻', kana: 'しんこく', romaji: 'shinkoku', meaning: 'nghiêm trọng', partOfSpeech: 'tính từ na' },
      { kanji: '不可欠', kana: 'ふかけつ', romaji: 'fukaketsu', meaning: 'không thể thiếu', partOfSpeech: 'tính từ na' },
      { kanji: '画一的', kana: 'かくいつてき', romaji: 'kakuitsuteki', meaning: 'rập khuôn, đồng nhất', partOfSpeech: 'tính từ na' },
      { kanji: '相対的', kana: 'そうたいてき', romaji: 'sōtaiteki', meaning: 'mang tính tương đối', partOfSpeech: 'tính từ na' },
    ],
  },
  {
    lessonNumber: 502,
    jlptLevel: 'N1',
    words: [
      { kanji: '把握', kana: 'はあく', romaji: 'haaku', meaning: 'nắm bắt', partOfSpeech: 'danh từ, động từ する',
        exampleJa: '状況を正確に把握する。', exampleKana: 'じょうきょうをせいかくにはあくする。', exampleVi: 'Nắm bắt chính xác tình hình.' },
      { kanji: '推測', kana: 'すいそく', romaji: 'suisoku', meaning: 'suy đoán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '推進', kana: 'すいしん', romaji: 'suishin', meaning: 'thúc đẩy', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '促進', kana: 'そくしん', romaji: 'sokushin', meaning: 'xúc tiến', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '抑制', kana: 'よくせい', romaji: 'yokusei', meaning: 'kìm hãm, ức chế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '緩和', kana: 'かんわ', romaji: 'kanwa', meaning: 'nới lỏng, làm dịu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '強化', kana: 'きょうか', romaji: 'kyōka', meaning: 'tăng cường', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '導入', kana: 'どうにゅう', romaji: 'dōnyū', meaning: 'đưa vào áp dụng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '確立', kana: 'かくりつ', romaji: 'kakuritsu', meaning: 'xác lập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '普及', kana: 'ふきゅう', romaji: 'fukyū', meaning: 'phổ cập', partOfSpeech: 'danh từ, động từ する',
        exampleJa: 'スマホが急速に普及した。', exampleKana: 'スマホがきゅうそくにふきゅうした。', exampleVi: 'Điện thoại thông minh phổ cập nhanh chóng.' },
      { kanji: '維持', kana: 'いじ', romaji: 'iji', meaning: 'duy trì', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '継続', kana: 'けいぞく', romaji: 'keizoku', meaning: 'tiếp tục, liên tục', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '中断', kana: 'ちゅうだん', romaji: 'chūdan', meaning: 'gián đoạn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '廃止', kana: 'はいし', romaji: 'haishi', meaning: 'bãi bỏ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '転換', kana: 'てんかん', romaji: 'tenkan', meaning: 'chuyển đổi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '改革', kana: 'かいかく', romaji: 'kaikaku', meaning: 'cải cách', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '改善', kana: 'かいぜん', romaji: 'kaizen', meaning: 'cải thiện', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '是正', kana: 'ぜせい', romaji: 'zesei', meaning: 'chỉnh sửa cho đúng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '対処', kana: 'たいしょ', romaji: 'taisho', meaning: 'ứng phó', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '措置', kana: 'そち', romaji: 'sochi', meaning: 'biện pháp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '対策', kana: 'たいさく', romaji: 'taisaku', meaning: 'đối sách', partOfSpeech: 'danh từ' },
      { kanji: '課題', kana: 'かだい', romaji: 'kadai', meaning: 'nhiệm vụ, vấn đề cần giải quyết', partOfSpeech: 'danh từ' },
      { kanji: '懸念', kana: 'けねん', romaji: 'kenen', meaning: 'sự quan ngại', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '弊害', kana: 'へいがい', romaji: 'heigai', meaning: 'tệ hại, tác hại', partOfSpeech: 'danh từ' },
      { kanji: '恩恵', kana: 'おんけい', romaji: 'onkei', meaning: 'ân huệ, lợi ích', partOfSpeech: 'danh từ' },
      { kanji: '打開', kana: 'だかい', romaji: 'dakai', meaning: 'phá vỡ bế tắc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '両立', kana: 'りょうりつ', romaji: 'ryōritsu', meaning: 'song hành, cân bằng cả hai', partOfSpeech: 'danh từ, động từ する',
        exampleJa: '仕事と育児を両立する。', exampleKana: 'しごとといくじをりょうりつする。', exampleVi: 'Cân bằng cả công việc lẫn nuôi con.' },
      { kanji: '模索', kana: 'もさく', romaji: 'mosaku', meaning: 'mò mẫm tìm kiếm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '着手', kana: 'ちゃくしゅ', romaji: 'chakushu', meaning: 'bắt tay vào', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '遂行', kana: 'すいこう', romaji: 'suikō', meaning: 'thực hiện đến cùng', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 503,
    jlptLevel: 'N1',
    words: [
      { kanji: '感慨', kana: 'かんがい', romaji: 'kangai', meaning: 'nỗi niềm cảm khái', partOfSpeech: 'danh từ' },
      { kanji: '未練', kana: 'みれん', romaji: 'miren', meaning: 'sự lưu luyến, day dứt', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '名残', kana: 'なごり', romaji: 'nagori', meaning: 'dấu vết còn lại, sự bịn rịn', partOfSpeech: 'danh từ' },
      { kanji: '衝動', kana: 'しょうどう', romaji: 'shōdō', meaning: 'sự bốc đồng', partOfSpeech: 'danh từ' },
      { kanji: '葛藤', kana: 'かっとう', romaji: 'kattō', meaning: 'sự giằng xé nội tâm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '嫉妬', kana: 'しっと', romaji: 'shitto', meaning: 'ghen tị', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '憂鬱', kana: 'ゆううつ', romaji: 'yūutsu', meaning: 'u uất', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '苦悩', kana: 'くのう', romaji: 'kunō', meaning: 'khổ não', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '安堵', kana: 'あんど', romaji: 'ando', meaning: 'sự nhẹ nhõm', partOfSpeech: 'danh từ, động từ する',
        exampleJa: '無事の知らせに安堵した。', exampleKana: 'ぶじのしらせにあんどした。', exampleVi: 'Tôi nhẹ nhõm khi nghe tin bình an.' },
      { kanji: '感無量', kana: 'かんむりょう', romaji: 'kanmuryō', meaning: 'xúc động khôn xiết', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '心構え', kana: 'こころがまえ', romaji: 'kokorogamae', meaning: 'sự chuẩn bị tinh thần', partOfSpeech: 'danh từ' },
      { kanji: '覚悟', kana: 'かくご', romaji: 'kakugo', meaning: 'sự quyết tâm, sẵn sàng đón nhận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '決意', kana: 'けつい', romaji: 'ketsui', meaning: 'quyết ý', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '信念', kana: 'しんねん', romaji: 'shinnen', meaning: 'niềm tin, tín niệm', partOfSpeech: 'danh từ' },
      { kanji: '誇り', kana: 'ほこり', romaji: 'hokori', meaning: 'niềm tự hào', partOfSpeech: 'danh từ' },
      { kanji: '尊厳', kana: 'そんげん', romaji: 'songen', meaning: 'phẩm giá, tôn nghiêm', partOfSpeech: 'danh từ' },
      { kanji: '偏り', kana: 'かたより', romaji: 'katayori', meaning: 'sự thiên lệch', partOfSpeech: 'danh từ' },
      { kanji: '相応しい', kana: 'ふさわしい', romaji: 'fusawashii', meaning: 'xứng đáng, phù hợp', partOfSpeech: 'tính từ i' },
      { kanji: '著しい', kana: 'いちじるしい', romaji: 'ichijirushii', meaning: 'rõ rệt, đáng kể', partOfSpeech: 'tính từ i' },
      { kanji: '甚だしい', kana: 'はなはだしい', romaji: 'hanahadashii', meaning: 'quá mức, trầm trọng', partOfSpeech: 'tính từ i' },
      { kanji: '紛らわしい', kana: 'まぎらわしい', romaji: 'magirawashii', meaning: 'dễ nhầm lẫn', partOfSpeech: 'tính từ i' },
      { kanji: '煩わしい', kana: 'わずらわしい', romaji: 'wazurawashii', meaning: 'rắc rối, phiền toái', partOfSpeech: 'tính từ i' },
      { kanji: '否めない', kana: 'いなめない', romaji: 'inamenai', meaning: 'không thể phủ nhận', partOfSpeech: 'cụm từ' },
      { kana: 'ひたすら', romaji: 'hitasura', meaning: 'một mực, chuyên tâm', partOfSpeech: 'phó từ' },
      { kana: 'ことごとく', romaji: 'kotogotoku', meaning: 'hết thảy, toàn bộ', partOfSpeech: 'phó từ' },
      { kana: 'あえて', romaji: 'aete', meaning: 'cố tình, dám (làm điều khó)', partOfSpeech: 'phó từ' },
      { kana: 'もはや', romaji: 'mohaya', meaning: 'giờ đây đã (không còn)', partOfSpeech: 'phó từ' },
      { kana: 'いかにも', romaji: 'ikanimo', meaning: 'quả đúng là, trông rất ~', partOfSpeech: 'phó từ' },
      { kana: 'とりわけ', romaji: 'toriwake', meaning: 'đặc biệt là', partOfSpeech: 'phó từ' },
      { kana: 'おのずと', romaji: 'onozuto', meaning: 'tự nhiên mà, tự khắc', partOfSpeech: 'phó từ' },
    ],
  },
  {
    lessonNumber: 504,
    jlptLevel: 'N1',
    words: [
      { kanji: '範疇', kana: 'はんちゅう', romaji: 'hanchū', meaning: 'phạm trù', partOfSpeech: 'danh từ' },
      { kanji: '領域', kana: 'りょういき', romaji: 'ryōiki', meaning: 'lĩnh vực, địa hạt', partOfSpeech: 'danh từ' },
      { kanji: '枠', kana: 'わく', romaji: 'waku', meaning: 'khuôn khổ, khung', partOfSpeech: 'danh từ',
        exampleJa: '常識の枠を超える発想。', exampleKana: 'じょうしきのわくをこえるはっそう。', exampleVi: 'Ý tưởng vượt khỏi khuôn khổ thường thức.' },
      { kanji: '境界', kana: 'きょうかい', romaji: 'kyōkai', meaning: 'ranh giới', partOfSpeech: 'danh từ' },
      { kanji: '限度', kana: 'げんど', romaji: 'gendo', meaning: 'hạn độ, giới hạn', partOfSpeech: 'danh từ' },
      { kanji: '極端', kana: 'きょくたん', romaji: 'kyokutan', meaning: 'cực đoan, thái quá', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '大幅', kana: 'おおはば', romaji: 'ōhaba', meaning: 'mức độ lớn', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '一律', kana: 'いちりつ', romaji: 'ichiritsu', meaning: 'đồng loạt, cào bằng', partOfSpeech: 'tính từ na, phó từ' },
      { kanji: '網羅', kana: 'もうら', romaji: 'mōra', meaning: 'bao quát, gồm hết', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '該当', kana: 'がいとう', romaji: 'gaitō', meaning: 'thuộc diện, tương ứng', partOfSpeech: 'danh từ, động từ する',
        exampleJa: '該当する項目に丸をつける。', exampleKana: 'がいとうするこうもくにまるをつける。', exampleVi: 'Khoanh tròn vào mục tương ứng.' },
      { kanji: '対象外', kana: 'たいしょうがい', romaji: 'taishōgai', meaning: 'ngoài đối tượng', partOfSpeech: 'danh từ' },
      { kanji: '例外', kana: 'れいがい', romaji: 'reigai', meaning: 'ngoại lệ', partOfSpeech: 'danh từ' },
      { kanji: '前例', kana: 'ぜんれい', romaji: 'zenrei', meaning: 'tiền lệ', partOfSpeech: 'danh từ' },
      { kanji: '慣例', kana: 'かんれい', romaji: 'kanrei', meaning: 'thông lệ', partOfSpeech: 'danh từ' },
      { kanji: '原則', kana: 'げんそく', romaji: 'gensoku', meaning: 'nguyên tắc', partOfSpeech: 'danh từ' },
      { kanji: '暫定', kana: 'ざんてい', romaji: 'zantei', meaning: 'tạm thời, lâm thời', partOfSpeech: 'danh từ' },
      { kanji: '恒久', kana: 'こうきゅう', romaji: 'kōkyū', meaning: 'lâu dài, vĩnh cửu', partOfSpeech: 'danh từ' },
      { kanji: '一貫', kana: 'いっかん', romaji: 'ikkan', meaning: 'nhất quán', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '徹底', kana: 'てってい', romaji: 'tettei', meaning: 'triệt để', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '柔軟', kana: 'じゅうなん', romaji: 'jūnan', meaning: 'linh hoạt, mềm dẻo', partOfSpeech: 'tính từ na' },
      { kanji: '寛容', kana: 'かんよう', romaji: 'kan\'yō', meaning: 'khoan dung', partOfSpeech: 'tính từ na, danh từ' },
      { kanji: '厳格', kana: 'げんかく', romaji: 'genkaku', meaning: 'nghiêm khắc, khắt khe', partOfSpeech: 'tính từ na' },
      { kana: 'あくまで', romaji: 'akumade', meaning: 'đến cùng; chỉ là (nhấn mạnh)', partOfSpeech: 'phó từ' },
      { kana: 'いかんせん', romaji: 'ikansen', meaning: 'khổ nỗi, ngặt nỗi', partOfSpeech: 'phó từ' },
    ],
  },
];
