// Bổ sung từ vựng N2 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 736-741.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N2_PART7: JlptVocabUnit[] = [
  {
    lessonNumber: 736,
    jlptLevel: 'N2',
    words: [
      { kanji: '材木', kana: 'ざいもく', romaji: 'zaimoku', meaning: 'gỗ, vật liệu gỗ', partOfSpeech: 'danh từ' },
      { kanji: '作成', kana: 'さくせい', romaji: 'sakusei', meaning: 'sự soạn thảo, lập ra', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '削ります', kana: 'けずります', romaji: 'kezurimasu', meaning: 'gọt, cắt giảm', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '削除', kana: 'さくじょ', romaji: 'sakujo', meaning: 'sự xóa bỏ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '索引', kana: 'さくいん', romaji: 'sakuin', meaning: 'bảng chỉ mục, tra cứu', partOfSpeech: 'danh từ' },
      { kanji: '匙', kana: 'さじ', romaji: 'saji', meaning: 'cái thìa', partOfSpeech: 'danh từ' },
      { kanji: '雑音', kana: 'ざつおん', romaji: 'zatsuon', meaning: 'tiếng ồn, tạp âm', partOfSpeech: 'danh từ' },
      { kanji: '雑巾', kana: 'ぞうきん', romaji: 'zōkin', meaning: 'giẻ lau nhà', partOfSpeech: 'danh từ' },
      { kanji: '錆', kana: 'さび', romaji: 'sabi', meaning: 'gỉ sét', partOfSpeech: 'danh từ' },
      { kanji: '錆びます', kana: 'さびます', romaji: 'sabimasu', meaning: 'bị gỉ sét', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '三角', kana: 'さんかく', romaji: 'sankaku', meaning: 'hình tam giác', partOfSpeech: 'danh từ' },
      { kanji: '三日月', kana: 'みかづき', romaji: 'mikazuki', meaning: 'trăng lưỡi liềm', partOfSpeech: 'danh từ' },
      { kanji: '山林', kana: 'さんりん', romaji: 'sanrin', meaning: 'rừng núi', partOfSpeech: 'danh từ' },
      { kanji: '散らかします', kana: 'ちらかします', romaji: 'chirakashimasu', meaning: 'làm bừa bãi, vứt lung tung', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '散らかります', kana: 'ちらかります', romaji: 'chirakarimasu', meaning: 'bừa bộn, lộn xộn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '散らします', kana: 'ちらします', romaji: 'chirashimasu', meaning: 'làm tung tóe, rải ra', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '散ります', kana: 'ちります', romaji: 'chirimasu', meaning: 'rụng, tàn (hoa)', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 737,
    jlptLevel: 'N2',
    words: [
      { kanji: '産地', kana: 'さんち', romaji: 'sanchi', meaning: 'nơi sản xuất', partOfSpeech: 'danh từ' },
      { kanji: '算数', kana: 'さんすう', romaji: 'sansū', meaning: 'môn số học', partOfSpeech: 'danh từ' },
      { kanji: '残らず', kana: 'のこらず', romaji: 'nokorazu', meaning: 'toàn bộ, không sót cái nào', partOfSpeech: 'phó từ' },
      { kanji: '仕上がります', kana: 'しあがります', romaji: 'shiagarimasu', meaning: 'được hoàn thành', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '刺さります', kana: 'ささります', romaji: 'sasarimasu', meaning: 'đâm vào, cắm vào', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '四つ角', kana: 'よつかど', romaji: 'yotsukado', meaning: 'ngã tư', partOfSpeech: 'danh từ' },
      { kanji: '四角い', kana: 'しかくい', romaji: 'shikakui', meaning: 'hình vuông', partOfSpeech: 'tính từ i' },
      { kanji: '四捨五入', kana: 'ししゃごにゅう', romaji: 'shishagonyū', meaning: 'phép làm tròn số', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '始終', kana: 'しじゅう', romaji: 'shijū', meaning: 'từ đầu đến cuối, luôn luôn', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '子孫', kana: 'しそん', romaji: 'shison', meaning: 'con cháu', partOfSpeech: 'danh từ' },
      { kanji: '思い掛けない', kana: 'おもいがけない', romaji: 'omoigakenai', meaning: 'không ngờ tới, bất ngờ', partOfSpeech: 'tính từ i' },
      { kanji: '思い込みます', kana: 'おもいこみます', romaji: 'omoikomimasu', meaning: 'đinh ninh, tin chắc là', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '思い付きます', kana: 'おもいつきます', romaji: 'omoitsukimasu', meaning: 'chợt nghĩ ra', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '指定', kana: 'してい', romaji: 'shitei', meaning: 'sự chỉ định', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '死体', kana: 'したい', romaji: 'shitai', meaning: 'xác chết, thi thể', partOfSpeech: 'danh từ' },
      { kanji: '私鉄', kana: 'してつ', romaji: 'shitetsu', meaning: 'đường sắt tư nhân', partOfSpeech: 'danh từ' },
      { kanji: '私立', kana: 'しりつ', romaji: 'shiritsu', meaning: 'tư lập, dân lập', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 738,
    jlptLevel: 'N2',
    words: [
      { kanji: '紙屑', kana: 'かみくず', romaji: 'kamikuzu', meaning: 'giấy vụn, rác giấy', partOfSpeech: 'danh từ' },
      { kanji: '紙幣', kana: 'しへい', romaji: 'shihei', meaning: 'tiền giấy', partOfSpeech: 'danh từ' },
      { kanji: '歯車', kana: 'はぐるま', romaji: 'haguruma', meaning: 'bánh răng', partOfSpeech: 'danh từ' },
      { kanji: '歯磨き', kana: 'はみがき', romaji: 'hamigaki', meaning: 'kem đánh răng; việc đánh răng', partOfSpeech: 'danh từ' },
      { kanji: '寺院', kana: 'じいん', romaji: 'jiin', meaning: 'chùa, đền', partOfSpeech: 'danh từ' },
      { kanji: '持参', kana: 'じさん', romaji: 'jisan', meaning: 'sự mang theo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '時間割', kana: 'じかんわり', romaji: 'jikanwari', meaning: 'thời khóa biểu', partOfSpeech: 'danh từ' },
      { kanji: '時速', kana: 'じそく', romaji: 'jisoku', meaning: 'tốc độ mỗi giờ', partOfSpeech: 'danh từ' },
      { kanji: '次ぎます', kana: 'つぎます', romaji: 'tsugimasu', meaning: 'đứng sau, kế tiếp', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '磁石', kana: 'じしゃく', romaji: 'jishaku', meaning: 'nam châm', partOfSpeech: 'danh từ' },
      { kanji: '自衛', kana: 'じえい', romaji: 'jiei', meaning: 'sự tự vệ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '自治', kana: 'じち', romaji: 'jichi', meaning: 'sự tự trị', partOfSpeech: 'danh từ' },
      { kanji: '自習', kana: 'じしゅう', romaji: 'jishū', meaning: 'sự tự học', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '自然科学', kana: 'しぜんかがく', romaji: 'shizenkagaku', meaning: 'khoa học tự nhiên', partOfSpeech: 'danh từ' },
      { kanji: '執筆', kana: 'しっぴつ', romaji: 'shippitsu', meaning: 'sự viết văn, chấp bút', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '失恋', kana: 'しつれん', romaji: 'shitsuren', meaning: 'sự thất tình', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '湿気', kana: 'しっけ', romaji: 'shikke', meaning: 'độ ẩm, hơi ẩm', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 739,
    jlptLevel: 'N2',
    words: [
      { kanji: '湿度', kana: 'しつど', romaji: 'shitsudo', meaning: 'độ ẩm không khí', partOfSpeech: 'danh từ' },
      { kanji: '実ります', kana: 'みのります', romaji: 'minorimasu', meaning: 'kết trái, đơm hoa kết quả', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '実感', kana: 'じっかん', romaji: 'jikkan', meaning: 'cảm giác thực sự', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '実習', kana: 'じっしゅう', romaji: 'jisshū', meaning: 'thực tập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '実物', kana: 'じつぶつ', romaji: 'jitsubutsu', meaning: 'vật thật, hàng thật', partOfSpeech: 'danh từ' },
      { kanji: '実力', kana: 'じつりょく', romaji: 'jitsuryoku', meaning: 'thực lực, năng lực thật sự', partOfSpeech: 'danh từ' },
      { kanji: '実例', kana: 'じつれい', romaji: 'jitsurei', meaning: 'ví dụ thực tế', partOfSpeech: 'danh từ' },
      { kanji: '写生', kana: 'しゃせい', romaji: 'shasei', meaning: 'sự vẽ phác họa từ thực tế', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '斜め', kana: 'ななめ', romaji: 'naname', meaning: 'chéo, xiên', partOfSpeech: 'tính từ na' },
      { kanji: '社会科学', kana: 'しゃかいかがく', romaji: 'shakaikagaku', meaning: 'khoa học xã hội', partOfSpeech: 'danh từ' },
      { kanji: '社説', kana: 'しゃせつ', romaji: 'shasetsu', meaning: 'bài xã luận', partOfSpeech: 'danh từ' },
      { kanji: '車庫', kana: 'しゃこ', romaji: 'shako', meaning: 'nhà để xe, ga ra', partOfSpeech: 'danh từ' },
      { kanji: '車掌', kana: 'しゃしょう', romaji: 'shashō', meaning: 'người soát vé tàu', partOfSpeech: 'danh từ' },
      { kanji: '車輪', kana: 'しゃりん', romaji: 'sharin', meaning: 'bánh xe', partOfSpeech: 'danh từ' },
      { kanji: '蛇口', kana: 'じゃぐち', romaji: 'jaguchi', meaning: 'vòi nước', partOfSpeech: 'danh từ' },
      { kanji: '若々しい', kana: 'わかわかしい', romaji: 'wakawakashii', meaning: 'trẻ trung, tươi trẻ', partOfSpeech: 'tính từ i' },
      { kanji: '弱点', kana: 'じゃくてん', romaji: 'jakuten', meaning: 'điểm yếu', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 740,
    jlptLevel: 'N2',
    words: [
      { kanji: '主語', kana: 'しゅご', romaji: 'shugo', meaning: 'chủ ngữ', partOfSpeech: 'danh từ' },
      { kanji: '取り出します', kana: 'とりだします', romaji: 'toridashimasu', meaning: 'lấy ra, rút ra', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '取り消します', kana: 'とりけします', romaji: 'torikeshimasu', meaning: 'hủy bỏ', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '取り入れます', kana: 'とりいれます', romaji: 'toriiremasu', meaning: 'thu hoạch; tiếp thu, áp dụng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '手頃', kana: 'てごろ', romaji: 'tegoro', meaning: 'vừa tầm, vừa phải', partOfSpeech: 'tính từ na' },
      { kanji: '手首', kana: 'てくび', romaji: 'tekubi', meaning: 'cổ tay', partOfSpeech: 'danh từ' },
      { kanji: '手拭い', kana: 'てぬぐい', romaji: 'tenugui', meaning: 'khăn lau tay kiểu Nhật', partOfSpeech: 'danh từ' },
      { kanji: '手洗い', kana: 'てあらい', romaji: 'tearai', meaning: 'nhà vệ sinh; sự rửa tay', partOfSpeech: 'danh từ' },
      { kanji: '手前', kana: 'てまえ', romaji: 'temae', meaning: 'phía trước mặt, bên này', partOfSpeech: 'danh từ' },
      { kanji: '手入れ', kana: 'ていれ', romaji: 'teire', meaning: 'sự bảo dưỡng, chăm sóc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '酒場', kana: 'さかば', romaji: 'sakaba', meaning: 'quán rượu', partOfSpeech: 'danh từ' },
      { kanji: '受け持ちます', kana: 'うけもちます', romaji: 'ukemochimasu', meaning: 'phụ trách, đảm nhận', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '受取', kana: 'うけとり', romaji: 'uketori', meaning: 'biên nhận, hóa đơn', partOfSpeech: 'danh từ' },
      { kanji: '受話器', kana: 'じゅわき', romaji: 'juwaki', meaning: 'ống nghe điện thoại', partOfSpeech: 'danh từ' },
      { kanji: '周辺', kana: 'しゅうへん', romaji: 'shūhen', meaning: 'vùng lân cận, ngoại vi', partOfSpeech: 'danh từ' },
      { kanji: '就任', kana: 'しゅうにん', romaji: 'shūnin', meaning: 'sự nhậm chức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '修繕', kana: 'しゅうぜん', romaji: 'shūzen', meaning: 'sự sửa chữa', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 741,
    jlptLevel: 'N2',
    words: [
      { kanji: '終点', kana: 'しゅうてん', romaji: 'shūten', meaning: 'điểm cuối, ga cuối', partOfSpeech: 'danh từ' },
      { kanji: '終了', kana: 'しゅうりょう', romaji: 'shūryō', meaning: 'sự kết thúc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '蹴ります', kana: 'けります', romaji: 'kerimasu', meaning: 'đá (chân)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '集会', kana: 'しゅうかい', romaji: 'shūkai', meaning: 'cuộc tụ họp', partOfSpeech: 'danh từ' },
      { kanji: '集金', kana: 'しゅうきん', romaji: 'shūkin', meaning: 'sự thu tiền', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '集合', kana: 'しゅうごう', romaji: 'shūgō', meaning: 'sự tập hợp; tập hợp (toán)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '醜い', kana: 'みにくい', romaji: 'minikui', meaning: 'xấu xí', partOfSpeech: 'tính từ i' },
      { kanji: '住まい', kana: 'すまい', romaji: 'sumai', meaning: 'nơi ở, chỗ ở', partOfSpeech: 'danh từ' },
      { kanji: '住居', kana: 'じゅうきょ', romaji: 'jūkyo', meaning: 'nơi cư trú', partOfSpeech: 'danh từ' },
      { kanji: '重たい', kana: 'おもたい', romaji: 'omotai', meaning: 'nặng nề', partOfSpeech: 'tính từ i' },
      { kanji: '重なります', kana: 'かさなります', romaji: 'kasanarimasu', meaning: 'chồng chất, trùng nhau', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '重ねます', kana: 'かさねます', romaji: 'kasanemasu', meaning: 'chồng lên, lặp lại', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '重役', kana: 'じゅうやく', romaji: 'jūyaku', meaning: 'giám đốc điều hành', partOfSpeech: 'danh từ' },
      { kanji: '重量', kana: 'じゅうりょう', romaji: 'jūryō', meaning: 'trọng lượng', partOfSpeech: 'danh từ' },
      { kanji: '重力', kana: 'じゅうりょく', romaji: 'jūryoku', meaning: 'trọng lực', partOfSpeech: 'danh từ' },
    ],
  },
];
