// Bổ sung kanji N2 để ôn thi — tự soạn tay (không auto-scrape).
// KanjiLesson number mới: 410–417.

import type { JlptKanjiLesson } from './jlpt-kanji.data';

export const JLPT_KANJI_BOOST2_N2: JlptKanjiLesson[] = [
  {
    lessonNumber: 410,
    jlptLevel: 'N2',
    title: 'Bài 46 · Kanji N2 bổ sung (1)',
    sortOrder: 4100,
    entries: [
      { character: '拡', hanViet: 'KHUẾCH', onyomi: 'かく', meaningVi: 'mở rộng (拡大)', strokeCount: 8 },
      { character: '縮', hanViet: 'SÚC', onyomi: 'しゅく', kunyomi: 'ちぢ-む, ちぢ-める', meaningVi: 'co lại, thu nhỏ', strokeCount: 17 },
      { character: '伸', hanViet: 'THÂN', onyomi: 'しん', kunyomi: 'の-びる, の-ばす', meaningVi: 'kéo dài, mở rộng', strokeCount: 7 },
      { character: '縦', hanViet: 'TUNG', onyomi: 'じゅう', kunyomi: 'たて', meaningVi: 'chiều dọc', strokeCount: 16 },
      { character: '横', hanViet: 'HOÀNH', onyomi: 'おう', kunyomi: 'よこ', meaningVi: 'chiều ngang, bên cạnh', strokeCount: 15 },
      { character: '幅', hanViet: 'PHÚC', onyomi: 'ふく', kunyomi: 'はば', meaningVi: 'độ rộng, chiều rộng', strokeCount: 12 },
      { character: '奥', hanViet: 'ÁO', onyomi: 'おう', kunyomi: 'おく', meaningVi: 'phía sâu bên trong', strokeCount: 12 },
      { character: '端', hanViet: 'ĐOAN', onyomi: 'たん', kunyomi: 'はし, はた', meaningVi: 'đầu mút, đầu mối', strokeCount: 14 },
      { character: '傾', hanViet: 'KHUYNH', onyomi: 'けい', kunyomi: 'かたむ-く', meaningVi: 'nghiêng, khuynh hướng', strokeCount: 13 },
      { character: '沿', hanViet: 'DUYÊN', onyomi: 'えん', kunyomi: 'そ-う', meaningVi: 'dọc theo', strokeCount: 8 },
      { character: '添', hanViet: 'THIÊM', onyomi: 'てん', kunyomi: 'そ-える', meaningVi: 'đính kèm, thêm vào', strokeCount: 11 },
      { character: '削', hanViet: 'TƯỚC', onyomi: 'さく', kunyomi: 'けず-る', meaningVi: 'cắt gọt, cắt giảm', strokeCount: 9 },
      { character: '刺', hanViet: 'THÍCH', onyomi: 'し', kunyomi: 'さ-す', meaningVi: 'đâm, châm chích', strokeCount: 8 },
      { character: '突', hanViet: 'ĐỘT', onyomi: 'とつ', kunyomi: 'つ-く', meaningVi: 'đột ngột, đâm thọc', strokeCount: 8 },
      { character: '衝', hanViet: 'XUNG', onyomi: 'しょう', meaningVi: 'va chạm, xung đột', strokeCount: 15 },
      { character: '撃', hanViet: 'KÍCH', onyomi: 'げき', kunyomi: 'う-つ', meaningVi: 'tấn công, đánh', strokeCount: 15 },
      { character: '襲', hanViet: 'TẬP', onyomi: 'しゅう', kunyomi: 'おそ-う', meaningVi: 'tập kích, thừa kế', strokeCount: 22 },
      { character: '殴', hanViet: 'ẨU', onyomi: 'おう', kunyomi: 'なぐ-る', meaningVi: 'đánh, đấm', strokeCount: 8 },
      { character: '暴', hanViet: 'BẠO', onyomi: 'ぼう, ばく', kunyomi: 'あば-れる', meaningVi: 'bạo lực, hung bạo', strokeCount: 15 },
      { character: '威', hanViet: 'UY', onyomi: 'い', meaningVi: 'uy quyền, uy hiếp', strokeCount: 9 },
    ],
  },
  {
    lessonNumber: 411,
    jlptLevel: 'N2',
    title: 'Bài 47 · Kanji N2 bổ sung (2)',
    sortOrder: 4110,
    entries: [
      { character: '滑', hanViet: 'HOẠT', onyomi: 'かつ', kunyomi: 'すべ-る', meaningVi: 'trơn trượt', strokeCount: 13 },
      { character: '転', hanViet: 'CHUYỂN', onyomi: 'てん', kunyomi: 'ころ-がる, ころ-ぶ', meaningVi: 'xoay chuyển, lăn', strokeCount: 11 },
      { character: '揺', hanViet: 'DIÊU', onyomi: 'よう', kunyomi: 'ゆ-れる, ゆ-らす', meaningVi: 'lắc lư, rung động', strokeCount: 12 },
      { character: '震', hanViet: 'CHẤN', onyomi: 'しん', kunyomi: 'ふる-える', meaningVi: 'rung chấn, run rẩy', strokeCount: 15 },
      { character: '跳', hanViet: 'KHIÊU', onyomi: 'ちょう', kunyomi: 'は-ねる, と-ぶ', meaningVi: 'nhảy, bật lên', strokeCount: 13 },
      { character: '躍', hanViet: 'DƯỢC', onyomi: 'やく', kunyomi: 'おど-る', meaningVi: 'nhảy vọt, hoạt động sôi nổi', strokeCount: 21 },
      { character: '潜', hanViet: 'TIỀM', onyomi: 'せん', kunyomi: 'ひそ-む, もぐ-る', meaningVi: 'tiềm ẩn, lặn', strokeCount: 15 },
      { character: '隠', hanViet: 'ẨN', onyomi: 'いん', kunyomi: 'かく-す, かく-れる', meaningVi: 'ẩn giấu', strokeCount: 14 },
      { character: '秘', hanViet: 'BÍ', onyomi: 'ひ', kunyomi: 'ひ-める', meaningVi: 'bí mật', strokeCount: 10 },
      { character: '漏', hanViet: 'LẬU', onyomi: 'ろう', kunyomi: 'も-れる, も-らす', meaningVi: 'rò rỉ', strokeCount: 14 },
      { character: '洩', hanViet: 'DUỆ', onyomi: 'えい', kunyomi: 'も-れる', meaningVi: 'rò rỉ (漏洩)', strokeCount: 9 },
      { character: '妨', hanViet: 'PHƯƠNG', onyomi: 'ぼう', kunyomi: 'さまた-げる', meaningVi: 'cản trở', strokeCount: 7 },
      { character: '阻', hanViet: 'TRỞ', onyomi: 'そ', kunyomi: 'はば-む', meaningVi: 'ngăn trở', strokeCount: 8 },
      { character: '遮', hanViet: 'GIÀ', onyomi: 'しゃ', kunyomi: 'さえぎ-る', meaningVi: 'che chắn, ngăn cản', strokeCount: 14 },
      { character: '塞', hanViet: 'TẮC', onyomi: 'そく, さい', kunyomi: 'ふさ-ぐ', meaningVi: 'lấp kín, tắc nghẽn', strokeCount: 13 },
      { character: '詰', hanViet: 'CẬT', onyomi: 'きつ', kunyomi: 'つ-める, つ-まる', meaningVi: 'nhồi nhét, chất vấn', strokeCount: 13 },
      { character: '挟', hanViet: 'HIỆP', onyomi: 'きょう', kunyomi: 'はさ-む', meaningVi: 'kẹp giữa', strokeCount: 9 },
      { character: '挿', hanViet: 'SÁP', onyomi: 'そう', kunyomi: 'さ-す', meaningVi: 'cắm vào, chèn vào', strokeCount: 10 },
      { character: '掃', hanViet: 'TÁO', onyomi: 'そう', kunyomi: 'は-く', meaningVi: 'quét dọn', strokeCount: 11 },
    ],
  },
  {
    lessonNumber: 412,
    jlptLevel: 'N2',
    title: 'Bài 48 · Kanji N2 bổ sung (3)',
    sortOrder: 4120,
    entries: [
      { character: '雇', hanViet: 'CỐ', onyomi: 'こ', kunyomi: 'やと-う', meaningVi: 'thuê, tuyển dụng', strokeCount: 12 },
      { character: '辞', hanViet: 'TỪ', onyomi: 'じ', kunyomi: 'や-める', meaningVi: 'từ chức, lời nói', strokeCount: 13 },
      { character: '辱', hanViet: 'NHỤC', onyomi: 'じょく', kunyomi: 'はずかし-める', meaningVi: 'sỉ nhục', strokeCount: 10 },
      { character: '誉', hanViet: 'DỰ', onyomi: 'よ', kunyomi: 'ほま-れ', meaningVi: 'danh dự, tiếng thơm', strokeCount: 13 },
      { character: '栄', hanViet: 'VINH', onyomi: 'えい', kunyomi: 'さか-える', meaningVi: 'vinh quang, phồn vinh', strokeCount: 9 },
      { character: '盛', hanViet: 'THỊNH', onyomi: 'せい, じょう', kunyomi: 'も-る, さか-ん', meaningVi: 'thịnh vượng, đầy ắp', strokeCount: 11 },
      { character: '衰', hanViet: 'SUY', onyomi: 'すい', kunyomi: 'おとろ-える', meaningVi: 'suy yếu', strokeCount: 10 },
      { character: '滅', hanViet: 'DIỆT', onyomi: 'めつ', kunyomi: 'ほろ-びる, ほろ-ぼす', meaningVi: 'diệt vong', strokeCount: 13 },
      { character: '崩', hanViet: 'BĂNG', onyomi: 'ほう', kunyomi: 'くず-れる, くず-す', meaningVi: 'sụp đổ', strokeCount: 11 },
      { character: '壊', hanViet: 'HOẠI', onyomi: 'かい', kunyomi: 'こわ-す, こわ-れる', meaningVi: 'phá hủy, hư hỏng', strokeCount: 16 },
      { character: '損', hanViet: 'TỔN', onyomi: 'そん', kunyomi: 'そこ-なう', meaningVi: 'tổn thất, hư hại', strokeCount: 13 },
      { character: '賠', hanViet: 'BỒI', onyomi: 'ばい', meaningVi: 'bồi thường', strokeCount: 15 },
      { character: '償', hanViet: 'THƯỜNG', onyomi: 'しょう', kunyomi: 'つぐな-う', meaningVi: 'đền bù, bồi thường', strokeCount: 17 },
      { character: '弁', hanViet: 'BIỆN', onyomi: 'べん', meaningVi: 'biện luận, van (kỹ thuật)', strokeCount: 5 },
      { character: '護', hanViet: 'HỘ', onyomi: 'ご', meaningVi: 'bảo hộ, che chở', strokeCount: 20 },
      { character: '擁', hanViet: 'ỦNG', onyomi: 'よう', meaningVi: 'ủng hộ, ôm giữ', strokeCount: 16 },
      { character: '拘', hanViet: 'CÂU', onyomi: 'こう', meaningVi: 'câu thúc, bắt giữ', strokeCount: 8 },
      { character: '束', hanViet: 'THÚC', onyomi: 'そく', kunyomi: 'たば', meaningVi: 'buộc lại, bó', strokeCount: 7 },
      { character: '縛', hanViet: 'PHƯỢC', onyomi: 'ばく', kunyomi: 'しば-る', meaningVi: 'trói buộc', strokeCount: 16 },
      { character: '拒', hanViet: 'CỰ', onyomi: 'きょ', kunyomi: 'こば-む', meaningVi: 'từ chối, cự tuyệt', strokeCount: 8 },
    ],
  },
  {
    lessonNumber: 413,
    jlptLevel: 'N2',
    title: 'Bài 49 · Kanji N2 bổ sung (4)',
    sortOrder: 4130,
    entries: [
      { character: '慶', hanViet: 'KHÁNH', onyomi: 'けい', meaningVi: 'khánh chúc, vui mừng', strokeCount: 15 },
      { character: '弔', hanViet: 'ĐIẾU', onyomi: 'ちょう', kunyomi: 'とむら-う', meaningVi: 'viếng tang, chia buồn', strokeCount: 4 },
      { character: '喪', hanViet: 'TANG', onyomi: 'そう', kunyomi: 'も', meaningVi: 'tang lễ, để tang', strokeCount: 12 },
      { character: '墓', hanViet: 'MỘ', onyomi: 'ぼ', kunyomi: 'はか', meaningVi: 'mộ phần', strokeCount: 13 },
      { character: '埋', hanViet: 'MAI', onyomi: 'まい', kunyomi: 'う-める, う-まる', meaningVi: 'chôn, lấp', strokeCount: 10 },
      { character: '棺', hanViet: 'QUAN', onyomi: 'かん', meaningVi: 'quan tài', strokeCount: 12 },
      { character: '葬', hanViet: 'TÁNG', onyomi: 'そう', kunyomi: 'ほうむ-る', meaningVi: 'mai táng', strokeCount: 12 },
      { character: '祖', hanViet: 'TỔ', onyomi: 'そ', meaningVi: 'tổ tiên', strokeCount: 9 },
      { character: '孫', hanViet: 'TÔN', onyomi: 'そん', kunyomi: 'まご', meaningVi: 'cháu (nội/ngoại)', strokeCount: 10 },
      { character: '甥', hanViet: 'SANH', onyomi: 'せい', kunyomi: 'おい', meaningVi: 'cháu trai (gọi bằng cô/dì/chú/bác)', strokeCount: 12 },
      { character: '姪', hanViet: 'CHẤT', onyomi: 'てつ', kunyomi: 'めい', meaningVi: 'cháu gái (gọi bằng cô/dì/chú/bác)', strokeCount: 9 },
      { character: '嫁', hanViet: 'GIÁ', onyomi: 'か', kunyomi: 'よめ, とつ-ぐ', meaningVi: 'con dâu, đi lấy chồng', strokeCount: 13 },
      { character: '婿', hanViet: 'TÊ', onyomi: 'せい', kunyomi: 'むこ', meaningVi: 'con rể', strokeCount: 12 },
      { character: '姑', hanViet: 'CÔ', onyomi: 'こ', kunyomi: 'しゅうとめ', meaningVi: 'mẹ chồng', strokeCount: 8 },
      { character: '養', hanViet: 'DƯỠNG', onyomi: 'よう', kunyomi: 'やしな-う', meaningVi: 'nuôi dưỡng', strokeCount: 15 },
      { character: '扶', hanViet: 'PHÙ', onyomi: 'ふ', meaningVi: 'giúp đỡ, phù trợ', strokeCount: 7 },
      { character: '援', hanViet: 'VIỆN', onyomi: 'えん', meaningVi: 'chi viện, viện trợ', strokeCount: 12 },
      { character: '救', hanViet: 'CỨU', onyomi: 'きゅう', kunyomi: 'すく-う', meaningVi: 'cứu giúp', strokeCount: 11 },
      { character: '助', hanViet: 'TRỢ', onyomi: 'じょ', kunyomi: 'たす-ける', meaningVi: 'giúp đỡ, trợ giúp', strokeCount: 7 },
    ],
  },
  {
    lessonNumber: 414,
    jlptLevel: 'N2',
    title: 'Bài 50 · Kanji N2 bổ sung (5)',
    sortOrder: 4140,
    entries: [
      { character: '巡', hanViet: 'TUẦN', onyomi: 'じゅん', kunyomi: 'めぐ-る', meaningVi: 'tuần tra, đi vòng quanh', strokeCount: 6 },
      { character: '巻', hanViet: 'QUYỂN', onyomi: 'かん', kunyomi: 'ま-く, まき', meaningVi: 'cuộn lại; tập (sách)', strokeCount: 9 },
      { character: '該', hanViet: 'CAI', onyomi: 'がい', meaningVi: 'thuộc diện, tương ứng', strokeCount: 13 },
      { character: '搬', hanViet: 'BAN', onyomi: 'はん', meaningVi: 'vận chuyển (搬送)', strokeCount: 13 },
      { character: '搭', hanViet: 'THÁP', onyomi: 'とう', meaningVi: 'lên (tàu, xe) - 搭乗', strokeCount: 12 },
      { character: '乗', hanViet: 'THỪA', onyomi: 'じょう', kunyomi: 'の-る, の-せる', meaningVi: 'lên (xe, tàu)', strokeCount: 9 },
      { character: '越', hanViet: 'VIỆT', onyomi: 'えつ', kunyomi: 'こ-える, こ-す', meaningVi: 'vượt qua', strokeCount: 12 },
      { character: '超', hanViet: 'SIÊU', onyomi: 'ちょう', kunyomi: 'こ-える, こ-す', meaningVi: 'vượt trội, siêu việt', strokeCount: 12 },
      { character: '破', hanViet: 'PHÁ', onyomi: 'は', kunyomi: 'やぶ-る, やぶ-れる', meaningVi: 'phá vỡ', strokeCount: 10 },
      { character: '裂', hanViet: 'LIỆT', onyomi: 'れつ', kunyomi: 'さ-く, さ-ける', meaningVi: 'xé rách, nứt vỡ', strokeCount: 12 },
      { character: '砕', hanViet: 'TOÁI', onyomi: 'さい', kunyomi: 'くだ-く, くだ-ける', meaningVi: 'đập vỡ, nghiền nát', strokeCount: 9 },
      { character: '粉', hanViet: 'PHẤN', onyomi: 'ふん', kunyomi: 'こな, こ', meaningVi: 'bột, phấn', strokeCount: 10 },
      { character: '末', hanViet: 'MẠT', onyomi: 'まつ, ばつ', kunyomi: 'すえ', meaningVi: 'cuối, ngọn', strokeCount: 5 },
      { character: '殻', hanViet: 'XÁC', onyomi: 'かく', kunyomi: 'から', meaningVi: 'vỏ (trứng, ốc...)', strokeCount: 11 },
      { character: '殼', hanViet: 'XÁC', onyomi: 'かく', kunyomi: 'から', meaningVi: 'vỏ (dạng chữ phồn thể của 殻)', strokeCount: 12 },
      { character: '殿', hanViet: 'ĐIỆN', onyomi: 'でん', kunyomi: 'との, どの', meaningVi: 'điện thờ; ngài (kính ngữ)', strokeCount: 13 },
      { character: '塔', hanViet: 'THÁP', onyomi: 'とう', meaningVi: 'ngọn tháp', strokeCount: 12 },
    ],
  },
  {
    lessonNumber: 415,
    jlptLevel: 'N2',
    title: 'Bài 51 · Kanji N2 bổ sung (6)',
    sortOrder: 4150,
    entries: [
      { character: '獲', hanViet: 'HOẠCH', onyomi: 'かく', kunyomi: 'え-る', meaningVi: 'thu được, bắt được', strokeCount: 16 },
      { character: '狩', hanViet: 'THÚ', onyomi: 'しゅ', kunyomi: 'か-る', meaningVi: 'săn bắn', strokeCount: 9 },
      { character: '猟', hanViet: 'LIỆP', onyomi: 'りょう', meaningVi: 'săn bắt (狩猟)', strokeCount: 11 },
      { character: '漁', hanViet: 'NGƯ', onyomi: 'ぎょ, りょう', meaningVi: 'đánh cá, ngư nghiệp', strokeCount: 14 },
      { character: '耕', hanViet: 'CANH', onyomi: 'こう', kunyomi: 'たがや-す', meaningVi: 'cày cấy', strokeCount: 10 },
      { character: '栽', hanViet: 'TÀI', onyomi: 'さい', meaningVi: 'trồng trọt (栽培)', strokeCount: 10 },
      { character: '培', hanViet: 'BỒI', onyomi: 'ばい', kunyomi: 'つちか-う', meaningVi: 'bồi dưỡng, ươm trồng', strokeCount: 11 },
      { character: '摘', hanViet: 'TRÍCH', onyomi: 'てき', kunyomi: 'つ-む', meaningVi: 'hái, trích dẫn', strokeCount: 14 },
      { character: '穫', hanViet: 'HOẠCH', onyomi: 'かく', meaningVi: 'thu hoạch (収穫)', strokeCount: 18 },
      { character: '蓄', hanViet: 'SÚC', onyomi: 'ちく', kunyomi: 'たくわ-える', meaningVi: 'tích lũy, dự trữ', strokeCount: 13 },
      { character: '肥', hanViet: 'PHÌ', onyomi: 'ひ', kunyomi: 'こ-える, こや-す', meaningVi: 'béo tốt, phân bón', strokeCount: 8 },
      { character: '飽', hanViet: 'BÃO', onyomi: 'ほう', kunyomi: 'あ-きる', meaningVi: 'no đủ, chán ngấy', strokeCount: 13 },
      { character: '腐', hanViet: 'HỦ', onyomi: 'ふ', kunyomi: 'くさ-る, くさ-らす', meaningVi: 'thối rữa', strokeCount: 14 },
      { character: '臭', hanViet: 'XÚ', onyomi: 'しゅう', kunyomi: 'くさ-い, にお-う', meaningVi: 'mùi hôi', strokeCount: 9 },
      { character: '汚', hanViet: 'Ô', onyomi: 'お', kunyomi: 'きたな-い, よご-す', meaningVi: 'dơ bẩn, ô nhiễm', strokeCount: 6 },
      { character: '濃', hanViet: 'NỒNG', onyomi: 'のう', kunyomi: 'こ-い', meaningVi: 'đậm đặc', strokeCount: 16 },
      { character: '淡', hanViet: 'ĐẠM', onyomi: 'たん', kunyomi: 'あわ-い', meaningVi: 'nhạt, thanh đạm', strokeCount: 11 },
      { character: '澄', hanViet: 'TRỪNG', onyomi: 'ちょう', kunyomi: 'す-む, す-ます', meaningVi: 'trong veo, trong trẻo', strokeCount: 15 },
    ],
  },
  {
    lessonNumber: 416,
    jlptLevel: 'N2',
    title: 'Bài 52 · Kanji N2 bổ sung (7)',
    sortOrder: 4160,
    entries: [
      { character: '励', hanViet: 'LỆ', onyomi: 'れい', kunyomi: 'はげ-む, はげ-ます', meaningVi: 'nỗ lực, khích lệ', strokeCount: 7 },
      { character: '奮', hanViet: 'PHẤN', onyomi: 'ふん', kunyomi: 'ふる-う', meaningVi: 'phấn chấn, hăng hái', strokeCount: 16 },
      { character: '闘', hanViet: 'ĐẤU', onyomi: 'とう', kunyomi: 'たたか-う', meaningVi: 'chiến đấu', strokeCount: 18 },
      { character: '争', hanViet: 'TRANH', onyomi: 'そう', kunyomi: 'あらそ-う', meaningVi: 'tranh giành, tranh chấp', strokeCount: 6 },
      { character: '競', hanViet: 'CẠNH', onyomi: 'きょう, けい', kunyomi: 'きそ-う, せ-る', meaningVi: 'cạnh tranh, thi đấu', strokeCount: 20 },
      { character: '駆', hanViet: 'KHU', onyomi: 'く', kunyomi: 'か-ける, か-る', meaningVi: 'phi nhanh, xua đuổi', strokeCount: 14 },
      { character: '追', hanViet: 'TRUY', onyomi: 'つい', kunyomi: 'お-う', meaningVi: 'truy đuổi', strokeCount: 9 },
      { character: '逃', hanViet: 'ĐÀO', onyomi: 'とう', kunyomi: 'に-げる, のが-す', meaningVi: 'chạy trốn, bỏ lỡ', strokeCount: 9 },
      { character: '匿', hanViet: 'NẶC', onyomi: 'とく', kunyomi: 'かくま-う', meaningVi: 'ẩn nấp, che giấu (匿名)', strokeCount: 10 },
      { character: '偽', hanViet: 'NGỤY', onyomi: 'ぎ', kunyomi: 'にせ, いつわ-る', meaningVi: 'giả dối, ngụy tạo', strokeCount: 11 },
      { character: '詐', hanViet: 'TRÁ', onyomi: 'さ', meaningVi: 'lừa dối (詐欺)', strokeCount: 12 },
      { character: '欺', hanViet: 'KHI', onyomi: 'ぎ', kunyomi: 'あざむ-く', meaningVi: 'lừa gạt', strokeCount: 12 },
      { character: '盗', hanViet: 'ĐẠO', onyomi: 'とう', kunyomi: 'ぬす-む', meaningVi: 'trộm cắp', strokeCount: 11 },
      { character: '奪', hanViet: 'ĐOẠT', onyomi: 'だつ', kunyomi: 'うば-う', meaningVi: 'đoạt lấy, cướp đoạt', strokeCount: 14 },
      { character: '脅', hanViet: 'HIẾP', onyomi: 'きょう', kunyomi: 'おど-す, おびや-かす', meaningVi: 'uy hiếp, đe dọa', strokeCount: 10 },
      { character: '恐', hanViet: 'KHỦNG', onyomi: 'きょう', kunyomi: 'おそ-れる, おそ-ろしい', meaningVi: 'sợ hãi', strokeCount: 10 },
      { character: '怖', hanViet: 'BỐ', onyomi: 'ふ', kunyomi: 'こわ-い', meaningVi: 'sợ hãi (怖い)', strokeCount: 8 },
      { character: '悩', hanViet: 'NÃO', onyomi: 'のう', kunyomi: 'なや-む, なや-ます', meaningVi: 'phiền não, lo lắng', strokeCount: 10 },
      { character: '悔', hanViet: 'HỐI', onyomi: 'かい', kunyomi: 'く-いる, くや-しい', meaningVi: 'hối hận, tiếc nuối', strokeCount: 9 },
    ],
  },
  {
    lessonNumber: 417,
    jlptLevel: 'N2',
    title: 'Bài 53 · Kanji N2 bổ sung (8)',
    sortOrder: 4170,
    entries: [
      { character: '徹', hanViet: 'TRIỆT', onyomi: 'てつ', meaningVi: 'triệt để, xuyên suốt', strokeCount: 15 },
      { character: '貫', hanViet: 'QUÁN', onyomi: 'かん', kunyomi: 'つらぬ-く', meaningVi: 'xuyên suốt, quán triệt', strokeCount: 11 },
      { character: '透', hanViet: 'THẤU', onyomi: 'とう', kunyomi: 'す-く, す-かす', meaningVi: 'trong suốt, thấu suốt', strokeCount: 10 },
      { character: '純', hanViet: 'THUẦN', onyomi: 'じゅん', meaningVi: 'thuần khiết, đơn thuần', strokeCount: 10 },
      { character: '粋', hanViet: 'TÚY', onyomi: 'すい', kunyomi: 'いき', meaningVi: 'tinh túy, sành điệu', strokeCount: 10 },
      { character: '磨', hanViet: 'MA', onyomi: 'ま', kunyomi: 'みが-く', meaningVi: 'mài giũa, đánh bóng', strokeCount: 16 },
      { character: '鍛', hanViet: 'ĐOÀN', onyomi: 'たん', kunyomi: 'きた-える', meaningVi: 'rèn luyện', strokeCount: 17 },
      { character: '錬', hanViet: 'LUYỆN', onyomi: 'れん', meaningVi: 'tôi luyện (鍛錬)', strokeCount: 16 },
      { character: '鋭', hanViet: 'DUỆ', onyomi: 'えい', kunyomi: 'するど-い', meaningVi: 'sắc bén, nhạy bén', strokeCount: 15 },
      { character: '鈍', hanViet: 'ĐỘN', onyomi: 'どん', kunyomi: 'にぶ-い', meaningVi: 'cùn, chậm chạp', strokeCount: 12 },
      { character: '繊', hanViet: 'TIÊM', onyomi: 'せん', meaningVi: 'sợi nhỏ, tinh vi (繊細)', strokeCount: 17 },
      { character: '繋', hanViet: 'HỆ', onyomi: 'けい', kunyomi: 'つな-ぐ', meaningVi: 'kết nối, ràng buộc', strokeCount: 19 },
      { character: '絡', hanViet: 'LẠC', onyomi: 'らく', kunyomi: 'から-む', meaningVi: 'liên lạc, quấn vào', strokeCount: 12 },
      { character: '網', hanViet: 'VÕNG', onyomi: 'もう', kunyomi: 'あみ', meaningVi: 'mạng lưới', strokeCount: 14 },
      { character: '糧', hanViet: 'LƯƠNG', onyomi: 'りょう', kunyomi: 'かて', meaningVi: 'lương thực', strokeCount: 18 },
      { character: '飢', hanViet: 'CƠ', onyomi: 'き', kunyomi: 'う-える', meaningVi: 'đói khát', strokeCount: 10 },
    ],
  },
];
