// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 995-1000.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART17: JlptVocabUnit[] = [
  {
    lessonNumber: 995,
    jlptLevel: 'N1',
    words: [
      { kanji: '張り紙', kana: 'はりがみ', romaji: 'harigami', meaning: 'giấy dán thông báo', partOfSpeech: 'danh từ' },
      { kanji: '挑みます', kana: 'いどみます', romaji: 'idomimasu', meaning: 'thách thức, khiêu chiến', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '挑戦', kana: 'ちょうせん', romaji: 'chōsen', meaning: 'sự thử thách, thách thức', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '朝寝坊', kana: 'あさねぼう', romaji: 'asanebō', meaning: 'sự ngủ nướng buổi sáng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '潮', kana: 'うしお', romaji: 'ushio', meaning: 'thủy triều', partOfSpeech: 'danh từ' },
      { kanji: '聴覚', kana: 'ちょうかく', romaji: 'chōkaku', meaning: 'thính giác', partOfSpeech: 'danh từ' },
      { kanji: '聴診器', kana: 'ちょうしんき', romaji: 'chōshinki', meaning: 'ống nghe (bác sĩ)', partOfSpeech: 'danh từ' },
      { kanji: '調印', kana: 'ちょういん', romaji: 'chōin', meaning: 'sự ký kết', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '調理', kana: 'ちょうり', romaji: 'chōri', meaning: 'sự nấu nướng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '長', kana: 'おさ', romaji: 'osa', meaning: 'người đứng đầu, tộc trưởng', partOfSpeech: 'danh từ' },
      { kanji: '長々', kana: 'ながなが', romaji: 'naganaga', meaning: 'dài dòng, kéo dài', partOfSpeech: 'phó từ' },
      { kanji: '長官', kana: 'ちょうかん', romaji: 'chōkan', meaning: 'trưởng ban, cục trưởng', partOfSpeech: 'danh từ' },
      { kanji: '長閑', kana: 'のどか', romaji: 'nodoka', meaning: 'yên bình, thanh thản', partOfSpeech: 'tính từ na' },
      { kanji: '長編', kana: 'ちょうへん', romaji: 'chōhen', meaning: 'tác phẩm dài kỳ (tiểu thuyết, phim)', partOfSpeech: 'danh từ' },
      { kanji: '頂', kana: 'いただき', romaji: 'itadaki', meaning: 'đỉnh (núi, đầu)', partOfSpeech: 'danh từ' },
      { kanji: '鳥居', kana: 'とりい', romaji: 'torii', meaning: 'cổng torii (đền thờ Thần đạo)', partOfSpeech: 'danh từ' },
      { kanji: '捗ります', kana: 'はかどります', romaji: 'hakadorimasu', meaning: 'tiến triển thuận lợi', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 996,
    jlptLevel: 'N1',
    words: [
      { kanji: '直面', kana: 'ちょくめん', romaji: 'chokumen', meaning: 'sự đối mặt trực tiếp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '沈めます', kana: 'しずめます', romaji: 'shizumemasu', meaning: 'làm chìm xuống', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '沈殿', kana: 'ちんでん', romaji: 'chinden', meaning: 'sự lắng đọng, kết tủa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '沈没', kana: 'ちんぼつ', romaji: 'chinbotsu', meaning: 'sự chìm đắm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '沈黙', kana: 'ちんもく', romaji: 'chinmoku', meaning: 'sự im lặng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '陳列', kana: 'ちんれつ', romaji: 'chinretsu', meaning: 'sự trưng bày', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '墜落', kana: 'ついらく', romaji: 'tsuiraku', meaning: 'sự rơi, rớt (máy bay)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '追い込みます', kana: 'おいこみます', romaji: 'oikomimasu', meaning: 'dồn vào, lùa vào; đẩy đến cùng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '追い出します', kana: 'おいだします', romaji: 'oidashimasu', meaning: 'đuổi ra, tống ra', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '追及', kana: 'ついきゅう', romaji: 'tsuikyū', meaning: 'sự truy cứu, truy hỏi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '追跡', kana: 'ついせき', romaji: 'tsuiseki', meaning: 'sự truy đuổi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '追放', kana: 'ついほう', romaji: 'tsuihō', meaning: 'sự trục xuất, lưu đày', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '痛みます', kana: 'いたみます', romaji: 'itamimasu', meaning: 'bị đau, đau nhức', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '痛めます', kana: 'いためます', romaji: 'itamemasu', meaning: 'làm đau, làm tổn thương', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '痛感', kana: 'つうかん', romaji: 'tsūkan', meaning: 'sự cảm nhận sâu sắc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '痛切', kana: 'つうせつ', romaji: 'tsūsetsu', meaning: 'thấm thía, sâu sắc', partOfSpeech: 'tính từ na' },
      { kanji: '通', kana: 'つう', romaji: 'tsū', meaning: 'người am hiểu, sành sỏi', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 997,
    jlptLevel: 'N1',
    words: [
      { kanji: '通りかかります', kana: 'とおりかかります', romaji: 'tōrikakarimasu', meaning: 'tình cờ đi ngang qua', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '通常', kana: 'つうじょう', romaji: 'tsūjō', meaning: 'thông thường', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '辻褄', kana: 'つじつま', romaji: 'tsujitsuma', meaning: 'sự nhất quán, hợp lý (câu chuyện)', partOfSpeech: 'danh từ' },
      { kanji: '壷', kana: 'つぼ', romaji: 'tsubo', meaning: 'cái lọ, cái bình', partOfSpeech: 'danh từ' },
      { kanji: '吊り革', kana: 'つりかわ', romaji: 'tsurikawa', meaning: 'quai đeo (trên tàu xe)', partOfSpeech: 'danh từ' },
      { kanji: '吊るします', kana: 'つるします', romaji: 'tsurushimasu', meaning: 'treo lên', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '釣鐘', kana: 'つりがね', romaji: 'tsurigane', meaning: 'chuông lớn treo (chùa)', partOfSpeech: 'danh từ' },
      { kanji: '堤防', kana: 'ていぼう', romaji: 'teibō', meaning: 'đê điều', partOfSpeech: 'danh từ' },
      { kanji: '定まります', kana: 'さだまります', romaji: 'sadamarimasu', meaning: 'được quyết định, ổn định', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '定めます', kana: 'さだめます', romaji: 'sadamemasu', meaning: 'quy định, xác lập', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '定義', kana: 'ていぎ', romaji: 'teigi', meaning: 'định nghĩa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '定年', kana: 'ていねん', romaji: 'teinen', meaning: 'tuổi nghỉ hưu', partOfSpeech: 'danh từ' },
      { kanji: '提供', kana: 'ていきょう', romaji: 'teikyō', meaning: 'sự cung cấp, tài trợ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '提示', kana: 'ていじ', romaji: 'teiji', meaning: 'sự trình bày, đưa ra', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '梯子', kana: 'はしご', romaji: 'hashigo', meaning: 'cái thang', partOfSpeech: 'danh từ' },
      { kanji: '訂正', kana: 'ていせい', romaji: 'teisei', meaning: 'sự đính chính, sửa chữa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '諦め', kana: 'あきらめ', romaji: 'akirame', meaning: 'sự từ bỏ, cam chịu', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 998,
    jlptLevel: 'N1',
    words: [
      { kanji: '邸宅', kana: 'ていたく', romaji: 'teitaku', meaning: 'dinh thự', partOfSpeech: 'danh từ' },
      { kanji: '摘みます', kana: 'つまみます', romaji: 'tsumamimasu', meaning: 'nhón, kẹp (bằng ngón tay)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '敵', kana: 'かたき', romaji: 'kataki', meaning: 'kẻ thù, đối thủ (cách nói khác)', partOfSpeech: 'danh từ' },
      { kanji: '適応', kana: 'てきおう', romaji: 'tekiō', meaning: 'sự thích ứng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '適宜', kana: 'てきぎ', romaji: 'tekigi', meaning: 'thích hợp, tùy nghi', partOfSpeech: 'tính từ na, phó từ' },
      { kanji: '適性', kana: 'てきせい', romaji: 'tekisei', meaning: 'sự phù hợp năng khiếu', partOfSpeech: 'danh từ' },
      { kanji: '鉄鋼', kana: 'てっこう', romaji: 'tekkō', meaning: 'sắt thép', partOfSpeech: 'danh từ' },
      { kanji: '鉄棒', kana: 'かなぼう', romaji: 'kanabō', meaning: 'thanh sắt, xà đơn', partOfSpeech: 'danh từ' },
      { kanji: '填まります', kana: 'はまります', romaji: 'hamarimasu', meaning: 'vừa khít, lọt vào; mê mẩn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '天', kana: 'あまつ', romaji: 'amatsu', meaning: 'thuộc về trời, thuộc hoàng gia (tiền tố cổ)', partOfSpeech: 'hậu tố' },
      { kanji: '天国', kana: 'てんごく', romaji: 'tengoku', meaning: 'thiên đường', partOfSpeech: 'danh từ' },
      { kanji: '天体', kana: 'てんたい', romaji: 'tentai', meaning: 'thiên thể', partOfSpeech: 'danh từ' },
      { kanji: '天地', kana: 'あめつち', romaji: 'ametsuchi', meaning: 'trời đất, vũ trụ', partOfSpeech: 'danh từ' },
      { kanji: '展示', kana: 'てんじ', romaji: 'tenji', meaning: 'sự trưng bày', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '展望', kana: 'てんぼう', romaji: 'tenbō', meaning: 'tầm nhìn, triển vọng', partOfSpeech: 'danh từ' },
      { kanji: '添えます', kana: 'そえます', romaji: 'soemasu', meaning: 'đính kèm, thêm vào', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '纏まり', kana: 'まとまり', romaji: 'matomari', meaning: 'sự thống nhất, gọn gàng', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 999,
    jlptLevel: 'N1',
    words: [
      { kanji: '纏め', kana: 'まとめ', romaji: 'matome', meaning: 'bản tổng kết', partOfSpeech: 'danh từ' },
      { kanji: '転じます', kana: 'てんじます', romaji: 'tenjimasu', meaning: 'chuyển hướng, biến đổi', partOfSpeech: 'động từ する' },
      { kanji: '転回', kana: 'てんかい', romaji: 'tenkai', meaning: 'sự xoay chuyển', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '転居', kana: 'てんきょ', romaji: 'tenkyo', meaning: 'sự chuyển nhà', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '転転', kana: 'てんてん', romaji: 'tenten', meaning: 'lăn qua lăn lại; di chuyển nhiều nơi', partOfSpeech: 'phó từ, động từ する' },
      { kanji: '転任', kana: 'てんにん', romaji: 'tennin', meaning: 'sự chuyển công tác', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '点火', kana: 'てんか', romaji: 'tenka', meaning: 'sự đốt cháy, châm lửa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '点線', kana: 'てんせん', romaji: 'tensen', meaning: 'đường chấm chấm', partOfSpeech: 'danh từ' },
      { kanji: '伝説', kana: 'でんせつ', romaji: 'densetsu', meaning: 'truyền thuyết', partOfSpeech: 'danh từ' },
      { kanji: '伝達', kana: 'でんたつ', romaji: 'dentatsu', meaning: 'sự truyền đạt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '伝来', kana: 'でんらい', romaji: 'denrai', meaning: 'được truyền lại, du nhập từ xưa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '殿', kana: 'しんがり', romaji: 'shingari', meaning: 'hậu quân, người đi cuối', partOfSpeech: 'danh từ' },
      { kanji: '殿様', kana: 'とのさま', romaji: 'tonosama', meaning: 'lãnh chúa phong kiến', partOfSpeech: 'danh từ' },
      { kanji: '田園', kana: 'でんえん', romaji: 'denen', meaning: 'đồng quê, thôn dã', partOfSpeech: 'danh từ' },
      { kanji: '電線', kana: 'でんせん', romaji: 'densen', meaning: 'dây điện', partOfSpeech: 'danh từ' },
      { kanji: '兎角', kana: 'とかく', romaji: 'tokaku', meaning: 'dù sao thì, hay là (thường xuyên xảy ra)', partOfSpeech: 'phó từ' },
      { kanji: '妬みます', kana: 'ねたみます', romaji: 'netamimasu', meaning: 'ghen tị, đố kỵ', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 1000,
    jlptLevel: 'N1',
    words: [
      { kanji: '徒歩', kana: 'とほ', romaji: 'toho', meaning: 'đi bộ', partOfSpeech: 'danh từ' },
      { kanji: '渡り鳥', kana: 'わたりどり', romaji: 'wataridori', meaning: 'chim di trú', partOfSpeech: 'danh từ' },
      { kanji: '登校', kana: 'とうこう', romaji: 'tōkō', meaning: 'sự đến trường', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '途上', kana: 'とじょう', romaji: 'tojō', meaning: 'trên đường, giữa chừng', partOfSpeech: 'danh từ' },
      { kanji: '途絶えます', kana: 'とだえます', romaji: 'todaemasu', meaning: 'bị gián đoạn, dừng hẳn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '努めて', kana: 'つとめて', romaji: 'tsutomete', meaning: 'cố gắng hết sức', partOfSpeech: 'phó từ' },
      { kanji: '度忘れ', kana: 'どわすれ', romaji: 'dowasure', meaning: 'sự quên nhất thời', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '土産', kana: 'どさん', romaji: 'dosan', meaning: 'sản vật địa phương', partOfSpeech: 'danh từ' },
      { kanji: '土手', kana: 'どて', romaji: 'dote', meaning: 'bờ đê', partOfSpeech: 'danh từ' },
      { kanji: '土俵', kana: 'どひょう', romaji: 'dohyō', meaning: 'sàn đấu sumo', partOfSpeech: 'danh từ' },
    ],
  },
];
