// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 905-910.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART2: JlptVocabUnit[] = [
  {
    lessonNumber: 905,
    jlptLevel: 'N1',
    words: [
      { kana: 'ジャンパー', romaji: 'janpā', meaning: 'áo khoác jacket', partOfSpeech: 'danh từ' },
      { kana: 'ジャンプ', romaji: 'janpu', meaning: 'sự nhảy', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'ジャンボ', romaji: 'janbo', meaning: 'cỡ lớn (jumbo)', partOfSpeech: 'danh từ, tính từ na' },
      { kana: 'ジャンル', romaji: 'janru', meaning: 'thể loại', partOfSpeech: 'danh từ' },
      { kana: 'ショー', romaji: 'shō', meaning: 'buổi trình diễn', partOfSpeech: 'danh từ' },
      { kana: 'ショック', romaji: 'shokku', meaning: 'cú sốc', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'しょっちゅう', romaji: 'shocchū', meaning: 'luôn luôn, suốt ngày', partOfSpeech: 'phó từ' },
      { kana: 'スタジオ', romaji: 'sutajio', meaning: 'phòng thu, studio', partOfSpeech: 'danh từ' },
      { kana: 'スチーム', romaji: 'suchīmu', meaning: 'hơi nước, lò sưởi hơi nước', partOfSpeech: 'danh từ' },
      { kana: 'ストライキ', romaji: 'sutoraiki', meaning: 'cuộc đình công', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'ストロー', romaji: 'sutorō', meaning: 'ống hút', partOfSpeech: 'danh từ' },
      { kana: 'ストロボ', romaji: 'sutorobo', meaning: 'đèn flash chụp ảnh', partOfSpeech: 'danh từ' },
      { kana: 'すばしこい', romaji: 'subashikoi', meaning: 'nhanh nhẹn, lanh lợi', partOfSpeech: 'tính từ i' },
      { kana: 'ずばり', romaji: 'zubari', meaning: 'thẳng thắn, đúng ngay chóc', partOfSpeech: 'phó từ' },
      { kana: 'スプリング', romaji: 'supuringu', meaning: 'lò xo', partOfSpeech: 'danh từ' },
      { kanji: 'ずぶ濡れ', kana: 'ずぶぬれ', romaji: 'zubunure', meaning: 'ướt sũng', partOfSpeech: 'danh từ, tính từ na' },
      { kana: 'スペース', romaji: 'supēsu', meaning: 'khoảng không gian', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 906,
    jlptLevel: 'N1',
    words: [
      { kana: 'スポーツカー', romaji: 'supōtsukā', meaning: 'xe thể thao', partOfSpeech: 'danh từ' },
      { kana: 'スラックス', romaji: 'surakkusu', meaning: 'quần tây', partOfSpeech: 'danh từ' },
      { kana: 'ずらっと', romaji: 'zuratto', meaning: 'xếp thành hàng dài', partOfSpeech: 'phó từ' },
      { kana: 'ずるずる', romaji: 'zuruzuru', meaning: 'kéo lê; dây dưa không dứt khoát', partOfSpeech: 'phó từ' },
      { kana: 'ずれ', romaji: 'zure', meaning: 'sự lệch, độ chênh', partOfSpeech: 'danh từ' },
      { kana: 'ずれます', romaji: 'zuremasu', meaning: 'bị lệch, trật khớp', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'すんなり', romaji: 'sunnari', meaning: 'suôn sẻ, thon thả', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'セール', romaji: 'sēru', meaning: 'đợt giảm giá', partOfSpeech: 'danh từ' },
      { kana: 'セクション', romaji: 'sekushon', meaning: 'khu vực, bộ phận', partOfSpeech: 'danh từ' },
      { kana: 'ゼリー', romaji: 'zerī', meaning: 'thạch (món ăn)', partOfSpeech: 'danh từ' },
      { kana: 'セレモニー', romaji: 'seremonī', meaning: 'buổi lễ', partOfSpeech: 'danh từ' },
      { kana: 'ソックス', romaji: 'sokkusu', meaning: 'tất, vớ', partOfSpeech: 'danh từ' },
      { kana: 'ソロ', romaji: 'soro', meaning: 'màn độc tấu, solo', partOfSpeech: 'danh từ' },
      { kana: 'ぞんざい', romaji: 'zonzai', meaning: 'cẩu thả, thô lỗ', partOfSpeech: 'tính từ na' },
      { kana: 'ダース', romaji: 'dāsu', meaning: 'một tá (12 cái)', partOfSpeech: 'danh từ' },
      { kana: 'タイトル', romaji: 'taitoru', meaning: 'tiêu đề', partOfSpeech: 'danh từ' },
      { kana: 'タイピスト', romaji: 'taipisuto', meaning: 'người đánh máy', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 907,
    jlptLevel: 'N1',
    words: [
      { kana: 'タイマー', romaji: 'taimā', meaning: 'đồng hồ hẹn giờ', partOfSpeech: 'danh từ' },
      { kana: 'タイミング', romaji: 'taimingu', meaning: 'thời điểm thích hợp', partOfSpeech: 'danh từ' },
      { kana: 'タイムリー', romaji: 'taimurī', meaning: 'đúng lúc, kịp thời', partOfSpeech: 'tính từ na' },
      { kana: 'タイル', romaji: 'tairu', meaning: 'gạch men', partOfSpeech: 'danh từ' },
      { kana: 'ダウン', romaji: 'daun', meaning: 'sự giảm xuống, gục ngã', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'たった', romaji: 'tatta', meaning: 'chỉ, vỏn vẹn', partOfSpeech: 'phó từ' },
      { kana: 'だぶだぶ', romaji: 'dabudabu', meaning: 'rộng thùng thình', partOfSpeech: 'phó từ, tính từ na' },
      { kana: 'ダブります', romaji: 'daburimasu', meaning: 'trùng lặp, bị đúp', partOfSpeech: 'động từ nhóm 1' },
      { kana: 'だらけ', romaji: 'darake', meaning: 'đầy rẫy, ngập tràn (mang sắc thái tiêu cực)', partOfSpeech: 'hậu tố' },
      { kana: 'タレント', romaji: 'tarento', meaning: 'người nổi tiếng trên truyền hình', partOfSpeech: 'danh từ' },
      { kana: 'タワー', romaji: 'tawā', meaning: 'tòa tháp', partOfSpeech: 'danh từ' },
      { kana: 'チームワーク', romaji: 'chīmuwāku', meaning: 'tinh thần đồng đội', partOfSpeech: 'danh từ' },
      { kana: 'チェンジ', romaji: 'chiぇnji', meaning: 'sự thay đổi', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'チャイム', romaji: 'chaimu', meaning: 'chuông báo (nhạc chuông)', partOfSpeech: 'danh từ' },
      { kana: 'ちやほや', romaji: 'chiyahoya', meaning: 'nuông chiều, xu nịnh', partOfSpeech: 'phó từ, động từ する' },
      { kana: 'チャンネル', romaji: 'channeru', meaning: 'kênh truyền hình', partOfSpeech: 'danh từ' },
      { kana: 'ちょくちょく', romaji: 'chokuchoku', meaning: 'thỉnh thoảng, thường xuyên', partOfSpeech: 'phó từ' },
    ],
  },
  {
    lessonNumber: 908,
    jlptLevel: 'N1',
    words: [
      { kana: 'ちらっと', romaji: 'chiratto', meaning: 'thoáng qua, liếc nhìn', partOfSpeech: 'phó từ' },
      { kana: 'ティッシュペーパー', romaji: 'teぃsshupēpā', meaning: 'giấy ăn, khăn giấy', partOfSpeech: 'danh từ' },
      { kana: 'でかい', romaji: 'dekai', meaning: 'to đùng (cách nói suồng sã)', partOfSpeech: 'tính từ i' },
      { kana: 'デコレーション', romaji: 'dekorēshon', meaning: 'sự trang trí', partOfSpeech: 'danh từ' },
      { kana: 'デザート', romaji: 'dezāto', meaning: 'món tráng miệng', partOfSpeech: 'danh từ' },
      { kana: 'てっきり', romaji: 'tekkiri', meaning: 'chắc chắn là (nhưng hóa ra không phải)', partOfSpeech: 'phó từ' },
      { kana: 'デッサン', romaji: 'dessan', meaning: 'bản phác thảo', partOfSpeech: 'danh từ' },
      { kana: 'デモンストレーション', romaji: 'demonsutorēshon', meaning: 'cuộc biểu tình; buổi trình diễn', partOfSpeech: 'danh từ' },
      { kana: 'テレックス', romaji: 'terekkusu', meaning: 'máy telex', partOfSpeech: 'danh từ' },
      { kana: 'てんで', romaji: 'tende', meaning: 'hoàn toàn (không), tuyệt nhiên', partOfSpeech: 'phó từ' },
      { kana: 'どうにか', romaji: 'dōnika', meaning: 'bằng cách nào đó', partOfSpeech: 'phó từ' },
      { kana: 'どうやら', romaji: 'dōyara', meaning: 'hình như, có vẻ như', partOfSpeech: 'phó từ' },
      { kana: 'トーン', romaji: 'tōn', meaning: 'tông màu, âm sắc', partOfSpeech: 'danh từ' },
      { kana: 'ドライ', romaji: 'dorai', meaning: 'khô ráo; thực dụng, lạnh lùng', partOfSpeech: 'tính từ na' },
      { kana: 'ドライクリーニング', romaji: 'doraikurīningu', meaning: 'giặt khô', partOfSpeech: 'danh từ' },
      { kana: 'トラブル', romaji: 'toraburu', meaning: 'rắc rối, sự cố', partOfSpeech: 'danh từ' },
      { kana: 'トランジスター', romaji: 'toranjisutā', meaning: 'bóng bán dẫn (transistor)', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 909,
    jlptLevel: 'N1',
    words: [
      { kana: 'ドリル', romaji: 'doriru', meaning: 'máy khoan; bài tập luyện', partOfSpeech: 'danh từ' },
      { kana: 'とんだ', romaji: 'tonda', meaning: 'khủng khiếp, ngoài sức tưởng tượng', partOfSpeech: 'từ hạn định' },
      { kana: 'ナイター', romaji: 'naitā', meaning: 'trận đấu ban đêm (thể thao)', partOfSpeech: 'danh từ' },
      { kana: 'ナプキン', romaji: 'napukin', meaning: 'khăn ăn', partOfSpeech: 'danh từ' },
      { kana: 'なんか', romaji: 'nanka', meaning: 'kiểu như, những thứ như', partOfSpeech: 'trợ từ' },
      { kana: 'ナンセンス', romaji: 'nansensu', meaning: 'vô nghĩa, phi lý', partOfSpeech: 'danh từ, tính từ na' },
      { kana: 'なんだかんだ', romaji: 'nandakanda', meaning: 'cái này cái nọ, đủ thứ chuyện', partOfSpeech: 'phó từ' },
      { kanji: 'にも拘らず', kana: 'にもかかわらず', romaji: 'nimokakawarazu', meaning: 'mặc dù vậy, tuy nhiên', partOfSpeech: 'liên từ' },
      { kana: 'ニュアンス', romaji: 'nyuansu', meaning: 'sắc thái ý nghĩa', partOfSpeech: 'danh từ' },
      { kana: 'ネガ', romaji: 'nega', meaning: 'phim âm bản', partOfSpeech: 'danh từ' },
      { kanji: 'ねじ回し', kana: 'ねじまわし', romaji: 'nejimawashi', meaning: 'cái tua vít', partOfSpeech: 'danh từ' },
      { kana: 'ノイローゼ', romaji: 'noirōze', meaning: 'chứng suy nhược thần kinh', partOfSpeech: 'danh từ' },
      { kana: 'パジャマ', romaji: 'pajama', meaning: 'đồ ngủ pyjama', partOfSpeech: 'danh từ' },
      { kana: 'バッジ', romaji: 'bajji', meaning: 'huy hiệu', partOfSpeech: 'danh từ' },
      { kana: 'バット', romaji: 'batto', meaning: 'gậy bóng chày', partOfSpeech: 'danh từ' },
      { kana: 'ばてます', romaji: 'batemasu', meaning: 'kiệt sức, đuối sức', partOfSpeech: 'động từ nhóm 2' },
      { kana: 'ハンガー', romaji: 'hangā', meaning: 'cái móc áo', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 910,
    jlptLevel: 'N1',
    words: [
      { kana: 'パンク', romaji: 'panku', meaning: 'thủng lốp xe; nhạc punk', partOfSpeech: 'danh từ, động từ する' },
      { kana: 'ビールス', romaji: 'bīrusu', meaning: 'vi rút', partOfSpeech: 'danh từ' },
      { kana: 'ビジネス', romaji: 'bijinesu', meaning: 'công việc kinh doanh', partOfSpeech: 'danh từ' },
      { kana: 'びっしょり', romaji: 'bisshori', meaning: 'ướt sũng, đẫm mồ hôi', partOfSpeech: 'phó từ' },
      { kana: 'ひょっと', romaji: 'hyotto', meaning: 'chợt, ngẫu nhiên', partOfSpeech: 'phó từ' },
      { kana: 'びり', romaji: 'biri', meaning: 'vị trí cuối cùng, hạng bét', partOfSpeech: 'danh từ' },
      { kana: 'ヒント', romaji: 'hinto', meaning: 'gợi ý', partOfSpeech: 'danh từ' },
    ],
  },
];
