// Bổ sung kanji N1 để ôn thi — tự soạn tay (không auto-scrape).
// KanjiLesson number mới: 509–518. Vẫn còn thiếu nhiều so với trọn bộ Jōyō
// Kanji (~2.136 chữ) — đây là đợt bổ sung, không phải hoàn thiện.

import type { JlptKanjiLesson } from './jlpt-kanji.data';

export const JLPT_KANJI_BOOST2_N1: JlptKanjiLesson[] = [
  {
    lessonNumber: 509,
    jlptLevel: 'N1',
    title: 'Bài 46 · Kanji N1 bổ sung (1)',
    sortOrder: 5090,
    entries: [
      { character: '呂', hanViet: 'LỮ', onyomi: 'ろ', meaningVi: 'âm luật (dùng trong お風呂 - bồn tắm)', strokeCount: 7 },
      { character: '朕', hanViet: 'TRẪM', onyomi: 'ちん', meaningVi: 'trẫm (đại từ vua tự xưng, cổ)', strokeCount: 10 },
      { character: '陛', hanViet: 'BỆ', onyomi: 'へい', meaningVi: 'bệ hạ (陛下)', strokeCount: 10 },
      { character: '皇', hanViet: 'HOÀNG', onyomi: 'こう, おう', meaningVi: 'hoàng đế', strokeCount: 9 },
      { character: '陣', hanViet: 'TRẬN', onyomi: 'じん', meaningVi: 'trận địa, đội hình', strokeCount: 10 },
      { character: '軍', hanViet: 'QUÂN', onyomi: 'ぐん', meaningVi: 'quân đội', strokeCount: 9 },
      { character: '隊', hanViet: 'ĐỘI', onyomi: 'たい', meaningVi: 'đội ngũ', strokeCount: 12 },
      { character: '砲', hanViet: 'PHÁO', onyomi: 'ほう', meaningVi: 'đại bác', strokeCount: 10 },
      { character: '弾', hanViet: 'ĐẠN', onyomi: 'だん', kunyomi: 'たま, ひ-く', meaningVi: 'đạn, gảy đàn', strokeCount: 12 },
      { character: '銃', hanViet: 'SÚNG', onyomi: 'じゅう', meaningVi: 'súng', strokeCount: 14 },
      { character: '剣', hanViet: 'KIẾM', onyomi: 'けん', kunyomi: 'つるぎ', meaningVi: 'thanh kiếm', strokeCount: 10 },
      { character: '刃', hanViet: 'NHẬN', onyomi: 'じん', kunyomi: 'は', meaningVi: 'lưỡi dao', strokeCount: 3 },
      { character: '盾', hanViet: 'THUẪN', onyomi: 'じゅん', kunyomi: 'たて', meaningVi: 'cái khiên', strokeCount: 9 },
      { character: '甲', hanViet: 'GIÁP', onyomi: 'こう', meaningVi: 'áo giáp; hạng nhất', strokeCount: 5 },
      { character: '冑', hanViet: 'TRỤ', onyomi: 'ちゅう', meaningVi: 'mũ trụ (giáp trụ)', strokeCount: 9 },
      { character: '征', hanViet: 'CHINH', onyomi: 'せい', meaningVi: 'chinh phạt, viễn chinh', strokeCount: 8 },
      { character: '伐', hanViet: 'PHẠT', onyomi: 'ばつ', meaningVi: 'thảo phạt, chặt đốn', strokeCount: 6 },
      { character: '侵', hanViet: 'XÂM', onyomi: 'しん', kunyomi: 'おか-す', meaningVi: 'xâm phạm', strokeCount: 9 },
    ],
  },
  {
    lessonNumber: 510,
    jlptLevel: 'N1',
    title: 'Bài 47 · Kanji N1 bổ sung (2)',
    sortOrder: 5100,
    entries: [
      { character: '賢', hanViet: 'HIỀN', onyomi: 'けん', kunyomi: 'かしこ-い', meaningVi: 'hiền tài, thông minh', strokeCount: 16 },
      { character: '愚', hanViet: 'NGU', onyomi: 'ぐ', kunyomi: 'おろ-か', meaningVi: 'ngu dốt', strokeCount: 13 },
      { character: '賎', hanViet: 'TIỆN', onyomi: 'せん', kunyomi: 'いや-しい', meaningVi: 'hèn hạ, ti tiện', strokeCount: 14 },
      { character: '貴', hanViet: 'QUÝ', onyomi: 'き', kunyomi: 'とうと-い, たっと-い', meaningVi: 'quý giá, cao quý', strokeCount: 12 },
      { character: '卑', hanViet: 'TI', onyomi: 'ひ', kunyomi: 'いや-しい', meaningVi: 'ti tiện, thấp hèn', strokeCount: 9 },
      { character: '傲', hanViet: 'NGẠO', onyomi: 'ごう', meaningVi: 'kiêu ngạo', strokeCount: 13 },
      { character: '慢', hanViet: 'MẠN', onyomi: 'まん', meaningVi: 'kiêu mạn, chậm chạp', strokeCount: 14 },
      { character: '謙', hanViet: 'KHIÊM', onyomi: 'けん', meaningVi: 'khiêm tốn', strokeCount: 17 },
      { character: '虚', hanViet: 'HƯ', onyomi: 'きょ, こ', kunyomi: 'むな-しい', meaningVi: 'trống rỗng, hư ảo', strokeCount: 11 },
      { character: '狡', hanViet: 'GIẢO', onyomi: 'こう', kunyomi: 'ずる-い', meaningVi: 'xảo quyệt', strokeCount: 9 },
      { character: '醜', hanViet: 'XÚ', onyomi: 'しゅう', kunyomi: 'みにく-い', meaningVi: 'xấu xí', strokeCount: 17 },
      { character: '麗', hanViet: 'LỆ', onyomi: 'れい', kunyomi: 'うるわ-しい', meaningVi: 'xinh đẹp, mỹ lệ', strokeCount: 19 },
      { character: '艶', hanViet: 'DIỄM', onyomi: 'えん', kunyomi: 'つや', meaningVi: 'diễm lệ, bóng bẩy', strokeCount: 19 },
      { character: '荘', hanViet: 'TRANG', onyomi: 'そう', meaningVi: 'trang nghiêm, biệt trang', strokeCount: 9 },
      { character: '粛', hanViet: 'TÚC', onyomi: 'しゅく', meaningVi: 'nghiêm túc, tĩnh lặng', strokeCount: 11 },
    ],
  },
  {
    lessonNumber: 511,
    jlptLevel: 'N1',
    title: 'Bài 48 · Kanji N1 bổ sung (3)',
    sortOrder: 5110,
    entries: [
      { character: '哀', hanViet: 'AI', onyomi: 'あい', kunyomi: 'あわ-れ', meaningVi: 'bi ai, thương xót', strokeCount: 9 },
      { character: '嘆', hanViet: 'THÁN', onyomi: 'たん', kunyomi: 'なげ-く', meaningVi: 'than thở, cảm thán', strokeCount: 13 },
      { character: '悼', hanViet: 'ĐIỆU', onyomi: 'とう', kunyomi: 'いた-む', meaningVi: 'thương tiếc (người mất)', strokeCount: 11 },
      { character: '憐', hanViet: 'LÂN', onyomi: 'れん', kunyomi: 'あわ-れむ', meaningVi: 'thương xót, đáng thương', strokeCount: 15 },
      { character: '慈', hanViet: 'TỪ', onyomi: 'じ', kunyomi: 'いつく-しむ', meaningVi: 'từ bi, nhân từ', strokeCount: 13 },
      { character: '悦', hanViet: 'DUYỆT', onyomi: 'えつ', meaningVi: 'vui mừng, hài lòng', strokeCount: 10 },
      { character: '欣', hanViet: 'HÂN', onyomi: 'きん', meaningVi: 'hân hoan (cổ, hiếm)', strokeCount: 8 },
      { character: '憤', hanViet: 'PHẪN', onyomi: 'ふん', kunyomi: 'いきどお-る', meaningVi: 'phẫn nộ', strokeCount: 15 },
      { character: '怨', hanViet: 'OÁN', onyomi: 'えん, おん', kunyomi: 'うら-む', meaningVi: 'oán hận', strokeCount: 9 },
      { character: '恨', hanViet: 'HẬN', onyomi: 'こん', kunyomi: 'うら-む', meaningVi: 'thù hận', strokeCount: 9 },
      { character: '妬', hanViet: 'ĐỐ', onyomi: 'と', kunyomi: 'ねた-む', meaningVi: 'ghen ghét', strokeCount: 8 },
      { character: '羨', hanViet: 'TIỄN', onyomi: 'せん', kunyomi: 'うらや-む, うらや-ましい', meaningVi: 'ghen tị, ao ước', strokeCount: 13 },
      { character: '嫉', hanViet: 'TẬT', onyomi: 'しつ', meaningVi: 'ghen tị (嫉妬)', strokeCount: 13 },
      { character: '侮', hanViet: 'VŨ', onyomi: 'ぶ', kunyomi: 'あなど-る', meaningVi: 'khinh thường', strokeCount: 8 },
      { character: '蔑', hanViet: 'MIỆT', onyomi: 'べつ', kunyomi: 'さげす-む', meaningVi: 'khinh miệt', strokeCount: 14 },
      { character: '恭', hanViet: 'CUNG', onyomi: 'きょう', kunyomi: 'うやうや-しい', meaningVi: 'cung kính', strokeCount: 10 },
    ],
  },
  {
    lessonNumber: 512,
    jlptLevel: 'N1',
    title: 'Bài 49 · Kanji N1 bổ sung (4)',
    sortOrder: 5120,
    entries: [
      { character: '賓', hanViet: 'TÂN', onyomi: 'ひん', meaningVi: 'tân khách, thượng khách', strokeCount: 15 },
      { character: '宴', hanViet: 'YẾN', onyomi: 'えん', kunyomi: 'うたげ', meaningVi: 'tiệc, yến tiệc', strokeCount: 10 },
      { character: '酌', hanViet: 'CHƯỚC', onyomi: 'しゃく', kunyomi: 'く-む', meaningVi: 'rót rượu, cân nhắc', strokeCount: 10 },
      { character: '酔', hanViet: 'TÚY', onyomi: 'すい', kunyomi: 'よ-う', meaningVi: 'say (rượu)', strokeCount: 11 },
      { character: '賭', hanViet: 'ĐỔ', onyomi: 'と', kunyomi: 'か-ける', meaningVi: 'cá cược', strokeCount: 16 },
      { character: '博', hanViet: 'BÁC', onyomi: 'はく, ばく', meaningVi: 'uyên bác, cờ bạc', strokeCount: 12 },
      { character: '賄', hanViet: 'HỐI', onyomi: 'わい', kunyomi: 'まかな-う', meaningVi: 'hối lộ, chi trả', strokeCount: 13 },
      { character: '賂', hanViet: 'LỘ', onyomi: 'ろ', meaningVi: 'của hối lộ (賄賂)', strokeCount: 13 },
      { character: '叛', hanViet: 'BẠN', onyomi: 'はん', meaningVi: 'phản nghịch', strokeCount: 9 },
      { character: '逆', hanViet: 'NGHỊCH', onyomi: 'ぎゃく', kunyomi: 'さか, さか-らう', meaningVi: 'ngược lại, nghịch', strokeCount: 9 },
      { character: '策', hanViet: 'SÁCH', onyomi: 'さく', meaningVi: 'kế sách, chính sách', strokeCount: 12 },
      { character: '奸', hanViet: 'GIAN', onyomi: 'かん', meaningVi: 'gian xảo, gian thần (cổ)', strokeCount: 6 },
    ],
  },
  {
    lessonNumber: 513,
    jlptLevel: 'N1',
    title: 'Bài 50 · Kanji N1 bổ sung (5)',
    sortOrder: 5130,
    entries: [
      { character: '瞭', hanViet: 'LIỄU', onyomi: 'りょう', meaningVi: 'rõ ràng (明瞭)', strokeCount: 17 },
      { character: '陥', hanViet: 'HÃM', onyomi: 'かん', kunyomi: 'おちい-る, おとしい-れる', meaningVi: 'sa vào, khiếm khuyết', strokeCount: 10 },
      { character: '穴', hanViet: 'HUYỆT', onyomi: 'けつ', kunyomi: 'あな', meaningVi: 'cái lỗ, hang huyệt', strokeCount: 5 },
      { character: '窮', hanViet: 'CÙNG', onyomi: 'きゅう', kunyomi: 'きわ-める, きわ-まる', meaningVi: 'cùng cực, khốn cùng', strokeCount: 15 },
      { character: '餓', hanViet: 'NGẠ', onyomi: 'が', kunyomi: 'う-える', meaningVi: 'đói (餓鬼)', strokeCount: 15 },
      { character: '渇', hanViet: 'KHÁT', onyomi: 'かつ', kunyomi: 'かわ-く', meaningVi: 'khát nước', strokeCount: 11 },
      { character: '涸', hanViet: 'HÁC', onyomi: 'こ', kunyomi: 'か-れる', meaningVi: 'khô cạn (nước)', strokeCount: 11 },
      { character: '涯', hanViet: 'NHAI', onyomi: 'がい', meaningVi: 'chân trời, bờ cõi (生涯)', strokeCount: 11 },
      { character: '孤', hanViet: 'CÔ', onyomi: 'こ', kunyomi: 'みなしご', meaningVi: 'cô độc, mồ côi', strokeCount: 9 },
      { character: '執', hanViet: 'CHẤP', onyomi: 'しつ, しゅう', kunyomi: 'と-る', meaningVi: 'chấp giữ, kiên trì', strokeCount: 11 },
    ],
  },
  {
    lessonNumber: 514,
    jlptLevel: 'N1',
    title: 'Bài 51 · Kanji N1 bổ sung (6)',
    sortOrder: 5140,
    entries: [
      { character: '謁', hanViet: 'YẾT', onyomi: 'えつ', meaningVi: 'yết kiến (cổ)', strokeCount: 15 },
      { character: '拝', hanViet: 'BÁI', onyomi: 'はい', kunyomi: 'おが-む', meaningVi: 'bái lạy, khiêm nhường', strokeCount: 8 },
      { character: '賜', hanViet: 'TỨ', onyomi: 'し', kunyomi: 'たまわ-る', meaningVi: 'ban tặng (từ trên xuống)', strokeCount: 15 },
      { character: '献', hanViet: 'HIẾN', onyomi: 'けん, こん', meaningVi: 'hiến tặng', strokeCount: 13 },
      { character: '呈', hanViet: 'TRÌNH', onyomi: 'てい', meaningVi: 'trình bày, dâng lên', strokeCount: 7 },
      { character: '贈', hanViet: 'TẶNG', onyomi: 'ぞう', kunyomi: 'おく-る', meaningVi: 'tặng, biếu', strokeCount: 18 },
      { character: '遺', hanViet: 'DI', onyomi: 'い, ゆい', kunyomi: 'のこ-す', meaningVi: 'để lại (di sản, di chúc)', strokeCount: 15 },
      { character: '踏', hanViet: 'ĐẠP', onyomi: 'とう', kunyomi: 'ふ-む', meaningVi: 'giẫm, đạp lên', strokeCount: 15 },
      { character: '滞', hanViet: 'TRỆ', onyomi: 'たい', kunyomi: 'とどこお-る', meaningVi: 'trì trệ, ứ đọng', strokeCount: 13 },
      { character: '渋', hanViet: 'SÁP', onyomi: 'じゅう', kunyomi: 'しぶ-い, しぶ-る', meaningVi: 'chát, miễn cưỡng', strokeCount: 11 },
      { character: '躊', hanViet: 'TRÙ', onyomi: 'ちゅう', meaningVi: 'do dự (躊躇)', strokeCount: 21 },
      { character: '躇', hanViet: 'TRỪ', onyomi: 'ちょ', meaningVi: 'do dự (躊躇)', strokeCount: 20 },
      { character: '惑', hanViet: 'HOẶC', onyomi: 'わく', kunyomi: 'まど-う', meaningVi: 'mê hoặc, hoang mang', strokeCount: 12 },
    ],
  },
  {
    lessonNumber: 515,
    jlptLevel: 'N1',
    title: 'Bài 52 · Kanji N1 bổ sung (7)',
    sortOrder: 5150,
    entries: [
      { character: '謹', hanViet: 'CẨN', onyomi: 'きん', kunyomi: 'つつし-む', meaningVi: 'cẩn thận, cung kính', strokeCount: 17 },
      { character: '慎', hanViet: 'THẬN', onyomi: 'しん', kunyomi: 'つつし-む', meaningVi: 'thận trọng', strokeCount: 13 },
      { character: '躾', hanViet: 'MỸ', kunyomi: 'しつけ', meaningVi: 'giáo dục lễ nghi (chữ tự tạo Nhật)', strokeCount: 17 },
      { character: '矯', hanViet: 'KIỂU', onyomi: 'きょう', kunyomi: 'た-める', meaningVi: 'uốn nắn, chỉnh sửa', strokeCount: 17 },
      { character: '懲', hanViet: 'TRỪNG', onyomi: 'ちょう', kunyomi: 'こ-りる, こ-らす', meaningVi: 'trừng phạt, răn đe', strokeCount: 18 },
      { character: '罰', hanViet: 'PHẠT', onyomi: 'ばつ, ばち', meaningVi: 'trừng phạt', strokeCount: 14 },
      { character: '裁', hanViet: 'TÀI', onyomi: 'さい', kunyomi: 'さば-く, た-つ', meaningVi: 'xét xử, phân xử', strokeCount: 12 },
      { character: '訴', hanViet: 'TỐ', onyomi: 'そ', kunyomi: 'うった-える', meaningVi: 'tố cáo, khởi kiện', strokeCount: 12 },
      { character: '訟', hanViet: 'TỤNG', onyomi: 'しょう', meaningVi: 'kiện tụng (訴訟)', strokeCount: 11 },
      { character: '控', hanViet: 'KHỐNG', onyomi: 'こう', kunyomi: 'ひか-える', meaningVi: 'kìm chế, ghi lại', strokeCount: 11 },
      { character: '述', hanViet: 'THUẬT', onyomi: 'じゅつ', kunyomi: 'の-べる', meaningVi: 'trần thuật, kể lại', strokeCount: 8 },
      { character: '陳', hanViet: 'TRẦN', onyomi: 'ちん', meaningVi: 'trần thuật, bày tỏ; cũ kỹ', strokeCount: 11 },
    ],
  },
  {
    lessonNumber: 516,
    jlptLevel: 'N1',
    title: 'Bài 53 · Kanji N1 bổ sung (8)',
    sortOrder: 5160,
    entries: [
      { character: '巧', hanViet: 'XẢO', onyomi: 'こう', kunyomi: 'たく-み', meaningVi: 'khéo léo, tinh xảo', strokeCount: 5 },
      { character: '妙', hanViet: 'DIỆU', onyomi: 'みょう', meaningVi: 'kỳ diệu, khéo léo', strokeCount: 7 },
      { character: '匠', hanViet: 'TƯỢNG', onyomi: 'しょう', meaningVi: 'thợ thủ công bậc thầy', strokeCount: 6 },
      { character: '彫', hanViet: 'ĐIÊU', onyomi: 'ちょう', kunyomi: 'ほ-る', meaningVi: 'điêu khắc', strokeCount: 11 },
      { character: '彩', hanViet: 'THÁI', onyomi: 'さい', kunyomi: 'いろど-る', meaningVi: 'màu sắc, tô điểm', strokeCount: 11 },
      { character: '彙', hanViet: 'DI', onyomi: 'い', meaningVi: 'sưu tập, loại (語彙 - từ vựng)', strokeCount: 13 },
      { character: '筆', hanViet: 'BÚT', onyomi: 'ひつ', kunyomi: 'ふで', meaningVi: 'bút lông', strokeCount: 12 },
      { character: '墨', hanViet: 'MẶC', onyomi: 'ぼく', kunyomi: 'すみ', meaningVi: 'mực tàu', strokeCount: 14 },
      { character: '硯', hanViet: 'NGHIỄN', onyomi: 'けん', kunyomi: 'すずり', meaningVi: 'nghiên mực', strokeCount: 12 },
      { character: '詩', hanViet: 'THI', onyomi: 'し', meaningVi: 'thơ ca', strokeCount: 13 },
      { character: '句', hanViet: 'CÚ', onyomi: 'く', meaningVi: 'câu (văn/thơ)', strokeCount: 5 },
      { character: '韻', hanViet: 'VẬN', onyomi: 'いん', meaningVi: 'vần điệu', strokeCount: 19 },
      { character: '旋', hanViet: 'TUYỀN', onyomi: 'せん', meaningVi: 'xoay vòng (旋回)', strokeCount: 11 },
      { character: '鑑', hanViet: 'GIÁM', onyomi: 'かん', kunyomi: 'かんが-みる', meaningVi: 'soi xét, thẩm định', strokeCount: 23 },
    ],
  },
  {
    lessonNumber: 517,
    jlptLevel: 'N1',
    title: 'Bài 54 · Kanji N1 bổ sung (9)',
    sortOrder: 5170,
    entries: [
      { character: '循', hanViet: 'TUẦN', onyomi: 'じゅん', meaningVi: 'tuần hoàn, noi theo', strokeCount: 12 },
      { character: '軌', hanViet: 'QUỸ', onyomi: 'き', meaningVi: 'quỹ đạo', strokeCount: 9 },
      { character: '跡', hanViet: 'TÍCH', onyomi: 'せき', kunyomi: 'あと', meaningVi: 'dấu vết, di tích', strokeCount: 13 },
      { character: '痕', hanViet: 'NGÂN', onyomi: 'こん', kunyomi: 'あと', meaningVi: 'vết tích, sẹo', strokeCount: 11 },
      { character: '刹', hanViet: 'SÁT', onyomi: 'せつ', meaningVi: 'khoảnh khắc (刹那); chùa (古刹)', strokeCount: 8 },
      { character: '那', hanViet: 'NA', onyomi: 'な', meaningVi: 'na (刹那 - sát-na)', strokeCount: 7 },
      { character: '摩', hanViet: 'MA', onyomi: 'ま', meaningVi: 'ma sát, xoa (摩擦)', strokeCount: 15 },
      { character: '擦', hanViet: 'SÁT', onyomi: 'さつ', kunyomi: 'す-る, こす-る', meaningVi: 'chà xát, cọ xát', strokeCount: 17 },
      { character: '摂', hanViet: 'NHIẾP', onyomi: 'せつ', meaningVi: 'thu nạp, nhiếp lấy (摂取)', strokeCount: 13 },
      { character: '浸', hanViet: 'XÂM', onyomi: 'しん', kunyomi: 'ひた-す, ひた-る', meaningVi: 'ngâm, thấm', strokeCount: 10 },
      { character: '滴', hanViet: 'TRÍCH', onyomi: 'てき', kunyomi: 'しずく, したた-る', meaningVi: 'giọt (nước)', strokeCount: 14 },
      { character: '雫', hanViet: 'HỌA', kunyomi: 'しずく', meaningVi: 'giọt nước (chữ tự tạo Nhật)', strokeCount: 11 },
      { character: '霧', hanViet: 'VỤ', onyomi: 'む', kunyomi: 'きり', meaningVi: 'sương mù', strokeCount: 19 },
    ],
  },
  {
    lessonNumber: 518,
    jlptLevel: 'N1',
    title: 'Bài 55 · Kanji N1 bổ sung (10)',
    sortOrder: 5180,
    entries: [
      { character: '霜', hanViet: 'SƯƠNG', onyomi: 'そう', kunyomi: 'しも', meaningVi: 'sương giá', strokeCount: 17 },
      { character: '虹', hanViet: 'HỒNG', onyomi: 'こう', kunyomi: 'にじ', meaningVi: 'cầu vồng', strokeCount: 9 },
      { character: '嵐', hanViet: 'LAM', onyomi: 'らん', kunyomi: 'あらし', meaningVi: 'bão', strokeCount: 12 },
      { character: '雷', hanViet: 'LÔI', onyomi: 'らい', kunyomi: 'かみなり', meaningVi: 'sấm sét', strokeCount: 13 },
      { character: '旱', hanViet: 'HẠN', onyomi: 'かん', kunyomi: 'ひで-り', meaningVi: 'hạn hán (cổ, hiếm)', strokeCount: 7 },
      { character: '渦', hanViet: 'OA', onyomi: 'か', kunyomi: 'うず', meaningVi: 'xoáy nước', strokeCount: 12 },
      { character: '氾', hanViet: 'PHIẾM', onyomi: 'はん', meaningVi: 'tràn lan (氾濫)', strokeCount: 5 },
      { character: '濫', hanViet: 'LẠM', onyomi: 'らん', meaningVi: 'tràn ngập, lạm dụng (氾濫)', strokeCount: 18 },
      { character: '噴', hanViet: 'PHÚN', onyomi: 'ふん', kunyomi: 'ふ-く', meaningVi: 'phun trào', strokeCount: 15 },
      { character: '爆', hanViet: 'BẠO', onyomi: 'ばく', meaningVi: 'nổ, bùng nổ', strokeCount: 19 },
      { character: '溶', hanViet: 'DUNG', onyomi: 'よう', kunyomi: 'と-ける, と-かす', meaningVi: 'hòa tan, dung nham', strokeCount: 13 },
      { character: '亀', hanViet: 'QUY', onyomi: 'き', kunyomi: 'かめ', meaningVi: 'con rùa', strokeCount: 11 },
    ],
  },
];
