// Bổ sung từ vựng N1 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 965-970.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N1_PART12: JlptVocabUnit[] = [
  {
    lessonNumber: 965,
    jlptLevel: 'N1',
    words: [
      { kanji: '樹立', kana: 'じゅりつ', romaji: 'juritsu', meaning: 'sự thiết lập, xác lập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '収益', kana: 'しゅうえき', romaji: 'shūeki', meaning: 'lợi nhuận, thu nhập', partOfSpeech: 'danh từ' },
      { kanji: '収集', kana: 'しゅうしゅう', romaji: 'shūshū', meaning: 'sự thu thập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '収容', kana: 'しゅうよう', romaji: 'shūyō', meaning: 'sự thu nhận, chứa đựng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '周期', kana: 'しゅうき', romaji: 'shūki', meaning: 'chu kỳ', partOfSpeech: 'danh từ' },
      { kanji: '就業', kana: 'しゅうぎょう', romaji: 'shūgyō', meaning: 'sự bắt đầu làm việc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '修学', kana: 'しゅうがく', romaji: 'shūgaku', meaning: 'việc học tập', partOfSpeech: 'danh từ' },
      { kanji: '終日', kana: 'しゅうじつ', romaji: 'shūjitsu', meaning: 'suốt cả ngày', partOfSpeech: 'danh từ' },
      { kanji: '衆議院', kana: 'しゅうぎいん', romaji: 'shūgiin', meaning: 'Hạ viện (Nhật Bản)', partOfSpeech: 'danh từ' },
      { kanji: '襲います', kana: 'おそいます', romaji: 'osoimasu', meaning: 'tấn công, ập đến', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '襲撃', kana: 'しゅうげき', romaji: 'shūgeki', meaning: 'cuộc tập kích', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '蹴飛ばします', kana: 'けとばします', romaji: 'ketobashimasu', meaning: 'đá văng, cự tuyệt', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '集計', kana: 'しゅうけい', romaji: 'shūkei', meaning: 'sự tổng hợp số liệu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '十字路', kana: 'じゅうじろ', romaji: 'jūjiro', meaning: 'ngã tư', partOfSpeech: 'danh từ' },
      { kanji: '十分', kana: 'じっぷん', romaji: 'jippun', meaning: 'mười phút', partOfSpeech: 'danh từ' },
      { kanji: '従業員', kana: 'じゅうぎょういん', romaji: 'jūgyōin', meaning: 'nhân viên', partOfSpeech: 'danh từ' },
      { kanji: '従事', kana: 'じゅうじ', romaji: 'jūji', meaning: 'sự tham gia (công việc)', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 966,
    jlptLevel: 'N1',
    words: [
      { kanji: '従来', kana: 'じゅうらい', romaji: 'jūrai', meaning: 'từ trước tới nay', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '渋い', kana: 'しぶい', romaji: 'shibui', meaning: 'chát; giản dị mà lịch lãm; cau có', partOfSpeech: 'tính từ i' },
      { kanji: '獣', kana: 'けだもの', romaji: 'kedamono', meaning: 'dã thú', partOfSpeech: 'danh từ' },
      { kanji: '重んじます', kana: 'おもんじます', romaji: 'omonjimasu', meaning: 'coi trọng, tôn trọng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '重複', kana: 'じゅうふく', romaji: 'jūfuku', meaning: 'sự trùng lặp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '重宝', kana: 'じゅうほう', romaji: 'jūhō', meaning: 'vật quý, sự tiện lợi', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '重役', kana: 'おもやく', romaji: 'omoyaku', meaning: 'trách nhiệm nặng nề; giám đốc', partOfSpeech: 'danh từ' },
      { kanji: '銃', kana: 'つつ', romaji: 'tsutsu', meaning: 'súng, nòng súng', partOfSpeech: 'danh từ' },
      { kanji: '宿命', kana: 'しゅくめい', romaji: 'shukumei', meaning: 'số mệnh', partOfSpeech: 'danh từ' },
      { kanji: '祝賀', kana: 'しゅくが', romaji: 'shukuga', meaning: 'sự chúc mừng, lễ mừng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '縮まります', kana: 'ちぢまります', romaji: 'chijimarimasu', meaning: 'bị rút ngắn lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '出くわします', kana: 'でくわします', romaji: 'dekuwashimasu', meaning: 'tình cờ gặp phải', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '出演', kana: 'しゅつえん', romaji: 'shutsuen', meaning: 'sự xuất hiện trên sân khấu/màn ảnh', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '出血', kana: 'しゅっけつ', romaji: 'shukketsu', meaning: 'sự chảy máu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '出産', kana: 'しゅっさん', romaji: 'shussan', meaning: 'sự sinh đẻ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '出社', kana: 'しゅっしゃ', romaji: 'shussha', meaning: 'sự đến công ty làm việc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '出世', kana: 'しゅっせ', romaji: 'shusse', meaning: 'sự thăng tiến, thành đạt', partOfSpeech: 'danh từ, động từ する' },
    ],
  },
  {
    lessonNumber: 967,
    jlptLevel: 'N1',
    words: [
      { kanji: '出生', kana: 'しゅっしょう', romaji: 'shusshō', meaning: 'sự ra đời', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '出題', kana: 'しゅつだい', romaji: 'shutsudai', meaning: 'sự ra đề (thi)', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '出直し', kana: 'でなおし', romaji: 'denaoshi', meaning: 'sự làm lại từ đầu', partOfSpeech: 'danh từ' },
      { kanji: '出動', kana: 'しゅつどう', romaji: 'shutsudō', meaning: 'sự xuất quân, xuất động', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '出費', kana: 'しゅっぴ', romaji: 'shuppi', meaning: 'chi phí, khoản chi', partOfSpeech: 'danh từ' },
      { kanji: '出品', kana: 'しゅっぴん', romaji: 'shuppin', meaning: 'vật trưng bày, sản phẩm dự thi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '出来物', kana: 'できもの', romaji: 'dekimono', meaning: 'mụn nhọt, khối u', partOfSpeech: 'danh từ' },
      { kanji: '瞬き', kana: 'またたき', romaji: 'matataki', meaning: 'cái chớp mắt, sự lấp lánh', partOfSpeech: 'danh từ' },
      { kanji: '準じます', kana: 'じゅんじます', romaji: 'junjimasu', meaning: 'tuân theo, dựa theo', partOfSpeech: 'động từ する' },
      { kanji: '準急', kana: 'じゅんきゅう', romaji: 'junkyū', meaning: 'tàu bán tốc hành', partOfSpeech: 'danh từ' },
      { kanji: '潤います', kana: 'うるおいます', romaji: 'uruoimasu', meaning: 'được ẩm ướt; được lợi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '処置', kana: 'しょち', romaji: 'shochi', meaning: 'sự xử lý, biện pháp', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '処罰', kana: 'しょばつ', romaji: 'shobatsu', meaning: 'sự trừng phạt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '処分', kana: 'しょぶん', romaji: 'shobun', meaning: 'sự xử lý, xử phạt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '初', kana: 'はつ', romaji: 'hatsu', meaning: 'lần đầu tiên, mới', partOfSpeech: 'danh từ' },
      { kanji: '初耳', kana: 'はつみみ', romaji: 'hatsumimi', meaning: 'lần đầu nghe thấy', partOfSpeech: 'danh từ' },
      { kanji: '初版', kana: 'しょはん', romaji: 'shohan', meaning: 'ấn bản đầu tiên', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 968,
    jlptLevel: 'N1',
    words: [
      { kanji: '所在', kana: 'しょざい', romaji: 'shozai', meaning: 'nơi ở, địa điểm', partOfSpeech: 'danh từ' },
      { kanji: '所持', kana: 'しょじ', romaji: 'shoji', meaning: 'sự sở hữu, mang theo', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '所属', kana: 'しょぞく', romaji: 'shozoku', meaning: 'sự trực thuộc', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '所定', kana: 'しょてい', romaji: 'shotei', meaning: 'đã quy định sẵn', partOfSpeech: 'danh từ' },
      { kanji: '庶民', kana: 'しょみん', romaji: 'shomin', meaning: 'dân thường', partOfSpeech: 'danh từ' },
      { kanji: '庶務', kana: 'しょむ', romaji: 'shomu', meaning: 'công việc hành chính chung', partOfSpeech: 'danh từ' },
      { kanji: '書き取ります', kana: 'かきとります', romaji: 'kakitorimasu', meaning: 'chép lại, viết chính tả', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '書評', kana: 'しょひょう', romaji: 'shohyō', meaning: 'bài phê bình sách', partOfSpeech: 'danh từ' },
      { kanji: '諸', kana: 'しょ', romaji: 'sho', meaning: 'các, nhiều (tiền tố)', partOfSpeech: 'hậu tố' },
      { kanji: '諸君', kana: 'しょくん', romaji: 'shokun', meaning: 'các bạn, quý vị', partOfSpeech: 'danh từ' },
      { kanji: '助', kana: 'じょ', romaji: 'jo', meaning: 'sự giúp đỡ, trợ giúp', partOfSpeech: 'danh từ' },
      { kanji: '助け', kana: 'たすけ', romaji: 'tasuke', meaning: 'sự trợ giúp', partOfSpeech: 'danh từ' },
      { kanji: '助言', kana: 'じょげん', romaji: 'jogen', meaning: 'lời khuyên', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '助動詞', kana: 'じょどうし', romaji: 'jodōshi', meaning: 'trợ động từ', partOfSpeech: 'danh từ' },
      { kanji: '女子', kana: 'おなご', romaji: 'onago', meaning: 'phụ nữ, con gái (cách nói cổ)', partOfSpeech: 'danh từ' },
      { kanji: '除外', kana: 'じょがい', romaji: 'jogai', meaning: 'sự loại trừ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '傷付きます', kana: 'きずつきます', romaji: 'kizutsukimasu', meaning: 'bị thương, bị tổn thương', partOfSpeech: 'động từ nhóm 1' },
    ],
  },
  {
    lessonNumber: 969,
    jlptLevel: 'N1',
    words: [
      { kanji: '勝ります', kana: 'まさります', romaji: 'masarimasu', meaning: 'vượt trội hơn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '勝利', kana: 'しょうり', romaji: 'shōri', meaning: 'chiến thắng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '商人', kana: 'あきうど', romaji: 'akiudo', meaning: 'thương nhân (cách đọc cổ)', partOfSpeech: 'danh từ' },
      { kanji: '唱えます', kana: 'となえます', romaji: 'tonaemasu', meaning: 'hô vang, tụng niệm; đề xướng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '嘗めます', kana: 'なめます', romaji: 'namemasu', meaning: 'liếm, nếm; xem thường', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '奨励', kana: 'しょうれい', romaji: 'shōrei', meaning: 'sự khuyến khích', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '小児科', kana: 'しょうにか', romaji: 'shōnika', meaning: 'khoa nhi', partOfSpeech: 'danh từ' },
      { kanji: '小切手', kana: 'こぎって', romaji: 'kogitte', meaning: 'tấm séc', partOfSpeech: 'danh từ' },
      { kanji: '小銭', kana: 'こぜに', romaji: 'kozeni', meaning: 'tiền lẻ', partOfSpeech: 'danh từ' },
      { kanji: '小柄', kana: 'こがら', romaji: 'kogara', meaning: 'nhỏ nhắn (vóc dáng)', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '少女', kana: 'おとめ', romaji: 'otome', meaning: 'thiếu nữ (cách nói văn chương)', partOfSpeech: 'danh từ' },
      { kanji: '尚更', kana: 'なおさら', romaji: 'naosara', meaning: 'càng thêm, hơn nữa', partOfSpeech: 'phó từ' },
      { kanji: '床', kana: 'とこ', romaji: 'toko', meaning: 'giường, chỗ nằm', partOfSpeech: 'danh từ' },
      { kanji: '承諾', kana: 'しょうだく', romaji: 'shōdaku', meaning: 'sự đồng ý, chấp thuận', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '招き', kana: 'まねき', romaji: 'maneki', meaning: 'lời mời', partOfSpeech: 'danh từ' },
      { kanji: '梢', kana: 'こずえ', romaji: 'kozue', meaning: 'ngọn cây', partOfSpeech: 'danh từ' },
      { kanji: '沼', kana: 'ぬま', romaji: 'numa', meaning: 'đầm lầy', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 970,
    jlptLevel: 'N1',
    words: [
      { kanji: '消去', kana: 'しょうきょ', romaji: 'shōkyo', meaning: 'sự xóa bỏ', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '焦げ茶', kana: 'こげちゃ', romaji: 'kogecha', meaning: 'màu nâu sẫm', partOfSpeech: 'danh từ' },
      { kanji: '焦ります', kana: 'あせります', romaji: 'aserimasu', meaning: 'sốt ruột, vội vàng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '照り返します', kana: 'てりかえします', romaji: 'terikaeshimasu', meaning: 'phản chiếu ánh sáng', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '称します', kana: 'しょうします', romaji: 'shōshimasu', meaning: 'tự xưng là, mạo nhận', partOfSpeech: 'động từ する' },
      { kanji: '衝撃', kana: 'しょうげき', romaji: 'shōgeki', meaning: 'cú sốc, sự va chạm', partOfSpeech: 'danh từ' },
      { kanji: '証', kana: 'あかし', romaji: 'akashi', meaning: 'bằng chứng, minh chứng', partOfSpeech: 'danh từ' },
      { kanji: '証言', kana: 'しょうげん', romaji: 'shōgen', meaning: 'lời chứng, lời khai', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '上位', kana: 'じょうい', romaji: 'jōi', meaning: 'thứ hạng cao, cấp trên', partOfSpeech: 'danh từ' },
    ],
  },
];
