// Bổ sung từ vựng N2 đợt 4 — dịch tay từ nguồn OpenJLPT (raw.githubusercontent.com/evanclan/OpenJLPT),
// đối chiếu loại bỏ trùng lặp với DB hiện có (đặc biệt các động từ đã tồn tại ở dạng ます, chỉ giữ
// động từ thực sự mới). lessonNumber 742-747.

import type { JlptVocabUnit } from './jlpt-vocab.data';

export const JLPT_VOCAB_BOOST4_N2_PART8: JlptVocabUnit[] = [
  {
    lessonNumber: 742,
    jlptLevel: 'N2',
    words: [
      { kanji: '縮みます', kana: 'ちぢみます', romaji: 'chijimimasu', meaning: 'co lại, teo lại', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '縮めます', kana: 'ちぢめます', romaji: 'chijimemasu', meaning: 'làm ngắn lại, thu nhỏ', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '縮れます', kana: 'ちぢれます', romaji: 'chijiremasu', meaning: 'bị xoăn, uốn lượn', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '縮小', kana: 'しゅくしょう', romaji: 'shukushō', meaning: 'sự thu nhỏ, cắt giảm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '熟語', kana: 'じゅくご', romaji: 'jukugo', meaning: 'thành ngữ, từ ghép', partOfSpeech: 'danh từ' },
      { kanji: '出勤', kana: 'しゅっきん', romaji: 'shukkin', meaning: 'sự đi làm', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '出迎え', kana: 'でむかえ', romaji: 'demukae', meaning: 'sự ra đón', partOfSpeech: 'danh từ' },
      { kanji: '出迎えます', kana: 'でむかえます', romaji: 'demukaemasu', meaning: 'ra đón, nghênh đón', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '出入り', kana: 'でいり', romaji: 'deiri', meaning: 'sự ra vào, thu chi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '出入口', kana: 'でいりぐち', romaji: 'deiriguchi', meaning: 'cửa ra vào', partOfSpeech: 'danh từ' },
      { kanji: '出来上がり', kana: 'できあがり', romaji: 'dekiagari', meaning: 'thành phẩm, kết quả hoàn thành', partOfSpeech: 'danh từ' },
      { kanji: '出来上がります', kana: 'できあがります', romaji: 'dekiagarimasu', meaning: 'được hoàn thành', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '述語', kana: 'じゅつご', romaji: 'jutsugo', meaning: 'vị ngữ', partOfSpeech: 'danh từ' },
      { kanji: '純情', kana: 'じゅんじょう', romaji: 'junjō', meaning: 'trong sáng, ngây thơ', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '巡ります', kana: 'めぐります', romaji: 'megurimasu', meaning: 'đi vòng quanh, chu du', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '巡査', kana: 'じゅんさ', romaji: 'junsa', meaning: 'cảnh sát tuần tra', partOfSpeech: 'danh từ' },
      { kanji: '順々', kana: 'じゅんじゅん', romaji: 'junjun', meaning: 'lần lượt theo thứ tự', partOfSpeech: 'phó từ' },
    ],
  },
  {
    lessonNumber: 743,
    jlptLevel: 'N2',
    words: [
      { kanji: '初級', kana: 'しょきゅう', romaji: 'shokyū', meaning: 'trình độ sơ cấp', partOfSpeech: 'danh từ' },
      { kanji: '初旬', kana: 'しょじゅん', romaji: 'shojun', meaning: 'thượng tuần (10 ngày đầu tháng)', partOfSpeech: 'danh từ' },
      { kanji: '所々', kana: 'ところどころ', romaji: 'tokorodokoro', meaning: 'chỗ này chỗ kia, một số chỗ', partOfSpeech: 'danh từ, phó từ' },
      { kanji: '書取', kana: 'かきとり', romaji: 'kakitori', meaning: 'bài chính tả', partOfSpeech: 'danh từ' },
      { kanji: '書籍', kana: 'しょせき', romaji: 'shoseki', meaning: 'sách vở, ấn phẩm', partOfSpeech: 'danh từ' },
      { kanji: '書店', kana: 'しょてん', romaji: 'shoten', meaning: 'hiệu sách', partOfSpeech: 'danh từ' },
      { kanji: '書道', kana: 'しょどう', romaji: 'shodō', meaning: 'thư pháp', partOfSpeech: 'danh từ' },
      { kanji: '助教授', kana: 'じょきょうじゅ', romaji: 'jokyōju', meaning: 'phó giáo sư', partOfSpeech: 'danh từ' },
      { kanji: '女の人', kana: 'おんなのひと', romaji: 'onnanohito', meaning: 'người phụ nữ', partOfSpeech: 'danh từ' },
      { kanji: '女房', kana: 'にょうぼう', romaji: 'nyōbō', meaning: 'vợ (cách gọi thân mật)', partOfSpeech: 'danh từ' },
      { kanji: '勝敗', kana: 'しょうはい', romaji: 'shōhai', meaning: 'thắng bại', partOfSpeech: 'danh từ' },
      { kanji: '勝負', kana: 'しょうぶ', romaji: 'shōbu', meaning: 'cuộc thi đấu, sự thắng thua', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '商業', kana: 'しょうぎょう', romaji: 'shōgyō', meaning: 'thương mại', partOfSpeech: 'danh từ' },
      { kanji: '商社', kana: 'しょうしゃ', romaji: 'shōsha', meaning: 'công ty thương mại', partOfSpeech: 'danh từ' },
      { kanji: '将棋', kana: 'しょうぎ', romaji: 'shōgi', meaning: 'cờ tướng Nhật (shogi)', partOfSpeech: 'danh từ' },
      { kanji: '小遣い', kana: 'こづかい', romaji: 'kozukai', meaning: 'tiền tiêu vặt', partOfSpeech: 'danh từ' },
      { kanji: '小指', kana: 'こゆび', romaji: 'koyubi', meaning: 'ngón tay út', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 744,
    jlptLevel: 'N2',
    words: [
      { kanji: '小数', kana: 'しょうすう', romaji: 'shōsū', meaning: 'số thập phân', partOfSpeech: 'danh từ' },
      { kanji: '床の間', kana: 'とこのま', romaji: 'tokonoma', meaning: 'hốc tường trang trí kiểu Nhật', partOfSpeech: 'danh từ' },
      { kanji: '承ります', kana: 'うけたまわります', romaji: 'uketamawarimasu', meaning: 'xin nghe, xin nhận (khiêm nhường)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '消化', kana: 'しょうか', romaji: 'shōka', meaning: 'sự tiêu hóa', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '消毒', kana: 'しょうどく', romaji: 'shōdoku', meaning: 'sự khử trùng', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '消防署', kana: 'しょうぼうしょ', romaji: 'shōbōsho', meaning: 'trạm cứu hỏa', partOfSpeech: 'danh từ' },
      { kanji: '消耗', kana: 'しょうもう', romaji: 'shōmō', meaning: 'sự tiêu hao, hao mòn', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '焦がします', kana: 'こがします', romaji: 'kogashimasu', meaning: 'làm cháy, làm khét', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '焦げます', kana: 'こげます', romaji: 'kogemasu', meaning: 'bị cháy khét', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '照らします', kana: 'てらします', romaji: 'terashimasu', meaning: 'chiếu sáng, soi rọi', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '照ります', kana: 'てります', romaji: 'terimasu', meaning: 'chiếu sáng (mặt trời)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '省略', kana: 'しょうりゃく', romaji: 'shōryaku', meaning: 'sự lược bỏ, tóm tắt', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '障子', kana: 'しょうじ', romaji: 'shōji', meaning: 'cửa giấy trượt kiểu Nhật', partOfSpeech: 'danh từ' },
      { kanji: '上り', kana: 'のぼり', romaji: 'nobori', meaning: 'chiều lên, tàu hướng lên trung tâm', partOfSpeech: 'danh từ' },
      { kanji: '上下', kana: 'じょうげ', romaji: 'jōge', meaning: 'trên dưới', partOfSpeech: 'danh từ' },
      { kanji: '上級', kana: 'じょうきゅう', romaji: 'jōkyū', meaning: 'trình độ cao cấp', partOfSpeech: 'danh từ' },
      { kanji: '上旬', kana: 'じょうじゅん', romaji: 'jōjun', meaning: 'thượng tuần (10 ngày đầu tháng)', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 745,
    jlptLevel: 'N2',
    words: [
      { kanji: '乗換', kana: 'のりかえ', romaji: 'norikae', meaning: 'sự chuyển tàu, đổi xe', partOfSpeech: 'danh từ' },
      { kanji: '乗車', kana: 'じょうしゃ', romaji: 'jōsha', meaning: 'sự lên xe/tàu', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '畳みます', kana: 'たたみます', romaji: 'tatamimasu', meaning: 'gấp (quần áo)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '蒸し暑い', kana: 'むしあつい', romaji: 'mushiatsui', meaning: 'oi bức, nóng ẩm', partOfSpeech: 'tính từ i' },
      { kanji: '蒸します', kana: 'むします', romaji: 'mushimasu', meaning: 'hấp; oi bức', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '蒸気', kana: 'じょうき', romaji: 'jōki', meaning: 'hơi nước', partOfSpeech: 'danh từ' },
      { kanji: '蒸発', kana: 'じょうはつ', romaji: 'jōhatsu', meaning: 'sự bốc hơi', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '飾り', kana: 'かざり', romaji: 'kazari', meaning: 'đồ trang trí', partOfSpeech: 'danh từ' },
      { kanji: '植木', kana: 'うえき', romaji: 'ueki', meaning: 'cây cảnh, cây trồng trong vườn', partOfSpeech: 'danh từ' },
      { kanji: '職人', kana: 'しょくにん', romaji: 'shokunin', meaning: 'thợ thủ công', partOfSpeech: 'danh từ' },
      { kanji: '食塩', kana: 'しょくえん', romaji: 'shokuen', meaning: 'muối ăn', partOfSpeech: 'danh từ' },
      { kanji: '食器', kana: 'しょっき', romaji: 'shokki', meaning: 'đồ dùng ăn uống, bát đĩa', partOfSpeech: 'danh từ' },
      { kanji: '侵入', kana: 'しんにゅう', romaji: 'shinnyū', meaning: 'sự xâm nhập', partOfSpeech: 'danh từ, động từ する' },
      { kanji: '唇', kana: 'くちびる', romaji: 'kuchibiru', meaning: 'môi', partOfSpeech: 'danh từ' },
      { kanji: '寝巻', kana: 'ねまき', romaji: 'nemaki', meaning: 'đồ ngủ', partOfSpeech: 'danh từ' },
      { kanji: '寝台', kana: 'しんだい', romaji: 'shindai', meaning: 'giường (trên tàu)', partOfSpeech: 'danh từ' },
      { kanji: '心身', kana: 'しんしん', romaji: 'shinshin', meaning: 'thân tâm, cả thể chất lẫn tinh thần', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 746,
    jlptLevel: 'N2',
    words: [
      { kanji: '心当たり', kana: 'こころあたり', romaji: 'kokoroatari', meaning: 'sự phỏng đoán, manh mối', partOfSpeech: 'danh từ' },
      { kanji: '心得ます', kana: 'こころえます', romaji: 'kokoroemasu', meaning: 'hiểu rõ, nắm vững', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '振舞います', kana: 'ふるまいます', romaji: 'furumaimasu', meaning: 'cư xử, đối đãi (đãi khách)', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '深まります', kana: 'ふかまります', romaji: 'fukamarimasu', meaning: 'trở nên sâu sắc hơn', partOfSpeech: 'động từ nhóm 1' },
      { kanji: '深夜', kana: 'しんや', romaji: 'shinya', meaning: 'đêm khuya', partOfSpeech: 'danh từ' },
      { kanji: '申し訳ない', kana: 'もうしわけない', romaji: 'mōshiwakenai', meaning: 'thật có lỗi, không thể biện minh', partOfSpeech: 'tính từ i' },
      { kanji: '真っ暗', kana: 'まっくら', romaji: 'makkura', meaning: 'tối om', partOfSpeech: 'tính từ na' },
      { kanji: '真っ黒', kana: 'まっくろ', romaji: 'makkuro', meaning: 'đen kịt', partOfSpeech: 'tính từ na' },
      { kanji: '真っ青', kana: 'まっさお', romaji: 'massao', meaning: 'xanh biếc; tái mét (mặt)', partOfSpeech: 'tính từ na' },
      { kanji: '真っ先', kana: 'まっさき', romaji: 'massaki', meaning: 'đầu tiên, trước hết', partOfSpeech: 'danh từ' },
      { kanji: '真っ白', kana: 'まっしろ', romaji: 'masshiro', meaning: 'trắng tinh', partOfSpeech: 'tính từ na' },
      { kanji: '真空', kana: 'しんくう', romaji: 'shinkū', meaning: 'chân không', partOfSpeech: 'danh từ' },
      { kanji: '真似ます', kana: 'まねます', romaji: 'manemasu', meaning: 'bắt chước, mô phỏng', partOfSpeech: 'động từ nhóm 2' },
      { kanji: '神様', kana: 'かみさま', romaji: 'kamisama', meaning: 'thần, Chúa', partOfSpeech: 'danh từ' },
      { kanji: '神話', kana: 'しんわ', romaji: 'shinwa', meaning: 'thần thoại', partOfSpeech: 'danh từ' },
      { kanji: '芯', kana: 'しん', romaji: 'shin', meaning: 'lõi, ruột (bút chì...)', partOfSpeech: 'danh từ' },
      { kanji: '親指', kana: 'おやゆび', romaji: 'oyayubi', meaning: 'ngón tay cái', partOfSpeech: 'danh từ' },
    ],
  },
  {
    lessonNumber: 747,
    jlptLevel: 'N2',
    words: [
      { kanji: '親類', kana: 'しんるい', romaji: 'shinrui', meaning: 'họ hàng', partOfSpeech: 'danh từ' },
      { kanji: '身分', kana: 'みぶん', romaji: 'mibun', meaning: 'địa vị xã hội, thân phận', partOfSpeech: 'danh từ' },
      { kanji: '針金', kana: 'はりがね', romaji: 'harigane', meaning: 'dây kim loại', partOfSpeech: 'danh từ' },
      { kanji: '人差指', kana: 'ひとさしゆび', romaji: 'hitosashiyubi', meaning: 'ngón trỏ', partOfSpeech: 'danh từ' },
      { kanji: '人造', kana: 'じんぞう', romaji: 'jinzō', meaning: 'nhân tạo', partOfSpeech: 'danh từ, tính từ na' },
      { kanji: '人通り', kana: 'ひとどおり', romaji: 'hitodōri', meaning: 'lượng người qua lại', partOfSpeech: 'danh từ' },
      { kanji: '人文科学', kana: 'じんぶんかがく', romaji: 'jinbunkagaku', meaning: 'khoa học nhân văn', partOfSpeech: 'danh từ' },
      { kanji: '人命', kana: 'じんめい', romaji: 'jinmei', meaning: 'tính mạng con người', partOfSpeech: 'danh từ' },
      { kanji: '塵紙', kana: 'ちりがみ', romaji: 'chirigami', meaning: 'giấy vệ sinh, giấy lau', partOfSpeech: 'danh từ' },
      { kanji: '図鑑', kana: 'ずかん', romaji: 'zukan', meaning: 'sách tranh ảnh minh họa', partOfSpeech: 'danh từ' },
      { kanji: '図形', kana: 'ずけい', romaji: 'zukei', meaning: 'hình vẽ, hình dạng', partOfSpeech: 'danh từ' },
      { kanji: '図表', kana: 'ずひょう', romaji: 'zuhyō', meaning: 'biểu đồ', partOfSpeech: 'danh từ' },
      { kanji: '吹雪', kana: 'ふぶき', romaji: 'fubuki', meaning: 'bão tuyết', partOfSpeech: 'danh từ' },
    ],
  },
];
