// Bổ sung kanji N1 — dịch tay (Hán Việt + nghĩa Việt) dựa trên dữ liệu đọc âm
// (onyomi/kunyomi) và stroke count lấy từ kanjiapi.dev (nguồn mở), không auto-scrape nghĩa tiếng Việt.
// KanjiLesson lessonNumber 841-845.

import type { JlptKanjiLesson } from './jlpt-kanji.data';

export const JLPT_KANJI_BOOST4_N1_I: JlptKanjiLesson[] = [
  {
    lessonNumber: 841,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (1)',
    sortOrder: 8410,
    entries: [
      { character: '栞', hanViet: 'KHAN', onyomi: 'かん', kunyomi: 'しおり', meaningVi: 'cái đánh dấu sách, sách hướng dẫn', strokeCount: 10 },
      { character: '洵', hanViet: 'TUÂN', onyomi: 'じゅん, しゅん', kunyomi: 'の-ぶ, まこと-に', meaningVi: 'thật vậy, quả thật', strokeCount: 9 },
      { character: '洸', hanViet: 'QUANG', onyomi: 'こう', meaningVi: 'nước lấp lánh', strokeCount: 9 },
      { character: '渥', hanViet: 'ÁC', onyomi: 'あく', kunyomi: 'あつ-い, うるお-う', meaningVi: 'ân huệ hậu hĩnh, ẩm ướt', strokeCount: 12 },
      { character: '滉', hanViet: 'HOẢNG', onyomi: 'こう', kunyomi: 'ひろ-い', meaningVi: 'nước sâu rộng', strokeCount: 13 },
      { character: '漬', hanViet: 'TÍ', onyomi: 'し', kunyomi: 'つ-ける, つ-かる, -づ-け, -づけ', meaningVi: 'ngâm, muối chua', strokeCount: 14 },
      { character: '潟', hanViet: 'TÍCH', onyomi: 'せき', kunyomi: 'かた, -がた', meaningVi: 'đầm phá', strokeCount: 15 },
      { character: '澪', hanViet: 'LINH', onyomi: 'れい', kunyomi: 'みお', meaningVi: 'luồng nước, kênh dẫn tàu', strokeCount: 16 },
      { character: '瀬', hanViet: 'LẠI', onyomi: 'らい', kunyomi: 'せ', meaningVi: 'ghềnh nước, dòng chảy xiết', strokeCount: 19 },
      { character: '熙', hanViet: 'HY', onyomi: 'き', kunyomi: 'たのし-む, ひか-る, ひろ-い, よろこ-ぶ, かわ-く, あきらか, ひろ-める, ひろ-まる', meaningVi: 'sáng sủa, thịnh vượng', strokeCount: 15 },
      { character: '燎', hanViet: 'LIỆU', onyomi: 'りょう', kunyomi: 'かがりび', meaningVi: 'đốt lửa, lửa trại', strokeCount: 16 },
      { character: '燦', hanViet: 'XÁN', onyomi: 'さん', kunyomi: 'さん-たる, あき-らか, きらめ-く, きら-めく', meaningVi: 'rực rỡ, sáng chói', strokeCount: 17 },
      { character: '燿', hanViet: 'DIỆU', onyomi: 'よう', kunyomi: 'かがや-く, ひかり', meaningVi: 'chiếu sáng', strokeCount: 18 },
      { character: '玖', hanViet: 'CỬU', onyomi: 'きゅう, く', meaningVi: 'ngọc đen đẹp; số chín', strokeCount: 7 },
      { character: '琳', hanViet: 'LÂM', onyomi: 'りん', meaningVi: 'viên ngọc', strokeCount: 12 },
      { character: '瑳', hanViet: 'THA', onyomi: 'さ', kunyomi: 'みが-く', meaningVi: 'mài giũa, sáng bóng (ngọc)', strokeCount: 14 },
      { character: '皐', hanViet: 'CAO', onyomi: 'こう', kunyomi: 'さつき', meaningVi: 'bờ đầm; tháng năm âm lịch', strokeCount: 11 },
      { character: '磯', hanViet: 'KY', onyomi: 'き', kunyomi: 'いそ', meaningVi: 'bờ biển đá', strokeCount: 17 },
      { character: '禎', hanViet: 'TRINH', onyomi: 'てい', kunyomi: 'さいわ-い', meaningVi: 'điềm lành, phúc lành', strokeCount: 13 },
      { character: '稔', hanViet: 'NHẪM', onyomi: 'ねん, じん, にん', kunyomi: 'みの-る, みのり', meaningVi: 'mùa màng bội thu, chín', strokeCount: 13 },
    ],
  },
  {
    lessonNumber: 842,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (2)',
    sortOrder: 8420,
    entries: [
      { character: '穣', hanViet: 'NHƯƠNG', onyomi: 'じょう', kunyomi: 'わら, ゆたか', meaningVi: 'mùa màng tốt, phồn vinh', strokeCount: 18 },
      { character: '竣', hanViet: 'TUẤN', onyomi: 'どう, しゅん', kunyomi: 'わらわ, わらべ, おわ-る', meaningVi: 'hoàn thành, kết thúc (công trình)', strokeCount: 12 },
      { character: '紘', hanViet: 'HOẰNG', onyomi: 'こう', kunyomi: 'おおづな, つな, つなぐ', meaningVi: 'rộng lớn, dây to buộc mũ', strokeCount: 10 },
      { character: '紬', hanViet: 'TRÙ', onyomi: 'ちゅう', kunyomi: 'つむぎ, つむ-ぐ', meaningVi: 'lụa thô dệt tay (tsumugi)', strokeCount: 11 },
      { character: '紺', hanViet: 'CÁM', onyomi: 'こん', meaningVi: 'màu xanh navy đậm', strokeCount: 11 },
      { character: '絢', hanViet: 'HUYỀN', onyomi: 'けん', meaningVi: 'hoa văn rực rỡ', strokeCount: 12 },
      { character: '繰', hanViet: 'TAO', onyomi: 'そう', kunyomi: 'く-る', meaningVi: 'cuộn lại, quay tơ, lật (trang)', strokeCount: 19 },
      { character: '耀', hanViet: 'DIỆU', onyomi: 'よう', kunyomi: 'かがや-く, ひかり', meaningVi: 'chiếu sáng lấp lánh', strokeCount: 20 },
      { character: '耶', hanViet: 'DA', onyomi: 'や, じゃ', kunyomi: 'か', meaningVi: 'trợ từ nghi vấn (cổ văn)', strokeCount: 9 },
      { character: '肇', hanViet: 'TRIỆU', onyomi: 'ちょう, じょう, とう', kunyomi: 'はじ-める, はじめ', meaningVi: 'khởi đầu', strokeCount: 14 },
      { character: '胤', hanViet: 'DẬN', onyomi: 'いん', kunyomi: 'たね', meaningVi: 'con cháu, dòng dõi', strokeCount: 9 },
      { character: '脩', hanViet: 'TU', onyomi: 'しゅう', kunyomi: 'おさ-める, なが-い, ほじし', meaningVi: 'thịt khô; dài, tu dưỡng', strokeCount: 11 },
      { character: '莞', hanViet: 'HOÀN', onyomi: 'かん', kunyomi: 'い', meaningVi: 'cói lót chiếu; cười mỉm', strokeCount: 10 },
      { character: '萩', hanViet: 'THU', onyomi: 'しゅう', kunyomi: 'はぎ', meaningVi: 'cây hagi (họ đậu)', strokeCount: 12 },
      { character: '蒔', hanViet: 'THỊ', onyomi: 'し, じ', kunyomi: 'う-える, ま-く', meaningVi: 'gieo trồng (mạ, hạt giống)', strokeCount: 13 },
      { character: '蔦', hanViet: 'ĐIỂU', onyomi: 'ちょう', kunyomi: 'つた', meaningVi: 'cây dây leo, thường xuân', strokeCount: 14 },
      { character: '蕗', hanViet: 'LỘ', onyomi: 'ろ, る', kunyomi: 'ふき', meaningVi: 'cây phong đầu (rau ăn được)', strokeCount: 16 },
      { character: '詢', hanViet: 'TUÂN', onyomi: 'じゅん, しゅん', kunyomi: 'はか-る, まこと', meaningVi: 'hỏi ý kiến, tư vấn', strokeCount: 13 },
      { character: '諄', hanViet: 'THUẦN', onyomi: 'しゅん', kunyomi: 'ひちくど-い, くど-い, くどくど, ねんご-ろ', meaningVi: 'dài dòng, tỉ mỉ, thiết tha', strokeCount: 15 },
      { character: '赳', hanViet: 'CỦ', onyomi: 'きゅう', meaningVi: 'mạnh mẽ, dũng cảm', strokeCount: 10 },
    ],
  },
  {
    lessonNumber: 843,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (3)',
    sortOrder: 8430,
    entries: [
      { character: '轄', hanViet: 'HẠT', onyomi: 'かつ', kunyomi: 'くさび', meaningVi: 'quản lý, cai quản (địa hạt)', strokeCount: 17 },
      { character: '迪', hanViet: 'ĐỊCH', onyomi: 'てき', kunyomi: 'みち, みちび-く, すす-む, いた-る', meaningVi: 'con đường, dẫn dắt', strokeCount: 8 },
      { character: '遼', hanViet: 'LIÊU', onyomi: 'りょう', meaningVi: 'xa xôi', strokeCount: 15 },
      { character: '銑', hanViet: 'TIỂN', onyomi: 'せん', meaningVi: 'gang thô (pig iron)', strokeCount: 14 },
      { character: '雛', hanViet: 'SỒ', onyomi: 'すう, す, じゅ', kunyomi: 'ひな, ひよこ', meaningVi: 'chim non, búp bê', strokeCount: 18 },
      { character: '離', hanViet: 'LY', onyomi: 'り', kunyomi: 'はな-れる, はな-す', meaningVi: 'tách rời, ly biệt', strokeCount: 19 },
      { character: '雰', hanViet: 'PHÂN', onyomi: 'ふん', meaningVi: 'sương mù, bầu không khí', strokeCount: 12 },
      { character: '需', hanViet: 'NHU', onyomi: 'じゅ', meaningVi: 'nhu cầu', strokeCount: 14 },
      { character: '霞', hanViet: 'HÀ', onyomi: 'か, げ', kunyomi: 'かすみ, かす-む', meaningVi: 'ráng mù, sương mờ', strokeCount: 17 },
      { character: '靖', hanViet: 'TĨNH', onyomi: 'せい, じょう', kunyomi: 'やす-んじる', meaningVi: 'yên bình, ổn định', strokeCount: 13 },
      { character: '鞠', hanViet: 'CÚC', onyomi: 'きく, きゅう', kunyomi: 'まり', meaningVi: 'quả bóng; nuôi dưỡng', strokeCount: 17 },
      { character: '響', hanViet: 'HƯỞNG', onyomi: 'きょう', kunyomi: 'ひび-く', meaningVi: 'âm vang, tiếng vọng', strokeCount: 20 },
      { character: '項', hanViet: 'HẠNG', onyomi: 'こう', kunyomi: 'うなじ', meaningVi: 'gáy cổ; khoản, mục', strokeCount: 12 },
      { character: '須', hanViet: 'TU', onyomi: 'す, しゅ', kunyomi: 'すべから-く, すべし, ひげ, まつ, もち-いる, もと-める', meaningVi: 'cần phải, tất yếu', strokeCount: 12 },
      { character: '頌', hanViet: 'TỤNG', onyomi: 'しょう, じゅ, よう', kunyomi: 'かたち, たた-える, ほめ-る', meaningVi: 'ca tụng, tụng ca', strokeCount: 13 },
      { character: '頑', hanViet: 'NGOAN', onyomi: 'がん', kunyomi: 'かたく-な', meaningVi: 'cứng đầu, ngoan cố', strokeCount: 13 },
      { character: '頒', hanViet: 'BAN', onyomi: 'はん', kunyomi: 'わ-かつ, わ-ける', meaningVi: 'phân phát, ban hành', strokeCount: 13 },
      { character: '顧', hanViet: 'CỐ', onyomi: 'こ', kunyomi: 'かえり-みる', meaningVi: 'nhìn lại, đoái hoài', strokeCount: 21 },
      { character: '颯', hanViet: 'TÁP', onyomi: 'さつ, そう', kunyomi: 'さっ-と', meaningVi: 'gió thổi vù vù; nhanh nhẹn', strokeCount: 14 },
      { character: '飾', hanViet: 'SỨC', onyomi: 'しょく', kunyomi: 'かざ-る, かざ-り', meaningVi: 'trang trí, trang sức', strokeCount: 13 },
    ],
  },
  {
    lessonNumber: 844,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (4)',
    sortOrder: 8440,
    entries: [
      { character: '馨', hanViet: 'HINH', onyomi: 'けい, きょう', kunyomi: 'かお-る, かおり', meaningVi: 'hương thơm bay xa', strokeCount: 20 },
      { character: '駄', hanViet: 'ĐÀ', onyomi: 'だ, た', meaningVi: 'hàng hóa chở bằng ngựa; vô ích', strokeCount: 14 },
      { character: '駒', hanViet: 'CÂU', onyomi: 'く', kunyomi: 'こま', meaningVi: 'ngựa con; quân cờ tướng', strokeCount: 15 },
      { character: '駿', hanViet: 'TUẤN', onyomi: 'しゅん, すん', kunyomi: 'すぐ-れる', meaningVi: 'ngựa tốt, nhanh', strokeCount: 17 },
      { character: '騎', hanViet: 'KỴ', onyomi: 'き', meaningVi: 'cưỡi ngựa', strokeCount: 18 },
      { character: '騒', hanViet: 'TAO', onyomi: 'そう', kunyomi: 'さわ-ぐ, うれい, さわ-がしい', meaningVi: 'ồn ào, quấy nhiễu', strokeCount: 18 },
      { character: '騰', hanViet: 'ĐẰNG', onyomi: 'とう', kunyomi: 'あが-る, のぼ-る', meaningVi: 'tăng vọt lên', strokeCount: 20 },
      { character: '驚', hanViet: 'KINH', onyomi: 'きょう', kunyomi: 'おどろ-く, おどろ-かす', meaningVi: 'kinh ngạc, sợ hãi', strokeCount: 22 },
      { character: '髄', hanViet: 'TỦY', onyomi: 'ずい', meaningVi: 'tủy, tinh túy', strokeCount: 19 },
      { character: '鬼', hanViet: 'QUỶ', onyomi: 'き', kunyomi: 'おに, おに-', meaningVi: 'ma quỷ', strokeCount: 10 },
      { character: '魁', hanViet: 'KHÔI', onyomi: 'かい', kunyomi: 'さきがけ, かしら', meaningVi: 'dẫn đầu, thủ lĩnh', strokeCount: 14 },
      { character: '魅', hanViet: 'MỊ', onyomi: 'み', meaningVi: 'quyến rũ, mê hoặc', strokeCount: 15 },
      { character: '魔', hanViet: 'MA', onyomi: 'ま', meaningVi: 'ma quỷ, yêu ma', strokeCount: 21 },
      { character: '鮎', hanViet: 'NIÊM', onyomi: 'でん, ねん', kunyomi: 'あゆ, なまず', meaningVi: 'cá hương (ayu)', strokeCount: 16 },
      { character: '鮮', hanViet: 'TIÊN', onyomi: 'せん', kunyomi: 'あざ-やか', meaningVi: 'tươi mới, rực rỡ', strokeCount: 17 },
      { character: '鯉', hanViet: 'LÝ', onyomi: 'り', kunyomi: 'こい', meaningVi: 'cá chép', strokeCount: 18 },
      { character: '鯛', hanViet: 'ĐIÊU', onyomi: 'ちょう', kunyomi: 'たい', meaningVi: 'cá tráp biển', strokeCount: 19 },
      { character: '鯨', hanViet: 'KÌNH', onyomi: 'げい', kunyomi: 'くじら', meaningVi: 'cá voi', strokeCount: 19 },
      { character: '鳩', hanViet: 'CƯU', onyomi: 'きゅう, く', kunyomi: 'はと, あつ-める', meaningVi: 'chim bồ câu', strokeCount: 13 },
      { character: '鳳', hanViet: 'PHỤNG', onyomi: 'ほう, ふう', meaningVi: 'chim phượng hoàng (đực)', strokeCount: 14 },
    ],
  },
  {
    lessonNumber: 845,
    jlptLevel: 'N1',
    title: 'Kanji N1 bổ sung (đợt 4) (5)',
    sortOrder: 8450,
    entries: [
      { character: '鴻', hanViet: 'HỒNG', onyomi: 'こう, ごう', kunyomi: 'おおとり, ひしくい, おおがり', meaningVi: 'chim hồng nhạn lớn', strokeCount: 17 },
      { character: '鵬', hanViet: 'BẰNG', onyomi: 'ほう', kunyomi: 'おおとり', meaningVi: 'chim bằng (đại bàng thần thoại)', strokeCount: 19 },
      { character: '鶏', hanViet: 'KÊ', onyomi: 'けい', kunyomi: 'にわとり, とり', meaningVi: 'gà', strokeCount: 19 },
      { character: '鶴', hanViet: 'HẠC', onyomi: 'かく', kunyomi: 'つる', meaningVi: 'chim hạc', strokeCount: 21 },
      { character: '鷹', hanViet: 'ƯNG', onyomi: 'よう, おう', kunyomi: 'たか', meaningVi: 'chim ưng', strokeCount: 24 },
      { character: '鹿', hanViet: 'LỘC', onyomi: 'ろく', kunyomi: 'しか, か', meaningVi: 'con hươu, nai', strokeCount: 11 },
      { character: '麟', hanViet: 'LÂN', onyomi: 'りん', meaningVi: 'kỳ lân', strokeCount: 24 },
      { character: '麻', hanViet: 'MA', onyomi: 'ま, まあ', kunyomi: 'あさ', meaningVi: 'cây gai dầu; tê dại', strokeCount: 11 },
      { character: '黎', hanViet: 'LÊ', onyomi: 'れい, り', kunyomi: 'くろ-い', meaningVi: 'đen; đông đảo (lê dân)', strokeCount: 15 },
      { character: '黙', hanViet: 'MẶC', onyomi: 'もく, ぼく', kunyomi: 'だま-る, もだ-す', meaningVi: 'im lặng', strokeCount: 15 },
      { character: '黛', hanViet: 'ĐẠI', onyomi: 'たい', kunyomi: 'まゆずみ', meaningVi: 'màu chì vẽ mày; mày ngài', strokeCount: 16 },
      { character: '鼓', hanViet: 'CỔ', onyomi: 'こ', kunyomi: 'つづみ', meaningVi: 'cái trống', strokeCount: 13 },
    ],
  },
];
