export type VocabSuffixSeedItem = {
  suffix: string;
  kana: string;
  romaji: string;
  meaningVi: string;
  attachesTo: string;
  exampleJa: string;
  exampleVi: string;
};

export type VocabSuffixSeedGroup = {
  slug: string;
  label: string;
  hint: string;
  items: VocabSuffixSeedItem[];
};

export const VOCAB_SUFFIX_GROUPS: VocabSuffixSeedGroup[] = [
  {
    slug: 'honorifics',
    label: 'Xưng hô',
    hint: 'Gắn sau tên người. さん là mặc định lịch sự; ちゃん thân mật; さま kính trọng hơn.',
    items: [
      {
        suffix: 'さん',
        kana: 'さん',
        romaji: 'san',
        meaningVi: 'anh/chị (lịch sự, dùng rộng)',
        attachesTo: 'tên người, nghề',
        exampleJa: '田中さん',
        exampleVi: 'anh/chị Tanaka',
      },
      {
        suffix: 'ちゃん',
        kana: 'ちゃん',
        romaji: 'chan',
        meaningVi: 'bé / thân mật',
        attachesTo: 'tên (trẻ em, bạn thân)',
        exampleJa: 'さくらちゃん',
        exampleVi: 'bé Sakura',
      },
      {
        suffix: 'くん',
        kana: 'くん',
        romaji: 'kun',
        meaningVi: 'cậu (thân, thường nam)',
        attachesTo: 'tên nam / cấp dưới',
        exampleJa: 'たけしくん',
        exampleVi: 'cậu Takeshi',
      },
      {
        suffix: 'さま / 様',
        kana: 'さま',
        romaji: 'sama',
        meaningVi: 'ngài / quý khách (kính)',
        attachesTo: 'tên, khách hàng',
        exampleJa: '神様 / お客様',
        exampleVi: 'thần / quý khách',
      },
      {
        suffix: '先生',
        kana: 'せんせい',
        romaji: 'sensei',
        meaningVi: 'thầy/cô, bác sĩ, luật sư',
        attachesTo: 'họ + nghề giáo/y',
        exampleJa: '山田先生',
        exampleVi: 'thầy/cô Yamada',
      },
      {
        suffix: '先輩',
        kana: 'せんぱい',
        romaji: 'senpai',
        meaningVi: 'đàn anh/chị (trường, công ty)',
        attachesTo: 'tên hoặc đứng riêng',
        exampleJa: '佐藤先輩',
        exampleVi: 'đàn anh/chị Sato',
      },
      {
        suffix: '氏',
        kana: 'し',
        romaji: 'shi',
        meaningVi: 'ông/bà (báo chí, trang trọng)',
        attachesTo: 'họ',
        exampleJa: '鈴木氏',
        exampleVi: 'ông/bà Suzuki',
      },
    ],
  },
  {
    slug: 'person',
    label: 'Người & nghề',
    hint: 'Tạo từ chỉ người. 人 đọc jin khi quốc tịch (ベトナム人), nin trong vài từ ghép khác.',
    items: [
      {
        suffix: '人',
        kana: 'じん',
        romaji: 'jin',
        meaningVi: 'người (quốc tịch / dân tộc)',
        attachesTo: 'tên nước, vùng',
        exampleJa: 'ベトナム人',
        exampleVi: 'người Việt',
      },
      {
        suffix: '者',
        kana: 'しゃ',
        romaji: 'sha',
        meaningVi: 'người làm / kẻ (trang trọng hơn 人)',
        attachesTo: 'danh từ, kanji nghề',
        exampleJa: '科学者',
        exampleVi: 'nhà khoa học',
      },
      {
        suffix: '家',
        kana: 'か',
        romaji: 'ka',
        meaningVi: 'nhà / chuyên gia (nghệ thuật, học thuật)',
        attachesTo: 'lĩnh vực',
        exampleJa: '画家 / 作家',
        exampleVi: 'họa sĩ / nhà văn',
      },
      {
        suffix: '員',
        kana: 'いん',
        romaji: 'in',
        meaningVi: 'nhân viên / thành viên',
        attachesTo: 'tổ chức, nghề',
        exampleJa: '会社員',
        exampleVi: 'nhân viên công ty',
      },
      {
        suffix: '師',
        kana: 'し',
        romaji: 'shi',
        meaningVi: 'thầy nghề (y, kỹ thuật)',
        attachesTo: 'chuyên môn',
        exampleJa: '医師 / 教師',
        exampleVi: 'bác sĩ / giáo viên',
      },
      {
        suffix: '士',
        kana: 'し',
        romaji: 'shi',
        meaningVi: 'sĩ (nghề có chứng chỉ)',
        attachesTo: 'chuyên môn',
        exampleJa: '弁護士 / 運転士',
        exampleVi: 'luật sư / lái tàu',
      },
      {
        suffix: '手',
        kana: 'しゅ',
        romaji: 'shu',
        meaningVi: 'người làm (thường nghề tay)',
        attachesTo: 'nghề / môn',
        exampleJa: '歌手 / 選手',
        exampleVi: 'ca sĩ / vận động viên',
      },
      {
        suffix: '屋',
        kana: 'や',
        romaji: 'ya',
        meaningVi: 'cửa hàng / người làm nghề đó',
        attachesTo: 'mặt hàng, nghề',
        exampleJa: '本屋 / 花屋',
        exampleVi: 'hiệu sách / tiệm hoa',
      },
      {
        suffix: '生',
        kana: 'せい',
        romaji: 'sei',
        meaningVi: 'học sinh / người học',
        attachesTo: 'nơi học, ngành',
        exampleJa: '学生 / 留学生',
        exampleVi: 'học sinh / du học sinh',
      },
    ],
  },
  {
    slug: 'quality',
    label: 'Tính chất',
    hint: 'Biến danh từ thành tính chất hoặc khái niệm trừu tượng. 的 ≈ “-ical”; 化 ≈ “-hóa”.',
    items: [
      {
        suffix: '的',
        kana: 'てき',
        romaji: 'teki',
        meaningVi: 'mang tính… / thuộc về…',
        attachesTo: 'danh từ',
        exampleJa: '日本的 / 科学的',
        exampleVi: 'mang tính Nhật / khoa học',
      },
      {
        suffix: '性',
        kana: 'せい',
        romaji: 'sei',
        meaningVi: 'tính chất / -ness / -ity',
        attachesTo: 'danh từ, kanji',
        exampleJa: '可能性 / 重要性',
        exampleVi: 'khả năng / tầm quan trọng',
      },
      {
        suffix: '化',
        kana: 'か',
        romaji: 'ka',
        meaningVi: 'hóa / biến thành…',
        attachesTo: 'danh từ',
        exampleJa: '国際化 / デジタル化',
        exampleVi: 'quốc tế hóa / số hóa',
      },
      {
        suffix: '力',
        kana: 'りょく',
        romaji: 'ryoku',
        meaningVi: 'lực / khả năng',
        attachesTo: 'danh từ',
        exampleJa: '能力 / 理解力',
        exampleVi: 'năng lực / sức hiểu',
      },
      {
        suffix: '度',
        kana: 'ど',
        romaji: 'do',
        meaningVi: 'độ / mức độ',
        attachesTo: 'danh từ',
        exampleJa: '温度 / 人気度',
        exampleVi: 'nhiệt độ / độ nổi tiếng',
      },
      {
        suffix: '感',
        kana: 'かん',
        romaji: 'kan',
        meaningVi: 'cảm giác / ấn tượng',
        attachesTo: 'danh từ',
        exampleJa: '安心感 / 違和感',
        exampleVi: 'cảm giác an tâm / cảm giác lệch',
      },
      {
        suffix: '風',
        kana: 'ふう',
        romaji: 'fū',
        meaningVi: 'phong cách / kiểu…',
        attachesTo: 'danh từ, tên nước',
        exampleJa: '日本風 / 西洋風',
        exampleVi: 'kiểu Nhật / kiểu Tây',
      },
      {
        suffix: 'っぽい',
        kana: 'っぽい',
        romaji: 'ppoi',
        meaningVi: 'hơi… / ra dáng… (thân mật)',
        attachesTo: 'danh từ, tính từ',
        exampleJa: '子供っぽい',
        exampleVi: 'trẻ con / hơi trẻ con',
      },
      {
        suffix: 'らしい',
        kana: 'らしい',
        romaji: 'rashii',
        meaningVi: 'đúng chất… / có vẻ…',
        attachesTo: 'danh từ',
        exampleJa: '男らしい / 雨らしい',
        exampleVi: 'đúng chất đàn ông / có vẻ mưa',
      },
    ],
  },
  {
    slug: 'time-state',
    label: 'Thời gian & trạng thái',
    hint: '中 đọc chuu = đang/trong lúc; juu = suốt. 済み = đã xong (thường sau danh từ động từ hóa).',
    items: [
      {
        suffix: '中',
        kana: 'ちゅう',
        romaji: 'chū',
        meaningVi: 'đang… / trong lúc…',
        attachesTo: 'danh từ hành động',
        exampleJa: '仕事中 / 会議中',
        exampleVi: 'đang làm việc / đang họp',
      },
      {
        suffix: '中',
        kana: 'じゅう',
        romaji: 'jū',
        meaningVi: 'suốt / toàn bộ khoảng',
        attachesTo: 'thời gian, nơi',
        exampleJa: '一日中 / 世界中',
        exampleVi: 'suốt cả ngày / khắp thế giới',
      },
      {
        suffix: '後',
        kana: 'ご',
        romaji: 'go',
        meaningVi: 'sau…',
        attachesTo: 'danh từ sự kiện',
        exampleJa: '食事後 / 授業後',
        exampleVi: 'sau bữa ăn / sau giờ học',
      },
      {
        suffix: '前',
        kana: 'まえ',
        romaji: 'mae',
        meaningVi: 'trước…',
        attachesTo: 'danh từ thời gian/sự kiện',
        exampleJa: '食事前 / 三年前',
        exampleVi: 'trước bữa ăn / 3 năm trước',
      },
      {
        suffix: '済み',
        kana: 'ずみ',
        romaji: 'zumi',
        meaningVi: 'đã xong / đã hoàn tất',
        attachesTo: 'danh từ hành động',
        exampleJa: '予約済み / 支払い済み',
        exampleVi: 'đã đặt chỗ / đã thanh toán',
      },
      {
        suffix: '以来',
        kana: 'いらい',
        romaji: 'irai',
        meaningVi: 'từ… đến nay',
        attachesTo: 'danh từ thời điểm',
        exampleJa: '卒業以来',
        exampleVi: 'từ khi tốt nghiệp đến nay',
      },
    ],
  },
  {
    slug: 'plural',
    label: 'Số nhiều',
    hint: 'Tiếng Nhật không bắt buộc số nhiều. たち thân mật; がた kính; ら hơi lạnh/văn viết.',
    items: [
      {
        suffix: 'たち',
        kana: 'たち',
        romaji: 'tachi',
        meaningVi: 'các… (nhóm người)',
        attachesTo: 'đại từ, người',
        exampleJa: '私たち / 子供たち',
        exampleVi: 'chúng tôi / bọn trẻ',
      },
      {
        suffix: 'ら',
        kana: 'ら',
        romaji: 'ra',
        meaningVi: 'bọn / các (ngắn, đôi khi lạnh)',
        attachesTo: 'đại từ',
        exampleJa: '彼ら / これら',
        exampleVi: 'họ (nam) / những cái này',
      },
      {
        suffix: 'がた',
        kana: 'がた',
        romaji: 'gata',
        meaningVi: 'các vị (kính ngữ)',
        attachesTo: 'người được kính',
        exampleJa: '先生がた / あなたがた',
        exampleVi: 'các thầy cô / quý vị',
      },
      {
        suffix: 'ども',
        kana: 'ども',
        romaji: 'domo',
        meaningVi: 'bọn (khiêm hoặc thô)',
        attachesTo: 'わたし, người',
        exampleJa: '私ども',
        exampleVi: 'chúng tôi (khiêm nhường)',
      },
    ],
  },
  {
    slug: 'verb-adj',
    label: 'Sau động từ / tính từ',
    hint: 'Gắn vào gốc ます (連用形). やすい = dễ; にくい = khó; すぎる = quá mức.',
    items: [
      {
        suffix: 'やすい',
        kana: 'やすい',
        romaji: 'yasui',
        meaningVi: 'dễ…',
        attachesTo: 'gốc ます của động từ',
        exampleJa: '分かりやすい / 使いやすい',
        exampleVi: 'dễ hiểu / dễ dùng',
      },
      {
        suffix: 'にくい',
        kana: 'にくい',
        romaji: 'nikui',
        meaningVi: 'khó…',
        attachesTo: 'gốc ます của động từ',
        exampleJa: '分かりにくい / 読みにくい',
        exampleVi: 'khó hiểu / khó đọc',
      },
      {
        suffix: 'すぎる',
        kana: 'すぎる',
        romaji: 'sugiru',
        meaningVi: 'quá…',
        attachesTo: 'gốc ます / gốc tính từ',
        exampleJa: '食べすぎる / 高すぎる',
        exampleVi: 'ăn quá nhiều / đắt quá',
      },
      {
        suffix: 'がたい',
        kana: 'がたい',
        romaji: 'gatai',
        meaningVi: 'khó… (trang trọng, cảm xúc)',
        attachesTo: 'gốc ます',
        exampleJa: '信じがたい',
        exampleVi: 'khó tin',
      },
      {
        suffix: 'そう',
        kana: 'そう',
        romaji: 'sō',
        meaningVi: 'trông có vẻ…',
        attachesTo: 'gốc ます / gốc tính từ',
        exampleJa: '美味しそう / 降りそう',
        exampleVi: 'trông ngon / có vẻ sắp mưa',
      },
      {
        suffix: 'みたい',
        kana: 'みたい',
        romaji: 'mitai',
        meaningVi: 'giống như… (thân mật)',
        attachesTo: 'danh từ, câu',
        exampleJa: '子供みたい',
        exampleVi: 'như trẻ con',
      },
    ],
  },
  {
    slug: 'place-purpose',
    label: 'Nơi, mục đích, xuất xứ',
    hint: '向け = dành cho đối tượng; 用 = dùng cho việc; 製 = sản xuất tại; 語 = ngôn ngữ.',
    items: [
      {
        suffix: '向け',
        kana: 'むけ',
        romaji: 'muke',
        meaningVi: 'dành cho…',
        attachesTo: 'đối tượng',
        exampleJa: '初心者向け / 子供向け',
        exampleVi: 'dành cho người mới / cho trẻ',
      },
      {
        suffix: '用',
        kana: 'よう',
        romaji: 'yō',
        meaningVi: 'dùng cho…',
        attachesTo: 'mục đích',
        exampleJa: '家庭用 / 学習用',
        exampleVi: 'dùng trong gia đình / để học',
      },
      {
        suffix: '製',
        kana: 'せい',
        romaji: 'sei',
        meaningVi: 'sản xuất tại / làm bằng',
        attachesTo: 'nước, chất liệu',
        exampleJa: '日本製 / 木製',
        exampleVi: 'sản xuất tại Nhật / làm bằng gỗ',
      },
      {
        suffix: '産',
        kana: 'さん',
        romaji: 'san',
        meaningVi: 'sản phẩm từ (nông sản, đặc sản)',
        attachesTo: 'nơi sản xuất',
        exampleJa: '国産 / 北海道産',
        exampleVi: 'nội địa / sản xuất Hokkaido',
      },
      {
        suffix: '側',
        kana: 'がわ',
        romaji: 'gawa',
        meaningVi: 'phía / bên',
        attachesTo: 'danh từ',
        exampleJa: '右側 / 会社側',
        exampleVi: 'bên phải / phía công ty',
      },
      {
        suffix: '語',
        kana: 'ご',
        romaji: 'go',
        meaningVi: 'ngôn ngữ',
        attachesTo: 'tên nước, lĩnh vực',
        exampleJa: '日本語 / 英語',
        exampleVi: 'tiếng Nhật / tiếng Anh',
      },
      {
        suffix: '式',
        kana: 'しき',
        romaji: 'shiki',
        meaningVi: 'kiểu / lễ / phương thức',
        attachesTo: 'danh từ',
        exampleJa: '日本式 / 結婚式',
        exampleVi: 'kiểu Nhật / lễ cưới',
      },
    ],
  },
  {
    slug: 'money',
    label: 'Phí & tiền',
    hint: '料 thường là lệ phí dịch vụ; 費 là chi phí; 代 là tiền trả cho thứ đó.',
    items: [
      {
        suffix: '料',
        kana: 'りょう',
        romaji: 'ryō',
        meaningVi: 'lệ phí / phí dịch vụ',
        attachesTo: 'dịch vụ',
        exampleJa: '入場料 / 手数料',
        exampleVi: 'phí vào cửa / phí thủ tục',
      },
      {
        suffix: '費',
        kana: 'ひ',
        romaji: 'hi',
        meaningVi: 'chi phí',
        attachesTo: 'hạng mục',
        exampleJa: '生活費 / 交通費',
        exampleVi: 'chi phí sinh hoạt / đi lại',
      },
      {
        suffix: '金',
        kana: 'きん',
        romaji: 'kin',
        meaningVi: 'tiền (khoản tiền)',
        attachesTo: 'loại khoản',
        exampleJa: '奨学金 / 罰金',
        exampleVi: 'học bổng / tiền phạt',
      },
      {
        suffix: '代',
        kana: 'だい',
        romaji: 'dai',
        meaningVi: 'tiền… / thế cho…',
        attachesTo: 'thứ phải trả',
        exampleJa: 'コーヒー代 / 家賃',
        exampleVi: 'tiền cà phê / tiền nhà',
      },
    ],
  },
];
